### ISSUE TITLE
How to share data between routes ?

### ISSUE THREAD

**Issue by antigol** [SergioBenitez/Rocket#100]
I want to use a database and I think I have to share the database client object between my routes.

```
#[get("/data")]
fn load_from_database() -> redis::RedisResult<String> {
    let con = try!(client.get_connection());
    try!(con.get("mydata"))
}

fn main() {
    let client = redis::Client::open("redis://127.0.0.1/").unwrap();

    // How to pass client to my function load_from_database ?

    rocket::ignite().mount("/", routes![load_from_database]).launch();
}
```

**Comment by FliegendeWurst** [comment]
[Request guards](https://rocket.rs/guide/requests/#request-guards) would do the trick. See [#53](https://github.com/SergioBenitez/Rocket/issues/53#issuecomment-269460216) for an example.

**Comment by SergioBenitez** [comment]
There's a simple solution to this coming very soon. But we'll keep tracking this in #53.
