### ISSUE TITLE
Use `std::net::SocketAddr` instead of address (`String`) and port (`u16`) in config

### ISSUE THREAD

**Issue by jhpratt** [SergioBenitez/Rocket#1000]
Is there any particular reason why this isn't being used currently? [`SocketAddr`](https://doc.rust-lang.org/std/net/enum.SocketAddr.html) has been stable since 1.0.0, and allows for parsing/stringifying both IPv4 and IPv6 addresses (including ports). As a bonus, this would slightly reduce the amount of work on Rocket's side, since you wouldn't need to parse it yourself.

Needless to say this would be a breaking change, so 0.5 at the minimum.

**Comment by jebrosen** [comment]
#594 also changes address configuration, but in a very different way. I think it's at least worth considering `SocketAddr` and documenting why we do/don't use it, especially for a hyper 0.12 migration which would change a lot of the low level connection code anyway.

I do like the convenience of `ROCKET_PORT=8080`, and it might be tricky to support both ideas.

**Comment by jhpratt** [comment]
With regard to `ROCKET_PORT`, there is a `SocketAddr::set_port` that takes a `u16`. It could certainly be documented that environment variables override the inline configuration.

The changeover to hyper 0.12 is a good point, a large portion will likely have to be modified regardless.

**Comment by SergioBenitez** [comment]
Let's handle this in #17.
