### ISSUE TITLE
Unable to compile and run the example in Quickstart guide

### ISSUE THREAD

**Issue by CorruptComputer** [SergioBenitez/Rocket#1001]
## Bug Reports

Bug reports _must_ include:

  1. The version of Rocket you're using. Ensure it's the latest, if possible.
      0.4.1

  2. The operating system (distribution and version) where the issue occurs.
      Manjaro Linux

  3. A brief description of the bug that includes:
    Unable to compile example/hello_world:
```
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error
```

  4. How you uncovered the bug. Short, reproducible tests are especially useful.
      Following the steps here: https://rocket.rs/v0.4/guide/quickstart/

  5. Ideas, if any, about what Rocket is doing incorrectly.
      Looks like a file is missing somewhere?

**Comment by jebrosen** [comment]
You will also need to install a C compiler (`cc`), usually `gcc` or `clang` depending on your operating system. I suspect it's the [`cc` crate](https://github.com/alexcrichton/cc-rs) that ends up showing that warning -- that would be the project to coordinate with to improve the warning message.

**Comment by CorruptComputer** [comment]
@jebrosen I have GCC and G++ installed, and they seem to be working fine on my system. Are you sure there is nothing missing from the project? The error seems to be pointing at a file being missing here.

**Comment by jebrosen** [comment]
That is the same error message verbatim that I get once I uninstall `gcc`. What operating system are you using? You may need to configure `gcc` as the default C compiler depending on how everything is packaged.

**Comment by CorruptComputer** [comment]
I am using Manjaro Linux.

**Comment by jebrosen** [comment]
If Manjaro hasn't deviated from Arch in this regard, the `gcc` package provides the `cc` command as an alias for `gcc`. What output do you get from `command -V cc`?

**Comment by CorruptComputer** [comment]
Looks like that didn't exist on my system, after adding an alias from cc to gcc it looks like the error has changed. Now it looks like this:

```
error[E0554]: #![feature] may not be used on the stable release channel
 --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/pear_codegen-0.1.2/src/lib.rs:1:1
  |
1 | #![feature(crate_visibility_modifier)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
 --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/pear_codegen-0.1.2/src/lib.rs:2:1
  |
2 | #![feature(proc_macro_diagnostic, proc_macro_span)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
 --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/devise_core-0.2.0/src/lib.rs:1:1
  |
1 | #![feature(proc_macro_diagnostic, proc_macro_span)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
 --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/devise_core-0.2.0/src/lib.rs:2:1
  |
2 | #![feature(crate_visibility_modifier)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
 --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/devise_core-0.2.0/src/lib.rs:3:1
  |
3 | #![feature(concat_idents)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0554`.
The following warnings were emitted during compilation:

warning: Pear was unable to check rustc compatibility.
warning: Build may fail due to incompatible rustc version.

error: Could not compile `pear_codegen`.
warning: build failed, waiting for other jobs to finish...
error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `devise_core`.

To learn more, run the command again with --verbose.

```

**Comment by jebrosen** [comment]
Yes, this is covered in the guide:

> Before you can start writing a Rocket application, you'll need a **nightly** version of Rust installed.

Working on a stable version of rust is tracked in issue #19.

**Comment by CorruptComputer** [comment]
Ah that seems to have fixed it, thanks!
