### ISSUE TITLE
How to use form with databse?

### ISSUE THREAD

**Issue by HonzsSedlomn** [SergioBenitez/Rocket#1006]
Hello, Is there any way to use database instance inside of struct with `FromForm` trait?
I'm a beginner in Rust so I have no idea, how can I do that.

Consider this example

```rust
#[derive(FromForm, Debug)]
pub struct SignupForm {
  full_name: String,
  username: Result<UniqueUsername, &'static str>,
  email: String,
  password: Result<HashedPassword, &'static str>,
}

#[derive(Debug)]
struct UniqueUsername(String);

impl<'a> FromFormValue<'a> for UniqueUsername {
  type Error = &'static str;

  fn from_form_value(v: &'a RawStr) -> Result<Self, Self::Error> {
    // Here I would like to make a db call and find existing username
  }
}
```

Could you give me a hint please?

**Comment by jebrosen** [comment]
This can't currently be done directly through `FromFormValue`, and I also feel like it probably shouldn't be allowed. I might be convinced that manual implementations of `FromForm` should get access to the `Request` (including state such as databases), though.

The easiest way to deal with this today is to have `username` and `password` be `String`s, and validate or process them within the route.

**Comment by HonzsSedlomn** [comment]
That's exactly what I needed to know, thank you. I was thinking whether it's right to do this in form struct.
