### ISSUE TITLE
Multiple value query param in 0.4?

### ISSUE THREAD

**Issue by leeola** [SergioBenitez/Rocket#1007]
After doing some digging, it seems that query params with multiple values are being reworked for 0.5.0 (#621, #205, #608), however I'm unclear as to the level of support, if any, 0.4 has for this feature.

My goal would be to communicate a `Vec<u8>` over a query string in 0.4. The discussion in #621 makes me question if this is even possible in 0.4, so I'm just seeking confirmation before I implement a hacky workaround like `?foo=1,2,3,4`.

Appreciate any replies. Thanks :)

**Comment by tronta** [comment]
I guess one has to wait til 0.5: https://github.com/SergioBenitez/Rocket/issues/205

**Comment by SergioBenitez** [comment]
Yes, this is #205. Closing as a duplicate.

**Comment by leeola** [comment]
Yea, to be clear I was just asking if it was possible. So, I'm taking that as no, Rocket 0.4 cannot, in any way, support multi value arguments.

**Comment by SergioBenitez** [comment]
@leeola Not out of the box, but it's rather straightforward to implement this behavior through [`FromFormValue`](https://api.rocket.rs/v0.4/rocket/request/trait.FromFormValue.html). In particular, you'd define a new type, say `Sequence<T>` and implement `FromFormValue` for said type.
