### ISSUE TITLE
Cookies never contain private cookies?

### ISSUE THREAD

**Issue by hamaluik** [SergioBenitez/Rocket#1015]
I'm trying to get private cookies to work, but for the life of me I just can't. My code works fine when I use non-private cookies, but as soon as I change the methods to `_private`, I can no longer get any cookies (`set_private` seems to work just fine). I'm using Rocket and Rocket Contrib 0.4:

```toml
rocket = { version = "^0.4", default-features = false, features = ["private-cookies"] }
rocket_contrib = { version = "^0.4", default-features = false, features = ["helmet", "diesel_sqlite_pool", "json"]}
```

I set a private cookie like so:

```rust
cookies.add_private(
    Cookie::new("user", user_context.to_string())
);
```

And can verify in the browser that it got set:

```json
{
    "user": {
        "value": "W8V3yJ85yvwmUAjM8JL+hYvj5o1RGCf4tdjkqtLl2cLsHVuHhBkHScfS7TSkcN2gCL3RVxpp+ru4s8RBLMa2stg8rJxnr4NFFCizCRtvHmVhKjSZmWDhHtIx6FwdxMsZy2uW53fmW9gADXiOwRxmHuSwQP9LW7nQ6ai45469+pz4kiArlGVvVIg9H%2Fi8pxrWfxl191VRfgdbQ3gYaHXC27PWA94Gv+76EID0NTPR01MfxsbiHpUWURLhcV3uTG06T6VNAWdD6xQBmPxnqb6cPa6ds%2FlngTMG26OnUq7GnNYiLyXzN7Wj+VFjbOTWDCKJWg%3D%3D",
        "domain": "localhost",
        "path": "/",
        "expires": "Sun, 02 Jun 2019 14:52:16 GMT",
        "accessed": "Sun, 26 May 2019 15:11:22 GMT",
        "HttpOnly": true,
        "sameSite": "Strict"
    }
}
```

However whenever I try to read it, Rocket doesn't seem to think it exists:

```rust
#[get("/")]
fn auth(mut cookies: Cookies, config: State<Config>) -> Redirect {
    if cookies.get_private("user").is_some() { // cookies.get_private("user") is always `None`??
        return Redirect::to("/");
    }

    Redirect::to(
        format!(
            "https://{}/authorize?response_type=code&scope=openid%20email%20profile&client_id={}&redirect_uri={}/auth/callback",
            config.auth_domain,
            config.auth_client_id,
            config.webroot
        )
    )
}
```

or:

```rust
impl<'a, 'r> FromRequest<'a, 'r> for UserContext {
    type Error = &'static str;

    fn from_request(request: &'a Request<'r>) -> request::Outcome<Self, Self::Error> {
        eprintln!("attempting to build user from request..");
        eprintln!("cookies:");
        for c in request.cookies().iter() {
            println!("Name: '{}', Value: '{}'", c.name(), c.value());
        }
        eprintln!("end cookies");
        
        let result = request
            .cookies()
            .get_private("user")
            .map_or(Outcome::Forward(()), |cookie| {
                eprintln!("checking private user cookie: {:?}", cookie.value());
                use std::str::FromStr;
                match UserContext::from_str(cookie.value()) {
                    Ok(uc) => {
                        eprintln!("is valid context: {:?}", uc);
                        Outcome::Success(uc)
                    },
                    Err(e) => {
                        eprintln!("is not valid context: {:?}", e);
                        Outcome::Failure((Status::Unauthorized, "unable to parse user cookie!"))
                    }
                }
            });
        
        eprintln!("result: {:?}", result);
        result
    }
}

#[get("/")]
fn auth_already_signed_in(user: UserContext) -> Redirect {
    eprintln!("user: {:?}", user);
    Redirect::to("/")
}

#[get("/", rank = 2)]
fn auth_not_signed_in(config: State<Config>) -> Redirect {
    Redirect::to(
        format!(
            "https://{}/authorize?response_type=code&scope=openid%20email%20profile&client_id={}&redirect_uri={}/auth/callback",
            config.auth_domain,
            config.auth_client_id,
            config.webroot
        )
    )
}
```

results in:

```
GET /auth text/html:
    => Matched: GET /auth (auth_already_signed_in)
attempting to build user from request..
cookies:
end cookies
result: Outcome::Forward
    => Outcome: Forward
    => Matched: GET /auth [2] (auth_not_signed_in)
    => Outcome: Success
    => Response succeeded.
```

Indicating that the private cookie `user` is invisible to Rocket for some reason.

When I run the [session example](https://github.com/SergioBenitez/Rocket/tree/master/examples/session) everything runs as expected, but I can't figure out why it's not working in my actual application.

I've tried setting the secret key both in `Rocket.toml` and as an environment variable, but it doesn't make a difference.

Any ideas about what I might be doing wrong?

**Comment by jebrosen** [comment]
Would it be possible to reduce this to a self-contained but minimal example? I see that the posted code and the code that generated the log output are not quite the same which might make troubleshooting this harder.

The [default flags set on private cookies](https://api.rocket.rs/v0.4/rocket/http/enum.Cookies.html#method.add_private), in particular `SameSite`, have been known to cause issues with certain combinations of redirects especially if they go between HTTP vs HTTPS. If you navigate manually to the target page directly, you will likely see that the cookie is actually working fine.

**Comment by hamaluik** [comment]
Ok, you're right—when I navigate directly to the target page, the cookies are picked up. However they don't work on the redirect (which is kind of a problem when I'm trying to sign in using them). I did make a test repo for this (https://github.com/hamaluik/rocket-private-cookies-test) but am completely unable to replicate the issue there, only on my actual application.

Any idea on how to get cookies working with redirect? I would rather leave the `SameSite` flag on for security purposes, but is that the only way to fix it?

**Comment by jebrosen** [comment]
I *think* the problem comes in somewhere in:

http://localhost/goto_auth -> **https**://authentication.domain -> **http**://localhost/auth_process -> http://localhost/after_auth

That is, you have the same problem as described in https://github.com/SergioBenitez/Rocket/issues/567#issuecomment-367399253. You could try setting `SameSite` to `Lax` on the cookie after evaluating the risk of doing so, or you could also try using https on `localhost` or on a staging site to see if it will already work as intended in production.

**Comment by hamaluik** [comment]
Yup, that's basically what I'm experiencing—except in Firefox instead of Chrome. I'll go lax for now, thanks for all the help!
