### ISSUE TITLE
Expose HTTP Version, Server Name, Server Port, URL Scheme on Request

### ISSUE THREAD

**Issue by lopopolo** [SergioBenitez/Rocket#1019]
Thank you for this library. I find it a joy to use, which is why I am trying to leverage it in [ferrocarril](https://github.com/lopopolo/ferrocarril).

## Feature Requests

I am building a [Rack](https://github.com/rack/rack)-compatible Ruby web application server with Rocket similar to [Thin](https://github.com/macournoyer/thin). Rack is a set of HTTP building blocks. It defines an [environment](https://www.rubydoc.info/github/rack/rack/file/SPEC#label-The+Environment) which is a `Hash` containing information about the incoming HTTP request (see https://github.com/lopopolo/ferrocarril/issues/61).

One item in the Hash is the HTTP version. I found GH-38 which discusses exposing the HTTP Version from Hyper, but decided not to do so because there wasn't a compelling reason to expand the API surface area. I hope this is the compelling reason :wink:.

Rocket provides high-level HTTP building blocks that I would like to use instead of dropping down to Hyper, but building frameworks with Rocket in this case requires knowing the internal details of the HTTP request.

The other data I need to fill out the Rack environment that I'm unclear how to access includes:

- server name
- server port
- url scheme (http vs https)

This feature needs to exist inside of Rocket because Rocket is hiding this information from the underlying Hyper request.

The right answer here might be that I need to use Hyper directly, and if that is the case I'm happy to do so. Thanks again! 😄

**Comment by jebrosen** [comment]
This is a very interesting use of Rocket! I plan to take a closer look at the project later, but for now I'll tell you what I can.

> * HTTP version

I don't see this listed in https://www.rubydoc.info/github/rack/rack/file/SPEC#label-The+Environment or the linked RFC. I see `HTTP_` for HTTP headers, but the HTTP version isn't in a header.

We *could* add a `request.version()` method to the API, but I don't see the utility. What nontrivial things can a request do differently depending on the HTTP version?

> * server name
> * server port
> * url scheme

Rocket doesn't exactly know a "server name". It does know a "server address" which can be specified as a name, along with a port and whether TLS is enabled or not. This is all accessible in the [`Config`](https://api.rocket.rs/v0.4/rocket/struct.Config.html), which for example an `on_launch` fairing has access to.

One problem I can see with using these, though, is public vs private server names/ports. It's common to put a Rocket application behind a proxy, so Rocket will see "http://" "127.0.0.1" and "8000" but be publicly accessible at "https://example.com/" on port 443. I don't know which one you need to expose, but I wanted to put that out there.

> The right answer here might be that I need to use Hyper directly, and if that is the case I'm happy to do so. Thanks again! 😄

You might end up wanting more fine-grained control of connection management or execution, in which case hyper may be more suitable for your project. But ultimately that is your call based on need, which I don't know well enough yet to have an opinion on. Good luck!

**Comment by lopopolo** [comment]
Hi @jebrosen it appears I was mistaken that HTTP version is part of the spec. After looking around the webrick and thin handlers + servers, it appears the `HTTP_VERSION` part of the environment is used for things like keep alive handling, which I would not need to worry about because Rocket is taking care of those bits.

When the spec says "server name", I think that is the same as when you say "server address" -- the bind address.

Rack apps (or middleware) are expected to handle things like X-Forwarded-For, X-Forwarded-Proto, and X-Real-IP headers.

Thanks for the pointer about the fairings. It looks like an `on_launch` fairing + managed state to store the config will move me in the right direction. It also seems like the fairing will allow me to modify things like the port and bind address that Rocket uses.

Thanks for your help and for Rocket. I'm going to close this issue because I don't need the HTTP version and can get at the other bits of the environment with a combination of a fairing and request guard.

Thank you! 💪
