### ISSUE TITLE
How to access absolute URI from request

### ISSUE THREAD

**Issue by vector623** [SergioBenitez/Rocket#1021]
I'm on rocket 0.4.1 and I'm trying to write a podcast server. I need to publish an xml document with links which include the scheme (http/https). I'll be running this behind a nginx as a reverse proxy. Is it possible to get the request scheme in the handler?

I've gone through the site docs, examples and issues but I'm not sure how to get the request scheme or if it's possible. If it's doable, maybe this could be added to the tera template example.

**Comment by jebrosen** [comment]
It is possible through the [`Config`](https://api.rocket.rs/v0.4/rocket/struct.Config.html) to tell whether or not TLS is enabled and the listening address and port, but that only applies to Rocket itself and won't necessarily match the externally accessible URI.

The host is in the `Host` header, but you may have to configure nginx to pass it along if it doesn't already. Port number and scheme are not part of the request data, so you would have to come up with another way to communicate those - either a custom header or other mechanism.

Alternatively, your server could have a configurable value such as "base path" that externally-facing absolute URIs are built from.

**Comment by vector623** [comment]
So then, if x-forwarded-proto header or config is set to HTTPS/TLS, then scheme is https; otherwise http.

Does that sound about right?

**Comment by jebrosen** [comment]
If that header is set then that may work. As with `Host`, I don't know if nginx passes that by default or not.

**Comment by vector623** [comment]
That answers my question, thanks for the help!
