### ISSUE TITLE
Incorrect implementation: the trait `rocket::response::Responder<'_>` is not implemented for `std::result::Result<rocket_contrib::json::Json<std::vec::Vec<user_module::Users>>, rocket::http::Status>

### ISSUE THREAD

**Issue by JayHelton** [SergioBenitez/Rocket#1022]
## Bug Reports

Bug reports _must_ include:

  1. The version of Rocket you're using: *0.4.1*

  2. The operating system: *MacOs Mojave*

  3. A brief description of the bug:
When trying to return a response using `std::Result<T, E>`, I received the following error:
````the trait `rocket::response::Responder<'_>` is not implemented for `std::result::Result<rocket_contrib::json::Json<std::vec::Vec<user_module::Users>>, rocket::http::Status>````

I am assuming this is not an actual bug, and just confusion on my part after reading the docs. I had thought that the ```std::Result``` did implement the Responder correctly, as well as ```rocket::httpStatus```.

I am using Diesel as an ORM.

Here is the following code block that errors.

```
use diesel::result::Error;
use rocket::http::Status;
use rocket_contrib::json::Json;

use crate::connection::DbConn;
use crate::user_module;
use crate::user_module::Users;

#[get("/test")]
pub fn test() -> Json<&'static str> {
    Json("hello world")
}

/// line 16 errors
#[get("/")]
pub fn all(connection: DbConn) -> Result<Json<Vec<Users>>, Status> {
    user_module::repository::all(&connection)
        .map(|users| Json(users))
        .map_err(|error| error_status(error))
}

fn error_status(error: Error) -> Status {
    match error {
        Error::NotFound => Status::NotFound,
        _ => Status::InternalServerError
    }
}

```

Here is my Users model implementation:

```
#![allow(proc_macro_derive_resolution_fallback)]

use chrono::NaiveDateTime;
pub mod handler;
pub mod router;
pub mod repository;


#[derive(Queryable, Deserialize)]
pub struct Users {
    pub id: i32,
    pub auth0_identifier: String,
    pub first_name: String,
    pub last_name: String,
    pub bio: Option<String>,
    pub created_on: NaiveDateTime,
    pub last_login: Option<NaiveDateTime>,
    pub profile_picture: Option<String>,
}

```

Here is my repository method:
```
use diesel;
use diesel::prelude::*;

use crate::schema::users;
use crate::user_module::Users;

pub fn all(connection: &PgConnection) -> QueryResult<Vec<Users>> {
    users::table.load::<Users>(&*connection)
}

```

Here is a more in depth error description:

```
error[E0277]: the trait bound `std::result::Result<rocket_contrib::json::Json<std::vec::Vec<user_module::Users>>, rocket::http::Status>: rocket::response::Responder<'_>` is not satisfied
  --> src/user_module/handler.rs:14:1
   |
14 | #[get("/")]
   | ^^^^^^^^^^^ the trait `rocket::response::Responder<'_>` is not implemented for `std::result::Result<rocket_contrib::json::Json<std::vec::Vec<user_module::Users>>, rocket::http::Status>`
   |
   = help: the following implementations were found:
             <std::result::Result<R, E> as rocket::response::Responder<'r>>
             <std::result::Result<R, E> as rocket::response::Responder<'r>>
   = note: required by `rocket::handler::<impl rocket::Outcome<rocket::Response<'r>, rocket::http::Status, rocket::Data>>::from`

error: aborting due to previous error

```

I am loving this framework, so thank you all for your hard work.

**Comment by jebrosen** [comment]
The problem is actually that `Serialize` is not implemented for `Users`: https://api.rocket.rs/v0.4/rocket_contrib/json/struct.Json.html#sending-json

I think if you had tried to return `-> Json<Vec<Users>>`, the error message would say that. The implementation of `Responder` for `Result` uses the unstable specialization feature, which has the side effect of making the error message less helpful.

**Comment by JayHelton** [comment]
@jebrosen WOW, I apologize for missing that. Thank you very much!

**Comment by savovs** [comment]
I wish the error was more descriptive, there's now way I would have figured out what to do on my own.

**Comment by jebrosen** [comment]
In that example the requirements on `diesel::result::Error` are arrived at in very different ways:

* `Json<Result<Vec<Post>, diesel::result::Error>>: Responder`
  * requires `Result<Vec<Post>, diesel::result::Error>: Serialize`
    * requires `Vec<Post>: Serialize` and `diesel::Result::Error: Serialize`.

* `Result<Json<Vec<Post>>, diesel::result::Error>`
  * requires either:
    * `Json<Vec<Post>>: Responder` and `diesel::result::Error: Debug`
    * OR: `Json<Vec<Post>>: Responder` and `diesel::result::Error: Debug + Responder`
    * This choice of two bounds is only possible because `impl Responder for Result` uses the specialization feature, and I believe that's why the error message is incomplete. If `impl Responder for Result` was not specialized and required just one of `Debug` or `Responder`, I'm pretty sure the error message would say `` `diesel::result::Error: Debug` is not satisfied`` as expected.

**Comment by huangjj27** [comment]
but why I get similar error even if I derive `Serialize` for both `Ok` and `Err`?
```rust
use rocket::post;
use rocket::response::status;
use rocket::http::Status;
use rocket_contrib::json::Json;
use serde::{ Serialize, Deserialize };

#[derive(Deserialize)]
pub(crate) struct PostUser {
    phone: String,
    password: String,
}

#[derive(Serialize)]
pub(crate) struct NewUser {
    uid: u64,
    phone: String,
}


#[derive(Serialize)]
pub(crate) struct ErrRegistered {
    err: &'static str,
    phone: String,
}

#[post("/users", data = "<user>")]
pub(crate) fn create(user: Json<PostUser>)
    -> Result<status::Created<Json<NewUser>>, status::Custom<Json<ErrRegistered>>> {
    let PostUser { phone, password } = user.deref();

    if let Some(_uid) = find_registered(&phone) {
        let err = Json(ErrRegistered {
            err: "PHONE_NUMBER_RIGISTERED",
            phone: phone.to_string(),
        });

        return Err(status::Custom(Status::Conflict, err));
    }

    let uid = register(&phone, &password).expect("Register failed!");

    let new_user = Json(NewUser {
        uid,
        phone: phone.to_string(),
    });
    let uri = format!("/users/{}", uid).to_string();

    Ok(status::Created(uri, Some(new_user)))
}

fn find_registered(p: &str) -> Option<u64> {
    Some(10086)
}

fn register(phone: &str, pass: &str) -> Result<u64, ()> {
    Ok(10086)
}
```

Here is the Error:
```
error[E0277]: the trait bound `std::result::Result<rocket::response::status::Created<rocket_contrib::json::Json<users::NewUser>>, rocket::response::status::Custom<rocket_contrib::json::Json<users::ErrRegistered>>>: rocket::response::responder::Responder<'_>` is not satisfied
   --> src\users.rs:27:1
    |
27  | #[post("/users", data = "<user>")]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `rocket::response::responder::Responder<'_>` is not implemented for `std::result::Result<rocket::response::status::Created<rocket_contrib::json::Json<users::NewUser>>, rocket::response::status::Custom<rocket_contrib::json::Json<users::ErrRegistered>>>`
    | 
   ::: C:\Users\34937\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rocket-0.4.2\src\handler.rs:202:20
    |
202 |     pub fn from<T: Responder<'r>>(req: &Request, responder: T) -> Outcome<'r> {
    |                    ------------- required by this bound in `rocket::handler::<impl rocket::outcome::Outcome<rocket::response::response::Response<'r>, rocket_http::status::Status, rocket::data::data::Data>>::from`
    |
    = help: the following implementations were found:
              <std::result::Result<R, E> as rocket::response::responder::Responder<'r>>
              <std::result::Result<R, E> as rocket::response::responder::Responder<'r>>

error: aborting due to previous error
```

Since that `u64`, `String` or `&'_ str` is primitive type, `Responder` should be `impl`ed. Therefore, the` `Json`s and `status::Created`/`status::Custom` should implement `Responder` too, And I've checked. Even `Result<(), ()>` can pass the compile. Why this error comes out? Is there anything I'm missing?

**Comment by jebrosen** [comment]
That error is appearing because the Error type has to implement `Debug`, even though you are using the `Responder` implementation.

**Comment by huangjj27** [comment]
> That error is appearing because the Error type has to implement Debug, even though you are using the Responder implementation.

@jebrosen Yes, I added `Debug` and issue is solved! Thanks!

**Comment by rainyday** [comment]
> That error is appearing because the Error type has to implement `Debug`, even though you are using the `Responder` implementation.

@jebrosen If you ever happen to have the time, I was wondering if you could explain why the compiler gives such a seemingly counter intuitive error? Why is it complaining about the Responder trait instead of the Debug trait?

**Comment by jebrosen** [comment]
@rainyday In 0.4, rocket used the `specialization` feature so that it could implement both of these:

* `impl<T, E> Responder for Result<T, E> where T: Responder, E: Debug`
* `impl<T, E> Responder for Result<T, E> where T: Responder, E: Debug + Responder`

One of the side effects of the `specialization` feature seems to be incomplete error messages like the one above - *usually* rustc prints out some kind of hint about which part of the `where` is not satisfied. As specialization gets closer to being stable, I expect these and similar error messages to improve.

---

But, the `master` branch (upcoming for 0.5) does not use `specialization` anymore since it is an unstable feature. Only this `impl` exists now:

* `impl<T, E> Responder for Result<T, E> where T: Responder, E: Responder`

The previous behavior can be restored by using <https://api.rocket.rs/master/rocket/response/struct.Debug.html>. This type was also backported to 0.4 for an easier migration path, and there is a runtime warning if using the removed `impl`: <https://github.com/SergioBenitez/Rocket/commit/436a5aad579f7f9e0053ec4fc35c068baf148d64>

**Comment by ajstyles0524** [comment]
`use log::*;
use reqwest::Error;
use rocket::launch;
use rocket::routes;
use rocket::Rocket;
use rocket::{get, Build};
use rocket::serde::Deserialize;
use rocket::serde::Serialize;
use reqwest::Response;
#[derive(Serialize, Deserialize)]
pub struct Welcome {
    #[serde(rename = "_id")]
    id: i64,
    name: Name,
    contribs: Vec<String>,
    awards: Vec<Award>,
}
#[derive(Debug, Serialize, Deserialize)]
pub struct Award {
    award: String,
    year: i64,
    by: String,
}
#[derive( Serialize, Deserialize)]
pub struct Name {
    first: String,
    last: String,
}
#[get("/")]
async fn index()->Result<(),reqwest::Error>{
    let result = reqwest::get("https://mocki.io/v1/3fee675e-373e-44c7-bb2e-5fc6512fb055")
        .await?
        .json::<Welcome>()
        .await?;
    println!("{:#?}", result.awards[0]);
    Ok(())
}
#[launch]
fn rocket() -> Rocket<Build> {
    rocket::build().mount("/", routes![index])
}
  `
@jebrosen @zackchandler @vladinator1000 @JayHelton 
when i run the above code i got an error mgs i do not why

The Error message

`error[E0277]: the trait bound `reqwest::Error: Responder<'_, '_>` is not satisfied
   --> src/main.rs:30:19
    |
30  | async fn index()->Result<(),reqwest::Error>{
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Responder<'_, '_>` is not implemented for `reqwest::Error`
    |
    = note: required because of the requirements on the impl of `Responder<'_, '_>` for `Result<(), reqwest::Error>`
note: required by a bound in `route::handler::<impl Outcome<rocket::Response<'o>, Status, rocket::Data<'o>>>::from`
   --> /home/knoldus/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.5.0-rc.1/src/route/handler.rs:188:20
    |
188 |     pub fn from<R: Responder<'r, 'o>>(req: &'r Request<'_>, responder: R) -> Outcome<'r> {
    |                    ^^^^^^^^^^^^^^^^^ required by this bound in `route::handler::<impl Outcome<rocket::Response<'o>, Status, rocket::Data<'o>>>::from`

`
