### ISSUE TITLE
Content-Length for Stream responses

### ISSUE THREAD

**Issue by alexpilotti** [SergioBenitez/Rocket#1028]
Currently when using Stream::from() there's no way to specify a content-length, so clients have no idea about the total length of the response until the stream ends.

I'm looking into doing this with a custom responder now, but it would be great to have a simple optional parameter in e.g.: Stream::chunked.

**Comment by amouat** [comment]
@alexpilotti can I ask why you closed this? I'm hitting the same problem, so I'm wondering if there's a solution I'm missing...
