### ISSUE TITLE
Question: managed state and dynamic dispatch

### ISSUE THREAD

**Issue by vector623** [SergioBenitez/Rocket#1032]
Hey guys, great framework.  Recently created a podcast app which generates podcast feeds out of mp3's hosted in dropbox and everything worked out great.

Question: how do I avoid dynamic dispatch with managed state?

I created a `WebFileClient` trait and implemented it for `DropBoxClient`, since I may replace DropBox with an alternative later.  All I need is a common interface to target in case I replace DropBox with S3/webdav/etc; I don't need run-time polymorphism.  How do I target a trait without incurring the cost of dynamic dispatch?

Here's some code snippets for context:

```rust
#[get("/", format="html")]
fn list_podcasts(file_client: State<Box<WebFileClient>>) -> content::Html<String> {
    let podcast_folders = file_client
        .get_folders("");
    let podcast_listing = format!("{:#?}", podcast_folders);

    content::Html(podcast_listing)
}

pub trait WebFileClient: Sync + Send  {
    fn get_folders(&self, folder:&str) -> Vec<WebFolder>;
}

pub struct WebDavClient;

pub struct DropBoxClient {
    pub api_key: String,
}

impl WebFileClient for WebDavClient {
    fn get_folders(&self, folder: &str) -> Vec<WebFolder> { unimplemented!(); }
}

impl WebFileClient for DropBoxClient {
    fn get_folders(&self, folder: &str) -> Vec<WebFolder> { unimplemented!(); }
}

```

**Comment by jebrosen** [comment]
I think [existential types](https://github.com/rust-lang/rfcs/blob/master/text/2071-impl-trait-existential-types.md) are what you want here, but last I remember there are still some easy-to-run-into compiler errors and soundness issues with them.

A close possible second in your case would be a type alias, such as `type ActiveWebFileClient = WebDavClient;`. You could use `ActiveWebFileClient` throughout your code, and then you only need to change it one place if you switch implementation. The major downside of this approach is that the real type leaks and you might accidentally use interfaces provided by `WebDavClient` that aren't part of `WebFileClient`.

**Comment by vector623** [comment]
Thank you!
