### ISSUE TITLE
warning: `...` range patterns are deprecated

### ISSUE THREAD

**Issue by anowlcalledjosh** [SergioBenitez/Rocket#1033]
- Rocket version: 0.4.1
- Rust version: rustc 1.37.0-nightly (b25ee6449 2019-06-17)
- OS: Ubuntu 18.04

Compiling this code:

```rust
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use] extern crate rocket;

#[get("/route")]
fn route() {
    match 1 {
        0..=24 => {},
        _ => {}
    }
}

fn main() {}
```

results in this warning:

```
warning: `...` range patterns are deprecated
 --> src/main.rs:8:10
  |
8 |         0..=24 => {},
  |          ^^^ help: use `..=` for an inclusive range
  |
  = note: #[warn(ellipsis_inclusive_range_patterns)] on by default
```

which is unexpected, given that the `..=` syntax is used in the code.

Removing the `get` attribute stops the warning from being emitted.

**Comment by jebrosen** [comment]
Unsubstantiated guess: `syn` parses this as "the inclusive range token", and `quote` re-emits it as `...`, perhaps for compatibility with older versions of Rust? Rocket isn't doing anything to these tokens. It might also be that long-standing span loss bug, where adding or removing a comma somewhere else in your code could make the warning go away.

**Comment by jebrosen** [comment]
`syn` emits inclusive ranges in patterns as `...` even if the input is `..=`. I've filed an issue upstream.

**Comment by jebrosen** [comment]
The latest release of `syn` (0.15.37) includes a fix, so a `cargo update` should make this error go away.
