### ISSUE TITLE
Is it possible to serve StaticFiles AND use dynamic route mounted to the same base path?

### ISSUE THREAD

**Issue by Tirka** [SergioBenitez/Rocket#1036]
> 1. The version of Rocket this question is based on, if any.

0.4.1 (latest)

> 2. What steps you've taken to answer the question yourself.

Read the docs and related github issues

>  3. What documentation you believe should include an answer to this question.

🤷‍♂️

Here is what i'm trying to do (main.rs):
```
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use] extern crate rocket;

#[get("/<name>")]
fn greeter(name: String) -> String {
    format!("Hello, {}", name)
}

fn main() {
    use rocket::ignite;
    use rocket_contrib::serve::StaticFiles;

    ignite()
        .mount("/", StaticFiles::from("/path/to/static_files"))
        .mount("/", routes![greeter])
        .launch();
}
```
`/path/to/static_files` contains `favicon.ico`, `main.js`, etc.

What i desire to get:
`GET /favicon.ico`  -> responds with corresponding file content
`GET /Sergio` -> responds with `Hello, Sergio` (if there is no file named `Sergio` in appropriate folder)

Is it possible to achieve desired behavior?

I also tried to play with route rank, but not succeed.

Thank you for making programming great again with rust! 😍

**Comment by jebrosen** [comment]
I believe the issue you are having is that StaticFiles in 0.4.1 is hardcoded with a rank of 10. Did you try setting your route to a rank later (higher) than 10?

The rank StaticFiles uses will be configurable in future releases.

**Comment by Tirka** [comment]
As I mentioned above I tried different ranks. 
If I set rank to 11 then route `greeter` fires for all requests:
`GET /favicon.ico` -> `Hello, favicon.ico`

**Comment by jebrosen** [comment]
Oh, this is a bit sad. `StaticFiles` actually never forwards - it either returns a file with the specified name or immediately responds with a 404. I think this has been encountered before, and maybe we should change StaticFiles to `Forward` in that case instead.

**Comment by SergioBenitez** [comment]
With `21b10176ee5d6ba89bf84e1a89dd7a0c1bb7ce4e`, this is now possible. One such implementation of the requested functionality is:

```rust
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use] extern crate rocket;

#[get("/<name>", rank = 11)]
fn greeter(name: String) -> String {
    format!("Hello, {}", name)
}

fn main() {
    use rocket_contrib::serve::StaticFiles;

    rocket::ignite()
        .mount("/", StaticFiles::from("/path/to/static_files"))
        .mount("/", routes![greeter])
        .launch();
}
```

You can also change the rank of the `StaticFiles` routes with: `StaticFiles::from("/path/to/static_files").rank(-10)`, for instance, though the former implementation is advisable.

**Comment by InstinctBas** [comment]
@SergioBenitez, any chance this commit can be cherry-picked for the next 0.4.x release/patch? Discussed with Jeb yesterday on IRC, I'm running into this as well and the fix doesn't really break anything.

**Comment by jebrosen** [comment]
@SergioBenitez ping - IMO this could be eligible for a 0.4 backport, despite possibly being a change in behavior. What I said on IRC:

> I believe the only noticeable change it would introduce is making unreachable routes reachable, routes which were probably meant to be reached in the first place
