### ISSUE TITLE
Return a created response without body

### ISSUE THREAD

**Issue by ianlet** [SergioBenitez/Rocket#104]
Hi, I'm working on a simple project to build a REST API with rust and I wanted to give Rocket a try.

Before bothering you here, I looked into your examples and in the source code but I could not find how you intended to handle a `Created` response without a body.

So for now, this is how I am handling it:
```rust 
#[post("/", format = "application/json", data = "<ride_request_dto>")]
fn new(ride_request_dto: JSON<RideRequestDto>) -> status::Created<()> {
  // ...
  let ride_number = Uuid::new_v4();
  let url = format!("/rides/{}", ride_number.to_string());
  status::Created(url, None)
}
```
I am kind of new to rust too so I hope this is not because of my ignorance, but I think this is a little bit cumbersome to have `()` as type and `None` as second parameter of `status::Created()`. Is there a better way to handle this case that comes to your mind?

On another note, Rocket is really awesome, great job!

**Comment by SergioBenitez** [comment]
No, this looks pretty idiomatic to me. I like that the signature makes it clear that there's no body, and `None` is required to express that. If you dislike seeing `()`, you could type alias it:

```rust
type Empty = ();
```

You can then change the return type to:

```rust
status::Created<Empty>
```

**Comment by SergioBenitez** [comment]
Closing this out. Feel free to reopen if you feel this is unanswered.
