### ISSUE TITLE
Weird behaviour with Docker and `Hello World`

### ISSUE THREAD

**Issue by dvcorreia** [SergioBenitez/Rocket#1041]
I don't know how to feel about this, but I think I should share.
I'm integrating a rocket application in a platform we are developing for a project in my university, and something weird is happening.

To put in context, we are running docker containers and architecting them with docker-compose and with NGINX doing reverse proxy to the different services. As an example, I've generated a service called `rustboiler` that contains the _Hello World_ example in the [Getting Started](https://rocket.rs/v0.4/guide/getting-started/#hello-world) and a `Dockerfile` that compiles the code and runs the binary in an Alpine Linux image, both can be seen bellow.

```rust
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use] extern crate rocket;


#[get("/")]
fn root() -> &'static str {
    "Hello World"
}

fn main() {
    rocket::ignite()
    .mount("/", routes![root])
    .launch();
}
```

```Dockerfile
# select bin image builder
FROM rustlang/rust:nightly as builder

# create a new empty project for cache persistence
WORKDIR /app/src
RUN USER=root cargo new --bin rustboiler

# copy over the manifests
COPY ./Cargo.toml ./rustboiler/

WORKDIR /app/src/rustboiler

# chache dependencies
RUN cargo build --release

# copy source tree
COPY ./ ./

# build for release
RUN cargo build --release

# pipeline to final image
FROM debian:jessie-slim

EXPOSE 8000
COPY --from=builder /app/src/rustboiler/target/release/rustboiler ./
CMD ["./rustboiler"]
```

```toml
[package]
name = "rustboiler"
version = "0.1.0"
authors = ["Author1"]
edition = "2018"
publish = false


[dependencies]
rocket = "0.4.1"
```

Now, what's the problem ? Everything should work alright.
Something strange happens when the response to the GET request is `"Hello world"`. It outputs to the terminal `Hello, World` and exists with code 0, like the image showed bellow:

<img width="881" alt="Screenshot 2019-06-26 at 19 31 16" src="https://user-images.githubusercontent.com/20357938/60202838-bf3e2180-984b-11e9-914a-b98ab9527766.png">

I was trying to understand what was happening, so I decided to hunt the problem. I removed the reverse proxy and didn't work, changed in every possible way the _Dockerfile_ but didn't seem the path to resolve the problem since it ran. So I decided just to change the request response from `"Hello World"` to something else like `"Hello World!"`, and in fact, it works well, as you can see bellow:

<img width="900" alt="Screenshot 2019-06-26 at 19 31 53" src="https://user-images.githubusercontent.com/20357938/60203175-6458fa00-984c-11e9-8669-73d9c3fd2ea1.png">

<img width="427" alt="Screenshot 2019-06-26 at 19 38 25" src="https://user-images.githubusercontent.com/20357938/60203185-69b64480-984c-11e9-8a37-cdf7510b081f.png">

I've tried changing to a bunch of different strings and everything seems to work with the exception of `"Hello World"`.

I don't have any clue why this is happening since I'm new to Rust.
You can reproduce the problem by doing the steps described above or just go to our repository in the [bug branch](https://github.com/engeniusua/datumbazo/tree/bug).

This can be a mistake that we aren't aware.

**Comment by SergioBenitez** [comment]
Either your example code is not the code you've used or Rocket wasn't actually running.

Your first image, the problem image, shows the string "Hello, world!" while the example program shows the string "Hello World" sans the `,` or the `!`. What's more, in the first image, we don't see any of Rocket's start-up log output, notably, "Configured for production. Rocket has launched.", while in the second image we do. As such, I'm inclined to believe that Rocket _is not_ running at all in the first example, and instead, you are running some "Hello, world!" binary. This would also explain why the container exits quickly.

Did you try running a standard, non-Rocket `Hello, world!" binary prior to running the Rocket "Hello, world!" binary? If so, my guess is that what you're seeing is a caching issue. That is, a cached binary of the non-Rocket "Hello, world!" binary is being loaded.

**Comment by dvcorreia** [comment]
I don't remember running any binary prior to what I showed here, but it might be a cache problem.
I've tried to run the binary compiled outside the container and in fact it ran as expected. In the example the only thing I've changed was the request response. The fact that only happens with "Hello World" was strange to me.

**Comment by SergioBenitez** [comment]
@dvcorreia It seems relatively clear from your logs that Rocket is not running in the case you consider to be erroneous. As a result, I'm closing this issue out.
