### ISSUE TITLE
how to use mongodb properly?

### ISSUE THREAD

**Issue by phantomxe** [SergioBenitez/Rocket#1043]
Hi, i'm trying to develop an api with using rocket. But when i was looking for a database solution like mongodb, it seems like okay. But mongodb documentation had shows only how to use `Client::connect("localhost", 27017)` in main function. But i need adapter in my routing functions. I tried ,
```
#[database("mongodb_test")]
pub struct TestConn(mongodb::db::Database);
``` 
and Rocket.toml file for required url.
```
[global.databases.mongodb_test]
url = "mongodb://localhost:27017/testdb"
```

But how can i convert TestConn to ready to use collection function?
```
#[get("")]
fn newFirm(firm: Json<Firm>, conn: TestConn) -> String { 
    /////*****////
    ????.collections("person").insert_one(doc!{ "name": "John" }, None).unwrap();  
    format!("testing")
}
```

**Comment by jebrosen** [comment]
`TestConn` should be usable as if it were a `Database`, which itself implements `ThreadedDatabase`: https://docs.rs/mongodb/0.3.12/mongodb/db/type.Database.html#impl-ThreadedDatabase. So I think the following code should work. You probably need to `use rocket_contrib::databases::mongodb::db::ThreadedDatabase`, and rustc should say that in an error message.

```rust
#[get("")]
fn newFirm(firm: Json<Firm>, conn: TestConn) -> String { 
    conn.collection("person").insert_one(doc!{ "name": "John" }, None).unwrap();  
    format!("testing")
}
```

**Comment by phantomxe** [comment]
First try,
```
error[E0599]: no method named `collections` found for type `TestConn` in the current scope
  --> src/bin/main.rs:40:10
   |
29 | pub struct TestConn(mongodb::db::Database);
   | ------------------------------------------ method `collections` not found for this
```
So, i added another variable.
```
    let db = &*conn;
    db.collections("firms").insert_one(doc!{ "name": "John" }, None).unwrap();  
```
Again error,
```
error[E0599]: no method named `collections` found for type `&std::sync::Arc<mongodb::db::DatabaseInner>` in the current scope
  --> src/bin/main.rs:40:8
```

**Comment by phantomxe** [comment]
I found that's my type error. It's working now 😄 @jebrosen
