### ISSUE TITLE
Connect to mysql

### ISSUE THREAD

**Issue by bostontrader** [SergioBenitez/Rocket#1044]
Hello Folks,

I'm trying to connect to mysql and it's not working! :-(  I'm a bit of n00b at rust so please forgive me in advance if this is an obvious fix.

The particular bit o' code that I suspect is the cause of all my woes is in src/main.rs :
```rust
#![feature(proc_macro_hygiene, decl_macro)]
#[macro_use] extern crate rocket;
#[macro_use] extern crate rocket_contrib;

// use rocket_contrib::databases::diesel;
#[database("mysqldb")]
struct MySQLConn(mysql::Conn);
```

If I compile this as-is, I get "**error[E0658]: The attribute `database` is currently unknown to the compiler and may have meaning added to it in the future**"

I suspect that this comes from commenting out **use rocket_contrib::databases::diesel** as specified in TFM.  I commented this out because I guess that the use of  "diesel" here is an example and that "mysql" might be a better guess.  However, code completion doesn't show either, or any other likely candidates, under rocket_contrib::databases.

While I further dissect the code in my search for this holy grail, I thought I'd post this issue.  Even if I find the answer myself, the next hapless n00b will undoubtedly step in the same thing.

Other possibly useful factoids...
Cargo.toml contains:
```toml
rocket = "0.4.2"
rocket_contrib = "0.4.2"
```

rustc --version = rustc 1.37.0-nightly (088b98730 2019-07-03)
>  2. What steps you've taken to answer the question yourself.

RTFM. Spelunk through source code.  Shout at the monitor and throw things at it.

> 3. What documentation you believe should include an answer to this question.

The Rocket docs under State/Databases would be a great place for this.

**Comment by jebrosen** [comment]
I think you are missing the feature specification, described at https://rocket.rs/v0.4/guide/state/#usage:

```toml
[dependencies.rocket_contrib]
version = "0.4.2"
features = ["mysql_pool"]
# or, for mysql with diesel:
features = ["diesel_mysql_pool"]
```

**Comment by bostontrader** [comment]
Opps! Forgot to include Rocket.toml
[global]
address = "0.0.0.0"
port = 8000

[global.databases]
mysqldb = { url = "mysql://root:supersecretpassword@172.17.0.2:3306" }

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["mysql_pool"]

**Comment by jebrosen** [comment]
Ah. So, the `[dependencies]` section is for `Cargo.toml` - not `Rocket.toml`.

**Comment by bostontrader** [comment]
Ha!  The secret is revealed!  It's ALIVE!  Thanks :-)
