### ISSUE TITLE
rocket_codegen Build Fails 1.38.0-nightly

### ISSUE THREAD

**Issue by Jacob-Stuart** [SergioBenitez/Rocket#1049]
1. The version of Rocket you're using. Ensure it's the latest, if possible.
```
commit 2d4dc5ae58f3c210199ed4ab59f2709cece4f0fa (HEAD, tag: v0.4.2)
Author: Sergio Benitez <sb@sergio.bz>
Date:   Fri Jun 28 17:50:57 2019 -0700

    New version: 0.4.2.
```

  2. The operating system (distribution and version) where the issue occurs.
```
Ubuntu 19.04
```

  3. A brief description of the bug that includes:
  Hello world example fails to compile rocket_codegen on latest ubuntu and latest nightly rust.

  4. How you uncovered the bug. Short, reproducible tests are especially useful.

```
Rocket/examples/hello_world$ cargo run
   Compiling rocket_codegen v0.4.2 (/home/stuart/src/Rocket/core/codegen)
error[E0433]: failed to resolve: unresolved import
  --> core/codegen/src/bang/uri_parsing.rs:18:13
   |
18 |     Ignored(Token![_]),
   |             ^^^^^^^^^
   |             |
   |             unresolved import
   |             help: a similar path exists: `devise::syn::token`
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

.
.
.
```
  ~~5. Ideas, if any, about what Rocket is doing incorrectly.~~

**Comment by messense** [comment]
https://github.com/rust-lang/rust/issues/62562

**Comment by AlterionX** [comment]
Just to save a link, you can roll back to __nightly-2019-07-10__ before it gets fixed.

**Comment by SergioBenitez** [comment]
As this is a compiler bug, there's unfortunately nothing we can do but wait for tonight's nightly.

**Comment by Trolldemorted** [comment]
rocket does not build on nightly-2019-07-10 either:
```
C:\Users\Benni\repositories\ENOKEY>cargo build
   Compiling serde_derive v1.0.94
   Compiling rocket_codegen v0.4.2
error[E0433]: failed to resolve: unresolved import
  --> C:\Users\Benni\.cargo\registry\src\github.com-1ecc6299db9ec823\rocket_codegen-0.4.2\src\bang\uri_parsing.rs:18:13
   |
18 |     Ignored(Token![_]),
   |             ^^^^^^^^^
   |             |
   |             unresolved import
   |             help: a similar path exists: `devise::syn::token`
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

**Comment by AlterionX** [comment]
😢 Roll back another day. I had it building on __nightly-2019-07-09__.

**Comment by Trolldemorted** [comment]
yeah with 2019-07-09 it works, now we have to convince our docker containers to use that version :(

If you'd solve #19 that would be great :)

**Comment by AlterionX** [comment]
Are you using Rocket in prod? What company/site? (Purely out of curiosity, and since my friend was asking about nightlies in prod.)

**Comment by Trolldemorted** [comment]
It is just a [hobby project](https://github.com/ENOFLAG/ENOKEY) with a fanatic nightly rustacean project lead :|

Unfortunately the Cinsects CTF is gonna start in 8.5 hours and we have to get our infrastructure up and running until then, otherwise we'd have to gather and deploy ssh keys manually like some kind of animal!

**Comment by olback** [comment]
@Trolldemorted New nightly build is available now and I can confirm that the issue is fixed.

Build on the latest release:
https://circleci.com/gh/olback/olback.net/148
