### ISSUE TITLE
too many connections on database

### ISSUE THREAD

**Issue by phantomxe** [SergioBenitez/Rocket#1054]
Hi, i got something weird on rocket with mongodb pool. I developed some api and tested it.
Works very well. But when server running on 20 minutes with `ROCKET_WORKERS=32`, concurrent connections on mongodb is doubled and in 25 minutes pulls to 97. And in 1 hours, server exceeds the connection limit of mongodb which 292 in my system. And thats crushes the server.

**Comment by brinsche** [comment]
Probably related to #979

**Comment by jebrosen** [comment]
Closing as duplicate of #979.
