### ISSUE TITLE
Cache busting implementation

### ISSUE THREAD

**Issue by AlterionX** [SergioBenitez/Rocket#1056]
I'm here to ask a seemingly simple question about cache invalidation. I'm attempting to deploy a relatively simple website through rocket, but my static assets (namely my javascript files) are being cached somewhere in between, my Rocket instance, the nginx reverse proxy, the cloud sending all my data to the browser, and the browser itself. I'm not sure where it's being cached, but I've been looking around pretty much all day today. I'm convinced it's caching since wait a long time and refereshing the page causes this to go away. Invalidating the browser cache does nothing, as does doing a vm restart, clean git clone, and then setup of the server.

I finally figured out that I probably am not the only one with this problem, so I then googled it, leading me to find out about a practice called "cache-busting". I was wondering if there is a recommended way of implementing this with Rocket specifically. I'm almost certain that the way I want to implement it is transforming links so that `a/b/c.js` is remapped to `a/b/c.{SHA256 hash of file}.js` but this is a chore to do in the html render, so I was thinking of transforming the html being sent. I'm fairly certain this would be done with a fairing. Then, we'd have to process the request on the way in, so the fairing would also have to forward it to the correct place. The part I got stuck on is how to trigger the correct route for the fairing, but that feels like an API issue.. Since this stuff should really be cached in memory, it would make sense to use State. Since that's the case, there should be a counterpart to the fairing to make everything work out, something like [an in-memory file cache](https://github.com/hgzimmerman/rocket-file-cache) that prioritizes storing SHA256 hashes of all static assets.

Well, that's more or less how I think I would implement it. The thing is, I would really prefer not to since this feels more like a hack than anything else on top of being a lot of work (correctly identifying links sounds like a nightmare to do quickly and efficiently).

So my question is this: is cache busting a solved issue for Rocket elsewhere and that I haven't found it yet since I didn't look in the right places. Honestly, I wouldn't really want to implement this either in nginx or in Rocket, but I seem to need it to deploy cleanly.

Needed request for question: Version: 0.4.2
Steps taken: Look into rocket_contrib, googling various things. I've been using the Staticfiles from rocket contrib this whole time, didn't really see anything there.
Documentation that should include an anser to this question: Not sure, really. I don't think it falls directly into rocket's purview.

**Comment by AlterionX** [comment]
It just occurred to me that storing SHA256 hashes also needs validation. That seems troublesome.

**Comment by jebrosen** [comment]
> but my static assets (namely my javascript files) are being cached

Normally caching is considered a good thing. What about the cache is causing you trouble?

If you need to change caching behavior, you should employ headers such as [`Cache-Control`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) to adjust cache rules and [`Last-Modified`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified) and/or [`ETag`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) for cache validation.

> Invalidating the browser cache does nothing

That is surprising, perhaps nginx or another proxy in between has been configured to cache too aggressively?

---

Overall, cache busting is most useful for "I set my assets to expire wrongly and I need everyone to get the new versions now". If you can set your expiration policies correctly up front it shouldn't be necessary.

**Comment by AlterionX** [comment]
A stray JS file wasn't being updated for one reason or another.

I was running my requests through three proxies, actually; nginx, Google's load balancer, and Cloudflare. Seems like purging Cloudflare's cache did the trick. Also, it seems specific to js files, since I also serve CSS, images, and WASM files as well, and those do not get stale. To be honest, I'm quite confused, hahaha.

As for the cache busting note, I'll take that into account.

**Comment by jebrosen** [comment]
It sounds like this wasn't/isn't something Rocket itself should be doing, so I'll close this. We can reopen this if you or someone else has a proposal for a good way to do it (in `contrib`, maybe).
