### ISSUE TITLE
target.'cfg(debug_assertions)'.dependencies doesn't work

### ISSUE THREAD

**Issue by jethrogb** [SergioBenitez/Rocket#1058]
https://github.com/SergioBenitez/Rocket/blob/v0.4/contrib/lib/Cargo.toml#L79 contains a section `[target.'cfg(debug_assertions)'.dependencies]`. This doesn't work as intended: cargo always resolves the target cfgs by running `rustc --print=cfg`, regardless of which profile has been selected in the cargo command line, and regardless of which profile options have been set in `Cargo.toml`.

**Comment by jebrosen** [comment]
Has this been this way for a year and a half and nobody noticed, or did something change in cargo? I would have to search logs spanning January through August of last year to find all the discussions about the PR that added it, but it would have been silly for us to add `'cfg(debug_assertions)'` if it didn't work. I do remember knowing at the time that `cfg(feature = )` isn't supported there, though.

Cargo does indeed compile the `notify` crate in release mode as well. If this isn't intended to work we might as well move it into `[dependencies]`.

**Comment by jethrogb** [comment]
> If this isn't intended to work we might as well move it into [dependencies].

I'd say it should be an optional feature then

**Comment by jebrosen** [comment]
4151cd4 moved it to `[dependencies]` to get rid of the warnings without changing behavior. I only now realized it doesn't even require enabling `templates` and it should.

> I'd say it should be an optional feature then

The main problem I originally had with an optional feature was that `default-features = false` is the norm and I expected few people would discover and use the functionality. However it's becoming more likely with the move to `async` that this will end up causing multiple versions of `mio` and others to get pulled in, so making it a separate feature is looking more and more attractive.

**Comment by SergioBenitez** [comment]
@jebrosen What would you like to do about this?

**Comment by jebrosen** [comment]
I propose that we change the `notify` dependency to be an optional one, conditioned only on the `templates` feature - and I will open a PR for that if nobody objects. This will not affect anyone using the `templates` feature, and it will remove some dependencies for anyone *not* using the `templates` feature.

We could add a separate feature flag for reloading, but as far as I know nobody has actually requested one. "multiple versions of `mio`" is not actually a concern yet anyway, and it's a pretty minor one.

**Comment by SergioBenitez** [comment]
> I propose that we change the `notify` dependency to be an optional one, conditioned only on the `templates` feature - and I will open a PR for that if nobody objects. This will not affect anyone using the `templates` feature, and it will remove some dependencies for anyone *not* using the `templates` feature.

Sounds great. I'm surprised we don't do this already. 

> We could add a separate feature flag for reloading, but as far as I know nobody has actually requested one. "multiple versions of `mio`" is not actually a concern yet anyway, and it's a pretty minor one.

I can't think of a clean way, that is, without feature explosion, to 1) automatically enable such a template reloading feature if any template feature is enabled, and 2) make it possible to disable, or not enable, template reloading. If there's such a way I'm overlooking, I'm all for it, otherwise, let's leave it out.

**Comment by SergioBenitez** [comment]
c19365dcbebce47a02c0cfa1de77fd278c4adb4e has been merged!
