### ISSUE TITLE
Private cookies stopped working

### ISSUE THREAD

**Issue by InstinctBas** [SergioBenitez/Rocket#1059]
I'm baffled, hopefully this is something simple someone can quickly answer.
Overnight my private cookies stopped working on my test environment. Still works fine in production. The only thing of note that's changed is that I installed the latest Xcode on my Mac. Running MacOS 10.14

As far as I can see is that the cookie just doesn't get transmitted, so maybe a dependancy issue that caused the feature to be unavailable? Changing the code to add a normal non-private cookie works fine. 

  1. The version of Rocket this question is based on, if any.
0.4.2 + todays nightly rust

  2. What steps you've taken to answer the question yourself.
Upgrade to the latest version of Rocket and nightly build, was using 0.4.0 for the longest time, just in case something was fixed.

  3. What documentation you believe should include an answer to this question.
https://api.rocket.rs/v0.4/rocket/http/enum.Cookies.html#method.add_private

**Comment by jebrosen** [comment]
I *hope* this is a duplicate of #1015 and #567 where the default value for `SameSite` causes these surprising results in some configurations. A quick way to troubleshoot is to use the browser's network inspector -- you should see a `Cookie` header on the request that matches the private cookie set via the response's `Set-Cookie` header.

I don't see any changes from 0.4.0 to 0.4.2 that might be related, and I can't imagine that upgrading Xcode or rustc would affect this either.

**Comment by InstinctBas** [comment]
The thing is, I upgraded to 0.4.2 in an attempt to fix this, I was still on 0.4.0 when this started happening. It's really weird because I hadn't touched the code for awhile. I can only think of cargo updating a dependency. 

I'm using Firefox, looking at the network inspector in that I can't see any cookie data in either request or response headers. It's like the add_private call is being ignored and doesn't add the cookie to the response.

**Comment by jebrosen** [comment]
> It's like the add_private call is being ignored and doesn't add the cookie to the response.

One way this could definitely happen is if multiple `Cookies` instances are active at once. This logs a pretty noticeable warning, though.

At this point a minimal reproducible example of the bug would be most helpful in troubleshooting this.

**Comment by InstinctBas** [comment]
It's not the multiple instance issue, I would have ran into it, plus normal cookies work, only private ones fail.

And it just went from bad to worse. Just did a new build on our test server and the same issue is present there. There are no code differences, the only thing that's changed is that it is a fresh build so cargo will have pulled all the latest dependencies. And this is a linux machine so that rules out the Xcode upgrade.

I might revert back to using normal cookies, the data it encrypts isn't really that sensitive, but I'll keep digging till I figure out the difference.

**Comment by InstinctBas** [comment]
I'll see if I can get something reproducible btw, but it'll be Monday, its the start of the weekend and my head is splitting

**Comment by InstinctBas** [comment]
Ok, sorry for the spam on this, its getting more confusing :)
Just had a colleague log into the same server and for her the cookies come through. So it's possibly a client issue...

**Comment by InstinctBas** [comment]
Ok, I'm pretty sure now this has nothing to do with Rocket. This is something Apple changed, it's blocking/filtering out cookies. Use Firefox or chrome or an Mac that hasn't yet been updated and everything is working as expected... 

Seeing these are all test environments they are DNSs that resolve to local network addresses with servers using self signed certificates. Must have all sorts of alarm bells going off. Where its all still working with Safari on my computer are our production servers that are running proper certificates. Just gave the illusion it must be a versioning thing on the server.

I don't know why Safari was happy with the non encrypted cookies, must be the sameSite setting on the cookie?
