### ISSUE TITLE
Adding support for the Future return type to the router

### ISSUE THREAD

**Issue by audioXD** [SergioBenitez/Rocket#1063]
# Feature Requests

Feature requests _must_ include:

  1. Why you believe this feature is necessary.
   - To enable the use of non blocking IO

  2. A convincing use-case for this feature.
  - For example: async database calls and file writes.

  3. Why this feature can't or shouldn't exist outside of Rocket.
  - I'm not sure how the internals of rocket work, but I do belive that the future needs to be propagated up to hyper.

**Comment by jhpratt** [comment]
I presume the way forward on this is the currently ongoing port to hyper 0.12, which will make things fully asynchronous.

**Comment by pythoneer** [comment]
i think this issue here is very related https://github.com/SergioBenitez/Rocket/issues/17

**Comment by jebrosen** [comment]
This will be resolved by #1065.
