### ISSUE TITLE
(async) Support launching on a custom runtime

### ISSUE THREAD

**Issue by jebrosen** [SergioBenitez/Rocket#1068]
It might be desired for a user to set up a custom runtime to launch rocket on, for example if one binary is starting multiple servers or is running a rocket server plus other tasks.

We could create a `launch_on(runtime: Runtime)` or similar function. Note that this must be a `tokio` runtime because hyper uses timers and likely other functionality from tokio that will only work inside tokio's event loop.

**Comment by jebrosen** [comment]
Another major obstacle to this is the use of `tokio::fs::File` in the `File` responder, which can only be used with a tokio runtime.

**Comment by jhpratt** [comment]
> Another major obstacle to this is the use of `tokio::fs::File` in the `File` responder, which can only be used with a tokio runtime.

Is this due to the fact that tokio uses its own `AsyncRead` and `AsyncWrite` traits, rather than using std's?

**Comment by jebrosen** [comment]
It's more coupled than that -- for I'm successfully using an adapter someone wrote to get around the different traits. Most operations on `tokio::fs::File` go through [`blocking_io`](https://github.com/tokio-rs/tokio/blob/master/tokio-fs/src/lib.rs#L83), which depends on running on a tokio_threadpool.

**Comment by Nemo157** [comment]
> Note that this must be a tokio runtime because `hyper` uses timers and likely other functionality from tokio that will only work inside tokio's event loop.

What makes you say this? As far as I can tell hyper is runtime agnostic, and I have a project running on top of romio + juliex using current master of hyper. (I realise for the other reasons mentioned you may be tied to tokio, I'm just trying to understand if there's something I'm missing that makes `hyper` more tied to tokio than I thought).

**Comment by jebrosen** [comment]
At the time that was written I was probably referring to hyper 0.12. `.executor()` required a tokio executor, or a trait that was effectively only implemented for tokio executors. We also used (and still use) `AddrIncoming` which uses tokio timers.

We plan to implement an alternative to `AddrIncoming`, which I was going to look at more closely this week. However we do still use `tokio::fs::File`, so we require the tokio runtime anyway. This could change if we were to use (for the sake of example) `async-std` instead.

**Comment by Nemo157** [comment]
Ah, ok, thanks. I did have to use compatibility shims for the executor (the one provided with `futures-preview` works for hyper 0.12, and `futures-tokio-compat` has one that works with current hyper master), and similar for the incoming connections, but it's all very straightforward if you do want to look at supporting a custom runtime (maybe even just for users that don't need any `fs` support).

**Comment by jhpratt** [comment]
@jebrosen This can be closed, as #1097 has been merged.
