### ISSUE TITLE
(async) Access to the runtime/executor Rocket is running on

### ISSUE THREAD

**Issue by jebrosen** [SergioBenitez/Rocket#1069]
Routes might want to spawn futures on a runtime. We could provide access to a runtime via a handle that implemented both `FromRequest` and `Spawn`. Spawning a future on this handle would spawn it on the same runtime Rocket itself is running on.

For example, it could be used to track a pool of background tasks:
```rust
struct BackgroundTasks(Arc<Mutex<Vec<Task>>>);

#[post("/thing")]
fn thing(exec: ExecutorHandle, tasks: State<BackgroundTasks>) {
    tasks.add(exec.spawn(async {
            // whatever
    }))
}
```

On the other hand, maybe we should not expose such a handle and require users to create their own thread pool.

**Comment by jhpratt** [comment]
The advantages of exposing the executor are obvious — there's no duplicated efforts among the program. What are the potential downsides? Asking this generally, not to anyone in specific.

**Comment by jebrosen** [comment]
One downside could be that the "background tasks" have to share a fixed number of threads with the tasks for handling connections and streaming data to and from clients. Whether this is a problem is workload and configuration dependent.

**Comment by jhpratt** [comment]
Having Rocket's thread pool exposed wouldn't prevent users from creating their own if they run into performance issue, though. I imagine it won't be an issue in most cases.

**Comment by jebrosen** [comment]
This could be extremely beneficial to allow the use of delays or timeouts, especially important for something like a periodic event stream. This starts to get into the nitty-gritty details of the whole runtime stack.

**Comment by jhpratt** [comment]
I'll likely take this one on once #1097 is merged in. It should be relatively similar to how graceful shutdown shares it's handle.

**Comment by jhpratt** [comment]
@jebrosen What's the proposed interop between this and the ability to launch on any runtime, not just tokio?

**Comment by jebrosen** [comment]
My idea for that was to expose something that implements [`futures::task::Spawn`](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.18/futures/task/trait.Spawn.html) -- probably a small wrapper type that forwards spawn to the actual underlying executor.

**Comment by jhpratt** [comment]
@jebrosen After some discussion with @carllerche, I've come to agree with him that access to the runtime is unnecessary and potentially inefficient. He said that tokio will be able to optimize its operations for execution on its own runtime. I inquired about the possible implementation of `futures::task::Spawn`, to which I received a firm no — tokio will actually be _removing_ its own spawn trait before the final 0.2 release.

Tokio already has `tokio::spawn`, which can be called directly from anywhere, including inside routes; other runtimes have something similar (async-std has `task::spawn` for example). Perhaps the key point he made is that apps are typically going to only use a single runtime, so there's no reason users shouldn't be able to call the aforementioned methods directly. I imagine switching runtimes would be relatively rare, since most runtimes provide similar features.

As a result of the discussion, I think it would be best to _not_ implement this.

**Comment by jhpratt** [comment]
NB: If we end up not implementing this, and instead just settle on tokio-only for now, it would be best to revert #1106

**Comment by carllerche** [comment]
I wouldn’t say it was a firm no :-) mostly it does not seem good to me but it is open to discussion.

**Comment by jhpratt** [comment]
You called spawn traits an anti-pattern :stuck_out_tongue:

**Comment by carllerche** [comment]
Yes. That is my opinion. But, I am always open to counter arguments

**Comment by jebrosen** [comment]
It's true that apps can use `tokio::spawn` or `async_std::task::spawn` directly. But for libraries that want to remain executor agnostic and simply need *a* runtime to spawn tasks on, an API like this one would be more convenient. This currently includes rocket itself, to do some write-to-read bridging over channels.

**Comment by jhpratt** [comment]
After thinking about this a bit more and thinking about a possible API, I think this wouldn't incur any additional runtime overhead, as we could still know the executor type and dispatch accordingly.

```rust
enum Executor {
    Tokio
}

impl futures::task::Spawn for Executor {
    fn spawn_obj(&mut self, future: FutureObj<'static, ()> -> Result<(), SpawnError {
        match self {
            Tokio => { ... }
        }
    }
}
```

We could then store the `Executor` on the Rocket instance, which would only incur a single byte of overhead. Performance would otherwise be identical.

**Comment by carllerche** [comment]
There would be a cost in converting the future into a FutureObj. In 0.2 final, if you do `tokio::spawn(async { ... })` there is no conversion to `FutureObj`. You would end up w/ double boxing by going through the `Spawn` trait.

**Comment by jhpratt** [comment]
@carllerche That's why I'm not particularly fond of the `futures::task::Spawn` trait, since it _requires_ the boxing. If I implemented this in Rocket, I'd likely end up not using a trait and just using a function that accepts a future as a parameter. It could then be boxed if the runtime requires it.

My code and explanation certainly wasn't clear, but that's what I meant when I said there wouldn't be any overhead.

**Comment by carllerche** [comment]
You could define a trait that takes a generic T: Future, but then it would not be object safe. There is the dilemma :)

**Comment by jebrosen** [comment]
It sounds like the `Spawn` trait is the issue. So instead, we could implement this:

```rust
struct RuntimeHandle<'?>(...);
impl FromRequest<'?, '?> for RuntimeHandle<'?> { ... }

impl RuntimeHandle<'_> {
    fn spawn<Fut: Future<Output=()>>(fut: Fut) { ... }
}
```

`spawn` can then be done in an optimized fashion, or not, as an implementation detail and/or depending on how rocket is given its executor. But it is not *required* to be unoptimized from the get-go.

I'm also willing to accept that we don't need this to be exposed at all. Rocket does need an executor handle of some kind passed to it - transitively for hyper and also to spawn tasks itself - but perhaps it's not worth the complexity to further expose it to libraries.

**Comment by jhpratt** [comment]
^^ That's basically what I was thinking, regardless of whether it's exposed.

**Comment by jhpratt** [comment]
My simple attempt at doing this is

```rust
use std::future::Future;

enum ExecutorHandle {
    Tokio,
    AsyncStd,
}

impl ExecutorHandle {
    fn spawn(&self, future: impl Future<Output = ()> + Send + 'static) {
        use ExecutorHandle::*;

        match self {
            Tokio => { tokio::spawn(future); },
            AsyncStd => { async_std::task::spawn(future); },
        }
    }
}

```

Ignoring any other issues there may be with this exact implementation, I have a major problem: if we're not requiring a feature flag, how can we avoid pulling in every single runtime as a dependency? Short of doing either of those, both `tokio` and `async-std` would be dependencies in the above, even though one would _never_ be used.

**Comment by jebrosen** [comment]
>  if we're not requiring a feature flag, how can we avoid pulling in every single runtime as a dependency?

I *do* plan to add a feature flag as part of #1070, which I've started working on. Without the feature, say, `default-runtime`, you would pass a custom listener and an executor/spawner to `listen_on`. This executor might eventually be the `Spawn` trait in the end, or not. With `default-runtime`, `launch()` additionally becomes available which uses `tokio::spawn`. This formulation is inspired by what hyper itself does. Here's how hyper handles the optional custom executor, as an example: https://github.com/hyperium/hyper/blob/master/src/common/exec.rs#L47

The main reason I opened this issue was to figure out whether we should *expose* a executor handle, and it sounds like the answer is "probably not". If enough libraries end up wanting it I'm pretty sure we would be able to add it backwards-compatibly anyway.

**Comment by jebrosen** [comment]
I'm going to decline this at this stage. While running on any executor is a nice idea, I don't want it to hold up 0.5 and instead I plan to assume `tokio::spawn` and `tokio::timer` are set up in the few places it matters. If and when we decide to support other runtimes, this can be revisited.

In lieu of this: use `spawn()` functions from `tokio` or other libraries in code, possibly paired with something like `remote_handle` to cross runtimes if necessary.
