### ISSUE TITLE
Update cookie dependency

### ISSUE THREAD

**Issue by krojew** [SergioBenitez/Rocket#1072]
It would be great to update cookie 0.11 dependency to 0.12. Right now it depends on an old version of ring which causes a dependency hell when other packages using ring are being used. 0.12 depends on the latest ring.

**Comment by jebrosen** [comment]
This is already done in master (#986). We *might* be able to backport this to 0.4 - see #1016.

**Comment by oleiba** [comment]
I'm also running into dependency issues with the dependant ring@0.13 (due to cookie@0.11) and would love to have this bump to 0.12.
Any plans to include in upcoming version soon?...
