### ISSUE TITLE
database attribute macro not found

### ISSUE THREAD

**Issue by AlterionX** [SergioBenitez/Rocket#1074]
Rocket Version: 0.4.2
OS: Arch Linux, kernel version 5.2.5 
Issue: Rustc cannot find attribute macro database

I'm pretty sure that I'm doing something wrong, but I `#[macro_use] extern crate rocket;` in main.rs, then attempt to use `#[database("db")]` in a child module. On attempting to compile, I get an error: `error: cannot find attribute macro `database` in this scope`

My Cargo.toml looks like this:
```
[package]
name = "server"
version = "0.1.0"
authors = ["AlterionX <ben.xu.cs@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
page-client = { path = "../page-client" }
wasm-script = { path = "../wasm-script" }
blog-client = { path = "../blog-client" }
blog-db = { path = "../blog-db" }
serde = { version = "1.0.98", features = ["derive"] }
rocket = "0.4.2"
rocket_contrib = { version = "0.4.2", default-features = false, features = ["json", "serve", "diesel_postgres_pool"] }
maud = { version = "0.21.0", features = ["rocket"] }
chrono = { version = "0.4.7", features = ["serde"] }
diesel = { version = "1.4.2", features = ["postgres", "chrono", "r2d2"] }
dotenv = "0.14.1"
```

**Comment by jebrosen** [comment]
For `#[database]`, you need `#[macro_use] extern crate rocket_contrib;` or `use rocket_contrib::database`.

**Comment by AlterionX** [comment]
Cool. I have the first part, but I  missed the second part. I don't think that it's in the docs for `rocket_contrib::databases`.

**Comment by jebrosen** [comment]
It is present in most of the docs. If you can remember where you looked for and missed it we should definitely add it or make it more obvious.

**Comment by AlterionX** [comment]
In the main pages for [`databases`](https://api.rocket.rs/v0.4/rocket_contrib/databases/index.html) and in the main guide for [`State`](https://rocket.rs/v0.4/guide/state/#databases). Neither mentions the database macro, but rather uses it as if it exists. It may be that I imported the wrong thing, but I did have the `use rocket_contrib::databases::diesel` as well as the `#[macro_use]`.

**Comment by jebrosen** [comment]
Both of those do have

```rust
#[macro_use] extern crate rocket_contrib;
```

So, I think we just need to point that out explicitly because it is easy to miss if someone's not looking for it (or might not notice that it is `rocket_contrib` and not `rocket` that has the `#[macro_use]`).

**Comment by AlterionX** [comment]
I think that I did put down the `#[macro_use] extern crate rocket_contrib`, but maybe I typoed something.
