### ISSUE TITLE
Provide the mounting point as a context to each function

### ISSUE THREAD

**Issue by botev** [SergioBenitez/Rocket#108]
This can be summarized in the following need: I have an app which I mount on let's say `/myapp/`. However the rendered templates used by the app make links to `/home` or `/about`. Obviously, however, what we want is those to point to `/myapp/home` and `/myapp/about`. This can easily be done with templates if we can pass the mounting point, however atm I do not know how to access it in the response methods.

**Comment by marcusball** [comment]
I've been thinking about this, too. It'd be really nice, and I think would make the mounting system very powerful, as it would enable plug-and-play crates that could be completely independent of the rest of the application.

**Comment by SergioBenitez** [comment]
Yes, it should certainly be possible to retrieve this information. Let's get this in for 0.2.

**Comment by botev** [comment]
Actually, it could be nice if we have access additionally to some kind of user defined context. E.g. have some generic `T` context except the overall info that Rocket provide (the mounting point being one of them). This would allow for certain ad-hoc things to be very easy to implement which needs to live on the server presistantly.

**Comment by SergioBenitez** [comment]
I'd forgotten about this earlier, but you can get the `URI` the the current request matched via the [URI](https://api.rocket.rs/rocket/http/uri/struct.URI.html) request guard implementation. Does this suffice?

**Comment by SergioBenitez** [comment]
Seeing as you might be able to get the information you're looking for via `URI`, I'm going to punt this to `0.3`.

**Comment by SergioBenitez** [comment]
@botev Is `URI` sufficient? Can we close out this issue?

**Comment by botev** [comment]
Ah sorry, I haven't been back on this to check it. But yes if the URI is provided that is probably sufficient. Although, it would be nice to have a utility function to extract the relative URI (e.g. after the domain name of the server).

**Comment by marcusball** [comment]
I feel like this would be desirable in the long-term. Using this method, I think a pattern might develop of frequently writing code like this:

```rust
#[get("/my/thing")]
fn handler(uri: &URI) { 
    let mount = extract_mount(uri, "/my/thing");
    ... 
} 
```

I suppose this works, but it feels redundant, and could be a possible source of bugs if someone updates the `#[get("...")]` path, but forgets to update the mount point extraction code. 

Also, it's a bit of an edge case, but, unless you manually add a method for extracting the matched URI string to objects implementing `FromSegments`, I'm not sure if the URI method will be possible with paths like `#[get("/<param..>")]`

**Comment by scull7** [comment]
Is this still a necessary thing for 0.3? If so, what approach should be taken?  It seems that passing the matched URI to the template might be sufficient.

**Comment by blackghost1987** [comment]
This feature would be really useful I think, as extracting the mount point from the URI is bothersome and also error prone as stated before. Maybe Rocket should have a Context type as a Managed state object, which is automatically created on launch? The URI provided is a "per request" data, but this Context object could be global for the whole application, similiarly to Flask's "request context" vs "app context". I think this differentiation is important.
