### ISSUE TITLE
Session example shows "Error" when logout is successful

### ISSUE THREAD

**Issue by pfrenssen** [SergioBenitez/Rocket#1086]
Occurs on latest master branch, regardless of operating system.

* Run the `session` example.
* Log in using user name "Sergio" and password "password".
* Log out again by pressing "logout".

Result: the text "Error: Successfully logged out." is shown.

Expected result: the example should not show "Error" for a successful logout.

**Comment by jebrosen** [comment]
#1087 has been merged.
