### ISSUE TITLE
macro conflict with log crate

### ISSUE THREAD

**Issue by flosse** [SergioBenitez/Rocket#109]
Using `log` and rocket's `error` macro doesn't work:
```
macro `error` may not be used in attributes
```
What would you recommend to solve that problem?

**Comment by marcusball** [comment]
I've asked pretty much the same thing. To paraphrase the answer I received, this is known, and there are plans to improve logging; see #21. Unfortunately, There aren't many great workarounds. My current solution has been to ignore `error!` cases—if you use error-chain, letting Rocket handle `Err` Results gives a pretty decent replacement for an `error!` log—and use the log crate, but [selectively include the other macros](https://doc.rust-lang.org/reference.html#macro-related-attributes) using `#[macro_use(log,info,debug,warn)]`.

**Comment by flosse** [comment]
> letting Rocket handle Err Results gives a pretty decent replacement for an `error!` log

This is a reasonable workaround as long as we're talking about the web layer of an application.
For the core business layer that handles other channels this solution wouldn't work :(

**Comment by SergioBenitez** [comment]
Indeed, this is an issue that will be handled by overall improved logging. We'll keep tracking that in #21. Closing this in favor of that.

**Comment by hatzel** [comment]
I had the problem as described by @flosse where my worker threads should do some logging (possibly errors).
Regardless of how Rocket will address this I just wanted to leave my disgusting solution here in case anyone else is wondering what to do: 
```
#[macro_use(log, info, debug, warn)] extern crate log;
// disgusting workaround for error also being present in rocket
macro_rules! log_error {
    (target: $target:expr, $($arg:tt)*) => (
        log!(target: $target, log::LogLevel::Error, $($arg)*);
    );
    ($($arg:tt)*) => (
        log!($log::LogLevel::Error, $($arg)*);
    )
}
```

I am just redefining their macro (which given it uses the log macro should be pretty stable) and calling it a different name.

No need to let me know how ugly of a hack this is, I know :cry:.

**Comment by SergioBenitez** [comment]
@hatzel There is a superior solution:

```rust
#![feature(use_extern_macros)]

#[macro_use(log)] extern crate log;

fn main() {
    log::error!("Hello, world!");
    log::info!("Hi! Hi!");
    // and so on...
}
```
