### ISSUE TITLE
Support for Modular Construction of Server

### ISSUE THREAD

**Issue by sazzer** [SergioBenitez/Rocket#1094]
I'm trying to use Rocket in a new application - and I'll openly admit I'm new to Rust too, so that might be the cause of problems here! - and I'm wanting to be able to build my server in a modular way. I.e. instead of a single mega method that constructs *everything*, I'm trying to have this separated out and some way of contributing configuration to the Rocket server.

I can't see a way of achieving this, and I *think* it's because `Rocket::mount` and `Rocket::manage` (and others) all take `mut self` instead of `&mut self`. Basically that means I can't pass the `Rocket` instance around for my other components to configure, and instead I need to do all of the configuration in a single place.

Am I overlooking how to do this? Or is it really not achievable? This is with the Rocket 0.4.2 crate and on Rust 1.38.0-nightly.

Cheers

**Comment by sazzer** [comment]
An example of what I'm trying to achieve:

```rust
pub struct HealthModule {}

impl HealthModule {
    fn configure_web_server(&self, rocket: &mut Rocket) {
        rocket.mount("/", routes![http::health]);
    }
}

pub fn build_server() -> Rocket {
    let mut health_module = HealthModule::new();

    let mut rocket = rocket::ignite();

    health_module.configure_web_server(&mut rocket);
    rocket
}```

**Comment by joeyjoejoejr** [comment]
One possible way to do this would be to not borrow the rocket struct and just pass ownership to your module.

```rust
pub struct HealthModule {}

impl HealthModule {
    fn configure_web_server(&self, mut rocket: Rocket) -> Rocket {
        rocket.mount("/", routes![http::health])
    }
}

pub fn build_server() -> Rocket {
    let health_module = HealthModule::new();

    let rocket = rocket::ignite();

    health_module.configure_web_server(rocket)
}
```

You were just running up against the borrow checker. Welcome to Rust!

There is another question, that I don't really know the answer to, which is how best to modularize a rocket web app.  Currently, I've just been keeping simple.

**Comment by sazzer** [comment]
Fantastic - that works wonders :) I suspected I was missing something (semi-)obvious :)
