### ISSUE TITLE
Don't display emojis on launch

### ISSUE THREAD

**Issue by xingyun86** [SergioBenitez/Rocket#1096]
Hello, and thanks for opening a new issue about Rocket!

Before opening your issue, we ask that you search through existing issues and
pull requests to see if your bug report, concern, request, or comment has
already been addressed. Ensure to search through both open and closed issues and
pull requests. If this is a question, feature request, or general comment,
please ensure that you have read the relevant sections of the documentation
before posting your issue. Finally, consider asking questions on IRC or Matrix
before opening an issue.

If you feel confident that your issue is unique, please include the following
information, selecting the category that best describes your issue:

## Bug Reports

  1. Paint::masked("🛰  ")
  2. Paint::masked("👾 ")
  3. Paint::masked("🚀 ")
  4. Paint::masked("🔧 ")

## Questions

  1. Paint::masked("🛰  ")
  2. Paint::masked("👾 ")
  3. Paint::masked("🚀 ")
  4. Paint::masked("🔧 ")

## Feature Requests

  1. Paint::masked("🛰  ")
  2. Paint::masked("👾 ")
  3. Paint::masked("🚀 ")
  4. Paint::masked("🔧 ")

Could you  modify it to other character? 🛰->*
Could you  modify it to other character? 👾->#
Could you  modify it to other character? 🚀->$
Could you  modify it to other character? 🔧->^

## General Comments
Could you  modify it to other character? 🛰->*
Could you  modify it to other character? 👾->#
Could you  modify it to other character? 🚀->$
Could you  modify it to other character? 🔧->^

**Comment by jebrosen** [comment]
What is the motivation for this change? At first glance it seems similar to #703, which the issue author never followed up on.

> Could you modify it to other character? 🛰 ->*

I think it's more likely we would remove them than replacing them with other. IMO `*#$^` would just be confusing.

**Comment by xingyun86** [comment]
> What is the motivation for this change? At first glance it seems similar to #703, which the issue author never followed up on.
> 
> > Could you modify it to other character? 🛰 ->*
> 
> I think it's more likely we would remove them than replacing them with other symbols. IMO `*#$^` would just be confusing.

You are right. I found error with logger. Because it is special character, and cause information printing incomplete

**Comment by SergioBenitez** [comment]
Disabling coloring will disable emojis: `ROCKET_CLI_COLORS=off`.

**Comment by SergioBenitez** [comment]
@xingyun86 Does that result your issue?

**Comment by xingyun86** [comment]
I want to enable color and found the problem.

**Comment by xingyun86** [comment]
> @ xingyun86这会解决您的问题吗？

没有解决，因为我想起用着色
