### ISSUE TITLE
State guide example uses type with hidden definition. 

### ISSUE THREAD

**Issue by Ben-PH** [SergioBenitez/Rocket#1100]
Somewhat related to this discussion comment:
https://github.com/SergioBenitez/Rocket/issues/950#issuecomment-515778753

 I also found an issue that had this one as a bystander. Compare screenshot in #960
 with this 
![image](https://user-images.githubusercontent.com/16680090/63404315-1e707a80-c426-11e9-8d04-911bfa18822f.png)

Source code of the screen shot: [scroll to bottom](https://github.com/SergioBenitez/Rocket/blob/2d4dc5ae58f3c210199ed4ab59f2709cece4f0fa/site/guide/6-state.md) or ctrl-f 'Logs>'

For me, Seeing `Logs` as a type, it was not clear to me that it was expected that the application provide the type, and not the ecosystem, at least for my envirenment. I searched with Duck Duck Go, and through the api docs for the `Logs` type and nothing, though I did find it [here](https://api.rocket.rs/v0.4/src/rocket_contrib/databases.rs.html#88)

I suggest introducing recommended methods of `Result<CustomType>` and examples of diesel/other Types independently, and/or making it more explicit the the guide reader that, in that example, `Logs` is a type defined by the application to be `()` for the purpose of that example.

**Comment by jebrosen** [comment]
@Ben-PH would the code snippet I posted in https://github.com/SergioBenitez/Rocket/issues/950#issuecomment-515778753 have been more clear?

**Comment by Ben-PH** [comment]
No, sorry. Unless I missed something, it's making the assumption that the reader knows that `Logs` is to be defined by the person implementing the application. 

It wasn't untill I dived into the source code and found a definition [here](https://api.rocket.rs/v0.4/src/rocket_contrib/databases.rs.html#73), that I realised Logs was just a placeholder definition.

something more like the source code snippit I linked, maybe with a comment detailing the utility of the `Logs` type, would be good.

**Comment by jebrosen** [comment]
Perhaps the right thing to do is to not use diesel as the example in the guide, as it seems to have caused more confusion than not. Rusqlite might be a better choice, since examples can be easily written without reference to any setup besides the database connection itself and familiar types from `std`.

**Comment by Ben-PH** [comment]
Your suggestion regarding Rusqlite seems attractive. Making it purely about the abstract notion of connecting to a database makes me think of the teaching principal "from known to unknown". Everything is already known except for that one thing you are introducing.

Does this shape it in a way that ensures that this part is purely about the most basic of applications? The "hello world" of connecting to a DB and querying it, if you will. 

I think it would be a shame to replace what currently shows the more powerful aspects. Once this gives the learner a familiarity of Rocket+DB, things like diesel, different db's etc can be introduced.
