### ISSUE TITLE
Support export to swagger or other API generators

### ISSUE THREAD

**Issue by vityafx** [SergioBenitez/Rocket#1103]
1. I think it is a good idea to be able to export all HTTP handlers with routes to a format which can be understood and/or rendered by services such as swagger. This would simplify collaboration. A use-case is simple: you write your rocket API and then you just export (deploy) it to your swagger instance. This could be a crate feature of `rocket`.
2. It is also a good idea to support code generation from swagger into rocket code. But this is not something we could inside the rocket framework, so just mentioning this here.

**Comment by GREsau** [comment]
I think this is a duplicate of #297

**Comment by vityafx** [comment]
Oh, it is actually!
