### ISSUE TITLE
Question: How to get a reference to the database connection for testing?

### ISSUE THREAD

**Issue by flosse** [SergioBenitez/Rocket#1108]
I'm using rocket `v0.4.2` and I use a [JSON file store](https://github.com/flosse/rust-json-file-store) for persistence.

In production the server uses the `json` database whereas for tests the `test` database is used which is an in-memory instance.

```rust
 #[cfg(not(test))]
 #[database("json")]
 pub struct DbConn(db::DbConn);
 
 #[cfg(test)]
 #[database("test")]
 pub struct DbConn(db::DbConn);
```
`Rocket.toml`:
```toml
[global.databases]
json =  { url = "db.json" }
test =  { url = "::memory::" }
```
The creation of the rocket instance is as usual:
```rust
fn create_rocket() -> Rocket {
    rocket::ignite()
        .attach(DbConn::fairing())
        .mount("/", routes::routes())
}
```

For my tests I'd like to have access to a local `Client` **and** to the `DbConn` instance.
How is that possbible?
I'd like to write something like this:
```rust
 pub fn setup() -> (Client, DbConn) {
    let rocket = create_rocket();
    let db = rocket.get_a_reference_to_the_db(); // <------ this is my question!
    let client = Client::new(rocket).unwrap();
    (client, db)
 }
```

**Comment by jebrosen** [comment]
I think `DbConn::get_one(&rocket)` is what you are looking for.

It's currently documented under https://api.rocket.rs/v0.4/rocket_contrib/databases/index.html#guard-types

**Comment by flosse** [comment]
@jebrosen Thank you, that's what I was looking for!

I'll leave this issue open until I tested it.

**Comment by flosse** [comment]
It works :)
