### ISSUE TITLE
How to add hyper::mime::Attr to a response?

### ISSUE THREAD

**Issue by flosse** [SergioBenitez/Rocket#111]
I'm looking for an equivalent to the iron response style:
```rust
Ok(Response::with((ContentType(Mime(TopLevel::Application, SubLevel::Json, vec![(Attr::Charset, Value::Utf8)])).0, status::Ok, json)))
```

**Comment by SergioBenitez** [comment]
Does that answer your question, @flosse?

**Comment by SergioBenitez** [comment]
Feel free to reopen this issue if you feel the question is unanswered. :)

**Comment by shalugin** [comment]
> That's simply ContentType::JSON. The charset=utf-8 parameter isn't necessary as JSON's encoding is already utf-8.

@SergioBenitez Without `charset=utf-8` Google Chrome shows answer with bad symbols :(
