### ISSUE TITLE
Misaligned formatting in windows 10 console

### ISSUE THREAD

**Issue by Alexendoo** [SergioBenitez/Rocket#1122]
Running Rocket 0.4.2, on Windows 10

With the [getting started](https://rocket.rs/v0.4/guide/getting-started) code:

```rust
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use] extern crate rocket;

#[get("/")]
fn index() -> &'static str {
    "Hello, world!"
}

fn main() {
    rocket::ignite().mount("/", routes![index]).launch();
}
```

When running the example in the console, a few visual issues occur: colours and underlines are misaligned. Some lines have text cut off from the end. Resizing the terminal causes the missing text to reappear.

It seems to be only present on lines with preceding emojis. I don't think it's related to the missing glyphs for the emojis though, as in vscode's terminal the mounting line has the correct glyph but is still misaligned. 

Standalone command window:

![image](https://user-images.githubusercontent.com/1830331/64429880-e7999600-d0ae-11e9-9e83-1574c3ae4b65.png)

VS Code integrated terminal:

![image](https://user-images.githubusercontent.com/1830331/64431481-722fc480-d0b2-11e9-8bef-55faeebbb97b.png)

**Comment by SergioBenitez** [comment]
Does the issue go away when you disable coloring with `ROCKET_CLI_COLORS=off`?

**Comment by Alexendoo** [comment]
Yeah, no issues when it's disabled

**Comment by Alexendoo** [comment]
From testing a bunch of characters with

```rust
fn test(ch: char) {
    println!("{}\x1b[35mtext\x1b[0m", ch)
}
```

The issue seems to appear every time a character ≥ U+10000 appears, so anything 4 bytes in UTF-8

e.g. `㐀`, the first character in CJK Unified Ideographs Extension A is fine because it's U+3400, but `𠀀`, the first of Extension B is not (U+20000)

Similarly Emoji below U+10000 such as `☔`, `⚽` etc don't exhibit this bug in particular

I would imagine this is due to it being the point where UTF-16 encoded codepoints become surrogate pairs

**Comment by jebrosen** [comment]
For some more data points: this problem appears in `conhost` windows (both cmd and powershell) and does not appear in the (preview) Windows Terminal app. Both color and emoji are disabled entirely in the PowerShell ISE and other terminals such as Git Bash or msys (`mintty.exe`).

I am actually a bit surprised that vscode's integrated terminal exhibits the same problem.

A quick search suggests it might even be a regression in some windows versions, according to comments in https://github.com/Microsoft/Terminal/issues/190

**Comment by EddyHamzich** [comment]
I have the same issue and its driving my OCD insane because even if i set a global env variable ROCKET_CLI_COLORS= 0 in my Rocket.toml I still get the emoji's and this bug. I dont want to open a seperate issue but I hope someone can tell me why that doesnt turn off the emoji's ? I just started with Rocket today so I might be doing something wrong. When I cargo run i see **"[extra] ROCKET_CLI_COLORS=off"** in the terminal but it still doesnt remove emoji's.

**Comment by jebrosen** [comment]
`ROCKET_CLI_COLORS=0` is an environment variable, not a config file setting. I don't think there is currently an equivalent setting for `Rocket.toml`, unfortunately.

**Comment by EddyHamzich** [comment]
lol I literally started with Rust today so i dont even know how to setup an environment variable. Can you tell exactly where I'm supposed to include that line of code ? I couldn't find that on the Rocket.rs website.

**Comment by jebrosen** [comment]
In `cmd.exe`, `set ROCKET_CLI_COLORS=0` before running your program should work. I'm not sure with PowerShell. If you want it to be persistent / for all applications, you can do that as well somewhere in System Properties.

**Comment by EddyHamzich** [comment]
yeah that works! thanks man... ahh I wish i didn't have OCD.

**Comment by jebrosen** [comment]
I'm labeling this as an upstream regression for now (see comments starting at https://github.com/microsoft/terminal/issues/190#issuecomment-452663010 ). If things don't improve we can do something more extreme like always disabling emoji display on windows.

**Comment by gastrodon** [comment]
I'm also having issues with jacked up fonts due to not having emoji fonts installed, and `export ROCKET_CLI_COLORS=off` is working for me. Is there a flag that I can set that will tell it to log with color, but without emojis?
