### ISSUE TITLE
The require syntax extensions is not include now ? It's very necessary to use nightly version of Rust today ?

### ISSUE THREAD

**Issue by mrdev023** [SergioBenitez/Rocket#1126]
Error 
error: failed to run custom build command for `rocket_codegen v0.4.2`

Caused by:
  process didn't exit successfully: `/home/florian/IdeaProjects/TestRocket/target/debug/build/rocket_codegen-fa289f87457242e4/build-script-build` (exit code: 101)
--- stderr
Error: Rocket (codegen) requires a 'dev' or 'nightly' version of rustc.
Installed version: 1.37.0 (2019-08-13)
Minimum required:  1.33.0-nightly (2019-01-13)

**Comment by jhpratt** [comment]
Rocket 0.5 will compile on stable. Nightly is currently necessary for a variety of reasons. See #19 for more details, which is something you'd have found if you searched. The error message is quite clear that nightly is needed to compile.

**Comment by jebrosen** [comment]
Removing the features that require nightly are breaking changes, so Rocket 0.4 will continue to require nightly to build. But we are committed to making Rocket 0.5 compile on stable rust.
