### ISSUE TITLE
Error: A table named `databases` was not found for this configuration

### ISSUE THREAD

**Issue by calvinbrown085** [SergioBenitez/Rocket#1127]
## Bug Reports

Hello!
```
[dependencies]
rocket = "0.4.0"
prometheus = "0.6"
lazy_static = "1.3.0"
rand = "0.6"
reqwest = "0.9.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
postgres = "0.15.2"
r2d2_postgres = "0.15.0-rc.1"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["json", "postgres_pool"]
```
Here is my `Cargo.toml`

```
[global.databases]
postgres = { url = "postgres://postgres@localhost:5432" }
```

Here is my `Rocket.toml`

```
#[database("postgres")]
struct PgConn(postgres::Connection);
 rocket::custom(http_config)
            .mount("/", routes![index, hello, ping, get_user, insert_person, get_person])
            .attach(PgConn::fairing())
            .launch();
```
This is the code to start the Http Application.

  2. This is on MacOS

  3. I'm getting a weird error i've seen on other issues, but I cannot seem to reproduce the same steps to get it working

**Comment by SergioBenitez** [comment]
You're using a custom configuration, `http_config`, to start up the Rocket application via `rocket::custom(http_config)`. This means that your `Rocket.toml` file will be ignored entirely. As such, unless the `http_config` configuration structure has an associated extra named `databases` that is a table with the relevant information, your application is simply misconfigured.

**Comment by calvinbrown085** [comment]
Interesting. I will look at possibly not using a custom config. Thanks for taking a look @SergioBenitez !
