### ISSUE TITLE
Traits in State?

### ISSUE THREAD

**Issue by synical** [SergioBenitez/Rocket#1128]
Rocket 0.4.2

I'm new to Rust/Rocket and am running into something I'm not sure how to solve.

(If this is the wrong place for this let me know and I'm happy to ask elsewhere!)

What I'm trying to do is have a Rocket route take a trait that defines a method that will store some value in a store, the idea being that this store could be implemented by several things e.g. an in memory store, a database etc.

```
trait Store {
    fn store_item(self, s1: String, s2: String) -> Result<(), Box<dyn Error>>;
}

struct MemoryStore {
    map: HashMap<String, String>
}

impl MemoryStore {
    pub fn new() -> MemoryStore {
        MemoryStore {
            map: HashMap::new()
        }
    }
}

impl Store for MemoryStore {
    fn store_item(mut self, s1: String, s2: String) -> Result<(), Box<dyn Error>> {
        self.map.insert(s1, s2);
        Ok(())
    }
}

#[post("/test")]
fn test_route(store: State<&dyn Store>) -> Result<String, Status> {
    store.store_item(String::from("Some"), String::from("String"));
    Ok(String::from("OK"))
}

fn main() {
    let store = MemoryStore::new();
    let config = Config::build(Environment::Development)
        .address("127.0.0.1")
        .port(8000)
        .finalize()
        .expect("Failed to start webserver!");

    rocket::custom(config)
    .mount("/", routes![test_route])
    .manage(store) 
    .launch();
}
```

Doesn't look like I'm able to do this:

```
_^ `dyn Store` cannot be shared between threads safely
   |
   = help: the trait `std::marker::Sync` is not implemented for `dyn Store`
   = note: required because of the requirements on the impl of `std::marker::Send` for `&dyn Store`
   = note: required by `rocket::State`
```

Reading around, I couldn't find anything obvious that showed how to solve this but I'm figuring this is just sheer Rust/Rocket ignorance on my part. Is any one able to show me where I am going wrong?

Thanks

**Comment by jebrosen** [comment]
This is doable, but you need to solve two problems:

1) The managed state must be a concrete type. You can do this by putting it behind a pointer such as a `Box`. The `&dyn Store` you used above is also a concrete type, but you can't manage one of those unless it's `&'static`. In this case, `Box<dyn Store>` should be a suitable alternative: `.manage(Box::new(store) as Box<dyn Store>)` and `store: State<Box<dyn Store>>`. You could also use an enum if you know all possible `Store` types ahead of time.
2) The managed state must be thread-safe, in particular `Send` and `Sync`. This can be accomplished by:
    * making them supertraits of Store: `trait Store: Send + Sync { }`. This requires each implementor of `Store` to do its own internal synchronization.
    * using `Box<dyn Store + Send + Sync>` everywhere instead of `Box<dyn Store>`. This requires instances of `Store` to be `Send + Sync` when you put them in managed state, but single-threaded users of the `Store` trait are unaffected.
    * using a synchronization tool such as `Mutex` or `RwLock` around the data: `.manage(Mutex::new(Box::new(store) as Box<dyn Store>))` and `state: Mutex<Box<dyn Store>>`

**Comment by synical** [comment]
@jebrosen thanks for the prompt response!

Making a bit more sense now, however, I think I'm still not quite there.

From what I gathered from your response, wrapping the pointer to the concrete store in a Mutex satisfies Sync + Send as Mutex is what implements that?

I modified the code to look like the below:

```
trait Store: Send + Sync {
    fn store_item(self, s1: String, s2: String) -> Result<(), Box<dyn Error>>;
}

struct MemoryStore {
    map: HashMap<String, String>
}

impl MemoryStore {
    pub fn new() -> MemoryStore {
        MemoryStore {
            map: HashMap::new()
        }
    }   
}

impl Store for MemoryStore {
    fn store_item(mut self, s1: String, s2: String) -> Result<(), Box<dyn Error>> {
        self.map.insert(s1, s2);
        Ok(())
    }   
}

#[post("/test")]
fn test_route(store: State<Mutex<Box<dyn Store>>>) -> Result<String, Status> {
    let locked_store = store.lock().unwrap();
    locked_store.store_item(String::from("Some"), String::from("String"));
    Ok(String::from("OK"))
}

fn main() {
    let store = MemoryStore::new();
    let config = Config::build(Environment::Development)
        .address("127.0.0.1")
        .port(8000)
        .finalize()
        .expect("Failed to start webserver!");

    rocket::custom(config)
    .mount("/", routes![test_route])
    .manage(Mutex::new(Box::new(store) as Box<dyn Store>) )
    .launch();
}
```

Which results in:

```
38 |     locked_store.store_item(String::from("Some"), String::from("String"));
   |     ^^^^^^^^^^^^ move occurs because value has type `dyn Store`, which does not implement the `Copy` trait
```
Along the right tracks? Assuming I need to somehow get a reference to the store here?

**Comment by jebrosen** [comment]
For that first error, `fn store_item(mut self, ...)` should be `fn store_item(&mut self, ...)`.

You don't need both `Store: Send + Sync` and `Mutex<Box<dyn Store>>`, as the `Mutex` does what is necessary to be `Sync`.

**Comment by synical** [comment]
@jebrosen ah yes, updating to `&mut self` and removing the `Send` has done the trick. Compiles and runs now!

Thanks for the timely assistance, much appreciated!

**Comment by jebrosen** [comment]
You're very welcome!

It sounds like this is resolved.
