### ISSUE TITLE
How to redirect from error catcher?

### ISSUE THREAD

**Issue by FliegendeWurst** [SergioBenitez/Rocket#113]
Something simple like
```rust
#[error(401)]
fn not_authorized() -> Redirect {
    Redirect::to("/login")
}
```
doesn't seem to work?

**Comment by marcusball** [comment]
I don't believe this is possible, as the `Redirect` responses use [status code, header-based redirects](https://api.rocket.rs/rocket/response/struct.Redirect.html). Your example is basically trying to send a 401 and a 303 status at the same time. 

I'm not sure if there's a better answer, but, my first thought is to just return a page with a Javascript redirect to the desired page.

**Comment by SergioBenitez** [comment]
I can't tell if this is a bug or a feature.

Rocket currently rewrites the status code of every response from an error catcher to be that of the caught error. But I think the right behavior is to use the catcher's status code if there is one, to allow something like this.

I'll call this an "enhancement" request and push a fix in a bit.

**Comment by SergioBenitez** [comment]
Unfortunately, this is a breaking change, so this will be in 0.2. I've already made several breaking changes, so 0.2 will come sooner than expected!

**Comment by FliegendeWurst** [comment]
Thanks for taking care of my request so fast!
