### ISSUE TITLE
Question for A Error: Trying to get Cookie from Request

### ISSUE THREAD

**Issue by migeruj** [SergioBenitez/Rocket#1132]
## Question
Hi im new on Rust and Rocket web framework.
I', trying to get and add a cookie(JWT) to the request.
But i'm having this error message on Compiling:
```

   |
80 | fn index(cookies: &Cookies) -> Result<Json<Respuesta>> {
   |          ^^^^^^^^^^^^^^^^^ the trait `rocket::request::FromRequest<'_, '_>` is not implemented for `&rocket::http::Cookies<'_>`
   |
   = help: the following implementations were found:
             <rocket::http::Cookies<'a> as rocket::request::FromRequest<'a, 'r>>

```
This is the code. 

```
#[get("/")]
fn index(cookies: &Cookies) -> Result<Json<Respuesta>> {
    static KEY: &'static [u8; 16] = include_bytes!("../.tendence");
    let token = match cookies.get("jwt").map(|msg| msg.value()) {
        Some(jwt) => jwt,
        None => return Ok(Json(Respuesta {status: "Denied".to_string(), result: "NOPE GTFO 420".to_string()})),
    };

    let token_data = decode::<UserRolesToken>(&token, KEY, Algorithm::HS256).unwrap();

    let mut context = HashMap::new();
    context.insert("name", token_data.claims.user.clone());

    if token_data.claims.has_role("admin") {
        context.insert("admin", "true".to_string());
    }

    Ok(Json(Respuesta{status: "Accepted".to_string(),result: &context}))
}
```

I would like to know how to implement this structure <rocket::http::Cookies<'a> as rocket::request::FromRequest<'a, 'r>>in my code (i guess then is the solution), i know how to use impl in structures but i dont know how to do it in this case. Or if i have a struct error on the code I would really appreciate knowing what my mistake is when implementing the cookie

  1. I'm using Rocket 0.4.2

  2. I'm based on the Api guide in Rocket and in this git repository for implement the jwt generator.  [https://github.com/skinkade/rocket-jwt-roles-demo/](url)

Thanks for your time.

**Comment by jebrosen** [comment]
`FromRequest` is implemented for `Cookies`; not `&Cookies`. So replacing `&Cookies` with `Cookies` (or `Cookies<'_>`) should work.

That repository uses `rocket = "0.1.5"`, which is quite old and probably has some other code that does not work with recent versions of Rocket.

**Comment by migeruj** [comment]
> `FromRequest` is implemented for `Cookies`; not `&Cookies`. So replacing `&Cookies` with `Cookies` (or `Cookies<'_>`) should work.
> 
> That repository uses `rocket = "0.1.5"`, which is quite old and probably has some other code that does not work with recent versions of Rocket.

Wow! It works, i have to change a few things about cookies. Like .find by .get Thanks for your time.
