### ISSUE TITLE
[Feature Request] Implement some form of Fairing::on_listening

### ISSUE THREAD

**Issue by mon** [SergioBenitez/Rocket#1136]
I'm using webview-rs as the GUI for a desktop application, and Rocket for the static server and API wrapper to system things (HidApi, in my case).

I currently use an `AdHoc::on_launch` fairing to extract the ephemeral port and open the webview to the UI.

However, sometimes the webview wins the race and the server hasn't actually begun to accept connections yet, resulting in a "can't connect" error. I can add a small delay in my handler, but it's hacky.

It would be useful to have a fairing that can fire when I know the server is ready to accept connections.

**Comment by jebrosen** [comment]
> sometimes the webview wins the race and the server hasn't actually begun to accept connections yet

That is surprising to me. `on_launch` happens after the socket is already bound, so at worst I think you should see a connection take a bit longer than usual while the server finishes initializing.

We could try adding an `on_listening` point or just have `on_launch` run a bit later if it is necessary, but I think it will have to wait for rocket 0.5 which will use hyper 0.13.

**Comment by mon** [comment]
Fantastic news! Thanks for the fix, it looks like it was some effort

**Comment by SergioBenitez** [comment]
@mon It fell out of other changes. But note, however, that `on_liftoff` is _still_ called when the socket is bound but before the first connection is accepted. You can now, however, `spawn()` a task that tries to connect to the server which will connect as soon as all of the liftoff fairings run.
