### ISSUE TITLE
Shared context data for templates

### ISSUE THREAD

**Issue by sazzer** [SergioBenitez/Rocket#1139]
Apologies if this is already possible, but if so I couldn't see how from the docs.

When rendering templates - using `Template::render()` and `Template::fairing()`, it can be very useful on occasion to have data provided to the templates but coming from other fairings or request guards and not from the handlers. This would then allow common data to be provided without duplication in the handlers.

As an example, data representing the current user could be provided to render the users name in the page, but this is independent of the request being performed.

**Comment by jebrosen** [comment]
I'm not inclined to implement an implicit or ambient "template context builder" inside `rocket_contrib` itself, but there are at least a few ways to approach this:

* Make a type such as `CommonContext` and implement `FromRequest` for that. It could be merged with route-specific context or added as `context.common`.
* Make a `Context` type wrapping a `HashMap` or `serde_json::Value`, and put it in [request-local state](https://rocket.rs/v0.4/guide/state/#request-local-state). Fairings and request guards can insert  values into it, and routes can extract that state and merge/or add it to the template-specific context.
* Combine the two ideas above: have fairings write to request-local state, and implement `CommonContext` in such a way that it reads those values back out.

**Comment by SergioBenitez** [comment]
This seems ripe for exposing vulnerabilities akin to mass-assignment. I would suggest that you propose this feature to template engines themselves; this does not seem like something Rocket should expose. Furthermore, I agree with @jebrosen that there are fairly ergonomic ways to accomplish the same without an explicit feature.
