### ISSUE TITLE
Add global headers

### ISSUE THREAD

**Issue by TheNeikos** [SergioBenitez/Rocket#114]
I want to add CORS headers to my site (or any other really), so far the only way I can see to do is, is to wrap each and every response with a type. 

Is there a simpler way to do this?

**Comment by SergioBenitez** [comment]
No simple way to do this quite yet; the solution you propose is the current best. Soon, however! But we have an issue tracking this already: #25. Closing this in favor of that one.

**Comment by TheNeikos** [comment]
Ah yes, I looked for Global, but not CORS. Thanks

**Comment by sebasmagri** [comment]
I believe this could be handled like a related but different issue. Global headers might be handled with something like a global middleware.
