### ISSUE TITLE
Rocket_codegen error when compiling

### ISSUE THREAD

**Issue by listofbanned** [SergioBenitez/Rocket#1142]
When I run `cargo build` shows me:

```
 --> src/main.rs:2:11
  |
2 | #![plugin(rocket_codegen)]
  |           ^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `*****`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I use the following nightly `rustc 1.39.0-nightly (7efe1c6e6 2019-09-17)`

It's a nightly version issue?,  maybe Rocket doesn't support it?
Many thanks.

**Comment by SergioBenitez** [comment]
You have not included the basic information we request for issues, in particular, the version of Rocket you're using. Nevertheless, I assume you've upgraded from 0.3 to 0.4 but have not read the CHANGELOG. Please see https://rocket.rs/v0.4/news/2018-12-08-version-0.4/#codegen-rewrite.

**Comment by listofbanned** [comment]
> You have not included the basic information we request for issues, in particular, the version of Rocket you're using. Nevertheless, I assume you've upgraded from 0.3 to 0.4 but have not read the CHANGELOG. Please see https://rocket.rs/v0.4/news/2018-12-08-version-0.4/#codegen-rewrite.

Many thanks!
