### ISSUE TITLE
Serve static 404

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [SergioBenitez/Rocket#1148]
First off I'd like to apologize because I'm sure this exist somewhere but I was unable to find it in doc.rs, these github issues, or rocket.rs.

I'd like to serve a static 404.html for every 404 response. Could someone show me a link to go to or directions on how to accomplish this.

**Comment by jebrosen** [comment]
The best fit to your need here is probably use an [error catcher](https://rocket.rs/v0.4/guide/requests/#error-catchers):

```rust
#[catch(404)]
fn not_found() -> NamedFile {
    NamedFile::open("404.html").expect("error response file")
}
```

**Comment by Th3Whit3Wolf** [comment]
You are the man! Also I think it would be a good idea to add this in the examples for static files.
