### ISSUE TITLE
question: authorization, typed headers and hyper types 

### ISSUE THREAD

**Issue by sclasen** [SergioBenitez/Rocket#1150]
Most everything seems pretty strongly typed in rocket, but I found myself having to write a lot more string related code than I was expecting to do something as simple request guard for http basic-auth.

Is there a plan for something like being able to get typed header data out of the request/put it into the response? something like:

`let a: Result<Authorization,Error> = request.header::<Authorization>()` 

as part of going from `request.headers().get_one("Authorization")`  to something typed that I can use in a guard, I also dipped into the 'vendored' hyper classes since that does have the notion of typed headers including Authorization with Basic and Bearer schemes.  Some of the docs seem to warn against using the hyper types, is there an alternative Ive missed?

## Questions

Any questions _must_ include:

  1. The version of Rocket this question is based on, if any.

0.4.2

  2. What steps you've taken to answer the question yourself.

Reading Docs and Code and Issues

  3. What documentation you believe should include an answer to this question.

some docs on how to implement authn/z in rocket.

**Comment by jebrosen** [comment]
The response side is pretty easy to deal with - all of the reexported header types implement `Into<rocket::http::Header>` and can therefore be used in `Response::set_header`.

On the request side, I unfortunately don't see an obvious way to parse headers aside from hyper's [parse_header function](https://docs.rs/hyper/0.10.16/hyper/header/trait.Header.html#tymethod.parse_header) which would require you to copy the header data a time or two.

It's worth mentioning that typed headers might be removed or replaced with a different implementation in 0.5 (see #1067), in which case you will need to do manual parsing or adapt to a different typed header library.

**Comment by sclasen** [comment]
Thanks @jebrosen

**Comment by jebrosen** [comment]
That would re-export it, but I'm not too happy about the idea of reexporting even more from hyper.

You can add `hyper` (0.10) as a dependency of your own crate and you will be able to import it from there.

**Comment by sclasen** [comment]
Will do, thanks!
