### ISSUE TITLE
Testing: Fairing::on_launch not called by Client

### ISSUE THREAD

**Issue by CugeDe** [SergioBenitez/Rocket#1154]
# Environment
- OS: Archlinux 5.2.9
- Rocket: 0.4
- cargo / rustc: 1.39.0-nightly

# What ?
The testing API of rocket doesn't allow to test Fairings having an `on_launch` callback.

## To reproduce

```rust
#![feature(proc_macro_hygiene)]

#[macro_use] extern crate rocket;

use std::sync::atomic::{AtomicBool, Ordering};

use rocket::{
    Data,
    fairing::{
        Fairing,
        Kind,
        Info
    },
    Request,
    Rocket
};

struct TestFairing {
    initialized: AtomicBool
}

impl TestFairing {
    pub fn new() -> Self {
        Self {
            initialized: AtomicBool::new(false)
        }
    }
}

impl Fairing for TestFairing
{
    fn info(&self) -> Info
    {
        Info {
            name: "TestFairing for on_launch callback",
            kind: Kind::Launch | Kind::Request
        }
    }

    fn on_launch(&self, _rocket: &Rocket)
    {
        self.initialized.store(true, Ordering::Relaxed);
    }

    fn on_request(&self, _request: &mut Request<'_>, _data: &Data)
    {
        if self.initialized.load(Ordering::Relaxed) == false {
            panic!("This should have been set to true in `Fairing::on_launch`");
        }
    } 
}

#[get("/<name>/<age>")]
fn hello(name: String, age: u8) -> String {
    format!("Hello, {} year old named {}!", age, name)
}

mod on_launch_fairing {
    use super::*;
    use rocket::local::Client;

    #[test]
    fn test_on_launch() {
        let rocket = rocket::ignite()
            .attach(TestFairing::new())
            .mount("/hello", routes![hello]);
        let client = Client::new(rocket).expect("valid rocket instance");

        let req = client.get("/hello/John%20Doe/37");
        let mut response = req.dispatch();
        let _body = response.body_string();

        // At this point, if the test succeed, no panic happened
    }
}
```

# Why ?

As you can see below, in `Rocket::launch`, `self.fairings.handle_launch(&self);` will trigger the `on_launch` callback of the attached fairings.

```rust
pub fn launch(mut self) -> LaunchError {
        self = match self.prelaunch_check() {
            Ok(rocket) => rocket,
            Err(launch_error) => return launch_error
        };

        /// ...

            // Freeze managed state for synchronization-free accesses later.
            self.state.freeze();

            // Run the launch fairings.
            self.fairings.handle_launch(&self);

        /// ...
}
```

However, in `rocket::local::Client` which is used for testing, only `Rocket::prelaunch_check()` is used. (`new(...)` calls `_new(...)`)

```rust
fn _new(rocket: Rocket, tracked: bool) -> Result<Client, LaunchError> {
    let cookies = match tracked {
        true => Some(RwLock::new(CookieJar::new())),
        false => None
    };

    Ok(Client { rocket: rocket.prelaunch_check()?, cookies })
}
```

It would be nice to include a call to `Rocket.fairings.handle_launch()` in a Client start by maybe providing a test-only launch method usable by the Client.

Thanks for reading.

CugeDe

**Comment by jebrosen** [comment]
I don't think this is explicitly stated anywhere, but IMO `on_launch` is only useful for notices or debugging, or for one or two things that can only be checked after a real launch. What is a real use case for an `on_launch` fairing that does something useful to tests, that isn't more suited for `on_attach`?

**Comment by CugeDe** [comment]
Now that I used Rocket a little more in deep, I think I understood why you answered that.

From you POV, Rocket must be entirely initialized at the end of `on_attach` while I finished initialization of my Fairings inside `on_launch`. This is the reason why `on_launch` receives a immutable ref to Rocket; because nothing must be edited in this callback.

I saw `on_launch` as the right moment to initialize my fairing because, IMO, if Rocket is not launched, Fairings have no reason to initialize. However, you chose to do this way and it is written in the doc but it feels strange to me to initialize even before being sure that Rocket will launch.

So, yes there is no real use case of an `on_launch` test but it also does not cost anything to add it, right ? But it is also written that in the doc: "A launch callback can be a convenient hook for launching services related to the Rocket application being launched". So you could imagine a test checking that services started well... The only real use-case, IMO, is to wait and check initialization of services if they initialize asynchronously.

**Comment by jebrosen** [comment]
> IMO, if Rocket is not launched, Fairings have no reason to initialize

There's a circular problem here - if an (attach) fairing fails to initialize, rocket can't launch! So it is heavily dependent on what the fairing does. If a fairing needs "veto power" over application startup or is truly necessary in order for the application to work it should be in `on_attach`. If the fairing needs a "fully finished" Rocket instance to inspect it should be in `on_launch`.

> So, yes there is no real use case of an `on_launch` test but it also does not cost anything to add it, right?

I don't think it's mentioned explicitly in the docs, but launch fairings can currently rely on the fact that Rocket is actually listening for traffic and we would be breaking that with this change. That would be problematic if a fairing does something like open a web browser or send a notification somewhere with the listening port number.

@SergioBenitez do you have anything to add wrt running `on_launch` in tests?

**Comment by SergioBenitez** [comment]
Apologies; I never got to this.

I'm not convinced one way or another. I'm inclined to suggest that `on_launch()` only fires when we spin up a sever. At minimum, we should document this. However, if there is a compelling reason why `on_launch()` should be called by `Client`, I'm all ears.
