### ISSUE TITLE
Database Sync impl missing inside Juniper schema

### ISSUE THREAD

**Issue by Y0hy0h** [SergioBenitez/Rocket#1157]
Using `rocket = "0.4.2"`. Bug reproduced on Windows 10 and Elementary OS (Ubuntu-based). I've tested on multiple nightly versions.

I'm encountering a bug that appears very similar to #578. Unfortunately, I don't understand what to do about it from their [last comment](https://github.com/SergioBenitez/Rocket/issues/578#issuecomment-369492184).

I'm trying migrate a ReST API to GraphQL, for which I employ `juniper`. It's backed by a SQLite database accessed through `diesel`, for which I use `rocket`'s integration. However, the code refuses to compile, because the `Schema` type that I need to pass to `juniper` is not deemed thread-safe:
```
error[E0277]: `std::cell::Cell<i32>` cannot be shared between threads safely
  --> src/api.rs:27:1
   |
27 | / fn post_graphql_handler(
28 | |     context: Database,
29 | |     request: juniper_rocket::GraphQLRequest,
30 | |     schema: State<Schema>,
31 | | ) -> juniper_rocket::GraphQLResponse {
32 | |     request.execute(&schema, &context)
33 | | }
   | |_^ `std::cell::Cell<i32>` cannot be shared between threads safely
   |
   = help: within `juniper::schema::model::RootNode<'static, store::Query, juniper::types::scalars::EmptyMutation<store::Context>>`, the trait `std::marker::Sync` is not implemented for `std::cell::Cell<i32>`
   = note: required because it appears within the type `diesel::connection::AnsiTransactionManager`
   = note: required because it appears within the type `diesel::SqliteConnection`
   = note: required because it appears within the type `rocket_contrib::databases::r2d2::Conn<diesel::SqliteConnection>`
   = note: required because it appears within the type `std::option::Option<rocket_contrib::databases::r2d2::Conn<diesel::SqliteConnection>>`
   = note: required because it appears within the type `diesel::r2d2::PooledConnection<diesel::r2d2::ConnectionManager<diesel::SqliteConnection>>`
   = note: required because it appears within the type `store::db::Database`
   = note: required because it appears within the type `store::Context`
   = note: required because it appears within the type `std::marker::PhantomData<store::Context>`
   = note: required because it appears within the type `juniper::types::scalars::EmptyMutation<store::Context>`
   = note: required because it appears within the type `juniper::schema::model::RootNode<'static, store::Query, juniper::types::scalars::EmptyMutation<store::Context>>`
   = note: required by `rocket::State`
```
This is one of 9 errors, all being about a missing `Sync` impl that can be traced back to `rocket::State`'s requirements. The full code is available at https://github.com/Y0hy0h/lindyhop-aachen/tree/graphql.

Curiously, I can run https://github.com/ELD/rocket-juniper-example just fine after copying the dependencies from my code into their `Cargo.toml`. But I can't figure out what I did differently than them. I use the `Database` struct instead of the `SqliteConnection` in the `Context` just as them, and I request the `Database` and `State<Schema>` as they do.

I hope this is the right place to open this issue. Maybe you can point me to where the problem may lie.

**Comment by jebrosen** [comment]
You might also look at https://github.com/davidpdrsn/graphql-app-example as an example of juniper in rocket.

Unfortunately I haven't yet put the time in to try working with juniper, and there's enough generated code involved that I can't seem to figure anything out from looking at the docs, either.

**Comment by Y0hy0h** [comment]
@jebrosen Thanks for the example, that's a very different approach. I haven't tried running it, because I the example I linked above is more similar to my code and already runs. The biggest difference in your example is that the GraphQL `Schema` type is auto-generated from a GraphQL file, instead of being explicitely constructed in Rust. That's, however, the type that seems to cause the problems, so I couldn't pull much more new information out of looking at that example.

**Comment by jebrosen** [comment]
Sorry that example didn't help after all.

One thing you seem to be doing differently from the example you posted has to do with the `MutationRoot`. @ELD, can you explain this difference and why it matters? It feels like I have to learn GraphQL in order to understand how these types actually work.

**Comment by ELD** [comment]
@Y0hy0h It's been awhile since I've experimented with GraphQL via Juniper. I should probably update my example now that they've expanded their use of procedural macros. I don't have time to look into it right now as I'm at work, but I'll try to provide more support this evening.

My initial guess is that their procedural macro doesn't take something into account that my example isn't affected by since I constructed the `Schema` type myself. This is all from memory, though, so I don't know if that's correct. I'll try to dig into it a little more, though.

**Comment by Y0hy0h** [comment]
@jebrosen The `Mutation` type seems to be it. If instead of using the `juniper::EmptyMutation` I simply do
```rust
pub struct Mutation;

#[juniper::object(Context=Store)]
impl Mutation {}
```
then it compiles.

So this definitely looks like an issue with `juniper` to me. I will push this issue upstream.

Thanks a lot for all you kind help!
