### ISSUE TITLE
rocket::request::FromRequest is not implemented for rocket::Request

### ISSUE THREAD

**Issue by incker** [SergioBenitez/Rocket#1158]
This code works:

    #[catch(404)]
    fn not_found(req: &rocket::Request) -> String {
        format!("{:?}", "")
    }

I have seen an [example](https://github.com/SergioBenitez/Rocket/blob/v0.4/examples/errors/src/main.rs)

But this code does not:

    #[get("/test-url")]
    fn not_found(req: &rocket::Request) -> String {
        format!("{:?}", "")
    }

As I get the error:

    fn not_found(req: &rocket::Request) -> String {
                 ^^^^^^^^^^^^^^^^^^^^^ the trait `rocket::request::FromRequest<'_, '_>` is not implemented for `&rocket::Request<'_>`

I am not sure is it a bug or not?
The aim is to get real ip form request like `req.real_ip()` (from [docks)](https://api.rocket.rs/v0.4/rocket/struct.Request.html#method.real_ip)
Or the only solution is to wrap it in own Request Guards?

Forward thank you for answer,
And thank you, Sergio, for great framework!

**Comment by jebrosen** [comment]
This is intentionally not implemented (see also https://github.com/SergioBenitez/Rocket/pull/675#issuecomment-400333243). Instead, you should implement a request guard that extracts only the data required.

**Comment by incker** [comment]
Ok. Done) Thank you

    pub struct NginxRealIP(IpAddr);
    
    impl<'a, 'r> FromRequest<'a, 'r> for NginxRealIP {
        type Error = ();
        fn from_request(request: &'a Request<'r>) -> request::Outcome<Self, Self::Error> {
            match request.real_ip() {
                Some(ip) => Outcome::Success(NginxRealIP(ip)),
                None => Outcome::Failure((Status::from_code(401).unwrap(), ()))
            }
        }
    }

**Comment by oliver-impero** [comment]
@jebrosen What if I need to call `request.local_cache(..)` inside an endpoint handler? Then it's not possible to solve this with a guard.
