### ISSUE TITLE
Wildcard routes?

### ISSUE THREAD

**Issue by leeola** [SergioBenitez/Rocket#1160]
After some searching, it _appears_ wildcard routes are not possible with Rocket. That is to say, I cannot implement `#[get("/*")]` and have it match every possible route. After some research, the best scenario I came up with was to match segments as a `PathBuf`, and ignore the argument entirely. Example:

```
#[get("/<_segs..>")]
fn redirect(uri: &Origin, domain: State<Domain>, _segs: PathBuf) -> Redirect {
  Redirect::permanent(format!("https://{}{}", domain.0, uri))
}
```

This seems less than obvious, and also wasteful as I have to imagine a PathBuf is being safely allocated when it's entirely unneeded. Alternatively, if Rocket allowed something like:

```
#[get("/*")]
fn redirect(uri: &Origin, domain: State<Domain>) -> Redirect {
  Redirect::permanent(format!("https://{}{}", domain.0, uri))
}
```

It would solve this more cleanly. Though perhaps the more "Rocket-y" way to solve this would be ignoring params? Ie, `#[get("/<_..>")]`. Thoughts?

As an aside, what I first reached for was a `catch(404)` handler, however that seems impossible  for this use case because the above example uses `State<Domain>` to inform the redirect, and catch handlers only allow a single Request arg.

Hopefully I'm not missing something obvious. Thank you.

**Comment by jebrosen** [comment]
> This seems less than obvious, and also wasteful as I have to imagine a PathBuf is being safely allocated when it's entirely unneeded.

If you don't need the actual data, `Segments` is the non-allocating multi-segment type.

> Alternatively, if Rocket allowed something like: (...) It would solve this more cleanly.

I actually somewhat like the idea `<_..>` for "ignored" path parameters. The main drawback is that it (IMO) looks absolutely bizarre.

> As an aside, what I first reached for was a `catch(404)` handler, however that seems impossible for this use case because the above example uses `State<Domain>` to inform the redirect, and catch handlers only allow a single Request arg.

You should be able to use `request.guard::<State<Domain>>()` in a catcher.

**Comment by leeola** [comment]
> If you don't need the actual data, Segments is the non-allocating multi-segment type.

Great idea, thanks!

> You should be able to use request.guard::<State<Domain>>() in a catcher.

Admittedly I didn't even try, I read that I couldn't from the documentation:


> Unlike route request handlers, catchers take exactly zero or one parameter. If the catcher takes a parameter, it must be of type &Request


After trying it, it fails with an error:

```
invalid number of arguments: must be zero or one
```

Regardless, I think this post was _mostly_ a feature request, not a question - however since you pointed out that Segments can be captured with no allocation I think that satisfies my desire to capture a wildcard with no allocation.

If it's decided that something more than ignoring segments should be implemented in Rocket, ala `/<_..>` or what have you, feel free to reopen this issue. However I think my requirements are satisfied enough that this issue/feature-request can be closed.

Thanks :)

**Comment by jebrosen** [comment]
> After trying it, it fails with an error:

Here's a more complete example of what I was going for:

```rust
#[catch(404)]
fn not_found(request: &Request) -> String {
    format!("State was {}", request.guard::<State<Domain>>().something())
}
```

**Comment by leeola** [comment]
Oh, awesome! Didn't even know that API was a possibility in Rocket, though it totally makes sense. Thanks again :)
