### ISSUE TITLE
Question about fairings

### ISSUE THREAD

**Issue by Ralthazoth** [SergioBenitez/Rocket#1161]
I have read some of the documentation for this project but..

```
fn main() {
// some code removed, user_database is an Arc<Mutex<Vec<User>>>
    let mut DatabaseObject = MyFairing{ user_database: vec![] };
    rocket::ignite()
        .attach(DatabaseObject)
        .mount("/", routes![user]).launch();
}

```

I need to modify that vec when data is posted, preferably something like so

```
#[post("/api/getuser", data = "<data>")]
fn api_getUser(database: MyFairing, data: Json<generic_request>) -> Json<User>
{
    let clone = database.user_database.clone();
    let mut lock = *clone.lock().unwrap();


    lock.data.push(User{ user_ID: 0, name: "Anonymous".to_string(), password: "".to_string(), private: false, banned: false, banned_by: 0, ban_reason: "".to_string() });

    return Json(lock.data[0]);
}
```

Im not interested in using SQL in any way, when I went to use this project for this and implementing a custom fairing (which appeared to be the way to go about this) I run into needing to implement a fairing kind (unused?), and then implementing a from_request for MyFairing, which looks like it is intended to create an instance of the object coming into api_getUser as database... This doesn't seem right to need so much boilerplate, or seem right in general - is there an easier way of getting to this goal? Is there a way to simply share an Arc to 'routes'? Sorry if this is a very obvious question too, I have only been writing in Rust for a few days!

**Comment by jebrosen** [comment]
[Managed state](https://rocket.rs/v0.4/guide/state/) is more appropriate for this task.

In your specific example, you should be able to `.manage(DatabaseObject)` instead of `.attach(DatabaseObject)`, and require `database: State<'_, MyState>` instead of `database: MyFairing` in routes. `State` acts somewhat like an `Arc`, so you might not need to your own `Arc` either (depending on what else you are doing with it).

**Comment by Ralthazoth** [comment]
Thank you so much!
