### ISSUE TITLE
Update major versions of dependencies

### ISSUE THREAD

**Issue by incker** [SergioBenitez/Rocket#1162]
Hello,
There available some major versions of dependencies that maybe need to be increased. 
In my own project in `Cargo.lock` I have only some duplicates dependencies but I have looked for everything that could be increased.

**Rocket/core/lib/Cargo.toml**

    [dependencies]
    toml = "0.5.3"

**Rocket/core/http/Cargo.toml**

    [dependencies]
    percent-encoding = "2.1.0"
    hyper = "0.12.35"
    rustls = "0.16.0"
    unicode-xid = "0.2.0"

**Rocket/contrib/lib/Cargo.toml**

    [dependencies]
    rmp-serde = "0.14.0"
    uuid = "0.8.1"
    rusqlite = "0.20.0"
    r2d2_sqlite = "0.12.0"
    redis = "0.13.0"
    r2d2_redis = "0.12.0"
    mongodb = "0.4.0"
    memcache = "0.13.1"
    r2d2-memcache = "0.4.0"

Forward thank you!

**Comment by jebrosen** [comment]
Nearly all of these can't be done at all until 0.5, because they are public dependencies - updating them in rocket would break other existing projects that depend on rocket. Upgrading the web dependencies in particular (including `hyper`) is tracked in #1065. Upgrading other dependencies may have already been done in the `master` branch, but any that aren't are welcome in a pull request.

(See also #1073 and #902)

**Comment by incker** [comment]
Oh I see..
Maybe it have sense to make something like this `dotenv = ">=0.8, <0.16"`

But ok, thank you for explain and thank you for great framework!)
I think I will close issue

**Comment by jebrosen** [comment]
> Maybe it have sense to make something like this `dotenv = ">=0.8, <0.16"`

For a very small dependencies that is useful and can probably be done (e.g. #1016), but cargo often makes surprising decisions with those. Unless something significant has changed, upgrading uuid to `>=0.7, < 0.9` would mean that `cargo update` *always* selects 0.8 for `rocket_contrib`, so an application using uuid 0.7 would get "`FromParam` trait not implemented" kinds of warnings unless they use `cargo update --precise`. Diesel ran into this or a similar issue when updating from 0.6 to 0.7.
