### ISSUE TITLE
error[E0432]: unresolved import `rocket_contrib::compression`

### ISSUE THREAD

**Issue by songroom2016** [SergioBenitez/Rocket#1168]
error[E0432]: unresolved import `rocket_contrib::compression`
  --> src\main.rs:17:5
   |
17 | use rocket_contrib::compression;

   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `compression` in the root
toml:

[dependencies]
rocket = { path = "S:/Rocket-master/core/lib" }#"0.4.1"
serde = "1.0.1"#{ version = "1.0.1", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
rocket_contrib = { path = "S:/Rocket-master/contrib/lib"}
csv = "1.1"
ndarray = "0.13.0"
chrono = "0.4"
jsonwebtoken = "6"
flate2 = { version = "1.0", features = ["zlib"], default-features = false,optional =true }
[features]
compression = ["brotli_compression", "gzip_compression"]
#compression = [ "gzip_compression"]
brotli_compression = ["brotli"]
gzip_compression = ["flate2"]

code:
`
#![feature(proc_macro_hygiene,decl_macro)]
#[macro_use] extern crate rocket;
extern crate rocket_contrib;
extern crate csv;
extern crate chrono;
extern crate jsonwebtoken as jwt;
use serde_derive::{Serialize, Deserialize};
use serde_json::to_string;
use std::collections::HashMap;
use std::thread;
//use std::time::Duration;
use std::time::{Duration, SystemTime};
use rocket_contrib::*;

use rocket_contrib::compression::Compress;
`

**Comment by jebrosen** [comment]
You need to enable the `compression` feature on `rocket_contrib`: https://api.rocket.rs/v0.5/rocket_contrib/compression/index.html#enabling

**Comment by songroom2016** [comment]
thanks a lot.
