### ISSUE TITLE
[Feature Repuest] Specifiy default values for struct fields for FromForm derive

### ISSUE THREAD

**Issue by Weasy666** [SergioBenitez/Rocket#1173]
Like the title implies, this request is all about some extra functionallity for `#[derive(FromForm]`.  
When using the derive on a form like follows
``` rust
#[derive(FromForm)]
pub struct Foo {
    pub bar: i16,
    pub baz: String,
}

#[post("/login", data = "<user>")]
fn login(user: LenientForm<Foo>) -> &'static str {
    "Hello, world!"
}
```
and the form does not carry any value for `bar` the [`default()`](https://api.rocket.rs/v0.4/rocket/request/trait.FromFormValue.html#method.default) function of `FromFormValue` is called, if implemented.  
But this enforces a "global" default for the type, which you can not easily set per `FromForm`.

So with this feature request i would propose something like this
``` rust
#[derive(FromForm)]
pub struct Foo {
    #[form(default = 1)]
    pub bar: i16,
    pub baz: String,
}
```
This way a "local" default value can be defined for a type for each form on which it is used.  
I guess this would still work with the "global" default value, as such that if a "local" default is present, use it otherwise fallback to the "global" one. I'm not exactly sure what should be done for structs, but i think a function invocation to get a default value should be possible, like `#[form(default = i16::default())]`.

**Comment by jebrosen** [comment]
I have a few thoughts on this:

1. Whether we should have this at all.
    * I'm inclined to say yes, because I expect it to be a relatively minor feature with clear added value over making a newtype.
2. How this interacts with `FromFormValue::default`.
    * `#[default]` should override `FromFormValue::default`, which might be complicated.
    * Would this feature make `FromFormValue::default()` unnecessary or obsolete?
3. How to specify default values.
    * Literals would be too restrictive (basically integer types and `&str` only)
    * We shouldn't try too hard to support arbitrary expressions like `#[from(default = thread_rng().next_u32())]`.
    * For comparison, serde has [`#[default]` for Default::default() and `#[default = "path"]` which calls a function at `path`](https://serde.rs/field-attrs.html#default).

**Comment by SergioBenitez** [comment]
Lets track this in #1536, which is a duplicate.
