### ISSUE TITLE
Constructing LenientForm instances for tests

### ISSUE THREAD

**Issue by sazzer** [SergioBenitez/Rocket#1175]
I will admit that I'm still new to both Rust and Rocket, and I could have missed something. I don't think I have though!

I'm trying to write a unit test for a handler function that takes form data - specifically a `LenientForm<LoginForm>`, and I can't work out how to construct a new `LenientForm` for my test.

Note that this is *not* an integration test, so I'm not setting up a whole Rocket instance to send requests to. That's partly because I'm generating HTML views and I don't want to need to parse the entire response to see if it did the right thing - I just want to call my handler and then assert on the `Template` instance that I get back from that.

Is this possible? Or if not, is there a suggested way to achieve this?

Cheers

**Comment by jebrosen** [comment]
`LenientForm<T>` has one public field (a `T`), so it should be possible to construct it directly like so:

```rust
let form = LenientForm(LoginForm { /* form fields */ });
```

**Comment by sazzer** [comment]
Ok - So I feel stupid now :)

I tried exactly that, but with curly brace syntax and that wouldn't work because it's a tuple struct and thus the field doesn't have a name.

Thanks! :)
