### ISSUE TITLE
Support postgres enum types with postgres-types crate

### ISSUE THREAD

**Issue by calvinbrown085** [SergioBenitez/Rocket#1179]
## Feature Requests

Add support for postgres enums with the postgres-types crate. https://docs.rs/postgres-types/0.1.0-alpha.2/postgres_types/

```
error[E0277]: the trait bound `channel_types::ChannelType: rocket_contrib::databases::postgres::types::FromSql` is not satisfied
  --> src/channel_store.rs:23:47
   |
23 |             let channel_type: ChannelType = r.get(3);
   |                                               ^^^ the trait `rocket_contrib::databases::postgres::types::FromSql` is not implemented for `channel_types::ChannelType`


```

This is implemented in the crate, but doesn't get an auto derive when we try to pull it out of the DB.
https://docs.rs/postgres-types/0.1.0-alpha.2/postgres_types/

  1. This seems like something pretty easy to support along-side the current third party crates in rocket contrib

  2. postgres enums are pretty widely used, this seems like a good feature to support.

  3. This feature is available, but i'm running into errors as it's not available from rocket contrib, please let me know if i'm wrong :) 

Thanks!

I'm happy to open a PR to help work on this.

**Comment by jebrosen** [comment]
I haven't looked too closely at the exact versions yet, but I expect this is because `postgres-types` implements `postgres[versionX]::FromSql` where `rocket_contrib` uses `postgres[versionY]`. You could, however, implement `Poolable` manually for that newer version of postgres and still be able to use `#[database]`.

**Comment by calvinbrown085** [comment]
Oh interesting, @jebrosen I'lll take a look at this. I actually switched back to postgres 0.15 because there wasn't a poolable for 0.17 yet. 

I'll see what it takes to get that there!

**Comment by calvinbrown085** [comment]
https://github.com/sfackler/r2d2-postgres Looks like r2d2 does support the new client for rust postgres.

**Comment by jebrosen** [comment]
I think the most likely scenarios for 0.5.0 are that it will either support the latest postgres (I haven't checked what version that is exactly), or it will support `tokio-postgres`, or it will not have built-in database support. That all depends on how #1117 is resolved.

In the worst-case and fairly unlikely scenario of no built-in database support, it will still be possible to create your own pool and connection as it always has been.

**Comment by calvinbrown085** [comment]
That makes sense! I was able to get around it by just making some new types so it's no big deal by any means :)

**Comment by calvinbrown085** [comment]
@jebrosen I understand having open tickets that aren't the best, would you prefer I close this ticket? As the outcome of #1117 seems important

**Comment by jebrosen** [comment]
Thanks for the reminder. This issue will definitely be resolved one way or another, so I will close it.

**Comment by chinedufn** [comment]
In case anyone else gets here after upgrading to `rust-postgres 0.17`

Here's a quick example of using a custom `Poolable` to support rust-postgres 0.17

```rust
use postgres::Client as PgClient;
use postgres::NoTls;
use rocket_contrib::databases::DbError;
use rocket_contrib::databases::{DatabaseConfig, Poolable};
use std::ops::{Deref, DerefMut};

#[database("akigi")]
pub struct AkigiDBConn(PgClientWrapper);

pub struct PgClientWrapper(PgClient);

impl Deref for PgClientWrapper {
    type Target = PgClient;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl DerefMut for PgClientWrapper {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}

pub struct PgConnectionManagerWrapper(r2d2_postgres::PostgresConnectionManager<NoTls>);

impl r2d2::ManageConnection for PgConnectionManagerWrapper {
    type Connection = PgClientWrapper;
    type Error = <r2d2_postgres::PostgresConnectionManager<postgres::NoTls> as r2d2::ManageConnection>::Error;

    fn connect(&self) -> Result<PgClientWrapper, Self::Error> {
        self.0.connect().map(|p| PgClientWrapper(p))
    }

    fn is_valid(&self, conn: &mut Self::Connection) -> Result<(), Self::Error> {
        self.0.is_valid(conn)
    }

    fn has_broken(&self, conn: &mut Self::Connection) -> bool {
        self.0.has_broken(conn)
    }
}

impl Poolable for PgClientWrapper {
    type Manager = PgConnectionManagerWrapper;
    type Error = DbError<postgres::Error>;

    fn pool(config: DatabaseConfig) -> Result<r2d2::Pool<Self::Manager>, Self::Error> {
        let manager =
            r2d2_postgres::PostgresConnectionManager::new(config.url.parse().unwrap(), NoTls);
        let manager = PgConnectionManagerWrapper(manager);

        r2d2::Pool::builder()
            .max_size(config.pool_size)
            .build(manager)
            .map_err(DbError::PoolError)
    }
}

```
