### ISSUE TITLE
Shouldn't hyper::header::Authorization be in headers instead of items?

### ISSUE THREAD

**Issue by InstinctBas** [SergioBenitez/Rocket#1185]
I'm getting a compilation error on this code:
```
let client = Client::new(rocket()).expect("valid rocket instance");
let mut response = client
	.get("/someurl")
	.header(header::Host {
		hostname: hostname.to_owned(),
		port: None,
	})
	.header(header::Authorization(
		header::Bearer { token: token.to_owned() }
	))
	.dispatch();
```

Which is:
```
the trait `std::convert::From<rocket::http::hyper::header::Authorization<rocket::http::hyper::header::Bearer>>` is not implemented for `rocket::http::Header<'static>`
```
If I understand the code here:
https://github.com/SergioBenitez/Rocket/blob/master/core/http/src/hyper.rs#L49
correctly, shouldn't Authorization be in `import_hyper_headers!` instead of `import_hyper_items!` ?

**Comment by jebrosen** [comment]
Unfortunately that wouldn't work. `import_hyper_headers!` generates a call to `to_string()`, and `Authorization` is one of only a few headers that does not implement `Display`.

Rocket could implement it manually for `Authorization` or change the approach entirely, but any fix is unlikely to be in a release before `0.5`, which currently loses *all* typed header support. #1067 is the tracking issue to decide what to do with them going forward.

**Comment by InstinctBas** [comment]
Bugger... it's ashame we don't have fall back where you can add a header by supplying a simple name/value pair. Or is there an option for that which I've missed? 

I've worked around it for now by sending the data as a cookie instead of in the header. Just trying to automate testing my API with CI :)

**Comment by jebrosen** [comment]
> Or is there an option for that which I've missed?

You can use [`Header::new()`](https://api.rocket.rs/v0.4/rocket/http/struct.Header.html#method.new) with a name and value. Something like `Header::new("Authorization", format!("Bearer {}", token))` should work.

**Comment by InstinctBas** [comment]
Sweet! that'll do :)

**Comment by InstinctBas** [comment]
@jebrosen hmm, it's complaining rocket::http::hyper::header::Header is a private member. Is there a different path to it?

**Comment by jebrosen** [comment]
I think that's not just a different name, it's the wrong `Header`. `rocket::http::Header` is the one you're after.

**Comment by InstinctBas** [comment]
Hmmm wonder where I got the other path from, anyway that worked :)

**Comment by SergioBenitez** [comment]
This is gone in `master`. #1067 tracks bringing something similar back. Ideally we'd resolve these kinds of issues then.
