### ISSUE TITLE
Rocket configuration should accept u16 for a port rather than a usize

### ISSUE THREAD

**Issue by drusellers** [SergioBenitez/Rocket#119]
`rocket::config::Config.port` is currently of type `usize`. I'd like to propose that the configuration class for Rocket be changed to a `u16` to more accurately reflect desired type of the configuration parameter.

- [x] Update configuration type
- [x]  Update docs
- [x] Make sure the config parsing reports a nice warning when above `u16::max`
- [x] Update tests

**Comment by SergioBenitez** [comment]
Pre-accepted via IRC. Slating for 0.2.

**Comment by SergioBenitez** [comment]
Fixed in https://github.com/SergioBenitez/Rocket/commit/a6084ab3e2ef9b5d26188ee01816316e0805c938.
