### ISSUE TITLE
Question: How to treat null and missing field differently in JSON?

### ISSUE THREAD

**Issue by cars10** [SergioBenitez/Rocket#1193]
Hi, i am writing an api with rocket and diesel. 
Consider the following two json objects:

    {
        "name": "test",
        "description": null
    }
-

    {
        "name": "test"
    }

If the `description` attribute of our struct is an `Option`  then both responses are treated in the same way. But this is not what i want - in the first case the user should explicitly set the field to `null`, in the second case only the `name` field should be updated.

I found an issue describing the exact problem here: https://github.com/serde-rs/serde/issues/984
So in the end this is probably a problem with serde, but i don't know how to implement the proposed solution in rocket.  Do i need to write a custom struct and implement `FromData` (that would be 90% identically with the original `json` type), or is there a simpler way?

Thanks.

**Comment by jebrosen** [comment]
You mentioned a `Responder`, but the linked serde issue is about the opposite direction (`Deserialize`). Which one are you trying to handle?

That being said, the implementations for both `FromData` and `Responder` for [`rocket_contrib::json::Json`](https://api.rocket.rs/v0.4/rocket_contrib/json/struct.Json.html) just call the JSON (de)serialization functions in `serde_json`. So anything you customize related to `Serialize` or `Deserialize` will work just as well when called from rocket.

**Comment by cars10** [comment]
Sorry, my mistake. I specifically have this problem when a user *sends* data to my rocket api. So in the above text i should have talked about `FromData` and not `Responder`, i fixed that :)

I was simply wondering if there is a built-in or easier way to do that instead of implementing my own struct, because i think this is a common problem. (A standard rails app for example treats both json objects differently, thats why i am trying to reproduce that behavior.)

**Comment by jebrosen** [comment]
In that case, the solution in https://github.com/serde-rs/serde/issues/984#issuecomment-314143738 would work. Since the behavior of `Json` is currently just to do what `Deserialize` does, adding such functionality to rocket directly would likely need a pretty large change.

**Comment by cars10** [comment]
Thanks :)

**Comment by oren0e** [comment]
In my case I have 2 structs - one for the request and one internal to the business logic. It will be really helpful to have the ability to return something other than `Self` in the `from_data()` method. So Ideally:
```rust
impl FromDataSimple for MyStructRequest {
    type Error = MyError;

    fn from_data(req: &Request, data: Data) -> data::Outcome<MyStruct, Self::Error> {
```
In this way I can make the conversion `MyStructRequest -> MyStruct` internally within the function.
