### ISSUE TITLE
Cookie-based sessions

### ISSUE THREAD

**Issue by MightyPork** [SergioBenitez/Rocket#1194]
I recently started learning rocket, and hit an obstacle with sessions - there are cookies and shared state, but no built-in session support. Unless I somehow missed it? 

Session is used to hold data between requests coming from the same client, using a session cookie as an identifier. It's a really useful feature, especially as a building block for user authentication.

..so I went ahead and built a generic session store with a fairing: https://crates.io/crates/rocket_session

I want to ask if this is something you might want to add to the contrib crate, or I should rather keep it as a separate crate, like it is now. I'm not sure how you'd write unit tests for something like this, beyond checking that it compiles.

**Comment by jebrosen** [comment]
For further reading: this is an implementation of option 2 in https://github.com/SergioBenitez/Rocket/issues/196#issuecomment-279883272

I do think this or similar functionality should become part of `rocket_contrib` at least for the "simple" use cases where a key-value store is sufficient session data, and/or this crate and other unofficial extension crates for `rocket` should have a dedicated place in some kind of documentation or a wiki.

**Comment by SergioBenitez** [comment]
Your crate looks great! I agree with @jebrosen. I'd love to find a place, likely somewhere on the Rocket website, to mention crates that have useful functionality but have also been vetted. For now, however, I'll close this out.
