### ISSUE TITLE
Update to tera 1.0

### ISSUE THREAD

**Issue by JoshLambda** [SergioBenitez/Rocket#1195]
Current Tera version (0.11) in contrib is nearly 1 year old and there are missing features, which are present in Tera documentation. 
Because of this, it's difficult to know what is available and not.

As an example, I'm getting this error:    ` => Error: Filter 'float' not found`
The filter `float` is present in standard Tera doc, but not in the (oldish) version Rocket uses.

Is there a plan to bump Tera version to current one?

**Comment by jebrosen** [comment]
> Is there a plan to bump Tera version to current one?

It will definitely be upgraded in `master` before the 0.5 release. It can't be done in 0.4 due to breaking changes.

I'll leave this open so we don't forget to actually do that update.

**Comment by jebrosen** [comment]
This was completed in #1201.
