### ISSUE TITLE
Consider making format in a route only match requests of that type

### ISSUE THREAD

**Issue by lholden** [SergioBenitez/Rocket#120]
Right now, a route specifying a format will match any request generically when the client doesn't care about the type.
```
#[get("/", format="application/json")]
fn list() -> &'static str {
  "{}"
}

#[get("/", rank=2)]
fn index() -> &'static str {
  "second"
}
/*
$ curl -X GET -H "Content-Type: application/json"  http://localhost:5000/organization
{}

$ curl -X GET  http://localhost:5000/organization
{}

*/

// ------
#[get("/", format="application/json")]
fn list() -> &'static str {
  "{}"
}

#[get("/")]
fn index() -> &'static str {
  "second"
}
/*
  Collision... always gets the second route even for application/json
  $ curl -X GET -H "Content-Type: application/json"  http://localhost:5000/organization
second
*/

// ------
#[get("/", format="application/json")]
fn list() -> &'static str {
  "{}"
}

#[get("/", format="text/html")]
fn index() -> &'static str {
  "second"
}
/*
 $ curl -X GET -H "Content-Type: application/json"  http://localhost:5000/organization
{}
curl -X GET  http://localhost:5000/organization
second
 */
```

I'd think the first example should work. (Since a type is specified, only match when the client is interested in that type... otherwise hit the second route).

**Comment by SergioBenitez** [comment]
Pre-accepted via IRC. Slating for 0.2.

**Comment by inferiorhumanorgans** [comment]
Can this be reopened? The Content-Type header is intended to indicate the type of the response/request body being sent, NOT the formats accepted by the client.  The correct header to request a JSON response is Accept.

http://webmasters.stackexchange.com/questions/31212/difference-between-the-accept-and-content-type-http-headers

**Comment by SergioBenitez** [comment]
@inferiorhumanorgans That's a separate issue, and it's already planned for `0.3`, where the `format` route attribute will match against the preferred media type in the `Accept` header for non-payload carrying requests.

**Comment by inferiorhumanorgans** [comment]
Cool.  How about inferring the type from the path as well?  Something akin to a a Rails route of `/foo(:format)` where `/foo` would default to whatever mime-type and `/foo.json` would be inferred as a request for a JSON response?

**Comment by lholden** [comment]
Yeah, I would very much like to have format matching against Accept too. :)
