### ISSUE TITLE
crates.io update?

### ISSUE THREAD

**Issue by roy-ganz** [SergioBenitez/Rocket#1200]
Hello Sergio,
I have been working on a new SQL query builder / ORM for Rust for the last 9 month (Toql). I have never announced it and would like to do so together with a big update on crates.io.

I like Rocket and I've done nice integration with it, so that Toql requests are smooth. 
My problem is that I need at least MySQL 15 (query column types) to do my magic. On crates.io rocket_contrib v0.4.2 depends on ^14. In your Git repo however the version is updated to 15.

Do you have any plans to update the version on crates.io?

(On my machine I have a Git dependency to Rocket. So no probs for me, but I can't push on crates.io with a Git depedency).

Have a nice week
Roy

Ref: [Toql](https://github.com/roy-ganz/toql) (Heavily outdated version)

**Comment by SergioBenitez** [comment]
I don't believe we can simply bump the version without it being a breaking change. That is, to bump the version of `mysql`, we'd need to bump the major version of Rocket as well, which we're unfortunately not ready to do (but will be soon!).  The alternative is to support multiple version of `mysql`. Assuming it can be shown that Cargo plays nice, I'd happy to accept such a PR.

**Comment by roy-ganz** [comment]
Thank you for your response. I still have a few issues on my side with my library (Toql), but once they are resolved, I will wait for a new major version of Rocket and support it directly.
I am looking forward for your new release - you and others do a great job!
