### ISSUE TITLE
How to support hyphen in urls?

### ISSUE THREAD

**Issue by gilescope** [SergioBenitez/Rocket#1203]
(I'd ask this on riot/matrix but couldn't find the room for some reason)

If we already have a query parameter unkind-rust-name=foo, is there a way to encode this as a route? 

```rust
#[get(/bar?unkind-rust-name=<kind_rust_name>)]
fn bar(kind_rust_name: String) {}
```

Many thanks in advance!

**Comment by jebrosen** [comment]
> (I'd ask this on riot/matrix but couldn't find the room for some reason)

The room is `#mozilla_#rocket:matrix.org` (listed on https://rocket.rs/v0.4/guide/conclusion/#getting-help) - sorry you had trouble finding it!

---

Renaming query parameters in the route path isn't supported directly. But you can go through `Form` to do it:

```rust
#[derive(FromForm)]
struct BarQuery {
    #[form(field = "unkind-rust-name")]
    kind_rust_name: String,
}

#[get("/bar?<query..>")]
fn bar(query: Form<BarQuery>) -> String {
    format!("unkind-rust-name is: {}", query.kind_rust_name)
}
```

This example route will require the `unkind-rust-name` parameter and disallow unknown query parameters; for more flexibility you can add `Option` or use `LenientForm` where necessary.

**Comment by gilescope** [comment]
Thanks - I hadn't made that mental leap to try parsing it as a form. I'd looked at the examples but hadn't found this. Will raise a small PR to add it into an example.

**Comment by jebrosen** [comment]
I think we probably could (under a different name than `form`), or we could introduce a different syntax for renaming such as `<rust_ident@param-name>`.

**Comment by SergioBenitez** [comment]
Aren't we supporting raw idents for this very reason, @jebrosen?
