### ISSUE TITLE
cargo build error

### ISSUE THREAD

**Issue by yuer1727** [SergioBenitez/Rocket#1205]
$ cargo build           
   Compiling proc-macro2 v0.4.30
   Compiling log v0.4.8
   Compiling unicode-xid v0.1.0
   Compiling cfg-if v0.1.10
   Compiling syn v0.15.44
   Compiling cc v1.0.50
   Compiling version_check v0.1.5
   Compiling matches v0.1.8
   Compiling libc v0.2.66
   Compiling byteorder v1.3.2
   Compiling yansi v0.4.0
   Compiling bitflags v1.2.1
   Compiling smallvec v1.1.0
error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
  --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.1.0/lib.rs:35:1
   |
35 | extern crate alloc;
   | ^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
  --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.1.0/lib.rs:49:5
   |
49 | use core::mem::MaybeUninit;
   |     ^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.1.0/lib.rs:294:12
    |
294 |     Inline(MaybeUninit<A>),
    |            ^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.1.0/lib.rs:315:28
    |
315 |     fn from_inline(inline: MaybeUninit<A>) -> SmallVecData<A> {
    |                            ^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.1.0/lib.rs:319:36
    |
319 |     unsafe fn into_inline(self) -> MaybeUninit<A> {
    |                                    ^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.1.0/lib.rs:394:45
    |
394 |             data: SmallVecData::from_inline(MaybeUninit::uninit()),
    |                                             ^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.1.0/lib.rs:434:63
    |
434 |                 let mut data = SmallVecData::<A>::from_inline(MaybeUninit::uninit());
    |                                                               ^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.1.0/lib.rs:470:45
    |
470 |             data: SmallVecData::from_inline(MaybeUninit::new(buf)),
    |                                             ^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.1.0/lib.rs:489:55
    |
489 |         unsafe { SmallVec::from_buf_and_len_unchecked(MaybeUninit::new(buf), len) }
    |                                                       ^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.1.0/lib.rs:508:51
    |
508 |     pub unsafe fn from_buf_and_len_unchecked(buf: MaybeUninit<A>, len: usize) -> SmallVec<A> {
    |                                                   ^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.1.0/lib.rs:670:55
    |
670 |                 self.data = SmallVecData::from_inline(MaybeUninit::uninit());
    |                                                       ^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.1.0/lib.rs:737:55
    |
737 |                 self.data = SmallVecData::from_inline(MaybeUninit::uninit());
    |                                                       ^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
    --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.1.0/lib.rs:1078:52
     |
1078 |                     let mut data: MaybeUninit<A> = MaybeUninit::uninit();
     |                                                    ^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
    --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.1.0/lib.rs:1078:35
     |
1078 |                     let mut data: MaybeUninit<A> = MaybeUninit::uninit();
     |                                   ^^^^^^^^^^^^^^

   Compiling maybe-uninit v2.0.0
error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.1.0/lib.rs:303:42
    |
303 |             SmallVecData::Inline(a) => a.as_ptr() as *const A::Item,
    |                                          ^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.1.0/lib.rs:310:42
    |
310 |             SmallVecData::Inline(a) => a.as_mut_ptr() as *mut A::Item,
    |                                          ^^^^^^^^^^

error[E0599]: no function or associated item named `uninit` found for type `core::mem::MaybeUninit<_>` in the current scope
   --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.1.0/lib.rs:394:58
    |
394 |             data: SmallVecData::from_inline(MaybeUninit::uninit()),
    |                                             -------------^^^^^^
    |                                             |
    |                                             function or associated item not found in `core::mem::MaybeUninit<_>`

error[E0599]: no function or associated item named `uninit` found for type `core::mem::MaybeUninit<_>` in the current scope
   --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.1.0/lib.rs:434:76
    |
434 |                 let mut data = SmallVecData::<A>::from_inline(MaybeUninit::uninit());
    |                                                               -------------^^^^^^
    |                                                               |
    |                                                               function or associated item not found in `core::mem::MaybeUninit<_>`

error[E0599]: no function or associated item named `uninit` found for type `core::mem::MaybeUninit<_>` in the current scope
   --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.1.0/lib.rs:670:68
    |
670 |                 self.data = SmallVecData::from_inline(MaybeUninit::uninit());
    |                                                       -------------^^^^^^
    |                                                       |
    |                                                       function or associated item not found in `core::mem::MaybeUninit<_>`

error[E0599]: no function or associated item named `uninit` found for type `core::mem::MaybeUninit<_>` in the current scope
   --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.1.0/lib.rs:737:68
    |
737 |                 self.data = SmallVecData::from_inline(MaybeUninit::uninit());
    |                                                       -------------^^^^^^
    |                                                       |
    |                                                       function or associated item not found in `core::mem::MaybeUninit<_>`

error[E0599]: no method named `assume_init` found for type `core::mem::MaybeUninit<A>` in the current scope
   --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.1.0/lib.rs:916:39
    |
916 |                 Ok(data.into_inline().assume_init())
    |                                       ^^^^^^^^^^^

error[E0599]: no function or associated item named `uninit` found for type `core::mem::MaybeUninit<_>` in the current scope
    --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.1.0/lib.rs:1078:65
     |
1078 |                     let mut data: MaybeUninit<A> = MaybeUninit::uninit();
     |                                                    -------------^^^^^^
     |                                                    |
     |                                                    function or associated item not found in `core::mem::MaybeUninit<_>`

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
    --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.1.0/lib.rs:1081:30
     |
1081 |                         data.as_mut_ptr() as *mut A::Item,
     |                              ^^^^^^^^^^

error: aborting due to 23 previous errors

Some errors occurred: E0599, E0658.
For more information about an error, try `rustc --explain E0599`.
error: Could not compile `smallvec`.
warning: build failed, waiting for other jobs to finish...
error: build failed

-----------------------------------------------------------------------------------

hello rocket workgroup:  
    when I run `cargo build ` , I got compile errors like these.  Base on macOS and rust version is 
 `1.34.0`. Maybe I  should update my rust version.

**Comment by jebrosen** [comment]
Rocket requires a nightly version of the rust compiler - more details on this are at https://rocket.rs/v0.4/guide/getting-started/#installing-rust

We are working on moving to a stable version of rust in a future release; the tracking issue for that is #19.
