### ISSUE TITLE
Guide: link to requests/#error-catchers from overview/#routing

### ISSUE THREAD

**Issue by jplatte** [SergioBenitez/Rocket#1206]
## Feature Request

It just took me about half an hour to find out how to define a custom 404 handler. I was trying to get a `#[get("/<path..>")]` route to work for that, and the only reason it didn't work is because I also had another, high-priority catch-all `NamedFile` route. Finally, I found out through [this issue](https://github.com/SergioBenitez/Rocket/issues/1148) that I could just write `#[catch(404)]` and where that is documented.

I had previously looked at all the routing docs I found because that's where I expected this to be documented. I think it would be very useful to link to the error catchers docs from the routing overview, and maybe also the more detailed routing page, to avoid this happening to other people too. Or maybe the error catching section could be moved up to immediately after the routing section, that would also make it much easier to discover.

**Comment by jebrosen** [comment]
The overview you mentioned is this one, right? https://rocket.rs/v0.4/guide/overview/#routing

Some text we could change:

> This declares the `world` route to match against the static path `"/world"` on incoming `GET` requests. Instead of `#[get]`, we could have used `#[post]` or `#[put]` for other HTTP methods or `#[catch]` for serving [custom error pages](https://rocket.rs/v0.4/guide/requests/#error-catchers). The `world` route is simple, but additional route parameters are necessary when building more interesting applications. For more details on routing and error handling, see the [Requests](https://rocket.rs/v0.4/guide/requests/) chapter.

**Comment by jplatte** [comment]
Yes, exactly. Your text looks good to me.
