### ISSUE TITLE
Accessing Parameterized State from Catcher

### ISSUE THREAD

**Issue by AshtonKem** [SergioBenitez/Rocket#1209]
It is currently impossible to access any parameterized state from a Catcher in Rocket, because Rocket only gives Catchers access to the un-parameterized `Request` struct. 

Example: I have managed the following struct within Rocket: `Configuration<T: Storage>`, where `Storage` is a trait that should be user extendible. 

For normal request methods, this can be solved as such:

```rust
fn example<T: Storage>(config: State<Storage<T>>) {
...
}
```

But for a catcher, the best I can do is the following:

```rust
#[catch(401)]
pub fn not_authorized<T: 'static + Storage>(req: &Request) -> Redirect {
    let config = req.guard::<State<Configuration<T>>>().unwrap();
    redirect_to_login(req, &config)
}
```

Which does not compile.

This feature would be very nice for external crates designed to provide common functionality to Rocket apps. I'm currently working on an OAuth2 crate that is (mildly) hampered by this problem.

**Comment by jebrosen** [comment]
The "normal request method" you posted shouldn't actually work either! I would expect that to be an error when you apply `#[get]` to it, along the lines of "type for `T` must be known in this context" and "hint: specify the type for `T`: `example::<Type>`".

The most appropriate solution to this is probably to use a `Box<dyn Storage>` inside `Configuration` instead of making it generic, but I might have a better specific idea if you could elaborate on who is supposed to implement which traits and why it's parameterized.

**Comment by AshtonKem** [comment]
The use case is accessing OAuth configuration (scopes, secrets, etc.) in various handlers and catchers. The parameterization will cover both where to store tokens once retrieved, and probably parameterization over what OAuth provider to use (Google, Facebook, etc.) Because there are a wide number of configurations an end user would reasonably want to take, especially if they want to store tokens in a database, I don’t see an easy way to avoid the parameterization.

I’ll give Box<dyn Storage> a try.

**Comment by AshtonKem** [comment]
I no longer need this use case, I found a library that solves my issues. No reason to push forward API changes without a justifiable use case.

**Comment by ElnuDev** [comment]
Sorry to necro this five years later but in case anyone comes across this in the future, the example you give of using `req.guard` works fine now on rocket 0.5.1. The following worked fine in my project.

```RS
#[catch(default)]
pub async fn catcher(status: Status, req: &Request<'_>) -> Template {
    let settings = req.guard::<&State<Settings>>().await.unwrap();
    Template::render("message", context! {
        status: status.code,
        reason: status.reason_lossy(),
        settings: settings.deref()
    })
}
```

Cheers
