### ISSUE TITLE
Docs: Consider running `cargo fmt` on `examples/*`

### ISSUE THREAD

**Issue by benjaminch** [SergioBenitez/Rocket#1210]
First of, thanks a lot for this very nice project :)

## Documentation?
I have been playing quite a bit with rocket and have enjoyed all the very detailed examples listed [here](https://github.com/SergioBenitez/Rocket/tree/master/examples).
It appears though that they are not all following rustfmt convention.
I though it will be nice to apply formatting on those.

Thanks a lot !

**Comment by SergioBenitez** [comment]
Please see #1211. Thank you!
