### ISSUE TITLE
problems with compiling hello_world please help

### ISSUE THREAD

**Issue by danielhop75** [SergioBenitez/Rocket#1217]
I use nightly rust.  When I try to compile examples from Rocket I get the following error:
Compiling time-macros v0.1.0
   Compiling time v0.2.5
   Compiling cookie v0.13.1
error[E0015]: calls in statics are limited to constant functions, tuple structs and tuple variants
   --> /home/daniel/.cargo/registry/src/github.com-1ecc6299db9ec823/cookie-0.13.1/src/lib.rs:806:47
    |
806 |           static MAX_DATETIME: OffsetDateTime = date!(9999-12-31)
    |  _______________________________________________^
807 | |             .with_time(time!(23:59:59.999_999))
808 | |             .using_offset(offset!(UTC));
    | |_______________________________________^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0015`.
error: could not compile `cookie`.
warning: build failed, waiting for other jobs to finish...
error: build failed

More information is: rustc --explain E0015
A constant item was initialized with something that is not a constant
expression.

Please give me some tips. Maybe any suggestions. I am begginer at rust. So It's a little diffcult for me ;-)
Regards, 
Daniel

**Comment by jebrosen** [comment]
This looks like https://github.com/SergioBenitez/cookie-rs/issues/136. `cargo update` should pull in `cookie v0.13.2`, which should compile successfully.

**Comment by SergioBenitez** [comment]
`cargo update` is indeed the answer!

**Comment by danielhop75** [comment]
Sergio, You are really fast. I have already send you a private email with this information. Anyway, one more time, Thanks a lot. 
in my opision rocket is the best framework in rust ;-) Do you think about something "more stable" than nightly versions ;-) I, and as far as I know lots of people wait for this version ;-) 
Thanks, one more time.
