### ISSUE TITLE
rocket_contrib::handlebar_templates does not register partials w/ Handlebars

### ISSUE THREAD

**Issue by kestred** [SergioBenitez/Rocket#122]
Out of the box, Rocket does not correctly handle handlebars partials.

See an example handlebars template:

```handlebars
{{> common/header }}
<main> ... </main>
{{> common/footer }}
```

I currently have a work-around where I write a little hacky-boilerplate before I launch rocket:

```rust
fn main() {
    let empty = HashMap::<String, String>::with_capacity(0);
    Template::render("common/header", &empty);
    Template::render("common/footer", &empty);

    rocket::ignite().mount("/", routes![...]).launch();
}
```

This works by re-purposing the `render()` function to register the partials in the `HANDLEBARS` static variable.

If you can describe your ideal way of fixing this issue, I'd be happy to implement a fix and open a pull request.

**Comment by SergioBenitez** [comment]
What is the layout/structure of your `templates` directory?

**Comment by kestred** [comment]
It is structured like so:

```
templates/
|__ common/
|   |__ header.html.hbs
|   \__ footer.html.hbs
|
|__ index.html.hbs
\__ etc.html.hbs
```

This isn't following any particular pattern, it is just what is convenient at the time;
Is there a specific place that `rocket.rs` recognizes for partials?

**Comment by SergioBenitez** [comment]
Indeed. The Handlebars template engine plugin for Rocket is lazy about loading templates. But this clearly indicates that it must be eager. The proper approach is to scan for all of the templates at initialization and register them with handlebars. This is what the Tera engine does, for instance.
