### ISSUE TITLE
serde-json build failed

### ISSUE THREAD

**Issue by myyrakle** [SergioBenitez/Rocket#1221]
1. I tried to build with the latest versions of rocket and rocket_contrib.  
![image](https://user-images.githubusercontent.com/16988115/73729613-b4038a80-4778-11ea-8cf4-ee428fca71e6.png)

2. The environment was Windows and the toolchain was rustc 1.42.0-nightly (8417d68de 2020-02-03).

3. I wrote roughly code and tried 'cargo run', but I got an error in the serde-json build.
![image](https://user-images.githubusercontent.com/16988115/73729662-cbdb0e80-4778-11ea-9e40-2f121e3ae5ba.png)

Can I expect a solution for this?

**Comment by jebrosen** [comment]
This looks like https://github.com/serde-rs/json/issues/612

I have a hunch that a `cargo update` might fix it; can you try that?

**Comment by myyrakle** [comment]
Oh, the problem is solved.
Thank you for your kindness.
