### ISSUE TITLE
how to get current environment string, like "development" or "prod" ?

### ISSUE THREAD

**Issue by insub** [SergioBenitez/Rocket#1223]
Rocket v0.4
I know it's a simple question, but I can't find the answer in the API documentation or Google...

**Comment by olback** [comment]
I don't know if there's a better way but checking the value of env variable `ROCKET_ENV` would work.

```rust
let rocket_env = std::env::var("ROCKET_ENV").expect("ROCKET_ENV not set");
```

**Comment by insub** [comment]
@olback thanks.
but i get error: 
"environment variable `ROCKET_ENV` not defined"

**Comment by jebrosen** [comment]
The `Config` type, accessible via `rocket.config()` during startup, has a public field `Environment`: https://api.rocket.rs/v0.4/rocket/struct.Config.html#structfield.environment

**Comment by insub** [comment]
@jebrosen get that.
thanks~
