### ISSUE TITLE
Dev version of Rocket can't find marco routes

### ISSUE THREAD

**Issue by Voodlaz** [SergioBenitez/Rocket#1225]
I was having a problem with Tera Templates. I'm using windows, and i found [this](https://github.com/SergioBenitez/Rocket/issues/169) issue(and it solved my broblem). I solved the problem just by using the unrealeased version. So, rust is saying that he can't find marco routes!.

main.rs code:
```
extern crate rocket;
extern crate rocket_contrib;

use std::collections::HashMap;

use rocket_contrib::templates::Template;

fn index() -> Template {
    let context: HashMap<&str, &str> = HashMap::new();
    Template::render("home", &context)
}

fn main() {
    rocket::ignite().attach(Template::fairing()).mount("/", routes![index]).launch();
}
```

cargo.toml code:
```
[dependencies]`
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket" }

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket"
default-features = false
features = ["handlebars_templates","tera_templates"]
```

P.S. Sorry for my English. I wasn't born with this language.

**Comment by jebrosen** [comment]
That issue should have been a fixed a long time ago; if you are using 0.4 I would expect that your problem with tera is different from that one.

As for this issue, you haven't imported the `routes!` macro anywhere. You need either a `#[macro_use] extern crate rocket;` in `main.rs` to import all macros, or a `use rocket::routes;` to import that specific macro.
