### ISSUE TITLE
Match the most specific route

### ISSUE THREAD

**Issue by zlnpgtdtfezf** [SergioBenitez/Rocket#1226]
If you have routes like these:

```Rust

#[get("/*")]
fn one() {
   ...
}

#[get(/something)]
fn two() {
   ...
}
```
then the most specific route should be matched for every request: e.g: `/a` should route to `one` but `/something` should route to `two`.

Also the rule which determines if a route descriptor is more specific than an another should be documented.

**Comment by nCrazed** [comment]
The rules are documented in the [Forwarding](https://rocket.rs/v0.4/guide/requests/#forwarding) section of the docs.

While in the case of your example, you'd have to use explicit ranks to delay matching of `/*`, there are well documented rules for implicit ranking based on specificity of a route. See: [Default Ranking](https://rocket.rs/v0.4/guide/requests/#default-ranking)

**Comment by zlnpgtdtfezf** [comment]
Hm, I think I had a problem with this, but now I can't seem to reproduce. Thruth to be told I created this issue from memory (hence the incorrect use of "/*" instead of "/<something>"). 

Anyhow things indeed seem to work so I will just close this.
