### ISSUE TITLE
Feature Request: Support for using externaly managed ports (ListenFd)

### ISSUE THREAD

**Issue by JoelEllis** [SergioBenitez/Rocket#1228]
Please add an option to listen to externaly managed ports, for example those from [ListenFd](https://github.com/mitsuhiko/rust-listenfd).
This feature is helpful in some use cases as it allows quick switching out of a process that is litening to a port. An example of a use case where this is helpful is during development, when you are quickly changing the running binary. It would be great to get fast automatic rebuilds via `systemfd --no-pid -p 3000 -- cargo watch -x run`.
This feature is not possible out side of rocket because rocket is currntly coded to always create its own socket.
An example of another framework that has this feature is Actix:
```rust
let mut server = HttpServer::new()
server = if let Some(l) = listenfd.take_tcp_listener(0)? {
    server.listen(l)?
} else {
    server.bind("0.0.0.0:3000")?
};
server.run().await
```
Thank you for taking the time to read this!

**Comment by jebrosen** [comment]
The `async` branch has the necessary infrastructure that should *probably* make this simply a matter of type wrangling (i.e. mapping from a `std` `TcpListener` to something that implements `tokio::io::AsyncRead/Write`). However it is not exposed and might not be in the first release of 0.5 - see also #1070.

**Comment by JoelEllis** [comment]
> The `async` branch has the necessary infrastructure that should _probably_ make this simply a matter of type wrangling (i.e. mapping from a `std` `TcpListener` to something that implements `tokio::io::AsyncRead/Write`). However it is not exposed and might not be in the first release of 0.5 - see also #1070.
Thanks for the reply and the info! Nice to know it's being worked on!

**Comment by SergioBenitez** [comment]
Closing in favor of #1070.
