### ISSUE TITLE
Overriding Nested Parameters

### ISSUE THREAD

**Issue by AshtonKem** [SergioBenitez/Rocket#1233]
This is a question, but it might turn into a feature request. I'm currently using rocket_oauth2, which recommends the following configuration in `Rocket.toml`

```
[global.oauth.google]
provider = "Google"
client_id = "<client_id>"
client_secret = "<client_secret>"
redirect_uri = "http://localhost:8000/auth/google"
```

Obviously, it's not a good idea to commit `client_id` and `client_secret` to git, so I would like to override these with environment variables. I've tried the following environment variables, to no clear effect.

`ROCKET_CLIENT_ID`, `ROCKET_OAUTH_GOOGLE_CLIENT_ID`. 

Is there an environment variables that would make this work, or should this be a feature request?

## Mandatory Details

  1. The version of Rocket this question is based on, if any.

0.4.2, should apply to all versions though.

  2. What steps you've taken to answer the question yourself.

Read the source in question, tried every combination of environment variable that I can think of.

  3. What documentation you believe should include an answer to this question.

[These Docs](https://api.rocket.rs/v0.4/rocket/config/index.html) should be updated to cover this use case.

**Comment by AshtonKem** [comment]
Agreed, I made a comment on #852 to give my request a good chance of being picked up. 

The database issue is particularly problematic, since it's pretty common for systems like Heroku to simply inject `DATABASE_URL` into running environment. It would be nice to be able to take advantage of that without having to hard code TOML into an environment variable.

**Comment by SergioBenitez** [comment]
Let's track this in #852.
