### ISSUE TITLE
Is there any way to handle ALL errors in a Rocket application?

### ISSUE THREAD

**Issue by silvioprog** [SergioBenitez/Rocket#1235]
Hi.

I would like to intercept **all** possible errors in a Rocket application, something like this:

```rust
impl<'r> Responder<'r> for ??? {
    fn respond_to(self, req: &Request) -> response::Result<'r> {
        status::Custom(Status::InternalServerError, self.to_string()).respond_to(req)
    }
}
```

So, is there any type to declare instead of `???` and intercept ANY error (from Serde, Diesel, std::io and so on) in the application?

Thank you!

**Comment by jebrosen** [comment]
Not currently, and I don't think we would add something so wide-reaching. Depending on what you want to do with it exactly, it may not even be possible in stable rust (see also https://github.com/SergioBenitez/Rocket/issues/1232#issuecomment-592976260 RE: `non_static_type_id`). If you can provide more details on why you want a global error handler such as this I might be able to help more.

**Comment by SergioBenitez** [comment]
I am happy to revisit this with a compelling use-case, as requested by @jebrosen. Until then, I'm closing this out in favor of #1232.
