### ISSUE TITLE
 autobahn websocket test suite

### ISSUE THREAD

**Issue by rustrust** [SergioBenitez/Rocket#1238]
To ensure that rocket provides production-grade websockets, it should pass the crossbar autobahn test suite.

https://github.com/crossbario/autobahn-testsuite

**Comment by jebrosen** [comment]
Has anyone run this against something built on top of hyper, such as warp? I have not yet looked at how much hyper handles and how much it leaves up to the user of the library.

**Comment by cbzehner** [comment]
It looks like Warp relies on [Tungstenite](https://github.com/snapview/tungstenite-rs) for their websocket implementation ([source](https://github.com/seanmonstar/warp/issues/356)). From the Testing section of the [Tungstenite](https://github.com/snapview/tungstenite-rs) README:

> Tungstenite is thoroughly tested and passes the Autobahn Test Suite for WebSockets. It is also covered by internal unit tests as good as possible.

**Comment by SergioBenitez** [comment]
Fur sure. Let's keep this in mind for #90.
