### ISSUE TITLE
Website unusable. Page transition loops forever. 

### ISSUE THREAD

**Issue by eshell** [SergioBenitez/Rocket#1247]
Once you use any link besides the index page, it keeps growing and shrinking.  I cant read the guide.

Chrome latest on android  10.

**Comment by jebrosen** [comment]
I can't reproduce this on Chrome on Android 8. Is there any specific page where it is working or broken, and what part of the page is growing and shrinking?

**Comment by eshell** [comment]
If I visit guide, the black background/ text area starts in top left and slowly expands bottom right and loops. Any page that's not on the index page.

![Screenshot_20200229-105516_Chrome](https://user-images.githubusercontent.com/1856531/75610780-4a11a300-5ae2-11ea-99a9-9803b060c7ea.jpg)

**Comment by eshell** [comment]
After looking more. News and guide do this.
![Screenshot_20200229-105907_Chrome](https://user-images.githubusercontent.com/1856531/75610811-a5dc2c00-5ae2-11ea-9c18-f7644d946734.jpg)

![Screenshot_20200229-105853_Chrome](https://user-images.githubusercontent.com/1856531/75610812-ac6aa380-5ae2-11ea-8647-3af4c8a47ef7.jpg)

**Comment by jebrosen** [comment]
The clouds are supposed to be partially transparent, as well. Do you happen to have any kind of content blocker running? Does the "desktop mode" option make any difference?

**Comment by eshell** [comment]
I have no extensions installed that aren't default  to fresh chrome install. Does this in desktop mode also.

**Comment by jebrosen** [comment]
The overview page *should* have a transition, so this is all kinds of broken. Perhaps an exception is being thrown early on in the page that prevents the rest of the code from running - does Chrome on Android has any easily accessible debugging capabilities?

**Comment by eshell** [comment]
I wish! If it does I'm not aware. I have to be on my laptop to debug. Index page on desktop version shows clouds and animations. Overview does not show clouds or animation. News and guide show clouds and animations, but grow and shrink content indefinitely.  Moving around those pages or resizing reset the animations.

**Comment by eshell** [comment]
Eh. I've given all I can via mobile.  Later today I'll look on my laptop to help see if I can find what's actually happening if you guys don't first.

**Comment by jebrosen** [comment]
> After finding the source to rocket.rs I realize I'm just learning rust and can't be very helpful with using your framework to fix it. Kind of in a catch 22 here lol.

The rocket.rs site is not built with the Rocket framework, and only the page content is actually in this repository. But the javascript is all in the served HTML and un-minified, so it should be pretty debuggabble if there's something going on. If you see anything in the error console, that might even be enough to figure out what goes wrong.

>  Later today I'll look on my laptop to help see if I can find what's actually happening if you guys don't first.

I have not been able to reproduce it on the android emulator, either (Chrome 74 on Android 10)

**Comment by eshell** [comment]
It works fine on my laptop. Now even the home page does this on android. Gonna look now and see what I can find on my laptop

**Comment by eshell** [comment]
Hmm.. emulating my device on chrome doesn't reproduce.

I copied the site to my machine and ran it via node. When I view my version on android it is fine... mystery to me right now.

**Comment by eshell** [comment]
I copied the html sources, css, and images. Works fine on my version from android with no changes but src links. Very strange. Guess we shouldn't worry about it unless more people experience this. Might be something buggy on my end.

**Comment by SergioBenitez** [comment]
I believe this is a cache issue. Your browser has cached previous resources that have since changed. A "fresh reload" of the site should fix up the issue. I'll see what we can do on our end to fix the problem.

**Comment by eshell** [comment]
I finally figured out how to clear my cache for just rocket.rs on android.  All is well.

**Comment by SergioBenitez** [comment]
I've set up a less aggressive cache policy. Hopefully this resolves the issue going forward.
