### ISSUE TITLE
Is there any way to interact with javascript code?

### ISSUE THREAD

**Issue by lucklove** [SergioBenitez/Rocket#125]
For example, I need to draw some chart on canvas, however, most of graph libraries are write in javascript, so is there any way to do that?

**Comment by SergioBenitez** [comment]
The typical way to do this is to serve the Javascript file from Rocket via a rendered template. So, you'd have some file, `chart.js.tera` (or handlebars, whatever suits you better), and then you'd use `Template::render(chart, some_context)` to inject information from the web application into the javascript file. [The guide](https://rocket.rs/guide/responses/#templates) has more information, as do [the API docs](https://api.rocket.rs/rocket_contrib/struct.Template.html).

**Comment by flosse** [comment]
@lucklove You could also render simple svg charts on the server with e.g. [maud](https://maud.lambda.xyz/):

```rust
#[get("/my/chart")]
fn my_chart() -> PreEscaped<String> {
  html!{
    svg width = "200" height = "100" {
       g class = "bar-chart" transform = "translate(10,10)" {
         g class = "bar" {
           rect width="40" height="19" /
           text x = "45" y = "9.5" dy = ".35em" { "4 apples" }
         }
         g class = "bar" {
           rect width="40" height="19" /
           text x = "45" y = "9.5" dy = ".35em" { "4 bananas" }
         }
       }
    }
  }
}
```

**Comment by lucklove** [comment]
@SergioBenitez @flosse Get!

**Comment by SergioBenitez** [comment]
Looks like this has been answered. :)
