### ISSUE TITLE
Rayon not using multiple cores when behind rocket state

### ISSUE THREAD

**Issue by BaxterEaves** [SergioBenitez/Rocket#1260]
Rocket v0.4.4

I have a rocket app managing a state that does some heavy computations using rayon. When I run a computation without rocket the computation uses all cores (i check visually in htop). When I do the same computation, but the computation is managed by a rocket state behind a server, everything runs on a  single core. 

I tried manually setting the number of workers to 1 thinking that somehow the number of workers was blocking the rayon threadpool. No dice. I also didn't see anything that stood out in [the managed state documentation](https://rocket.rs/v0.4/guide/state/#managed-state), which is where I would expect documentation to be regarding limits on the way states can carry out computation. 

Thanks

**Comment by jebrosen** [comment]
Rocket 0.4 is based on hyper 0.10, which spawns its workers with `thread::spawn` - so it should not impact `rayon` at all. Can you share a minimal example that someone could run to reproduce and/or investigate this?

**Comment by BaxterEaves** [comment]
Thanks for the response. I did some digging and it turns out the error was on my side 🤦‍♂A probabilistic program fell into an unforeseen edge case that caused one of the parallel computations to take much longer than the others. Sorry about that!

**Comment by jebrosen** [comment]
Thanks for following up!
