### ISSUE TITLE
`Route.set_uri` does not play well with segment offset calculation

### ISSUE THREAD

**Issue by jebrosen** [SergioBenitez/Rocket#1262]
Consider this example code (adapted from an issue reported on IRC):

<details>

```rust
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use] extern crate rocket;

use rocket::http::uri;

pub fn prepend(prefix: &str, route: &rocket::Route) -> rocket::Route {
    let prefix = uri::Origin::parse(prefix).unwrap();
    let new_base = uri::Origin::parse_owned(format!("{}{}", prefix, route.base)).unwrap();

    let uri_part = &route.uri.to_string()[route.base.path().len() - 1..];

    let mut new_route = route.clone();
    if let Err(error) = new_route.set_uri(new_base, uri::Origin::parse_route(uri_part).unwrap()) {
        panic!(error);
    }
    new_route
}

pub fn extend_routes(prefix: &str, routes: Vec<rocket::Route>) -> Vec<rocket::Route> {
    routes
        .iter()
        .map(|route| dbg!(prepend(prefix, route)))
        .collect()
}

mod a {
    #[get("/b/<id>")]
    fn b(id: u8) -> String {
        format!("{}", id)
    }

    pub fn routes() -> Vec<rocket::Route> {
        super::extend_routes("/a", routes![b])
    }
}

#[get("/")]
fn hello() -> &'static str {
    "Hello, world!"
}

fn main() {
    rocket::ignite().mount("/", routes![hello]).mount("/", a::routes()).launch();
}
```

</details>

Trying to access `/a/b/3` fails, because the `id` parameter tries to decode `b` as a `u8`. I am not quite sure where exactly the blame lies here, but it has to do with the behavior of `set_uri` and of `Request::routed_path_segment`.

* `Request::routed_path_segment` is used to calculate which part of a URI corresponds to the "nth" segment. This is done by calculating how many segments are in the "base" URI, then skipping over that many segments in the full URI.
* When calling `set_uri` manually it is difficult to correctly preserve the relationship between "base" and "original" URIs such that it does not break `routed_path_segment`. The code above does that (I think), but in a hacky way.
* `mount` calls `set_uri` in such a way that it does *not* preserve the relationship between base and original URIs. Consider the route with `base`="/a" and `uri`="/a/b/<id>" (`uri` always includes `base`). `mount`ing this route at "/" will adjust the route to have `base`="/" and `uri`="/a/b/\<id\>", which has changed the base-to-uri offset and adversely affected `routed_path_segment`.

I am not sure what the best way to solve this is, but I definitely think the `set_uri` API and/or documentation should be improved to avoid falling into this trap.

**Comment by SergioBenitez** [comment]
I'm labeling this as a bug: Rocket should ensure that no API can break codegen. Fix is incoming.
