### ISSUE TITLE
Rocket depends on a vulnerable version of hyper.

### ISSUE THREAD

**Issue by Pavlov123** [SergioBenitez/Rocket#1265]
Rocket depends on hyper 0.10.13, which is vulnerable to request smuggling.

See https://rustsec.org/advisories/RUSTSEC-2020-0008 for details on the vulnerability.

Unfortunately, hyper has not issued a patch for the 0.10 branch.

**Comment by Pavlov123** [comment]
I dug a little deeper, and it seems the issue was introduced to hyper in the 0.12 branch. Thus I will be closing this issue.

**Comment by jebrosen** [comment]
The issue is apparently in the `hyper` client, which Rocket does not use either.
