### ISSUE TITLE
Connection closed without response under load

### ISSUE THREAD

**Issue by nimrod-codota** [SergioBenitez/Rocket#1268]
Hey,

While trying to use [this buildpack](https://github.com/emk/heroku-buildpack-rust) to run our app @ heroku I have encountered a situation where we are getting H13 errors from heroku under load. The [error description](https://devcenter.heroku.com/articles/error-codes#h13-connection-closed-without-response) @ heroku support says:
 `This error is thrown when a process in your web dyno accepts a connection, but then closes the socket without writing anything to it.`
I've implemented a counting Fairing and it doesn't even receive these requests, they seem to be failing at the network level and not reaching our app. This is what the heroku log says:

```<app_name> heroku/router at=error code=H13 desc="Connection closed without response" method=POST path="<different pathes>" host=<app_name> request_id=xxx fwd="xxx" dyno=web.1 connect=0ms service=0ms status=503 bytes=561 protocol=http tls_version=unknown```

per @emk 's suggestion on https://github.com/emk/rust-buildpack-example-rocket/issues/3, opening this here to see if you guys have any idea where I could start investigating.  
Would be happy to investigate further, appreciate your advise as for what I should try

Thanks a lot in advance!

Nimrod

**Comment by jebrosen** [comment]
I believe this issue is a duplicate of #1254: it's a consequence of Rocket 0.4 using the (not actively maintained) old synchronous version of `hyper`, which has a concurrent connection limit equal to the number of worker threads.

**Comment by nimrod-codota** [comment]
i saw that issue and was suspecting that as well. i tried increasing the worker count and dramatically upscaling the machine to no avail. ill try the keep alive workaround, thanks

**Comment by nimrod-codota** [comment]
`ROCKET_KEEP_ALIVE=0` solves this issue. Thanks for the prompt reply @jebrosen ! looking forward to 0.5. Will see what I can do to add this to the rocket heroku buildpack documentation.
