### ISSUE TITLE
No method of creating a private session cookie

### ISSUE THREAD

**Issue by trolleyman** [SergioBenitez/Rocket#1272]
I think that, if I'm not mistaken, there is no way of creating a private session cookie.

The [`add_private`](https://api.rocket.rs/v0.4/rocket/http/enum.Cookies.html#method.add_private) method of the `Cookies` object, sets `expires` to be 1 week if it is not set, however a session cookie requires the `expires` field to be not set.

**Comment by jebrosen** [comment]
This is actually already fixed: https://github.com/SergioBenitez/Rocket/issues/991#issuecomment-586665853.

However, the functionality is only present in cookie 0.13 - that is, the version of cookie used in the `master` branch of Rocket.

**Comment by trolleyman** [comment]
Ah great, thanks :)
