### ISSUE TITLE
Rocket without "private-cookies" feature still uses `ring`

### ISSUE THREAD

**Issue by grantperry** [SergioBenitez/Rocket#1275]
rocket = "0.4.4"
cargo 1.44.0-nightly (390e8f245 2020-04-07)
MacOS 10.14.6

I have added rocket to my crate with no default features, which should remove the `private-cookies` feature, removing rocket's dependancy on ring. I also use a crate that uses `ring = "0.16.5"`.

Here is my Cargo.toml:
```
rocket = { version = "0.4", default-features = false }
jsonwebtoken = "7"
```
I receive this error when building:
```
error: failed to select a version for `ring`.
    ... required by package `cookie v0.11.2`
    ... which is depended on by `rocket_http v0.4.4`
    ... which is depended on by `rocket v0.4.4`
    ... which is depended on by `admin-api v0.1.0 (/Users/me/mmt/admin-api)`
versions that meet the requirements `^0.13.0` are: 0.13.5

the package `ring` links to the native library `ring-asm`, but it conflicts with a previous package which links to `ring-asm` as well:
package `ring v0.16.5`
    ... which is depended on by `jsonwebtoken v7.0.0`
    ... which is depended on by `admin-api v0.1.0 (/Users/me/mmt/admin-api)`

failed to select a version for `ring` which could resolve this conflict
```

I would expect that with all features disabled the dependancy on `ring` via `cookie` would not be used. I also found mention to this solution [here](https://github.com/SergioBenitez/Rocket/issues/1266#issuecomment-609441310).

**Comment by jebrosen** [comment]
I tried this in a blank application and it passes `cargo build`. My guess is `cargo` is simply misreporting how `ring` got selected - do you also have other dependencies that depend on `rocket`?

**Comment by grantperry** [comment]
Having a look through my Cargo.lock the following all depend on rocket:
```
juniper_rocket = "0.5.2"
rocket_contrib = "0.4.4"
rocket_cors = "0.5.2"
```

I image I will want to try look through these and find which is including the the private-cookies feature?

**Comment by grantperry** [comment]
I think I tracked the issue back to [juniper_rocket](https://github.com/graphql-rust/juniper/blob/master/juniper_rocket/Cargo.toml) but I am unsure why it does.

A minimum example:
```
rocket = { version = "0.4", default-features = false }
jsonwebtoken = "7"
juniper_rocket = "0.5.2"
```

**Comment by jebrosen** [comment]
This is graphql-rust/juniper#530. It looks like there is no released version that has the fix in it, so you would have to depend on a git branch or revision:

`juniper_rocket = { git="https://github.com/graphql-rust/juniper.git", rev="xxxxxxx" }`

Or, perhaps you can use an older version of `jsonwebtoken`. Version `5` uses *ring* `0.13`.

**Comment by grantperry** [comment]
Thanks @jebrosen. I've got some time, so hopefully [graphql-rust/juniper#530](https://github.com/graphql-rust/juniper/pull/530) is merged before I go to production.

**Comment by grantperry** [comment]
Thanks @jebrosen, I'll try depend on a revision for the moment. Hopefully they roll out a version before I go to production.

**Comment by jebrosen** [comment]
Closing as invalid, since this turned out to be an issue in `juniper_rocket` instead.
