### ISSUE TITLE
How to enable foreign key support for SQLite?

### ISSUE THREAD

**Issue by jufickel** [SergioBenitez/Rocket#1282]
Hi,

I am using `rocket` and `rocket_contrib` in version 0.4.2. Following the [official guide](https://rocket.rs/v0.4/guide/state/#databases) for getting a SQLite connection guard works fine.

However I wonder how to enable the Pragma `"foreign_keys = ON"` to make cascading deletion work – for example. Could you please give me a hint.

Thanks a lot.

**Comment by jebrosen** [comment]
To use sqlite pragmas you will need to execute the SQL statement directly - for diesel it's [`sql_query`](http://docs.diesel.rs/diesel/fn.sql_query.html), and for rusqlite it's [`Connection.execute`](https://docs.rs/rusqlite/0.14.0/rusqlite/struct.Connection.html#method.execute).

I believe that pragma is set per connection, so you would have to enable it in every route that requires it to be sure. There isn't an easy way to get this to happen more automatically, though - you would probably have to implement your own request guard. @ELD or I had an idea for a connection customization callback which would be perfect for this, but it never turned into a concrete proposal.

**Comment by ELD** [comment]
@jebrosen This would be a good use for a connection customization callback during `on_attach` (or somewhere similar). I never materialized a proposal because I was thinking just about transactional testing.

Might be worth cooking up a proposal for that now :)

**Comment by panstromek** [comment]
You can also compile sqlite with foreign keys turned on by default. That's what `better-sqlite` for node does, for example.

**Comment by SergioBenitez** [comment]
Looks like this has been answered without further activity!
