### ISSUE TITLE
Trouble using postgres and uuid feature with rocket

### ISSUE THREAD

**Issue by cx0der** [SergioBenitez/Rocket#1284]
## Background

I am trying to learn rust and rocket, so I am fairly new to this. I am trying to build something that reads and writes to a Postgres Db that has the UUID extension.

I came across a prior issue https://github.com/SergioBenitez/Rocket/issues/993 about how to go about using non-default features with postgres

## Bug Reports

  1. Rocket version 4.4

  2. rustc version `rustc 1.44.0-nightly (ce93331e2 2020-04-17)`

  3. Fedora 32

  4. Compilation fails when I try to interact with a DB column that has UUID.

### cargo.toml

```
[package]
name = "rocket-test"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = "0.4.4"
uuid = "0.7.4"

[dependencies.rocket_contrib]
version = "0.4.4"
default-features = false
features = ["uuid", "postgres_pool"]

[dependencies.postgres]
version = "0.15"
features = ["with-uuid"]
```

I have included postgres and a dependency to enable to feature `with-uuid`.

### main.rs

```
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use] extern crate rocket;
#[macro_use] extern crate rocket_contrib;

use rocket_contrib::databases::postgres;
use std::collections::HashMap;

use rocket::config::{Config, Environment, Value};

use rocket_contrib::uuid::Uuid;

#[database("postgres_pool")]
#[derive(Debug)]
struct Conn(postgres::Connection);


#[get("/")]
fn index(conn: Conn) -> &'static str {
    let q = "SELECT channel_id FROM channels";
    for row in conn.query(&q, &[]).unwrap().iter() {
        let id: Uuid = row.get("channel_id");
    }
    "Hello, world!"
}

fn get_config() -> Config {
    let environment = Environment::active().expect("No environment found");
    let mut database_config = HashMap::new();
    let mut databases = HashMap::new();
    database_config.insert("url", Value::from("postgres://user:pass@localhost/db_name"));
    databases.insert("postgres_pool", Value::from(database_config));

    Config::build(environment)
        .environment(environment)
        .extra("databases", databases)
        .finalize()
        .unwrap()
}

fn main() {
    rocket::custom(get_config())
    .attach(Conn::fairing())
    .mount("/", routes![index]).launch();
}
```

Compiler seems to have a problem with line ` let id: Uuid = row.get("channel_id");`  and complains about "`rocket_contrib::databases::postgres::types::FromSql` is not implemented for `rocket_contrib::uuid::Uuid`"

Tried asking this on IRC as well, and I was point to #993.

What is the mistake I am making.

**Comment by jebrosen** [comment]
One problem here is that `postgres 0.15` uses `uuid 0.5`, but `rocket_contrib 0.4` uses `uuid 0.7`. The other problem is that `rocket_contrib::uuid::Uuid` is *not* `Uuid` from the `uuid` crate; it is a wrapper that implements `FromParam`.

In your current code you don't need `Uuid` from `rocket_contrib` at all. Instead, you would need to add the `uuid` dependency (version 0.5!) to your own `Cargo.toml` and `use uuid::Uuid;` to get the type that `postgres` can deserialize from the database.

If you do start using both rocket's `Uuid` type and postgres's, you would need to convert between them. Depending on how much you use UUIDs in route paths, it may be easier to use `String` parameters or to make a copy of `rocket_contrib::uuid::Uuid` that uses the version of the `uuid` crate that you need.

**Comment by cx0der** [comment]
That works! Thank you for your help @jebrosen.

To summarize the solution.

Add the lowest version of the common dependency with `postgres` and `rocket_contrib` crates as the applications dependency explicitly and use that directly and not refer to what `rocket_contrib` exposes.
