### ISSUE TITLE
My Rocket won't start.

### ISSUE THREAD

**Issue by Voodlaz** [SergioBenitez/Rocket#1287]
When I try to run `cargo run` It's gives me this error:

`Error: Rocket failed to bind network socket to given address/port.
thread 'main' panicked at 'Сделана попытка доступа к сокету методом, запрещенным правами доступа. (os error 10013)', C:\Users\user\.cargo\git\checkouts\rocket-8bf16d9ca7e90bdc\9f0e02f\core\lib\src\error.rs:192:17
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
error: process didn't exit successfully: target\debug\rocket_blog.exe(exit code: 101)`

I haven't got any process running.
My code worked perfectly Until today, but I hasn't changed any code.
P.S. I'm working on Windows.

**Comment by jebrosen** [comment]
I am not familiar with windows error codes, but it looks like that could be a conflict with another running server. If you solved it, we would appreciate a note for anyone who has the same problem in the future!

**Comment by Voodlaz** [comment]
Yes, I have solved the problem, it was confilcting.
