### ISSUE TITLE
Copyright owner information is missing from Apache License file

### ISSUE THREAD

**Issue by klingtnet** [SergioBenitez/Rocket#1290]
Please fill out this line: [LICENSE-APACHE#L189](https://github.com/SergioBenitez/Rocket/blob/1010f6a2a88fac899dec0cd2f642156908038a53/LICENSE-APACHE#L189)

```
...
Copyright [yyyy] [name of copyright owner]
...
```

**Comment by ralpha** [comment]
Was going to note the same thing. Also:

Looking in crates.io I also noticed your license states:
https://github.com/SergioBenitez/Rocket/blob/1010f6a2a88fac899dec0cd2f642156908038a53/core/lib/Cargo.toml#L13
Maybe consider changing this to:
```
license = "MIT OR Apache-2.0"
```
Then it is written the same way as other rust-lang licenses.
