### ISSUE TITLE
Unable to render GIF with handlebars

### ISSUE THREAD

**Issue by niharrs** [SergioBenitez/Rocket#1291]
main.rs- 
```
#![feature(plugin)]

#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use] extern crate rocket;
#[macro_use] extern crate serde_derive;
extern crate rocket_contrib;

use rocket::Request;
use rocket::response::Redirect;
use rocket_contrib::templates::{Template, handlebars};
use rocket_contrib::serve::StaticFiles;

use handlebars::{Helper, Handlebars, Context, RenderContext, Output, HelperResult, JsonRender};

#[derive(Serialize)]
struct TemplateContext {
    title: &'static str,
    name: Option<String>,
    items: Vec<&'static str>,
    // This key tells handlebars which template is the parent.
    parent: &'static str,
}

#[get("/")]
fn index() -> Redirect {
    Redirect::to("https://twitter.com")
}

#[catch(404)]
fn not_found(req: &Request) -> Template {
    let mut map = std::collections::HashMap::new();
    map.insert("path", req.uri().path());
    Template::render("error/404", &map)
}

fn main() {
    rocket::ignite()
        .mount("/", routes![index])
        .mount("/", StaticFiles::from("static/"))
        .attach(Template::fairing())
        .register(catchers![not_found])
        .launch();
}
```
404.hbs-
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Oops! Error!</title>
  </head>
  <body>
    <div>
      <img src="/static/error.gif" alt="404 error">
    </div>
  </body>
</html>
```

Console-
```
GET /static/image.jpg image/webp:
    => Matched: GET /<path..> [10]
    => Warning: Response was `None`.
    => Outcome: Failure
    => Warning: Responding with 404 Not Found catcher.
    => Response succeeded.
```
File structure:
```
-src
    --main.rs
-static
    --error.gif
-templates
    --error
        ---404.hbs
    --index.hbs
cargo.tml
```
<img width="782" alt="Screenshot 2020-04-28 at 7 31 03 PM" src="https://user-images.githubusercontent.com/24189168/80496419-cdd2f900-8986-11ea-9c7a-a4f2d1f09354.png">

<img width="1242" alt="Screenshot 2020-04-28 at 7 31 40 PM" src="https://user-images.githubusercontent.com/24189168/80496487-e5aa7d00-8986-11ea-921f-f714d1583751.png">

**Comment by jebrosen** [comment]
You are trying to access `image.jpg` but the file is named `image.gif` - which one is correct?

**Comment by niharrs** [comment]
There were actually two assets `error.gif` and `image.jpg`. But for the sake of the question, I mentioned one. 

<img width="422" alt="Screenshot 2020-04-28 at 9 13 24 PM" src="https://user-images.githubusercontent.com/24189168/80507995-1a253580-8995-11ea-8d70-30b8cdcd4d02.png">

**Comment by jebrosen** [comment]
It is probably this, then:

`.mount("/", StaticFiles::from("static/"))`

This checks any request to `/<filename>` against `static/<filename>`, so `GET /static/error.gif` would be looked for at `static/static/error.gif`. It looks like instead you want `.mount("/static", StaticFiles::from("static/"))`.

**Comment by niharrs** [comment]
Yes, I just caught the error.

I changed the `img` source to `/error.gif` from `/static/error.gif`. Thanks.
