### ISSUE TITLE
Rocket can't find route that exists

### ISSUE THREAD

**Issue by Voodlaz** [SergioBenitez/Rocket#1293]
I'm trying to make a Post creating form.
I'm getting error that It can't find route /new_post.

function new_post:
`#[post("/new_post", data="<form>")]
fn new_post(form: Form<NewPostForm>) -> Template {
    let context: HashMap<&str, &str> = HashMap::new();
    Template::render("new_post", &context)
}`

I think the problem is that it can't find a <form> in templates for a POST request. Only I can't understand how to solve it.

**Comment by jebrosen** [comment]
Can you post the log output from the request?

**Comment by Voodlaz** [comment]
@jebrosen here the logs:

```
GET /new_post text/html:
    => Matched: GET /<path..> [10]
    => Warning: Response was None.
    => Outcome: Failure
    => Warning: Responding with 404 Not Found catcher.
    => Response succeeded.
```

**Comment by jebrosen** [comment]
That's more or less expected - you made a GET request, but you defined a route for a POST request.

For a standard HTML form, the GET route is the one that should serve a `Template`. The POST request should process the form, and then either serve the same or a different `Template` or send a `Redirect` depending on your needs.

**Comment by Voodlaz** [comment]
@jebrosen thanks! I have solved the problem.
