### ISSUE TITLE
Support for Dartlang

### ISSUE THREAD

**Issue by hukynobo** [SergioBenitez/Rocket#1294]
As you know, an interesting alternative to JavaScript is Dartlang created by Google, which has a better and more understandable syntax and is more modern. It would be great if Rocket support will add to Rocket to generate JavaScript automatically in a situation where some browser did not support Dartlang yet. A similar solution was applied to Django packages. In my opinion, it's a great combination of Rust + SASS + Dart. SASS has great support for Dart.
https://sass-lang.com/dart-sass

**Comment by Voodlaz** [comment]
This is strange. Why Sergio Benitez not putting some labels on new features? It's looks like Rocket is dead.

**Comment by asonix** [comment]
I haven't looked at Dart in years, but if it's running in a browser, shouldn't it always be javascript? I was under the impression that dartium was never going to be merged to chromium upstream

**Comment by SergioBenitez** [comment]
@Voodlaz Rocket is alive and well!

**Comment by jebrosen** [comment]
> It would be great if Rocket support will add to Rocket to generate JavaScript automatically in a situation where some browser did not support Dartlang yet.

This sounds out of scope for Rocket core, which knows nothing about the client side of the application aside from the contents of the HTTP responses. It's plausible that something could be included in `contrib`, but it sounds like a relatively niche use case that can be done in a library first.

**Comment by awulkan** [comment]
> I haven't looked at Dart in years, but if it's running in a browser, shouldn't it always be javascript? I was under the impression that dartium was never going to be merged to chromium upstream

That's right, no browsers execute Dart directly. Dart needs to be compiled to JavaScript to run in the browser.

**Comment by teymour-aldridge** [comment]
> I haven't looked at Dart in years, but if it's running in a browser, shouldn't it always be javascript? I was under the impression that dartium was never going to be merged to chromium upstream

You can use WebAssembly instead of Javascript.

**Comment by SergioBenitez** [comment]
I'm in agreement with @jebrosen. Closing as out-of-scope.
