### ISSUE TITLE
Gives error 422 when trying to submit the form.

### ISSUE THREAD

**Issue by Voodlaz** [SergioBenitez/Rocket#1295]
I'm trying to make a form to create posts(I'm not acessing db yet).
When I try to submit the form

Error:
```
POST /new_post application/x-www-form-urlencoded:
    => Matched: POST /new_post (new_post_form)
    => Error: The incoming form failed to parse.
    => Outcome: Failure
    => Warning: Responding with 422 Unprocessable Entity catcher.
    => Response succeeded.
```
Handler:
```
#[post("/new_post", data="<form>")]
fn new_post_form(form: Form<NewPostForm>) -> Flash<Redirect>  {
    let form = form.into_inner();
    if form.body.is_empty() {
        Flash::error(Redirect::to("/new_post"), "NoBodyError");
    }
    if form.name.is_empty() {
        Flash::error(Redirect::to("/new_post"), "NoNameError");
    }
    if form.name.is_empty() && form.body.is_empty() {
        Flash::error(Redirect::to("/new_post"), "NoNameBodyError")
    } else {
        Flash::error(Redirect::to("/new_post"), "NoNameBodyError")
    }
}
```
Form struct:
```
#[derive(FromForm)]
pub struct NewPostForm {
    pub name: String,
    pub body: String
}
```
Form:
```
<form action="/new_post" method="post">
  name:<input type="text" name="name" id="name">
  Body:<input type="text" name="body" id="body">
  <button type="submit" name="button"></button>
</form>
```

**Comment by mjanda** [comment]
Are you using Form or LenientForm in your handler? Becase your post data will contain also your submit button.

**Comment by Voodlaz** [comment]
@mjanda I have added the Handler's code.

**Comment by mjanda** [comment]
@Voodlaz try changing `Form<NewPostForm>` to `LenientForm<NewPostForm>`. That will ignore your submit.

Or add it to your form struct.

**Comment by Voodlaz** [comment]
@mjanda How can I submit the Forms? because I need data to get To the server.
P.S. Changing `Form<NewPostForm>` to `LenientForm<NewPostForm>` worked.

**Comment by jebrosen** [comment]
> How can I submit the Forms? because I need data to get To the server.

I am not sure what you mean by this question. With your first error (`The incoming form failed to parse`), the form has been submitted and sent data to the server. Has something else changed that the form is not submitting anymore?

**Comment by olback** [comment]
I don't know for sure but removing the name attribute from the button might work.

**Comment by Voodlaz** [comment]
@olback Thanks! That solved the problem.

**Comment by pinpox** [comment]
I'm having a similar problem, is there a way to debug parsing in general? I would like to print what fields where missing or failed to parse, how can I spit out some information about what went wrong when parsing?
