### ISSUE TITLE
Rich Text Support for Rocket.

### ISSUE THREAD

**Issue by Voodlaz** [SergioBenitez/Rocket#1296]
It will be very good if there will be added Rich Text Support for Rocket. This new feature would make possible to make not just text, but complex blog posts(or something else) with images,links,text titles and much more. This features is been used by Django.

**Comment by jebrosen** [comment]
"Rich Text Support" is pretty broad. I found a few different kinds of answers trying to learn about Django's rich text support - can you share a link to some documentation for Django that explains the feature?

**Comment by Voodlaz** [comment]
@jebrosen By Rich Text I mean HTML. In Django, there's a tag `{ <there goes context> | safe }` that makes from ordinary text(but with HTML markdown) to HTML tags.

**Comment by Voodlaz** [comment]
@jebrosen Here the link:
https://docs.djangoproject.com/en/3.0/ref/templates/builtins/#std:templatefilter-safe

**Comment by nCrazed** [comment]
This functionality is/should be covered by the templating engine that you're using.

**Comment by Voodlaz** [comment]
@nCrazed Okay. I understand.
