### ISSUE TITLE
How to access raw POST data?

### ISSUE THREAD

**Issue by mjanda** [SergioBenitez/Rocket#1297]
Hello,
I'm trying to implement PayPal IPN handler.

It takes raw post data, sends it to paypal website that will verify them. Then you also extract from them some variables and process them. So you'd need both raw data and extracted values.

I was thinking about using `rocket::Data` directly in my handler, read data into `Vec<u8>` use them in my request and ... well, I'm not sure how to extract anything else from that data. `Data::from_local` is private, constructing it manually would require importing parts of hyper. Am I missing some reasonable options?

Thank you

**Comment by jebrosen** [comment]
I believe this is a duplicate of #775, this is indeed a use case that the `Data` API can't really handle.

Currently, you are "stuck" with extracting the data manually as if `FromData` didn't exist - e.g. with `serde_json::from_slice`.

**Comment by mjanda** [comment]
Ok, thank you. I'll try it that way.
