### ISSUE TITLE
rocket_contrib::uuid::Uuid missing FromUriParam?

### ISSUE THREAD

**Issue by brownjohnf** [SergioBenitez/Rocket#1299]
I have a question, which I _think_ (if I'm correct) translates into a feature request.

`rocket version`: 0.4.4
`rocket_contrib version`: 0.4.4

I've looked through all issues I can find relating to the `uri!` macro and `uuid` from `rocket_contrib`, but as far as I can tell the `Uuid` type from `rocket_contrib` does not implement the `rocket::http::uri::FromUriParam` trait, which means it cannot be passed as an argument to the `uri!` macro.

Here's a basic example of what I'm trying to do:

```
#[get("/repositories/<repo_uuid>")]
pub fn show(
    repo_uuid: rocket_contrib::uuid::Uuid,
) -> Template {
...
}

#[put("/repositories/<repo_uuid>"]
pub(crate) fn update(
    repo_uuid: rocket_contrib::uuid::Uuid,
) -> Redirect {
    Redirect::to(uri!("/", show: repo_uuid = repo_uuid))
}
```
I want to redirect to a route that takes a UUID in the path. The route works fine, because of the `FromParam` implementation on `rocket_contrib::uuid::Uuid`. However, I get the following error when trying to use the UUID in the `uri!` macro:

```
the trait `rocket::http::uri::FromUriParam<rocket::http::uri::Path, _>` is not implemented for `rocket_contrib::uuid::Uuid`
```

I don't think documentation is required here, provided that I'm correct in my assessment of the situation, but I do think that it would be nice if `rocket_contrib::uuid::Uuid` implemented FromUriParam. Or I'm missing something and it actually does.

**Comment by jebrosen** [comment]
Yes, these implementations are missing. It should be solved by #1024.

**Comment by brownjohnf** [comment]
Okay, cool. Shall I close the issue?

**Comment by jebrosen** [comment]
Might as well leave it open, so it's easier for others to find!
