### ISSUE TITLE
Calling ws from rocket route

### ISSUE THREAD

**Issue by hyousefGopher** [SergioBenitez/Rocket#1303]
Hi, not sure if this should be assured here or at tungstenite as.

I've 2 main routes in my rocket.rs app:

```rust
#[get("/route1")]
fn route1() -> Template {}

#[get("/route2")]
fn route2() -> Template {}
```

And I want to use `ws` so that from each route I can send different msg for all connected and opened sockets,

I run the `ws` as shown in the server exams as:
```rust
spawn( move || {
     let mut websocket = ....
})
``|

**Comment by nCrazed** [comment]
Looks like a use case for [Managed State](https://rocket.rs/v0.4/guide/state/#managed-state)

**Comment by hyousef-rusty** [comment]
mmm, can you help more, I tried the below but ended up in an endless loading of the page.

```rust
struct WebSocket(TcpListener);

fn main() {
    let server = WebSocket(TcpListener::bind("127.0.0.1:3012").unwrap());
    rocket::ignite()
    .mount("/", routes![root])
        .manage(WebSocket(server.0))
    .attach(Template::fairing())
    .launch();
}

#[get("/")]
fn root(ws: State<WebSocket>) -> Template {
    let mut context = HashMap::<&str, i32>::new();
    context.insert("value", 3);


    for stream in ws.0.incoming() {
      //  spawn(move || {
            let callback = |req: &Request, mut response: Response| {
                println!("Received a new ws handshake");
                println!("The request's path is: {}", req.uri().path());
                println!("The request's headers are:");
                for (ref header, _value) in req.headers() {
                    println!("* {}", header);
                }

                // Let's add an additional header to our response to the client.
                let headers = response.headers_mut();
                headers.append("MyCustomHeader", ":)".parse().unwrap());
                headers.append("SOME_TUNGSTENITE_HEADER", "header_value".parse().unwrap());

                Ok(response)
            };
            let mut websocket = accept_hdr(stream.unwrap(), callback).unwrap();

            loop {
                let msg = websocket.read_message().unwrap();
                if msg.is_binary() || msg.is_text() {
                    println!("I'm the server, recieved {} and will send it back", msg);
                    websocket.write_message(msg).unwrap();

                }
            }
    //    });
    }

    Template::render("index", context)
}
```

**Comment by nCrazed** [comment]
`loop` is an infinite loop that as far as I can tell you're not breaking it in any way.

**Comment by hyousef-rusty** [comment]
But nothing is disposing in the browser, i.e. the rite not retaining the result, also the ws server is not receiving/sending any thing

**Comment by nCrazed** [comment]
Nothing will be displayed in the browser because your route handler is always looping trying to read a message and never gets to rendering the template response.

**Comment by hyousef-rusty** [comment]
mmm, actually not this what I'm looking for, I need to get the template displayed and at the same time having the ws opened and ready to send back to the user based on his inputs in the template

**Comment by nCrazed** [comment]
Most of that ws code should probably be running in its own thread. Then you can use some communication mechanism (wrapped in a managed state) to pass important events from the rocket routes to the ws thread.

**Comment by hyousef-rusty** [comment]
This is the point, how can I pass events from rocket routes to the ws thread?

**Comment by nCrazed** [comment]
Either by sharing the ws instance (via managed state mechanism) and writing to it directly or using something like channels to pass messages to your ws thread and lit it do the writing.

**Comment by hyousef-rusty** [comment]
I tried sharing the instant as shown in my code above, but did not work, is there something wrong in mm code regarding the way of sharing?

**Comment by nCrazed** [comment]
It's not the sharing, but usage that is wrong.

You are "forever" listening for new messages in your `GET /` route which means that the route will never return. The listening code needs to be outside of the route. Route should only do a one-off write and then return.

**Comment by hyousef-rusty** [comment]
Then I stuck, can you help with code snippets

**Comment by jebrosen** [comment]
With the channel approach, you would *probably* use the `Receiver` end in the websocket server and the `Sender` end in the rocket server (or possibly both). The `mpsc::channel` `Sender` is not `Sync`, so you may want to use a different channel such as `mpsc::sync_channel` or something from `crossbeam-channel`.

**Comment by SergioBenitez** [comment]
Looks like this has been answered without further activity!
