### ISSUE TITLE
Typo in documentation Trait rocket::request::FromQuery

### ISSUE THREAD

**Issue by ralpha** [SergioBenitez/Rocket#1304]
There is a minor typo on the page:
https://api.rocket.rs/v0.4/rocket/request/trait.FromQuery.html
or
https://docs.rs/rocket/0.4.4/rocket/request/trait.FromQuery.html

In section: Provided Implementations
> The path segment is parsed by T's FromQuery mplementation. The returned Result value is returned.

should be change to:

> The path segment is parsed by T's FromQuery **implementation**. The returned Result value is returned.

Very minor, but also a quick fix.

**Comment by jebrosen** [comment]
#1315 has been merged!
