### ISSUE TITLE
Help with Streaming data

### ISSUE THREAD

**Issue by hyousefGopher** [SergioBenitez/Rocket#1305]
I wrote the below:
```rust
struct PipeLoop {filename: String}
impl PipeLoop {
    fn new(filename: &str) -> PipeLoop {
        let p = PipeLoop {filename: filename.to_string()};
        p
    }
}
impl Read for PipeLoop {
    fn read(&mut self, buf: &mut [u8]) -> Result<usize, Error> {
        let mut fd: File = File::open("start").unwrap();
        let len;

        println!("Opening file {}", &self.filename);
        'open: {
            fd = match File::open(&self.filename) {
                Err(e) => {
                    println!("Failed to open {}, {}", self.filename, e);
                    break 'open;
                    //return Ok(0);
                },
                Ok(f) => { f }
            };
        }


        println!("Reading file {}", &self.filename);
        len = match fd.read(buf) {
            Err(e) => {
                println!("Failed to read {}, {}", self.filename, e);
                return Ok(0);
            },
            Ok(buf) => { buf }
        };

        println!("Successfully read {} bytes from file {}", len, &self.filename);
        Ok(len)
    }
}
```

That worked with:
```rust
#[get("/")]
fn root() -> content::Html<String> {
    content::Html(format!(r#"
    <br/>Welcome
    <div id="content"></div>

    <script>
        function loard(url, element)
        {{
            req = new XMLHttpRequest();
            req.open("GET", url, false);
            req.send(null);

            element.innerHTML = req.responseText;
        }}

        load("stream", document.getElementById("content"));
     </script>
    "#))
}

#[get("/stream")]
fn stream() -> Stream<PipeLoop> {
    let p = PipeLoop::new("testfile");
    Stream::from(p)
}
```

This works, read from file and stream data to the specified div, but I've 2 issues:

1. The stream is interrupted if the content of the file changed, I need it to keep streaming the new data

2. The stream append data, not overriding it , if the file contains `Test stream data` it will be streamed multiple times as below, I need the streamed to be shown once, and keep overwritten:

I get this:
![image](https://user-images.githubusercontent.com/60115476/82693595-7c0e4d80-9c6a-11ea-9444-5e5cb291d11d.png)

I want this:

![image](https://user-images.githubusercontent.com/60115476/82693734-b1b33680-9c6a-11ea-84a1-a38dc93cb8d3.png)

**Comment by jebrosen** [comment]
Streaming files in this way is surprisingly complex, and there are many ways it can fail, cause other issues, or not work how one might expect. For that reason, I suggest accomplishing your goal with a different technology if possible. That said, here are a few pointers based on the code you posted:

---

```rust
impl Read for PipeLoop {
    fn read(&mut self, buf: &mut [u8]) -> Result<usize, Error> {
        let mut fd: File = File::open("start").unwrap();
```

This is the cause of your problem 2: `read` is called repeatedly to get a bit more data at a time, and you re-open the `File` (from the beginning) on each call to `read`. The `File::open` could be done in `PipeLoop::new` instead so you are reusing the same `File`.

> The stream is interrupted if the content of the file changed, I need it to keep streaming the new data

This is much harder. Normally "reading" 0 bytes (the end of the file) is treated as permanent, so the stream will end as soon as the current end of the file is reached. For live streaming, you would need to check for that, and wait for the file to change before giving the new data. That will require code specific to each operating system where the server will run, or maybe it already exists in a library.

> ```
> req = new XMLHttpRequest();
> req.open("GET", url, false);
> req.send(null);
> element.innerHTML = req.responseText;
> ```

The client code doesn't quite do what you want either. `false` means the client will wait for the server to say it is done, which is "never" if the file is streaming. You will need to use something like [`onreadystatechange`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/onreadystatechange) to continue updating as data becomes available.

**Comment by SergioBenitez** [comment]
Looks like this has been answered without further activity!
