### ISSUE TITLE
Cross compilation for FreeBSD fails

### ISSUE THREAD

**Issue by gahag** [SergioBenitez/Rocket#1307]
I'm trying to cross build a project that uses Rocket from Linux to FreeBSD, but Rocket fails to build. I'm having a hard time troubleshooting this, so I would really appreciate your help. I'm using a docker image to setup the toolchains, so this should be easily reproducible. I'm not sure whether this is a issue directly with Rocket, or one of it's dependencies, so that's why I'm posting the just the minimal details. I can provide the docker file/image and anything else requested.

I would like to note that the same version of the project builds fine in FreeBSD. The error only occurs when cross compiling.

The build fails with:
```
   Compiling rocket v0.4.4
error: /home/rust/code/target/release/deps/librocket_codegen-e2859b228468d6ea.so: undefined symbol: GFp_SYS_GETRANDOM
  --> /home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.4/src/lib.rs:99:39
   |
99 | #[allow(unused_imports)] #[macro_use] extern crate rocket_codegen;
   |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `rocket`.
```
I noticed that `GFp_SYS_GETRANDOM` is a symbol from the Ring dependency, even though cargo errors on Rocket itself. Is this likely to be an issue with Rocket, or Ring? How can I proceed to troubleshoot this issue? I have no idea what's going on.

1. Rocket version: 0.4.4
2. Operating system: Linux (Docker)
3. Target operating system: FreeBSD 12

**Comment by jebrosen** [comment]
The most helpful information you could add for reproduction/testing is the `Dockerfile` or at least the tool you are using to do the actual cross-compilation. It may end up being a problem with `ring`, but it might also be a quirk specific to a tool/container/configuration involved.

**Comment by gahag** [comment]
So, I've set up a self contained minimal reproducible example here:
https://github.com/gahag/rocket-cross-fail-demo

This is basically the hello world example from this repository bundled with the cross build dockerfile.
Building this should be really simple and automatic, but it can be a little bit slow because it compiles gcc and some tools. The precise instructions are on the repository.

Please let me know if you find out anything about it, or of anything else I can be of help.

**Comment by gahag** [comment]
I've updated the repository with a newer gcc version.

**Comment by jebrosen** [comment]
I get a slightly different error:

```
error: /rust/project/target/release/deps/librocket_codegen-ea568c49201ed67b.so: undefined symbol: __stack_chk_guard
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.4/src/lib.rs:99:39
   |
99 | #[allow(unused_imports)] #[macro_use] extern crate rocket_codegen;
   |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

I suspect this has something to do with `rocket_codgen` being a `proc_macro` crate, which are dynamically linked and need to be run on the host instead of the target. I also found that `rocket_codegen` (a bit surprisingly) does depend on `ring`, via `rocket_http`.

**Comment by gahag** [comment]
Thanks for taking your time into this. I have seen that error too, but I think it got back to the original error when I updated the GCC version in the container, but I'm not sure that's consistent. Thanks for the tip on `rocket_codegen`, I'll try to investigate how it's being compiled in my setup.

By the way, is there a expectation for when Rocket will update it's Ring dependency? I've seen some discussions around it in other issues, but I don't know if it's something the maintainers plan to do in the near future. The project I'm trying to cross-compile directly depends on both Rocket and Ring, but a newer version of Ring that apparently compiles fine.

**Comment by SergioBenitez** [comment]
@gahag The latest update to `cookie` removes the dependency on `ring`, which removes Rocket's dependency on `ring` by default (that is, as long as TLS isn't enabled). Can you try now and see if your issues are resolved?

**Comment by gahag** [comment]
@SergioBenitez I'll check that out tomorrow. Thanks for the hint!

**Comment by gahag** [comment]
@SergioBenitez This seems to have fixed my issue. Thanks a lot for the help!
