### ISSUE TITLE
More ergonomic/less boilerplate response handling for JSON

### ISSUE THREAD

**Issue by jrozner** [SergioBenitez/Rocket#131]
This would apply to other data formats as well but JSON is the example used.

Rocket makes it incredibly easy to handle JSON input and responses for http endpoints when the output is always going to be exactly the same; however in most JSON apis this is rarely the case. There might be one expected result that's always the same structure, with perhaps some optional fields, but this is all simply handled by declaring the type of the member as an Option<T>. The real issue comes when something goes wrong and a handler needs to respond with an error message or some data that isn't the normal expected response.

As far as I can tell the only ways to currently handle this are to either subvert the strong typing and use a HashMap, some enum type as the response, such as Result, rather than specifying the intended type and getting all the benefits of static typing, or a string and passing back the serialized value. The Result/enum works but then the response that's actually sent to the client is wrapped in the variant (either "Err": {} or "Ok": {}) which isn't really ideal.

From the bit of reading I've done about serde it looks like custom serializers could be written to remove the variant wrapping of the enum type. Would it make sense to build a helper type into Rocket to handle this case that's generic over two types (the expected result and error type) since this is something that would likely need to be done quite often?

**Comment by SergioBenitez** [comment]
Hmm, perhaps I'm missing something here, but I believe returning a `Result<JSON<T>, JSON<E>>` will do exactly what you'd like. The JSON derived from T or E won't have any `Err` or `Ok` fields.

**Comment by chrisoverzero** [comment]
Just a wild guess here, @jrozner, but does your handler have the return type `JSON<Result<T, E>>`? I think that would cause the symptoms you're seeing. Flipping the wrappers, as @SergioBenitez said, should get the correct structure.

**Comment by jrozner** [comment]
Just verified that this solution does work. Thanks

**Comment by SergioBenitez** [comment]
Glad to hear! :D
