### ISSUE TITLE
add_template_files to Tera

### ISSUE THREAD

**Issue by hyousef-rusty** [SergioBenitez/Rocket#1314]
I'm trying to write:
```rust
#![feature(decl_macro, proc_macro_hygiene)]
use rocket_contrib::templates::{Template}

main()
    rocket::ignite()
    .attach(Template::custom(|engine|{
        engine.tera.add_template_files("",);
    }))
    .launch();
}
```

But it looks it needs 2 params, and I did not find any documentation for it.

**Comment by SergioBenitez** [comment]
I'm not sure what you're trying to do. Rocket automatically registers template files, so you shouldn't need to call this manually. The documentation is here: https://api.rocket.rs/v0.4/rocket_contrib/templates/index.html.

**Comment by Mcat12** [comment]
Hey @SergioBenitez, @hyousef-rusty is trying to embed template files using `rust-embed`. In the linked issue we pointed him to the [`Tera::add_raw_templates`] documentation. He's having some issues understanding how to read the docs and use the code, but this is not an issue with Rocket.

> But it looks it needs 2 params, and I did not find any documentation for it.

If you scroll up to the function above [`Tera::add_raw_templates`], `add_raw_template`, the parameters are more clearly documented. The first string is the filename and the second is the file contents.

[`Tera::add_raw_templates`]: https://docs.rs/tera/0.11.20/tera/struct.Tera.html#method.add_raw_templates
