### ISSUE TITLE
Upgrade Tera to 1.3.0

### ISSUE THREAD

**Issue by sternj** [SergioBenitez/Rocket#1316]
## Feature Request
The most recent release of Tera has some new filters, particularly the `urlencode_strict` filter, which escapes spaces. 
## General Comments
I have a local repo where I tried just changing the tera version in contrib/lib/cargo.toml from 1.0.2 to 1.3.0 and it maintains test passage.

**Comment by SergioBenitez** [comment]
`1.3.0` is semver compatible with `1.0.2`, so we shouldn't need to make any changed in Rocket for you to get the new version. Can you confirm that a simple `cargo update` gets you the latest version?

**Comment by sternj** [comment]
Confirmed-- here's the entry in `Cargo.lock`
```
[[package]]
name = "tera"
version = "1.3.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "44567278e3f16c6f888f4a1426d1af33827e6bffbe3911fe24aec2c594f0dfcb"
dependencies = [
 "chrono",
 "chrono-tz",
 "globwalk",
 "humansize",
 "lazy_static 1.4.0",
 "percent-encoding 2.1.0",
 "pest",
 "pest_derive",
 "rand 0.7.3",
 "regex 1.3.9",
 "serde",
 "serde_json",
 "slug",
 "unic-segment",
]
```

**Comment by SergioBenitez** [comment]
Excellent!
