### ISSUE TITLE
Accessing rocket state in spawned background process

### ISSUE THREAD

**Issue by lamka02sk** [SergioBenitez/Rocket#1323]
I am working on a service where route spawns background process, so the client doesn't have to wait, until all of the heavy computational stuff is complete. The problem is that I need access to the app state inside the background process to update work progress status (the app is currently not using any database so everything non-permanent is stored in the app state and everything permanent is stored in files).

To get a better picture of what I am trying to achieve, here is my code:
```rust
use rocket_contrib::json::Json;
use crate::models::Response;
use crate::guards::auth::AuthGuard;
use rocket::{State};
use crate::state::AppState;
use std::thread::spawn;

#[get("/route")]
pub fn route(auth: AuthGuard, app_state: State<AppState>) -> Json<Response> {

    spawn(move || {
        xxx::start(auth.get(), app_state); // <--- not working, rust compiler can't determine lifetime of app_state variable 
    });

    Response::success("OK", None)

}
```

Is there any way to access the app state inside the closure, or I have to use files to manage state from inside of the closure manually?

Thank you!

**Comment by SergioBenitez** [comment]
Looks like this has been answered without further activity!
