### ISSUE TITLE
Patch resource with dynamic payload managing 3 states for a field

### ISSUE THREAD

**Issue by hidwulf** [SergioBenitez/Rocket#1327]
I, maybe I didn't look enough but I didn't find my answer.

Use case:
* Patch API over a resource with a dynamic payload
* the payload may or may not contain field for update. Usually in null friendly (or algebric one) language we could have:
   * Null: field not present in the payload 
   * None: field explicitly set to null in the payload (ex: "name": null)
   * Some: fileld set to a value (ex: "name": "John")

Examples:
```
pub struct User {
  id: UUID  
  name: String,
  nickname: String,
  age: u8
}

pub struct UserPatchPayload { 
  name: Option<String>,
  nickname: Option<String>,
  age: Option<u8>
}

#[patch("/item", format = "application/json", data = "<user>")]
pub fn patch(user: Json<UserPatchPayload>) -> Json<User> { 
  /* ... */
}

```
```
Use case: I want to update the name of a user
Patch /rest/v1/user/ca4454d1-4d38-427c-b7b1-6891790cb933
Body { "name": "Tom" }
```
it detect a Some("Tom"), a Some("Tom") is detected we have something to update, the rest is None we don't care. 

```
Use case: I want to update my name but also remove my name
Patch /rest/v1/user/ca4454d1-4d38-427c-b7b1-6891790cb933
Body { "name": "Tom", "age": null }
```
Same as before, it detect a Some("Tom"), but we want to know that the API caller wants his name set to null. But unfortunately it's also a None like above.

So in these two examples we cannot see the difference from backend perspective.

In haskell I would have a special json/string decoder allowing to use an algebric datatype representing our 3 states.

How do you think we could handle that with Rocket/Rust?

Thanks in advance.

**Comment by jebrosen** [comment]
`Json` uses `serde_json` for the actual parsing and mapping to rust structs, and there is a possible solution posted at <https://github.com/serde-rs/serde/issues/984#issuecomment-314143738>. More details / future work on that is tracked in <https://github.com/serde-rs/serde/issues/1042>.

Further questions on this would be best answered on that repository, so I'm going to close this issue.
