### ISSUE TITLE
Adding (.js).map extension

### ISSUE THREAD

**Issue by ralpha** [SergioBenitez/Rocket#1336]
This is not a bug report but more a small feature request.
Currently in the list of extensions there is one missing which I think might want to be added.
https://docs.rs/rocket/0.4.5/rocket/http/struct.ContentType.html#method.from_extension

Files with the `.js.map` are currently not handled. I know this is a file with a double extension.
(same for `css.map` (and `ts.map`))
But `.map` is otherwise not a common extension.

So this is a proposal to add `map - ContentType::JavaScript` to the list.

**Comment by SergioBenitez** [comment]
We only add media types that are registered with IANA. Are these registered with IANA? If so, could you point us to the relevant registrations?

**Comment by ralpha** [comment]
It seems to be more common practice then a standard on the web. All most popular browsers support it (Chrome, Firefox, Edge, Safari,..) but the file extension is optional. But almost always used.
So if only IANA registered are added. This is not one of them.

**Comment by jebrosen** [comment]
`.map` is a bit unusual. I wish I could find more authoritative sources, but here are two relevant StackOverflow links:

* <https://stackoverflow.com/a/19912684>: "No DevTools actually care what the content-type is, so you can ignore it safely"
* <https://stackoverflow.com/q/18809567>: "It does not mention it in this Source Map Revision document that I can see." (And I also don't see anything relevant in that document myself)

The browser would use a hypothetical `Content-Type` in these ways:

* As a source map referenced by a script, the Content-Type is (currently) ignored. In the future, browsers *might* follow the precedent set with CSS and JS, and enforce that maps are served with some (to-be-determined!) Content-Type even when the intended use is specified in the HTML. If and when that happens, we should definitely do it.
* As a direct link, it can influence presentation by the browsers - in this case, the reasonable choices are `text/plain` (text), `application/json` (an interactive tree view), or `application/octet-stream` (a download prompt). In my opinion this situation isn't frequent or important enough to warrant adding a media type, *especially* if it's not standardized.

Finally, note that [Source Map Revision 3 Proposal](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit?hl=en_US&pli=1&pli=1#) suggests deliberately making the source map invalid JSON - it seems to me that would make `application/json` a *worse* choice than `text/plain` or `application/octet-stream` if browsers don't take that special case into account.

**Comment by SergioBenitez** [comment]
Closing based on the above comment.
