### ISSUE TITLE
../../README.md file not found (rocket_codegen)

### ISSUE THREAD

**Issue by Tevinthuku** [SergioBenitez/Rocket#1337]
## Bug Reports

Bug reports _must_ include:

 Rocket Version "0.4.5"

  2. The operating system (distribution and version) where the issue occurs.
 MacOS Catalina

  3. A brief description of the bug that includes:
   Deploying a barebones app built with rocket to Heroku gives me this error
```
remote: Rust is installed now. Great!
remote: 
remote: To get started you need Cargo's bin directory (/app/tmp/cache/cargo/bin) in 
remote: your PATH
remote: environment variable. Next time you log in this will be done
remote: automatically.
remote: 
remote: To configure your current shell run source /app/tmp/cache/cargo/env
remote: -----> Building application using Cargo
remote:     Updating crates.io index
remote:  Downloading crates ...
remote:   Downloaded rocket_codegen v0.4.5
remote: error: failed to parse manifest at `/app/tmp/cache/cargo/registry/src/github.com-1ecc6299db9ec823/rocket_codegen-0.4.5/Cargo.toml`
remote: 
remote: Caused by:
remote:   readme file with name '../../README.md' was not found
remote:  !     Push rejected, failed to compile Rust app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to tevs-transformer-api.
remote: 
To https://git.heroku.com/tevs-transformer-api.git
 ! [remote rejected] master -> master (pre-receive hook declined)
```

  4. How you uncovered the bug. Short, reproducible tests are especially useful.
   I ran `git push heroku master` 
Here's my repo (https://github.com/tevs-rust-land/transformer-api)

  5. Ideas, if any, about what Rocket is doing incorrectly.
I'm not so sure, I'm kinda new to Rust. 

## General Comments

If there's anything I have not included or that I'm doing wrong, kindly let me know

**Comment by julien1619** [comment]
I have the same problem since today with my Github Actions linked to my repository.
https://github.com/Creatiwity/siren/actions/runs/133337882

**Comment by jebrosen** [comment]
@julien1619 Thanks for that link.

https://github.com/rust-lang/rust/pull/73266 has been merged including the fix, so tonight's nightly should fix the issue.

**Comment by Tevinthuku** [comment]
I've tried re-deploying again and it works as expected. I'll be closing this since I have no further issues on the same. Thanks 👍
