### ISSUE TITLE
Unable to compile hello_world example

### ISSUE THREAD

**Issue by captain-yossarian** [SergioBenitez/Rocket#1338]
Hi, I'm unable to compile [hello_workd1](https://github.com/SergioBenitez/Rocket/tree/master/examples/hello_2015) and [hello_world2](https://github.com/SergioBenitez/Rocket/tree/master/examples/hello_2018) examples.

Rust version: `rustc 1.46.0-nightly (feb3536eb 2020-06-09)`
I'm using nightly version: nightly-x86_64-pc-windows-msvc unchanged - rustc 1.46.0-nightly (feb3536eb 2020-06-09)
Rocket version: `0.4.5`
OS: Windows 10

My code:
```rust
#![feature(proc_macro_hygiene)]

use rocket::{get, routes};

#[rocket::get("/")]
fn hello() -> &'static str {
    "Hello, Rust 2018!"
}

fn main() {
    rocket::ignite().mount("/", routes![hello]).launch();
}
```
*OR*
```rust
#![feature(proc_macro_hygiene)]

use rocket::{get, routes};

#[get("/")]
fn hello() -> &'static str {
    "Hello, Rust 2018!"
}

fn main() {
    rocket::ignite().mount("/", routes![hello]).launch();
}
```
*OR*
```rust
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use] extern crate rocket;

#[get("/")]
fn index() -> &'static str {
    "Hello, world!"
}

fn main() {
    rocket::ignite().mount("/", routes![index]).launch();
}
```

Every time I'm receiving:
```
error[E0658]: `macro` is experimental
 --> src\main.rs:5:1
  |
5 | #[get("/")]
  | ^^^^^^^^^^^
  |
  = note: see issue #39412 <https://github.com/rust-lang/rust/issues/39412> for more information
  = help: add `#![feature(decl_macro)]` to the crate attributes to enable
  = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by Darkkaiserl** [comment]
i try this:

#![feature(proc_macro_hygiene, decl_macro)]
#[macro_use] extern crate rocket;

#[get("/")]
fn index() -> &'static str {
    "Hello, world!"
}

fn main() {
    rocket::ignite().mount("/", routes![index]).launch();
}

and it's works for me...

cargo.toml

[dependencies.rocket]
version = "0.4.5"
default-features = false

**Comment by captain-yossarian** [comment]
@Darkkaiserl thanks a lot. It works now. I think [quick start guide](https://rocket.rs/v0.4/guide/getting-started/) needs to be updated

**Comment by SergioBenitez** [comment]
@captain-yossarian I don't follow. That's the exact source code as it appears in the guide. The guide is also tested by the CI to ensure that it compiles. Are you sure you used the code as it appears in the guide?

**Comment by captain-yossarian** [comment]
@SergioBenitez Code itself is Ok, but it began to work after I added `default-features = false` to Cargo.toml.
I'm sorry, but I cant find it in [quick start](https://rocket.rs/v0.4/guide/getting-started/) example

**Comment by SergioBenitez** [comment]
@captain-yossarian You shouldn't need `default-features = false`. The CI tests with all features and combinations of features, all of which are working. Since there are no other reports of this issue, I'm closing this out.
