### ISSUE TITLE
Update rusqlite

### ISSUE THREAD

**Issue by JMS55** [SergioBenitez/Rocket#1341]
I am using rocket_contrib with the sqlite_pool feature. The current version of rusqlite is 0.23, but rocket uses 0.14. As you can see, there have been many changes since 0.14 https://github.com/rusqlite/rusqlite/releases.

**Comment by jebrosen** [comment]
See also https://github.com/SergioBenitez/Rocket/issues/888#issuecomment-454616267.

This will definitely be upgraded for 0.5, and I have some ideas for making it easier to support multiple versions of some crates such as `rusqlite` in the future.
