### ISSUE TITLE
Interaction with log facade

### ISSUE THREAD

**Issue by RalfJung** [SergioBenitez/Rocket#1344]
This is with Rocket 0.4.5. I am seeing some strange interactions with the log facade.

Usually, when I launch rocket, it prints some pretty informative text like this:
```
🔧 Configured for development.
    => address: localhost
    => port: 8000
    => log: normal
    => workers: 16
    => secret key: generated
    => limits: forms = 32KiB
    => keep-alive: 5s
    => tls: disabled
    => [extra] databases: ...
    => [extra] ff-node-monitor: ...
🛰  Mounting /static:
    => GET /static [10]
    => GET /static/<path..> [10]
🛰  Mounting /:
    => GET / (index)
    => GET /list?<email> (list)
    => GET /list (list_formfail)
    => POST /prepare_action (prepare_action)
    => GET /run_action?<signed_action> (run_action)
    => GET /cron (cron)
📡 Fairings:
    => 1 request: Templates
```

However, ever since I added `env_logger::init()` or `pretty_env_logger::init()` to my main function, instead it prints just nothing. When I set `RUST_LOG=info`, it prints
```
 INFO  launch          > 🔧 Configured for development.
 INFO  launch_         > address: localhost
 INFO  launch_         > port: 8000
 INFO  launch_         > log: normal
 INFO  launch_         > workers: 16
 INFO  launch_         > secret key: generated
 INFO  launch_         > limits: forms = 32KiB
 INFO  launch_         > keep-alive: 5s
 INFO  launch_         > tls: disabled
 INFO  launch_         > [extra] databases: ...
 INFO  launch_         > [extra] ff-node-monitor: ...
 INFO  rocket::rocket  > 🛰  Mounting /static:
 INFO  _               > GET /static [10]
 INFO  _               > GET /static/<path..> [10]
 INFO  rocket::rocket  > 🛰  Mounting /:
 INFO  _               > GET / (index)
 INFO  _               > GET /list?<email> (list)
 INFO  _               > GET /list (list_formfail)
 INFO  _               > POST /prepare_action (prepare_action)
 INFO  _               > GET /run_action?<signed_action> (run_action)
 INFO  _               > GET /cron (cron)
 INFO  rocket::fairing::fairings > 📡 Fairings:
 INFO  _                         > 1 request: Templates
 INFO  launch                    > 🚀 Rocket has launched from http://localhost:8000
```

it seems like somehow Rocket detects that the log facade is initialized and then changes its logging style to be less pretty, or so? I am not sure what is going on. I searched the Rocket guide but found no mention of this.

Is there a way to get the old, prettier log back, but still also enable other parts of the application to use the log facade?

**Comment by jebrosen** [comment]
> it seems like somehow Rocket detects that the log facade is initialized and then changes its logging style to be less pretty, or so? I am not sure what is going on. I searched the Rocket guide but found no mention of this.

Not quite, and indeed it is not currently documented. If `ROCKET_LOG` is not set to `off`, rocket registers itself as the global logger. The logger [can only be set once](https://docs.rs/log/0.4.8/log/fn.set_logger.html#errors), so initializing `env_logger` prevents Rocket from installing its logger.

The other side of that is the broken formatting. This is because rocket's logger treats `launch` and `_` specially, for indentation and to show launch information regardless of the log level.

> Is there a way to get the old, prettier log back, but still also enable other parts of the application to use the log facade?

Simply removing `env_logger::init` should do that - anything logged using `log`'s macros will be logged by rocket's logger. Of course, this has the downside of not being able to use the per-module filtering provided by those crates.

---

All that being said, there are numerous downsides to the current approach and we do want to do things differently here - see also #21.

**Comment by RalfJung** [comment]
> Simply removing env_logger::init should do that - anything logged using log's macros will be logged by rocket's logger. Of course, this has the downside of not being able to use the per-module filtering provided by those crates.

Ah, that explains a bunch of things, like why a user reported seeing a `warn!` even though I didn't initialize any logger. ;)
What is the filtering behavior of Rocket's logger? Which levels does it print?

**Comment by jebrosen** [comment]
> What is the filtering behavior of Rocket's logger? Which levels does it print?

The log levels are controlled by `Rocket.toml` (the `log` key) or by the `ROCKET_LOG` environment variable. The recognized values are different from the `log` crate's names: Rocket's `critical`, `normal`, and `debug` respectively correspond to `log`'s `WARN`, `INFO`, and `TRACE`.

Additionally, a log message with a target that ends with `_` will be printed indented with `=>` in front. This is currently an implementation detail, but it's something we want to make available to application code in a documented and supported, form.

There are some other special cases; the [entire logger implementation](https://github.com/SergioBenitez/Rocket/blob/83925bbae100592cc6bb4360716d2cfc2a7b2c3e/core/lib/src/logger.rs) is only around 250 LOC in case you are curious.

**Comment by SergioBenitez** [comment]
Looks like this has been answered without further activity!
