### ISSUE TITLE
How Exactly do i create an Multi-threaded Async web server

### ISSUE THREAD

**Issue by EliteDaMyth** [SergioBenitez/Rocket#1348]
I am new to Rust in a whole as a language. I read "The Book" and it contains a guide on how to create a multi threaded web server. I was wondering how could i do the same in rocket.

**Comment by jebrosen** [comment]
Most of that chapter covers topics including parsing HTTP (which is done by Rocket) and low-level connection management (which is done by one of Rocket's dependencies `hyper`). Rocket is a web *framework*, which means that it provides building blocks for creating a web server without needing to worry much about those details.

Rocket 0.4 is multithreaded (one thread per incoming connection), and rocket 0.5 will be async (any number of incoming connections N spread out across M threads) - but for the most part, you do not need to worry about that when using Rocket! The [`pastebin` example](https://github.com/SergioBenitez/Rocket/blob/v0.4/examples/pastebin/src/main.rs) in this repository is a good place to look to see how much Rocket does for you and how much you encode into the application itself.

**Comment by EliteDaMyth** [comment]
thank you very much :)
