### ISSUE TITLE
How to proxy request to another host and pass response back to original caller

### ISSUE THREAD

**Issue by zwhitchcox** [SergioBenitez/Rocket#1350]
version: 0.4.5

steps taken: looked at docs, google, source code, issues, etc.

Hi, I was wondering if there was any middleware for a proxy server or what would be the best way to go about creating a proxy server so I can forward requests to my `create-react-app` server instance.

If you are unfamiliar, during development, the `create-react-app` server listens on port `3000` and supplies the front end for development.

In the past I have used [express-http-proxy](https://www.npmjs.com/package/express-http-proxy) for my typescript code to forward development traffic to that port.

I know what I'm asking is super basic and is probably fairly easy to create, but I guess I was wondering if there was already a prepared solution or recommended approach to save myself and possibly others some time. And if not, we could create something that benefits the community as a whole.

Is there a project in place already? What would be a good place to start? I have not seen a place to create middleware or a list of middlewares that already exist, is there one yet?

**Comment by zwhitchcox** [comment]
Ok, so it looks like this is impossible until #1065 is implemented?

**Comment by zwhitchcox** [comment]
Closing as people don't really seem to answer questions here

**Comment by jebrosen** [comment]
> Hi, I was wondering if there was any middleware for a proxy server or what would be the best way to go about creating a proxy server so I can forward requests to my `create-react-app` server instance.

I'm not aware of any middleware (in Rocket terms, it would probably be either a `Fairing` or `Responder`) that is made for proxying requests. Depending on how much of the `create-react-app` devserver's functionality you are using, proxying requests may end up being more complex to get working than replacing the devserver entirely with [`StaticFiles`](https://api.rocket.rs/v0.4/rocket_contrib/serve/struct.StaticFiles.html) + a tool such as [watchexec](https://crates.io/crates/watchexec) to rebuild the js when files have changed. Alternatively, a program with dedicated proxy support such as `nginx` can make two backend servers appear as a single one. That said, assuming you do want to proxy from inside of Rocket:

> Ok, so it looks like this is impossible until #1065 is implemented?

That shouldn't be a requirement; the main limitation of 0.4 that might apply is "one in-flight request per worker thread", but this should not be a problem for static file serving in particular.

> I know what I'm asking is super basic and is probably fairly easy to create, but I guess I was wondering if there was already a prepared solution or recommended approach to save myself and possibly others some time. And if not, we could create something that benefits the community as a whole.

An HTTP proxy is unfortunately less basic than it seems. The biggest issues are with headers - some of which [need to be forwarded](https://www.ietf.org/rfc/rfc2068.html#section-13.5.1), and some of which don't - and with the forwarding of different transfer encodings of bodies. For the specific case of a static file server like `create-react-app`'s, you should be able to avoid most of the "hard" problems though.

> Is there a project in place already? What would be a good place to start? I have not seen a place to create middleware or a list of middlewares that already exist, is there one yet?

[`rocket_contrib`](https://api.rocket.rs/v0.4/rocket_contrib/index.html) is a set of addons for `rocket` that are officially-sanctioned, i.e. they are maintained and updated in sync with `rocket` itself. We don't currently maintain a list of other middleware or utilities that work with `rocket`, but many of them have been published to [crates.io](https://crates.io/).

As for "a good place to start": I would start by getting something working in a route directly, and when I was comfortable with the implementation I would adapt it to either a [Fairing](https://rocket.rs/v0.4/guide/fairings/) or a [custom Responder](https://api.rocket.rs/v0.4/rocket/response/trait.Responder.html). For the case of proxying, a `Responder` seems somewhat more appropriate.

**Comment by zwhitchcox** [comment]
@jebrosen Hey, thanks for your detailed response, I know my question was long, so I appreciate that! That gives me more confidence in using rocket.rs moving forward, because I was afraid there wouldn't be enough community support if I get stuck, and this is my first project with Rust as well.

But I actually found that you can use `create-react-app`'s [proxy](https://create-react-app.dev/docs/proxying-api-requests-in-development/) functionality and just forward requests from the `create-react-app` instance, which is much easier than trying to create the proxy in rust. So for anyone else stumbling upon this in the future, that is what I would recommend, and then just adding a static file server when you are ready to deploy to production.

Thanks for all you do, rocket.rs team!

**Comment by jebrosen** [comment]
> But I actually found that you can use `create-react-app`'s proxy functionality and just forward requests from the `create-react-app` instance

That is probably the best solution; it's similar to my `nginx` suggestion above but much more convenient. In hindsight, I knew enough to check for that first! I frequently use a similar feature in Angular's `ng serve`.

**Comment by zwhitchcox** [comment]
>In hindsight, I knew enough to check for that first!

I definitely did too...although, the last time I used React, this was not an option....thankfully there is a really good example of an integration here: https://github.com/ghotiphud/rust-web-starter

**Comment by jebrosen** [comment]
> On a semi-related note, rocket also rejects the proxied requests,
> if you happen to know does rocket just reject all proxied requests by default?

That doesn't sound right. The first thing that comes to mind is that the request URI doesn't match. If you request `http://localhost:xyz/api/endpoint` to `create-react-app`, does it pass it through directly as `/api/endpoint` or does it rewrite it to `/endpoint`? Alternatively, if you have some of Rocket's log output from one of these rejected requests that may help troubleshoot.

> I just started using warp, because of this and also lack of support for `async/await`

Sorry to hear that. The `async` branch (#1065) is nearly ready to merge into master and there is a bit more work after that to release Rocket 0.5. When that happens, I hope you're interested in giving Rocket another try!
