### ISSUE TITLE
Inconsistency in the guide regarding paths in chapter requests: multiple-segments 

### ISSUE THREAD

**Issue by arctic-alpaca** [SergioBenitez/Rocket#1351]
Hello,

there is an small inconsistency in the guide regarding the use of relative and absolute paths when serving files.
In the [multiple-segments](https://rocket.rs/v0.4/guide/requests/#multiple-segments) part, first serving files is shown like this:
`NamedFile::open(Path::new("static/").join(file)).ok()`, 
then like this:
`rocket.mount("/public", StaticFiles::from("/static"))`

I didn't understand "/static" is an absolute path and asked in the IRC. Sergio Benitez was kind enough to explain the situation to me. He also asked me to mention the following in this issue:
>  StaticFiles should check, on creation, that the directory it's to serve from actually exists. And if it doesn't, fail. This way, you don't have to wait until your application starts, to discover you got the path wrong.

Regarding the guide and [documentation](https://api.rocket.rs/v0.4/rocket_contrib/serve/struct.StaticFiles.html), mentioning "/static" is an absolute path might be helpful for new people coming from windows.

**Comment by SergioBenitez** [comment]
This is resolved in master: https://api.rocket.rs/master/rocket_contrib/serve/struct.StaticFiles.html#relative-paths.
