### ISSUE TITLE
.register(catchers![404]) in production mode.

### ISSUE THREAD

**Issue by Darkkaiserl** [SergioBenitez/Rocket#1354]
Nightly version: nightly-x86_64-pc-windows-msvc unchanged - rustc 1.45.0-nightly (a74d1862d 2020-05-14)
Rocket version: 0.4.5
OS: Windows 10

Hi, when use

``` rust
.register(catchers![found404])
```

in production mode, this response enter in a loop, and i need use "Ctrl + c" in console to send response(this console dont close with this.. only send response).

in dev mode, response instantly.

in other try, without
``` rust
.register(catchers![found404])
```
same result... stuck in a loop

![image](https://user-images.githubusercontent.com/30737924/85417246-d2123180-b545-11ea-817c-e8bedd3b93ce.png)

only when press "Ctrl + c" send 404.
![image](https://user-images.githubusercontent.com/30737924/85418317-063a2200-b547-11ea-9076-7697de1252cb.png)

with database connection its same, but have a timeout and send error in a certain seconds(but, there send 2 or 3 at the same time, not when catch the error):
![image](https://user-images.githubusercontent.com/30737924/85418737-8791b480-b547-11ea-874d-5aa7a4a4bccd.png)

**Comment by jebrosen** [comment]
What is the code in `found404`? This is a surprising problem, since only a small number of changes are supposed to happen between development and production mode.

**Comment by Darkkaiserl** [comment]
> What is the code in `found404`? This is a surprising problem, since only a small number of changes are supposed to happen between development and production mode.

`found404`:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>404</title>
  </head>
  <body>
    <h1>404: Hey! There's nothing here.</h1>
    The page at {{ path }} does not exist!
  </body>
</html>
```

I have a partial solution;
![image](https://user-images.githubusercontent.com/30737924/85903040-c8096080-b7db-11ea-9abf-34e85c0d40cf.png)
force one catch error... but in some times only works after close 1 connection with client. 

thanks for all you do

**Comment by jebrosen** [comment]
Sorry! I think I misunderstood your original question.

> in other try, without `.register(catchers![found404])` same result... stuck in a loop

So, `found404` is *not* part of the problem?

I am not sure what is going on here... it looks like the database is not connecting (sometimes), and also your responses "hang" sometimes? The only known issue I can think of with hanging connections is `keep-alive` (see also https://github.com/SergioBenitez/Rocket/issues/928#issuecomment-464632953) - but this does not look like that problem.

The database *sometimes* not connecting is a total mystery to me and should not be related to the hanging responses, but if they are consistently having problems at the same time there might be yet another problem contributing to both issues.

**Comment by Darkkaiserl** [comment]
So, question is ... why on error catch  (with or without .register ()) hang on response.

Database is out of question, it's only an example of hanging response(this work all fine).. 
in case of database, the response print only when catch 3 errors or more(maybe keep-alive, but is working good, not issues here)
[In dev mode, database does same, print err 3 by 3].
![image](https://user-images.githubusercontent.com/30737924/85920116-70084380-b847-11ea-9b9e-fb6ae01cbb2b.png)

`found404` it's irrelevant... in other case, catch 500 internal server error, have a same problema. (when catch error, there hang in and need force Ctrl+C).

422, 404, 500.. all stuck in a loop.

if closed the connection with the client one time Code: 10054 , this problem pass out(sometimes).

I so sorry for my bad english.

**Comment by jebrosen** [comment]
Are you sure the problem is *after* a response has been chosen? Database connection errors can "hold up" requests or request capacity until they finally time out (after 30 seconds by default). If you are really seeing a problem with responses themselves, you should be able to see the problem with only a "hello world" example and no database connection.

**Comment by Darkkaiserl** [comment]
You see the response time on top, 1.3 min(because i manually close that).
This dont have a time out... if i dont close with ctrl + c, don't have time out.

**This try is with database components(new cargo build, same cfg):**
![image](https://user-images.githubusercontent.com/30737924/85974219-51bb5880-b9ab-11ea-9b24-46877fca0a78.png)
`After Ctrl + c`  (8.6 mins).
![image](https://user-images.githubusercontent.com/30737924/85974305-87604180-b9ab-11ea-9917-672672a6652c.png)

when unstuck this, all errors send at same time(and never stuck again in this process).

**Now try without database components(new cargo build, same cfg, without code & dep mysql):**
![image](https://user-images.githubusercontent.com/30737924/85975258-f179e600-b9ad-11ea-83fe-d3c7497d6db5.png)
in this case without database, i try see a time out (going to edit this when get a timeout, or tired)

**Comment by Darkkaiserl** [comment]
In "hello world" example, with TLS(try without tls and same, stuck sometimes):
![image](https://user-images.githubusercontent.com/30737924/86031850-d4283480-ba0c-11ea-8903-bc1020cf8db1.png)

After hours try find this issue, i conclude this is CMD of Windows 10(in my computer), because set the project in other pc and all work good, don't stuck, it's fast. So.

**This is full main project with the supposed error:**
![image](https://user-images.githubusercontent.com/30737924/86037417-bc08e300-ba15-11ea-82ba-13b828d8d92d.png)

Windows 10 it's.... ^^

**Comment by jebrosen** [comment]
> After hours try find this issue, i conclude this is CMD of Windows 10(in my computer), because set the project in other pc and all work good, don't stuck, it's fast.

That is strange. If you do see it again on another machine, it may be helpful to find the exact problem to help future users.

> Question: with tls enable, how i redirect http to https?

You can't accomplish this with rocket's built-in tls support by itself, since rocket listens on only one port. Usually an http -> https redirect can be done with a web hosting platform, or with a reverse proxy such as nginx or apache.

**Comment by Darkkaiserl** [comment]
> That is strange. If you do see it again on another machine, it may be helpful to find the exact problem to help future users.

I try find why only "prod" mode stuck in my "PC".

I think have a conflict in my dev computer for all redistributable(composer, rust, git, node... i don't know). In a clear version of windows 10, all works fine.
