### ISSUE TITLE
Support for default values in Form/LenientForm parsing

### ISSUE THREAD

**Issue by sazzer** [SergioBenitez/Rocket#1355]
As best I can see this hasn't been raised before, and I can't find how to make this work, so apologies if this is already covered.

I'm implementing a struct to parse query parameters into. Easy enough, just derive `FromForm` and wrap it in `LenientForm<>` and all is good.

Except that I want to have the struct get populated with default values for any that are not present in the querystring. It seems that I can do this by having the fields be `Option<>` and then doing the defaulting myself, but I'd really like to be able to just tell the struct what the defaults are and be done with it.

Actual example:
```
/// Request details to describe the pagination of a request
#[derive(Debug, FromForm)]
pub struct PaginationRequest {
    /// The desired offset for the request
    pub offset: u32,
    /// The desired count for the request
    pub count: u32,
}

impl Default for PaginationRequest {
    fn default() -> Self {
        Self {
            offset: 0,
            count: 10,
        }
    }
}
```

It seems reasonable that, given the above, the `offset` and `count` query parameters can be defaulted to the values defined in the `impl Default` if they aren't present in the querystring. But this doesn't work, and I can't see any way to make this work.

Obviously I can do this myself, by having getters on the `Pagination` struct that do an `unwrap_or()` as appropriate. But that seems excessive.

Cheers

**Comment by sazzer** [comment]
I have for now done this manually using `FromQuery`, but it feels like it should be possible without this much extra code:

```
impl<'q> FromQuery<'q> for PaginationRequest {
    type Error = ();

    fn from_query(query: Query<'q>) -> Result<Self, Self::Error> {
        let mut result = Self::default();

        for item in query {
            if item.key == "offset" {
                if let Ok(value) = u32::from_str(item.value.as_str()) {
                    result.offset = value;
                }
            } else if item.key == "count" {
                if let Ok(value) = u32::from_str(item.value.as_str()) {
                    result.count = value;
                }
            }
        }

        Ok(result)
    }
}
```

**Comment by jebrosen** [comment]
This might be a duplicate of #1173 - can you confirm that or elaborate on why it isn't / what needs to be added?

Currently, the default values for fields come from the `FromFormValue` trait. For most types the "if missing" value is "treat as invalid input".

**Comment by sazzer** [comment]
I must have completely missed that one. They do look like the exact same problem.

I'll close this as a duplicate then :)

Cheers
