### ISSUE TITLE
Allow FromFormValue to return an error

### ISSUE THREAD

**Issue by sazzer** [SergioBenitez/Rocket#1357]
As best I can tell, implementations of `FromFormValue` are not able to fail the request.

If they return `Ok(...)` then it passes and this is fine.
If they return `Err(...)` then it fails and is considered to be `Outcome::Forward` instead of `Outcome::Failure`. This means that either another handler for the same URL path is needed or else an HTTP 404 will be returned, whereas an HTTP 400 or 422 is actually a better reaction in this case.

We *can* have the handler parameter be a `Result<T, T::Error>` instead of just a `T`, and then handle this in the handler. But this then means we need to handle it in *every* handler instead of being central. This also doesn't seem to respect the `default()` handler, and thus I actually need to have a parameter of `Option<Result<T>, T::Error>` and handle both the defaulting and the error in every handler.

**Comment by jebrosen** [comment]
> If they return Err(...) then it fails and is considered to be Outcome::Forward instead of Outcome::Failure.

It looks like a Failure is being returned here: <https://api.rocket.rs/v0.4/src/rocket/request/form/form.rs.html#168>, with status code 422 (Unprocessable Entity). Where is the `Forward` coming from?

>  This also doesn't seem to respect the `default()` handler, and thus I actually need to have a parameter of `Option<Result<T>, T::Error>` and handle both the defaulting and the error in every handler.

I *think* I understand this point, but could you post some sample code for this case so we're definitely talking about the same thing?

**Comment by sazzer** [comment]
I've assumed that it was a Forward based on the observed output.

I've got a custom type `SortFieldsRequest<T>`, and it implements `FromFormField`. This then returns either `Ok(SortFieldsRequest(...))` or `Err(input)`.

When I have a parameter of type `SortFieldsRequest<T>` on my handler then this works great, but only if the above returned `Ok()`. If it returns `Err()` then the result is an HTTP 404 sent to the client, and my log messages show:
```
Jun 27 15:28:00.112  INFO rocket::rocket: GET /worlds?sort=n:
Jun 27 15:28:00.113  INFO _: Matched: GET /worlds?<owner>&<sort>&<pagination..> (search_worlds)
Jun 27 15:28:00.115 DEBUG multiverse_lib::model::sorts: Parse sort field input="n" result=Err(UnknownField("n"))
Jun 27 15:28:00.115 DEBUG multiverse_lib::model::sorts: Parse sort fields input="n" result=Err(UnknownField("n"))
Jun 27 15:28:00.115  WARN multiverse_lib::http::sorts: Failed to parse sorts e=UnknownField("n") value=RawStr("n")
Jun 27 15:28:00.115  WARN _: Failed to parse 'sort': RawStr("n")
Jun 27 15:28:00.115  INFO _: Outcome: Forward
Jun 27 15:28:00.115 ERROR _: No matching routes for GET /worlds?sort=n.
Jun 27 15:28:00.115  WARN _: Responding with 404 Not Found catcher.
Jun 27 15:28:00.117  INFO _: Response succeeded.
```

When I have a parameter of type `Result<SortFieldsRequest<T>, SortFieldsRequest<T>::Error>` then I can correctly handle if the parsing failed. But I can't handle if the parameter wasn't present at all. That's fair - if the type was `SortFieldsRequest<T>` then it's mandatory in the same way.

In order to handle all of:
* The parameter being present and valid
* The parameter being present and invalid
* The parameter being absent

Then I need to have a parameter of type `Option<Result<SortFieldsRequest<T>, SortFieldsRequest<T>::Error>>`. That then gives the following results for the above:
* The parameter being present and valid - `Some(Ok(...))`
* The parameter being present and invalid - `Some(Err(...))`
* The parameter being absent - `None`

But obviously that's actually quite awkward to work with in my handler.

**Comment by jebrosen** [comment]
> `/worlds?<owner>&<sort>&<pagination..>`

Okay, this is what I was missing. I was assuming you were using it in `FromForm`, but you are using it in a query parameter. Query parameters do indeed [always Forward](https://api.rocket.rs/v0.4/rocket/attr.route.html#semantics) on errors. This matches the behavior for path parameters, where e.g. `/person/<id>` with `id: i32` will forward, possibly to another route `/person/<name>` with `name: String`.

In your case, you don't want the forwarding. One alternative that comes to mind is to put the entire query into one structure that implements/derives `FromForm`, so you can wrap a single `Result` around the whole form instead of one for each field. You should also be able to eliminate the `Option` if you have a sensible default:

> This also doesn't seem to respect the `default()` handler

It should!

```rust
struct Val(i32);
impl<'v> rocket::request::FromFormValue<'v> for Val {
    type Error = ();
    fn from_form_value(form_value: &'v rocket::http::RawStr) -> Result<Self, Self::Error> {
        Ok(Val(1))
    }
    fn default() -> Option<Self> {
        Some(Val(2))
    }
}

#[get("/?<val>")]
fn hello(val: Val) -> String {
    val.0.to_string()
}

fn main() {
    rocket::ignite().mount("/", routes![hello]).launch();
}
```

This endpoint returns `1` if a `val` was specified, and `2` if it was left out.

**Comment by sazzer** [comment]
I'll try wrapping it all in a struct, see how that works out. Cheers for the pointer :)

Regarding the defaulting, I might have not been clear enough. It works great if you're using the type as-is in the parameter. It doesn't if you're using it as a `Result<>`.

```
#![feature(proc_macro_hygiene, decl_macro)]

use rocket::*;

#[derive(Debug)]
struct Val(usize);

impl<'v> rocket::request::FromFormValue<'v> for Val {
    type Error = &'v rocket::http::RawStr;
    fn from_form_value(form_value: &'v rocket::http::RawStr) -> Result<Self, Self::Error> {
        form_value.percent_decode()
            .map_err(|_| form_value)
            .and_then(|v| v.parse().map_err(|_| form_value))
            .map(|v| Val(v))
    }
    fn default() -> Option<Self> {
        Some(Val(0))
    }
}

#[get("/simple?<val>")]
fn simple(val: Val) -> String {
    format!("{:?}", val)
}

#[get("/option?<val>")]
fn option(val: Option<Val>) -> String {
    format!("{:?}", val)
}

#[get("/result?<val>")]
fn result(val: Result<Val, &rocket::http::RawStr>) -> String {
    format!("{:?}", val)
}

#[get("/both?<val>")]
fn both(val: Option<Result<Val, &rocket::http::RawStr>>) -> String {
    format!("{:?}", val)
}

fn main() {
    rocket::ignite().mount("/", routes![simple, option, result, both]).launch();
}
```

In this case:
* /simple -> sees `Val(0)`
* /simple?val=1 -> sees `Val(1)`
* /simple?val=a -> Forward
* /option -> sees `None`
* /option?val=1 -> sees `Some(Val(1))`
* /option?val=a -> sees `None`
* /result -> Forward
* /result?val=1 -> sees `Ok(Val(1))`
* /result?val=a -> sees `Err("a")`
* /both -> sees `None`
* /both?val=1 -> sees `Some(Ok(Val(1)))`
* /both?val=a -> sees `Some(Err("a"))`

**Comment by jebrosen** [comment]
Okay, thanks for the example!

This *seems* easy to fix, although it also seems like a bit of a breaking change: `FromFormValue for Result<T, T::Error>` should respect `T::default()` instead of using the automatic implementation that says "field is required". I'm tagging this is `enhancement` + `request` accordingly.

**Comment by SergioBenitez** [comment]
> So that using a type of `Result<Val, Val::Error>` would allow defaulting if the parameter isn't present but also allow errors if the parameter was present but malformed.

This is how `Result<T, form::Errors<'v>>` works after the form revamp! What's more, you can also do `Result<Strict<T>, form::Errors<'v>>` to get an error even when the parameter isn't present. As a result, it looks like this has been handled.
