### ISSUE TITLE
BUG rocket 0.4.5 compilation fails

### ISSUE THREAD

**Issue by benjaminweb** [SergioBenitez/Rocket#1358]
1. Version: rocket 0.4.5, rustc 1.46.0-nightly (67100f61e 2020-06-24)

  2. Archlinux 5.5.9-arch1-2

  3. A brief description of the bug that includes:
      * `cargo build
   Compiling rocket_http v0.4.5
error: proc macro panicked
   --> /srv/http/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket_http-0.4.5/src/parse/uri/parser.rs:119:34
    |
119 |             let path_and_query = pear_try!(path_and_query(is_pchar));`
     * When the bug occurs: **compiling the package.**
     * What you expected: **successful compilation** vs. what actually happened: **compilation fails.**

  4. How you uncovered the bug. Short, reproducible tests are especially useful. **compiling the package**

  5. Ideas, if any, about what Rocket is doing incorrectly. **None.**

**Comment by benjaminweb** [comment]
Solved via https://github.com/rust-lang/rust/pull/73293

**Comment by SergioBenitez** [comment]
For posterity: as noted in [the guide](https://rocket.rs/v0.4/guide/getting-started/#installing-rust), a `cargo update` resolves the issue.
