### ISSUE TITLE
Cargo Run on a Default Install Using The HelloWorld Project Fails

### ISSUE THREAD

**Issue by AlexCreamer** [SergioBenitez/Rocket#136]

**Comment by SergioBenitez** [comment]
Rocket requires Rust nightly. This is mentioned throughout the documentation, including in the README, the guide, and the rustdocs.

See the [Getting Started](https://rocket.rs/guide/getting-started/) for a walk through.

**Comment by AlexCreamer** [comment]
Ok, can you delete this issue then?
