### ISSUE TITLE
Route documentation could cover which way ranks work

### ISSUE THREAD

**Issue by tbelaire** [SergioBenitez/Rocket#1360]
Looking at https://api.rocket.rs/v0.4/rocket/struct.Route.html

The table lays out the rank for each possible combination, but it doesn't mention if lowest ranked routes are picked first or highest ranked.  Just one extra sentence of clarification would be nice.  

Thanks a lot, this project has been really well documented overall and this is just the tiniest of nit picks.

**Comment by jebrosen** [comment]
This is explained in the guide: <https://rocket.rs/v0.4/guide/requests/#default-ranking>

Similar text ("higher/lower precedence") should be added to the API documentation.
