### ISSUE TITLE
Support providing TLS certificates from binary data, not files

### ISSUE THREAD

**Issue by ashaduri** [SergioBenitez/Rocket#1367]
I'm setting up TLS on Rocket, but in our application the certificates (at least the private key) should be embedded in the application binary, not provided as files. This is crucial for our security.

I see that Rocket's tls() method only accepts paths, nothing else.
I also cannot find any support for private key passwords, which would mitigate this problem somewhat (I would be able to embed the password in the binary and leave the key as a separate file).

Please provide support for reading the TLS data from variables (in addition to files).

I'm using Rocket 0.4.5.

**Comment by igalic** [comment]
> but in our application the certificates (at least the private key) should be embedded in the application binary, not provided as files. This is crucial for our security.

what is the threat model here?
or put differently, and more concretely for this specific case: how are you protecting the application memory?

**Comment by ashaduri** [comment]
> what is the threat model here?
> or put differently, and more concretely for this specific case: how are you protecting the application memory?

I'm aware that the application memory cannot be protected. It's the difference between an ordinary user stealing and forging certificates by simply overwriting them, and an experienced engineer disassembling and modifying a (possibly signed) executable. Sort of like game binaries providing their private license keys as files, as opposed to embedding them into binaries. Nobody expects them to do former, but everybody knows they can be cracked in theory.

**Comment by SergioBenitez** [comment]
I agree. Let's make sure we resolve this in #852.
