### ISSUE TITLE
rocket_http does not compile with latest nightly

### ISSUE THREAD

**Issue by Svedrin** [SergioBenitez/Rocket#1369]
A [tool of mine](https://github.com/Svedrin/galry) that compiled just fine a few weeks ago does not compile with the latest nightly anymore, because `rocket_http` fails to build:

```
   Compiling rocket_http v0.4.5
error: proc macro panicked
   --> /home/mz1030/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket_http-0.4.5/src/parse/uri/parser.rs:119:34
    |
119 |             let path_and_query = pear_try!(path_and_query(is_pchar));
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: message: called `Option::unwrap()` on a `None` value
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

error: could not compile `rocket_http`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

It fails both on my local dev system and in CI using a clean Docker container based on Alpine Linux. I originally saw the error with Rocket 0.4.4, but it still occurs with 0.4.5. Three months ago it built just fine.

I'm not sure if it's an error in Rocket or if I'm doing something wrong in my code, please feel free to point out if it's me :stuck_out_tongue: 

Thanks.

**Comment by igalic** [comment]
did you try `cargo update`, as described here https://github.com/SergioBenitez/Rocket/issues/1358 ?

**Comment by SergioBenitez** [comment]
Please see the myriad issues pointing to the same problem resolvable with `cargo update`.

**Comment by Svedrin** [comment]
yep, this worked, thanks :)

**Comment by CockyCat** [comment]
I have run cargo update, but still "could not compile `rocket_http`"
