### ISSUE TITLE
Incorrect ROCKET_ENV example in overview

### ISSUE THREAD

**Issue by Phrohdoh** [SergioBenitez/Rocket#137]
> For example, to launch the `Hello, world!` application in the `production` environment, we can run:
```
ROCKET_ENV=stage cargo run
```

This should be:
```
ROCKET_ENV=prod cargo run
```

Or should mention the `stage` environment not `production`.

**Comment by SergioBenitez** [comment]
Thanks! I've pushed a fix. :D

**Comment by Phrohdoh** [comment]
Why isn't that site open-source (with its own repo)?
