### ISSUE TITLE
rocket_contrib::uuid::Uuid missing serde Serialize/Deserialize?

### ISSUE THREAD

**Issue by Ran4** [SergioBenitez/Rocket#1370]
Feature request: adding `serde::{Serialize, Deserialize}` impls for `rocket_contrib::uuid::Uuid`

## Feature Requests

Feature requests _must_ include:

  1. Why you believe this feature is necessary.

It's probably expected functionality and can be very useful.

  2. A convincing use-case for this feature.

Serializing UUIDs to return it as a json document, for example

  3. Why this feature can't or shouldn't exist outside of Rocket.

Implementing it yourself isn't super hard, but it would be nice if it was available (perhaps as a feature?) in `rocket_contrib`

**Comment by jebrosen** [comment]
I have tried to think up a good example where having `Serialize/Deserialize` would be much better than calling `rocket_uuid.into_inner()`, but couldn't come up with one - what is the motivation for having this?

One reason I have against this feature is that `serde` (moreso `serde_derive`) can be fairly expensive to projects that don't already use it, and making yet another feature to split the "`serde`ness" of `Uuid` sounds needlessly confusing - my preference would be for crates can enable the `uuid/serde` feature if they need the functionality.

I'd be more than happy to have my mind changed on this, though!

**Comment by Ran4** [comment]
>calling rocket_uuid.into_inner()

While that's fine if you *just* want to serialize an uuid, the issue comes when you have a struct containing an `rocket_contrib::uuid::Uuid` and you want to return it.

For example, let's say you have some struct

```rust
#[derive(Serialize)
struct Person {
    id: rocket_contrib::uuid::Uuid,
    age: u32,
}

and you want to send it back

```rust
#[get["persons/<id>"]
fn get_person() -> Json<Person> {
    Json(Person {
        id: rocket_contrib::uuid::Uuid(...),
        age: 97,
    })
}
```

then you'd have to explicitly annotate how to serialize the id field, or have another struct that converts the Person into a Person with an uuid that uses uuid::Uuid (which *does* implement Serialize). Neither of which is very nice for productivity.

**Comment by SergioBenitez** [comment]
I'm happy to accept this in a PR, now that `serde` is a core dependency of Rocket.
