### ISSUE TITLE
hot upgrade & hot restart

### ISSUE THREAD

**Issue by hongliang5316** [SergioBenitez/Rocket#1371]
Is there an example to demonstrate http `hot upgrade` and `hot restart` like https://github.com/facebookarchive/grace In production environment ?

**Comment by jebrosen** [comment]
Rocket doesn't currently support hot restarting, and I think this is the first time it's been requested.

Roughly speaking, it looks like `grace` accomplishes this by having server1 (old) stop listening for new connections, and start server2 (new) with the FDs it was listening on passed in.

Some of the APIs necessary for this are probably the same as #1228 - it *might* even be possible to implement this entirely "around"/outside of `rocket` itself with those APIs. The overlap time where both servers are sharing the same listener seems like one of the biggest issues, along with doing this in a cross-platform way.

**Comment by luisvonmuller** [comment]
You can implement it by cargo watch,  but I do not think this is a rust enviroment desired enviroment, since you could have a lot of changes done and a big code (as we have on our company implementations) live reloading could cause server related issues.

**Comment by aisq2008** [comment]
i hope this feature will be implement with rocket, then developing rocket web code can be more happier.

**Comment by SergioBenitez** [comment]
Closing in favor of #1070, a proper implementation of which would allow implementing this outside of Rocket.
