### ISSUE TITLE
Build fails on nightly rustc 1.46.0-nightly (346aec9b0 2020-07-11)

### ISSUE THREAD

**Issue by snakehand** [SergioBenitez/Rocket#1377]
Cargo.toml:
[dependencies]
rocket = "0.4.5"
rocket_contrib = { version = "0.4.5", features = ["json"] }

Build output:

   Compiling rocket_http v0.4.5
error: proc macro panicked
   --> /home/frank/.cargo/registry/src/github.com-1ecc6299db9ec823/pear-0.1.2/src/macros.rs:71:9
    |
69  | / macro_rules! pear_try {
70  | |     ([$name:ident; $input:ident] $e:expr) => {{
71  | |         switch! { [$name;$input] result@$e => { Some(result) }, _ => { None } }
    | |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
72  | |     }};
...   |
78  | |     }}
79  | | }
    | |_- in this expansion of `pear_try!`
    | 
   ::: /home/frank/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket_http-0.4.5/src/parse/uri/parser.rs:119:34
    |
119 |               let path_and_query = pear_try!(path_and_query(is_pchar));
    |                                    ----------------------------------- in this macro invocation
    |
    = help: message: called `Option::unwrap()` on a `None` value

error: aborting due to previous error

error: could not compile `rocket_http`.

**Comment by finnkauski** [comment]
```
   Compiling rocket_http v0.4.5
error: proc macro panicked
   --> /home/finn/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket_http-0.4.5/src/parse/uri/parser.rs:119:34
    |
119 |             let path_and_query = pear_try!(path_and_query(is_pchar));
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: message: called `Option::unwrap()` on a `None` value
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

error: could not compile `rocket_http`.

To learn more, run the command again with --verbose
```

Fails to compile for me as well.

**Comment by jebrosen** [comment]
See #1358 - this should be fixed by a `cargo update`.
