### ISSUE TITLE
rocket::custom example code may be incomplete or broken

### ISSUE THREAD

**Issue by intrepion** [SergioBenitez/Rocket#139]
I am not very good at rust yet, but I wanted to make a heroku project, but heroku dynamically assigns a port number, so I want to use rocket::custom to specify what port number to use.

I am currently using the following versions
Rocket 0.1.5
cargo 0.17.0-nightly (6c79cf9 2017-01-13)
rustc 1.16.0-nightly (ff591b6dc 2017-01-15)

When I try to use the example code at [https://api.rocket.rs/rocket/struct.Rocket.html#method.custom](https://api.rocket.rs/rocket/struct.Rocket.html#method.custom)

I get the following errors:

```rust
let config = Config::default_for(Environment::active()?, "/custom")?
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::ops::Carrier` is not implemented for `()`
                                 ^^^^^^^^^^^^^^^^^^^^^^ the trait `std::ops::Carrier` is not implemented for `()`
                                 the trait bound `(): std::ops::Carrier` is not satisfied
    .address("1.2.3.4".into())
    .port(9234);
```

Thanks for any assistance you can provide to get me past this roadblock.

**Comment by intrepion** [comment]
Hmm, this is my current workaround, but I don't know if it is the right way to do it.

```rust
let config = Config::default_for(Environment::active().unwrap(), "/custom").unwrap()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::ops::Carrier` is not implemented for `()`
                                 ^^^^^^^^^^^^^^^^^^^^^^ the trait `std::ops::Carrier` is not implemented for `()`
                                 the trait bound `(): std::ops::Carrier` is not satisfied
    .address("1.2.3.4".into())
    .port(9234);
```

**Comment by anderejd** [comment]
I'm guessing here, but I suspect your function has no return type declared. To use the question mark operator the enclosing function need to return a Result.
Here are some links:
https://doc.rust-lang.org/book/error-handling.html
https://doc.rust-lang.org/std/result/

Hope that helps! :)

**Comment by intrepion** [comment]
What I'm trying to say is I think there is a bug with the example code at [https://api.rocket.rs/rocket/struct.Rocket.html#method.custom](https://api.rocket.rs/rocket/struct.Rocket.html#method.custom)

```rust
use rocket::config::{Config, Environment};

let config = Config::default_for(Environment::active()?, "/custom")?
    .address("1.2.3.4".into())
    .port(9234);

let app = rocket::custom(&config);
```

I don't see an enclosing function around it.  Should there be?  It's not clear in the example.

**Comment by SergioBenitez** [comment]
All of the example code (with the exception of code that has `...` in it) you see in the API documentation _must_ be correct as it's checked by Rust. What you're observing is that the docs are hiding the surrounding function for (hopefully) clarity. The full example code is the following:

```rust
use rocket::config::{Config, Environment};
use rocket::config::ConfigError;

fn try_config() -> Result<(), ConfigError> {
    let config = Config::default_for(Environment::active()?, "/custom")?
        .address("1.2.3.4".into())
        .port(9234);

    let app = rocket::custom(&config);
    Ok(())
}
```

You'd see this in the source code. This is a fairly common way to structure examples in Rust. The `?` operator should make it clear that `Environment::active()` and `Config::default_for(..)` return a `Result`. If not, their API docs make this clear.

This particular example code will go away soon, but there will still be one `?` in the example. I am inclined to keep the example clean in this way, but if people feel that the example is obtuse as a result, I'm happy to change it.

**Comment by SergioBenitez** [comment]
This appears to be answered. Feel free to reopen if you feel otherwise!
