### ISSUE TITLE
Rocket doesn't expect comma-separated IPs

### ISSUE THREAD

**Issue by githubaccount624** [SergioBenitez/Rocket#1393]
So I was just going through my rocket (master branch on stable) logs on prod and I noticed this line:

`Warning: 'X-Real-IP' header is malformed: 1.2.3.4, 5.6.7.8`

The actual IP addresses are different of course, but basically the question is whether or not this is something I should be concerned with? I'm not too sure how to interpret it to be honest. I suppose someone connected with two IP addresses? Not sure.

Anyways, Jeb recommended I file an issue so here it is!

**Comment by SergioBenitez** [comment]
The `X-Real-IP` header is a non-standard header used by proxies to indicate to the origin server the IP of the client that hit the proxy. As the name would suggest, the header _should_ contain exactly one IP address; this is what Rocket expects. Of course, proxies are free to do whatever they want. In this case, it seems that some proxy added another IP to the list; this IP should have likely been stored in an `X-Forwarded-For` header instead, which generally does contain a list of IPs.

While Rocket _could_ accept a list of IPs in the header's value, it is unclear what it should do with the list. The singular purpose of parsing the header is to determine the canonical IP address of the client: in a list of IP addresses, which one should Rocket choose? Every choice is equally arbitrary and amounts to deciding a format for the header value: this is akin to deciding that the header should contain only one IP address. What's more, proxies can be configured to choose one IP from the list if necessary, propagating only one IP to Rocket. As such, I believe Rocket's functionality here is correct and judicious. I don't think we should change it.
