### ISSUE TITLE
How to have Catcher return Responder borrowing from Request

### ISSUE THREAD

**Issue by couchand** [SergioBenitez/Rocket#1394]
I'd like to write a catcher that returns a `Responder` borrowing from the `Request`.  The ideal code would be:

```
#[derive(Responder)]
#[response(status = 404, content_type = "html")]
struct NotFound<'a> {
  inner: OtherResponder<'a>,
}

#[catch(404)]
fn not_found<'r, 's>(&'r Request<'s>) -> NotFound<'r> {
    todo!()
}
```

Unfortunately, this fails in compilation with something like:

```
25 | #[catch(404)]
   | ------------- expected due to this
26 | pub fn not_found<'r, 's>(req: &'r Request<'s>) -> NotFound<'r> {
   |                          ^^^^^^^^^^^^^^^^^^^^ expected concrete lifetime, found bound lifetime parameter
   |
   = note: expected fn pointer `for<'r, 's> fn(&'r rocket::Request<'s>) -> _`
                 found fn item `for<'r, 's> fn(&'r rocket::Request<'s>) -> routes::not_found::NotFound<'r> {routes::not_found::not_found}`
```

I've tried using `'s` (though I don't think that's the right lifetime) and that doesn't compile either.  I've tried a few other tricks, and nothing seems to line up.

However, I rewrote it to not use the macro machinery and everything works fine:

```
pub fn not_found_2<'r>(req: &'r Request) -> rocket::response::Result<'r> {
    let responder = todo!();

    responder.respond_to(req)
}
```

Is there a way to make the lifetimes work out on the macro and `Responder` version?  Thanks.

Using 0.4 latest.

**Comment by SergioBenitez** [comment]
Yes, this is an unfortunate shortcoming of inference, which we trigger with `_` in codegen as below:

https://github.com/SergioBenitez/Rocket/blob/4683407f59abc56d247387cd296502f7e1b6ccb2/core/codegen/src/attribute/catch.rs#L56-L63

This has been reworked in `master`. The following compiles and works as expected:

```rust
#[catch(404)]
fn not_found<'r>(req: &'r rocket::Request<'_>) -> &'r str {
    req.uri().path()
}
```

I'd be happy to accept a PR backporting the relevant changes to `v0.4`. Alas, with `0.5` in the wings, the best course of action is likely to wait for a release. As such, I'm closing this issue.
