### ISSUE TITLE
Invalid code in guide: Request -> field validation doc for v0.4

### ISSUE THREAD

**Issue by Weird-Dan** [SergioBenitez/Rocket#1395]
Going through the docs i found this in the Request page in the field validation paragraph:

```
use rocket::http::RawStr;
use rocket::request::FromFormValue;

struct AdultAge(usize);

impl<'v> FromFormValue<'v> for AdultAge {
    type Error = &'v RawStr;

    fn from_form_value(form_value: &'v RawStr) -> Result<AdultAge, &'v RawStr> {
        match form_value.parse::<usize>() {
            Ok(age) if age >= 21 => Ok(AdultAge(age)),
            _ => Err(form_value),
        }
    }
}

#[derive(FromForm)]
struct Person {
    age: AdultAge
}
```

I find it unclear why there is an alias created but never used, and from where "age" is coming. 
Excuse me if i'm wrong, is just started learning rust today, but would not this be more "correct":

```
use rocket::http::RawStr;
use rocket::request::FromFormValue;

struct AdultAge(usize);

impl<'v> FromFormValue<'v> for AdultAge {
    type Error = &'v RawStr;

    fn from_form_value(form_value: &'v RawStr) -> Result<AdultAge, Error> {
       let age = match usize::from_form_value(v) {
            Ok(v) => v,
            Err(_) => return Err("value is not a number."),
        };

        match age >= 21 {
            true => Ok(AdultAge(age)),
            false => Err("must be at least 21."),
        }
    }
}

#[derive(FromForm)]
struct Person {
    age: AdultAge
}
```

**Comment by SergioBenitez** [comment]
All documentation code is tested to compile and, when relevant, run and pass tests. Thus, it is necessarily valid.

> I find it unclear why there is an alias created but never used

I'm not sure what you're referring to as an "alias" here. In Rust, "alias" usually refers to [type aliases](https://doc.rust-lang.org/reference/items/type-aliases.html) of which there are none in that example.

>  ...and from where "age" is coming.

I assume you mean the `age` in the `if` in the pattern match? That would be the `age` that's pattern matched in the `Some`; this is a [match guard](https://doc.rust-lang.org/reference/expressions/match-expr.html#match-guards).

> Excuse me if i'm wrong, is just started learning rust today, but would not this be more "correct":

This is identical to the implementation in the guide except it's lengthier, returns a string as an error message, discarding the original value (which may be useful), and, in my opinion, much less idiomatic.

Feel free to hop on on our [Matrix channel](https://chat.mozilla.org/#/room/#rocket:mozilla.org) should you find yourself with similar questions!
