### ISSUE TITLE
Default content-type for StaticFiles

### ISSUE THREAD

**Issue by pwoolcoc** [SergioBenitez/Rocket#1397]
Rocket version:

```
version = "0.5.0-dev"
source = "git+https://github.com/SergioBenitez/rocket#ddfd73d6f33e8a8ef3f37be94bbbdcb840804326"
```

os version: OSX Catalina (10.15.6)

When using `StaticFiles` to serve content, it relies on `ContentType::from_extension` to generate the content-type header for a response. If a file does not have an extension, no content-type will be set. I'd like to know if there is a way to set a default content-type, or if that would be a useful feature to add. I'm willing to open a PR for the feature if there is a likely chance it will be accepted.

To reproduce: serve a file without an extension using `rocket_contrib::serve::StaticFiles`

Assuming there is no existing way to do this, I'd be curious about maintainers' ideas of how to solve this. I'd be happy defaulting to `text/plain`, and including it as an option in the existing `Options` bitmask. However, others might want the ability to set it to a specific content-type, like `text/html` or something else, and in that case I don't have a great idea for a design.

**Comment by igalic** [comment]
maybe one could provide a default content type via Rocket.toml? although i don't know how much of that would change with #852

**Comment by SergioBenitez** [comment]
> When using `StaticFiles` to serve content, it relies on `ContentType::from_extension` to generate the content-type header for a response. If a file does not have an extension, no content-type will be set. I'd like to know if there is a way to set a default content-type, or if that would be a useful feature to add. I'm willing to open a PR for the feature if there is a likely chance it will be accepted.

There is no way to set a default `Content-Type` at the moment. My take is that a good default would be `ContentType::Binary`, or perhaps `None` as it is today. Here's an idea for an API:

```rust
impl StaticFiles {
    pub fn default_content_type<C>(mut self, content_type: C) -> Self 
        where C: Into<Option<ContentType>>
    {
        self.default_content_type = content_type.into();
        self
    }
}
```

`.default_content_type(None)` would revert the functionality to the present one. `.default_content_type(ContentType::Plain)`, for example, would set `ContentType::Plain` as the default `Content-Type`.

I would accept a PR implementing this API. It's unfortunate that `default_content_type` is rather lengthy; I'd be appreciative of a name that is as descriptive yet pithier.

**Comment by SergioBenitez** [comment]
@igalic With #852 implemented, you could parse your own `Content-Type` from a config easily:

```toml
# Rocket.toml
default_content_type = "application/json"
```

```rust
#[derive(Deserialize)]
struct MyAppConfig {
    default_content_type: ContentType
}

let config: MyAppConfig = Config::default().extract()?;
rocket::ignite().mount("/", StaticFiles::from(...).default(config.default_content_type));
```

**Comment by SergioBenitez** [comment]
Accepted, and moving to tracking in #95.
