### ISSUE TITLE
Use edition 2018 code for docs?

### ISSUE THREAD

**Issue by hongquan** [SergioBenitez/Rocket#1399]
Hello,

I found that Rocket documentation is still using traditional Rust code style. Do you think that we should convert them to "2018 edition"? Rocket already applies nightly Rust features, there isn't a "backward compatibility" promise to keeps.

**Comment by SergioBenitez** [comment]
What are you referring to, specifically? All of the documentation in `master` _is_ Rust 2018.

Perhaps you're referring to our use of `macro_use`? If so, the documentation for 0.5 makes it clear that why this is our preference, you may prefer using the new `use`-based alternative in Rust 2018.

**Comment by hongquan** [comment]
Yes, I'm referring to `macro_use`. Thank @SergioBenitez for explanation.
