### ISSUE TITLE
sqlite_pool + confliflicting dependencies on r2d2_sqlite version

### ISSUE THREAD

**Issue by ajvok** [SergioBenitez/Rocket#1403]
Can't use sqlite_pool due to conflicting version dependencies on rusqlite.

My .toml has rusqlite = "0.16.0" as per the rocket documentation.
However rocket_contrib v0.4.5 depends on `r2d2_sqlite v0.6.0` which depends on  `rusqlite v0.14.0`
Is there a way to get around this? Thanks.

>  1. The version of Rocket you're using. Ensure it's the latest, if possible.

Rocket 0.4.5

>  2. The operating system (distribution and version) where the issue occurs.

Debian 10

>  3. A brief description of the bug that includes:

I'm trying to use sqlite_pool.
As per https://rocket.rs/v0.4/guide/state/#databases I'm using rusqlite 0.16 with rusqlite::Connection

This fails to build as...

error: multiple packages link to native library `sqlite3`, but a native library can be linked only once

package `libsqlite3-sys v0.9.1`
    ... which is depended on by `rusqlite v0.14.0`
    ... which is depended on by `r2d2_sqlite v0.6.0`
    ... which is depended on by `rocket_contrib v0.4.5`
    ... which is depended on by `web v0.1.0 (mytest)`
links to native library `sqlite3`

package `libsqlite3-sys v0.11.1`
    ... which is depended on by `rusqlite v0.16.0`
    ... which is depended on by `web v0.1.0 (mytest)`
also links to native library `sqlite3`

**Comment by SergioBenitez** [comment]
There is not, unfortunately. You can either use Rocket from `master`, patch `0.4` locally and use Cargo's `patch` feature, or implement `Poolable` yourself for the current version. See #1341, https://github.com/SergioBenitez/Rocket/issues/888#issuecomment-454616267, #902.
