### ISSUE TITLE
The Json example does not compile against master

### ISSUE THREAD

**Issue by CapnOrange** [SergioBenitez/Rocket#1408]
# Bug Report

Not able to run the JSON example (https://github.com/SergioBenitez/Rocket/tree/master/examples/json) against master branch.

1. Rocket version: https://github.com/SergioBenitez/Rocket/tree/master (0.5.0-dev)
2. OSX 10.15.5
3. Multiple instances(6) of `error[E0277]`:
```
  --> examples/json/src/main.rs:28:16
      |
28 | fn new(id: ID, message: Json<Message>, map: State<'_, MessageMap>) -> JsonValue {
      |                ^^^^^^^^^^^^^^^^^^^^^^ the trait `rocket::data::FromData` is not implemented for `rocket_contrib::json::Json<Message>`
      |
      = note: required because of the requirements on the impl of `rocket::data::FromTransformedData<'_>` for `rocket_contrib::json::Json<Message>`
```

**Comment by jebrosen** [comment]
This generally shouldn't happen, since CI runs tests on all examples. I also can't reproduce with the latest master (549c924). What commit are you using, and how did you run the example?

**Comment by CapnOrange** [comment]
I'm sorry, this issue is likely related to version mismatch for `rocket` and `rocket-contrib`.

```
[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket", version = "0.5.0-dev", branch = "master" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dependencies.rocket_contrib]
version = "0.4.5"
default-features = false
features = ["json"]
```

I need to figure out how to use the sub-module of `rocket-contrib`.
