### ISSUE TITLE
diesel::PgConnection fairing fails in unittests

### ISSUE THREAD

**Issue by MikhailMS** [SergioBenitez/Rocket#1409]
## Bug Reports

  1. The version of Rocket you're using

I am using version 0.4.5

  2. The operating system (distribution and version) where the issue occurs
macOS 10.14.6, rustc 1.47.0-nightly (6c8927b0c 2020-07-26)

  3. A brief description of the bug that includes:
    * The nature of the bug.
I attempted to create a simple API in Rocket, which connects to PostgresDB and inserts/searches data there.
Weirdly enough everything works in a sense that I can compile Rocket application and I can manually test it.
However unit tests are failing for some reason and unfortunately, for some reason, when I run **cargo test** it doesn't display any error/debug messages so it is hard for me to see what actually is wrong here

    * When the bug occurs.
Only when I run unittests

    * What you expected vs. what actually happened.
Ideally unit tests should pass, as application works as expected (confirmed after manual testing)

  4. How you uncovered the bug. Short, reproducible tests are especially useful.
I do have a repo for this project here - https://github.com/MikhailMS/rust-rocket-api-example
So, to reproduce the issue: **git clone** and then **cargo test**. To ensure it doesn't fail because it cannot connect to DB, there is a simple docker container with PostresDB in that project, which you can spin up

  5. Ideas, if any, about what Rocket is doing incorrectly.
I am clearly missing something about **struct PostgresDBConn(diesel::PgConnection)** and how it supposed to work.
BUT there could be a chance that there is a bug somewhere in Rocket (I've been lucky in a past couple of weeks to run into bugs in different libraries here & there)

PS: I am a total beginner in Rust & Rocket, so if I am doing something wrong - sorry :)

**Comment by jebrosen** [comment]
> unfortunately, for some reason, when I run cargo test it doesn't display any error/debug messages so it is hard for me to see what actually is wrong here

Yes, this is normal for `cargo test` since it makes it harder to see which tests were run/passed/failed. To see the program output, you need to add a flag: `cargo test -- --nocapture`.

> However unit tests are failing for some reason

It looks like you only attach the fairing in `main()`, which the tests don't ever call. Moving the fairing into `rocket()` should fix this. (If it doesn't, please re-open!)

**Comment by MikhailMS** [comment]
Now I feel stupid :D 
That's probably obvious, that **main()** is not called in tests, but I missed it somehow.

Thank you for pointing that out - now it works :)
