### ISSUE TITLE
State should implement Clone+Copy

### ISSUE THREAD

**Issue by timokoesters** [SergioBenitez/Rocket#1411]
State is just a reference to a type. There's no reason why it can't be copied or clones (to create another reference to that type).
Use-case: One of my endpoints calls another endpoint method internally, supplying a State<>. Because this consumes the state, I can't do anything else with it afterwards.

**Comment by igalic** [comment]
usually the solution is to put an `Arc` into `State` which can very cheaply be cloned

Since that is such a common pattern, we might as well implement `State` as `Arc`…

**Comment by timokoesters** [comment]
Even if the type in State is an Arc, the State struct does not implement Clone or Copy

**Comment by jebrosen** [comment]
Yeah, `State<'_, T>` should be constructible from some kind of pointer-to-T for easier reuse. Conservatively, I see no problem with implementing `Clone` but I am less sure about `Copy` (which is more restrictive on the kinds of changes we could make to `State` in the future).

**Comment by igalic** [comment]
does this now mean we can use `State` without an `Arc`?

**Comment by SergioBenitez** [comment]
@igalic You can put whatever you'd like in `State` as long as it's `Send + Sync + 'static`; there was never any requirement to use an `Arc`. You'd only need an `Arc` prior if you were sharing ownership of the value inside of the `State` - this remains true today.

The latest change simply implements `Clone` by copying the internal reference to the managed state. It doesn't provide shared ownership, nor does it copy or clone the internal value.
