### ISSUE TITLE
Missing secret_key warning should only show when necessary

### ISSUE THREAD

**Issue by timokoesters** [SergioBenitez/Rocket#1412]
https://rocket.rs/v0.4/guide/requests/#secret-key

The secret key is used for private cookies, so I think it should only be displayed if your code uses private cookies.

**Comment by SergioBenitez** [comment]
It is already the intention that the warning is only emitted if the `private-cookies` feature is enabled and no secret key has been set. Can you confirm? Note that `private-cookies` is a default feature.
