### ISSUE TITLE
Add `FromRequest for IpAddr` which maps to `Request.client_ip()`

### ISSUE THREAD

**Issue by Gerhut** [SergioBenitez/Rocket#1414]
## Feature Requests

Feature requests _must_ include:

  1. Why you believe this feature is necessary.

> The `client_ip` is pretty useful for logging or subnet filtering as long as the `X-Real-IP` is trusted, and it's very straight to user about mapping `IpAddr` to `client_ip`.

> As we implemented, there are 2 addresses the server can get, `remote: SocketAddr` and `client_ip: IpAddr`, the former one already have a guard so I think provide another guard for the latter one looks good.

  2. A convincing use-case for this feature.

> Display user's IP at the footer of the page.

  3. Why this feature can't or shouldn't exist outside of Rocket.

> It's not possible to implement `FromRequest for IpAddr` outside of Rocket.

**Comment by oiwn** [comment]
This would be useful.

**Comment by SergioBenitez** [comment]
Sure! Happy to accept a PR.
