### ISSUE TITLE
Automatically parse routes

### ISSUE THREAD

**Issue by impowski** [SergioBenitez/Rocket#142]
Some guy came into IRC and gave an example of how Laravel work with their `Controllers`, and I become curious about implementing the same future in Rocket, because it seems kinda neat.

Some example how it might work:
```
impl Controller for UserController {
    #[get("/create")]
    fn create() -> User {}
}
```
And then we can just simply mount it like that:
```
mount("/user", UserController)
```

This will allow us to automatically consider which functions implement what and etc. I guess it could be done via codegen, but I didn't take a look is it possible right now or not.

Or maybe we could consider something like this: 
```
impl Controller for UserController {
    fn get_create() -> User {}
}
```
With this we will just take a look at prefixes of functions and decide which method it uses, but I don't really know it this possible at all, maybe through some sort of macro.

I don't really consider this as a very needed thing but it will kinda simplify mounting, so there will be no need to use `use` to import functions to a different file if you mount in a different place.

And I guess I would like to hear what @SergioBenitez will say about such enhancement, and if it's possible or even needed I'd take a look and implement such thing.

**Comment by SergioBenitez** [comment]
This sounds like #18, an idea I proposed some time ago. Does that match?

**Comment by impowski** [comment]
They seem similar but, it would be good to have more methods instead of just CRUD, like in [Laravel](https://laravel.com/docs/5.1/controllers#restful-resource-controllers).

**Comment by impowski** [comment]
So due to IRC discussion with @SergioBenitez I'll post this as what we might agree on.

At least we need to have something like this:
```
use user;
.mount("/user", user::*)
```
This will allow to mount all functions which use a `#[route]` thingy, instead of writing it by hand. Not really sure how it will be implemented.

**Comment by SergioBenitez** [comment]
I'm going to go ahead and close this out. While syntax like `user::*` _might_ be something we want in the future, I don't see a way to enable it gives Rust's syntax extensions. Even then, it's not clear if it's actually needed. Happy to revisit focused proposals for improvements on this front in the future.
