### ISSUE TITLE
Rocket/Juniper/MySQL Integration

### ISSUE THREAD

**Issue by bostontrader** [SergioBenitez/Rocket#1421]
I'm having a difficult time getting Rust, Juniper/GraphQL, and MySQL to all work together.  This problem is compounded by the fact that each piece is working just fine, it's the integration that is a problem.  So who shall I beg insight from?

As Rocketeers know, Rocket has a method for connecting to MySQL. It involves creating an object, in my example I'll call it MyRocketSQLConn, and feeding said object to any route handlers that need a connection to MySQL.  This part works just fine.

As Junipeters know, Juniper defines a query, schema, and context that are also fed to any Rocket route handlers that need them.  The route handler will invoke query.execute(schema, context) to do its thing. This part also works just fine.

I can successfully deliver MyRocketSQLConn, Query, Schema, and Context into a route handler, but get stuck shortly thereafter.

In the examples that I've seen Context has been used to hold a toy database but it looks like an obvious place to inject MyRocketSQLConn into the Juniper works. Unfortunately this is trouble.  The basic reason for this is that the context is [immutable for reasons of thread safety](https://github.com/graphql-rust/juniper/issues/5) and I would need to use inner mutability to inject MyRocketSQLConn into this.

I have come tantalizingly close to a solution by adding a field to the Juniper Context object, which I call JunDatabase:

```
pub struct JunDatabase {
    pub conn: Arc<Mutex<Option<MyRocketSQLConn>>>,
}
```

The Arc and Mutex deal with the thread safety issues.  I need Option because I must create the Juniper Context before I have instantiated MyRocketSQLConn.

So the route handler that I have is:

```
#[rocket::post("/graphql", data = "<request>")]
fn post_graphql_handler(
    context: State<M::JunDatabase>,
    request: juniper_rocket::GraphQLRequest,
    schema: State<Schema>,
    mut conn: MyRocketSQLConn
) -> juniper_rocket::GraphQLResponse {

    {
        let m = &*context.conn;
        let mut m1 = m.lock().unwrap();
        *m1 = Some(conn);
    }

    request.execute(&schema, &context)

}
```

This part works just fine and execution will eventually get to:

```
fn helloJuniper(database: &JunDatabase) -> i32 {
    let m1 = &*database.conn;
    let m2 = m1.lock().unwrap().as_ref().unwrap();

    ...
}
```

At this point the code compiles and upon execution m2 is a &MyRocketSQLConn.  This is where I'm stumped.

The basic issue is that, depending upon which of the 99,000 subsequent variations I try, the error messages generally complain about moves, borrows, mutability, and lifetimes.  I have a general understanding of these issues individually, but undoubtedly have more to learn about these topics.

Given one particular guess yields:
```
let m3 = (*m2).prep_exec(...);
^^^^^ `m2` is a `&` reference, so the data it refers to cannot be borrowed as mutable

```
I'll spare you the loooong list of guesses that I've made about this as I thrash hopelessly hoping that the infinite monkey battalion can succeed in the absence of divine insight.  If I'm missing a magic * somewhere, I'd be happy to have my nose rubbed in that fact.  But I'd **really** like to hear some ideas for a general purpose approach to dealing with this issue.

Thank you.

**Comment by jebrosen** [comment]
This isn't the first time I've seen this kind of issue with `juniper` and `rocket`, but I've seen plenty of "success stories" as well. I'm starting to be able to guess why, though: for several of the databases with integrations in `rocket_contrib`, all of the query methods take `&self`, for example the `Connection` type from `postgres 0.15`.

For your specific example, it looks to me like your attempted solution might work, with one minor change: `let m2 = m1.lock().unwrap().as_mut().unwrap();` - notice the `as_mut()` instead of `as_ref()`. Here's another unrelated change I think you will want: don't put `JunDatabase` into managed `State`, instead create one in the route. Currently, all of the routes are sharing a single `JunDatabase` even though they don't need to.

```rust
#[rocket::post("/graphql", data = "<request>")]
fn post_graphql_handler(
    request: juniper_rocket::GraphQLRequest,
    schema: State<Schema>,
    mut conn: MyRocketSQLConn
) -> juniper_rocket::GraphQLResponse {
    let context = JunDatabase { conn: Arc::new(Mutex::new(Some(conn))) };
    request.execute(&schema, &context)
}
```

**Comment by bostontrader** [comment]
@jebrosen , thanks for the advice.  For the next guy who has this problem, I did specifically get this part working in [this particular commit](https://github.com/bostontrader/bookwerx-core-rust/commit/592d114906f5938199e38ffe60e93e7656a1fd81)

**Comment by SergioBenitez** [comment]
Looks like this was resovled!
