### ISSUE TITLE
Live template reloading is unavailable.

### ISSUE THREAD

**Issue by dixtel** [SergioBenitez/Rocket#1430]
Rocket version: 0.4.5
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
Kernel Version: 5.4.0-47-generic
OS Type: 64-bit
Processors: 2 × Intel® Pentium® CPU G3258 @ 3.20GHz

Hello, hot reoloading in my rocket project is unavailable. On the windows the same project structure (almost) hot reoloading is working. Everythings else works fine, I'm thinking that this issue is related to my OS. I use custom system theme.

Error on console after "cargo run":

Warning: Failed to enable live template reloading: other os error
    => Warning: Live template reloading is unavailable.

**Comment by cbzehner** [comment]
Can you provide the full output of `cargo run`? And if your project is public a link to the git repo?

**Comment by dixtel** [comment]
```  
Finished dev [unoptimized + debuginfo] target(s) in 3.59s
     Running `target/debug/haxly`
🔧 Configured for development.
    => address: localhost
    => port: 8000
    => log: normal
    => workers: 4
    => secret key: provided
    => limits: forms = 32KiB
    => keep-alive: 5s
    => tls: disabled
    => [extra] databases: { haxly = { url = "postgresql://postgres:postgres@localhost:5432/haxly" } }
🛰  Mounting /:
    => GET /script?<token> (get_haxly_core_script)
    => GET /login (login)
    => POST /login (login_post)
    => GET /signup (signup)
    => POST /signup (signup_post)
    => GET /logout (logout)
    => GET / (index)
    => GET /dashboard (dashboard)
    => GET /dashboard/new (dashboard_new)
🛰  Mounting /:
    => GET / [10]
    => GET /<path..> [10]
📡 Fairings:
    => 1 request: Templates
🚀 Rocket has launched from http://localhost:8000
GET / text/html:
    => Matched: GET / (index)
    => Outcome: Success
    => Response succeeded.
GET /bootstrap/css/bootstrap.min.css text/css:
    => Matched: GET /<path..> [10]
    => Outcome: Success
    => Response succeeded.
GET /css/styles.css text/css:
    => Matched: GET /<path..> [10]
    => Outcome: Success
    => Response succeeded.
...
```

This project is private but i can send you this project on pv or paste some code.

**Comment by dixtel** [comment]
Hmmm very strange, now hot reolading works fine. I dont know what i did but now its look like this is working.

**Comment by cbzehner** [comment]
Glad it's working now! I don't know if this is what you experienced but...

I've seen some similar issues using Tera templates, but in most cases it's actually a syntax error in my template files HTML. Generally before the final output I'll find some error message pointing to the specific template/syntax error.

**Comment by dixtel** [comment]
I use tera templates and this error showed after ```cargo run```, before doing any requests. So I didin't have any syntax error in templates i'm think.

**Comment by jebrosen** [comment]
> Warning: Failed to enable live template reloading: other os error

This corresponds to `std::io::ErrorKind::Other`, which could mean pretty much anything (and it unfortunately didn't include any more details). Since it's working fine now, I assume it was some kind of temporary or one-time kernel/filesystem error when setting up `inotify` that will be difficult or impossible to reproduce. If it does happen again, let's reopen this and investigate it more closely.
