### ISSUE TITLE
Optional header include to ResponseBuilder

### ISSUE THREAD

**Issue by wh75er** [SergioBenitez/Rocket#1431]
Version of Rocket: 0.4.5

I have a question about including an optional header into the ResponseBuilder. I haven't found anything about it in the docs: struct Response, ResponseBuilder and Responder Trait and in any other issues. Here's the point. I've created custom response struct, which has Status and Json fields. I've implemented a Responder trait:

```Rust
 1 #[derive(Debug)]
  2 pub struct ApiResponder {
  3     inner: JsonRespond //custom enum with different Json<T>,
  4     status: Status,
  5 }
  6 
  7 impl<'r> Responder<'r> for ApiResponder {
  8     fn respond_to(self, req: &Request) -> response::Result<'r> {
  9         Response::build_from(self.inner.respond_to(&req).unwrap())
 10             .status(self.status)
 11             .header(ContentType::JSON)
 12             .ok()
 13     }
 14 }
```

It works fine, but sometimes I need to add an additional header to my custom response and I'm struggling to find how to do it. E.g. I want to add an optional header .raw_header("Location", "url") to the builder, but I can't do it, because any changes in respond_to function will apply to other cases where I don't need any additional headers.

I hope thats clear and the solution will be obvious and easy. Also, I think it should be in the ResponseBuilder man page, because it describes how to build your custom Response.

OR how can I make an empty header so it'll not pop up in headers in response. I've tried this

> .raw_header("", "")

But it just creates an empty header like

> :

**Comment by wh75er** [comment]
Alright, I found out how to do it: you can create a Responder wrapper, either you can write condition in your custom Responder implementation.

**Comment by jebrosen** [comment]
Glad you were able to solve your issue. Would you mind copying part of the code here in case someone else has the same question again?

**Comment by wh75er** [comment]
Yeah, sure. Sorry, if it looks ugly, but here's 2 solutions to that problem:

- Condition in the Responder implementation:

```Rust
#[derive(Debug)]
pub struct ApiResponder {
    inner: JsonRespond,
    status: Status,
    location: Option<String>,
}

impl<'r> Responder<'r> for ApiResponder {
    fn respond_to(self, req: &Request) -> response::Result<'r> {
        let mut build = Response::build_from(self.inner.respond_to(&req).unwrap());
        if let Some(location) = self.location {
            build.merge(Response::build().header(header::Location(location)).finalize());
        }
        build.status(self.status).header(ContentType::JSON).ok()
    }
}
```

- Responder Wrapper:

```Rust
#[derive(Debug)]
pub struct ApiResponder {
    inner: JsonRespond,
    status: Status,
}

#[derive(Debug)]
pub struct LocationWrapper<R>(pub String, pub Option<R>);

impl<'r> Responder<'r> for ApiResponder {
    fn respond_to(self, req: &Request) -> response::Result<'r> {
        Response::build_from(self.inner.respond_to(&req).unwrap())
            .status(self.status)
            .header(ContentType::JSON)
            .ok()
    }
}

impl<'r, R: Responder<'r>> Responder<'r> for LocationWrapper<R> {
    fn respond_to(self, req: &Request) -> response::Result<'r> {
        let mut build = Response::build();
        if let Some(responder) = self.1 {
            build.merge(responder.respond_to(req)?);
        }

        build.header(header::Location(self.0)).ok()
    }
}
```

But I've got *"match arms have incompatible types"* when I was trying to return impl Responder with *match*. There was LocationWrapper in one arm and ApiResponder in the other one. So I ended up with the first solution...
