### ISSUE TITLE
How do I pass a mysql connection to endpoint controller?

### ISSUE THREAD

**Issue by ChristianLindLarsen** [SergioBenitez/Rocket#1435]
Hi. Learning Rust and trying to create a simple application with Rocket - basically call an endpoint(`/orgs`) that fetches a bunch of records in a MySQL database. Pretty basic stuff, but I can't seem to make it work together. I'm coming from programming in Go mostly. 

Heres's my current code, pretty stuck at the moment:

```
#![feature(decl_macro)]
#[macro_use] extern crate rocket;
#[macro_use] extern crate rocket_contrib;

use serde::Serialize;
use rocket_contrib::json::Json;

#[macro_use]
extern crate mysql;
use mysql as my;
use mysql::Pool;
use mysql::consts::ColumnType::MYSQL_TYPE_DATE;
use mysql::prelude::Queryable;

#[get("/orgs")]
fn get_orgs(conn: MyDb) -> Json<Vec<Org>> {
    // I need to have the db connection here to pass it to get_all.
    let o = match Org::get_all() {
        Ok(o) => o,
        Err(e) => panic!(e),
    };

    Json(o)
}


#[derive(Serialize)]
pub struct Org {
    pub id: Option<i32>,
    pub name: String,
}

fn main() {
    let url = "mysql://root:mysql@(localhost:33061)/rustdb";
    let pool = Pool::new(url)?;
    let mut conn = pool.get_conn();
    // I need to pass "conn" around, first to get_orgs, then to Org::get_all.
    rocket::ignite()
        .mount("/", routes![get_orgs])
        .launch();
}

impl Org {
    fn get_all(mut conn: mysql::Conn) -> Result<Vec<Org>, Err> {
        let all_orgs = conn
            .query_map(
                "SELECT id, name from organization",
                |(id, name)| {
                    Org { id, name }
                },
            )?;

        return match all_orgs() {
            Ok(all_orgs) => all_orgs,
            Err(e) => e,
        };
    }
}
``` 

So, when using `#[get("/orgs")]` it probably does a bunch of code generation(assumption on my side - again, I'm new!). Googling around, I found this: https://rocket.rs/v0.4/guide/state/#databases - which looks correct. I just cannot for the life of me figure out a working example to connect to my local mysql instance. 

Here are my dependencies:

```
[dependencies]
rocket = "0.4.2"
rocket_codegen = "0.4.2"
rocket_contrib = "0.4.2"
serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1.0"}
mysql = "*"
```

I looked in the `0.4` tag of the repository and went to examples. I think this is a widely popular use-case. Would it perhaps be an idea to make an example of how to set up an endpoint with a database connection parsed into it, be that via postgres or mysql? Would be awesome, I'm sure a lot - especially myself - would appreciate it!

**Comment by SergioBenitez** [comment]
> I looked in the `0.4` tag of the repository and went to examples. I think this is a widely popular use-case. Would it perhaps be an idea to make an example of how to set up an endpoint with a database connection parsed into it, be that via postgres or mysql? Would be awesome, I'm sure a lot - especially myself - would appreciate it!

The [`todo`](https://github.com/SergioBenitez/Rocket/tree/v0.4/examples/todo) example does just this.

> So, when using `#[get("/orgs")]` it probably does a bunch of code generation(assumption on my side - again, I'm new!). Googling around, I found this: https://rocket.rs/v0.4/guide/state/#databases - which looks correct. I just cannot for the life of me figure out a working example to connect to my local mysql instance.

Your code doesn't seem to be following the advice in the guide. In particular, it's not using Rocket's build-in database support. Can you give that a try?

**Comment by ChristianLindLarsen** [comment]
I used the todo example and tried making it working with my code. It makes more sense for me, so thank you for that - however, I'm faced with a strange error now(again, new to Rust, probably tripping my own legs!)

Here's my code:

```
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use] extern crate rocket;
#[macro_use] extern crate diesel;
#[macro_use] extern crate diesel_migrations;
#[macro_use] extern crate log;
#[macro_use] extern crate serde_derive;
#[macro_use] extern crate rocket_contrib;

use rocket::Rocket;
use rocket::fairing;
use rocket::request::{Form, FlashMessage};
use rocket::response::{Flash, Redirect};
use rocket_contrib::{templates::Template, serve::StaticFiles};
use diesel::MysqlConnection;


use rocket::State;
use rocket::response::content;
use mysql::prelude::Queryable;
use rocket::response::content::Json;


#[database("mysql_database")]
pub struct DbConn(MysqlConnection);

#[get("/orgs")]
fn get_orgs(conn: DbConn) -> Json<Vec<Org>> {
    // I need to have the db connection here to pass it to get_all.
    let o = match Org::get_all(conn) {
        Ok(o) => o,
        Err(e) => panic!(e),
    };

    Json(o)
}


fn rocket() -> rocket::Rocket {
    rocket::ignite()
        .attach(DbConn::fairing())
        .mount("/", routes![get_orgs])
}

fn main() {
    rocket().launch();
}

#[derive(Serialize)]
pub struct Org {
    pub id: Option<i32>,
    pub name: String,
}

impl Org {
    fn get_all(pool: mysql::Pool) -> Result<Vec<Org>, Err> {
        let mut conn = pool.get_conn()?;
        let all_orgs = conn
            .query_map(
                "SELECT id, name from organization",
                |(id, name)| {
                    Org { id, name }
                },
            ).unwrap();

        return match all_orgs() {
            Ok(all_orgs) => all_orgs,
            Err(e) => e,
        };
    }
}
```

There are a bunch of issues with my own code, but more notably I get this:

```
error[E0599]: no function or associated item named `fairing` found for struct `DbConn` in the current scope
```

Which I guess comes when I do `.attach(DbConn::fairing())`

What did I do wrong here?

`Cargo.toml`:

```
[dependencies]
rocket = "0.4.2"
rocket_codegen = "0.4.2"
rocket_contrib = "0.4.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
diesel = { version = "1.3", features = ["mysql", "r2d2"] }
diesel_migrations = "1.3"
log = "0.4"
```


And then I have `Rocket.toml` with:

```
[global.databases.mysql_database]
url = "root:mysql@(localhost:33061)/some-db"
```

What could be the issue, do you think?

**Comment by ChristianLindLarsen** [comment]
In similar spirit, I checked out the `todo` example and changed a few things:

In `Cargo.toml` I changed the diesel dependency to `diesel = { version = "1.3", features = ["mysql", "r2d2"] }`

In `Rocket.toml` I changed the following:

```
[global.databases.mysql_database]
url = "root:mysql@(localhost:33062)/mydb"
```

And in `main.rs`, I changed these things:

````
use diesel::MysqlConnection;`
#[database("mysql_database")]
pub struct DbConn(MysqlConnection);
```

Doing `cargo run` results in:

```
error[E0277]: the trait bound `MysqlConnection: Poolable` is not satisfied
  --> examples/todo/src/main.rs:28:19
   |
28 | pub struct DbConn(MysqlConnection);
   |                   ^^^^^^^^^^^^^^^ the trait `Poolable` is not implemented for `MysqlConnection`
```

What did I do wrong?

**Comment by flangknecht** [comment]
> In similar spirit, I checked out the `todo` example and changed a few things:
> 
> In `Cargo.toml` I changed the diesel dependency to `diesel = { version = "1.3", features = ["mysql", "r2d2"] }`
> 
> In `Rocket.toml` I changed the following:
> 
> ```
> [global.databases.mysql_database]
> url = "root:mysql@(localhost:33062)/mydb"
> ```
> 
> And in `main.rs`, I changed these things:
> 
> ```
> use diesel::MysqlConnection;`
> #[database("mysql_database")]
> pub struct DbConn(MysqlConnection);
> ```
> 
> Doing `cargo run` results in:
> 
> ```
> error[E0277]: the trait bound `MysqlConnection: Poolable` is not satisfied
>   --> examples/todo/src/main.rs:28:19
>    |
> 28 | pub struct DbConn(MysqlConnection);
>    |                   ^^^^^^^^^^^^^^^ the trait `Poolable` is not implemented for 'MysqlConnection'
> ```
> 
> What did I do wrong?

I'm guessing you didn't enable the feature "diesel_mysql_pool" as stated in https://rocket.rs/v0.4/guide/state/#usage

**Comment by ChristianLindLarsen** [comment]
Gotcha! That fix worked.

Now, I get:

```
error[E0308]: mismatched types
  --> examples/todo/src/main.rs:27:1
   |
27 | #[database("mysql_database")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `rocket::config::config::Config`, found struct `Config`
```


And

```
error[E0277]: the trait bound `Vec<Route>: std::convert::From<StaticFiles>` is not satisfied
  --> examples/todo/src/main.rs:96:10
   |
96 |         .mount("/", StaticFiles::from("static/"))
   |          ^^^^^ the trait `std::convert::From<StaticFiles>` is not implemented for `Vec<Route>`

```

And

```
error[E0277]: the trait bound `impl rocket::fairing::Fairing: Fairing` is not satisfied
  --> examples/todo/src/main.rs:99:17
   |
99 |         .attach(Template::fairing())
   |                 ^^^^^^^^^^^^^^^^^^^ the trait `Fairing` is not implemented for `impl rocket::fairing::Fairing`

```

I guess it's an import problem?

Here are the imports:


```
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use] extern crate rocket;
#[macro_use] extern crate diesel;
#[macro_use] extern crate diesel_migrations;
#[macro_use] extern crate log;
#[macro_use] extern crate serde_derive;
#[macro_use] extern crate rocket_contrib;

mod task;
#[cfg(test)] mod tests;

use rocket::Rocket;
use rocket::fairing::AdHoc;
use rocket::request::{Form, FlashMessage};
use rocket::response::{Flash, Redirect};
use rocket_contrib::{templates::Template, serve::StaticFiles};
use diesel::MysqlConnection;

use task::{Task, Todo};

// This macro from `diesel_migrations` defines an `embedded_migrations` module
// containing a function named `run`. This allows the example to be run and
// tested without any outside setup of the database.
embed_migrations!();

#[database("mysql_database")]
pub struct DbConn(MysqlConnection);
```

Did I miss something? Apart from changing Diesel to MySql, I haven't touched much at all.

**Comment by ChristianLindLarsen** [comment]
Thank you! I got it working by doing so. It's connected and using MySql now.
