### ISSUE TITLE
Update to tokio 1.0

### ISSUE THREAD

**Issue by incker** [SergioBenitez/Rocket#1451]
New version of `tokio` is released
rocket vesrion is `0.2` [Cargo.toml](https://github.com/SergioBenitez/Rocket/blob/master/core/http/Cargo.toml#L32)

Chance to make breaking changes while `rocket = "0.5"` not released yet

**Comment by SergioBenitez** [comment]
We need hyper to upgrade first. In general, we're aware of new releases and will upgrade as soon as possible.

**Comment by krojew** [comment]
You can upgrade now and wrap hyper in a compatibility layer until they update.

**Comment by incker** [comment]
Looks like `h2` have already received PR, see [link](https://github.com/hyperium/h2/pull/491) 
And the only blocker for hyper is `h2`see [link](https://github.com/hyperium/hyper/issues/2302)

So, there is no reason to make compatibility layer. Looks like hyper updates will come soon

**Comment by protheory8** [comment]
Tokio 0.3 upgrade PR got merged into Hyper master branch recently, waiting for new Hyper release now?

**Comment by SergioBenitez** [comment]
@protheory8 That's right.

**Comment by jebrosen** [comment]
`hyper 0.14.0` has just been released, targeting `tokio 1.0` (released earlier today). The other blocker will be `tokio-rustls` (see https://github.com/tokio-rs/tls/pull/46), and I will likely start tackling a migration PR today or Saturday.

**Comment by l4l** [comment]
@jebrosen mind if I work on this? Curious to look into the sources.

**Comment by jebrosen** [comment]
I already started and (maybe) finished it! - https://github.com/SergioBenitez/Rocket/compare/master...jebrosen:tokio1. But I don't think we should review/merge it quite yet, since a decent number of crates don't yet have releases for tokio 1.0. One is `reqwest`, which I want to be able to run some tests with, and @SergioBenitez has some work in progress on multipart handling that I think will also need a dependency update.

**Comment by aspenluxxxy** [comment]
@jebrosen Reqwest already has a PR open: https://github.com/seanmonstar/reqwest/pull/1076

**Comment by aspenluxxxy** [comment]
`tokio-native-tls` and `tokio-rustls` have both just updated to Tokio 1.0.

**Comment by aspenluxxxy** [comment]
[hyper-tls has just updated to Tokio 1.0](https://github.com/hyperium/hyper-tls/commit/83747a7440f0df821672ac6d323ad34f59d1498c)

**Comment by aspenluxxxy** [comment]
Reqwest has just updated.
