### ISSUE TITLE
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch

### ISSUE THREAD

**Issue by non-binary** [SergioBenitez/Rocket#1457]
Hi there. Thanks so much everyone for building an awesome dependency.

I believe there has been a regression on the master branch for v0.5.0 or maybe something changed and I'm unaware of how to use the changed version. I am deploying Rocket with async functionality to Heroku with this Procfile:

```
web: ROCKET_PORT=$PORT target/release/bumblebee-slack
```

With this [Cargo.lock file](https://gist.github.com/non-binary/75c2cd904ec3f7aaa08f2236c7aae174), it does not work but with [this older one it does](https://gist.github.com/non-binary/392d9534f387dd0fcf3c53bdb3243e53). There are some additional dependencies in the second one but notice that the hashes are different for Rocket.

When running on Heroku, it returns this error:

```
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
```

I've worked around this but it would be nice to use a later version of Rocket at some point so if someone could let me know what i'm doing wrong or if there's an issue, let me know and maybe I can fix it but I just wanted to report this in case anyone else was experiencing something similar.

Happy coding. 🌮

**Comment by SergioBenitez** [comment]
Can you reproduce the timeout locally? And, if so, are you able to reduce the reproduction to a minimal example?

**Comment by non-binary** [comment]
I'm unable to reproduce it locally. Running `cargo run` works every time. Would you still like me to make a minimal example?

**Comment by SergioBenitez** [comment]
Do you have logs of the Rocket process starting up on Heroku? If not, could you enable debug logging with `ROCKET_LOG_LEVEL=debug`, start up the process, and collect the logs?

**Comment by SergioBenitez** [comment]
@non-binary Checking in; any chance you could provide us with the logs so we can take a closer look?

**Comment by SergioBenitez** [comment]
I was able to reproduce this with `stable` on the latest `master`; triaging now.

**Comment by SergioBenitez** [comment]
Rocket changed it's default listening address to `127.0.0.1` across all profiles, including `release`. This means that, by default, the server only listens on the local interface at `127.0.0.1`. To listen on the global interface, the address must be set to `0.0.0.0`. You can accomplish this by setting `ROCKET_ADDRESS` in `Procfile`:

```diff
-web: ROCKET_PORT=$PORT ./target/release/app
+web: ROCKET_PORT=$PORT ROCKET_ADDRESS=0.0.0.0 ./target/release/app
```

**Comment by non-binary** [comment]
Sorry, I didn't get notifications for this thread for some reason until you closed it. Thanks for looking into it. I'll know to define the ROCKET_ADDRESS in the future. Thank you!
