### ISSUE TITLE
Update database information for MongoDB in guide

### ISSUE THREAD

**Issue by techbelle** [SergioBenitez/Rocket#1462]
page: https://rocket.rs/v0.4/guide/state/#databases
MongoDB information currently links to: https://github.com/mongodb-labs/mongo-rust-driver-prototype
this page has been archived since we released our official Rust driver earlier this year. So the hyperlink should be updated to
https://github.com/mongodb/mongo-rust-driver
and version number should be 1.1.1

Thank you! 👍

**Comment by SergioBenitez** [comment]
The version used in 0.4 is `0.3`, so the documentation is correct, as far as I can tell. We _could_ update the `mongodb` driver in `0.4`, but that would be a breaking change and thus would require a major-version bump of `rocket_contrib`, which we currently reserve to occur in-sync with updates to `rocket`. Given that we've removed `mongodb` as a supported database in `0.5` (see #1343, #1117), the current situation appears correct me.
