### ISSUE TITLE
Route param format

### ISSUE THREAD

**Issue by sphinxc0re** [SergioBenitez/Rocket#147]
Is the current format of routes non-optional? Why did you choose this exact format? Currently it's:
```
/<name>/<age>
```
where it is more common to do it like this:
```
/:name/:age
```
of course this is more of a taste thing but I think it might be a struggle for a few coders

**Comment by impowski** [comment]
I guess it was more obvious to parse, for example with Iron they are not using any codegen features and they implementing TypeMap, which I guess a lot heavier then how it works in Rocket. I'll wait what @SergioBenitez

**Comment by SergioBenitez** [comment]
I don't think it's more common to do one or the other. Flask, Bottle, Django (for names groups) for instance all use the syntax Rocket uses. Rails and Go web frameworks, in general, use ':'. 

The main reasons to use the current syntax are:

  1. It's visually more obvious. My eyes can more easily parse `<` and `>` versus a single `:`.
  2. It allows for text before and after the dynamic parameter name. We might imagine Rocket allowing something like `<a>:<b>` in the future.

In any case, I really don't think anyone will struggle with this. There's no reason to debate the matter.

**Comment by mehcode** [comment]
My concern with `<a>` syntax (and likely why most frameworks use `:a`) is sub path matching.

Flask solves this with `<path:a>` and Bottle solves this with `<a:path>`. Clearly there is no consensus here. 

```python
"/articles/<year>"
"/resource/<path:rem>"
```

I'd also argue you can't count Django as its just allowing full regex (which most frameworks and I think is a touch extreme).

```python
r'^articles/(?P<year>[0-9]{4})/$'
r'^resource/(?P<rem>.*)$'
```

Now take a look at this pattern if we decided to use `:a` syntax:

```rust
"/articles/:year"
"/resource/*"
```

Much cleaner.

**Comment by SergioBenitez** [comment]
Your argument doesn't really make sense in the context of Rust and Rocket. Flask and Bottle do that because there are no types otherwise; `path` is one of many things you can require. The `*` syntax doesn't assign the path a name, which doesn't work since we need to typecheck. Finally, using `:name` is a it ambiguous at the end; does it match a single segment or everything after it.

Rocket uses `<path..>` to match all of the remaining segments. This falls in line perfectly with the syntax used in Rust for ranges.

**Comment by mehcode** [comment]
@SergioBenitez I must have missed that in the documentation. Yeah, scratch everything I said. I like how `<path..>` looks a lot.

I have a weak argument for `<path...>` as `..` means inclusive, exclusive range in Rust.

**Comment by SergioBenitez** [comment]
`..` always means "the rest" when used as a pattern in Rust.

**Comment by mehcode** [comment]
Is it not possible to do `/article/<middle..>/end` ? I was reading it more as a range.

**Comment by SergioBenitez** [comment]
It is not, no.

**Comment by mehcode** [comment]
Should it be possible? I guess that'd be another issue then to discuss later.

**Comment by sphinxc0re** [comment]
Woah... I didn't mean to break such a tall rock apart guys 😁 anyway I guess I can get used to the format. Thanks for the discussion.

**Comment by mehcode** [comment]
@sphinxc0re Eh. Discussion is good. I started with an invalid premise because I missed something in the docs but it's always good to have more viewpoints.

**Comment by sphinxc0re** [comment]
I agree with you that discussion is good. This one made me realize that I don't need the `:foo` notation
