### ISSUE TITLE
unable to configure read timeout, and no default provided

### ISSUE THREAD

**Issue by camlorn** [SergioBenitez/Rocket#1472]
I'm not sure if this is a bug, question, or feature request, but hopefully there's an answer in any case.  We're on Rocket 0.4.5, multiple versions of Linux, trying to adopt Rocket for some microservices, and our test servers are getting taken offline in a manner that suggests that no read timeout is set on the socket.  I've dug through the code, and:

- The block of code that sets Hyper up doesn't seem to set one.
- Hyper seems to default to no read timeout unless you set it.

We're still investigating this some on our end, but the next step seems to be to configure a read timeout, which I can't figure out how to do.  Is this possible?  If not, and if no read timeout is set, it seems to me that it is trivially easy to DOS a rocket server.  Any advice would be appreciated.

**Comment by camlorn** [comment]
As a clarification, I'm talking about `Server::set_read_timeout` in Hyper, not HTTP keep-alive.

**Comment by SergioBenitez** [comment]
To be clear, the latest tip of `v0.4` does indeed set a default timeout. Alas, it is not configurable, which we should remediate.

**Comment by SergioBenitez** [comment]
Resolved by 86bd7c1008a7ae8fa48fbc61c9fde72f79f4d5ea.
