### ISSUE TITLE
Reverse proxy not working with default values

### ISSUE THREAD

**Issue by AntonOellerer** [SergioBenitez/Rocket#1475]
Hey, we are currently developing a project with rocket.
As frontend, we are using a npm-based client.
Initially, we used  a `Rocket.toml` like this:
```toml
[development]
address = "127.0.0.1"
port = 8000
```
Since we figured that those are the default values, we deleted the file to reduce the amount of clutter in our codebase.
After this, when booting up our server and client, every client request was rejected, with npm showing the following error (the client runs on port 3000, the endpoints are on port 8000/api/):
```npm
Proxy error: Could not proxy request /api/ from localhost:3000 to http://localhost:8000/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
```
When hitting the api endpoint directly (e.g. with curl requesting something from localhost:8000/api), there are no problems.
When testing and fixing the bug, we discovered that the reverse proxy of Rocket seems to fail when it is configured (by default) to run on `localhost` instead of `127.0.0.1`. When we set the environment variable `ROCKET_ADDRESS` before starting Rocket, the service works again as intended.

Rocket version: `0.4.5`.

OS: Fedora 33, NixOS

**Comment by SergioBenitez** [comment]
I don't have enough information to conjecture conclusively, but here's what's probably happening: in `0.4`, the default address varies based on the environment. In `development`,  it is `localhost`, and in `production`, it is `0.0.0.0`. What's more, the default environment depends on whether the application is compiled in debug mode, where it is `development`, or release mode, where it is `production`. My guess is you're running the application in one environment when testing and in another when deploying. By setting `ROCKET_ADDRESS` explicitly, you override the address irrespective of the profile, resolving the issue.

Can you verify which environment and which address Rocket is using? The logs should indicate this. See also the [configuration guide](https://rocket.rs/v0.4/guide/configuration/) for more on how configuration works in 0.4.

**Comment by AntonOellerer** [comment]
Hey Sergio, thank you for the quick answer!
I do not think that this is the problem, since I can still reach the server API under localhost:8000/api/.
I checked for the running mode, it is `development`, I will attach the startup logs of both the client and the server below.
[client.log](https://github.com/SergioBenitez/Rocket/files/5536551/client.log)
[server.log](https://github.com/SergioBenitez/Rocket/files/5536552/server.log)

**Comment by SergioBenitez** [comment]
Got it. Then I'm fairly certain that `localhost` is resolving to something other than `127.0.0.1`. Try `host localhost` and check your `hosts` file.

**Comment by AntonOellerer** [comment]
Hey,
Here is the output, it does not seem unusual:
```bash
[user@loc ~]$ host localhost
localhost has address 127.0.0.1
localhost has IPv6 address ::1
[user@loc ~]$ cat /etc/hosts 
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

**Comment by SergioBenitez** [comment]
As you can see, `localhost` has both an IPv4 address and IPv6 address; Rocket will only bind to one. Perhaps `curl` and your node application are attempting to use different addresses. If you can reach the server under `localhost:8000/api/` but node can't reach it at the same address on the same machine, then either there is something wrong with node or it's using a different address for `local host`. Try `curl`ing to a specific address instead of `localhost`.

Unless I'm missing something rather important here, it does not seem like Rocket is doing anything incorrect: it is reachable at the address assigned. Instead, it appears that the host is being resolved differently by different clients. Setting and using an IP address rather than a hostname resolves the ambiguity.

**Comment by AntonOellerer** [comment]
Ah yes, it seems as if Rocket bound to [::1] and node tried to access it via 127.0.0.1.
Do you know whether this is documented somewhere?
Thank you a lot and sorry for the troubles!

**Comment by SergioBenitez** [comment]
We don't document this explicitly, but we ~do~ did assume that the idea of a host, and the ensuing ramifications, would be understood by end-users. This assumption has proved to be false, and so we've changed the default address to `127.0.0.1` in `0.5` to avoid issues like yours.

I'm glad this resolves your issue! Closing. :)
