### ISSUE TITLE
0.5 release timeline

### ISSUE THREAD

**Issue by samanpa** [SergioBenitez/Rocket#1476]
Is there a timeline for a 0.5 release? 

For a project that I am involved in we would like to be able to package a server that we building with rocket. It is currently not possible because rocket is not available on crates.io (We are getting tripped up [here](https://github.com/rust-lang/cargo/blob/b49ccadb4a936a4b6764040ea9c87681b7c1a4b3/src/cargo/sources/git/source.rs#L144-L147)).

**Comment by tbarusseau** [comment]
Hello @samanpa, you can build from the master branch using this in `Cargo.toml`: `rocket = { git = "https://github.com/SergioBenitez/Rocket", version = "0.5.0-dev" }`

I've been using it for a few weeks and it seems very stable.

**Comment by SergioBenitez** [comment]
@samanpa No. Rocket does not release on a timed schedule. As soon as we are feature complete for 0.5 (see [milestones](https://github.com/SergioBenitez/Rocket/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.5.0)), we will release an RC with a GM shortly thereafter. I expect at least one of these events to occur before the end of the month.

**Comment by samanpa** [comment]
> 
> 
> @samanpa No. Rocket does not release on a timed schedule. As soon as we are feature complete for 0.5 (see [milestones](https://github.com/SergioBenitez/Rocket/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.5.0)), we will release an RC with a GM shortly thereafter. I expect at least one of these events to occur before the end of the month.

Thanks for the replay.

That was the answer I was looking for (i.e. end of the month). I will be OK as long as there is something even alpha available on crates.io.

**Comment by jensim** [comment]
I'd love to have this isssue (or another) open as a tracking issue, and by it be notified when 0.5.0 does get released
