### ISSUE TITLE
Rocket 0.5.0-dev unresponsive when containerized

### ISSUE THREAD

**Issue by adamfriedland** [SergioBenitez/Rocket#1478]
rustc --version

```
rustc 1.48.0
```

Rocket version from Cargo lock

```
name = "rocket"
version = "0.5.0-dev"
source = "git+https://github.com/SergioBenitez/Rocket?branch=master#bcb8b3334b2f4e4f1a213937bcfcbd8599229f63"
```

Example

#### Cargo.toml

```
[package]
authors = ["Adam Friedland"]
edition = "2018"
name = "docker-test"
version = "0.1.0"

[dependencies]
rocket = {git = "https://github.com/SergioBenitez/Rocket", branch = "master"}
```

#### Main.rs

```
#![feature(proc_macro_hygiene, decl_macro)]

#[rocket::get("/")]
fn index() -> &'static str {
    "Hello, world!"
}

#[rocket::launch]
fn rocket() -> rocket::Rocket {
    rocket::ignite().mount("/", rocket::routes![index])
}
```

#### Rocket.toml
```
[debug]
address = "127.0.0.1"
log_level = "debug"
port = 8000

[release]
address = "0.0.0.0"
log_level = "debug"
port = 8000
```

#### Dockerfile

```
# select bin image builder
FROM rustlang/rust:nightly as builder

# create a new empty project for cache persistence
WORKDIR /app/src

# copy source tree
COPY ./ ./

# build for release
RUN cargo build --release

# pipeline to final image
FROM debian:jessie-slim

COPY --from=builder /app/src/target/release/docker-test ./
CMD ["./docker-test"]
```

#### Expected in container
```
Configured for release.
    => address: 0.0.0.0
    => port: 8000
    => workers: 48
    => log level: debug
    => secret key: [zero]
    => limits: forms = 32KiB
    => cli colors: true
    => keep-alive: 5s
    => tls: disabled
Mounting /:
    => GET / (index)
registering with poller
register Token(0) Readable | Writable
set readiness to (empty)
scheduling an accept
Rocket has launched from http://0.0.0.0:8000
```

#### What actually outputs to container
```
docker logs --tail 1000 -f #####
```

I can `cargo build --release` locally which produces a binary that I can run without a hitch. It's only when I try to run the compiled image within Docker that it produces no output. I've also just tried to hit the endpoint just in case I somehow messed up my `Rocket.toml` config but still didn't have any luck. I'm currently using Docker for Windows with the WSL 2 engine enabled.

**Comment by SergioBenitez** [comment]
There are no known issues of this sort. Are you _sure_ it's actually stalled? As of a recent commit, we switched off logging the launch information by default in `release`; you'll need to set `ROCKET_LOG_LEVEL=debug` to see it. We'll be reverting this change in #1410 which has clearly caused much confusion. See #1469 and #1468.

Try setting `ROCKET_LOG_LEVEL=debug`. Also, try running a shell in the docker container and sending a request.

Also, as a side note, you don't need `#![feature(proc_macro_hygiene, decl_macro)]` in `main.rs`.

**Comment by cbzehner** [comment]
I think I ran into this last night as well. I was able to log into my Docker container with `docker exec -it <container-id> /bin/bash` and run `curl`

```
> curl 0.0.0.0:8000
Hello, world! 
```

It's odd because `Rocket.toml` in both @adamfriedland case and my own has `log_level = "debug"` set for `[release]`

**Comment by adamfriedland** [comment]
Well that certainly is strange. If I directly set the environment variables - those being `ROCKET_LOG_LEVEL` and `ROCKET_ADDRESS` - within the compose file itself then then it overrides correctly. Is there a possible reason that it ignored my `Rocket.toml` file in the first place @SergioBenitez ? From the documentation I've read it doesn't require any explicit reference to the file.

I hope that helps with your issue though @cbzehner .

**Comment by jebrosen** [comment]
> ```
> FROM debian:jessie-slim
> COPY --from=builder /app/src/target/release/docker-test ./
> CMD ["./docker-test"]
> ```

@adamfriedland I think you left out `Rocket.toml` from the container, which might explain both problems. `Rocket.toml` is read from the current working directory at runtime, so if you're using that for configuration it needs to be included in the container or mounted somewhere the container can access it.

**Comment by adamfriedland** [comment]
Ah that makes perfect sense then. I was unaware that it was read at runtime as opposed to only at compilation. Many thanks to @SergioBenitez and @jebrosen. That solved the issues I was having. Hopefully this helps anyone else experiencing similar issues.
