### ISSUE TITLE
Feature Request: Support states that do not implement Sync

### ISSUE THREAD

**Issue by schrieveslaach** [SergioBenitez/Rocket#1480]
I'm using Rocket in the HTTP API layer of [PREvant](https://github.com/aixigo/PREvant) and there, I'm crawling data from a set of service that run on Docker daemon or Kubernetes. This crawled information is required in some frequently used REST APIs and therefore these APIs should be fast. So we decided to separate the crawling from the actual requests (done in [this commit](https://github.com/aixigo/PREvant/commit/61ca2533951da6ce659d82ad24e7c1368e3f98a9)).

In order to reduce the response time we decided to use [evmap](https://docs.rs/evmap/10.0.2/evmap/struct.ReadHandle.html) and use the `ReadHandle` that holds up the crawled information in a `State`. Evmap is a lock-free multi map so the hope was that the request will be very fast. 

However, `ReadHandle` does not implement `Sync` so we had to wrap it into a `Mutex` (see [here](https://github.com/aixigo/PREvant/blob/61ca2533951da6ce659d82ad24e7c1368e3f98a9/api/src/main.rs#L252)) and then we need to require a lock for each request (see [here](https://github.com/aixigo/PREvant/blob/61ca2533951da6ce659d82ad24e7c1368e3f98a9/api/src/apps/routes.rs#L56)). That eliminates the performance advantage of a lock-free data structure.

Maybe Rocket could offer some sort of state factory that would create a clone of the `ReadHandle` so that the request do not block each other. At the end of the request the state could be dropped.

```rust
#[get("/")]
fn count(map: ClonedState<ReadHandle<…>>) -> String {
   let map: ReadHandle<…> = map.into();
}
```

If Rocket supports this feature, applications could become more responsive.

**Comment by SergioBenitez** [comment]
> In order to reduce the response time we decided to use [evmap](https://docs.rs/evmap/10.0.2/evmap/struct.ReadHandle.html) and use the `ReadHandle` that holds up the crawled information in a `State`. Evmap is a lock-free multi map so the hope was that the request will be very fast.
> 
> However, `ReadHandle` does not implement `Sync` so we had to wrap it into a `Mutex` (see [here](https://github.com/aixigo/PREvant/blob/61ca2533951da6ce659d82ad24e7c1368e3f98a9/api/src/main.rs#L252)) and then we need to require a lock for each request (see [here](https://github.com/aixigo/PREvant/blob/61ca2533951da6ce659d82ad24e7c1368e3f98a9/api/src/apps/routes.rs#L56)). That eliminates the performance advantage of a lock-free data structure.

I believe you're looking for [`ReadHandleFactory`](https://docs.rs/evmap/10.0.2/evmap/struct.ReadHandleFactory.html). You should place one of these in managed state instead.

**Comment by schrieveslaach** [comment]
Thank you very much for this tip.
