### ISSUE TITLE
Uri::Absolute and Uri::Authority

### ISSUE THREAD

**Issue by dawid-nowak** [SergioBenitez/Rocket#1484]
I am trying to understand the differences here. Based on the documentation when using uri::Absolute I will be able to read authority part of the uri and split it into components: 
```
let uri = Absolute::parse("http://google.com").expect("valid URI");
assert_eq!(uri.scheme(), "http");
assert_eq!(uri.authority().unwrap().host(), "google.com");
```
The same fails when using uri::Authority: 
```
Authority::parse("http://google.com").expect_err("invalid authority");
```

My expectation is that Authority parse should not return an error here, since it is a valid authority albeit without user_info.
https://tools.ietf.org/html/rfc3986#section-3.2

**Comment by SergioBenitez** [comment]
Have you read the docs? The documentation for [`Authority`](https://api.rocket.rs/v0.4/rocket/http/uri/struct.Authority.html) details both the semantics and examples, which should make it clear that `http://google.com` is not a valid authority; the RFC section you link to does the same. The `user_info` is irrelevant; what's relevant is the scheme, that is, `http://`, which is not part of an authority. Thus, while `google.com` is a valid authority (with `host` `google.com`), `http://google.com` is not. See the [spec](https://github.com/SergioBenitez/Rocket/blob/1f1f44f336e5a172361fc1860461bb03667b1ed2/core/http/src/parse/uri/spec.txt) for fhe full grammar.

**Comment by dawid-nowak** [comment]
thanks for clarifying, 
so basically if I get it right,  uri::Authority::parse should only be used if the uri is already stripped from schema and path.

**Comment by SergioBenitez** [comment]
I think that's the wrong way to think about it. `Authority` parses an `authority` target, which by definition does not include a `scheme` or `path`. You should use `Authority` if you want to parse an `authority`, otherwise you shouldn't. If you have a request target that may or may not be an `Authority`, you should probably parse a [`Uri`](https://api.rocket.rs/v0.4/rocket/http/uri/enum.Uri.html) instead.

**Comment by dawid-nowak** [comment]
yeah, I get you, but no matter what if I parse a valid uri string that has schema or path I will get an error. So in order for  Authority::parse to succeed, I need to be pretty sure that the string contains only Authority. 

My original thinking was that Authority::parse will take any uri string and then extract the Authority section from it while stripping all other stuff, which would be handy in my use case.

**Comment by SergioBenitez** [comment]
> yeah, I get you, but no matter what if I parse a valid uri string that has schema or path I will get an error.

This isn't true. Both `Uri::parse()` and `Absolute::parse()` will parse URIs with schemes and paths. 

> My original thinking was that Authority::parse will take any uri string and then extract the Authority section from it while stripping all other stuff, which would be handy in my use case.

But this is exactly what parsing with `Uri::parse()` and then calling `.authority()` gets you.
