### ISSUE TITLE
How to perform a db health check?

### ISSUE THREAD

**Issue by wh75er** [SergioBenitez/Rocket#1487]
Hello, I'm using: rocket 0.4.6 with diesel::PgConnection and I can't figure out how to perform a database health check. I'm using #[database] attribute described in the [docs](https://api.rocket.rs/v0.4/rocket_contrib/databases/index.html). Everything works fine, but is there any way to make a health check without getting Status::ServiceUnavailable? Is it possible to check for available connection in my GET route handler e.g. '/health-check'?

At this moment, the only solution I can see is to get the default diesel::PgConnection and implement Poolable and Fairing for it with desired on_request method. But I wonder is there more convenient way to do it? Maybe override on_request method, wrap it or use method to check if connection is available in the handler(I didn't find anything in the diesel docs for poolable trait or PgConnection)?

I'll appreciate your help on this topic and I think it will be useful to mention this in [databases docs](https://api.rocket.rs/v0.4/rocket_contrib/databases/index.html)

**Comment by jebrosen** [comment]
> but is there any way to make a health check without getting Status::ServiceUnavailable

It sounds like one way to accomplish what you need is to catch the error on one route only. This is possible by using the `FromRequest` implementation on `Result` (described in more detail at <https://api.rocket.rs/v0.4/rocket/request/trait.FromRequest.html#provided-implementations>):

```rust
#[get("/health_check")]
fn health_check(connection: Result<DbConnection, ()>) {
    if connection.is_err() { /* the database failed to connect */ }
}
```

**Comment by wh75er** [comment]
@jebrosen Thank you for your answer!  It's what I need! Elegant way to make what I want. I should have read the docs attentively
