### ISSUE TITLE
Add support for MsgPack in contrib

### ISSUE THREAD

**Issue by thedrow** [SergioBenitez/Rocket#149]
MsgPack is very common de/serialization protocol that is widely being used for backend services.
Serde already provides support for MsgPack through a user contributed crate.
Can we please add it to our TODO list?

**Comment by impowski** [comment]
I guess if there will be enough people which will need this, it would be added. But since you the only one right now, you can implement it yourself for now.

**Comment by mgattozzi** [comment]
@thedrow in the meantime someone already has a msgpack implementation you can use https://github.com/3Hren/msgpack-rust

**Comment by SergioBenitez** [comment]
@thedrow Implementing this yourself is very simple. See the `JSON` implementation as an example; you essentially only need to implement [FromData](https://api.rocket.rs/rocket/data/trait.FromData.html) and [Responder](https://api.rocket.rs/rocket/response/trait.Responder.html).

How often is Message Pack used in practice? I feel that this is something that can start off as a `rocket-msgpack` crate providing a `MsgPack` type similar to the `JSON` type. If the community sees it as something that should be trivial to include via `contrib`, we can move it to `contrib` then.

**Comment by thedrow** [comment]
MsgPack is widely used in backend HTTP servers. Those servers don't communicate with browsers so there's no need for the slower and larger JSON payload.

**Comment by SergioBenitez** [comment]
I'm happy to review a PR for a `MsgPack` addition to Rocket's `contrib`.

**Comment by thedrow** [comment]
I can't promise anything. We'll see if someone beats me to it.

**Comment by shssoichiro** [comment]
I can put an implementation together, if @thedrow hasn't had a chance to.

**Comment by SergioBenitez** [comment]
@thedrow Can @shssoichiro take the lead here? Or can you commit to implementing this?

**Comment by thedrow** [comment]
@shssoichiro Go ahead :)

**Comment by SergioBenitez** [comment]
Implemented in d43678c35ea3cbaab9343faf1565638f44f94570 by @shssoichiro!
