### ISSUE TITLE
clippy: "warning: passing a unit value to a function" 

### ISSUE THREAD

**Issue by NyxCode** [SergioBenitez/Rocket#1495]
## description:
When a route returns a unit (`()`), clippy emits this warning:
```
warning: passing a unit value to a function
  --> src/rest/api/auth/mod.rs:26:8
   |
26 | pub fn logout(ctx: &App, jwt: &JWT) {
   |        ^^^^^^
   |
   = note: `#[warn(clippy::unit_arg)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unit_arg
help: move the expression in front of the call...
   |
26 | pub fn logout;
   |        ^^^^^^^
help: ...and use a unit literal instead
   |
26 | pub fn ()(ctx: &App, jwt: &JWT) {
   |    
```
adding a return type resolves this warning.
The snipped which provoked this warning is this:
```rust
#[post("/logout")]
pub fn logout(ctx: &App, jwt: &JWT) {
    ctx.jwt.invalidated_users.invalidate(jwt.user_id);
}
```

**Comment by jebrosen** [comment]
The generated code for such a route includes a pattern similar to this:

```
{
    let ___responder = hello2();
    rocket::handler::Outcome::from(__req, ___responder)
})
```

I think clippy is too eager to lint this; there's a similar case at <https://github.com/rust-lang/rust-clippy/issues/6447>. If there is a reasonable way to generate code differently to avoid the lint I'd be interested, but it looks like the code is generated this way in order to provide better error messages.

**Comment by NyxCode** [comment]
couldn't we just put a `#[allow(clippy:unit_arg)]` in there?

**Comment by jebrosen** [comment]
In principle we can (and I have opened a PR doing that). I'm not *super* happy about adding arbitrary clippy exemptions in generated code, since the exemptions may hide errors introduced in the future and this one really does look like a bug in clippy.

**Comment by SergioBenitez** [comment]
This appears to have either been resolved upstream or no longer occur with the latest codegen:

```rust
❯ cat src/main.rs                                                                                                                                                                                                                
use rocket::*;

#[get("/")]
fn index() { }

#[launch]
fn rocket() -> _ {
    rocket::build().mount("/", routes![index])
}

❯ cargo clippy                                                                                                                                                                                                                   master ●
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
```

Closing as "resolved".

**Comment by tobymurray** [comment]
Using 0.5.0-dec (rocket v0.5.0-dev (https://github.com/SergioBenitez/Rocket.git?branch=master#801e04bd))and clippy 0.1.51 (2fd73fa 2021-03-23) I see this warning on routes that accept data. Maybe it came back?

Is there anything an end user had to do to silence these?

**Comment by jebrosen** [comment]
rust-lang/rust-clippy#6447 was merged which probably fixed this, but that fix might not have made it to the `stable` releases yet. It ought to hit stable the week of May 6 (or June 17, if I miscounted).
