### ISSUE TITLE
Return Image from DynamicImage or from bytes

### ISSUE THREAD

**Issue by uucly** [SergioBenitez/Rocket#1496]
Hi,

i want to build an "on-the-fly" image scaler api. So i need to load an image from the file-system, resize it and return it to the client. So i don't want to save the image and return it via NamedFile but i want to return the DynamicImage directly.
But if i return `vec[u8]` i get no valid image and if i try to return `[u8]` i get an "does not have a constant size at compile time".
So is it currently possible to response an image which data is already in bytes available?

Thanks for your support,
Sven

**Comment by jebrosen** [comment]
> i want to build an "on-the-fly" image scaler api. So i need to load an image from the file-system, resize it and return it to the client. So i don't want to save the image and return it via NamedFile but i want to return the DynamicImage directly.

Sounds reasonable! Depending on how often the sizes might be reused it might be wise to cache them, but that is a totally separate concern of course.

> if i try to return `[u8]` i get an "does not have a constant size at compile time".

Rust functions can't directly return a `[u8]` without opting into experimental features; they have to return a `Box<[u8]>` or `&[u8]` instead. For your purposes, `Vec<u8>` is probably the most reasonable - and in the end, all of these formats would be sent to the client the same way, i.e. all the bytes directly as-is.

> But if i return `vec[u8]` i get no valid image

This *should* work, in general. If this is intended for a web browser to display, you will also need to set a `Content-Type` that corresponds with the data, for example with [`rocket::response::Content`](https://api.rocket.rs/v0.4/rocket/response/struct.Content.html). If setting a `Content-Type` still does not work, can you share some more specifics of what format `DynamicImage` is in and how you encode it to a `Vec<u8>`?

**Comment by uucly** [comment]
Hi jebrosen,

wow thanks a lot for your quick response. 
Regarding the caching, you are absolutly right. I am currently using a C++ Rest Api and in front of the webapp is a cdn. Currently i am using libvips for the image processing and this is quite fast but as you might know (as a Rust'er ;-) ) C++ is not a simple language and want to try to rebuild current app in Rust. So i want to test the speed and developmend-speed of Rust.

The use of Vec<u8> worked for me. So the problem was in front of the laptop again. My mistake was to get the pixels directly from the DynamicImage like
`let dynamic_image = image::open("pexels-artem-beliaikin-853199.jpg").expect("");`
`let image_bytes = dynamicImage.to_bytes();`

and this did'nt work. I had to use
`let mut bytes: Vec<u8> = Vec::new();`
 `dynamic_image.write_to(&mut bytes, image::ImageOutputFormat::from(ImageFormat::Jpeg)).expect("");`

Thanks for your support
