### ISSUE TITLE
Support ad-hoc query params

### ISSUE THREAD

**Issue by SergioBenitez** [SergioBenitez/Rocket#15]
Something that might be nice would be to allow query string parsing without having to use a full structure. As an example, consider a simple route to some path `/hello?name=Sergio`. Currently, you need to write code that looks like:

``` rust
struct Person {
    name: String;
}

#[get("/hello?<person>")]
fn hello(person: Person) -> ... { ... }
```

It's not particularly great to have to create a structure for just a single field. Instead, we could use ad-hoc query params. The example could look like:

``` rust
#[get("/hello?{name}")]
fn hello(name: String) -> ... { ... }
```

This is much cleaner. Several params could be matched like:

``` rust
#[get("/hello?{name,age}")]
fn hello(name: String, age: Option<u8>) -> ... { ... }
```

**Comment by LLBlumire** [comment]
Definitely a desirable feature, doing parsing with structs is obviously cleaner in a lot of cases, but for quick prototyping of methods this would be invaluable.

**Comment by a-nigredo** [comment]
I'd like to have such feature because it is very useful. e.g. in my current project we use pagination as query params like perPage and currentPage so it'd be nice to avoid creating 2 struct and just use primitive.

**Comment by kestred** [comment]
I would find this feature helpful; I actually expected it to work this way after switching from a path parameter (like `#[post(/<blah>")] fn blah(blah: String)` to a query parameter `#[post(/?<blah>")] fn blah(blah: String)`.

I notice you recommended using syntax `{blah}` for plain params vs `<blah>`, however I would expect that the latter would have worked with anything implementing FromParam.

Possibly there could be multiple varieties (like `<var>` for FromParam, `{var}` for FromData, and `[var]` for FromForm) but I don't like that solution too much because the syntax would feel somewhat arbitrary?

**Comment by SergioBenitez** [comment]
@kestred The reason I'd like to use different syntax here is to differentiate between the arity of the collection. I propose that `<...>` is always 1-ary, as it is now, while `{...}` is used for n-ary collections of parameters. Thus, `{param1, param2}` is valid while `<param1, param2>` is not.

**Comment by lholden** [comment]
This would certainly be useful. It would also be nice of the param could be converted from camel case to snake case automatically during this process.

So ex, a param comes in as MyParam but you specify fn(my_param: String). (Ex, twilio uses camel case when it submits a request)

**Comment by diggyk** [comment]
Does this also imply that it is not possible to have one function handle URLs with and without a query string? 

I have
`#[post("/events?<query>", data = "<events>")]`

But even though the struct that `query` goes into is just an `Option<String>`, it won't match `/events`

**Comment by sickHamm** [comment]
@SergioBenitez  Would consider  support multi  query params ? `#[get("/hello?<p1><p2>")] or #[get("/hello?{<p1>, <p2>}")] `

**Comment by lholden** [comment]
@sickHamm Imagine both struct p1 and p2 both having a field of the same name. Who gets the value? Do they both? Suppose Rocket could check at compile time to make sure structs p1 and p2 wouldn't conflict.

**Comment by SergioBenitez** [comment]
@sickHamm How does that differ from what's being proposed here via `path?{p1, p2}`?

**Comment by lholden** [comment]
@sickHamm Doesn't. :D

**Comment by sickHamm** [comment]
> while {...} is used for n-ary collections of parameters. Thus, {param1, param2} is valid
``` 
struct  P1 { ...};
struct P2 {...};
#[get("/hello?{p1,p2}")]
fn hello(p1: P1, p2: P2)
```
 is valid?

 In my opinion `{p1, p2}`  mean p1, p2 both "simple"  type  that `impl FromFormValue`;
`{<p1>, <p2>}` mean `<p>` is  ”complex” must  `impl FromForm`.

**Comment by sickHamm** [comment]
if <>  just mean 1-ary collections and  {} is used for n-ary collections ;  what differ `{p1}`  via `<p1>` ,
and above example  should be valid， so just a simple usage  would have  many problem  as @LLBlumire  say;

**Comment by SergioBenitez** [comment]
Accepting this and slating it for 0.5.

**Comment by SergioBenitez** [comment]
Accepted for 0.4. Tracked in #608 as part of the new query-string handling.

**Comment by Johnlon** [comment]
It is not invalid to have the same param name appear multiple times in a query string "arg=1&arg=2"
How is this handled?
Also re how that interrelates to params passed in the body - what does the spec say? is the spec is silent then what do other frameworks do?
