### ISSUE TITLE
Nightly step can be included in Quickstart documentation steps for smooth working

### ISSUE THREAD

**Issue by saki-osive** [SergioBenitez/Rocket#1504]
The steps given in the quickstart on the page https://rocket.rs/v0.4/guide/quickstart/ have a rather long process of adding a nightly build to the project for getting the project up and running :

I believe the quickstart process should be smooth and should get it up and running quickly which can be added simply with a command.

The current steps are :

```
git clone https://github.com/SergioBenitez/Rocket
cd Rocket
git checkout v0.4.6
cd examples/hello_world
cargo run
```

The proposed steps are : 

```
git clone https://github.com/SergioBenitez/Rocket
cd Rocket
git checkout v0.4.6
cd examples/hello_world
rustup override set nightly
cargo run
```
Thanks.

**Comment by jebrosen** [comment]
The page you linked says to see the [getting started](https://rocket.rs/v0.4/guide/getting-started/) page, which does explain `rustup override set nightly` and a few other options. Is that page the "long process" you mentioned?

**Comment by saki-osive** [comment]
Hi, the getting started page definitely covers all the steps needed and the Quick Start page refers to that but I believe the Quick Start page should include the :

```
rustup override set nightly
```
within the steps included within that page itself which would make the quick start process really smooth and quick from the get go.
Thanks.

**Comment by nathanielford** [comment]
I'd like to mention that the getting started page also mentions that there are a number of per-directory `rustup` [override options](https://rust-lang.github.io/rustup/overrides.html), in particular the [`rust-toolchain` file](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) which I've found to be super useful for managing multiple projects with different needs and generally useful for programming in Rust even outside of Rocket.

That said, it's probably also worth mentioning that Rocket soon plans to no longer be dependent on the `nightly` toolchain, so it might be worth skipping this for now as it's about to be moot.

**Comment by saki-osive** [comment]
Yes, that's true, the _Getting Started_ page is all good. The only thing I am suggesting is that becomes a really quick start like that, if you don't have to go to another page and get a project up and running - that's what the quick start is there for, isn't it?


> That said, it's probably also worth mentioning that Rocket soon plans to no longer be dependent on the nightly toolchain, so it might be worth skipping this for now as it's about to be moot.

When the change happens, inevitably, we'd have to make changes to the _Quick Start_ page, so a change can be made in the commands as well, then.
