### ISSUE TITLE
Incorrect warning when not utilizing secrets

### ISSUE THREAD

**Issue by ecton** [SergioBenitez/Rocket#1505]
Currently running master on Windows, but the architecture doesn't matter.

When running without the `secrets` feature enabled, [this code block](https://github.com/SergioBenitez/Rocket/blob/9671115796e42865eaebd020ac27542802027b02/core/lib/src/config/config.rs#L287-L290) prints messages to the console:

```rust
if !self.secret_key.is_provided() {
  warn!("secrets enabled without a configured `secret_key`");
  info_!("disable `secrets` feature or configure a `secret_key`");
  info_!("this becomes a {} in non-debug profiles", Paint::red("hard error").bold());
}
```

This block is not actually checking to see if the `secrets` feature is enabled, but it prints the messages regardless. The net effect is minor: messages in the log. 

I believe this block should be wrapped in a `#[cfg(feature="secrets")]` check.

**Comment by SergioBenitez** [comment]
As a side not: it's a bummer that there's no simple way to test this. I'd _really_ like to have "ui tests" for `stdout` output when running Rocket; we frequently have outdated docs and issues like this where we _want_ something to be logged but some refactor or something else causes a change that goes undetected.
