### ISSUE TITLE
HTTP Caching

### ISSUE THREAD

**Issue by thedrow** [SergioBenitez/Rocket#151]
Rocket does not currently handle Etags, If-Modified-Since idiomatically.
It'd be useful to have a responder that is able to check if the response is already cached at the client's side before proceeding to actually performing the request.

**Comment by mehcode** [comment]
I'd say this fits more into a middleware type scenario (same as CORS).

**Comment by SergioBenitez** [comment]
I agree with @mehcode here. Closing this in favor of #55.
