### ISSUE TITLE
secret_key gets zeroed when converting config to figment

### ISSUE THREAD

**Issue by dspicher** [SergioBenitez/Rocket#1510]
A `SecretKey` is always serialized as `[0; 32]`:
https://github.com/SergioBenitez/Rocket/blob/9671115796e42865eaebd020ac27542802027b02/core/lib/src/config/secret_key.rs#L170

This leads to the secret key being zeroed out when calling `rocket::figment::Figment::from(config)` because `Config` uses `Serialized` in its implementation of the `Provider` trait:
https://github.com/SergioBenitez/Rocket/blob/9671115796e42865eaebd020ac27542802027b02/core/lib/src/config/config.rs#L316

**Comment by SergioBenitez** [comment]
Safe and secure, but unintentional! On it.
