### ISSUE TITLE
`secret_key` not working when set with environment variable `ROCKET_SECRET_KEY`

### ISSUE THREAD

**Issue by SirWindfield** [SergioBenitez/Rocket#1512]
## Bug Reports

Setting the secret key using the environment variable `ROCKET_SECRET_KEY` doesn't work. I always get the error that I have no key configured, even though (from reading the docs), the above environment key should map to the secret key.

__Details__:
- Windows 10 and Ubuntu
- Rocket, revision `48fd83a`
- rustc 1.51.0-nightly (c5a96fb79 2021-01-19)

Example dotenv:
```dotenv
ROCKET_SECRET_KEY=change in production
```

Example output:
```
🔧 Configured for debug.
    => address: 127.0.0.1
    => port: 8000
    => workers: 4
    => log level: normal
    => secret key: [generated]
    => limits: forms = 32KiB
    => cli colors: true
    => keep-alive: 5s
    => tls: disabled
Warning: secrets enabled without a configured `secret_key`
    => disable `secrets` feature or configure a `secret_key`
    => this becomes a hard error in non-debug profiles
```

**Comment by jebrosen** [comment]
> Example dotenv

Rocket doesn't use dotenv, which could be the issue. If you want to use dotenv, you should add a call to [`dotenv::dotenv()`](https://docs.rs/dotenv/0.15.0/dotenv/fn.dotenv.html) somewhere before the call to `rocket::ignite()`.

**Comment by SirWindfield** [comment]
I should have clarified that I do indeed run `dotenv` myself beforehand. I know that it works as the DATABASE_URL gets populated properly.

**Comment by jebrosen** [comment]
I've been unable to reproduce this so far. I added this code before `rocket::ignite()` in a project to verify:

```rust
    dotenv::dotenv().ok();
    for (k, v) in std::env::vars() {
        eprintln!("{}={}", k, v);
    }
```

If my `.env` file contains lines like these:

```rust
ROCKET_LOG_LEVEL=debug
ROCKET_SECRET_KEY=1234567890123456789012345678901234567890123
ROCKET_SECRET_KEY=12345678901234567890123456789012345678901234
ROCKET_SECRET_KEY=
```

I get the appropriate errors or sucess indicators:
```
Error: invalid length 0, expected 44 or 88 for base64, 64 for hex
    => secret key: [provided]
```

It's strange that some of your variables are working but this one isn't. Can you check if the variable is actually set and Rocket's "missing" it, or if `dotenv` isn't actually adding that one for some reason?

**Comment by SirWindfield** [comment]
Yep, it's `dotenv`. It doesn't add keys that contain spaces in their values. I didn't know that! Sorry for the inconvenience!
