### ISSUE TITLE
the trait bound `rocket::request::FormParseError<'_>: std::error::Error` is not satisfied

### ISSUE THREAD

**Issue by OliverEvans96** [SergioBenitez/Rocket#1516]
Hello,

I'm fairly new to rust, so I hope you'll forgive me for any beginner's mistakes. I also apologize that my example is a bit complicated. It's the simplest I've been able to come up with.

Also, I'm using Rocket v0.4.3.

I have a two structs: `Person`, which is simple enough to use `#[Derive(FromForm)]`, and `DerivedPerson`, which *might* be able to be created from `Person` (it implements `TryFrom<Person>`). I'm trying to use `Form<DerivedPerson>` in my form handler by writing an implementation of `FromForm` for `DerivedPerson` which first uses `Person::from_form`, then converts to `DerivedPerson`. That way, I can determine upfront whether the `Person` given in the request is convertible to `DerivedPerson`, and rocket can reject the request if it's no good.

To be concrete, here's the code that *almost* compiles:

```rust
#![feature(proc_macro_hygiene, decl_macro)]
#[macro_use]
extern crate rocket;

use std::convert::{TryFrom, TryInto};
use std::error::Error;

use rocket::request::{Form, FormItems, FromForm};

#[derive(FromForm)]
struct Person {
    name: String,
}

#[derive(Debug)]
struct DerivedPerson {
    first_name: String,
    last_name: String,
}

#[derive(Debug)]
struct PersonParsingError {
    msg: &'static str,
}

impl std::fmt::Display for PersonParsingError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        std::fmt::Debug::fmt(self, f)
    }
}

impl Error for PersonParsingError {}

impl<'a> TryFrom<Person> for DerivedPerson {
    type Error = Box<dyn Error>;

    fn try_from(person: Person) -> Result<Self, Self::Error> {
        let names: Vec<_> = person.name.split(" ").collect();
        match names.len() {
            2 => Ok(DerivedPerson {
                first_name: names[0].to_owned(),
                last_name: names[1].to_owned(),
            }),
            _ => Err(PersonParsingError {
                msg: "Couldn't parse name",
            }
            .into()),
        }
    }
}

impl<'a> FromForm<'a> for DerivedPerson {
    type Error = Box<dyn Error>;

    fn from_form(it: &mut FormItems<'a>, strict: bool) -> Result<Self, Self::Error> {
        let person = Person::from_form(it, strict)?;
        person.try_into()
    }
}

#[post("/", data = "<derived>")]
fn index(derived: Form<DerivedPerson>) -> String {
    format!("Got derived person: {:?}", derived)
}

fn main() {
    rocket::ignite().mount("/", routes![index]).launch();
}
```

However, I get the error:
```rust
error[E0277]: the trait bound `rocket::request::FormParseError<'_>: std::error::Error` is not satisfied
  --> src/main.rs:56:51
   |
56 |         let person = Person::from_form(it, strict)?;
   |                                                   ^ the trait `std::error::Error` is not implemented for `rocket::request::FormParseError<'_>`
   |
   = note: required because of the requirements on the impl of `std::convert::From<rocket::request::FormParseError<'_>>` for `std::boxed::Box<dyn std::error::Error>`
   = note: required by `std::convert::From::from`
```

It seems reasonable that `FormParseError` should implement `std::error::Error` to be usable with `?` in a function returning `Result<Box<dyn Error>>`, which seems to be common practice. Is there any particular reason it doesn't currently?

I'd also love to hear if there's a better way to be doing what I'm trying to do.

Thanks!
Oliver

**Comment by OliverEvans96** [comment]
Actually, I found that it compiles if I just do

```rust
let person = Person::from_form(it, strict).or(Err("rocket failed"))?;
```

but I'm not actually sure why this works (`&'static str` doesn't implement `std::error::Error`, does it?) or whether I'm doing something terrible. I'd love to know.

**Comment by jebrosen** [comment]
> It seems reasonable that FormParseError should implement std::error::Error to be usable with ? in a function returning Result<Box<dyn Error>>, which seems to be common practice. Is there any particular reason it doesn't currently?

Indeed, `FormParseError` does not implement `Error`. It does look like it could implement `Error`, which would be more ergonomic for some cases. @SergioBenitez, do you know/remember why it doesn't?

> but I'm not actually sure why this works (&'static str doesn't implement std::error::Error, does it?)

The `?` operator does not actually require anything to implement `std::error::Error`. In a function that returns `Result<T, E>`, the `?` operator can be used on any `Result<U, F>` as long as `E` implements `From<F>` to convert the error to another type. In your case, it works because there is an `impl From<&str> for Box<dyn Error>`. There is also an `impl From<'a, E: Error + 'a> for Box<dyn Error + 'a>`, which is why `?` works on most error types.

**Comment by OliverEvans96** [comment]
That makes a lot of sense, thanks @jebrosen !

**Comment by SergioBenitez** [comment]
@jebrosen I don't think there's any reason. This error type is now gone, however. The new form error types _also_ does not implement std::error::Error, but I'm happy to field a PR that does.

In any case, I'm closing this out as the particular question has been answered.
