### ISSUE TITLE
Handle multiple identical query keys

### ISSUE THREAD

**Issue by dest4** [SergioBenitez/Rocket#1518]
Hello,
I'd like to handle a URL such as `/test?id=foo&id=bar` and extract `foo` and `bar`.

That question was asked in 2018 and got no response at the time 
https://github.com/SergioBenitez/Rocket/issues/15#issuecomment-386165871

I tried to build several routes like this, but got a "route collisions detected" error
```
...
    => GET /test?id=foo&id=bar (test1)
    => GET /test?id=foo (test3)
    => GET /test?id=bar (test4)
    => GET /test (test5)
Could not start server: route collisions detected
```

I tried to replace `=` with the URL encoded variant `%3D` but I get the error `segment contains invalid URI characters`.

Is there a workaround, or is this a dead end?

- Version: 0.5.0-dev
- relevant doc https://rocket.rs/master/guide/requests/#query-strings states that the last query param is extracted

**Comment by chakflying** [comment]
Tracked in #205, I believe for now you have to implement `FromParam` yourself.

**Comment by dest4** [comment]
Thank you, closing this one then
