### ISSUE TITLE
Replace src/logger.rs with slog-rs

### ISSUE THREAD

**Issue by mehcode** [SergioBenitez/Rocket#152]
https://github.com/slog-rs/slog
https://github.com/slog-rs/slog#advantages-over-log-crate

---

Thoughts? Structured logging out of the box would be a big win for Rocket. As it stands now I would need to disable Rocket logging and implement a Responder I use on every resource (should I open a tracking issue for Middleware) that logs how I want it to log.

**Comment by SergioBenitez** [comment]
There are tracking issues for both of these ideas/questions. See #21 and #55.
