### ISSUE TITLE
how to return JSON and a response status like 201

### ISSUE THREAD

**Issue by mvolkmann** [SergioBenitez/Rocket#1520]
I am using the master branch of Rocket as of January 31, 2021.
My OS is macOS.
I have a POST route that I want to return JSON and a response status of 201.
If I make the function return type be `Json` and return `Json(value)` it returns JSON and a 200 status.
Someone suggested that I could return `rocket::response::status::Created(resource_url, Some(Json(value)))` but I couldn't get that to work, maybe because I don't know what the function return type should be in that case.
See the `create_dog` function here: https://github.com/mvolkmann/rust-rocket-demo/blob/master/src/main.rs#L52

**Comment by jebrosen** [comment]
> See the create_dog function here: https://github.com/mvolkmann/rust-rocket-demo/blob/master/src/main.rs#L52

I get a "not found" - is the repository private, maybe?

> If I make the function return type be `Json` and return `Json(value)` it returns JSON and a 200 status.
Someone suggested that I could return `rocket::response::status::Created(resource_url, Some(Json(value)))` but I couldn't get that to work, maybe because I don't know what the function return type should be in that case.

The return type of that function would be `rocket::response::status::Created<Json<...>>`, if I understand this example.

**Comment by mvolkmann** [comment]
So sorry, I moved it to here today: https://github.com/mvolkmann/rust-rest/blob/83bb83e9f5a31aaa45507a4519dc97780cac316b/rocket/src/main.rs#L52

**Comment by mvolkmann** [comment]
To clarify what I’m doing, this new repo contains implementations of the same set of REST services using many frameworks, Rocket being one of them. I want it to compare favorably with the others, but currently my Rocket server doesn’t pass the tests in the benchmark directory because it doesn’t return the expected status for a successful create.

**Comment by jebrosen** [comment]
`Json<T>` is a generic type over `T`, so you had to specify which specific type to use as in `Json<Dog>`. `Created` is also a generic type; if you change the return value `Json(value)` to `Created(resource_url, Some(Json(value))`, you would similarly change the return type `Json<Dog>` to `Created<Json<Dog>>`.

Incidentally, if you don't need or want to generate and return a `Location` header you could also use [`status::Custom`](https://api.rocket.rs/v0.4/rocket/response/status/struct.Custom.html) to set the status code only. It works similarly (`-> Custom<Json<Dog>>` and `Custom(Status::Created, Json(value))`).

**Comment by mvolkmann** [comment]
Thanks! Here is what I have now:

```rust
use rocket::response::status::Created;
...
#[post("/", format = "json", data = "<json>")]
    fn create_dog(json: Json<NewDog>, state: State<MyState>) -> Created<Json<Dog>> {
        let new_dog = json.into_inner();
        let id = Uuid::new_v4().to_string();
        let dog = Dog {
            id: id.clone(),
            name: new_dog.name,
            breed: new_dog.breed,
        };
        let mut dog_map = state.dog_map.write();
        dog_map.insert(id, dog.clone());

        let url = format!("http://localhost:1234/dog/{}", id);
        Created(url, Some(Json(dog)))
    }
```

The last line that starts with `Created` gives me the error "cannot initialize a tuple struct which contains private fields".

**Comment by jebrosen** [comment]
> I am using the master branch of Rocket

Whoops, sorry I missed this. `Created` has changed a bit and lost the `Created(url, value)` constructor; you now need [`Created::new`](https://api.rocket.rs/master/rocket/response/status/struct.Created.html#method.new):

`Created::new(url).body(Json(dog))`

The return type has not changed, though.

**Comment by mvolkmann** [comment]
That worked! Thanks! Looks like the docs here need to be updated to show that syntax.
https://api.rocket.rs/v0.4/rocket/response/status/struct.Created.html
On a related note, what is the syntax to return a 204 No Content?
I tried `NoContent::new()` and `NoContent::new().body("")` but neither of those works.

**Comment by jebrosen** [comment]
You linked the 0.4 docs; the docs have already been updated for `master` here: https://api.rocket.rs/master/rocket/response/status/struct.Created.html

[`NoContent`](https://api.rocket.rs/master/rocket/response/status/struct.NoContent.html) has no fields (a "[unit struct]"(https://doc.rust-lang.org/reference/expressions/struct-expr.html#unit-struct-expression)), so to create one it's simply the struct name: `NoContent`

**Comment by mvolkmann** [comment]
Ah, I see that in order to do that I have to change the return type to be `NoContent`. That worked. Thanks!

**Comment by mvolkmann** [comment]
Is there an easy way to get the server host and port from Rocket so I can use them to form the URL that goes in the Location response header?

**Comment by jebrosen** [comment]
> Is there an easy way to get the server host and port from Rocket so I can use them to form the URL that goes in the Location response header?

*kindof*. The port can be determined by inspecting the `Config` after launch (e.g. in an `on_launch` fairing). The host that the request was sent to is in the `Host` header. However, one or both of these could be wrong if you are using a reverse proxy.

This advice still applies, though. Apparently the expectation for `Created` is that the default `Location` is the request URI, so maybe we should change `Created` to make that behavior easier to access.

>  Incidentally, if you don't need or want to generate and return a Location header you could also use status::Custom to set the status code only. It works similarly (-> Custom<Json<Dog>> and Custom(Status::Created, Json(value))).

**Comment by SergioBenitez** [comment]
Looks like this is answered!
