### ISSUE TITLE
How to stream data from a http reqwest

### ISSUE THREAD

**Issue by kdj0c** [SergioBenitez/Rocket#1521]
## Question

I'm using rocket v0.5

I'm trying to stream the result of a http reqwest, but I'm not sure how to convert the bytes_stream() from reqwest to a Stream that rocket will handle. I also tried with hyper, but I have the same issue.
In the documentation, only streaming from a file or a UnixSocket is explained.

```rust
#[macro_use]
extern crate rocket;
use reqwest;
use rocket::response::Stream;

#[get("/proxy")]
async fn proxify() -> Stream {
    let url =
        reqwest::Url::parse("https://www.rust-lang.org/static/images/rust-logo-blk.svg").unwrap();
    let client = reqwest::Client::new();
    let response = client.get(url).send().await.unwrap();

    // Try to stream the response back with Rocket
    response.bytes_stream()
}

#[rocket::main]
async fn main() {
    rocket::ignite()
        .mount("/", routes![proxify])
        .launch()
        .await
        .unwrap();
}
```

**Comment by jebrosen** [comment]
A lot of confusion probably comes the overloaded use of the word "stream":

* A *stream*, very broadly speaking, is a sequence of data of some kind - objects, bytes, etc. - where the length of the sequence is not known ahead of time by the receiving side (and sometimes not by the sending side either). You know you have reached the end of a stream when you reach a special "END" marker either in the stream itself or the transport layer, depending on the kind of stream.
  * By this definition, anything implementing `Read` or `AsyncRead` is a "stream" in some sense, or can be used as one.
* Rocket, since before 0.5, has had the `Stream` type. This type takes any `Read` and sends it in chunks of `chunk_size`
  * In 0.5 this was changed from `Read` to `AsyncRead`.
* A futures `Stream` is like an async `Iterator` - you don't know the end, and you can asynchronously get the "next value". So it also fits the definition of a "stream"
* [`reqwest::Response::bytes_stream`](https://docs.rs/reqwest/0.11.0/reqwest/struct.Response.html#method.bytes_stream) returns a `Stream<Item = Result<Bytes>>`, and [`Bytes`](https://docs.rs/bytes/1.0.1/bytes/struct.Bytes.html) is essentially a `Vec<u8>`.

The main issue here is that you have a `impl Stream<Item = Result<Bytes>>` and you need to provide Rocket an `AsyncRead`. One thing you may be able to use here is [`tokio_util::io::StreamReader`](https://docs.rs/tokio-util/0.6.3/tokio_util/io/struct.StreamReader.html).

For instance:

```rust
use tokio_util::io::StreamReader;
use bytes::Bytes;
#[get("/proxy")]
async fn proxify() -> rocket::response::Stream<StreamReader<impl rocket::futures::Stream<Item = Result<Bytes, std::io::Error>>, Bytes>> {
    let url =
        reqwest::Url::parse("https://www.rust-lang.org/static/images/rust-logo-blk.svg").unwrap();
    let client = reqwest::Client::new();
    let response = client.get(url).send().await.unwrap();

    use rocket::futures::TryStreamExt; // for map_err() call below:
    let reader = StreamReader::new(response.bytes_stream().map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e)));
    rocket::response::Stream::chunked(reader, 4096)
}
```

This example is, of course, *not* what I would call "aesthetically pleasing", mostly because of the conversion layers between `Stream<Item = Result<Bytes, Error>>` and `AsyncRead`. I can't think of any "obvious" ways to make this better off the top of my head, but there are probably a few APIs we could introduce to make this sort of thing more ergonomic.

**Comment by kdj0c** [comment]
Thanks for the solution, and the great explanation. I was a bit lost with this AsyncRead / Stream in Rust.

Just for others, you need to add this to your cargo.toml to build it:

[dependencies]
rocket = {"git" = "https://github.com/SergioBenitez/Rocket"}
reqwest = {version = "*", features=["stream"]}
tokio-util = {version="*", features=["io"]}
bytes = "*"

**Comment by rahulmr** [comment]
> A lot of confusion probably comes the overloaded use of the word "stream":
> 
> * A _stream_, very broadly speaking, is a sequence of data of some kind - objects, bytes, etc. - where the length of the sequence is not known ahead of time by the receiving side (and sometimes not by the sending side either). You know you have reached the end of a stream when you reach a special "END" marker either in the stream itself or the transport layer, depending on the kind of stream.
>   
>   * By this definition, anything implementing `Read` or `AsyncRead` is a "stream" in some sense, or can be used as one.
> * Rocket, since before 0.5, has had the `Stream` type. This type takes any `Read` and sends it in chunks of `chunk_size`
>   
>   * In 0.5 this was changed from `Read` to `AsyncRead`.
> * A futures `Stream` is like an async `Iterator` - you don't know the end, and you can asynchronously get the "next value". So it also fits the definition of a "stream"
> * [`reqwest::Response::bytes_stream`](https://docs.rs/reqwest/0.11.0/reqwest/struct.Response.html#method.bytes_stream) returns a `Stream<Item = Result<Bytes>>`, and [`Bytes`](https://docs.rs/bytes/1.0.1/bytes/struct.Bytes.html) is essentially a `Vec<u8>`.
> 
> The main issue here is that you have a `impl Stream<Item = Result<Bytes>>` and you need to provide Rocket an `AsyncRead`. One thing you may be able to use here is [`tokio_util::io::StreamReader`](https://docs.rs/tokio-util/0.6.3/tokio_util/io/struct.StreamReader.html).
> 
> For instance:
> 
> ```rust
> use tokio_util::io::StreamReader;
> use bytes::Bytes;
> #[get("/proxy")]
> async fn proxify() -> rocket::response::Stream<StreamReader<impl rocket::futures::Stream<Item = Result<Bytes, std::io::Error>>, Bytes>> {
>     let url =
>         reqwest::Url::parse("https://www.rust-lang.org/static/images/rust-logo-blk.svg").unwrap();
>     let client = reqwest::Client::new();
>     let response = client.get(url).send().await.unwrap();
> 
>     use rocket::futures::TryStreamExt; // for map_err() call below:
>     let reader = StreamReader::new(response.bytes_stream().map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e)));
>     rocket::response::Stream::chunked(reader, 4096)
> }
> ```
> 
> This example is, of course, _not_ what I would call "aesthetically pleasing", mostly because of the conversion layers between `Stream<Item = Result<Bytes, Error>>` and `AsyncRead`. I can't think of any "obvious" ways to make this better off the top of my head, but there are probably a few APIs we could introduce to make this sort of thing more ergonomic.

This example is not working for me. I am trying to find out solution for this on how to use `reqwest + rocket` or `reqwest + warp` but not getting proper help.

Following output is coming
```
error[E0412]: cannot find type `Stream` in module `rocket::response`
  --> src\main.rs:37:39
   |
37 | async fn funds() -> rocket::response::Stream<StreamReader<impl rocket::futures::Stream<Item = Result<Bytes, std::io::Error>>, Bytes>> {
   |                                       ^^^^^^ not found in `rocket::response`
   |
help: consider importing this trait
   |
8  | use futures::Stream;
   |

error[E0433]: failed to resolve: could not find `Stream` in `response`
  --> src\main.rs:49:23
   |
49 |     rocket::response::Stream::chunked(reader, 4096)
   |                       ^^^^^^ not found in `rocket::response`
   |
help: consider importing this trait
   |
8  | use futures::Stream;
   |

error[E0412]: cannot find type `Stream` in module `rocket::response`
  --> src\main.rs:53:41
   |
53 | async fn proxify() -> rocket::response::Stream<StreamReader<impl rocket::futures::Stream<Item = Result<Bytes, std::io::Error>>, Bytes>> {
   |                                         ^^^^^^ not found in `rocket::response`
   |
help: consider importing this trait
   |
8  | use futures::Stream;
   |

error[E0433]: failed to resolve: could not find `Stream` in `response`
  --> src\main.rs:61:23
   |
61 |     rocket::response::Stream::chunked(reader, 4096)
   |                       ^^^^^^ not found in `rocket::response`
   |
help: consider importing this trait
   |
8  | use futures::Stream;
   |

error[E0425]: cannot find function `ignite` in crate `rocket`
  --> src\main.rs:89:13
   |
89 |     rocket::ignite().mount("/", routes![index, funds, proxify]).launch();
   |             ^^^^^^ not found in `rocket`

warning: unused import: `reqwest::ClientBuilder`
  --> src\main.rs:10:5
   |
10 | use reqwest::ClientBuilder;
   |     ^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused import: `rocket::http::RawStr`
  --> src\main.rs:11:5
   |
11 | use rocket::http::RawStr;
   |     ^^^^^^^^^^^^^^^^^^^^

warning: unused imports: `JsonValue`, `Json`
  --> src\main.rs:12:28
   |
12 | use rocket_contrib::json::{Json, JsonValue};
   |                            ^^^^  ^^^^^^^^^

warning: unused import: `std::time::Duration`
  --> src\main.rs:13:5
   |
13 | use std::time::Duration;
   |     ^^^^^^^^^^^^^^^^^^^

warning: unused import: `std::collections::HashMap`
  --> src\main.rs:16:5
   |
16 | use std::collections::HashMap;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused `#[macro_use]` import
  --> src\main.rs:17:1
   |
17 | #[macro_use]
   | ^^^^^^^^^^^^

error[E0599]: no method named `bytes_stream` found for struct `reqwest::Response` in the current scope
  --> src\main.rs:48:45
   |
48 |     let reader = StreamReader::new(response.bytes_stream().map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e)));
   |                                             ^^^^^^^^^^^^ method not found in `reqwest::Response`

error[E0599]: no method named `bytes_stream` found for struct `reqwest::Response` in the current scope
  --> src\main.rs:60:45
   |
60 |     let reader = StreamReader::new(response.bytes_stream().map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e)));
   |                                             ^^^^^^^^^^^^ method not found in `reqwest::Response`

error[E0282]: type annotations needed
  --> src\main.rs:37:1
   |
37 | async fn funds() -> rocket::response::Stream<StreamReader<impl rocket::futures::Stream<Item = Result<Bytes, std::io::Error>>, Bytes>> {
   | ^^^^^^^^^^^^^^^^^^^^-----------------------------------------------------------------------------------------------------------------
   | |                   |
   | |                   consider giving `___responder` a type
   | cannot infer type

error[E0282]: type annotations needed
  --> src\main.rs:53:1
   |
53 | async fn proxify() -> rocket::response::Stream<StreamReader<impl rocket::futures::Stream<Item = Result<Bytes, std::io::Error>>, Bytes>> {
   | ^^^^^^^^^^^^^^^^^^^^^^-----------------------------------------------------------------------------------------------------------------
   | |                     |
   | |                     consider giving `___responder` a type
   | cannot infer type

warning: unused import: `rocket::futures::TryStreamExt`
 --> src\main.rs:8:5
  |
8 | use rocket::futures::TryStreamExt;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `rocket::futures::TryStreamExt`
  --> src\main.rs:47:9
   |
47 |     use rocket::futures::TryStreamExt; // for map_err() call below:
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `rocket::futures::TryStreamExt`
  --> src\main.rs:59:9
   |
59 |     use rocket::futures::TryStreamExt; // for map_err() call below:
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Some errors have detailed explanations: E0282, E0412, E0425, E0433, E0599.
For more information about an error, try `rustc --explain E0282`.
warning: `hello-rocket` (bin "hello-rocket") generated 9 warnings
error: could not compile `hello-rocket` due to 9 previous errors; 9 warnings emitted

```

**Comment by hyx0329** [comment]
For rocket v0.5.0-rc.2, need to use `ReaderStream` instead of `rocket::response::Stream::chunked`, and the macro `ReaderStream` is required to construct the type annotation. Still causing headaches.

**Comment by SuperCuber** [comment]
Here's updated to rc.1 :
```rs
use rocket::response::stream::ReaderStream;
use tokio_util::io::StreamReader;

#[get("/proxy?<url>")]
async fn handle_proxy(
    _user: User,
    url: String,
) -> ReaderStream![
    StreamReader<impl rocket::futures::Stream<Item = Result<Bytes, std::io::Error>>, Bytes>
] {
    let stream = reqwest::get(url).await.unwrap().bytes_stream();
    use rocket::futures::TryStreamExt; // for map_err() call below:
    let reader =
        StreamReader::new(stream.map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e)));
    ReaderStream::one(reader)
}
```

**Comment by SergioBenitez** [comment]
Another way to do this is via the `ReaderStream!` generator:

```rust
#[rocket::get("/")]
async fn stream_reqwest2() -> Result<ByteStream![Bytes], Debug<reqwest::Error>> {
    let mut bytes_stream = reqwest::get("http://google.com").await?.bytes_stream();
    Ok(ByteStream! {
        while let Some(Ok(bytes)) = bytes_stream.next().await {
            yield bytes;
        }
    })
}
```

This approach also makes it rather simple to do something with the error:

```rust
#[rocket::get("/")]
async fn stream_reqwest2() -> Result<ByteStream![Bytes], Debug<reqwest::Error>> {
    let bytes_stream = reqwest::get("http://google.com").await?.bytes_stream();
    Ok(ByteStream! {
        for await bytes in bytes_stream {
            match bytes {
                Ok(bytes) => yield bytes,
                Err(e) => {
                    eprintln!("error while streaming: {}", e);
                    break;
                }
            }
        }
    })
}
```

You can stick this in a module somewhere to get a nicer API:

```rust
mod req {
    use rocket::response::{Debug, stream::ByteStream};

    pub use bytes::Bytes;

    pub type Result<T, E = Debug<reqwest::Error>> = std::result::Result<T, E>;

    pub async fn get(url: &str) -> Result<ByteStream![Bytes]> {
        let bytes_stream = reqwest::get(url).await?.bytes_stream();
        Ok(ByteStream! {
            for await bytes in bytes_stream {
                match bytes {
                    Ok(bytes) => yield bytes,
                    Err(e) => {
                        eprintln!("error while streaming: {}", e);
                        break;
                    }
                }
            }
        })
    }
}
```

Then we can do:

```rust
use rocket::response::stream::ByteStream;

#[rocket::get("/")]
async fn stream_reqwest() -> req::Result<ByteStream![req::Bytes]> {
    req::get("http://google.com").await
}
```
