### ISSUE TITLE
Error: Template 'index' does not exist.

### ISSUE THREAD

**Issue by puffanddmx** [SergioBenitez/Rocket#1523]
i run below code. i got the error. (Template 'index' does not exist.)

## main.rs
#![feature(proc_macro_hygiene, decl_macro)]

extern crate rocket_contrib;
extern crate serde;

#[macro_use] 
extern crate rocket;
#[macro_use] 
extern crate serde_derive;

use rocket_contrib::templates::Template;

#[derive(Serialize)]
struct IndexContext {
    header: String
}

#[get("/")]
fn index() -> Template {
    let context = IndexContext {
        header: "Hello".to_string(),
    };
    Template::render("index", &context)

}

fn main() {
    rocket::ignite()
    .mount("/", routes![index])
    .attach(Template::fairing())
    .launch();
}
  
## Cargo.toml

[package]
name = "hello-rocket"
version = "0.1.0"
authors = ["root"]
edition = "2018"

[dependencies]
rocket = "0.4.6"
serde = "1.0.37"
serde_derive = "1.0.37"

[dependencies.rocket_contrib]
version = "0.4.6"
default-features = false
features = ["tera_templates"]

# index.html.tera
<html>
    <body>
        <h1>{{ header }}</h1>
    </body>
</html>

**Comment by puffanddmx** [comment]
solved

**Comment by dylanopen** [comment]
> solved

Next time, please can you explain how you solved the issue?

For me, the solution was to enable the `tera` feature in the `rocket_dyn_templates` crate.  
Hope this helps someone!
