### ISSUE TITLE
Result does not implement Responder when Error type does not implement Responder, contradicting documentation

### ISSUE THREAD

**Issue by davidv1992** [SergioBenitez/Rocket#1524]
# Description

Despite documentation (https://rocket.rs/master/guide/responses/#result) stating error type does not need to implement Responder, compiling the following code fails with message that Responder is not implemented for TestError:

```
use rocket::{get, launch, routes};

#[derive(Debug)]
enum TestError {
    A(),
    B(),
}

#[get("/")]
fn test_response() -> Result<String, TestError> {
    Err(TestError::A())
}

#[launch]
fn rocket() -> rocket::Rocket {
    rocket::ignite().mount("/", routes![test_response])
}

```

# Additional information:
Rocket version: master
Cargo version: 1.49.0
Rustc version: 1.49.0
OS: Ubuntu 20.04

**Comment by jebrosen** [comment]
Is this fixed by #1514?

**Comment by davidv1992** [comment]
Yes, that seems to remove the contradictory information from the documentation.

On a slightly tangential note, it might be useful to document how to achieve the behaviour (500 + log of error) of the old responder in the new situation, as that is not immediately clear from the documentation currently, and is fairly useful behaviour. (at least better than the behaviour on panic, which is to drop the connection without a response at all)

**Comment by wezm** [comment]
@davidv1992 I think this can be replicated with the [Debug](https://api.rocket.rs/master/rocket/response/struct.Debug.html) responder. Something like:

```rust
use rocket::{get, launch, routes};

#[derive(Debug)]
enum TestError {
    A(),
    B(),
}

#[get("/")]
fn test_response() -> Result<String, Debug<TestError>> { // <- note Debug
    Err(Debug(TestError::A()))
}

#[launch]
fn rocket() -> rocket::Rocket {
    rocket::ignite().mount("/", routes![test_response])
}
```

**Comment by bamilab** [comment]
Hmmm, what was the reasoning behind removing this Responder implementation?

**Comment by SergioBenitez** [comment]
@bamilab It is incompatible with Rust stable, and arguably, encourages suboptimal returning of semantically meaningless types.

Looks like this was fixed in the docs. Closing out.
