### ISSUE TITLE
Serve static files from multiple directories

### ISSUE THREAD

**Issue by Iqon** [SergioBenitez/Rocket#1526]
## Questions

Hello, I have a question (or if not possible a feature request).

Is it possible to serve static files from multiple directories behind the same endpoint. E.g. I want to serve 
- the directory `./spa/`
- the directory `./css/`
- the directory `./images/`
- All from the same URL `http://url/static/

In `express.js` (see [Documentation](http://expressjs.com/en/resources/middleware/serve-static.html) section _Multiple Roots_) you can configure multiple directories using their fallthrough mechanism:

```js
app.use('/static', express.static('./css'));
app.use('/static', express.static('./spa'));
app.use('/static', express.static('./images'));
```

In `rocket.rs` I am not allowed to configure multiple endpoints because of route collisions. So the following will fail:

```rs
server.mount("/static", StaticFiles::from("./spa"))
      .mount("/static", StaticFiles::from("./css"))
      .mount("/static", StaticFiles::from("./images"))
```

It would be great if `StatifFiles::from` of `StaticFiles::new` would accept a vector of directories:

```rs
server.mount("/static", StaticFiles::new(vec![
  "./spa",
  "./css",
  "./images"])
)
```

Any questions _must_ include:

  1. The version of Rocket this question is based on, if any.
```toml
rocket = "0.4.6"
[dependencies.rocket_contrib]
version = "0.4.6"
default-features = false
features = ["handlebars_templates", "json", "serve"]
```

  2. What steps you've taken to answer the question yourself.
I've done online research and looked in the docs, but couldn't find anything.

  3. What documentation you believe should include an answer to this question.
Either a link to an example, an example, or an explanation on how to achieve this. 

Thanks, and great work! I really enjoy using Rocket.rs.

**Comment by jebrosen** [comment]
> In rocket.rs I am not allowed to configure multiple endpoints because of route collisions. So the following will fail:

The error message for this should indicate that you can change the [*rank*](https://rocket.rs/v0.4/guide/requests/#forwarding) to specify which one should be tried first. For `StaticFiles`, this is exposed in the [`StaticFiles::rank`](https://api.rocket.rs/v0.4/rocket_contrib/serve/struct.StaticFiles.html#method.rank) method. For example:

```rust
server.mount("/static", StaticFiles::from("./spa").rank(1))
      .mount("/static", StaticFiles::from("./css").rank(2))
      .mount("/static", StaticFiles::from("./images").rank(3))
```

**Comment by Iqon** [comment]
@jebrosen Thanks for the comment. Somehow I missed that. I am going to close this issue.

**Comment by Iqon** [comment]
Sorry to reopen the issue. I have tried to set this up for a while now. I can't get the ranks to work. The first rank will respond with 404 if the file does not exist. So the second rank is not able to respond and deliver the file. 

I've created an example project: https://github.com/Iqon/RocketStaticFilesFallthroug

A small example that should serve the content of two folders behind `/static`. So both URLs `localhost:8000/static/file1.txt` and `localhost:8000/static/file2.txt` should work.

Run `cargo test` to see if both endpoints work.

**Comment by jebrosen** [comment]
Oh, shoot. That is issue #1036; I misremembered and thought the fix had actually been backported to 0.4.x.

**Comment by SergioBenitez** [comment]
@jebrosen If you believe this is backwards compatible, please feel free to backport to 0.4.

**Comment by SergioBenitez** [comment]
I'm closing this because this is resolved on master. I'll leave it up to @jebrosen or someone else to backport this to 0.4 if desired.
