### ISSUE TITLE
Update Postgres dependency

### ISSUE THREAD

**Issue by knutin** [SergioBenitez/Rocket#1527]
Hello team,

Do you have a plan/desire to update the `postgres` crate? The `0.19.0` release uses tokio 1.0.

Happy to submit a PR, but I think it also means upgrading `r2d2_postgres` and I'm unsure about the implications.

Best
Knut

**Comment by jebrosen** [comment]
Yes, we should make sure to do this before 0.5. FWIW it shouldn't matter *too* much which tokio release it uses aside from reducing extraneous dependencies on older versions, since this refers to the non-`async` `postgres` library that creates its own separate runtime.
