### ISSUE TITLE
Templates not found?

### ISSUE THREAD

**Issue by mmstick** [SergioBenitez/Rocket#153]
This struct is listed in the website's guide, but it is [missing from documentation](https://docs.rs/rocket_contrib/0.1.6/rocket_contrib/struct.Template.html), and a compiler error is generated if you try to import it. Was it moved? Removed? Replaced?

**Comment by SergioBenitez** [comment]
Please don't read documentation for Rocket on docs.rs. The service makes no effort to allow customized documentation building. As a result, the Rocket docs are broken in many places.

Please use https://api.rocket.rs instead.
