### ISSUE TITLE
Discussions Tab

### ISSUE THREAD

**Issue by atahabaki** [SergioBenitez/Rocket#1530]
Hi, may I suggest something that may help for newbies? Opening the discussions tab for this repository? Sorry for making an issue for this but, the "Discussions" tab would be very useful for not much important stuff, like helps, guides, and etc. And I must say that Rocket is awesome!.. Thanks for this awesome repo. Good luck!..

**Comment by SergioBenitez** [comment]
The plan is indeed to open up discussions on the release of 0.5! I'll close this issue in an attempt at keeping the issues tab tidy, but know that your request has been headed. :)
