### ISSUE TITLE
Translation of documentation into Ukrainian

### ISSUE THREAD

**Issue by faramozzayw** [SergioBenitez/Rocket#1533]
Hi, I want to translate documentation for `rocket` into Ukrainian. It's possible? How can I do this in the best way?

**Comment by jebrosen** [comment]
There are several different parts that could be translated; which parts were you thinking of?

* The contents of the main site, especially the guide, is stored as markdown files in the repository (v0.4: https://github.com/SergioBenitez/Rocket/tree/v0.4/site).
* The source code for the main site layout (https://rocket.rs) is not yet published anywhere to my knowledge.
* The API documentation (v0.4: https://api.rocket.rs/v0.4/rocket/) is auto-generated via `rustdoc` from the code. This is probably much more difficult to translate, and I don't know if `docs.rs` or similar already has any support for hosting alternative languages.

There is also the question of hosting the translated documentation somewhere, explaining where to find that documentation, and keeping the translations updated. I don't believe we have the bandwidth to keep on top of translations at this time, but it's a good problem to be thinking about.

**Comment by faramozzayw** [comment]
Hmm, thinking about translating the content of the main site.

> hosting the translated documentation

Depends on. If there is a way to host the translation as part of the main site, that would be great, otherwise things like [Vercel](http://vercel.com/), [Netlify](https://www.netlify.com/) or [Github Pages](https://pages.github.com/) can be used.

> where to find that documentation

The first option is to add a select box to the navbar with translation options where the default is English.  And the translation will be available, for instance, at `https://rocket.rs/uk/overview`. But this option requires changing the source code for the main site.

Another option is to add a section to the [Guide/Index](https://github.com/SergioBenitez/Rocket/blob/v0.4/site/guide/index.md) page, which will be called `Translation` and will store a list of links to different translations.

**Note**: without the source code of the main site, it will be difficult to make the same design for different translations. So it seems to me that using mdbook for a more familiar design is the best way out in this situation.

> keeping the translations updated

Well, I cannot guarantee long-term support (e.g. a year or more), but I am thinking of creating an organization or something similar with the main goal of translating (and keeping the translations updated) the Rust libraries into Ukrainian.

**Comment by SergioBenitez** [comment]
> * The source code for the main site layout (https://rocket.rs) is not yet published anywhere to my knowledge.

While the HTML/CSS/etc. are not published anywhere, all of the text is (_should be_) available at https://github.com/SergioBenitez/Rocket/tree/master/site. For instance, the `index.toml` file contains all of the text for the index.

@faramozzayw I'd love translations. I'd love to make Rocket accessible to as many people as possible. I'd be happy to modify the site to make it easy to switch between available languages.

My concern, as you allude to, is maintaining the documentation. There's quite a bit of it, and it's constantly being improved. Outdated documentation can be very confusing, and reading outdated documentation from the official source doubly so. I'm curious how other projects handle it. From a cursory search, [Rails doesn't host official translations](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#translating-rails-guides), simply pointing users to other repositories, for exactly this reason. [Rust itself seems to do the same](https://doc.rust-lang.org/book/appendix-06-translation.html). [Django uses Transifex](https://docs.djangoproject.com/en/dev/internals/contributing/localizing/#documentation) and rolls out partial docs when translations aren't complete, like on [this page](https://docs.djangoproject.com/ko/3.1/intro/reusable-apps/#reusability-matters). I'm not sure what ASP.net does, but they [also have partial translations](https://docs.microsoft.com/fr-fr/aspnet/core/getting-started/?view=aspnetcore-5.0).

So it seams like a good start, if any, is to translate the docs at your own leisure. Once you arrive at a comfortable point of "completion", we can explore integration options or tools like Transifex/Lokalise/LingoHub/CrowdId.

**Comment by faramozzayw** [comment]
Got it, I'll start translating this week :)

**Comment by atahabaki** [comment]
> So it seams like a good start, if any, is to translate the docs at your own leisure. Once you arrive at a comfortable point of "completion", we can explore integration options or tools like Transifex/Lokalise/LingoHub/CrowdIn.

Cool, I'll also translate the [rocket.rs](https://rocket.rs) website to Turkish. :rocket:
Whenever I got time, I'll translate the docs too...

**Comment by LastGenius-edu** [comment]
Hi @faramozzayw , do you need any help with this?

**Comment by SergioBenitez** [comment]
Closing this for now; we need a more reasonable, actionable plan for translation.

**Comment by sertceps** [comment]
Hi! What is the current situation? If I want to contribute translated documents, is there a feasible channel? Thanks!
