### ISSUE TITLE
Allow setting an arbitrary default value for derived FromForm fields

### ISSUE THREAD

**Issue by ThouCheese** [SergioBenitez/Rocket#1536]
When deriving FromForm for a struct, it is sometimes nice to be able to provide a one-off default value that is used only in this case. For example, `FromFormValue::default` is not implemented for `String`, but a default value might still be desired.

```rust
#[derive(FromForm)]
struct Form {
    #[form(default)]
    value: String, // uses the Default::default impl
    #[form(default = def_username)]
    username: String, // uses the Default::default impl
    #[form(default = Vec::new)]
    fields: Vec<i32>,
}

fn def_username() -> String {
    "anonymous".to_string()
}
```

It may be useful to reimplement the full set of field attributes as specified in https://serde.rs/field-attrs.html (that is, only the fields that are relevant for Deserialize), so that people can switch from JSON using serde::Deserialize to forms using FromForm as a drop-in replacement.

Furthermore, it is sometimes desired to have the FromForm implementation fail even when a type has a `FromFormValue::default` implemenation.

```rust
#[derive(FromForm)]
struct Form {
    #[form(default = "save_humanity")]
    save_humanity: bool, // should default to true
}

fn save_humanity() -> bool { true }
```

**Comment by SergioBenitez** [comment]
This should now be straightforward to implement. I recommend a mechanism similar to that of `validate`:

```rust
#[derive(FromForm)]
struct Form<'r> {
    #[field(default = "this")]
    value: String,
    #[field(default = "this".to_uppercase())]
    value: &'r str,
    #[field(default = or_this())]
    value: &'r str,
}
```

Basically, allow any expression, call `.into()` on it, force the value to be `T` where `T` is the form field:

```rust
let default: #T = #expr;
```

> Furthermore, it is sometimes desired to have the FromForm implementation fail even when a type has a `FromFormValue::default` implemenation.

We could either change the expression return `Option<T>`, sacrificing the `.into()` niceness, so you could do:

```rust
#[derive(FromForm)]
struct Form {
    #[field(default = None)]
    boolean: bool,
}
```

Or we could change the `Strict` guard to disallow defaults:

```rust
#[derive(FromForm)]
struct Form {
    boolean: Strict<bool>,
}
```

Or we could add a new form guard that disallows defaults:

```rust
#[derive(FromForm)]
struct Form {
    boolean: Exists<bool>,
}
```

Or some special syntax in the field:

```rust
#[derive(FromForm)]
struct Form {
    #[field(default = _)]
    boolean: bool,
}
```

I like the idea of `Strict` paying double-duty. It feels right, too, given the name.

**Comment by ThouCheese** [comment]
I agree that the `Strict` approach is the nicest here, also because it relies on the type system more than macro magic. Do you think it is a good idea I start implementing this, or are the underlying mechanisms still in too much flux?

**Comment by SergioBenitez** [comment]
> I agree that the `Strict` approach is the nicest here, also because it relies on the type system more than macro magic. Do you think it is a good idea I start implementing this, or are the underlying mechanisms still in too much flux?

Please go ahead. The forms revamp is complete. I've implement the `strict` changes already, however.

**Comment by ThouCheese** [comment]
Not completely within the scope of this issue, but perhaps related: we could also add support for adding validation attributes like `#[field(check = "lt(5)")]` or transformation attributes like `#[field(transform = "String::trim")]`. Is this something that you are interested in or that has a previous discussion history?

**Comment by SergioBenitez** [comment]
> Not completely within the scope of this issue, but perhaps related: we could also add support for adding validation attributes like `#[field(check = "lt(5)")]`

There's already `validate`. Your example would be `#[field(validate = range(..5)]`.

> or transformation attributes like `#[field(transform = "String::trim")]`. Is this something that you are interested in or that has a previous discussion history?

I don't quite see the utility in this one. The transform would be limited to things that return the same type. It seems that you'd either simply want to validate that it looks the way you want it to, write a form guard that does the transformation, or apply the transformation in the handler. Are there some good uses cases for this that you can think of?

**Comment by ThouCheese** [comment]
For me such a use case is input normalization that needs to happen really often, for example when taking emails from the request, you always want to cast those emails to lower case and trim them, so that `me@host.com` and `Me@host.com ` end up being treated as the same account.

> The transform would be limited to things that return the same type. 

We could allow the transform to be of the type` T -> impl Into<T>`, which would allow users to use `String::trim`. The drawback of this is that those `.into()` calls can be very expensive (such as in the case of &str into String).

**Comment by SergioBenitez** [comment]
I'd suggest an `Email` type that does what you need, more likely lazily, on `Display` or otherwise. A `FromFormField` implementation would be straightforward. This is both more performant, more obvious, more reusable, and in my opinion, easier to use overall.

**Comment by SergioBenitez** [comment]
> We could allow the transform to be of the type `T -> impl Into<T>`, and then call that into implementation to convert the result back to the correct type. This would allow users to use `String::trim`. The drawback of this is that those `.into()` calls can be very expensive (such as in the case of &str into String).

To be clear, the `trim()` case is actually okay: the form struct field could be an `&str`, and `trim()` returns an `&str` with the same lifetime. The bigger issue would be `to_lowercase()`, which allocates, forcing you to use a `String` in the form struct, allocating once, and a second `String` and allocation to call `to_lowercase()`.

**Comment by ThouCheese** [comment]
> I'd suggest an Email type that does what you need, more likely lazily, on Display or otherwise. A FromFormField implementation would be straightforward. This is both more performant, more obvious, more reusable, and in my opinion, easier to use overall.

Fair enough! Will leave that out then.

**Comment by ThouCheese** [comment]
Since this is marked for the 0.6 release, is there a branch that I should create a PR into?

**Comment by SergioBenitez** [comment]
No, all development, except backports, happens on `master`.

**Comment by somehowchris** [comment]
These things sound awesome and are the excact things I am looking for right now. As of the title you are looking into this for FromForm fields but how about Json inputs?

**Comment by SergioBenitez** [comment]
> These things sound awesome and are the excact things I am looking for right now. As of the title you are looking into this for FromForm fields but how about Json inputs?

Json support works through Serde which already has support for overriding defaults.

**Comment by somehowchris** [comment]
> > These things sound awesome and are the excact things I am looking for right now. As of the title you are looking into this for FromForm fields but how about Json inputs?
> 
> Json support works through Serde which already has support for overriding defaults.
Ok, well just seems like an inconsistent way of handling things. How about the validation part? Which is already done and basically a similar thing as you already mentioned but also only available for forms as it seems

**Comment by ThouCheese** [comment]
I'm looking at the grammar now:

```txt
field := name? validate*

name := 'name' '=' name_val
name_val :=  '"' FIELD_NAME '"'
         | 'uncased(' '"' FIELD_NAME '"' ')

validate := 'validate' '=' EXPR

FIELD_NAME := valid field name, according to the HTML5 spec
EXPR := valid expression, as defined by Rust
```

This seems to suggest that the "name =" part must come before any validators. Yet if I look at the macros, it seems that it will accept any order, so the macros accept a superset of this syntax. Am I being overly pedantic or wrong or is this something you'd like to see fixed? Also, should the name and validate not be comma-separated? That is: `field := name?, validate,*`
