### ISSUE TITLE
Changelog uses wrong year

### ISSUE THREAD

**Issue by adrian5** [SergioBenitez/Rocket#1537]
[Version 0.4.7 (Feb 09, 2020)](https://github.com/SergioBenitez/Rocket/blob/v0.4.7/CHANGELOG.md) should be 2021 I reckon :wink:

Happens to me too, it feels like the new year _should_ be 2020. Not sure if Covid-19 is to blame.

**Comment by SergioBenitez** [comment]
Good catch! Fixed. :)
