### ISSUE TITLE
Update to serde 0.9.0

### ISSUE THREAD

**Issue by dtolnay** [SergioBenitez/Rocket#154]
From looking through the Cargo.toml files it looks like this requires `handlebars` to update first.

- [x] https://github.com/sunng87/handlebars-rust/issues/134
- [x] https://github.com/Keats/tera/issues/119

Here are the release notes: https://github.com/serde-rs/serde/releases/tag/v0.9.0

**Comment by SergioBenitez** [comment]
That's right. Waiting on Handlebars and Tera for this one.

**Comment by sunng87** [comment]
Handlebars 0.25 is ready for serde 0.9

**Comment by dtolnay** [comment]
Tera has a PR ready to work against: https://github.com/Keats/tera/pull/123
