### ISSUE TITLE
StripPrefixError while updating Rocket to latest version

### ISSUE THREAD

**Issue by sopheaksem1993** [SergioBenitez/Rocket#1541]
Hi, Dear Rocket team

Nowadays I update rocket version to latest (commit: e4c2324bab3141355f175e1ad11a6ed7cb5af234).
##  Here is code part for this.
  rocket = { git = "https://github.com/SergioBenitez/Rocket.git", features = ["secrets"], 
   rev="e4c2324bab3141355f175e1ad11a6ed7cb5af234"}
## Bug Reports:
 When I run project, it throws error like below. (Before I update to latest version, it works great without any error).
    thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: StripPrefixError(())', 
   /home/sem/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/e4c2324/contrib/lib/src/templates/context.rs:72:44
   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', /home/sem/.cargo/git/checkouts/rocket- 
  8bf16d9ca7e90bdc/e4c2324/core/lib/src/rocket.rs:310:27

- Why would I get this kind error ?
- What is the solution to solve this error ?
- 
Thanks in advance.

**Comment by SergioBenitez** [comment]
This is impossible to debug without seeing any relevant code. Can you post the backtrace from `RUST_BACKTRACE=1` and show how you initialize templates? What is your Rocket.toml? What does Rocket print while initializing?

This error occurs because somehow the glob `root/**/*` returned a path that does not contain `root`.

**Comment by sopheaksem1993** [comment]
Thanks for your quick reply and help.
I resolved this issue by handling the template directory path.
Best regards.

**Comment by SergioBenitez** [comment]
This function is not expected to panic, ever. Can you describe what you were doing before and what you changed to resolve this issue?
