### ISSUE TITLE
Documentation for deploying app to cloud

### ISSUE THREAD

**Issue by ayyagari-dalalstreet** [SergioBenitez/Rocket#1542]
Hello Team, 

I am super confused to use the framework for the development of my application as there is no proper documentation of how to deploy the app on the public clouds like AWS, Digital Ocean etc...

It will be of great help to me if there is a proper documentation put up in the website to that it will be easy for everyone to know how to deploy the app as well.

**Comment by ayyagari-dalalstreet** [comment]
Any blog suggestions will also be appreciated

**Comment by SergioBenitez** [comment]
See #171.
