### ISSUE TITLE
Documentation for Rocket master requires a minor change

### ISSUE THREAD

**Issue by SaadiSave** [SergioBenitez/Rocket#1546]
In the documentation for [Rocket](https://rocket.rs/master/guide/getting-started/), this is written in the getting started section:
```toml
[dependencies]
rocket = "0.5.0-dev"
```
However, doing this fails, and crates.io says that no such version exists. Is this intentional, and if so, why is this segment included in the documentation? Or is it a bug?

**Comment by SaadiSave** [comment]
Never mind, I found the solution at #1476.
However, shouldn't the documentation include this instead:
```toml
rocket = { git = "https://github.com/SergioBenitez/Rocket", version = "0.5.0-dev" }
```

**Comment by SergioBenitez** [comment]
Yes, but we given that we automate this change based on the Cargo version string, I don't think fixing this is worth the effort. What's more, it's a nice speed bump to using Rocket from GitHub, which should generally be avoided as we can break your code at any time.
