### ISSUE TITLE
uri! Macro doesn't provide correct path to routes mounted to non "/" origin path

### ISSUE THREAD

**Issue by k-g** [SergioBenitez/Rocket#1553]
Using Rocket 0.4.7:

I have a route mounted at the origin `/cart`:

```
...
.mount("/cart",
               routes![
                routes::cart::list_cart,
                routes::cart::add_to_cart,

               ])
...
```

And I have a basic view and route defined:
```
#[get("/")]
pub fn list_cart(connection: db::Connection, session: session::Session) -> Template  {

    #[derive(Serialize)]
    struct CartContext{
        session_data: session::StoreSession
    }
    let context = CartContext{session_data: session.tap(|session_data|{ session_data.clone() })};

    Template::render("cart/list", &context)
}
```

In another view, I want to redirect to `list_cart` so I do:

```
let redirect_url = uri!(list_cart);
info!("Successfully added item to cart, redirecting to: {}", &redirect_url.to_string());
return Ok(Redirect::to(redirect_url));
```

What I expect to be returned as the uri: 
```
/cart/
```

But what is returned:
```
/
```

My interpretation is that instead of redirecting to the correct path as mounted in Rocket (which should be `/cart/`), the URL returned is `/` which is the index of the side, and not what I think makes the most sense.

I couldn't find documentation covering this issue so I think it may be a bug.

**Comment by SergioBenitez** [comment]
This is covered in the guide and API docs. See https://rocket.rs/v0.4/guide/responses/#typed-uris, for instance. You need to supply the mount point manually; `uri!("/mount", route)`. It would be nice to _not_ have to do this, but this appears to be an impossibility with the current design.

**Comment by k-g** [comment]
Hey thanks for pointing that out! Maybe this could be a feature request instead
