### ISSUE TITLE
Resolve `unused_extern_crates` 2018 idioms lint

### ISSUE THREAD

**Issue by jebrosen** [SergioBenitez/Rocket#1554]
#1549 (fixing the `elided_lifetimes_in_paths` lint) surfaced a new warning in user code that opts into `rust_2018_idioms`: `extern crate rocket`, emitted as part of the support for the `uri!` macro, is a no-op in the 2018 edition. I am opening this issue to document it as a known problem for anyone who is opting into the `rust_2018_idioms` lint group.

---

IIRC the original reason that `extern crate rocket;` is used here was to guard against e.g. `mod rocket { }` in user code. This particular syntax works in both 2015 and 2018 editions; however, this might not be the best solution anymore:

* 2015 crates might no longer be able to use rocket's macros anyway, since they emit `async` and `await`. So there would be no benefit to using 2015-compatible syntax.
* There may be other syntax, e.g. with `use`, that works unambiguously in this location, in both editions, starting in some undetermined version of the compiler. I don't remember all of which changes were made and/or backported to the 2015 edition to answer this off the top of my head.
* "edition hygiene" might help solve this or be intended to solve this. In other words, Rust syntax and lints are intended to be applied based on the edition of the crate the code came from, but I am still unsure what kinds of macros this applies to and whether there are missing features or bugs here.

If it is still useful for compatibility and is the only way, we can simply add an `#[allow(unused_extern_crates)]` to silence the warning instead. But it would be nice if this could be resolved in a way that is idiomatic in both editions.

**Comment by SergioBenitez** [comment]
I believe these `extern crate`s are simple holdbacks from when the macro was a `decl_macro`, where they would have been required. We refer to `std` and `rocket` item elsewhere directly, so simply removing these should result in no issues.
