### ISSUE TITLE
Allow specifing rustls ServerConfig via Rocket API

### ISSUE THREAD

**Issue by BinAlyan** [SergioBenitez/Rocket#1556]
I am going to implement this feature because I need to change the default configuration. I can try to make a pull request but I am not sure if this feature would be accepted. I also have never done any pull request before. I am interested in enforcing protocol version as TLS 1.3 and cipher suite as AES_256_GCM_SHA384.

**Comment by SergioBenitez** [comment]
Sure! This should be a relatively straightforward change in https://github.com/SergioBenitez/Rocket/blob/fbf0aa824d2a2bb36b53ba984a87b47cb7361d92/core/lib/src/config/tls.rs. Looking forward to your PR! Please be sure to include tests!

**Comment by SergioBenitez** [comment]
This was handled in https://github.com/SergioBenitez/Rocket/commit/dd722cdcfcdf9fc1217c4763009cdd374173a2a8.
