### ISSUE TITLE
Query missing in git master

### ISSUE THREAD

**Issue by MikailBag** [SergioBenitez/Rocket#1557]
I can find `Query` in neither [published docs](https://api.rocket.rs/master/rocket/request/trait.FromQuery.html?search=Query) (I get 404 when clicking on `Query` search result) nor locally built documentation (I checked out `fbf0aa824d2a2bb36b53ba984a87b47cb7361d92` and executed `cargo doc --open`, then got no search results for `Query`).

Was it removed in favor of `Form`?

**Comment by MikailBag** [comment]
Ah, it seems it was simply renamed to `Segments`

**Comment by SergioBenitez** [comment]
Indeed, `Query` is gone! Please see the updating query string handling docs: https://rocket.rs/master/guide/requests/#query-strings

**Comment by fstephany** [comment]
Yep, it seems that it was part of the big set of changes from today ;) 

Isn't this the one you're looking for: https://api.rocket.rs/master/rocket/http/uri/enum.Query.html ?
You can access the values with [`query_values()`](https://api.rocket.rs/master/rocket/request/struct.Request.html#method.query_value) on the request.
