### ISSUE TITLE
the trait `Responder<'_>` is not implemented for `impl Future`

### ISSUE THREAD

**Issue by mikeximu** [SergioBenitez/Rocket#1562]
```
src
   -controllers
       #[post("/login")]
       pub async fn login() ->&'static str {
            "hello"
     }

```
error is :
     pub async fn login() ->&'static str {
    |                        ^^^^^^^^^^^^ the trait `Responder<'_>` is not implemented for `impl Future`

**Comment by mikeximu** [comment]
Is there a project that can be used for reference？？？？？？？ 
project ：mvc

action:
post multipart/form-data
post application/x-www-form-urlencoded
post application/json 
get

**Comment by SergioBenitez** [comment]
Please read our issue.md on how to open a useful issue.
