### ISSUE TITLE
Contributions labels

### ISSUE THREAD

**Issue by impowski** [SergioBenitez/Rocket#157]
It would be nice to have a more understandable way of handling project contributions. 

Some issues which we might take on with different labels like `easy`, `less-easy`, `hard`. And a label if someone already took an issue like `assigned`. It would help a lot, because someone might come and not see any real issues which he might take and do, and you @SergioBenitez could split some work which you don't want to do yourself, like tests and etc.

**Comment by SergioBenitez** [comment]
At present, there's the `help wanted` label for issues that are appropriate for contributions. We don't have difficulty labels, and I'd rather keep it that way. I don't know what someone might find easy or hard, and I don't want to guess how easy or hard something might be. I feel that a descriptive title and accurate description should suffice.

Are you aware of the `help wanted` label? GitHub already has assigning, so a label feels redundant.

**Comment by impowski** [comment]
Maybe. Having a more issues with `help wanted` would be cool:)

**Comment by SergioBenitez** [comment]
@impowski Agreed. It's definitely a goal, but at this point, many of the wanted changes are to the core of Rocket, which can be difficult for outside contributors to make, especially as the project is still young. I think as time goes on, you'll see more and more issues tagged with `help wanted`. :)

**Comment by impowski** [comment]
@SergioBenitez I understand. But what do you think about mentoring for those issues? I like how Servo does it, you can basically have a zero knowledge of the project itself and they guide you a little and you figure it out by yorself afterwards.

**Comment by SergioBenitez** [comment]
@impowski I'm okay with that, as long as the issue is somewhat involved. Otherwise I'd advocate for someone simply jumping in and exploring. :)

**Comment by SergioBenitez** [comment]
I'm going to decline this request, for now. As Rocket gets bigger and has more community contributions, this might become essential. Thank you for bringing this up!
