### ISSUE TITLE
State containing generics in handlers

### ISSUE THREAD

**Issue by davxy** [SergioBenitez/Rocket#1570]
Hi there,

I'm having some troubles using generics in the `State` managed by Rocket to be passed to the handlers.

For example, given that I have a trait `Db` that is `Sync + Send + 'static`, I would like to define a `post` handler like this:

```rust
struct MyData<T: Db> {
     db: T
}

#[post("/submit", format = "application/octet-stream", data = "<buf>")]
fn submit<T: Db>(state: State<MyData<T>>, buf: Vec<u8>) -> Vec<u8> {
...
}

```
The compiler gives me the following error:

```
error[E0412]: cannot find type `D` in this scope
   --> src/rest_svc.rs:116:43
    |
116 | fn submit<D: Db>(state: State<MyData<D>>, buf: Vec<u8>) -> Vec<u8> {
    |                                                                    ^ help: a trait with a similar name exists: `Db`
    | 
```

Is this a limitation of the macro system to construct the handler (i.e. don't use generics).
Is there a workaround?

Thank you for your work

**Comment by SergioBenitez** [comment]
I believe this is #408. See the discussion there for why a generic route doesn't make sense, but a close approximation might, with effort.

**Comment by SergioBenitez** [comment]
Closed as duplicate.
