### ISSUE TITLE
On master branch rocket_contrib, FromRequest not implemented for Json<T>

### ISSUE THREAD

**Issue by DanielJoyce** [SergioBenitez/Rocket#1572]
> the trait bound `rocket_contrib::json::Json<CreateProjectFolderRequest>: FromRequest<'_, '_>` is not satisfied
> the trait `FromRequest<'_, '_>` is not implemented for `rocket_contrib::json::Json<CreateProjectFolderRequest>`

```rust 
use rocket_contrib::json::Json;

#[post("/users", format = "json", data = "<user>")]
fn new_user(user: Json<User>) {
    /* ... */
}
```

This won't work from the docs.

**Comment by DanielJoyce** [comment]
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket", version = "0.5.0-dev", features = ["uuid"] }

json is a default feature, and works in all other ways. It's just the data guard doesn't work

**Comment by DanielJoyce** [comment]
Looking at the source it appears FromRequest is missing.

**Comment by SergioBenitez** [comment]
`Json` is not and has never been a request guard, and this does not implement `FromRequest`. It is a data guard, however, and does implement `FromData`. This is true in `master`. Many, many tests check for this.

I suspect you have a typo in your program or are not using the `data` route argument.

**Comment by DanielJoyce** [comment]
So what should the data argument be if the post body is pure json? Not clear from documents.

**Comment by SergioBenitez** [comment]
What does "pure" JSON mean? Is it just JSON? Then `Json`. I'm not sure how we can be clearer than what the docs say now:

> To parse request body data as JSON , add a data route argument with a target type of Json<T>, where T is some type you’d like to parse from JSON. T must implement serde::Deserialize.

**Comment by DanielJoyce** [comment]
Doesn't matter. Figured it out. :)
