### ISSUE TITLE
Add support for on_shutdown to fairings.

### ISSUE THREAD

**Issue by DanielJoyce** [SergioBenitez/Rocket#1576]
Currently when shutdown is called, there is no way for components, especially fairings, to be notified that it is happening. 

At the very least adding a on_shutdown method to fairings would let fairings do some housekeeping before shutdown.

We can't do it in Drop because Drop is synchronous only, and if the fairing has async code or assets, on_shutdown would need to be async too, and would need to be called by rocket ( possibly with a timeout ) before rocket terminates the executor pool.

```
Rocket is told to shutdown
Stop handling requests
Finish handling responses
Notify fairings of shutdown
Wait for fairings to shutdown ( possibly with timeout )
Cleanup up executors
Exit
```

**Comment by SergioBenitez** [comment]
What is your use-case? You can already run code after the server is done by calling launch() manually and waiting for it to return. 

In any case, let's track this in #180.

**Comment by DanielJoyce** [comment]
When launch() finishes, is the async executor still running?

**Comment by DanielJoyce** [comment]
Also, in tests, since client wraps rocket, we can't see when launch finishes.

Use case is being able to clean up the database or other such actions when tests finishes. 

 Also in general many other frameworks support lifecycle callback for middleware.

**Comment by SergioBenitez** [comment]
@DanielJoyce If you control the runtime, you decide when the executor stops. If not, it stops when the `main()` or `launch()` function returns. If you use `rocket::main`, then you know a shutdown occurred after `launch()` returns.

The idea of `launch()` finishing in tests doesn't make sense; there is no `launch()` in tests.
