### ISSUE TITLE
Enable DualStack - IPv6 and IPv4

### ISSUE THREAD

**Issue by nicraMarcin** [SergioBenitez/Rocket#1581]
Hi,
Does Rocket support IPv6 and IPv4 while running?
All documentations say only about IPv4.

How to configure Rocket to listen both?

**Comment by jebrosen** [comment]
Currently Rocket forwards the socket address to [`tokio::net::TcpListener::bind`](https://docs.rs/tokio/1.3.0/tokio/net/struct.TcpListener.html#method.bind) more or less directly. Rocket cannot currently listen on two different *addresses* in one server instance, but on some operating systems and configurations listening on `::` (IPv6 any address) will additionally accept requests made to any interface via IPv4 by default. One way you could check if this is the case on your machine is by starting a server with `ROCKET_ADDRESS=::` and making a request to `127.0.0.1`.

Here are a few other potential solutions:

* You could start two servers, one on each port.
* You can run a reverse proxy such as HAproxy or nginx, listening on both IPv4 and IPv6 and forwarding all requests to the Rocket server. We also generally recommend running a reverse proxy in production for other reasons, such as the completeness and configurability of specific features (such as TLS) and protection from denial-of-service attacks that Rocket does not (yet!) have an answer for.
* If and when #1070 is implemented, it would be possible to set custom socket options. In particular you could disable the IPV6_V6ONLY option, if it is available and enabled by default on your system.

**Comment by nicraMarcin** [comment]
@jebrosen Hi, Thank you for answer. Yes, this `ROCKET_ADDRESS=::` works. I'm thik this should be written in documentation :) My question wouldn't be here :)
Thanks again

**Comment by SergioBenitez** [comment]
The thing is that has little to do with Rocket and more to do with how your OS works. Nevertheless, these kinds of questions do stump users, and I think it would be nice to have a section in the documentation for FAQ of this sort. Lets track that in #1585.
