### ISSUE TITLE
The release version cannot run on Linux Centos7

### ISSUE THREAD

**Issue by yang-dong-dong** [SergioBenitez/Rocket#1584]
The release version cannot run on Linux Centos7.

Exception information:

error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

![image](https://user-images.githubusercontent.com/20069609/111754088-8d4bd900-88d2-11eb-94ea-133601fa713a.png)

![image](https://user-images.githubusercontent.com/20069609/111754038-7d33f980-88d2-11eb-83f6-9a7a45ec8c6c.png)

**Comment by SergioBenitez** [comment]
I don't think anything in Rocket or its dependencies uses `libssl`, so at the moment I'm inclined to believe you're depending on some other library, like `openssl` that depends on a `libssl` being present.

What does the rest of your project look like?

**Comment by yang-dong-dong** [comment]
Thank you very much, and very sorry at the same time, it is my own problem.
