### ISSUE TITLE
is "Introduce Managed State" not in Rocket v1.6?

### ISSUE THREAD

**Issue by greglearns** [SergioBenitez/Rocket#159]
I see that State was added January 21, and version 0.1.6 on January 26. However, when I use 0.1.6 in my code and try to follow the examples for State, I'm getting 
```
error[E0432]: unresolved import rocket::State
```
and 
```
error: no method named manage found for type rocket::Rocket in the current scope
```

**Comment by SergioBenitez** [comment]
The master branch does not correspond to the latest release. Instead, it's the latest in development for the next breaking release. Version 0.1 releases and develop is tracked in the [v0.1 branch](https://github.com/SergioBenitez/Rocket/tree/v0.1). The [CHANGELOG](https://github.com/SergioBenitez/Rocket/blob/master/CHANGELOG.md) shows which changes are in each release.

**Comment by greglearns** [comment]
Oh, so you are cherry-picking commits from master into release branches. I missed that! Thanks.
