### ISSUE TITLE
Expose the original file name including the extension in the multipart DataField

### ISSUE THREAD

**Issue by JBBgameich** [SergioBenitez/Rocket#1594]
### Why do I believe the feature is necessary

In cases were the client is trusted, the file extension can contain useful information.

### Use case

In my use-case  the client is trusted, and the server not publicly accessible. The client is uploading debian package build artifacts, which are output in a specific naming from a build tool.
There is a sort of manifest file, which lists the other files that belong to the build.

After uploading all those files including the manifest as a multipart request, the manifest file is passed to a tool that manages the repository, and it imports all related files automatically. This depends on the files to be named the same as output by the build tool.
Reconstructing the file extension from the content type is hard and probably error prone.

### Why not outside rocket 

As far as I understand the needed information is not exposed by Rocket, so this is not possible to implement as an additional crate

## General comments

@SergioBenitez mentioned on Matrix that APIs tend to be used the wrong way if the wrong way is as easy to use and find as the proper way to do things.

In occasions were the client is not trusted, the file extension should not be used, as it might be wrong. The content type instead tells the real type of data.

One way to solve this is hiding features that depend on a trusted client behind a feature flag, so they require concious enabling.

**Comment by NoraCodes** [comment]
I wonder if it would be possible to, rather than hiding this behind a feature flag, make it just require a second method call? I think this is useful in other situations, such as simply preserving the file name on upload regardless of type, and those don't require trusting the user at all.

**Comment by SergioBenitez** [comment]
> I wonder if it would be possible to, rather than hiding this behind a feature flag, make it just require a second method call? I think this is useful in other situations, such as simply preserving the file name on upload regardless of type, and those don't require trusting the user at all.

But that's _exactly_ what we want to avoid as it is wholly unsafe to use an arbitrary client-provided string as a file name. In the simplest case, consider the user providing a name of `/etc/special-file`. Calling `temp_file.persist_to(upload_dir.join(user_string))` will result in the special file being overridden. The security consequences are dire.

**Comment by NoraCodes** [comment]
> But that's _exactly_ what we want to avoid as it is wholly unsafe to use an arbitrary client-provided string as a file name. In the simplest case, consider the user providing a name of `/etc/special-file`. Calling `temp_file.persist_to(upload_dir.join(user_string))` will result in the special file being overridden. The security consequences are dire.

Yes, I absolutely agree with that. Could we just provide the file name, thought? We don't have to preserve the path, and could instead return [`path.file_name()`](https://doc.rust-lang.org/std/path/struct.PathBuf.html#method.file_name), which avoids the security implications.

**Comment by SergioBenitez** [comment]
> > But that's _exactly_ what we want to avoid as it is wholly unsafe to use an arbitrary client-provided string as a file name. In the simplest case, consider the user providing a name of `/etc/special-file`. Calling `temp_file.persist_to(upload_dir.join(user_string))` will result in the special file being overridden. The security consequences are dire.
> 
> 
> 
> Yes, I absolutely agree with that. Could we just provide the file name, though? We don't have to preserve the path, and could instead return [`path.file_name()`](https://doc.rust-lang.org/std/path/struct.PathBuf.html#method.file_name), which avoids the security implications.

That _still_ has security issues, unfortunately. Letting the user choose the file extension can result in other parts of the application or the OS interpreting the file in a way you don't desire. Allowing hidden files can have similar "don't overwrite _that!_" issues.

I am working now on a change that exposes a safe subset of the file name, if it exists, and otherwise provides a "unsafe_dangerous_raw()" method.

**Comment by NoraCodes** [comment]
> other parts of the application or the OS interpreting the file in a way you don't desire.

That's true, I guess allowing users to upload a `.htaccess` or `Rocket.toml` would be bad, huh. Apologies for my shortsightedness :)
