### ISSUE TITLE
`#[catch(default)]` doesn't work?, it expects an `int` (am I using this right? / does this still work?)

### ISSUE THREAD

**Issue by rolandpeelen** [SergioBenitez/Rocket#1599]
## Questions

I think the screenshot below says everything. I want to create a error catcher that returns some JSON (as opposed to the html). Basically a default error catcher that just forwards the message and code, but in a JSON structure.
This is sort of taken from [this example](https://github.com/SergioBenitez/Rocket/blob/master/examples/errors/src/main.rs).

<img width="1147" alt="Screen Shot 2021-03-30 at 1 38 00 PM" src="https://user-images.githubusercontent.com/4375473/112982845-41642400-915d-11eb-8804-c351f2420f84.png">

My question is basically;
1. Am I using this right
2. If not what would be the way to return JSON errors instead of HTML?

----

  1. The version of Rocket this question is based on, if any.
  
`0.4.7`

  2. What steps you've taken to answer the question yourself.
  
Looked through the docs and [source](https://docs.rs/crate/rocket_codegen/0.4.0/source/src/attribute/catch.rs)
  

  3. What documentation you believe should include an answer to this question.
  
https://rocket.rs/v0.4/guide/requests/#error-catchers

**Comment by SergioBenitez** [comment]
You're looking at docs in master but using v0.4. There is no such thing as a default catcher in 0.4.

**Comment by rolandpeelen** [comment]
Makes sense 😅 . Thanks for the reply. Perhaps though, the link in the docs, right at the bottom needs to be pinned to 0.4? That's how I got there at least :)

https://rocket.rs/v0.4/guide/requests/#error-catchers

"Unlike route request handlers, catchers take exactly zero or one parameter. If the catcher takes a parameter, it must be of type &Request. The **error catcher example** on GitHub illustrates their use in full."

The bold part links to: https://github.com/SergioBenitez/Rocket/tree/master/examples/errors
