### ISSUE TITLE
Request headers from upload stream are not being read

### ISSUE THREAD

**Issue by indiv0** [SergioBenitez/Rocket#160]
I have a `multipart/form-data` form.
When I attempt to submit this form, a request is sent, with some headers like so in the request stream:

```
Content-Type: multipart/form-data; boundary=---------------------------79069925012100300641397869547
Content-Length: 346

-----------------------------79069925012100300641397869547
Content-Disposition: form-data; name="media"; filename="test.txt"
Content-Type: text/plain

123

-----------------------------79069925012100300641397869547
Content-Disposition: form-data; name="submit"

Upload Image
-----------------------------79069925012100300641397869547--
```

The first two headers are not being read by Rocket.

**Comment by SergioBenitez** [comment]
Can you be clearer about why you think Rocket isn't reading the headers? I've personally tested cases like this, and Rocket should be reading this just fine.

What happens if you print request.headers()? Also, which versions are you on?

**Comment by indiv0** [comment]
My apologies, I misinterpreted the problem on my end.

The problem is actually not that Rocket is not reading the header, but rather that it is not reading the param for the header.

Here's the answers to your questions:

* `request.headers()`:

```
HeaderMap { headers: {UncasedAscii { string: "Content-Type" }: ["multipart/form-data"]} }
```

* versions:
    * rocket: `0.1.6`
    * rustc: `rustc 1.16.0-nightly (4ce7accaa 2017-01-17)`

**Comment by indiv0** [comment]
I've narrowed it down, it's actually just the `Content-Type` header.

Here's the result of `request.headers()`:

```
HeaderMap { headers: {UncasedAscii { string: "Content-Type" }: ["multipart/form-data; boundary=---------------------------79069925012100300641397869547"], UncasedAscii { string: "Content-Length" }: ["346"], UncasedAscii { string: "User-Agent" }: ["Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0"], UncasedAscii { string: "Upgrade-Insecure-Requests" }: ["1"], UncasedAscii { string: "DNT" }: ["1"], UncasedAscii { string: "X-Forwarded-Proto" }: ["https"], UncasedAscii { string: "Accept-Encoding" }: ["gzip, deflate, br"], UncasedAscii { string: "Host" }: ["dank.local"], UncasedAscii { string: "Referer" }: ["https://dank.local/"], UncasedAscii { string: "Connection" }: ["close"], UncasedAscii { string: "X-Real-IP" }: ["127.0.0.1"], UncasedAscii { string: "Accept" }: ["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"], UncasedAscii { string: "Accept-Language" }: ["en-US,en;q=0.5"], UncasedAscii { string: "Cache-Control" }: ["max-age=0"], UncasedAscii { string: "X-Forwarded-For" }: ["127.0.0.1"]} }
```

As you can see, the `Content-Type` header is in there:

```
UncasedAscii { string: "Content-Type" }: ["multipart/form-data; boundary=---------------------------79069925012100300641397869547"]
```

However, when reading it from `req.content_type()`, I get `ContentType::Any` instead of the expected result.

I believe I have found the cause of the error, [here](https://github.com/SergioBenitez/Rocket/blob/master/lib/src/http/content_type.rs#L374-L376).
You see, the parsing code expects the value to be a quoted string (e.g. `attr="some string"`), but as seen from the headers output above (i.e. `boundary=---------------------------79069925012100300641397869547`), this is not always the case.
This can also be confirmed by looking at the ABNF for the param value from the [relevant RFC](https://www.w3.org/Protocols/rfc1341/4_Content-Type.html):

```
parameter := attribute "=" value 

attribute := token 

value := token / quoted-string 

token := 1*<any CHAR except SPACE, CTLs, or tspecials> 
```

I believe that the parsing code not handling the `token` option for the `value` rule is the origin of the problem.

Versions:

* Rocket: `1.6.0`
* Rustc: `rustc 1.16.0-nightly (4ce7accaa 2017-01-17)`

**Comment by indiv0** [comment]
Actually, ignore my above diagnosis. I'm tired and I missed the fact that you *do* handle token properly. My apologies.

The symptoms of my problem remain the same.

**Comment by SergioBenitez** [comment]
Ah, yeah. This has already been fixed in https://github.com/SergioBenitez/Rocket/commit/2da08a975c838ab7e208b4970f862af2a5646b2e. Unfortunately, I don't believe this change is in any `v0.1` release. Can you try using the master branch to see if your issue goes away? You can do this my requiring Rocket as a dependency in your `Cargo.toml` as:

```toml
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket" }
```

Rocket v0.2 will include this fix an is scheduled to be released later this week.

**Comment by SergioBenitez** [comment]
@indiv0 Can you verify that this is no longer an issue?

**Comment by indiv0** [comment]
Right, sorry about the lack of response, I just haven't had a chance to test this yet. Will do ASAP.

**Comment by indiv0** [comment]
I've just confirmed that this is no longer an issue in Rocket v0.2.0.

Thank you!
