### ISSUE TITLE
Serde field name issue with json input

### ISSUE THREAD

**Issue by somehowchris** [SergioBenitez/Rocket#1601]
Hey :)

#### Rocket version
```toml
[dependencies]
rocket = "0.4.7"
rocket_contrib = { version = "0.4.7", features = ["json", "helmet", "diesel_mysql_pool"]}
```

#### System
From my system info:
```text
Version	10.0.18363 Build 18363
```
Running in wsl 2 with the linux 20.4 distro

#### Rust
Output of `rustup -V`
````text
rustup 1.23.1 (3df2264a9 2020-11-30)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.53.0-nightly (07e0e2ec2 2021-03-24)`
````
and `cargo -V`
```text
cargo 1.52.0-nightly (90691f2bf 2021-03-16)
```

## The thing
I'm not really sure where to open this ticket but since my primary issue accurs when using rocket here I am.

I am not really fimiliar with rockets in depth code but as usually it should use serde for its deserialization and serialization. serde provides a method to rename fields during those but I am experiencing__ 422: Unprocessable Entity__ responses with it.

What I do is a post with the following paiload [0]
```json
{
    "basePrice": 20,
    "paymentCurrency": "USD"
}
```

For that I get a 422 back where as for the following everything works [1]
```json
{
    "base_price": 20,
    "payment_currency": "USD"
}
```

And in return I get the expected output which is [0] as a 200

For all requests I use specific request entities which as used by the above example look like this:
```rust
use serde::{Serialize, Deserialize};

#[derive(Deserialize, Serialize)]
#[serde(rename_all(serialize = "camelCase", deserialize = "snake_case"))]
pub struct CreateOrderRequest{
    pub base_price: u128,
    pub payment_currency: String,
}
```

And for testing purposes I created an endpoint where I just respond with the just received data [3]
```rust
#[post("/", format = "json", data = "<order>")]
pub fn create_order(order: Json<CreateOrderRequest>) -> Result<Json<CreateOrderRequest>, Status> {
    return Ok(order);
}
```

As you can see the during the serialization fields are renamed as request [1] transforms to response [0] with the serde macro of [2] to rename all fields to camelCase.

Am I missing something? Would love to get this working.

**Comment by jebrosen** [comment]
I think you want `#[serde(rename_all = "camelCase")]` instead. `deserialize = "snake_case"` means that you expect the JSON data to use snake_case, which isn't the case here.

Here's a playground example using only `serde_json`:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f3b53fcdc5a27418078576cc7236c210

**Comment by somehowchris** [comment]
Thanks a lot man. Makes a lot of sence that way and not the other but couldn't find it explicitly on the serde docs.
