### ISSUE TITLE
Use "." in a query name

### ISSUE THREAD

**Issue by jafioti** [SergioBenitez/Rocket#1603]
I am attempting to use facebook webhooks with Rocket, and overall my experience has been quite smooth. However, to register a webhook, facebook sends a GET request with queries named "hub.challenge" and "hub.mode". I can't figure out how to use a "." in the name of the query, Rocket believes it is an invalid identifier. 

Here is my code:
```
#[get("/webhook?<hub.mode>&<hub.challenge>&<hub.verify_token>")]
fn webhook_get(mode: Strict<String>, challenge: Strict<String>, verify_token: Strict<String>) -> status::Accepted<String> {
```

And my error: ```invalid identifier: `hub.mode`
dynamic parameters must be valid identifiers
did you mean `<hubmode>`?```

Is it possible to have "." in the query name, or is there a way to rename incoming query names?

**Comment by jebrosen** [comment]
This looks very similar to: https://github.com/SergioBenitez/Rocket/issues/1203#issuecomment-574778108 , including a possible workaround for Rocket 0.4.


If you are using the `master` branch of Rocket, the `hub` prefix can now be handled via `#[derive(FromForm)]`; there is an example of this feature at: <https://rocket.rs/master/guide/requests/#dynamic-parameters>).

**Comment by jafioti** [comment]
@jebrosen Sorry if this is a dumb question, but when I try to use field renaming, I get an issue:
```cannot find attribute `form` in this scope```
I've imported rocket::form but I don't think that's the one it needs.

**Comment by SergioBenitez** [comment]
You don't even need field renaming on `master`:

```rust
#[derive(FromForm)]
struct Hub<'r> {
    mode: &'r str,
    challenge: &'r str,
    verify_token: &'r str
}

#[get("/webhook?<hub>")]
fn webhook_get(mode: Hub<'r>) { }
```

But the field attribute is now `#[field]`, not `#[form]`. See https://rocket.rs/master/guide/requests/#forms for the new guide.

**Comment by jafioti** [comment]
@SergioBenitez  Thanks for the help! It works great now.
