### ISSUE TITLE
Outcome Returns Failure when parsing JSON body

### ISSUE THREAD

**Issue by jafioti** [SergioBenitez/Rocket#1604]
I'm trying to accept POST requests that send a JSON body, and I am going off of the JSON example for Rocket. Currently, I have a hierarchy of structs built to parse the JSON, and they are all Serializable and Deserializable, but I am always getting an `Outcome: Failure`. I also tried to simply accept a string, or a Cow<String>, but both of those failed as well. Is it possible to simply accept a string, or a serde::value rather than have to perfectly build a struct hierarchy for the body to parse into?

Here's my struct hierarchy:
```
#[derive(Debug, Serialize, Deserialize)]
struct FBBody {
    object: String,
    entry: Vec<FBEntry>,
}

#[derive(Debug, Serialize, Deserialize)]
struct FBEntry {
    id: String,
    time: i32,
    messaging: Vec<FBMessaging>,
}

#[derive(Debug, Serialize, Deserialize)]
struct FBMessaging {
    sender: FBSender,
    recipient: FBSender,
    timestamp: i32,
    message: FBMessage
}

#[derive(Debug, Serialize, Deserialize)]
struct FBMessage {
    mid: String,
    text: String,
    quick_reply: Option<FBQuickReply>
}

#[derive(Debug, Serialize, Deserialize)]
struct FBQuickReply {
    payload: String,
}

#[derive(Debug, Serialize, Deserialize)]
struct FBSender {
    id: String,
}
```

And here's my post route:
```
#[post("/webhook", data="<body>", format="json")]
fn webhook_post(body: Json<FBBody>) -> status::Accepted<String> {
```

I also tried other post routes:
```
#[post("/webhook", data="<body>", format="json")]
fn webhook_post(body: Json<Cow<'_, str>>) -> status::Accepted<String> {
```

This is the JSON I am trying to parse:
```
{
  "object":"page",
  "entry":[
    {
      "id":"<PAGE_ID>",
      "time":1458692752478,
      "messaging":[
        {
          "sender":{
            "id":"<PSID>"
          },
          "recipient":{
            "id":"<PAGE_ID>"
          },
          "timestamp":1458692752478,
          "message":{
            "mid":"mid.1457764197618:41d102a3e1ae206a38",
            "text":"hello, world!",
            "quick_reply": {
              "payload": "<DEVELOPER_DEFINED_PAYLOAD>"
            }
          }
        }
      ]
    }
  ]
}
```

I know the problem is from parsing and not from inside my function because I've removed all code from my function and simply return a success, and I still get `Outcome: Failure`.

**Comment by blackghost1987** [comment]
Just an idea: those numbers look larger then i32::MAX, even larger then u32::MAX. Have you tried u64 (or i64) for the timestamps?

**Comment by jafioti** [comment]
@blackghost1987  I cannot believe it was that simple, but thank you for the suggestion. That was indeed the problem. I changed the numbers to u64 and it works like a charm!
