### ISSUE TITLE
Provide a convenience method to map Outcome<S,E,F> to Result<S,E>

### ISSUE THREAD

**Issue by DanielJoyce** [SergioBenitez/Rocket#1612]
Right now, we have success_or which throws away E, and you must provide your own error value, or success_or_else which takes a function, but the function takes no parameters. In all cases, the error value is thrown away.

This would make it easier to interop with Result style apis, the ? operator, etc.

We can of course use `match` but that's verbose.

**Comment by SergioBenitez** [comment]
Sure! Happy to accept a PR, if you could send one in!

**Comment by DanielJoyce** [comment]
Yeah, I have something knocking about. I'll see if I can get something together.

**Comment by SergioBenitez** [comment]
Closed in https://github.com/SergioBenitez/Rocket/commit/59851a621c7826f72fcfc71d14863ec1dc03d755.
