### ISSUE TITLE
Question: There is any method to obtain a config value in a FromRequest?

### ISSUE THREAD

**Issue by ogarcia** [SergioBenitez/Rocket#1616]
Hi guys, I have a little question about config. There is any method to obtain a config value in a FromRequest?

I have a code like this:
```rust
pub struct TokenLifetime(i64);
fn main() {
    rocket::ignite()
    .attach(AdHoc::on_attach("Token lifetime config", |rocket| {
            let registration_enabled = rocket.config()
                .get_int("token_lifetime")
                .unwrap_or(30);
            Ok(rocket.manage(TokenLifetime(token_lifetime)))
        }))
}
```

I can access to my `TokenLifetime` in any request using something like this:
```rust
#[post("/auth/users", data = "<user>")]
pub fn post_auth_users(user: Json<NewUser>, token_lifetime: State<TokenLifetime>) -> status::Custom<Json<JsonValue>> {
...(function code)...
}
```

But I need to implemente a _Request Guard_ to check if token is expired and I would like to offer the possibility of being able to configure how long the token can be valid.

Is this possible? Can you provide me an example for noobs?

**Comment by jebrosen** [comment]
[`FromRequest::from_request`](https://api.rocket.rs/v0.4/rocket/request/trait.FromRequest.html#tymethod.from_request) receives an `&Request` argument, which has the [`request.guard()`](https://api.rocket.rs/v0.4/rocket/request/struct.Request.html#method.guard) method. Is that the method you are looking for?

**Comment by ogarcia** [comment]
Yes! Shit, I read `request.guard()` method documentation 272194029421 times and now I see my issue. I'm using `request.guard::<TokenLifetime>()` instead of `request.guard::<State<TokenLifetime>>()`. Now this works:
```rust
let token_lifetime = request.guard::<State<TokenLifetime>>().expect("token lifetime");
```
May thanks @jebrosen :heart: !
