### ISSUE TITLE
`anyhow`'s backtraces are lost inside `#[rocket::main] async fn main()` if and only if `use sqlx;` is present at top level. 

### ISSUE THREAD

**Issue by itsfarseen** [SergioBenitez/Rocket#1623]
1. Rocket version: https://github.com/SergioBenitez/Rocket#336a03e27f43d0ec3b02d8b99e10d2df202523ad
  2. Rust version: `rustc 1.53.0-nightly (42816d61e 2021-04-24)`
     This bug doesn't apply to stable, because `anyhow`'s backtraces are not generated in stable yet.

  3. Description of the bug:
 
      `anyhow`'s backtraces are lost inside `#[rocket::main] async fn main()` if and only if `use sqlx;` is present at top level. 
      
      Bug is not there if `#[tokio::main] async fn main()` is used and `rocket` is removed from `Cargo.toml`
      Bug is still there if `#[tokio::main] async fn main()` is used, but `rocket` is kept in `Cargo.toml`

       SQLx in `Cargo.toml`:  
        `sqlx = { version = "0.5.2", features = ["runtime-tokio-rustls"] }`

  4. Minimal repro:
      https://github.com/itsfarseen/repro-sqlx-rocket-anyhow-no-backtrace

  5. Other notes:
      I don't know much about the internals of async/await, but I think `#[rocket::main]` is somehow conflicting with sqlx.  
      What's weird is I'm not even using sqlx. I'm merely importing it.

**Comment by SergioBenitez** [comment]
cc @dtolnay

**Comment by itsfarseen** [comment]
Output of `RUST_BACKTRACE=1 cargo run`
```bash
warning: unused import: `Context`
 --> src/main.rs:4:22
  |
4 | use anyhow::{anyhow, Context, Result};
  |                      ^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `sqlx`
 --> src/main.rs:7:5
  |
7 | use sqlx;
  |     ^^^^

warning: 2 warnings emitted

    Finished dev [unoptimized + debuginfo] target(s) in 10.80s
     Running `target/debug/repro-rocket-anyhow-no-backtrace`
Error: foo

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: __libc_start_main
  21: <unknown>
```

**Comment by dtolnay** [comment]
Does `anyhow` have any relevance here or does the same discrepancy occur if directly requesting the backtrace from std::backtrace?

```rust
#![feature(backtrace)]

println!("{}", std::backtrace::Backtrace::force_capture());
```

**Comment by itsfarseen** [comment]
The same discrepancy occurs when directly requesting the backtrace from std::backtrace.

**Comment by itsfarseen** [comment]
Just tried removing rocket from Cargo.toml and it seems the bug occurs with just `tokio` and `sqlx`.  
I might have missed something last time I tested it.  
I have updated the minimal repro to reflect this. 
Closing, since this is not a Rocket or anyhow issue. Thanks for your time :)

**Comment by itsfarseen** [comment]
I found the cuplrit. I had been using the experimental linker https://github.com/rui314/mold. Switching back to lld solved the issue
