### ISSUE TITLE
Ring does not compile if I use tls while I'm on Apple M1

### ISSUE THREAD

**Issue by marirs** [SergioBenitez/Rocket#1627]
Hi, on the Apple Mac M1 (works on the intel mac)

If I build rocket with the tls feature, it does not build. It is not able to compile Ring again. Is there any work around to use without ring. The version of Ring that gets included is 0.13 while current Ring version is 0.16.

I remove the tls feature, it compiles, because I guess the ring is not used here

  1. The version of Rocket you're using. Ensure it's the latest, if possible.
rocket = { version = "0.4.7", default-features = false, features = ["tls"] }
rocket_contrib = "0.4.7"

  2. The operating system (distribution and version) where the issue occurs.
Apple macOS Bigsur on M1
rustc 1.53.0-nightly (478a07df0 2021-04-29)
binary: rustc
commit-hash: 478a07df05e3fe8df964291d8b25dd80b7e0e76b
commit-date: 2021-04-29
host: aarch64-apple-darwin
release: 1.53.0-nightly
LLVM version: 12.0.0

**Comment by SergioBenitez** [comment]
Can you test this on master?

Please see the myriad issues for why ring makes it impossible for us to upgrade its version without a breaking change.

**Comment by marirs** [comment]
yes from master it seems to build now, however, seems like there are changes from 0.4.7 to 0.5 :)

**Comment by SergioBenitez** [comment]
> yes from master it seems to build now, however, seems like there are changes from 0.4.7 to 0.5 :)

I would hope so!

Given `ring` and its policies, we can't do anything about this, unfortunately. See https://github.com/briansmith/ring/issues/535 and my declined fix at https://github.com/briansmith/ring/pull/619.

**Comment by marirs** [comment]
Hi - just thinking to see if there is any other way to compile in M1.
If I disable the "tls" feature it compiles, but if I enable it, it stops compiling because of ring 0.13
With the secure cookies it compiles without any problem. So its just the issue with enabling tls.
I need tls for my project, but moving to the 5 breaks my code, so changing from 4.7 to 5 is also tedious.
any thing else can I do? like force ring with latest version or so?
