### ISSUE TITLE
Option to reload or prevent caching of templates

### ISSUE THREAD

**Issue by trombonehero** [SergioBenitez/Rocket#163]
It would be super-helpful for development and debugging if Rocket could reload cached templates when I modify them, or else turn off caching altogether in development mode.

**Comment by SergioBenitez** [comment]
I've handled this same issues out-of-band by using tools like `entr` or `watchexec`. These tools monitor some set of files and run a command when any of those files changes. For instance, you can ask `watchexec` to monitor template files and restart the application on changes with:

```sh
watchexec --exts tera,hbs --restart "cargo run"
```

Unless the template engines themselves support the feature (which they presently don't), I think adding this functionality to Rocket itself isn't a great idea. The complexity isn't worth the reward, in my opinion, especially when it's so easy to use an out-of-band tool.

**Comment by mehcode** [comment]
https://github.com/passcod/cargo-watch looks promising. It doesn't support running a server yet but it's on the top of their roadmap.

**Comment by trombonehero** [comment]
Ok, that's fair enough. In fact, the `watchexec` approach is even better than reloading templates because it can also reload on `.rs` file changes.

Now the only remaining question is, what would be required to integrate LiveReload-like functionality (á la http://nitoyon.github.io/livereloadx) to Rocket? If Rocket told my web page to reload itself every time it started running again after `watchexec`-driven recompilation... well, that would be nice.

**Comment by SergioBenitez** [comment]
I use the [LiveReload](http://livereload.com/) application for exactly that, @trombonehero, no changes to Rocket needed. I simply monitor the directory where my application is, and `LiveReload` does the rest.

**Comment by SergioBenitez** [comment]
@trombonehero Do you still feel like this is something Rocket should have built-in?

**Comment by SergioBenitez** [comment]
For now, I think this is something better handled outside of Rocket. Maybe one day we'll have a `rocket` CLI, and `rocket watch` will do the right thing. ;)

Closing this issue for now.

**Comment by Qqwy** [comment]
> For templating specifically, I think it would be nice if Rocket could reload templates automatically during development. Further, I think it's absolutely possible, and quite simple, in fact, given the new fairings and the new Template implementation in master. We should see this in the not-too-distant future. We can have that discussion in #163.

Maybe it is worth opening this issue again, so we can talk about template reloading in more detail :-).

**Comment by C-Bouthoorn** [comment]
I'd like to bump this. Would it be possible to re-parse a template every time a request is made (optional, developing environment). I think restarting the server every time one changes a little HTML shouldn't be necessary

**Comment by jebrosen** [comment]
I am working on this issue now, informed by https://github.com/SergioBenitez/Rocket/issues/523#issuecomment-354476111. I am to a point where the template context is reloaded on every request made in debug mode, including re-running the engine customization callback. The next step is to reload only when files were actually changed on disk; after that is done I will focus on cleaning up some rough edges and submit a PR.
