### ISSUE TITLE
Removed JSON example still linked in docs

### ISSUE THREAD

**Issue by Anton-4** [SergioBenitez/Rocket#1634]
## General Comments

At the URL https://rocket.rs/v0.4/guide/responses/#json there is a link with the text "JSON example on GitHub" and URL https://github.com/SergioBenitez/Rocket/tree/master/examples/json". This example does not exist anymore and thus clicking the link results in a 404.

The link should be updated to point to the correct example.

**Comment by SergioBenitez** [comment]
The problem is that, for some reason, that link is going to `master` which it should be going to the 0.4 docs. Also, you probably want to read the guide at rocket.rs/master if you're working with master, otherwise all of the docs will be wrong.

**Comment by SergioBenitez** [comment]
This has been fixed.
