### ISSUE TITLE
How to pass custom context to handlers?

### ISSUE THREAD

**Issue by drahnr** [SergioBenitez/Rocket#164]
I scouted through the examples but I fail to see how one can pass extra context conveniently to a handler?

Usecase: I have a some library which collects data, does fun stuff with it and then want to display/make it RESTable.

Can someone give me a snippet how to pass a context to handlers?

**Comment by SergioBenitez** [comment]
#53 asks the same question, so marking this is a duplicate.

That being said, there's no easy way in a current release. You essentially have to do it manually, using something like [lazy_static](https://crates.io/crates/lazy_static) or [state](https://crates.io/crates/state). In `v0.2`, you'll be able to use managed state, and example of which is available in [here](https://github.com/SergioBenitez/Rocket/blob/master/examples/state/src/main.rs).
