### ISSUE TITLE
Background Processes

### ISSUE THREAD

**Issue by jafioti** [SergioBenitez/Rocket#1640]
I am trying to run a background process every few minutes with access to a managed state. I have a number of endpoints that use this shared state, currently stored in a mutex. One way I can think of is to setup a new endpoint to do my work, and then launch another thread that makes a request to that endpoint every few minutes, but this seems janky.

What would be the recommended way of doing this?
Sorry for the lack of specific code, I think this is a pretty general problem not specific to my project.

**Comment by SergioBenitez** [comment]
Please fill in the required information from the issue template.

**Comment by jafioti** [comment]
# Question
Rocket Version: 0.5.0-dev

Steps Taken: So far I've only come up with a seemingly workaround solution to make an endpoint, make another thread, and call that endpoint every so often.

Documentation: I don't know if this is already a feature, but if not, then I would suggest this be made a feature, an ability to mount threads that accept states as well as routes. This would allow someone to have a thread that can sleep for a while, wake up, lock a mutex, and use the state, then go back to sleep. I don't believe this feature can exist outside of rocket, because rocket manages the states, so I don't think another crate can access or work with rocket's states.

**Comment by mjanda** [comment]
@jafioti one way would be to create on_launch fairing and use something like job_scheduler to run your tasks. That's the way I did it.

**Comment by jebrosen** [comment]
> I don't believe this feature can exist outside of rocket, because rocket manages the states, so I don't think another crate can access or work with rocket's states.

This already shouldn't be an obstable. Any owned thread-safe data can be put into managed state, including `Arc<T>` for most `T` (including e.g. `Arc<Mutex<T>>`). The `Arc` can then be used in the same ways as it would have been without Rocket, and doesn't require fake endpoint calls.

For running tasks in the background, either `std::thread::spawn` and `tokio::spawn` would both be suitable depending on your needs, and these tasks can `std::thead::sleep()` or `tokio::time::sleep().await` to perform work periodically. And as @mjanda mentions, `on_launch` can be a good place to do this.

**Comment by SergioBenitez** [comment]
> For running tasks in the background, either `std::thread::spawn` and `tokio::spawn` would both be suitable depending on your needs, and these tasks can `std::thead::sleep()` or `tokio::time::sleep().await` to perform work periodically. And as @mjanda mentions, `on_launch` can be a good place to do this.

Note that there is no `on_launch()`, though there is `on_ignite()`. Even then, `on_liftoff()` seems like a better place to start tasks when the server starts, or simply do it before. Here is the general scaffold for this idea:

#[launch]
fn rocket() -> _ {
    let state = Arc::new(Mutex::new(State::new()));

    let clone = state.clone();
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(Duration::from_seconds(60));
        loop {
            do_something_with(&clone);
            interval.tick().await;
        }
    });

    rocket::build().manage(state)
}
```

You can move the `tokio::spawn()` into a liftoff fairing and optionally `select` on the `Shutdown` future to gracefully stop an infinite task.

**Comment by ryadom** [comment]
Is there a way to get an access to database from this background process?

**Comment by SergioBenitez** [comment]
@ryadom If you just need one connection, use the generated [`get_one()`](https://api.rocket.rs/v0.5-rc/rocket_sync_db_pools/attr.database.html) method. Otherwise, we'll need #1187.

**Comment by Zopieux** [comment]
#1187 has been fixed -- thanks @SergioBenitez! :partying_face:  I have a similar requirement in that I need access to a `rocket(_sync)_db_pools` connection in a "background" task that does processing outside of Rocket request handlers, for instance by receiving events through an async channel. I have the option to put said task in a liftoff fairing as you suggested. 

How would I fix the code below to do so?

```rust
rocket::build()
  .attach(Db::init())
  .attach(AdHoc::try_on_ignite("migrate", run_migrations))
  .attach(AdHoc::on_liftoff("forever running bg task", |rocket| {
    Box::pin(async move {
      while let Some(msg) = some_recv.next().await /* TODO: select {} for graceful shutdown */ {
        // How do I get a Db connection here?
        do_some_stuff(conn).await;
      }
    })
  }))
```

**Comment by tobymurray** [comment]
@zopieux I think you're 95% of the way there, trying this out today on the head of the 0.5.0-rc.1:
```
AdHoc::on_liftoff("background database", |rocket| {
	Box::pin(async move {
		let mut interval = time::interval(Duration::from_secs(5));
		loop {
			interval.tick().await;

			// Get an actual DB connection
			let db = DbConnection::get_one(rocket).await.unwrap();

			// Execute a query of some kind
			db.run(move |c| match query_some_things(c) {
				Ok(s) => println!("Results are: {:#?}", s),
				Err(e) => panic!("{:#?}", e),
			})
			.await;
		}
	})
});
```

This works for me. So to answer your question directly,
> // How do I get a Db connection here?

You pass your rocket instance the [get_one](https://api.rocket.rs/v0.5-rc/rocket_sync_db_pools/attr.database.html) method off the structure you've used the `#[database]` macro on that corresponds to the database you'd like to access, e.g. `DbConnection` for me:

	let db = DbConnection::get_one(rocket).await.unwrap();

**Comment by yzernik** [comment]
@tobymurray I tried using your approach, and it blocks the app from handling any requests.

**Comment by yzernik** [comment]
Ok, I ended up using a modified version of this [code](https://github.com/SergioBenitez/Rocket/issues/1884#issuecomment-1075866102):

```
            .attach(AdHoc::on_liftoff("DB polling", |rocket| {
                Box::pin(async move {
                    let conn = Db::fetch(&rocket);
                    rocket::tokio::spawn(async move {
                        let mut interval = rocket::tokio::time::interval(
                            rocket::tokio::time::Duration::from_secs(10),
                        );
                        loop {
                            interval.tick().await;
                            // do_sql_stuff(&conn).await;
                            println!("Do something here!!!");
                        }
                    });
                })
            }))
```

**Comment by tobymurray** [comment]
I actually went the opposite direction of this and grabbed the DB connection from outside Rocket to tie as little as possible to Rocket.

```
let url = Config::figment()
		.extract_inner("databases.mydatabase.url")
		.unwrap();
let db = Connection::open(url).unwrap()
```
then making use of it:
```
tokio::spawn(async move {
  let mut ten_minutes = time::interval(Duration::from_secs(60 * 10));
  loop {
    ten_minutes.tick().await;
    sync_stores(db).await;
  }
});
```
