### ISSUE TITLE
Add `Request::request_id()` and `Request::set_request_id()`?

### ISSUE THREAD

**Issue by kenaniah** [SergioBenitez/Rocket#1651]
@SergioBenitez would you be open to a PR that would add an API for handling request identifiers?

I have some initial thoughts about a potential implementation, and would love feedback before diving in...

While I was unable to find an actual RFC for this, it appears as though the `X-Request-Id` header has become an informally standardized way to trace individual requests to a web service. I would like to propose `Request::request_id()` and `Request::set_request_id()` to set/generate/retrieve unique identifiers for each request.

Because there is no officially-agreed upon format for request identifiers that is in place today, my initial inclination is that it should be backed by something like: 

```rust
pub struct RequestState<'r> {
    ...
    pub request_id: Arc<RwLock<Option<Cow<'r, str>>>>, // Would this type definition makes sense?
    ...
}
```

`Request::request_id()` would either return the current value or calculate & store one if missing (first looking at the value of the `X-Request-Id` header if set, generating a new value stringified from UUID if not). 

`Request::set_request_id()` should probably have reasonable limits on the size of the value passed in (limit to 256 UTF-8 characters). 

Questions:
 * Would it make more sense to track the request_id using `request::local_cache!`? 
 * How should a request identifier be generated if `uuid` feature is not enabled?
 * Are there other things that need to be taken into consideration?

These are just my initial thoughts, and I would very much appreciate feedback on the design of the feature overall. I consider myself new to both rocket and Rust in general. Thanks!

**Comment by SergioBenitez** [comment]
My immediate reaction is that this can be done in a rather straightforward manner using request local state. Coupled with a fairing,￼ request ID tracking would happen universally and without any additional effort. See the [request-local state Fairing example](https://api.rocket.rs/master/rocket/fairing/trait.Fairing.html#request-local-state). 

Do you see any advantage to building this into Rocket?

**Comment by kenaniah** [comment]
That does indeed seem like a very straightforward approach, and in retrospect I think a fairing would be the right place to do this, at least for now. I think there would be an advantage to at least including the fairing in rocket_contrib as an optional dependency for anyone else who may be interested in logging & tracing requests end-to-end. Would you be open to a PR for a fully-documented fairing w/ examples added to contrib?

**Comment by SergioBenitez** [comment]
I don't think this makes sense to include in Rocket or in a `contrib` library or feature. I'm dubious of the _general_ utility of such a feature. Nevertheless, when #21 is resolved, each request _will_ actually have an ID associated with it, and so we'd simply need to expose it with `request.id()`.

> Would you be open to a PR for a fully-documented fairing w/ examples added to contrib?

I think we can add a simple example to fairing docs on how to do this, not an implementation. Something that uses an AtomicU64 or something to that effect and stores it in request-local state. I think the example is more valuable as the exact implementation can be tailored to needs. Though this is effectively what the "counter" example is now except with one less counter and no response fairing.

**Comment by SergioBenitez** [comment]
I'm closing this out as the issue itself is resolved. Happy to take that doc PR, however!
