### ISSUE TITLE
Return Result with a custom FromData implementation and errors with 200 HTTP return code

### ISSUE THREAD

**Issue by dzervas** [SergioBenitez/Rocket#1653]
### Question info:

1. Rocket version: 0.4.7
2. See at the bottom for my tried steps to solve this
3. I think that https://rocket.rs/v0.4/guide/responses/ should include this answer, somewhere. Not sure though as I think that this a bit of a "too specific" use case

I have an odd case of a client (that I don't control) that expects the response to be of the form:

```json
{
  "resp": { "my": "data" },
  "err": "my error (if any)"
}
```

I have many endpoints to manage so I've coded a wrapper:

```rust
use std::borrow::Borrow;
use std::fmt::Debug;

use rocket::{self, http::Status};
use rocket::Request;
use rocket::response::{Responder, content};
use serde::Serialize;

#[derive(Serialize)]
pub struct Wrapper<T> {
	pub resp: Option<T>,
	pub err: Option<String>,
}

#[derive(Debug, Clone)]
pub struct Response<T>(pub Result<T, String>);

impl<'a, T: Serialize + Debug> Responder<'a> for Response<T> {
	fn respond_to(self, req: &Request) -> rocket::response::Result<'a> {
		if self.0.is_err() {
			let e = self.0.borrow().as_ref().unwrap_err();
			println!("Error during handling request: {:?}", &e);
		}

		let wrapper = match self.0 {
			Ok(d) => Wrapper { resp: Some(d), err: None },
			Err(e) => Wrapper { resp: None, err: Some(e) }
		};
		let original = serde_json::to_string(&wrapper);

		if original.is_ok() {
			return content::Json(original).respond_to(req);
		}

		let e = original.unwrap_err();
		println!("Unable to serialize response: {:?}", e);
		let erroneous = serde_json::to_string(&Wrapper::<String> { resp: None, err: Some(format!("Unable to serialize response: {:?}", e)) });

		match erroneous {
			Ok(d) => content::Json(d).respond_to(req),
			Err(ei) => {
				println!("Unable to serialize error in response: {:?}", ei);
				Err(Status::InternalServerError)
			}
		}
	}
}
```

An example use case:

```rust
#[post("/save")]
pub fn save_handler<'r>(s: ReqState<'r>) -> Response<State> {
	let state = s.read().unwrap().to_owned();
	state.save().unwrap();
	info!("Internal state saved to disk");
	Response(Ok(state))
}
```

I have two problems:

1. I want to be able to propagate errors in the `Response` by using the `?` operator (I've tried implementing the experimental `Try` trait with no luck`. How can I do that?
2. When an error happens I want to return a 200 answer with the Result's `Err` as a string. How would I write such an error handler?

I want to keep the return code as concise as possible due to the amount of handlers that I have (~30) so I'd like to stay away from `Result<Response<()>, anyhow::Error>` and the likes

Example target code (hypothetical):
```rust
#[post("/save")]
pub fn save_handler<'r>(s: ReqState<'r>) -> Response<State> {
	let state = s.read()?.to_owned();
	state.save()?;
	info!("Internal state saved to disk");
	Ok(state) // or even better just `state`
}
```

**Comment by jebrosen** [comment]
> I want to be able to propagate errors in the Response by using the ? operator (I've tried implementing the experimental Try trait with no luck). How can I do that?

I believe `Try` should be able to do this, but it was recently reworked and I am not familiar with the new design off the top of my head. What didn't work about it?

Unfortunately your goal might not be possible as written without implementing `Try`. The only built-in types that work with the `?` operator are `Option` (not helpful) or `Result` (not quite what you want here, I think). You can *almost* achieve the target code by returning `Result<Json<Something>, ErrorResponse>`: Errors can be handled via `?` by adding an `impl From<T> for ErrorResponse where T: Display`, since `?` automatically calls `From::from` on the error type. But, you would need to wrap the success response with `Ok(data.into())` or similar.

There are a few other ways to organize the code, but to use `?` you will effectively always need to write a function somewhere that returns `Result<T, E>`. This actually sounds like it may be a good use case for `try` blocks (rust-lang/rust#31436), although I haven't used this feature myself and don't know if/how it works today.

> When an error happens I want to return a 200 answer with the Result's Err as a string. How would I write such an error handler?

Can you elaborate on this question? The code you posted looks like it returns a 200 with the `Err` contents (in the Wrapper instead of a String), so I think I am missing some context.

**Comment by SergioBenitez** [comment]
Which version of Rocket are you using? Please don't ignore the issue template.

**Comment by SergioBenitez** [comment]
In any case, I'd probably do something like this:

```rust
use rocket::Request;
use rocket::response::{self, Responder};

use serde::{Serialize, json::Json};

#[derive(Serialize)]
struct Response<T> { resp: T }

#[derive(Serialize)]
struct Error { err: Cow<'static, str> }

type Result<T> = std::result::Result<Response<T>, Error>;

impl<'r, T: Serialize> Responder<'r, 'static> for Response<T> {
    fn respond_to(self, request: &'r Request<'_>) -> response::Result<'static> {
        Json(self).respond_to(request)
    }
}

impl<T> From<T> for Response<T> {
    fn from(value: T) -> Self {
        Response { resp: value }
    }
}

impl<E: Display> From<E> for Error {
    fn from(err: E) -> Self {
        Error { err: err.to_string().into() }
    }
}

impl<'r> Responder<'r, 'static> for Error {
    fn respond_to(self, request: &'r Request<'_>) -> response::Result<'static> {
        Json(self).respond_to(request)
    }
}
```

This assumes that `resp` and `err` are mutually exclusive. Adjust the implementation as needed, but please note that lack of `expect()` or `unwrap()` or lengthy `Responder` impl: just delegate to the existing `Json` responder. Much, much easier, and also actually correct.

Then you can write your example as:

```rust
#[post("/save")]
pub fn save_handler<'r>(s: ReqState<'r>) -> Result<State> {
    let state = s.read()?.to_owned();
    state.save()?;
    Ok(state.into())
}
```

**Comment by dzervas** [comment]
@jebrosen I'll give another go with the try v2 block and report back. I deleted the code (I just don't get what output and the other type should be, I'll dig the rust docs)
@SergioBenitez sorry for ignoring the template, will fix it up soon. I thought that it's about a bug.
I'm on rocket 0.4.7 btw.

ooooh you're right! I dismissed `Json` responder as I tried to implement the error part (obviously the wrong way.

Thank you both! :)
I'll update and come back later

**Comment by dzervas** [comment]
Updated to rocket 0.4.10
@SergioBenitez I'm trying your solution and I get the following which I'm not quite sure how to solve:
```rust
error[E0277]: the trait bound `std::result::Result<app::response::Response<state::State>, app::response::Error>: Responder<'_>` is not satisfied
   --> src/app/setter.rs:29:45
    |
29  | pub fn save_handler<'r>(s: ReqState<'r>) -> Result<State> {
    |                                             ^^^^^^^^^^^^^ the trait `Responder<'_>` is not implemented for `std::result::Result<app::response::Response<state::State>, app::response::Error>`
    |
   ::: /home/dzervas/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.10/src/handler.rs:202:20
    |
202 |     pub fn from<T: Responder<'r>>(req: &Request, responder: T) -> Outcome<'r> {
    |                    ------------- required by this bound in `handler::<impl Outcome<rocket::Response<'r>, rocket::http::Status, rocket::Data>>::from`
    |
    = help: the following implementations were found:
              <std::result::Result<R, E> as Responder<'r>>
              <std::result::Result<R, E> as Responder<'r>>
```

The `Responder` trait is implemented for `std::result::Result` when both of its types (R & E) implement `Responder`. In `pub type Result<T, E = Error> = std::result::Result<Response<T>, E>;` both `Response<T>` and `Error` implement `Responder`, so where's the problem? I don't get it

**Comment by dzervas** [comment]
OMG... `Error` needed to implement the `Debug` trait as `Responder` for `Result` is implemented:
`impl<'r, R: Responder<'r>, E: Debug> Responder<'r> for Result<R, E>` and
`impl<'r, R: Responder<'r>, E: Responder<'r> + Debug> Responder<'r> for Result<R, E>`

For anyone looking at the same problem my final code:

```rust
use rocket::Request;
use rocket::response::{self, Responder};
use core::fmt::Display;
use std::borrow::Cow;
use rocket::response::content::Json;

use serde::Serialize;

#[derive(Serialize)]
pub struct Response<T> { resp: T }

#[derive(Serialize, Debug)]
pub struct Error { err: Cow<'static, str> }

pub type Result<T, E = Error> = std::result::Result<Response<T>, E>;

impl<'r, T: Serialize> Responder<'r> for Response<T> {
	fn respond_to(self, request: &Request<'_>) -> response::Result<'r> {
		Json(self).respond_to(request)
	}
}

impl<T> From<T> for Response<T> {
	fn from(value: T) -> Self {
		Response { resp: value }
	}
}

impl<E: Display> From<E> for Error {
	fn from(err: E) -> Self {
		Error { err: err.to_string().into() }
	}
}

impl<'r> Responder<'r> for Error {
	fn respond_to(self, request: &Request<'_>) -> response::Result<'r> {
		Json(self).respond_to(request)
	}
}
```

Thank you very much! Amazing response times and amazing project :sunglasses:
