### ISSUE TITLE
Minimum supported rust version incorrect

### ISSUE THREAD

**Issue by timokoesters** [SergioBenitez/Rocket#1654]
https://github.com/SergioBenitez/Rocket/blob/8d4d01106e2e10b08100805d40bfa19a7357e900/core/lib/build.rs#L6

The state crate uses unsafe_cell_get_mut which was stabilized in Rust 1.50:
https://github.com/SergioBenitez/state/blob/master/src/shim.rs#L41

https://caniuse.rs/features/unsafe_cell_get_mut

**Comment by SergioBenitez** [comment]
Yes, I'm aware. It'll be updated once we're ready for a release. Thanks!
