### ISSUE TITLE
How do I start multiple async servers from Rocket's `main`?

### ISSUE THREAD

**Issue by nicolasvac** [SergioBenitez/Rocket#1655]
Hello @SergioBenitez , i found rather difficult to understand how we can make software which spawns other things other than rocket.

I will provide my example:

I'm building a backend system which responds on port 443 with rocket for the public APIs, and spawns a tonic instance (grpc) on port 50000 for the internal communications.

To get around this, i've now created two binaries (http_server and grpc_server) which do call two different main files, one for rocket and one for tonic.

But this is causing me some problems on the gRPC side, i get all those kind of errors from rocket:

```
error: cannot find attribute `get` in this scope
  --> src/app/http/worlds_controller.rs:23:3
   |
23 | #[get("/<name>")]
   |   ^^^
```

I would like to know how to deal with issues, and also i would like to create a single main that spawns both the rocket instance, and the grpc instance, like:

```rust
fn main() {
 app::grpc::init().await;

 app::http::init().await;
}
```

My TOML configuration:

```toml
[[bin]]
name = "grpc"
path = "src/grpc_server.rs"

[[bin]]
name = "http"
path = "src/http_server.rs"
```

http_server.rs:

```rust
#[launch]
pub fn rocket() -> Rocket<Build> {
    println!("{} {} {}", "Hyperion HTTP".green(), "BigBox".blue(), env!("CARGO_PKG_VERSION").bright_red());

    tracing_subscriber::fmt().with_max_level(Level::INFO).init();

    dotenv::dotenv().ok();

    info!(".env file loaded");

    rocket::build().attach(app::http::init())
}
```

grpc_server.rs:
```rust
fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("{} {} {}", "Hyperion GRPC".green(), "BigBox".blue(), env!("CARGO_PKG_VERSION").bright_red());

    tracing_subscriber::fmt().with_max_level(Level::INFO).init();

    dotenv::dotenv().ok();

    info!(".env file loaded");

    app::grpc()
}

#[tokio::main]
pub async fn grpc() -> Result<(), Box<dyn std::error::Error>> {
    grpc::init().await
}
```

**Comment by SergioBenitez** [comment]
> I'm building a backend system which responds on port 443 with rocket for the public APIs, and spawns a tonic instance (grpc) on port 50000 for the internal communications.
> 
> To get around this, i've now created two binaries (http_server and grpc_server) which do call two different main files, one for rocket and one for tonic.

This is unnecessary. Use `tokio::spawn` to start the `tonic` instance. Something like this:

```rust
#[rocket::main]
fn main() {
    let rocket = rocket();
    let tonic = grpc::init();
    tokio::spawn(tokio::join!(rocket, tonic));
}
```

> But this is causing me some problems on the gRPC side, i get all those kind of errors from rocket:
> 
> ```
> error: cannot find attribute `get` in this scope
>   --> src/app/http/worlds_controller.rs:23:3
>    |
> 23 | #[get("/<name>")]
>    |   ^^^
> ```

You need to either `#[macro_use] extern crate rocket;` at the crate root in which you use Rocket or to do `use rocket::get;` (etc.) in each file. You now have two crate roots: `src/http_server.rs` and `src/grpc_server.rs".

> I would like to know how to deal with issues, and also i would like to create a single main that spawns both the rocket instance, and the grpc instance, like:
> 
> ```rust
> fn main() {
>  app::grpc::init().await;
> 
>  app::http::init().await;
> }
> ```

See my comment above.

**Comment by nicolasvac** [comment]
Hello @SergioBenitez , thank you for clarifying my questions.

I tried to implement your suggestions and this is what i get.

![Image](https://user-images.githubusercontent.com/45635090/120102583-04f87880-c14c-11eb-80e8-396551fa5e16.png)

This is my Cargo.toml:

```toml
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", features = ["json"] }

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket.git"
default-features = false
features = ["databases"]
```

**Comment by SergioBenitez** [comment]
Sorry, I misunderstood how `join` was expected to work. Just call spawn twice and then call join on the returned futures from each spawn.

```rust
let f1 = tokio::spawn(rocket.launch());
let f2 = tokio::spawn(grpc);

join!(f1, f2);
```

None of this is specific to Rocket. Please consult docs.rs/tokio.

**Comment by nicolasvac** [comment]
Thank you Sergio. Your answers were precious.

I will be transfering my questions to the tokio team.

Learning Rust the hard way from java and php.

Thank you and keep up the good work!

**Comment by SergioBenitez** [comment]
Sounds good! You may have an easier time asking questions on Tokio's or Rust's discord channels. GitHub issues are generally not a good place for questions.
