### ISSUE TITLE
request_guard_decl generates code that triggers clippy's used_underscore_binding

### ISSUE THREAD

**Issue by dspicher** [SergioBenitez/Rocket#1656]
When working on the current master tip and using `rocket::State<_>`, clippy complains along the following lines:
```
error: used binding `_e` which is prefixed with an underscore. A leading underscore signals that a binding will not be used
  --> my_lib/src/api.rs:17:9
   |
17 |     db: &rocket::State<crate::models::Db>,
   |         ^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#used_underscore_binding

```

I believe this was introduced [here](https://github.com/SergioBenitez/Rocket/commit/801e04bd5369eb39e126c75f6d11e1e9597304d8#diff-a600d4727489274c4dbe0720b3495afdff8718dfb9d8697470e2d0a0927d2987R125).

**Comment by SergioBenitez** [comment]
We generally don't change our codegen in response to clippy warnings when there is no logical issue, especially those under the `pedantic` group, and _especially_ those which are [known to have issues with generated code](https://rust-lang.github.io/rust-clippy/master/#used_underscore_binding). But this one's an easy fix which follows our codegen style anyway.
