### ISSUE TITLE
raw_sqlite example can be improved a little

### ISSUE THREAD

**Issue by adsick** [SergioBenitez/Rocket#1658]
Just a short proposal here:
1) ```examples/raw_sqlite``` features 0.14 version of rusqlite, while the actual version of the crate is 0.25 now
2) the current example won't compile with a fairly ugly linking error 1181 if sqlite is not installed, so it is better to either leave a note about installing a sqlite (and a link to instructions on how to do it properly) or just use **bundled** feature like so:
```toml
[dependencies.rusqlite]
version = "0.25.1"
features = ["bundled"]
```
3) I'm not a pro in this kind of questions, but using a Mutex<Connection> looks like a bottleneck even for me (I understand that this is not real world application, only an example, but still) we have to enforce rustaceans with best code quality&performance&safety practices!
4) maybe some other improvements

**Comment by SergioBenitez** [comment]
You're looking at the 0.4 branch which is 100s of commits behind master. None of these suggestions apply today.
