### ISSUE TITLE
rocket_contrib crate

### ISSUE THREAD

**Issue by marirs** [SergioBenitez/Rocket#1659]
Hi,
I'm using the rocket 0.5 from github, and now the rocket_contrib is a different crate. I was using rev = d03a07b1832a2491abf76212f76339f193adb910

where can I point now to the rocket_contrib

**Comment by SergioBenitez** [comment]
Please see https://github.com/SergioBenitez/Rocket/commit/5a4e66ec439411d30f16e5c045f8e4986f5883a4. Some features are now in core (https://api.rocket.rs/master) and some are new crates.

**Comment by marirs** [comment]
Thanks - got most of it migrated .. :)

Also the JsonValue from rocket_contrib is in rocket_dyn_templates::handlebars, just confirming.. :)

i would like to share this: https://github.com/marirs/rocketapi
where I have built a boiler plate of api using rocket, mongodb

**Comment by SergioBenitez** [comment]
> Thanks - got most of it migrated .. :)
> 
> 
> 
> Also the JsonValue from rocket_contrib is in rocket_dyn_templates::handlebars, just confirming.. :)


No, that value is gone. We use the real Value, in rocket::serde::json::Value.

**Comment by marirs** [comment]
Ahh.. perfect..
I changed to Value..
Thanks so much for you awesome support and this fantastic Rocket :)
