### ISSUE TITLE
Get `TempFile` contents without persisting it to disk (possibly second time)

### ISSUE THREAD

**Issue by ivan770** [SergioBenitez/Rocket#1661]
Hi! Is it possible to get `TempFile` without persisting it to disk? It looks like Rocket already has all the information about file to provide raw data:
https://github.com/SergioBenitez/Rocket/blob/dc5c57b624cebd52063c645e2de2e4cc978d960d/core/lib/src/fs/temp_file.rs#L103-L113
In case if enum value is `File`, we could read it from FS again. If `Buffered`, just return value.
While I could use those values in my project, I'm not sure that there are no missed caveats, since those variants are hidden from rustdoc.

**Comment by SergioBenitez** [comment]
The type does not implement read because it's almost certainly not what you want. That is, as a means to prevent likely inefficient behavior. The thinking is: if you are writing the data to the disk, why immediately read it out to some other location?￼ instead, the data should have been streamed to that location in the first place.￼

What is your use case?￼

**Comment by ivan770** [comment]
> The type does not implement read because it's almost certainly not what you want. That is, as a means to prevent likely inefficient behavior. The thinking is: if you are writing the data to the disk, why immediately read it out to some other location?￼ Instead, the data should have been streamed to that location in the first place.￼
> 
> There are valid use cases, however.￼￼ What is your use case?￼

Use case is uploading file to S3. I'm not sure if there is any point in re-saving the file, or even writing it onto the disk at all, if all I want is file bytes.

**Comment by SergioBenitez** [comment]
Got it. This is exactly what we want to prevent: streaming the data to disk only to stream it out elsewhere, in your case, S3.

You should write a custom data and/or form guard (`FromData`, `FromFormValue`) that streams the incoming data directly to S3, or as close as possible to doing so. Either guard has access to the "raw" (but fully decoded, limited) stream. I think it'd be nice if we provided a mechanism to do this kind of thing out of the box. I've opened #1662 to track this.

**Comment by ivan770** [comment]
> Got it. This is exactly what we want to prevent: streaming the data to disk only to stream it out elsewhere, in your case, S3.
> 
> You should write a custom data and/or form guard (`FromData`, `FromFormValue`) that streams the incoming data directly to S3, or as close as possible to doing so. Either guard has access to the "raw" (but fully decoded, limited) stream. I think it'd be nice if we provided a mechanism to do this kind of thing out of the box. I've opened #1662 to track this.

Thanks for response, closing in favour of this issue.
