### ISSUE TITLE
`.apk` is not a known file extension

### ISSUE THREAD

**Issue by paulzhang5511** [SergioBenitez/Rocket#1663]
1. The version of Rocket you're using. Ensure it's the latest, if possible.
       master
  2. The operating system (distribution and version) where the issue occurs.
       Ubuntu20.04
  3. A brief description of the bug that includes:
    * The nature of the bug.
     Framework of the bug.
    * When the bug occurs.
     When accessing a file with the suffix `.apk`, output the content instead of downloading the file.
   ```rust
#[get("/files/<file..>")]
async fn apk(file: PathBuf) -> Option<NamedFile> {
    NamedFile::open(Path::new("public/files/").join(file)).await.ok()
}
   ```
    * What you expected vs. what actually happened.
  The browser can download the file.

**Comment by SergioBenitez** [comment]
Are `.apk` and its associated media type registered with IANA?

**Comment by paulzhang5511** [comment]
How to set the media type in the rocket web framework? I do not found docs.

**Comment by fanninpm** [comment]
> The `.apk` file is a Android app.

The MIME type appears to be `application/vnd.android.package-archive`, [according to Wikipedia](https://en.wikipedia.org/wiki/Android_application_package). However, it doesn't seem to be registered with IANA.

**Comment by jebrosen** [comment]
When a media type is not registered with IANA, we generally don't add it to the built-in list.

If the main goal is to show a download prompt, something like this should work in all major browsers:

```rust
#[get("/files/<file..>")]
async fn apk(file: PathBuf) -> Option<(ContentType, NamedFile)> {
    NamedFile::open(Path::new("public/files/").join(file)).await.ok().map(|f| (ContentType::Binary, f))
}
```

If for some reason it really is necessary to use a special content type here, [rocket::response::content::Custom](https://api.rocket.rs/v0.5-rc/rocket/response/content/struct.Custom.html) can also be used.

**Comment by paulzhang5511** [comment]
OK. Thanks.
