### ISSUE TITLE
rocket_contrib::databases module not defined.

### ISSUE THREAD

**Issue by lukasdiegelmann** [SergioBenitez/Rocket#1664]
Hey, I want to connect my Rocket API with a MongoDB Atlas. I have managed to do so with [this](https://github.com/mongodb/mongo-rust-driver#platforms) crate. But since this is not the best way to do it in Rocket, I wanted to connect via the ´rocket_contrib´ method, which is way better integrated into the Rocket system.

Now, the [documentation](https://api.rocket.rs/v0.4/rocket_contrib/databases/index.html) of which tells me that, if I want to connect to MongoDB, I should use [that](https://github.com/mongodb-labs/mongo-rust-driver-prototype) driver. I also saw, that the `rocket_contrib` crate reexported this module. So I figured, why not just `use` it from there. And as [this](https://github.com/SergioBenitez/Rocket/issues/950#issuecomment-475100273) issue comment states, that should be easily possible.

That is where the problem arose. When I try to use said `use` statement in my `main.rs` file like this:

```
#![feature(proc_macro_hygiene, decl_macro)]
#![feature(format_args_capture)]

#[macro_use] extern crate rocket;
#[macro_use] extern crate rocket_contrib;

use rocket_contrib::databases; <--- here!

#[database("mongodb_logs")]
struct LogsDbConn(Database);

#[get("/")]
fn index() -> &'static str {
    "Hello World"
}

#[tokio::main]
async fn main() {
    rocket::ignite()
        .mount("/", routes![index])
        .attach(LogsDbConn::fairing())
        .launch();
}
```

I get the following error:
```
error[E0432]: unresolved import `rocket_contrib::databases`
 --> src\main.rs:7:5
  |
7 | use rocket_contrib::databases;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^ no `databases` in the root
```

Here's my `Cargo.toml` file:
```
[package]
name = "www"
version = "0.1.0"
authors = *removed
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.10"
dotenv = "0.15.0"

[dependencies.tokio]
version = "0.2"
features = ["full"]

[dependencies.rocket_contrib]
version = "0.4.10"
default-features = false
featuers = ["mongodb_pool"]
```

And my `Rocket.toml` file:
```
[development]
address = "localhost"
port = 8001
workers = 8
log = "normal"
limits = { forms = 32768 }

[staging]
adress = "0.0.0.0"
port = 80
workers = 8
log = "normal"
limits = { forms = 32768 }

[production]
adress = "0.0.0.0"
port = 80
workers = 8
log = "critical"
limits = { forms = 32768 }

[global.database]
mongodb_logs = { url = "mongodb+srv://*removed:*removed@cluster-0.mqf2m.mongodb.net/test" }
```

Help is very much appreciated!

**Comment by lukasdiegelmann** [comment]
# Update

With this `Cargo.toml` file I am able to take a step further:
```
[package]
name = "www"
version = "0.1.0"
authors = ["lukasdiegelmann <lukas.j.diegelmann@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.10"
dotenv = "0.15.0"
mongodb = "0.3.12" <-- used the listed version, which is not at all current...

[dependencies.rocket_contrib]
version = "0.4.10"
default-features = false
featuers = ["mongodb_pool"]
```

But now I am stuck at another place. Writing this in my `main.rs` file
```
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use]
extern crate rocket;
#[macro_use]
extern crate rocket_contrib;

use mongodb::db::Database;

#[database("mongodb_logs")]
struct DbConn(Database);

#[get("/")]
fn index() -> &'static str {
    "Hello, world!"
}

fn main() {
    rocket::ignite().mount("/", routes![index]).launch();
}
```

I get the following error:
```
error: cannot find attribute `database` in this scope
  --> src\main.rs:10:3
   |
10 | #[database("mongodb_logs")]
   |   ^^^^^^^^
```

So there is clearly something wrong with importing the module. I just cannot make out the issue. Is there maybe any feature I need to enable. The documentation says I do not. But coming to think of it, the documentation also told me that it would work with my first attempt. So what does it know...

**Comment by jebrosen** [comment]
I think you have a typo here with `featuers`:

```
featuers = ["mongodb_pool"]
```

**Comment by lukasdiegelmann** [comment]
Thank you, very much. Probably would've spend hours on this one....
