### ISSUE TITLE
MongoDB Atlas Support

### ISSUE THREAD

**Issue by lukasdiegelmann** [SergioBenitez/Rocket#1669]
# _Feature Request_: MongoDB Atlas Support

Currently `rocket` does not support the `mongodb+srv://` protocol for connection strings as stated by this error message that is found by trying it out anyway:

```
Error: Failed to initialize pool for 'mongodb_logs'
    => Error: Custom(ArgumentError("MongoDB connection string must start with 'mongodb://'."))
Error: Rocket failed to launch due to failing fairings:
    => 'mongodb_logs' Database Pool
```

This limits `rocket` to only local deploys of Mongo Databases, which is not quite desirable. Which brings me to the next point.

## Why I think this feature is necessary

This feature is necessary to make use of the cloud services provided by MongoDB, which are a very useful tool for building cloud-based applications. This might still be possible with some hosting providers, but most of them will only run the deployed applications on a temporal basis, meaning that the data will be deleted after one run.

This is where MongoDB Atlas comes in and still keeps running, since the part of the application that is run by the provider would only need to connect to the database and not store it locally in an temporal environment.

It also distributes the application across multiple servers, making it slightly more decentralized.

## A convincing use-case for this feature

I would consider my current situation as a use-case for this feature. Whether it is convincing or not is up to you.

I am trying to deploy my rust-code on an Heroku environment (with the one default `dyno`). This means that I will not be able to store my database in this environment. So I decided to opt for MongoDB Atlas. However, this lack of a feature now has arisen. I would be able to accomplish this cloud configuration with said feature.

## Why this feature can not or should not exist outside of Rocket

Do not get me wrong here: It is totally possible to connect with the `mongodb+srv://` protocol with the newest versions of the `mongodb` crate. The problem is that `rocket` does not support this in its current database implementations.

It should also be said that, although rocket needs to do something about this, `r2d2_mongodb` does not support Atlas connections, also. This will inevitably impose complications with the implementation of this feature. Thus, something has to be done there as well. I have already written a short [issue](https://github.com/armersong/r2d2-mongodb/issues/1#issue-911898965) there. Nevertheless, nobody seems to be responding there.

**Comment by SergioBenitez** [comment]
Please see #1617 and #1115.
