### ISSUE TITLE
TempFile doc not found

### ISSUE THREAD

**Issue by zemelLeong** [SergioBenitez/Rocket#1687]
![image](https://user-images.githubusercontent.com/26835087/121770973-240cf680-cb9f-11eb-87e2-0f790efeb42d.png)
![image](https://user-images.githubusercontent.com/26835087/121770980-2ff8b880-cb9f-11eb-8fd6-a3ae21d6231d.png)

**Comment by zemelLeong** [comment]
https://rocket.rs/master/guide/requests/#temporary-files

**Comment by SergioBenitez** [comment]
Master docs are behind the RC docs. See https://rocket.rs/v0.5-rc/guide/requests/#temporary-files.
