### ISSUE TITLE
Render a view file without any context

### ISSUE THREAD

**Issue by dumindu** [SergioBenitez/Rocket#169]
**Is there any way to render a tera view file without any context?**
```
#[get("/hello_template/")]
fn hello_template() -> Template {
    Template::render("main")
}
```
Get ```Template::render expected 2 parameters```

----

```
#[get("/hello_template/")]
fn hello_template() -> Template {
    Template::render("main", ())
}
```
Get ```expected type `&_` found type `()` ```

----

```
#[get("/hello_template/")]
fn hello_template() -> Template {
    Template::render("main", &())
}
```

No error when ```cargo build``` but when runnning ```cargo run```

```
=> GET /hello_template
Warning: GET /hello_template and GET /hello_template collide!
Warning: Route collisions detected!
Rocket has launched from http://localhost:8000...

GET /hello_template:
    => Matched: GET /hello_template
    => Error: Tera template 'main.tera' does not exist.
    => Outcome: Failure
    => Warning: Responding with 500 Internal Server Error catcher.
    => Response succeeded.
```

Even I had templates/main.tera

**Comment by mkroman** [comment]
The error `Error: Tera template 'main.tera' does not exist.` is unrelated to the context.

However, `Template::render("main", &())` will give the error `Error rendering Tera template 'main': Failed to value_render 'main.tera': context isn't an object`

I suspect this might be because [tera expects a valid json object](https://docs.rs/tera/0.7.0/src/tera/tera.rs.html#204-205) and most things can't be represented as a JSON object.

**Comment by dumindu** [comment]
something I have missed? 
https://pastebin.mozilla.org/8973142

**Comment by SergioBenitez** [comment]
Which version of Rocket are you using? Please make sure you're on the latest one: `v0.1.6`.

**Comment by dumindu** [comment]
I used v0.1.5. Also updated and checked but get the same error. Have I missed something on Cargo.toml ?

```
[dependencies]
rocket = "0.1.6"
rocket_codegen = "0.1.6"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["tera_templates"]
```

```
$ rustc -V
rustc 1.16.0-nightly (eedaa94e3 2017-02-02)
```
using rustup on Windows.

**Comment by SergioBenitez** [comment]
@dumindu Please see my updated comment above.

**Comment by dumindu** [comment]
Got it. Thanks @mkroman @SergioBenitez  for the effort and time to check this.
