### ISSUE TITLE
Try to use MySQL got an error

### ISSUE THREAD

**Issue by zemelLeong** [SergioBenitez/Rocket#1693]
Use this config. Execute `cargo run` got an error.
```
[dependencies]
rocket = {version = "0.5.0-dev", features = ["secrets", "tls", "json"]}
serde = { version = "1.0.126", features = ["derive"] }

[dependencies.rocket_contrib]
version = "0.4.10"
default-features = false
features = ["json", "diesel_mysql_pool"]
```
```
PS H:\rust-workspace\hello-rocket> cargo run
   Compiling mysqlclient-sys v0.2.4
   Compiling diesel v1.4.7
error: could not find native static library `mysqlclient`, perhaps an -L flag is missing?

error: aborting due to previous error

error: could not compile `mysqlclient-sys`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I have been installed mysql server and add the `mysqlclient.lib` path to the system environment variable.
![image](https://user-images.githubusercontent.com/26835087/121807660-ab359980-cc87-11eb-89f8-2a4d996bcb03.png)

**Comment by SergioBenitez** [comment]
Three things:

  1. There is no published `0.5.0-dev`, so I'm not sure how this code is building. Use the RC.
  1. Your `MYSQLCLIENT_LIB_DIR` should point to the MySQL connector, not the server.
  2. `rocket_contrib` is fully deprecated in 0.5. You _must_ migrate to `rocket_sync_db_pools` if you want to use Diesel in 0.5.

Nevertheless, this an issue with Diesel that has myriad issues on the subject online. A brief search yields many articles on the matter, the majority of which are related to Rocket directly. I would encourage you to do this search.
