### ISSUE TITLE
FromFormField::from_data forward to from_value, or something

### ISSUE THREAD

**Issue by ijackson** [SergioBenitez/Rocket#1695]
Hi.  I'm upgrading one of my applications from Rocket 0.4 to 0.5.  I have an observation and a feature/change request regarding `FromFormField`.

There are a good set of provided implementations of `FromFormField`.  There is of course the option to implement the trait by hand.  There is also the option to derive it for nested parameters.  But I use newtypes heavily to make my program typesafe and clearer internally.

Implementing `FromFormField` for a newtype wrapper around a small string or integer (or other similar small type) is quite inconvenient.  Chiefly, the problem is the need to provide an implementation of `from_data`.  Even if the implementation is no more than read into a string, and feed that to a string parser, the amount of boilerplate is considerable.

Or to put it another way, there is a gap between the very cooked provided implementations, and the very manual direct impl.  I think that gap consists of types which are parseable from strings (probably, smallish ones).

I would like a more convenient way to define such a `FromFormField` impl.  As a success criterion, it ought to make it easy to implement `FromFormField` for any type which is `FromStr`.  (But not *all* `FromStr` should be `FromFormField`, and possibly the `FromFormField` might be different to the `FromStr` - that should be up to the type's author.)

I have two suggestions for how to achieve this.  You may have a better idea.

 1. Have the default `from_data` read the data to a string, and forward to `from_value`, rather than erroring.  (Probably a smaller data limit would be a good idea.)

 2. Some kind of macro to generate a `from_data` impl.

Of these I think 1 is probably best.

To give you a flavour of what I am looking to improve, here is a fragment from in my proto-Rocket-0.5 branch right now (lightly edited, and it doesn't typecheck right now...):
```
impl<'i,Id> InstanceAccess<'i,Id>
  where Id: AccessId,
        form::Error: From<Id::Error>
{
  #[throws(form::Error<'i>)]
  fn from_str(s: &'i str) -> Self {
    /* actual code for generating an InstanceAccess from a string elided */
  }
}

impl<'v, Id> FromFormField<'v> for InstanceAccess<'v, Id>
  where Id: AccessId,
        form::Error: From<Id::Error>
{
  fn from_value(field: ValueField<'v>) -> Result<Self, form::Error<'v>> {
    InstanceAccess::from_str(FromFormField::from_value(field)?)?
  }

  fn from_data<'life0, 'async_trait>(
    field: DataField<'v, 'life0>
  ) -> Pin<Box<dyn Future<Output = form::Result<'v, Self>> + Send + 'async_trait>>
  where
    'v: 'async_trait,
   'life0: 'async_trait,
    Self: 'async_trait,
  {
    InstanceAccess::from_str(FromFormField::from_data(field).await?)?
  }
}
```

**Comment by SergioBenitez** [comment]
I generally agree. This is something I wanted to address before 0.5 but haven't gotten to yet. However, neither of your proposals are tenable. The first has coherence issues, while the second has no precedence in Rust or Rocket and thus likely unintuitive.

Nevertheless, your approach is more difficult than it needs to be. If you're just wrapping a type that already implements `FromForm`, you can just call the implementation directly. Assuming your `FromStr::Error` type implements `Into<Error>`, this is as simple as:

```rust
#[rocket::async_trait]
impl<'r> FromFormField<'r> for Token<'r> {
    fn from_value(field: ValueField<'r>) -> form::Result<'r, Self> {
        Ok(<&str>::from_value(field)?.parse()?)
    }

    async fn from_data(field: DataField<'r, '_>) -> form::Result<'r, Self> {
        Ok(<&str>::from_data(field).await?.parse()?)
    }
}
```

What I would like to support is the following, which would expand to the above except for a custom validation error message:

```rust
#[derive(FromForm)]
#[field(validate = with(Token::from_str, "Invalid token string.")]
struct Token<'r>(&'r str);
```

I'm curious what your `InstanceAccess<'i,Id>` looks like, exactly, however. Ideally this derive would support the vast majority of "wrapping"-like use-cases. Can you post the complete `struct` definition and 0.4 `FromFormValue` implementation?

**Comment by SergioBenitez** [comment]
I also want to point out that I _would_ eventually like to remove the need for both `from_value` and `from_data`, opting instead for a single `from_field`. The reason this doesn't happen today is because this would result in boxing for _every single_ field parse, which is rather unfortunate. This would also let you easily override the data limit for something like `&str`:

```rust
impl<'r> FromFormField<'r> for Token<'r> {
    async fn from_field(field: Field<'r>) -> form::Result<'r, Self> {
        let string = field.into_local_str("some/limit/name").await?;
        Ok(string.parse()?)
    }
}
```

**Comment by ijackson** [comment]
> I generally agree. This is something I wanted to address before 0.5 but haven't gotten to yet.

Thanks for looking at this.  Taking your comments out of order:

> I'm curious what your `InstanceAccess<'i,Id>` looks like, exactly, however. Ideally this derive would support the vast majority of "wrapping"-like use-cases. Can you post the complete `struct` definition and 0.4 `FromFormValue` implementation?

Sure.  Hold onto your hat!

```
#[derive(Clone,Debug)]
pub struct InstanceAccess<'i, Id> {
  pub raw_token: &'i RawTokenVal,
  pub i: InstanceAccessDetails<Id>,
}

impl<Id> InstanceAccessDetails<Id>
  where Id: AccessId, OnlineError: From<Id::Error>
{
  #[throws(OnlineError)]
  pub fn from_token(token: &RawTokenVal) -> InstanceAccessDetails<Id> { /* complex lookup */ }
}

#[derive(Hash,Ord,PartialOrd,Eq,PartialEq,Serialize)]
#[repr(transparent)]
pub struct RawTokenVal(str);

impl RawTokenVal {
  pub fn from_str(s: &str) -> &RawTokenVal { /* trivial */ }
}

impl<'r, Id> FromFormValue<'r> for InstanceAccess<'r, Id>
  where Id: AccessId, OnlineError: From<Id::Error>
{
  type Error = OnlineErrorResponse;
  #[throws(OnlineErrorResponse)]
  fn from_form_value(param: &'r RawStr) -> Self {
    let token = RawTokenVal::from_str(param.as_str());
    let i = InstanceAccessDetails::from_token(token)?;
    InstanceAccess { raw_token: token, i }
  }
}

#[derive(Error,Debug)]
#[error("{0}")]
pub struct OnlineErrorResponse(#[from] OnlineError);

impl From<&OnlineErrorResponse> for rocket::http::Status { ... }
```

Here `#[throws]` is from fehler and the attributes on
`OnlineErrorResponse` are from thiserror.


>  However, neither of your proposals are tenable. The first has coherence issues,

I'm confused.  Is this about my suggestion "Have the default from_data read the data to a string" ?  I don't think this raises any coherence issues.  Perhaps I wasn't sufficiently clear.  I'm suggesting something like this

```
    /// Parse a value of `T` from a form data field.
    ///
-   /// The default implementation returns an error of
-   /// [`DataField::unexpected()`].
+   /// The default implementation reads up to 512 bytes, converts
+   /// them to UTF-8, and calls `from_value`.  This is suitable for
+   /// types with a short string representation.  For longer types,
+   /// override this method.
    async fn from_data(field: DataField<'v, '_>) -> Result<'v, Self> {
-       Err(field.unexpected())?
+       ... field.data.peek() ... field.data.peek_complete() ...
+       ... from_utf8 ...
+       ... Self::from_value(...)
    }
```

I think this default impl wouldn't need to know anything about the actual type of T and I don't think it raises any trait coherence issues.

My alternative suggestion would be a macro which provides this implementation.  That is less legible but more flexibile; it would be possible to specify a custom data limit, box for when the limit was more than `peek` provides, etc.

> What I would like to support is the following, which effectively expands to the above except with a custom validation error message:
> 
> ```rust
> #[derive(FromForm)]
> #[field(validate = with(Token::from_str, "Invalid token string.")]
> struct Token<'r>(&'r str);
> ```

I think this would be good but I think changing the provided `from_data` to one which uses `peek` and `from_value` would be good too.  And the latter is quite easy :-).  I think it achieves most of the benefit of your `from_field` plan.

**Comment by SergioBenitez** [comment]
> I'm confused. Is this about my suggestion "Have the default from_data read the data to a string" ? I don't think this raises any coherence issues. Perhaps I wasn't sufficiently clear. I'm suggesting something like this

Sorry, I misunderstood what you were suggesting. The biggest issue here is that we have no idea what data limit to use. `peek()` reads at most 512 bytes. This may be more or less than the current maximum of a data field. I think this would be far too confusing even if it would be convenient.

> I think this would be good but I think changing the provided `from_data` to one which uses `peek` and `from_value` would be good too. And the latter is quite easy :-). I think it achieves most of the benefit of your `from_field` plan.

Note that the derive already exists. It needs minor extensions to be able to support that exact syntax. If you implemented `FromStr` (or anything `&str` -> `Token`), your use case would fit the solution, assuming you don't need a special data limit.

> My alternative suggestion would be a macro which provides this implementation. That is less legible but more flexibile; it would be possible to specify a custom data limit, box for when the limit was more than `peek` provides, etc.

The `#[derive(FromForm)]` _is_ this macro.

**Comment by ijackson** [comment]
Thanks for your comments.  I think I need to go away and look at this again, especially at `#[derive(FromForm)]`.  I will do that and report back, probably after a few days.

**Comment by univerz** [comment]
another motivating example to somehow handle Display / FromStr is (mongodb) bson::ObjectId.

due to previous rocket Form limitations i use custom wrapper type `Qs<T>` that serializes types using serde_qs & implements FromFormField + FromData.
it's serde compatible so i can use `serde_with` crate like this:

```
#[derive(Serialize, Deserialize, Debug, Default)]
pub struct Filter {
    #[serde(default, with = "As::<Option<DisplayFromStr>>")]
    id_user: Option<ObjectId>,
}

#[get("/ticket/listing?<filter>")]
pub async fn listing(
    filter: Option<Qs<crate::ticket::listing::Filter>>,
) -> AllResult {
    let mut filter = filter.map(|f| f.into_inner()).unwrap_or_default();

```

or

```
#[get("/history/ticket?<ticket_id>")]
pub async fn ticket(ticket_id: Qs<ObjectId>) -> AllResult {
    let ticket_id = ticket_id.into_inner();

```

in an ideal world i would like to use first example with rocket's `#[derive(FromForm)]` & get rid of `into_inner` in second exaple - serialization strategy could be encoded in url.

**Comment by SergioBenitez** [comment]
> due to previous rocket Form limitations i use custom wrapper type `Qs<T>` that serializes types using serde_qs & implements FromFormField + FromData.

This is a bad idea. Which limitations are you referring to? As far as I can tell, Rocket's form support is a superset of `serde_qs`. In fact, I haven't found a more flexible and robust implementation anywhere.

**Comment by univerz** [comment]
> Rocket's form support is a superset of serde_qs

yes, now it is (minus (de)serialization helpers?) & i'm looking to port from that abomination :). project from ~year ago; i needed nested forms in containers, easy handling of ObjectId & custom DateTime (de)serialization from/to string date was welcomed bonus.

**Comment by univerz** [comment]
looking through source code, these are attributes/helpers i use:
```
    #[serde(default, with = "As::<Option<DisplayFromStr>>")]
    id_user: Option<ObjectId>,
    #[serde(default, with = "datetime_dmy_opt")] // should rewrite it using composable serde_with
    tfrom: Option<DateTime<Utc>>,
    #[serde(skip)]
    data: FilterData,
```

`skip` is useful to store & reuse data between validation and rendering for example for selectbox with items stored in db

**Comment by SergioBenitez** [comment]
> looking through source code, these are attributes/helpers i use:
> 
> ```
>     #[serde(default, with = "As::<Option<DisplayFromStr>>")]
>     id_user: Option<ObjectId>,
>     #[serde(default, with = "datetime_dmy_opt")] // should rewrite it using composable serde_with
>     tfrom: Option<DateTime<Utc>>,
>     #[serde(skip)]
>     data: FilterData,
> ```
> 
> `skip` is useful to store & reuse data between validation and rendering for example for selectbox with items stored in db

Defaults are built into Rocket's form handling. Your `ObjectId` would just need to implement (likely derive) `FromForm` or `FromFormValue`.

There's direct support for `time::DateTime` as well. No need for an attribute.

There's no skipping yet, but I'm curious if you need it with the existence of `Context` and `Contextual`. Can you elaborate?

**Comment by univerz** [comment]
> Your ObjectId would just need to implement (likely derive) FromForm or FromFormValue.

sadly it's in third party `bson` (mongodb) crate.

> There's direct support for time::DateTime as well. No need for an attribute.

looks like it's not possible to use custom format, but i can live with that.

> But I'm curious if you need it with the existence of Context and Contextual. 

looking at the [example](https://github.com/SergioBenitez/Rocket/tree/master/examples/forms) mentioned in documentation, i'm not sure how it will help. more complete example:

```rust
#[derive(Serialize, Deserialize, Debug, Default)]
pub struct Filter {
    #[serde(default, with = "As::<Option<DisplayFromStr>>")]
    id_user: Option<ObjectId>,
    ...
 
    #[serde(skip)]
    data: FilterData,
}

#[derive(Debug, Default)]
struct FilterData {
    users: Vec<(ObjectId, String)>,
    ...

    doc: Document,
}


impl Filter {
    async fn init_and_validate(&mut self, me: ME, owner: &str, st: &AllState) -> Result<()> {
        self.data.users = st.users.get4selectbox(me, owner).await;
        if let Some(id_user) = self.id_user.as_ref() {
            self.data.users.iter().find(|u| u.0 == *id_user).context("invalid id_user")?;
            self.data.doc.insert("id_user", id_user);
        }
        ...

        Ok(())
    }

    fn render<'b>(&self, uri: String, tmpl: &mut TemplateBuffer<'b>) {
        tmpl << html! {
            form(action=uri, method="POST") {
                div(class="form-row align-items-center justify-content-center") {
                    div(class="col-auto") {
                        select(name="id_user", class="form-control") {
                            option(value="") : "User...";
                            @ for (id, login) in self.data.users.iter() {
                                option(value=id.to_string(), selected?=self.id_user.contains(id)) : login;
                            }
                        }
                    }
                    ...
                    div(class="col-auto") {
                        button(type="submit", class="btn btn-primary") : "Filter";
                    }
                }
            }
        };
    }
```

=> `filter.init_and_validate` loads and stores active users in `filter.data.users`, validates selected `id_user` & generates `filter.data.doc` (mongodb `Document`) that i than pass to my monstrous `Grid` component. `filter.data.users` are than used again in `form.render`. i'm using it more like component than POD - probably not as intended, but it's nicely encapsulated.

```rust
#[get("/ticket/listing?<grid_state>&<filter>")]
pub async fn listing(
    st: &State<AllState>,
    user: User,
    grid_state: Option<Qs<GridState<crate::mongo::ObjectId>>>,
    filter: Option<Qs<crate::ticket::listing::Filter>>,
    flash: Option<FlashMessage<'_>>,
) -> AllResult {
    let mut filter = filter.map(|f| f.into_inner()).unwrap_or_default();
    filter.init_and_validate(user.me, &user.owner, &st).await?;
    let grid = Grid::new(
        |state| uri!(listing(Some(state), Some(&filter))).to_string(),
        MongoModel { collection: st.get_owner_db(&user.owner).collection("ticket"), filter: filter.data.doc.clone() },
    ...
    render_with_filter(
        "Tickets",
        flash,
        &user,
        html! {
            |tmpl| {
                filter.render(uri!(listing_filter(Some(GridState { page: 0, sort, action: None }))).to_string(), tmpl);
            }
        },
        html! {
            : grid;
            : format!("{:#?}", filter.data.doc);
        },
    )
}
```

**Comment by SergioBenitez** [comment]
> > Your ObjectId would just need to implement (likely derive) FromForm or FromFormValue.
> 
> 
> 
> sadly it's in third party `bson` (mongodb) crate.

If it implements Deserialize, you can use a field of `Json<ObjectId>` to deserialize from a JSON representation. 


> > There's direct support for time::DateTime as well. No need for an attribute.
> 
> 
> 
> looks like it's not possible to use custom format, but i can live with that.

There is only one set of standard formats for HTTP forms. That is what we support. 

As for `FilterData`, I can't say I follow exactly what you're doing with it, but at a glance, it doesn't seem like there's a reason why it's a field of the form structure. This seems like concerns aren't being properly separated.

**Comment by univerz** [comment]
>  This seems like concerns aren't being properly separated.

from the POD de/serialization point of view it's true, but if you count in validation (& possibly rendering), than it is reasonable to expect that form should somehow store (valid) selectbox values. however, i can pass that data around, it's just tedious.

**Comment by univerz** [comment]
> If it implements Deserialize, you can use a field of Json<ObjectId> to deserialize from a JSON representation.

thank you, `Json` looks great :). aside from some issues around my generic `Grid` component (
```implementation of `FromForm` is not general enough\n`Tid` must implement `FromForm<'_>`\n...but it actually implements `FromForm<'__f>```?), it looks like that the only thing i will need  is `impl UriDisplay` for `Json` & `Date`.

**Comment by univerz** [comment]
it looks like the problem with lifetimes is in DeserializeOwned? ( + it would be great if `Json` could have `#[derive(Clone)]`.)

minimal example:

```rust
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use rocket::{
    form::{Form, FromForm},
    response::Redirect,
    serde::json::Json,
};

#[derive(Deserialize, Serialize, Clone)]
struct Id;

// #[derive(UriDisplayQuery, Clone)]
#[derive(FromForm, Debug)]
pub struct Generic<Tid>
where
    Tid: DeserializeOwned + Serialize + Clone,
{
    // t: Option<Date>,
    id: Json<Tid>,
}

#[post("/test_form", data = "<filter>")]
pub async fn test_form<'r>(filter: Form<Generic<Id>>) -> Redirect {
    // Redirect::to(uri!(test_query(Some(filter.into_inner()))))
    todo!()
}

#[get("/test_query?<filter>")]
pub async fn test_query(filter: Option<Generic<Id>>) -> String {
    todo!()
}
```

**Comment by SergioBenitez** [comment]
@univerz The derive didn't really support type generics, but it does now. This should just work:

```rust
#[derive(FromForm, UriDisplayQuery, Clone, Debug)]
pub struct Generic<Tid> {
    id: Json<Tid>,
}
```

**Comment by univerz** [comment]
thank you @SergioBenitez! getting really close :).

if you uncomment line with `Redirect` == generate url, you will see that rocket is forcing `UriDisplay` on `Id`. i have noticed commit where you implemented:

`impl<T: fmt::UriDisplay<fmt::Query>> fmt::UriDisplay<fmt::Query> for Json<T> {`

but for `Json<T>` to work as workaround wrapper around serde (de)serializable types, i'll need:

`impl<T: Serialize> fmt::UriDisplay<fmt::Query> for Json<T> {`

but there is something else going on around `FromUriParam`, i'm not sure what to do. i have expanded example to include `Json<Id>` as simplified parameter:

```rust
#[derive(Deserialize, Serialize, Clone)]
pub struct Id;

#[derive(UriDisplayQuery, Clone, FromForm, Debug)]
pub struct Generic<Tid: Serialize> {
    t: Option<Date>,
    id: Json<Tid>,
}

#[post("/test_form", data = "<filter>")]
pub async fn test_form<'r>(filter: Form<Generic<Id>>) -> Redirect {
    Redirect::to(uri!(test_query(Some(filter.into_inner()), Id)))
}

#[get("/test_query?<filter>&<id>")]
pub async fn test_query(filter: Option<Generic<Id>>, id: Json<Id>) -> String {
    todo!()
}
```

& comparing with my `Qs` hack, it looks like i need `impl<T: Serialize> FromUriParam<Query, T> for Json<T>` (+ for `&T` & `Json<T>` for ergonomics). with that `Json<Id`> works, but it's not enough for `Option<Generic<Id>>` (but works for Generic without type parameter & `id: Json<Id>`).

**Comment by SergioBenitez** [comment]
> but for `Json<T>` to work as workaround wrapper around serde (de)serializable types, i'll need:
> 
> `impl<T: Serialize> fmt::UriDisplay<fmt::Query> for Json<T> {`

This isn't possible. `T` _must_ implement `fmt::UriDisplay<fmt::Query>`. Implementing `UriDisplay<Query>` isn't necessary for implementing `FromForm`. There is no workaround and there will never be. If you need to, you should implement `UriDisplay<Query>` for your wrapper type manually.

> but there is something else going on around `FromUriParam`, i'm not sure what to do. i have expanded example to include `Json<Id>` as simplified parameter:

Please see the docs. Specifically, https://api.rocket.rs/v0.5-rc/rocket/http/uri/fmt/trait.FromUriParam.html and https://api.rocket.rs/v0.5-rc/rocket/http/uri/fmt/trait.UriDisplay.html. The error message you're getting is an unfortunate message that rustc emits.

**Comment by univerz** [comment]
> This isn't possible. 

hmm, this part actually works & i have tested it (together with `FromUriParam`).

in `form::FromFormField<'v> for Json<T>` rocket expects `T` serialized as json string & `UriDisplay` looks like a place where the symetric serialization should be done for `T` when using `Json` as query parameter. otherwise rocket generates invalid url like `"/test_query?filter.f=foo"` when `"/test_query?filter=%7B%22f%22:%22foo%22%7D"` is expected.

```rust
#[derive(UriDisplayQuery, Serialize, Deserialize, Debug)]
pub struct F {
    f: String,
}
#[get("/test_query?<filter>")]
pub async fn test_query(filter: Json<F>) -> () {
    dbg!((filter, uri!(test_query(F { f: "foo".to_string() })).to_string()));
}
```

**Comment by univerz** [comment]
> If you need to, you should implement UriDisplay<Query> for your wrapper type manually.

to clarify, i'm trying to use `Json<T>` as the wrapper that would work everywhere & for every datatype that derives serde, when it's not possible or a good idea to derive Rockets custom (de)serialization traits.

**Comment by SergioBenitez** [comment]
> in `form::FromFormField<'v> for Json<T>` rocket expects `T` serialized as json string & `UriDisplay` looks like a place where the symetric serialization should be done for `T` when using `Json` as query parameter. otherwise rocket generates invalid url like `"/test_query?filter.f=foo"` when `"/test_query?filter=%7B%22f%22:%22foo%22%7D"` is expected.

You're absolutely right! I'll be pushing a fix shortly.

> to clarify, i'm trying to use `Json<T>` as the wrapper that would work everywhere & for every datatype that derives serde, when it's not possible or a good idea to derive Rockets custom (de)serialization traits.

I just want to note that you should only use `Json<T>` in this way sparingly as it comes at a (relatively) rather high cost in all directions. For instance, the `UriDisplay` implementation indeed has to first serialize into JSON (an allocation), then percent encode (another allocation), and then write out the string.

**Comment by univerz** [comment]
> I'll be pushing a fix shortly.

thanky you :). i have noticed some relevant commits, is it expected to work? if yes, could you please try this slightly expanded previous example?

```rust
use rocket::{
    form::{Form, FromForm},
    serde::json::Json,
};
use serde::{Deserialize, Serialize};
use time::Date;

#[derive(Deserialize, Serialize, Clone, Debug)]
pub struct Id;

#[derive(UriDisplayQuery, Clone, FromForm, Debug)]
pub struct Generic<Tid> {
    t: Option<Date>,
    id: Json<Tid>,
}

#[post("/test_form", data = "<filter>")]
pub async fn test_form<'r>(filter: Form<Generic<Id>>) -> () {
    let filter = Some(filter.into_inner());
    uri!(test_query(filter, Json(Id)));
    uri!(test_query(filter, Id));
    uri!(test_query(filter, Json(&Id)));
    uri!(test_query(filter, &Id));
}

#[get("/test_query?<filter>&<id>")]
pub async fn test_query(filter: Option<Generic<Id>>, id: Json<Id>) -> String {
    todo!()
}
```

(rocket rev = "416f42b")
```
error: invalid type bounds: expected `,`
  --> allnet/src/ticket/listing.rs:39:5
   |
39 |     id: Json<Tid>,
   |     ^^^^^^^^^^^^^
```

\+ `FromUriParam` errors - for `Json<Id>` it's simple, but error for `Generic` is what puzzled me a few comments back.

**Comment by SergioBenitez** [comment]
> thanky you :). i have noticed some relevant commits, is it expected to work? if yes, could you please try this slightly expanded previous example?

No, but now it is.

**Comment by univerz** [comment]
> now it is.

wow, i was really worried about that problem with Generic.

but there is still one missing piece for `Json<T>`. inspired with code for `Option<T>` i have implemented something like this for my qs wrapper, probably it's possibel to write it better:


```rust
impl<T: Serialize> uri::fmt::FromUriParam<uri::fmt::Query, Json<T>> for Json<T> {
    type Target = Json<T>;

    #[inline(always)]
    fn from_uri_param(param: Json<T>) -> Self::Target {
        param
    }
}

impl<T: Serialize> uri::fmt::FromUriParam<uri::fmt::Query, T> for Json<T> {
    type Target = Json<T>;

    #[inline(always)]
    fn from_uri_param(param: T) -> Self::Target {
        Json(param)
    }
}

impl<'a, T: Serialize> uri::fmt::FromUriParam<uri::fmt::Query, &'a T> for Json<T> {
    type Target = Json<&'a T>;

    #[inline(always)]
    fn from_uri_param(param: &'a T) -> Self::Target {
        Json(&param)
    }
}
```

with that my example & probably all other code will work.

**Comment by univerz** [comment]
porting going well, but i have just found one small difference in deserialization - for type `s: Option<String>` & data `s=` (== empty value in selectbox), rocket decodes `Some("")`, but serde_qs `None`. i understand rocket's point of view, but `None` behaviour is somewhat nicer - there is no need to check for emptyness & when later used in url as query parameter, serialization can be skipped

**Comment by SergioBenitez** [comment]
> but there is still one missing piece for `Json<T>`. inspired with code for `Option<T>` i have implemented something like this for my qs wrapper, probably it's possibel to write it better:

Yes, these impls are indeed missing.

> porting going well, but i have just found one small difference in deserialization - for type `s: Option<String>` & data `s=` (== empty value in selectbox), rocket decodes `Some("")`, but serde_qs `None`. i understand rocket's point of view, but `None` behaviour is somewhat nicer - there is no need to check for emptyness & when later used in url as query parameter, serialization can be skipped

This is not accidental or by happenstance: this is what's specified by the [WHATWG standard](https://url.spec.whatwg.org/#urlencoded-parsing). The `serde_qs` implementation does not conform.

**Comment by SergioBenitez** [comment]
In any case, the `FromUriParam` impls are now in `master`.

**Comment by univerz** [comment]
thank you :)

>  use Json<T> in this way sparingly as it comes at a (relatively) rather high cost

i'm trying to minimize it & push Json as down as possible - most ot the time it's simple enum & even with structs the other converted parts made uri rendering significantly faster, i'm really impressed.
