### ISSUE TITLE
How do I get the URI's host in a request handler?

### ISSUE THREAD

**Issue by WilliamVenner** [SergioBenitez/Rocket#1699]
Hi,

I'm trying to setup my Rocket application for Sign in through Steam. For this I need to provide a URL to redirect the user back to from Steam.

Currently, it does not appear to be possible to get the URI's host inside a request handler, which is needed for me to form this redirect URI.

E.g., if my request handler is registered for `GET https://example.com/auth`, I need to extract `example.com` from the URI.

It appears that `Origin` does not provide this information.

**Comment by WilliamVenner** [comment]
Here is my current solution

```rust
#[derive(Debug)]
pub struct Host<'r>(Option<&'r str>);

#[rocket::async_trait]
impl<'r> FromRequest<'r> for Host<'r> {
	type Error = ();

	async fn from_request(request: &'r rocket::Request<'_>) -> rocket::request::Outcome<Self, Self::Error> {
		rocket::request::Outcome::Success(Host(request.headers().get("host").next()))
	}
}
```

**Comment by WilliamVenner** [comment]
I suppose it would also be useful to get the URI scheme.

**Comment by SergioBenitez** [comment]
An origin form URI, by definition, contains only a path and maybe a query. So it, of course, does not contain a scheme or host.

In general, an HTTP/1.1 request will target an origin form URI, and so there is no host information available. The `Host` header is designated as containing this information. In HTTP/1.1, the host information is part of the request URI. There is no `Host`; the header is indeed illegal. This variance is why Rocket doesn't yet expose a mechanism.

Nevertheless, I did indeed plan on providing a `host()` method on `Request` that abstracted these differences away. We'll see that soon. Thanks for the reminder.
