### ISSUE TITLE
Problem Adding Cors to Rocket v0.5-rc

### ISSUE THREAD

**Issue by tolumide-ng** [SergioBenitez/Rocket#1701]
First, Thank you for the wonderful work on the `Rocket` web framework.

I have tried checking this out on StackOverflow and issues/PRs on Rocket and Rocket_cors but nothing really helping at the moment. The closest I got is a deleted question on [stackoverflow](https://stackoverflow.com/questions/67478789/how-do-i-disable-cors-in-rust-rocket-v-0-5). 
I am new to Rocket.

I am using a macOS Big Sur (version 11.3.1)

### Applicable dependencies:
```
rocket = { version = "0.5.0-rc.1", features = ["secrets", "json"] }
rocket_cors = { version = "0.5.2", default-features = false }
dotenv = "0.15.0"
```

### My code:
```
#[get("/")]
fn todo() -> Json<ResponseBody> {
    Json(ResponseBody {
        status_code: 200,
        message: "Hello World".to_owned(),
    })
}

pub fn db_config<'a>() -> Figment {
    //
}


#[database("recs_db")]
pub struct RecsDbConn(diesel::PgConnection);


fn cors_fairing() -> Cors {
    Cors::from_options(&CorsOptions::default()).expect("Cors Fairing cannot be created")
}


#[launch]
pub fn rocket() -> _ {
    dotenv().ok();

    rocket::custom(db_config())
        .mount("/", routes![todo])
        .attach(cors_fairing())
        .attach(RecsDbConn::fairing())
        .register("*", catchers![not_found, internal_error])
}

```

### Error:
I keep getting this `error` from my IntelliSense 
```
the trait bound `rocket_cors::Cors: rocket::fairing::Fairing` is not satisfied

the trait `rocket::fairing::Fairing` is not implemented for `rocket_cors::Cors`

note: perhaps two different versions of crate `rocket` are being used?rustc(E0277)
lib.rs(60, 17): the trait `rocket::fairing::Fairing` is not implemented for `rocket_cors::Cors`
```

### What have I tried:
I have tried various methods to resolve the problem including 
1. The example illustrated on [rocket_cors](https://github.com/lawliet89/rocket_cors/blob/master/examples/fairing.rs)

2.  The [realworld](https://github.com/TatriX/realworld-rust-rocket/blob/master/src/lib.rs) example using the same version of `rocket_cors` but `0.5-rc` for `rocket`

3. Described approach on [rocket_cors](https://docs.rs/rocket_cors/0.5.2/rocket_cors/) v0.5.2 documentation

4. I have tried using two versions of `rocket_cors` specifically `0.5.1` and `0.5.2`

**Comment by SergioBenitez** [comment]
The `rocket_cors` crate is not a product of the Rocket project. Their issue tracker would be the right place to ask. That being said, I'm fairly certain this is simply a matter of dependency versions. The versions of `rocket` depended on by both `rocket_cors` and your crate must match. Otherwise, even if two types exported from Rocket have the same name, they are (to the Rust compiler) logically different types.

**Comment by tolumide-ng** [comment]
Thank you for the information @SergioBenitez, They both share the same version of `rocket`. I would use the `rocket_cors` crate issue.

**Comment by jebrosen** [comment]
> They both share the same version of rocket.

To avoid causing confusion for anyone else: no, the version of rocket really is different. `rocket_cors` 0.5 depends on `rocket 0.4`, not `0.5.0-rc`. At the time I am writing this, there is no version of `rocket_cors` on crates.io that uses `rocket 0.5.0-rc`.

What led you believe that `rocket_cors` used `rocket 0.5.0-rc`? That source of information should be corrected if possible.

**Comment by tolumide-ng** [comment]
@jebrosen You're right, apologies about that. I was only using the current `[master](https://github.com/lawliet89/rocket_cors/blob/master/Cargo.toml)` branch on Github as against the actual release `rocket_cors-0.5.2` which uses `rocket v0.4.2`. Thank you for clearing this.
