### ISSUE TITLE
`/route/<optional>` does not work (HTTP 404)

### ISSUE THREAD

**Issue by WilliamVenner** [SergioBenitez/Rocket#1705]
Version: `0.5.0-rc.1`

This route returns a HTTP 404 when navigating to `/route` or `/route/`, but works when navigating to `/route/blah`

```rust
#[get("/route/<param>")]
pub fn optional_param(param: Option<String>) {

}
```

**Comment by SergioBenitez** [comment]
That's by the design. The parameter cannot be empty. The `Option` does not change the semantics.
