### ISSUE TITLE
Implement Clone for NamedFile

### ISSUE THREAD

**Issue by clay53** [SergioBenitez/Rocket#1724]
Hello, and thanks for opening a new issue about Rocket!

Before opening your issue, we ask that you search through existing issues and
pull requests to see if your bug report, concern, request, or comment has
already been addressed. Ensure to search through both open and closed issues and
pull requests. If this is a question, feature request, or general comment,
please ensure that you have read the relevant sections of the documentation
before posting your issue. Finally, consider asking questions on IRC or Matrix
before opening an issue.

If you feel confident that your issue is unique, please include the following
information, selecting the category that best describes your issue:

## Feature Requests

Feature requests _must_ include: implement Clone for rocket::fs::NamedFile

  1. Why you believe this feature is necessary.
It is useful for operations like caching while keeping the niceties of using NamedFile.
  2. A convincing use-case for this feature.
Using [cached](https://github.com/jaemk/cached) for caching route functions (works otherwise without issues as far as I can tell btw - must put it after path), requires the Clone trait but NamedFile does not have it creating the need for the user to implement their own workaround.
  3. Why this feature can't or shouldn't exist outside of Rocket.
One cannot implement traits on external crate structs. Even if one'd be able to, it's easier to just have it.

**Comment by SergioBenitez** [comment]
`File` is not `Clone`, so `NamedFile` cannot be `Clone`. This really seems like trying to work around a limitation of some other library. I see no reason why return types would need to be `Clone` for such utility.
