### ISSUE TITLE
Best way to fetch configuration only once?

### ISSUE THREAD

**Issue by mlieberman85** [SergioBenitez/Rocket#173]
I'm still fairly new to Rust and Rocket so I hope I'm not missing something obvious.

I want to retrieve some entries from configuration once without needing to retrieve them every time the route is called. I also don't want to put the same snippet of code to fetch various config values or default to a constant for every config value for every route I need.

Below is an example building from the static_files example:

```
#![feature(plugin)]
#![plugin(rocket_codegen)]

extern crate rocket;

use std::io;
use std::path::{Path, PathBuf};

use rocket::response::NamedFile;
use rocket::config;

const DEFAULT_STATIC_DIR: &'static str = "static";

#[get("/")]
fn index() -> io::Result<NamedFile> {
	let static_dir = config::active().map(|config| {
	    let dir = config.get_str("static_dir")
	        .map_err(|e| if !e.is_not_found() { e.pretty_print(); })
	        .unwrap_or(DEFAULT_STATIC_DIR);

    config.root().join(dir).to_string_lossy().into_owned()
	}).unwrap_or(DEFAULT_STATIC_DIR.to_string());

    NamedFile::open(format!("{}/index.html", static_dir))
}

#[get("/<file..>")]
fn files(file: PathBuf) -> Option<NamedFile> {
    NamedFile::open(Path::new("static/").join(file)).ok()
}

fn main() {
    rocket::ignite().mount("/", routes![index, files]).launch();
}
```

If I want to also retrieve the `static_dir` from the config in the files route I would have to put in the same code to retrieve the value from the config or default to the constant.

I attempted to use managed state but from what I can tell the Rocket struct containing config and state gets initialized at launch time meaning I couldn't put the loading of the config in the main function before launch.

What is the best way to approach this?

**Comment by SergioBenitez** [comment]
You can certainly use managed state for this. The config gets initialized on ignition, not launch. So you can do something like:

```
let rocket = rocket::ignite();

let config = /* your init here */;

rocket.mount(...)
    .manage(config)
    .launch()
```

**Comment by mlieberman85** [comment]
Thanks, I must have misread the code. That worked!
