### ISSUE TITLE
Detect Event Stream closed

### ISSUE THREAD

**Issue by iMplode-nZ** [SergioBenitez/Rocket#1731]
I'm making a game and I want to delete the player information once the `EventStream` the player gets events from is closed.

**Ideal Solution**

I don't know async stuff much so I'm not sure. The event close handler might just work as another one of the `rocket` handler methods that can take in the `State<>` parameters.

**Comment by iMplode-nZ** [comment]
Perhaps something like this:

```rs
fn create_stream() -> EventStream![] {
  EventStream! ({
    yield "foo";
    yield "bar";
    yield "baz";
  }, cleanup)
}

fn cleanup(players: &State<Players>) {
  
}
```

**Comment by SergioBenitez** [comment]
This is already possible by implementing a `Drop` guard. Modifying the `chat` example, this looks like:

```rust
struct Guard<'r>(&'r State<Sender<Message>>);

impl Drop for Guard<'_> {
    fn drop(&mut self) {
        self.0.send(Message::default());
    }
}

#[get("/events")]
async fn events(queue: &State<Sender<Message>>) -> EventStream![Event + '_] {
    EventStream! {
        let _guard = Guard(queue);
        loop {
            yield ...;
        }
    }
}
```

(The `EventStream![Event + '_]` syntax will be supported in `master` shortly.)

You can also accomplish the same thing by implementing a custom `Responder` or `Stream` with a `Drop` impl.

There are a couple of issues:
  1. This is a rather advanced concept.

  2. Rust has no `async` `Drop`, so this requires spawning a task in `Drop` if `async` work is needed. This, in-turn, means that `'static` data has to be moved into the `async` function passed to spawn. For types like `broadcast::Sender` (which doesn't actually require `async`) which are already internally an `Arc`, this is fine. But for other types, an `Arc<T>` will be needed.

     ```rust
     impl Drop for Guard<'_> {
         fn drop(&mut self) {
             let async_thing: Arc<Foo> = self.0.inner().clone();
             rocket::tokio::task::spawn(async move {
                 async_thing.do_async().await;
             });
         }
     }
     ```

The rest of this comment describes possible approaches to implementing a generic interface without the above drawbacks.

One alternative is for Rocket to call a function when a response is done being written or the remote disconnected. This would  require changing `Response` itself. This should be relatively straightforward, but exposing an API to make this usable outside of custom responders is slightly less so. For example, it would be nice to write the `async` example above like: 

```rust
#[get("/events")]
async fn events(thing: &State<AsyncThing>) -> EventStream![Event + '_] {
    let stream = EventStream! {
        loop {
            yield ...;
        }
    };

    stream.finalized(async move {
        thing.do_async().await;
    })
}
```

It _might_ be possible to create a `Finalized` `Responder` which would simply set the finalizing function on `Response`. Then, the above example could be written:


```rust
#[get("/events")]
async fn events(thing: &State<AsyncThing>) -> Finalized<EventStream![Event + '_]> {
    let stream = EventStream! {
        loop {
            yield ...;
        }
    };

    stream.finalized(async move {
        thing.do_async().await;
    })
}
```

Or, even, if we implement `Stream` for `Finalized`, then `Finalized` can become the inner stream of `EventStream` (and friends) and things would just work.

Mostly, we're papering over the fact that Rust has no `async` `Drop`.

**Comment by iMplode-nZ** [comment]
Couldn't you instead write the last example as `async fn events(thing: &State<AsyncThing>) -> impl Responder`? That would be a bit simpler and not require people to know what the type of the output `finalised` is.

**Comment by SergioBenitez** [comment]
> Couldn't you instead write the last example as `async fn events(thing: &State<AsyncThing>) -> impl Responder`? That would be a bit simpler and not require people to know what the type of the output `finalised` is.

This is _highly_ discouraged in Rocket. Please don't write code like that. It obfuscates the return type making it both harder to understand what the route does at a glance and certain static analyses (like sentinel discovery) impossible.

**Comment by iMplode-nZ** [comment]
Hmm maybe `impl Responder<Output = EventStream![]>`?

**Comment by SergioBenitez** [comment]
> Hmm maybe `impl Responder<Output = EventStream![]>`?

That is both longer than the alternative and incorrect.

**Comment by iMplode-nZ** [comment]
Well if the `Finalized` type also has to take in the closure, and you can't write out the closure type... Also having an `Output` property makes it less messy to pile up wrappers.

**Comment by SergioBenitez** [comment]
That is not what my example showed. You would literally write `Finalized<R>` where `R` is the type of the responder. In this context, that would be `Finalized<EventStream![]>` or, if the `EventStream` itself is borrowing (which in your example, it is not), `Finalized<EventStream![Event + '_]>`.

The finalizing function would be converted into a dynamically dispatching type internally.

**Comment by iMplode-nZ** [comment]
Oh it uses `Box<dyn FnMut>` instead of `impl FnMut` like normal iterators.
