### ISSUE TITLE
Is Freenode IRC still used?

### ISSUE THREAD

**Issue by Shadlock0133** [SergioBenitez/Rocket#1733]
Rocket's website and readme currently point to IRC channel on Freenode server. Is this still the case, or has it been moved to other server (like Libera)?

**Comment by jebrosen** [comment]
The bridged channel did move to [libera.chat](https://kiwiirc.com/client/irc.libera.chat/#rocket).

See also #1690, which updates the website to reflect this.

**Comment by SergioBenitez** [comment]
Please ask questions in discussions in the future.
