### ISSUE TITLE
Docs: Link to JSON example not working

### ISSUE THREAD

**Issue by palango** [SergioBenitez/Rocket#1742]
**Description**

In the 0.5rc docs, the link to the JSON example is not working: https://rocket.rs/v0.5-rc/guide/requests/#json

**To Reproduce**

Click the link.

**Expected Behavior**

Should link to the mentioned example.

**Additional Context**

I don't find the json example in the examples folder any more.

**Comment by SergioBenitez** [comment]
This is already fixed in master.
