### ISSUE TITLE
Some macros don't show up in documentation

### ISSUE THREAD

**Issue by Garmelon** [SergioBenitez/Rocket#1751]
**Description**

When building documentation for rocket via `cargo doc`, the macros `request::local_cache`, `outcome::try_outcome`, `fs::relative` and `rocket::form::validate::msg` don't show up. There may be other macros that also don't show up, but so far I haven't found any.

While they don't show up in the documentation, they can still be used if imported.

I've tried to build documentation for rocket 0.5.0-rc.1 as a dependency of another project and for rocket master@efce2bc958d25065584ce01982ff4f1dd9c84750 by cloning and running `cargo doc` in both the project root and in `core/lib`.

**To Reproduce**

```
git clone https://github.com/SergioBenitez/Rocket.git
cd Rocket/
cargo doc --open
```

**Expected Behavior**

The macros are visible in the generated documentation.

**Environment:**

 - OS Distribution and Kernel: Ubuntu 5.8.0, Arch 5.10.47
 - Rocket Version: 0.5.0-rc.1, master@efce2bc958d25065584ce01982ff4f1dd9c84750

**Additional Context**

The macros show up correctly in https://api.rocket.rs/master/rocket/index.html.

**Comment by Garmelon** [comment]
I'm a bit blind apparently. The macros appear but as reexports that don't get picked up by the search and have no documentation attached:
![image](https://user-images.githubusercontent.com/11077553/124893025-ab9d2800-dfda-11eb-9ded-b94037a80925.png)

I was looking for something that looks like this, and must have missed the "Re--xports" section. 
![image](https://user-images.githubusercontent.com/11077553/124893388-fa4ac200-dfda-11eb-9312-0b638b321066.png)

**Comment by SergioBenitez** [comment]
Due to bugs in rustdoc and limitations in rustc, we export macros in a very peculiar way. Suffice to say that docs need to be built with nightly to be rendered correctly.

**Comment by Garmelon** [comment]
Thanks for the info. With nightly, everything shows up like it should.
