### ISSUE TITLE
[`0.5-rc1`]: `Into<Status> for hyper::StatusCode` is missing

### ISSUE THREAD

**Issue by ShadowJonathan** [SergioBenitez/Rocket#1755]
**Is your feature request motivated by a concrete problem? Please describe.**

In previous development versions of Rocket 0.5, `Into<Status> for hyper::StatusCode` existed, this was used by one of the codepaths in a library, yet with `rc1`, this conversion is missing.

**Why this feature can't or shouldn't live outside of Rocket**

This conversion seems very obvious and trivial to implement to me, as `StatusCode` is a `NonNullU16` internally and `Status` works around a `u16` field.

**Ideal Solution**

Re-implement `Into<Status> for hyper::StatusCode`

**Alternatives Considered**

Don't, though this will make the conversion `Status::new(statuscode.as_u16())` instead of `.into()`

**Additional Context**

This behaviour was previously used in [conduit](https://gitlab.com/famedly/conduit), while trivial to replace, it's still an obvious conversion in my eyes.

**Comment by jebrosen** [comment]
> In previous development versions of Rocket 0.5, `Into<Status> for hyper::StatusCode` existed, this was used by one of the codepaths in a library, yet with `rc1`, this conversion is missing.

I can't find a relevant-looking `From` impl for either `Status` or `StatusCode` anywhere in the git history, so there might be something more subtle going on here. Do you have a commit hash (from a lockfile) and/or code demonstrating how/when this worked?

**Comment by ShadowJonathan** [comment]
```

**Comment by ShadowJonathan** [comment]
(whoops)

```toml
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", rev = "801e04bd5369eb39e126c75f6d11e1e9597304d8", features = ["tls"] } # Used to handle requests
```

this is the line we have in `Cargo.toml`

**Comment by the10thWiz** [comment]
This is not actually converting `hyper::StatusCode` into `Status`, although that may not be obvious. `raw_status` actually takes it's argument as a `u16`, so here the status is being converted into a u16 and passed to Rocket.

**Comment by ShadowJonathan** [comment]
Interesting, in rc1 `raw_status` doesn't seem to exist anymore, and i took the closest alternative `status`, which gave me the type requirement of `Status`.

Even still, how does this request stand onto it's own?

**Comment by the10thWiz** [comment]
@ShadowJonathan I'm not sure. The implementation would be straight forward (as you mentioned above), but I'm not sure if this should be a supported use case. Rocket tries to insulate against the underlying HTTP library, and most users shouldn't interact with any part of Hyper.

Unless @SergioBenitez wants to chime in, I think this should be rejected. I believe Rocket is also trying to work towards HTTP backend independence, so `hyper` may not be dependency for ever.

**Comment by jebrosen** [comment]
> I believe Rocket is also trying to work towards HTTP backend independence, so `hyper` may not be dependency for ever.

Rocket does expose some parts of hyper in the public API, but the intent is for most of these to go away eventually. Since this isn't a regression after all and would actually be a new feature adding integration/compatibility/dependence upon hyper, I think rejecting it is appropriate.

Thank you for the feedback nonetheless!
