### ISSUE TITLE
pastebin example in documentation is outdated

### ISSUE THREAD

**Issue by CGMossa** [SergioBenitez/Rocket#1756]
Hey! I'm getting into rocket, and found this message while following the pastebin building-tutorial

```
    => Error: Response was a non-`Responder` `Err`: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }.
    => Warning: This `Responder` implementation has been deprecated.
    => Warning: In Rocket v0.5, `Result<T, E>` implements `Responder` only if `E` implements `Responder`. For the previous behavior, use `Result<T, Debug<E>>` where `Debug` is `rocket::response::Debug`.    => Outcome: Failure
    => Warning: Responding with 500 Internal Server Error catcher.
    => Response succeeded.
```

Now, I was able to follow the instruction and move on, but how is this example supposed to look like for `rocket = "0.5"`?

**Comment by SergioBenitez** [comment]
The tutorial indeed needs to be updated. The example, however, is fully updated and idiomatic for 0.5: https://github.com/SergioBenitez/Rocket/tree/677790d6397147f83066a284ee962bc174c555b5/examples/pastebin.

**Comment by mattfbacon** [comment]
Hey @SergioBenitez could I work on this? Looks like the last issue in the 0.5.0 milestone.
