### ISSUE TITLE
Callbacks when graceful shutdown is initiated

### ISSUE THREAD

**Issue by ShadowJonathan** [SergioBenitez/Rocket#1758]
#### Is your feature request motivated by a concrete problem? Please describe.

Our web-app implements long-polling, which then returns results based on other events in the app.

During a graceful shutdown, these long-polling events dont return until timeout because no events are happening.

#### Why this feature can't or shouldn't live outside of Rocket.

Graceful shutdowns are intrinsic to rocket's internals, and while it's also possible to add signal hooks to signals that initiate shutdown, that method is more a monkey patch around the problem.

#### Ideal Solution

The ideal solution would be to allow a fairing/config argument that adds callbacks that're called upon shutdown to initiate further cleanup, or in our case, fire a special event that rounds up all long-polls to return immidiately. This allows the graceful shutdown to be shortened, and helps it get back up quicker on restart.

**Comment by SergioBenitez** [comment]
That's what [`Shutdown`](https://api.rocket.rs/v0.5-rc/rocket/struct.Shutdown.html) is. You can retrieve a handle either as a request guard or anywhere via [`Rocket.shutdown()`](https://api.rocket.rs/v0.5-rc/rocket/struct.Rocket.html#method.shutdown).
