### ISSUE TITLE
HTTP2 push support

### ISSUE THREAD

**Issue by cogman** [SergioBenitez/Rocket#177]
Some reading
https://blogs.oracle.com/theaquarium/entry/http_2_and_server_push

Server push is great for applications which know 1 request generally follows another.  For example, a request for /index.html will almost always be followed by a request for /bundle.js and /bundle.css .  It allows the server and the client to sidestep the roundtrip requirement.

It can also come in handy for things like replacing polling with pushing.

**Comment by SergioBenitez** [comment]
This should we possible once we stabilize the underlying HTTP library. Let's track this issue, along with other HTTP/2 related issue, in #17.
