### ISSUE TITLE
Out of the box tls example achieving A+ at ssllabs.com and webpagetest.org

### ISSUE THREAD

**Issue by omac777** [SergioBenitez/Rocket#1770]
**Is your feature request motivated by a concrete problem? Please describe.**
No matter whatever web framework in whatever language, it has always been a challenge to achieve A+ for a tls/https web site at ssllabs.com and webpagetest.org.  With rocket_contrib space helmet, we were able to enable a bunch of things to achieve security level A, but not A+ and these needed to be added by ourselves after examining the tls example.  rocket_contrib was deprecated which was disappointing since it addressed all the security issues and clearly stated so.  With the current 0.5.0 rocket, there is no mention of any of those security issues being dealt with in the new version.

A clear and concise description of what the problem is. Examples:
Build the tls example, run the tls example and test it at ssllabs.com and webpagetest.org.
Achieve B or A, but not A+.

Please add additional framework to the tls example to successully achieve A+ security levels as a reference point for all Rocket users.  It's difficult to adopt Rocket without such things in place or well-documented to do such things easily.

Thank you or listening.

**Comment by MikailBag** [comment]
While `rocket_contrib` is deprecated, there are [some](https://api.rocket.rs/v0.5-rc/rocket/shield/index.html) security features in Rocket core.

**Comment by omac777** [comment]
If all these are enabled, I perceive it to do better with the above tests.  I'll give it a go.

I'm surprised to not see any mention of these in the tls example.
I'm also surprised the exiting rocket_contrib documentation doesn't mention it is deprecated along with a suggestion to relay you to a newer existing replacement for it.

Thank you so much MikailBag.

**Comment by omac777** [comment]
I'm surprised to see when using shield, the default doesn't enable all policies listed.  Why not?
Wouldn't it be what we want when deploying?
Why not make a function called enableAllPolicies() in shield for sane defaults achieving security test A+ levels.

**Comment by omac777** [comment]
This gets me through to webpagetest.org security level: A

One last outstanding item: 

>  ❌ The following security headers are missing from the website:
> high severity
> Content Security Policy
> 
> A computer security standard introduced to prevent cross-site scripting (XSS), clickjacking and other code injection attacks resulting from execution of malicious content in the trusted web page context
> 

Here is the code giving me security level A, but please advise me to upgrade it to A+.  Thank you.
```
#[macro_use] extern crate rocket;

use rocket::shield::{Shield, Referrer, Prefetch, NoSniff, XssFilter, ExpectCt};
use rocket::fs::FileServer;

#[launch]
fn rocket() -> _ {
   let shield = Shield::default()
    .enable(Referrer::NoReferrer)
    .enable(XssFilter::default())
    .enable(NoSniff::Enable)
    .enable(ExpectCt::default())
    .enable(Prefetch::Off);

    rocket::build().attach(shield).mount("/", FileServer::from("static"))
}
```

**Comment by omac777** [comment]
I read for security reasons, the compression mod with flate2 was entirely disabled.  
As a result the same webpagetest.org also gives grades for 
 - compress transfer : F
 - compress images : F

I'm under the impression it hints that compression of transfers and images might be considered as security policies.

What do you use to check the integrity of transfers and images?  I have come to appreciate blake3. b3sum is much faster than sha256sum for very large files.

**Comment by jebrosen** [comment]
>  rocket_contrib was deprecated which was disappointing since it addressed all the security issues and clearly stated so. With the current 0.5.0 rocket, there is no mention of any of those security issues being dealt with in the new version.
> 
> I'm also surprised the exiting rocket_contrib documentation doesn't mention it is deprecated along with a suggestion to relay you to a newer existing replacement for it.

This is mentioned [in the CHANGELOG](https://github.com/SergioBenitez/Rocket/blob/master/CHANGELOG.md#contrib-graduation). Although, how did you know `rocket_contrib` was removed without also knowing it was replaced by `rocket::shield::Shield` which is enabled by default? Is there other documentation we have not updated?

I think it's still premature to put a notice directly in the `rocket_contrib` documentation; perhaps once 0.5 is released we can add a link to the documentation for the releases of the new crate(s).

> I'm surprised to see when using shield, the default doesn't enable all policies listed. Why not?
> Wouldn't it be what we want when deploying?

Not necessarily! Several browsers policies are reasonably secure by default, but applications may want to opt in to stricter security or privacy. Some of the policies are also no longer respected by modern browsers, and it would be wasteful to emit those headers for every Rocket application. Are there particular polici(es) you are concerned about not being enabled by default?

> Content Security Policy
> Here is the code giving me security level A, but please advise me to upgrade it to A+. Thank you.

This is #264. Content-Security-Policy is quite complex and difficult to configure correctly, and the correct policy is quite sensitive to what the individual website does. For instance, it's easy to write a `Content-Security-Policy` that gets an A+, but breaks all of the functionality of the website by disabling inline scripts and styles. It is also possible to write a website that requires the use of features that prevent it from ever using an "A+" policy. I think this is a reasonable thing to add, but I expect it to be a pretty large task to tackle to determine a sane default policy (if that's even possible), document how the policy works, provide a typed API for the different parts of CSP, and explain how/why to change it.

> I'm under the impression it hints that compression of transfers and images might be considered as security policies.

They are not. Compression of transfers and images are both listed under the "Performance" section of that page.

> What do you use to check the integrity of transfers and images? I have come to appreciate blake3. b3sum is much faster than sha256sum for very large files.

HTTP relies on the underlying transport for integrity checks.

**Comment by omac777** [comment]
Thank you Mr. Rosen, you've really highlighted the complexity of achieving an A+ on these security/performance websites.

With this said and done I understand this of no fault on Rocket.rs's part.

Perhaps the Web Consortium and the rust language community could establish some apis answering to this problem. 
How about a rust web security conformance api and audit api crate?
How about a rust web performance conformance api and audit api crate?

Hopefully by : 
 - filling out rust web security conformance api empty stubs
 - filling out rust web performance conformance api empty stubs
 - run the rust web security conformance audit tool
 - run the rust web performance conformance audit tool 

this would tell straight away we have A+ passed all conformance tests with 100% confidence without having to do external testing.

**Comment by omac777** [comment]
Here's a post that might be relevant. Web server security and privacy concerns about using CDN's are mentioned:
https://httptoolkit.tech/blog/public-cdn-risks/
Perhaps these web server security evaluation/performance benchmark web sites are a ploy to sell their security and cdn services to small businesses.

**Comment by SergioBenitez** [comment]
Looks like the only thing we'd need is built-in CSP, so closing in favor of #264. Note that you can always enable CSP by setting your own headers either via an implementation of a `Shield` `Policy`, a fairing, or anything in between.
