### ISSUE TITLE
In rocket_dyn_templates crate module `context` is private

### ISSUE THREAD

**Issue by mofengme** [SergioBenitez/Rocket#1771]
**Description**
He,guys!

The  examples/cookies  on branch v0.5.0-rc.1 can work well when git clone and cargo run.
But when I run the cookies example on a new project with the following `Cargo.toml`, something wrong with error message
```
error[E0603]: module `context` is private
   --> src/session.rs:7:38
    |
7   | use rocket_dyn_templates::{Template, context};
    |                                      ^^^^^^^ private module
    |
note: the module `context` is defined here
   --> /Users/mofeng/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket_dyn_templates-0.1.0-rc.1/src/lib.rs:160:1
    |
160 | mod context;
    | ^^^^^^^^^^^^

error: aborting due to previous error
```
All files are same with cookies example except the `Cargo.toml` file

The following is the `Cargo.toml`
```
[package]
name = "rocket-demo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["secrets"] }

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.1"
features = ["handlebars"]
```

**Environment:**

 - OS Distribution and Kernel: MacOS 10.14.6
 - Rocket Version: 0.5.0-rc.1

**Comment by SergioBenitez** [comment]
Please switch to a branch or tag that corresponds to the version of Rocket you're using. You're looking at the code on master but using 0.5-rc.

**Comment by mofengme** [comment]
The  `cookies` example on both the `master` branch or the `0.5-rc` branch are the same

**Comment by SergioBenitez** [comment]
The branch is not the same as a tag. A tag marks a release. A branch marks progress in a series of releases. The 0.5-rc branch is the current progress in the 0.5-rc series of releases.

**Comment by mofengme** [comment]
Ok, thanks for the info

**Comment by jakob-lilliemarck** [comment]
Im having the same issue, and got insecure as per the answer above but did double check.
This is the relevant parts of the cargo.toml

```[dependencies]
rocket = "0.5.0-rc.1"

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.1"
features = ["handlebars", "tera"]```

The `rocket_dyn_templates = 0.1.0-rc.1` is specified to depend on `rocket = 0.5.0-rc.1` as per the info at crates.io:
https://crates.io/crates/rocket_dyn_templates/0.1.0-rc.1/dependencies

When I do:

```
#[get("/")]
fn index() -> Template {
    Template::render("index", context! { test: "test" })
}
```

I get:
```
error: cannot find macro `context` in this scope
  --> src/main.rs:27:31
   |
27 |     Template::render("index", context! { test: "test" })
```
