### ISSUE TITLE
No crate for rocket_db_pools

### ISSUE THREAD

**Issue by thomas66777** [SergioBenitez/Rocket#1783]
I cannot see the crate for `rocket_db_pools`
I'm following the example: [database](https://github.com/SergioBenitez/Rocket/tree/master/examples/databases) which points to the contrib folder [db_pools](https://github.com/SergioBenitez/Rocket/tree/master/contrib/db_pools)

In the db_pools `README` it links to the crate `rocket_db_pools` at this link [https://api.rocket.rs/v0.5-rc/rocket_db_pools](https://api.rocket.rs/v0.5-rc/rocket_db_pools)

But as you can see this link is broken.  Not sure if I am missing something or if this just hasnt been officially published yet.

Thank you

**Comment by SergioBenitez** [comment]
You're looking at master, which is unreleased.
