### ISSUE TITLE
Panic with Lint error: unequal ty/span (1/0)

### ISSUE THREAD

**Issue by kballard** [SergioBenitez/Rocket#179]
In a toy program I'm writing, I wanted to use an r2d2 connection pool for Diesel as managed state. To make things easier, I defined

```rust
type PoolState<'r> = rocket::State<'r, r2d2::Pool<r2d2_diesel::ConnectionManager<SqliteConnection>>>;
```

and then my routes look like

```rust
#[get("/")]
fn index(pool: PoolState) -> Template {
    …
}
```

Unfortunately, doing this triggers a compiler panic at `rocket_codegen-0.2.0/src/lints/mod.rs:291`.

I believe what's going on is it's correctly identifying that `PoolState` is in fact a `rocket::State`, but then trying to look at the first type param to `PoolState` (which obviously has no parameters).

This has a trivial workaround, which is to use a type alias only for the parameter and having my route use `State<ConnPool>` instead, but it's not as nice as I'd like.

**Comment by SergioBenitez** [comment]
Cool! Thanks for reporting this! I'll take a look soon. 

As a quick work around, you should be able to add `#[allow(unmanaged_state)]` to the route to make the panic go away.

**Comment by SergioBenitez** [comment]
Confirmed. Fix is incoming.
