### ISSUE TITLE
max_level_warn help message could be clearer

### ISSUE THREAD

**Issue by timokoesters** [SergioBenitez/Rocket#1794]
There's currently a message like this:
> help: to enable INFO logging, remove the `max_level_warn` feature

If the end user of my program downloads a binary and gets that warning, they might not realize what Rust "features" are and that they have to be set at compile time. I suggest changing it to something like
> help: to enable INFO logging, use a binary compiled without the `max_level_warn` feature flag

**Comment by SergioBenitez** [comment]
To my knowledge, Rocket isn't emitting this message.
