### ISSUE TITLE
The rocket_db_pools crate disable the sqlx log

### ISSUE THREAD

**Issue by paulzhang5511** [SergioBenitez/Rocket#1798]
**Is your feature request motivated by a concrete problem? Please describe.**

I often check the sqlx log. but the `rocket_db_pools` crate disable the sqlx log.

https://github.com/SergioBenitez/Rocket/blob/master/contrib/db_pools/lib/src/pool.rs

```rust
  async fn init(figment: &Figment) -> Result<Self, Self::Error> {
            let config = figment.extract::<Config>()?;
            let mut opts = config.url.parse::<Options<D>>().map_err(Error::Init)?;
            opts.disable_statement_logging();
            specialize(&mut opts, &config);

            sqlx::pool::PoolOptions::new()
                .max_connections(config.max_connections as u32)
                .connect_timeout(Duration::from_secs(config.connect_timeout))
                .idle_timeout(config.idle_timeout.map(Duration::from_secs))
                .min_connections(config.min_connections.unwrap_or_default())
                .connect_with(opts)
                .await
                .map_err(Error::Init)
        }
```
`opts.disable_statement_logging();` disable the sqlx log.

**Ideal Solution**

Define `sql_log_level` in Rocket.toml

**Comment by SergioBenitez** [comment]
I've already implemented a "fix" for this which simply propagates the existing `log_level`, which I think is the most seamless solution.
