### ISSUE TITLE
Rocket - error: expected item, found `[`

### ISSUE THREAD

**Issue by sm8082** [SergioBenitez/Rocket#1803]
Hi, I am getting this error when compiling my rust program: 

**error: expected item, found `[`

[rocket::get("/")]
 ^ expected item**

or as below:

![image](https://user-images.githubusercontent.com/8048105/127773708-e60a08e8-11e1-42dd-8122-b0d2727e9cf6.png)

Could you please assist fixing this issue. Many thanks in advance.
On the terminal: **rustc --version** returns "**rustc 1.56.0-nightly (4e282795d 2021-07-31)**"

My code has three files as below:

**main.rs:**

#![feature(proc_macro_hygiene, dec1_macro)]
#[macro_use]
extern crate rocket;
use rocket::get;
use rocket::routes;
extern crate reqwest;
use std::collections::HashMap;
use std::error::Error;
use std::io::prelude::*;
use std::fs::File;
use std::path::Path;
extern crate rustc_serialize;
use rustc_serialize::json::Json;
use std::io::Read;

// #[get("/")]
[rocket::get("/")]

fn hello()->String {
    let path = Path::new("api.json");
    let display = path.display();

    println!("{:?} {:?}", path, display);
    let mut file = match File::crate(path) {
        Ok(file)  => file,
        Err(_) => panic!("Could not create the file"),
    };

    match reqwest::get("https://api.openweathermap.org/data/2.5/weather?q=Lahore&Apikey=8b4b24c4db5055993c896329922f73dc") {
        Ok(mut response) => {
            match response.text(){
                Ok(text) => match file.write_all(text.as_bytes()) {
                    Ok(_)=> println!("Data Write in File"),
                    Err(e)=>println!("The Error is this {}",e),
                }
                Err(_)=>println!("The response is not coming from the server"),
            }
        }
        Err(_)=>println!("Server could not establish the connection"),
    }

    let mut file = match File::open(&path){
        Ok(file)=>file,
        Err(e)=>panic!("File open error: {:?}",e),
    };
    
    let mut buffer = String::new();
    file.read_to_string(&mut buffer).unwrap();
    let json = Json::from_str(&buffer).unwrap();
    let result = format!("The temperature of Lahore is: {}", json.find_path(&["temp"]).unwrap());
    result
}

fn main() {
    rocket::ignite().mount("/",routes![hello].launch)
}

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
**Rocket.toml:**

[development]
address = "192.168.43.61"
port = 3000

**---------------------------------------------------------------------------------------------------------------------------------------------------------------------**
**Cargo.toml:**

[package]
name = "Q3Live1Vid9-WeatherAPI"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = "0.4.2"
reqwest = "0.11.4"
rustc-serialize = "0.3.24"

**Comment by SergioBenitez** [comment]
It's `#[get("/")]`, with a leading `#`. This is a Rust OEM attribute.
