### ISSUE TITLE
Error[E0599]: no method named 'launch' found for struct 'Vec<Route>'

### ISSUE THREAD

**Issue by sm8082** [SergioBenitez/Rocket#1808]
I'm facing the following error in Rust and wonder if you could please assist in resolving.

![image](https://user-images.githubusercontent.com/8048105/128390656-39cb7170-0e21-4df3-91f9-724cdd1c4c63.png)

--------------------------------------------------------------------------------------------------------------------
**Main.rs** (inside the src folder)

#![feature(proc_macro_hygiene,decl_macro)]
#[macro_use] 
extern crate rocket;
use rocket::get;
use rocket::routes;
extern crate reqwest;
//use std::collections::HashMap;
//use std::error::Error;
use std::io::prelude::*;
use std::fs::File;
use std::path::Path;
extern crate rustc_serialize;
use rustc_serialize::json::Json;
use std::io::Read;

// #[get("/")]
//[rocket::get("/")]
#[get("/")]

fn hello()->String {
    let path = Path::new("api.json");
    let display = path.display();

    println!("{:?} {:?}", path, display);
    let mut file = match File::create(path) {
        Ok(file)  => file,
        Err(_) => panic!("Could not create the file"),
    };

    match reqwest::get("https://api.openweathermap.org/data/2.5/weather?q=Lahore&Apikey=8b4b24c4db5055993c896329922f73dc") {
        Ok(mut response)=>{
            match response.text(){
                Ok(text) => match file.write_all(text.as_bytes()) {
                    Ok(_)=> println!("Data Write in File"),
                    Err(e)=>println!("The Error is this {}",e),
                }
                Err(_)=>println!("The response is not coming from the server"),
            }
        }
        Err(_)=>println!("Server could not establish the connection"),
    }

    let mut file = match File::open(&path){
        Ok(file)=>file,
        Err(e)=>panic!("File open error: {:?}",e),
    };
    
    let mut buffer = String::new();
    file.read_to_string(&mut buffer).unwrap();
    let json = Json::from_str(&buffer).unwrap();
    let result = format!("The temperature of Lahore is: {}", json.find_path(&["temp"]).unwrap());
    result
}

fn main() {
    rocket::ignite().mount("/",routes![hello].launch());  // thats where the error is
}

-----------------------------------------------------------------------------------------------------------
**Cargo.toml:** (inside the project folder)

[package]
name = "Q3Live1Vid9-WeatherAPI"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = "0.4.2"
reqwest = "0.9.22"
rustc-serialize = "0.3.24"

-----------------------------------------------------------------------------------------------------------
**Rocket.toml** (inside the project folder)

[development]
address = "192.168.0.13"
port = 3000

**Comment by SergioBenitez** [comment]
You're missing a closing `)`.

**Comment by sm8082** [comment]
Hi Sergio,
Could you please let me know where exactly have I missed the closing ).

The following line has two open and two closed brackets so not sure where am I going wrong:

rocket::ignite().mount("/",routes![hello].launch());

**Comment by SergioBenitez** [comment]
```diff
- rocket::ignite().mount("/",routes![hello].launch());
+ rocket::ignite().mount("/",routes![hello]).launch();
```
