### ISSUE TITLE
Address config not working when building in container

### ISSUE THREAD

**Issue by nlanson** [SergioBenitez/Rocket#1811]
**Description**

When building a rust program using Rocket with a ```rocket.toml``` file in a Docker container, the address config is ignored and set to http://127.0.0.1:8000 instead of http://0.0.0.0:8000 as specified in ```rocket.toml```.

**To Reproduce**

Build a generic Rocket project in the rust official docker container with address config set to ```0.0.0.0``` in rocket.toml.

**Expected Behavior**

Program starts with server binded to ```0.0.0.0```

**Environment:**

 - Rust official docker container
 - Rocket Version: [0.5.0-rc.1]

**Comment by SergioBenitez** [comment]
How are you configuring the address? What does your Rocket.toml look like? Are there other environment variables you're setting?

**Comment by nlanson** [comment]
Thanks for the quick response.

I am configuring the address through rocket.toml:
```
[global]
address = "0.0.0.0"
log_level = "critical"
```

When I build and run in the container, only the log level config is applied:
```
Configured for release.
   >> address: 127.0.0.1    //Should be 0.0.0.0
   >> port: 8000
   >> workers: 2
   >> ident: Rocket
   >> keep-alive: 5s
   >> limits: bytes = 8KiB, data-form = 2MiB, file = 1MiB, form = 32KiB, json = 1MiB, msgpack = 1MiB, string = 8KiB
   >> tls: disabled
   >> temp dir: /tmp
   >> log level: critical     //This is working
   >> cli colors: true
   >> shutdown: ctrlc = true, force = true, signals = [SIGTERM], grace = 2s, mercy = 3s
```

**Comment by nlanson** [comment]
I have been able to come around this issue following documentation from here (https://rocket.rs/v0.5-rc/guide/configuration/) but it just means I am not using a toml file any more.

**Comment by SergioBenitez** [comment]
The file needs to be called `Rocket.toml`. This is case sensitive. Are you naming it correctly? Otherwise, the file needs to be in the CWD or any parent thereof of the process.

**Comment by nlanson** [comment]
Yes file is called ```Rocket.toml``` with the correct case and file is located in the same directory as ```Cargo.toml```.

The file is copied along with the other project files to be built. 
As I have highlighted, what is strange is that only half of the config from ```Rocket.toml``` is appled.

**Comment by SergioBenitez** [comment]
If you're using Docker, you need to ensure the file is actually copied or otherwise made available to the container. "Critical" is the default level for the release profile, so its presence offers no indication of the file not working.

The use of Rocket.toml is tested thoroughly, so the probability of a bug in this area is extremely unlikely.

**Comment by nlanson** [comment]
I am sure the ```Rocket.toml``` file was copied into the container.

I also tested the program but running ```cargo run``` in the container but still produced the same result. Log level was critical for ```cargo run``` indicating the config file's log level option was applied but address was still ```127.0.0.1```.

Not sure what is happenening.

**Comment by SergioBenitez** [comment]
Can you create a reproducible example?

**Comment by nlanson** [comment]
Yep.

src/main.rs
```
#[macro_use] extern crate rocket;

#[get("/")]
fn index() -> &'static str {
    "Hello, world!"
}

#[launch]
fn rocket() -> _ {
    rocket::build().mount("/", routes![index])
}
```

cargo.toml
```
[package]
name = "project"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
```

Rocket.toml
```
[global]
address = "0.0.0.0"
log_level = "critical"
```

Dockerfile:
```
FROM rust as builder
WORKDIR /app
COPY . .
RUN cargo build --release

FROM rust as runtime
WORKDIR /app
COPY --from=builder /app/target/release/project .
EXPOSE 8000
CMD ["./project"]
```

**Comment by asopicki** [comment]
> COPY -- from=builder /app/Rocket.toml

Testing your Dockerfile I noticed that you have a space between the two dashes and the from which is probably not correct and maybe why the Rocket.toml file is missing in your image. Also note that the second argument for the COPY instruction (the dot) is missing. Hopefully that is going to fix your issue.

**Comment by nlanson** [comment]
My bad I just noticed the mistakes in the Dockerfile (I quickly wrote that up in the github editor). 

This is the actual Dockerfile I have been using, copy pasted:
```
FROM rust as builder
WORKDIR /app
COPY . .
RUN cargo build --release

FROM rust as runtime
WORKDIR /app
COPY --from=builder /app/target/release/project .
COPY --from=builder /app/Rocket.toml .
EXPOSE 8000
CMD ["./app/project"]
````

**Comment by asopicki** [comment]
Try changing the line 
> CMD ["./app/project"]
to the following
> CMD ["./project"]
and check if that works. 

I have a similar setup here with Docker and Rocket 0.5.0-rc.1. Rocket is picking up my Rocket.toml just fine as otherwise the application wouldn't start. You can also open a shell in your docker container via docker exec -it <containerid> and check if all files are in the expected location.

**Comment by jebrosen** [comment]
I can confirm that I got an error with @nlanson's latest Dockerfile, which was fixed by changing the last line to `CMD ["./project"]`. It read `Rocket.toml` just fine after that, including a non-default address and log level in `Rocket.toml`.

**Comment by SergioBenitez** [comment]
Checking in, @nlanson. Does the fixed `Dockerfile` resolve your issue?

**Comment by nlanson** [comment]
Fixed. 

Thanks for the help.
