### ISSUE TITLE
Fails to compile with mongodb_pool

### ISSUE THREAD

**Issue by tim-harding** [SergioBenitez/Rocket#1812]
**Description**

Using the latest version of `rocket_contrib` as a dependency with the `mongodb_pool` feature enabled, I get the following build error with `cargo check`:
```
error: failed to select a version for the requirement `crypto-mac = "^0.6"`
candidate versions found which didn't match: 0.11.1, 0.11.0, 0.10.1, ...
location searched: crates.io index
required by package `hmac v0.6.2`
    ... which is depended on by `mongodb v0.3.12`
    ... which is depended on by `rocket_contrib v0.4.10`
```
It appears that all the `crypto-mac` versions prior to 0.7 have been removed from crates.io. `hmac` and `mongodb` have since updated their dependencies in the latest versions, but the version of `mongodb` that `rocket_contrib` depends on has not. 

**To Reproduce**

This `cargo.toml` dependency triggers the compilation failure. 
```
[dependencies.rocket_contrib]
version = "0.4.10"
default-features = false
features = ["mongodb_pool"]
```

**Expected Behavior**

The app compiles

**Environment:**

 - OS Distribution and Kernel: Windows 10 build 19042.1110
 - Rocket Version: 0.5.0-rc.1

**Additional Context**

None.

**Comment by jebrosen** [comment]
I haven't been able to find out why or exactly when those `crypto-mac` versions were yanked. That's an unfortunate surprise.

However, in your particular case you are still using `rocket_contrib` with `rocket 0.5-rc.1`, which does not work; please see the [CHANGELOG](https://github.com/SergioBenitez/Rocket/blob/v0.5-rc/CHANGELOG.md#contrib-graduation). Issue #1117 included support for the latest `async` version of `mongodb`, which has been implemented in the `master` branch.

**Comment by tim-harding** [comment]
I think I must have been unwittingly referring to the 0.4 documentation when I was trying to figure this out because looking back it does suggest `rocket_sync_db_pools` for my use case. The setup looks similar, so I'll give that a try and see how it goes. Thanks for the pointer. Hopefully this issue report was at least some new information.

**Comment by SergioBenitez** [comment]
That's fascinating. I don't think there's anything we can really do, short of a breaking release. Since this is also resolved in 0.5, I'm closing this out.

**Comment by elibroftw** [comment]
@SergioBenitez , when will 0.5 release for rocket-contrib? Or how do you use it?

**Comment by the10thWiz** [comment]
> @SergioBenitez , when will 0.5 release for rocket-contrib? Or how do you use it?

`rocket_contrib` has been fully deprecated. For 0.5, the various libraries provided by contrib have been split into separate crates, namely `rocket_dyn_templates`, `rocket_db_pools`, and `rocket_sync_db_pools`. See the upgrading guide for more information.

**Comment by elibroftw** [comment]
Thanks. I figured that out myself after commenting.
