### ISSUE TITLE
Cookie "SameSite" value set to "None" is actually "Lax"

### ISSUE THREAD

**Issue by TanguyDelume** [SergioBenitez/Rocket#1825]
In the Cookie struct, regarding [the function set_same_site](https://api.rocket.rs/v0.4/rocket/http/struct.Cookie.html#method.set_same_site):
When the parameter is set to SameSite::None, the attribute SameSite is not set, but in most recent browser (since chrome version 76+) when this value is unset the default one is SameSite::Lax, so there is no way to set it to the actual "None" value.

It would be helpful to have this fix.

**Comment by jebrosen** [comment]
What version of Rocket are you using? I believe this was fixed in `cookie` between 0.4 and 0.5-rc.1, but it was not upgraded within 0.4.x to keep compatibility. (The new default is "blank (i.e. Lax, currently), but can set anything explicitly".)

**Comment by SergioBenitez** [comment]
Indeed, this is possible in 0.5 and the latest `cookie`.
