### ISSUE TITLE
context macro from rocket_dyn_templates is private

### ISSUE THREAD

**Issue by henrifrancois** [SergioBenitez/Rocket#1826]
**Description**

The `context!` macro from the `rocket_dyn_templates` crate is private. 

**To Reproduce**

When included in a `use` statement, as shown in the cookies example, for instance, the build will fail stating `error[E0603]: module `context` is private`. 

**Expected Behavior**

The macro should be public.

**Environment:**

 - OS Distribution and Kernel: Ubuntu 20.04
 - Rocket Version: 0.5-rc

**Additional Context**

Add any other context about the problem here, for example, how you uncovered the bug or if you have ideas about what/where Rocket is going wrong.

**Comment by SergioBenitez** [comment]
It's not private, it's simply not in a release version.

**Comment by mataslauzadis** [comment]
Should references to this macro be removed from the documentation?

https://api.rocket.rs/master/rocket_dyn_templates/struct.Template.html#examples

**Comment by Merlin-Brandt** [comment]
Yes, they really should. It's misleading and confusing.

**Comment by blackghost1987** [comment]
You can create a simple context struct manually, the `context!` macro is just a helper to create a quick, one-off context, without defining a type. See the comment before the macro definition:
```
/// # Examples
///
/// The following code:
///
/// ```rust
/// # #[macro_use] extern crate rocket;
/// # use rocket_dyn_templates::{Template, context};
/// #[get("/<foo>")]
/// fn render_index(foo: u64) -> Template {
///     Template::render("index", context! {
///         // Note that shorthand field syntax is supported.
///         // This is equivalent to `foo: foo,`
///         foo,
///         bar: "Hello world",
///     })
/// }
/// ```
///
/// is equivalent to the following, but without the need to manually define an
/// `IndexContext` struct:
///
/// ```rust
/// # use rocket_dyn_templates::Template;
/// # use rocket::serde::Serialize;
/// # use rocket::get;
/// #[derive(Serialize)]
/// # #[serde(crate = "rocket::serde")]
/// struct IndexContext<'a> {
///     foo: u64,
///     bar: &'a str,
/// }
```

Templating is definitely usable at the moment, just create a context struct which implements serialize. Or you can even use a unit type `()` as well if you don't need any context.

I'm not sure why the macro is private in the current version or will it stay private in the release, but if it will stay private then it should not be used in the examples, that's for sure. But it being unreachable is not a major loss in my opinion, because if you want to reuse the same context type multiple times, then you would need to define a struct type anyway.

**Comment by blackghost1987** [comment]
Sorry, it turns out the `()` solution is compiling fine, but it gives a runtime error. You have to use an empty struct, if there's no context. Something like this:
```
#[derive(Serialize)]
struct EmptyContext {}

#[get("/<foo>")]
fn render_index(foo: u64) -> Template {
    Template::render("index", EmptyContext {})
}
```

If somebody knows a simpler way to define an empty context, please let me know.
