### ISSUE TITLE
Flash messages lasting too long

### ISSUE THREAD

**Issue by kballard** [SergioBenitez/Rocket#186]
I just stuck some Flash messages into my app, but they're lasting for much longer than a single request. It looks like the cookie itself has a 5 minute timeout, and Rocket is never explicitly clearing it, so the Flash will show on every page (that can show flashes) until the cookie expires.

**Comment by SergioBenitez** [comment]
Rocket _does_ clear the flash cookie; there's even [a comment in the code](https://github.com/SergioBenitez/Rocket/blob/master/lib/src/response/flash.rs#L226) about it. The todo example uses flash messages, and they're working exactly as expected, so I don't believe the issue it in Rocket's side.

Can you try to debug your app a bit more to confirm that it's certainly on Rocket's side?

**Comment by kballard** [comment]
This is pretty weird. I turned on debug logging, and I can clearly see `Set-Cookie: _flash=; Max-Age=0; Expires=Wed, 08 Feb 2016 23:11:59`. Similarly, if I look in the web inspector in Safari, I can also see this header in the response headers. And yet, the cookie wasn't actually cleared, and it still contains the message that was previously set. I also tried Chrome and it's busted there too, so this isn't some weird Safari issue.

**Comment by SergioBenitez** [comment]
Are you setting another `Flash` in the same request?

**Comment by kballard** [comment]
Nope. I even confirmed that accessing my `"/"` route (which is not capable of returning a Flash) doesn't clear the Flash message. And there are no other `Set-Cookie` headers in the response I'm seeing.

**Comment by kballard** [comment]
Hmm, I just noticed that the Expires date is a full year ago. That seems kind of weird. Also, [RFC 6265](https://tools.ietf.org/html/rfc6265#section-4.1.1) explicitly says the Max-Age value must start with a non-zero value, and yet you have `Max-Age=0`. So maybe the browser is rejecting the header?

**Comment by SergioBenitez** [comment]
Where are you reading that? The RFC specifically says, in 5.2.2:

>    If delta-seconds is less than or equal to zero (0), let expiry-time
>    be the earliest representable date and time.  Otherwise, let the
>    expiry-time be the current date and time plus delta-seconds seconds.

I don't know what to tell you. If you browser is not clearing the cookie, even though we set `Max-Age=0` and expiration to a year ago, there's not much we can do. I can't replicate this on my side.

Is your system clock correct? Is your browser clock correct?

**Comment by kballard** [comment]
I linked to the section where it says that, specifically the grammar productions. Here's the relevant production:

```
 max-age-av        = "Max-Age=" non-zero-digit *DIGIT
```

That said, I'm currently reading through section 5.2.

**Comment by kballard** [comment]
I've figured it out.

Section 5.3 says

>    11.  If the cookie store contains a cookie with the same name,
>         domain, and path as the newly created cookie:
> 
>         1.  Let old-cookie be the existing cookie with the same name,
>             domain, and path as the newly created cookie.  (Notice that
>             this algorithm maintains the invariant that there is at most
>             one such cookie.)

And that's the problem. The original cookie was set with `Path=/`, but the attempt to clear the cookie doesn't have a `Path` at all. And I just tested; if I navigate to http://localhost:8000/, that actually does clear the cookie (since the default-path for that URL is `/`). But navigating to e.g. http://localhost:8000/foo/1 does not clear the cookie.

So the solution here is clearing the cookie requires providing the same Path value.

**Comment by kballard** [comment]
Looks like the actual bug here is in alexcrichton/cookie-rs instead of this repo. I'll be following up there.

**Comment by SergioBenitez** [comment]
Yeah, I figured this out in the meantime as well. I was relying on the `cookie` crate doing the right thing for deletion, but it unfortunately doesn't. The `cookie` API doesn't really enable doing this right. I'll have to go fix that crate.

Anyway, the resolution/workaround is pretty simple. I'll push a fix in a second and have you confirm the issue is gone.

**Comment by kballard** [comment]
I just filed alexcrichton/cookie-rs#75 about this. The API actually should enable this, as if it actually locates the existing cookie in the Jar when asked to remove a cookie by name (so it can grab the Path and Domain values). In fact, I would argue that it's a bug that you can say `jar.remove("foo")` and it'll produce a Set-Cookie header even if there was no cookie called `"foo"` in the jar.

**Comment by SergioBenitez** [comment]
Can you confirm that https://github.com/SergioBenitez/Rocket/commit/1e1ff3bd23de92086da4903f1774161d6811f489 resolves this?

**Comment by kballard** [comment]
Confirmed. The Flash is now deleted properly. Thanks! I'll close out this ticket now, though we should still fix cookie-rs (but that's tracked in alexcrichton/cookie-rs#75).
