### ISSUE TITLE
Support generating OpenAPI/Swagger docs

### ISSUE THREAD

**Issue by 3olkin** [SergioBenitez/Rocket#1862]
The OpenAPI/Swagger documentation is very useful in REST API development. It would be great if rocket is able to generate them automatically.

**Comment by ralpha** [comment]
[Okapi](https://github.com/GREsau/okapi) does this. And will be updating soon for better support for rocket 0.5.0-rc.1

**Comment by luisroel91** [comment]
Okapi isn't a solution is you're using the stable toolchain, moving to nightly will break most projects in a way that it isn't really a tenable solution for most using stable

**Comment by blackghost1987** [comment]
@luisroel91 The rocket_okapi crate works fine on Stable, at least 0.8.0-rc.2 definitely does (with Rocket 0.5.0-rc.2). I'm not sure about the previous versions.

**Comment by luisroel91** [comment]
> @luisroel91 The rocket_okapi crate works fine on Stable, at least 0.8.0-rc.2 definitely does (with Rocket 0.5.0-rc.2). I'm not sure about the previous versions.

This is terrific news! Let me give it another shot and I'll let you know the results. Thank you.

**Comment by luisroel91** [comment]
Still not really working...

For example, I have this simple endpoint 
![image](https://user-images.githubusercontent.com/44761184/220225121-55eb719f-fea8-4c6f-a78e-c8c184814521.png)

Can't get the `openapi_get_routes` macro to work...
![image](https://user-images.githubusercontent.com/44761184/220225321-929c8dfb-f6aa-4f30-959b-77d619da6237.png)

And that was after having to implement two traits, which I had to dig into the docs to figure out how to do...wasn't very clear. 

Its just way more work to get something enabled that seems to be extremely easy in other languages frameworks...Maybe there's something I'm missing. I would love to get this working, so if you have any hints, please let me know.

This is my cargo.toml for reference:
![image](https://user-images.githubusercontent.com/44761184/220225444-1e470374-f5b3-4866-b0d9-c394f8606eb9.png)

**Comment by luisroel91** [comment]
I still think it would be a better solution to add this natively to Rocket instead of having to depend on another package that may/may not break as Rocket develops, or, is easy enough for beginners to enable.
