### ISSUE TITLE
Derived Responder is not accepted as Responder

### ISSUE THREAD

**Issue by threema-danilo** [SergioBenitez/Rocket#1864]
**Description**

First, let's start with a serializable type:

```rust
#[derive(Debug, serde::Serialize)]
struct MySerializable(usize);
```

Next, I'll create a derived enum responder which encloses this serializable type in a JSON response:

```rust
#[derive(Debug, rocket::Responder)]
pub enum MyResponder<T: serde::Serialize> {
    JsonVariant(rocket::serde::json::Json<T>),
}
```

Because of the trait bound, I can construct the `MyResponder::JsonVariant` with any type `T` which is serializable.

Now let's use this responder in a handler:

```rust
#[get("/asdf")]
pub fn foo() -> MyResponder<MySerializable> {
    MyResponder::JsonVariant(Json(MySerializable(42)))
}
```

Surprisingly (to me), this does not compile:

```rust
error[E0277]: the trait bound `MySerializable: Responder<'_, '_>` is not satisfied
   --> src/api/handlers.rs:895:17
    |
895 | pub fn foo() -> MyResponder<MySerializable> {
    |                 ^^^^^^^^^^^ the trait `Responder<'_, '_>` is not implemented for `MySerializable`
    |
note: required because of the requirements on the impl of `Responder<'_, '_>` for `MyResponder<MySerializable>`
   --> src/api/handlers.rs:886:17
    |
886 | #[derive(Debug, rocket::Responder)]
    |                 ^^^^^^^^^^^^^^^^^
887 | pub enum MyResponder<T: serde::Serialize> {
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: required by `route::handler::<impl Outcome<rocket::Response<'o>, rocket::http::Status, rocket::Data<'o>>>::from`
    = note: this error originates in the derive macro `rocket::Responder` (in Nightly builds, run with -Z macro-backtrace for more info)
```

For some reason Rust expects the serializable type `T` (enclosed inside `Json`) to be a responder. But I can't figure out why. 

The `Responder` impl for `Json` is this:

```rust
impl<'r, T: Serialize> Responder<'r, 'static> for Json<T> {
...
```

This puts a `T: Serialize` trait bound on the type `T`, but it doesn't require the inner type to be a responder.

Any ideas why this doesn't compile? Am I doing something wrong, or is this a bug in the proc macro?

**Environment:**

 - OS Distribution and Kernel: ArchLinux
 - Rocket Version: 0.5.0-rc.1

**Comment by SergioBenitez** [comment]
Exactly as @jebrosen states. This is made easier in `master`.

**Comment by threema-danilo** [comment]
Ah, thank you @jebrosen! That helped.
