### ISSUE TITLE
Tera not rendering child templates

### ISSUE THREAD

**Issue by leontoeides** [SergioBenitez/Rocket#1869]
**Description**

Using `rocket_dyn_templates` - the child templates seem to be ignored by Tera even though they are being discovered and registered with Tera. I know the child template is being loaded because if I make an mistake in the child template, an error will be reported.

**To Reproduce**

`Cargo.toml`
```
[package]
name = "test"

[dependencies]
rocket = "0.5.0-rc.1"
rocket_dyn_templates = { version = "0.1.0-rc.1", features = ["tera"] }
serde = "1.0"
```

`main.rs`
```
#[macro_use] extern crate rocket;
use rocket_dyn_templates::Template;
use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize, Serialize)]
struct TestObj { name: String }

#[get("/")]
fn test() -> Template {
    let context = TestObj { name: "Mr. Doctor".to_string() };
    Template::render("test", &context)
} // fn

#[launch]
fn rocket() -> _ {
    rocket::build()
        .mount("/", routes![test])
        .attach(Template::fairing())
}
```

`templates\test.txt.tera`
```
Hello, {% block person -%}No Name{% endblock person -%}
```

`templates\name.txt.tera`
```
{% extends "test" %}
{% block person -%}{{ name }}{% endblock person -%}
```

**Actual Behavior**

```
Hello, No Name
```

**Expected Behavior**

```
Hello, Mr. Doctor
```

**Environment:**

 - Windows 10
 - Rocket Version: 0.5.0-rc.1

**Comment by SergioBenitez** [comment]
You need to render the _child_ template, not the parent. The reasoning should be clear: it is the _child_ that's specialized, not the parent, so rendering the parent can't possibly render the specialized content.

**Comment by leontoeides** [comment]
Son of a gun. I completely misunderstood how this works.
