### ISSUE TITLE
client.get() and special characters

### ISSUE THREAD

**Issue by TarekAS** [SergioBenitez/Rocket#1875]
**Description**

I'm creating an API that simply echoes the path. I came across a potential bug when unit testing for special characters like `©`.  I get the following error when running the code below:

```Error: invalid request URI: Path { source: None, data: Data { value: "/©", decoded_segments: [uninitialized storage] } }```

**To Reproduce**

`main.rs`
```
#[macro_use] extern crate rocket;

#[get("/<s>")]
fn index(s: &str) -> String {
    s.to_string()
}

#[launch]
fn rocket() -> _ {
    rocket::build().mount("/", routes![index])
}

#[cfg(test)]
mod test {
    use super::rocket;
    use rocket::local::blocking::Client;
    use rocket::http::Status;

    #[test]
    fn test() {
        let client = Client::tracked(rocket()).expect("valid rocket instance");
        let response = client.get("/©").dispatch();

        // This does not work.
        assert_eq!(response.status(), Status::Ok);
        assert_eq!(response.into_string().unwrap(), "©");
    }
}

```

`cargo.toml`
```
[package]
name = "mypackage"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = "0.5.0-rc.1"
```

**Expected Behavior**

Test case should succeed.

**Environment:**

 - OS Distribution and Kernel: WSL2 Linux 4.19.104-microsoft-standard
 - Rocket Version: 0.5.0-rc.1

**Comment by DanielJoyce** [comment]
Does the test pass if you urlencode it first?

Kinda surprised client isn't urlencoding it, but there may multiple encodings to chose from perhaps.

**Comment by SergioBenitez** [comment]
Indeed, you must encode the URL. The preferred mechanism is to use the `uri!` macro which does this for you while also providing further compile-time guarantees.

**Comment by TarekAS** [comment]
In that case, I suggest mentioning this in the  `Testing` section of the docs.

**Comment by TarekAS** [comment]
`uri!("/©")`  throws a compile time error `invalid URI: unexpected token byte 194 at index 1`.

I'm still new to Rust, is there something obvious that I'm missing?

I just went ahead and used `%C2%A9` in my test case and it worked. i.e.

```
#[test]
    fn replace() {
        let client = Client::tracked(rocket()).expect("valid rocket instance");
        let response = client.get("/replace/ThisStringContainsOracle?from=Oracle&to=Oracle%C2%A9").dispatch();

        // This does not work.
        assert_eq!(response.status(), Status::Ok);
        assert_eq!(response.into_string().unwrap(), "ThisStringContainsOracle©");
    }
 ```
