### ISSUE TITLE
having Fairing::ignite return Err<Rocket> for failure makes error chaining inside ignite() unergonomic

### ISSUE THREAD

**Issue by DanielJoyce** [SergioBenitez/Rocket#1876]
You can't use '?'

You can't come up with a custom From impl for errors because there is no way to grab the current rocket instance that is in scope.

You're forced to use a lot of if-let or match statements, and manual threading. Frankly it's easier to use expect().

it's super unergonomic. Is there a reason ignite has to return Err<Rocket> instead of some kind of actual error type? 

If the hope is to keep passing Rocket to subsequent fairings, and give a user a list of all fairings that failed, this seems suspect and potentially dangerous.

**Comment by DanielJoyce** [comment]
I've just come to use logging and expect("Something went wrong") in my ignite impls.

**Comment by DanielJoyce** [comment]
I can also shove it into a utility method, and have ignit call that, which works, but for simple ones, its still unergo.

**Comment by jebrosen** [comment]
> Is there a reason ignite has to return Err&lt;Rocket&gt; instead of some kind of actual error type?

In principle, `on_ignite` could take e.g. an `&mut Rocket` and return `Result<(), SomeErrorType>` - but of course, that also entails redesigning the entire `Rocket` struct, which methods mostly take `self`. My own feeling on this is that `self` is more ergonomic than `&mut self` in more situations than the other way around (the Rust API Guidelines project details [some of these tradeoffs](https://rust-lang.github.io/api-guidelines/type-safety.html#consuming-builders)). 100% of Rocket projects use functions like `mount`; writing an `on_ignite` fairing is less common.

> If the hope is to keep passing Rocket to subsequent fairings, and give a user a list of all fairings that failed, this seems suspect and potentially dangerous.

Rocket does indeed do this. What about this seems suspect or potentially dangerous?

**Comment by SergioBenitez** [comment]
I agree that this can be annoying, and as a result I've tried changing methods around to avoid it, but doing so makes _other_ cases annoying. This is vague, and it's been a while since I've run this little API experiment, but suffice to say that I have not found an alternative that makes all cases better, or even _more_ cases better, so we have the API we do. If you find such an alternative, please open a PR as I'm all ears.
