### ISSUE TITLE
Allow pre-building a Rocket instance (without runtime) then launch it with Rocket's runtime

### ISSUE THREAD

**Issue by blackghost1987** [SergioBenitez/Rocket#1881]
**Is your feature request motivated by a concrete problem? Please describe.**

I would require a way to build Rocket outside of `#[rocket::main]` before even having a runtime, but still start it with Rocket's own runtime when the building is finished.

As Rocket matures it seems like there's a frequent need to include Rocket in a bigger application as a module, or maybe have more control over the startup and shutdown of the application. In my opinion the issue is there's only two ways to start Rocket with it's own "official" runtime, and they are both designed to be used on the application's `main()`. These are really useful for simple applications where Rocket is a first class citizen and it governs application startup, but they lack the flexibility needed by more complex programs, where Rocket is just a module (especially if the runtime should be started from another thread!). It would be really useful to do some computation on application startup, check some data, and only launch Rocket and it's runtime (on a separate thread) when needed.

Currently Rocket CAN be started programmatically e.g. by putting `#[launch]` in a sub-module, then calling the blocking `main()` function of the sub-module (generated by the codegen). This function can be launched in a separate thread.
The biggest issue is these macros can only be used on functions without any inputs or outputs. This makes it impossible to use any data from outside of the function which has been annotated with the macro.

Having access to the "outside world" would be really useful during the building or ignition of Rocket. The current setup makes the following cases impossible:
- Adding any data to Rocket managed state which was created before runtime creation
- Using the Shutdown functionality from a spawning thread (see [here](https://github.com/SergioBenitez/Rocket/discussions/1880))

Of course it is possible to create a custom Tokio runtime and call build(), ignite() and launch() respectively, but this has some limitations:
- it's up to the user to provide an appropriate runtime, which could be complicated for newbies and easy to mess up. This is especially cumbersome if other parts of the application doesn't even need any async functionalities.
- even if the user provides a proper runtime, the Shutdown functionality depends on Rocket using it's own runtime, and using a custom runtime will mess things up with cooperative shutdown.

**Why this feature can't or shouldn't live outside of Rocket**
The launch mechanism and the runtime creation is a core part of Rocket. The `async_main` function contains the runtime creation, and there's no other way to create it. That function is only public though because of a Rust limitation and should not be called directly (see #1772 ), so there's not way to re-create Rocket's runtime from the outside.

**Ideal Solution**
My idea is to move the building of Rocket (or at least parts of it) outside of the async main. The current functions in `Rocket<Build>` (build, mount, attach, etc.) are not async at all, they can be called before the runtime is even created. There could be a new function to accept a "pre-built" Rocket (with all the outside world stuff already in it), then Rocket would create it's own Tokio runtime and ignite & launch it.
This could also be a macro, similar to `#[launch]`. The macro would be working on functions like `fn(Rocket<Build>) -> Rocket<Build>`. This way the user function could get a "semi-built" Rocket and complete it before passing it to Rocket to launch it. (This sounds a bit like Payload Integration to me, if we are talking rocketry analogies 😃 )

**Alternatives Considered**
An alternative would be to expose the runtime by adding a "getter". This way the users could get Rocket's runtime and call block_on(launch()) themselves. This seams less ergonomical though, and AFAIK Rocket is trying to hide the underlying runtime from it's public interface, so probably not a good idea for the future.

Note: These changes would still make it impossible to do anything with the _ignited_ Rocket instance from the outside, so Shutdown from the spawning thread would still be impossible (because it requires ignition, which requires a runtime), but I hope this will be easy to solve later.

**Comment by zeroflaw** [comment]
I needed to get to the tokio runtime before rocket did its thing, so I expanded the macros to see what it was doing, and you could do something like this. 

```
fn main() {
    // FIXME: The `workers` value won't reflect swaps of `Rocket` in attach
    // fairings with different config values, or values from non-Rocket configs.
    // See tokio-rs/tokio#3329 for a necessary solution in `tokio`.
    rocket::tokio::runtime::Builder::new_multi_thread()
        .worker_threads(Config::from(Config::figment()).workers)
        // NOTE: graceful shutdown depends on the "rocket-worker" prefix.
        .thread_name("rocket-worker-thread")
        .enable_all()
        .build()
        .expect("create tokio runtime")
        .block_on(async move {
            let _ = rocket::build().mount("/hello", routes![hello])
            .launch()
            .await;
        })
}
```

**Comment by blackghost1987** [comment]
@zeroflaw thx, this is a valid workaround. Unfortunately that's the kind of stuff I meant by "creating a custom Tokio runtime and calling build/ignite/launch", which I still think is not an ergonomic way to start Rocket. It would be much better if Rocket could create and handle it's own runtime, in an encapsulated fashion.
Also when I tried this "hack" to use the "rocket-worker" prefix for the thread name in my custom runtime, I still had some issues with graceful shutdown not working properly, or at least it gave some mean warnings... :(

**Comment by the10thWiz** [comment]
> Note: These changes would still make it impossible to do anything with the ignited Rocket instance from the outside, so Shutdown from the spawning thread would still be impossible (because it requires ignition, which requires a runtime), but I hope this will be easy to solve later.

I agree that this is something to solve separately. A simple solution might be creating an async `mpsc` channel, which is used to communicate between async and sync code. This could be used to pass information, events, and even shutdown notifications between async and sync code. Trivially, it could be used to shutdown Rocket from outside (by passing the message to a function running inside the runtime), but it could also be used to share events, e.g. to send configuration values between the application and the HTTP front end.

**Comment by SergioBenitez** [comment]
I fail to see why `#[rocket::main]` is not sufficient, as illustrated in @jebrosen's comment https://github.com/SergioBenitez/Rocket/discussions/1880#discussioncomment-1268465. Why can't you do all of the synchronous work inside the async main? Nothing will go wrong, you'll simply block the worker while the synchronous code is being executed, which is what you would do anyway if you weren't using an async runtime. Or if you don't want to block, use `spawn_blocking()` or `thread::spawn()`, the latter as illustrated in https://github.com/SergioBenitez/Rocket/discussions/1880#discussioncomment-1268465.

**Comment by AdmiralNemo** [comment]
@SergioBenitez I would like to see this feature because my application consists of multiple processes, each launched from the same executable with different arguments.  One of those processes is a Rocket web server, while another is a different server that _also_ manages its own Tokio runtime.

I have been able to work around this limitation so far by putting the `#[launch]` in a submodule as described in the issue description, so it's actually not that big of a deal to me; I just wanted to offer my use case.

**Comment by SergioBenitez** [comment]
Thanks for the commentary, @the10thWiz; valuable as always. My thinking here is that it would suffice to have a rocket::execute function, or similar, that takes a `Rocket<P>`, starts a runtime, blocks on the server, and returns when the server shuts down. What do you think?

**Comment by blackghost1987** [comment]
> Thanks for the commentary, @the10thWiz; valuable as always. My thinking here is that it would suffice to have a rocket::execute function, or similar, that takes a `Rocket<P>`, starts a runtime, blocks on the server, and returns when the server shuts down. What do you think?

This sounds like a perfect solution for my usecase, and it doesn't even require any macro "magic" 👍 

Although your original comment was totally right, I could use an async main without actually launching Rocket, with a minimal overhead. The only reason I didn't do that is to separate Rocket related code from the other parts of the application, so not really a functional thing, more like code quality. But that's also doable by using `#[launch]` in a submodule, even if that solution is kinda unintuitive.

The proposed `rocket::execute()` would make this all possible without exposing the runtime (or building it manually), while it is also a bit more intuitive in my opinion. I like the approach of using the macros for the "usual" way OR using a function if something different is needed.
