### ISSUE TITLE
Get access to database connection pool

### ISSUE THREAD

**Issue by threema-danilo** [SergioBenitez/Rocket#1884]
**Is your feature request motivated by a concrete problem? Please describe.**

I handle requests that trigger the processing of long-running tasks in the background. These tasks are executed in the context of a thread pool (let's call it the worker thread).

Because the worker thread needs access to the database, and potentially to multiple connections (due to further parallelization of tasks), the API currently expects that a reference to the database connection pool is passed in.

When using the `rocket_sync_db_pools` crate, I can create a database and use that through the request guard. However, from what I can tell by reading the source code, that request guard only gets access to a single connection and does not expose the connection pool itself. And the connection (at least in the case of `diesel::PgConnection`) is not cloneable.

**Why this feature can't or shouldn't live outside of Rocket**

As long as the connection pool is not exposed in any way, there cannot be any solution outside of `rocket_sync_db_pools` (unless a completely separate solution is written).

**Ideal Solution**

Ideally the `#[database(...)]`-annotated struct that wraps the connection would get an automatically implemented method `fn get_pool(&self) -> P` which returns a reference to the database connection pool.

**Alternatives Considered**

I could create a second, completely independent database connection and pass that into the handlers using `&RocketState<MyPool>`. However, that seems hacky.

**Comment by Zopieux** [comment]
Ah, fun timing, there is some context and half-solutions in a related (but closed) bug that I just commented on: https://github.com/SergioBenitez/Rocket/issues/1640#issuecomment-917320655

Since July 18th and the implementation of async `rocket_db_pools` (5b1a04deabc75981fde566c4381b4cba0d3b7cc8), it looks like this became possible, so I've asked Sergio about the expected usage pattern. I feel like this should be documented in a "background processing" section of some sort, given the multiple FRs we've seen.

**Comment by threema-danilo** [comment]
The async pools will only work with async-capable backends though (e.g. no diesel).

If the general approach of exposing a `get_pool(&self) -> Option<Pool>` in the `sync_db_pools` crate is deemed to be OK (I'm not sure if exposing the pool can have any side effects), then I'll happily try to contribute an implementation!

**Comment by SergioBenitez** [comment]
> If the general approach of exposing a `get_pool(&self) -> Option<Pool>` in the `sync_db_pools` crate is deemed to be OK (I'm not sure if exposing the pool can have any side effects), then I'll happily try to contribute an implementation!

I think we already have this. It's simply a matter of exposing it. We should probably call/rename it `fetch`, to be on-par with the new `db_pools` crate.

**Comment by Mike-Neto** [comment]
Hey, I'm currently in the process of doing something very close to this and would not mind adding some docs on how to do it, however currently I was not able to make it work. While app runs the connection seems to never be released so every other endpoint timeouts, if someone could give me some pointers on what I'm missing I could then create some docs & examples for the general get a connection for BG tasks use case:

Here is what I have:
```
rocket.attach(rocket::fairing::AdHoc::on_liftoff(
"Background Task Runner",
            move |rocket| {
                Box::pin(async move {
                    let mut interval =
                        rocket::tokio::time::interval(rocket::tokio::time::Duration::from_secs(60));
                    let mut ticks: i32 = 0;
                    interval.tick().await; 
                    loop {
                        {
                            // Inner scope that I expected would release the connection.
                            let conn = models::DbConn::get_one(rocket).await;
                            run_background_jobs(&conn.unwrap(), ticks).await;
                        }
                        interval.tick().await;
                    }
                })
            },
        ));
```

**Comment by threema-danilo** [comment]
Proposed fix in #1972.

**Comment by violarulan** [comment]
@Mike-Neto 

I use this and it works for me. Just get the connection before spawning. And it doesn't block the app.
```
        .attach(AdHoc::on_liftoff("DB polling", |rocket| {
            Box::pin(async move {
                let conn = YourDBConn::get_one(&rocket).await.expect("database connection");
                rocket::tokio::spawn(async move {
                    let mut interval = tokio::time::interval(tokio::time::Duration::from_secs(10));
                    loop {
                        interval.tick().await;
                        do_sql_stuff(&conn).await;
                    }
                });
            })
        }))
```

**Comment by DanielJoyce** [comment]
You're gonna want to hand off to some sort of worker instance that only uses a small set of connections in a dedicated small pool, otherwise long running tasks will consome all the connections in a pool if enough come in, blocking everything.

Long running jobs should have their own queue, pools, and workers.

**Comment by threema-danilo** [comment]
> I use this and it works for me. Just get the connection before spawning. And it doesn't block the app.

I think that won't work in my use case, because I don't just need a single connection, I need a connection that can be cloned and passed to separate threads (i.e. a pool).
