### ISSUE TITLE
Layering: move FromParam trait (and others) into dedicated crate

### ISSUE THREAD

**Issue by zopieux** [SergioBenitez/Rocket#1903]
**Is your feature request motivated by a concrete problem? Please describe.**

Rocket already provides a relatively lightweight `rocket_http` crate with traits like

```rust
rocket_http::uri::fmt::{Formatter,FromUriParam,Path,UriDisplay}
```

which allows library author to provide rocket URI/path adapters for structs intended to be used in URIs, etc. and web frameworks in general.

I was surprised to see that sadly, `rocket::request::FromParam` belongs to the main rocket crate, therefore as a library author I cannot provide an implementation of that trait without depending on the main rocket crate. Unsurprisingly, `rocket::request::FromParam` depends only on `rocket_http` symbols and a bunch of std symbols, making it a good candidate for taking out of the main crate.

**Why this feature can't or shouldn't live outside of Rocket**

(does not apply in context)

**Ideal Solution**

Would it be possible to refactor some of these traits (I'm sure I'm forgetting others) inside a lightweight, dedicated lib crate intended for library authors?

Thanks!

**Alternatives Considered**

 Status quo. Library authors need to depend on the heavyweight `rocket` in order to implement the `rocket::request::FromParam` trait and other similar traits.

**Additional Context**

See first paragraph.

**Comment by the10thWiz** [comment]
The typical solution is to add a feature flag, since the rocket impls is only needed if the user is already depending on Rocket.

**Comment by Zopieux** [comment]
A feature flag would work as well, thanks for the suggestion.

**Comment by SergioBenitez** [comment]
> A feature flag would work as well, thanks for the suggestion.

The suggestion is for a feature flag on the crate implementing Rocket's traits. This is indeed, the preferred solution, and I don't see any downsides for the end-consumer, even if it means the library author needs to compile more of Rocket during development than absolutely necessary.
