### ISSUE TITLE
Support for static files

### ISSUE THREAD

**Issue by ivanceras** [SergioBenitez/Rocket#191]
The framework supports templates, it would be convenient addition to also load javascript and css files relative to the template files.

**Comment by SergioBenitez** [comment]
You can already do this easily by using the `NamedFile` type. See the [static_files](https://github.com/SergioBenitez/Rocket/tree/v0.2.0/examples/static_files) example for how to do so.

**Comment by ivanceras** [comment]
Thanks, I didn't notice NameFile is what I should be looking at.
