### ISSUE TITLE
`deadpool-diesel` support

### ISSUE THREAD

**Issue by anirudhb** [SergioBenitez/Rocket#1917]
Deadpool has support for the Diesel ORM through the [deadpool-diesel](https://crates.io/crates/deadpool-diesel) crate. It would be great if this feature was added to Rocket's async_db_pools crates so we can use Diesel asynchronously.

Currently Diesel can only be used through rocket_sync_db_pools which is not ergonomic and introduces a lot of clones (as all arguments passed into the `run` closure must be `'static`.) A lot of that could be eliminated with deadpool's diesel support. From the looks of it, it seems that Rocket's async_db_pools already supports some of deadpool's other drivers.

**Comment by SergioBenitez** [comment]
What we do in sync_db is the same thing that anyone else needs to do. There is no workaround. The previous deadpool implementation was wrong and misleading. Please see the issues I opened in the repository.
