### ISSUE TITLE
Limit for data-form is incorrect when set with environmental variables

### ISSUE THREAD

**Issue by iTzBoboCz** [SergioBenitez/Rocket#1924]
**Description**

Hi,
I think I found an issue when configuring limits with environmental variables (.env file).

I am working on an API that receives and serves images and I am sending them using multipart/form-data from my front-end.

**To Reproduce**

```rust
#[derive(FromForm, Debug)]
pub struct MediaData<'r> {
  file: TempFile<'r>,
}

#[post("/media/upload", data = "<media_data>")]
pub async fn upload_media(mut media_data: Form<MediaData<'_>>) -> Result<Status, Status> {
  // ...
}
```

This successfully sets the file limit (1 MiB by default) to 20 MiB so the only thing that limits the upload is the default 2 MiB limit for data-form:
```
# .env
ROCKET_LIMITS={file="20 MiB"}
```

But when I set data-form, I can no longer upload 1.9 MiB image that I could in the previous step. Looks like the data-form limit is 1 MiB now:
```
# .env
ROCKET_LIMITS={file="20 MiB", data-form="20 MiB"}
```

**Expected Behavior**

Limit for data-form should be the configured value.

**Environment:**

 - OS Distribution and Kernel: Pop!_OS 21.04 (kernel 5.11.0-7633-generic)
 - Rocket Version: 0.5.0-rc.1

**Additional Context**

It works when I set it in Rocket.toml:
```toml
# Rocket.toml
[default.limits]
file="20 MiB"
data-form="20 MiB"
```

**Comment by SergioBenitez** [comment]
Perhaps remove the space after the `,`?

**Comment by iTzBoboCz** [comment]
That fixed it, thanks :)
