### ISSUE TITLE
Publish rocket_db_pools on crates.io

### ISSUE THREAD

**Issue by roy-ganz** [SergioBenitez/Rocket#1951]
Hi, 
according to your [documentation]( https://api.rocket.rs/master/rocket_db_pools/index.html) `rocket_db_pools` is published on `crates.io`. However searching on [crates.io](https://crates.io/search?q=rocket_db_pools) does not yield any results.

Personally I get by with a cloned Rocket repository. But now that I'm preparing the announcement of my ORM, I wrote an [example with Rocket](https://github.com/roy-ganz/todo_rotomy). The example has some ugly Rocket patches in [Cargo.toml](https://github.com/roy-ganz/todo_rotomy/blob/master/Cargo.toml) and I need to get rid of them - otherwise the example is not clone-and-play for others.

Is there a reason, why `rocket_db_pools` is not published on `crates.io`? Or is there another solution to depend on `rocket_db_pools`?

Thank you for your time.

UPDATE: I just figured out, that cargo actually crawls through a repository to find crates. I can't get rid of the patches, but at least  they are now public dependencies and no show stopper anymore.

**Comment by SergioBenitez** [comment]
> Is there a reason, why `rocket_db_pools` is not published on `crates.io`? Or is there another solution to depend on `rocket_db_pools`?

It was written after the `rc`. The docs you're looking at are `master`. The crate will be published soon.
