### ISSUE TITLE
mysql_async::Pool support in rocket_db_pools

### ISSUE THREAD

**Issue by roy-ganz** [SergioBenitez/Rocket#1952]
Hi,
currently `rocket_db_pools` supports MySQL through `sqlx`.

The `mysql_async` crate features a [Pool](https://docs.rs/mysql_async/0.28.1/mysql_async/struct.Pool.html) and could be supported for users who don't want an extra `sqlx` dependency. 

I've done this for myself [here](https://github.com/roy-ganz/todo_rotomy/blob/master/src/mysql_async_pool.rs) and think others might want that, too.

So my proposal is to add MySQL to the [supported drivers](https://api.rocket.rs/master/rocket_db_pools/index.html#supported-drivers)

Thanks for your time.

**Comment by SergioBenitez** [comment]
Please feel free to send in a PR! Please ensure that docs are properly updated. In particular, the supported drivers table you linked to.

**Comment by SergioBenitez** [comment]
I'm not against this in the slightest. Since no one has stepped up to implement it, however, and there has been no further request for this, I'm closing this out. But I would happily accept a PR.
