### ISSUE TITLE
try_outcome! should use IntoOutcome

### ISSUE THREAD

**Issue by couchand** [SergioBenitez/Rocket#1954]
**Is your feature request motivated by a concrete problem? Please describe.**

Using `try_outcome!` to manage early returns is great, as long as the nested calls themselves return an `Outcome`.  However, under 0.4 we'd been using `?` and the impl of `Try` to automatically convert `Result` into `Outcome`.  It appears that migrating to 0.5 requires not just exchanging the much-nicer `?` with `try_outcome!`, but also remembering to add a call to `.into_outcome()`.

Is there a compelling reason that `try_outcome!` doesn't add a call to `.into_outcome()` to support `Result`s?

**Ideal Solution**

```
diff --git a/outcome.rs b/outcome.rs
index df3dbc1..cecec1e 100644
--- a/outcome.rs
+++ b/outcome.rs
@@ -744,7 +744,7 @@ crate::export! {
     /// }
     /// ```
     macro_rules! try_outcome {
-        ($expr:expr $(,)?) => (match $expr {
+        ($expr:expr $(,)?) => (match $crate::outcome::IntoOutcome::into_outcome($expr) {
             $crate::outcome::Outcome::Success(val) => val,
             $crate::outcome::Outcome::Failure(e) => {
                 return $crate::outcome::Outcome::Failure(::std::convert::From::from(e))
```

**Comment by SergioBenitez** [comment]
See #597, which should answer all of your questions!
