### ISSUE TITLE
Need an example for connecting to MongoDB on Rust

### ISSUE THREAD

**Issue by ayyagari-dalalstreet** [SergioBenitez/Rocket#1962]
### Discussed in https://github.com/SergioBenitez/Rocket/discussions/1961

<div type='discussions-op-text'>

<sup>Originally posted by **ayyagari-dalalstreet** October 23, 2021</sup>
I have tried the methods given by the doc url[https://rocket.rs/v0.4/guide/state/#databases] and explored the drivers but getting an issue of `pbkdf2` version is unmatched.

```
# Full Error message here

failed to select a version for the requirement `pbkdf2 = "^0.2.0"`
candidate versions found which didn't match: 0.9.0, 0.8.0, 0.7.5, ...
location searched: crates.io index
required by package `mongodb v0.3.12`
    ... which satisfies dependency `mongodb = "^0.3.12"` of package `rocket_contrib v0.4.10`
    ... which satisfies dependency `rocket_contrib = "^0.4.10"` of package `rocket_mongodo v0.1.0 

```
Unable to solve with the help of the current resources and findings. Need help with an small example on connecting `Rocket` with `MongoDB` 

As a author I am new to `Rust` and my previous background was working with `JS` and `Python`</div>

**Comment by Guileas** [comment]
@ayyagari-dalalstreet Do you have any news? I'm facing the same issue

**Comment by Guileas** [comment]
@ayyagari-dalalstreet I've come to a working solution with Rocket 0.5.0-rc.1 using this repo as exemple: 

- https://github.com/TaeyoonKwon/rust-rocket-sample

It has everything you need to make your project work with MongoDB rust driver 2.1.0.
Let me know if you have any problem.

**Comment by SergioBenitez** [comment]
Please use 0.5.
