### ISSUE TITLE
Documentation - JSON Example

### ISSUE THREAD

**Issue by dharmatech** [SergioBenitez/Rocket#1965]
The documentation links to a JSON example here:

https://github.com/SergioBenitez/Rocket/blob/8cae077ba1d54b92cdef3e171a730b819d5eeb8e/site/guide/4-requests.md?plain=1#L681

However, that example doesn't seem to exist.

**Comment by somehowchris** [comment]
Hey,

Just jumped over some issues, you mean like this one https://github.com/SergioBenitez/Rocket/blob/master/examples/serialization/src/json.rs ?

**Comment by joenano** [comment]
The example files are trash for newcomers, mixing 7 or 8 different things in the same file with 15 imports from all over the shop isnt helpful at all for leaning the library, examples should be broken into individual blocks with the minimum imports for each.

As an example, I want to learn how to do a simple database query and im met with this.

```rust 
use rocket::{Rocket, Build, futures};
use rocket::fairing::{self, AdHoc};
use rocket::response::status::Created;
use rocket::serde::{Serialize, Deserialize, json::Json};

use rocket_db_pools::{sqlx, Database, Connection};

use futures::{stream::TryStreamExt, future::TryFutureExt};

#[derive(Database)]
#[database("sqlx")]
struct Db(sqlx::SqlitePool);

type Result<T, E = rocket::response::Debug<sqlx::Error>> = std::result::Result<T, E>;
```

**Comment by SergioBenitez** [comment]
This is fixed in master.

> The example files are trash for newcomers, mixing 7 or 8 different things in the same file with 15 imports from all over the shop isnt helpful at all for leaning the library, examples should be broken into individual blocks with the minimum imports for each.

The docs tell you how to do simple things. The examples integrate them. Please feel free to maintain a separate set of examples that meet your standards.
