### ISSUE TITLE
"Databases" section not accessible in Rocket 0.5 guide

### ISSUE THREAD

**Issue by Razican** [SergioBenitez/Rocket#1971]
**Description**

The "Databases" section in the 0.5-rc guide is inaccessible, but it's searchable.

**To Reproduce**

In the Rocket 0.5-rc guide (https://rocket.rs/v0.5-rc/guide/), when searching for "database", some results appear. Mostly "Databases" and "Usage". They seem to be in a path that says "Within Guards > Databases" and the "Usage" is inside that.

When clicking there, it brings you to a 404 page: https://rocket.rs/v0.5-rc/guide/within-guards#databases

**Expected Behavior**

The databases guide opens.

**Additional Context**

I guess this is a wrong "search" link, but I'm not able to see how is this managed in the repo.

**Comment by mhutter** [comment]
If you scroll down the nav to the left, you'll find "Within Guards" being listed and accessible: https://rocket.rs/v0.5-rc/guide/state/#databases

Guess this is a nesting issue, I'd assume that `Within Guards` should be a `h3` and not a `h2`

**Comment by mhutter** [comment]
I think this was fixed in https://github.com/SergioBenitez/Rocket/commit/416f42bca703766a8a2bc0efa18fe4e93facee1e but not yet released

**Comment by SergioBenitez** [comment]
Indeed, this is already fixed in master.
