### ISSUE TITLE
HELP! Rust analyser highlights entire main function

### ISSUE THREAD

**Issue by PrisionMike** [SergioBenitez/Rocket#1979]
**Description**

Query initially [posted](https://users.rust-lang.org/t/help-rust-analyser-highlights-entire-main-function/66910) in the rust-lang forum as I thought it was an IDE bug. Latest reply suggests it might be the rocket::main annotation that is causing problems.

Basically the rust analyser extension on VSCode now highlights the entire main code too promptly while I am writing the code. Makes the coding experience very frustrating.
[Can't seem to attatch the image to make it easier for the readers here. Kindly use the[ link ](https://users.rust-lang.org/t/help-rust-analyser-highlights-entire-main-function/66910)to the rust-lang forum post.]

**Comment by Darksonn** [comment]
See https://github.com/tokio-rs/tokio/pull/4162 for how we handled the same issue in Tokio.

**Comment by jackHedaya** [comment]
It looks like this issue has been resolved on the forum post if the moderators want to close this
