### ISSUE TITLE
can provide some mysql operating example？

### ISSUE THREAD

**Issue by wanglunhui2012** [SergioBenitez/Rocket#1980]
I find the examples path doesn't hava mysql operating case,can provide some?

**Comment by zemelLeong** [comment]
```rust
use diesel::MysqlConnection;
use rocket_sync_db_pools::database;

#[database("mysql")]
pub struct MysqlDBConn(MysqlConnection);

#[launch]
async fn rocket() -> _ {
    rocket::build()
        .attach(database::MysqlDBConn::fairing())
}

#[get("/")]
pub async fn operation(conn: MysqlDBConn) {
    conn.run(move |c: &mut MysqlConnection| {

    });
}
```
这是我做的一些尝试，希望对你有用

**Comment by wanglunhui2012** [comment]
> ```rust
> use diesel::MysqlConnection;
> use rocket_sync_db_pools::database;
> 
> #[database("mysql")]
> pub struct MysqlDBConn(MysqlConnection);
> 
> #[launch]
> async fn rocket() -> _ {
>     rocket::build()
>         .attach(database::MysqlDBConn::fairing())
> }
> 
> #[get("/")]
> pub async fn operation(conn: MysqlDBConn) {
>     conn.run(move |c: &mut MysqlConnection| {
> 
>     });
> }
> ```
> 
> 这是我做的一些尝试，希望对你有用

**Comment by zemelLeong** [comment]
可以看下diesel相关文档案例
