### ISSUE TITLE
benchmark improvement

### ISSUE THREAD

**Issue by rainchen** [SergioBenitez/Rocket#1982]
**Existing Functionality**

Here is a benchmark results report for popular web frameworks which using Rust lang:
https://web-frameworks-benchmark.netlify.app/compare?f=actix,salvo,iron,gotham,nickel,rocket

<img width="1045" alt="Screen Shot 2021-11-08 at 7 06 36 PM" src="https://user-images.githubusercontent.com/71397/140848466-0702851a-370a-478c-913a-a2f98668b5be.png">

the Rocket project using in benchmark is:
https://github.com/the-benchmarker/web-frameworks/tree/master/rust/rocket

the project struct was following the contributing requirement of:
https://github.com/the-benchmarker/web-frameworks/blob/master/CONTRIBUTING.md

the project was auto built into a docker image with CI :
https://github.com/the-benchmarker/web-frameworks/blob/master/rust/Dockerfile

**Suggested Changes**

is there any tip can improve the performance?

**Alternatives Considered**

**Additional Context**

**Comment by SergioBenitez** [comment]
You're almost certainly not measuring the same thing across frameworks. Look at the responses: are they the same? Furthermore, you allocate in a handler (`id.to_string()`) which you can just return the value directly.

**Comment by SergioBenitez** [comment]
In any case, this isn't appropriate for the issue tracked. Feel free to start a discussion if you'd like to continue the thread.

**Comment by rainchen** [comment]
@SergioBenitez 
1. the response are the same. There is a set of unit tests to make sure all web framework project doing the same thing. Here is the testing code:  https://github.com/the-benchmarker/web-frameworks/blob/master/.spec/route_spec.rb . 
2. thx the suggestion, here is the PR: https://github.com/the-benchmarker/web-frameworks/pull/4816
