### ISSUE TITLE
Database URL behaves differently between `cargo run` and compiled binary when using unix sockets

### ISSUE THREAD

**Issue by TheAncientGoat** [SergioBenitez/Rocket#1986]
**Description**

Currently, `ROCKET_DATABASES={staging={url="/cloudsql/path-to-unix-socket"}} cargo run` connects to my database as expected, but using the compiled binary with `ROCKET_DATABASES={staging={url="/cloudsql/path-to-unix-socket"}} ./target/debug/rust-rocket-test` fails with
 ``` 
Error: database pool init error for pool named `staging`
> timed out waiting for connection: missing "=" after "/cloudsql/path-to-unix-socket" in connection info
```

I fixed this by using the extended url form - 
```
ROCKET_DATABASES={localhost={url="postgresql://postgres:******@postgres?host=/cloudsql/path-to-unix-socket"}} ./target/debug/rust-rocket-test
```
which works as expected; mainly posting this issue as it is odd that it would work in the one format but not the other (is it something to do with the connection string being available at compile time maybe?)

**To Reproduce**

Steps above show how to reproduce, any rocket application with a pg database exposed as a unix socket will do.

**Expected Behavior**

Expect `cargo run` and the binary to handle the same connection string consitently

**Environment:**

 - OS Distribution and Kernel: NixOS 21.09 and Debian buster-slim as a Dockerfile
 - Rocket Version: 0.5.0-rc.1

**Additional Context**

Found this when deploying to Google Cloud Run + Cloud SQL - where passing the plain unix socket path is the standard practice (works fine with my Node applicatiosn)

**Comment by SergioBenitez** [comment]
I suspect this has more to do with how `cargo` forwards environment variables to the binary, if all you're changing is exactly how you invoke the command. If instead you're invoking the command in different ways, say one via your shell and the other via some config file read by a cloud service, that could also do it. I don't think there's anything for us to do here, unfortunately.

I suspect some form of escape will do the trick. Maybe:

```
ROCKET_DATABASES="{staging={url=/cloudsql/path-to-unix-socket}}" ./target/debug/rust-rocket-test
```

Or perhaps:

```
ROCKET_DATABASES="{staging={url=\"/cloudsql/path-to-unix-socket\"}}" ./target/debug/rust-rocket-test
```
