### ISSUE TITLE
Redirect type is quite large (384 bytes)

### ISSUE THREAD

**Issue by wezm** [SergioBenitez/Rocket#1999]
Via a Clippy warning: https://rust-lang.github.io/rust-clippy/master/index.html#large_enum_variant I discovered that the `Redirect` type is quite large, which when combined with other types to build custom responders [as recommended](https://github.com/SergioBenitez/Rocket/issues/568#issuecomment-367201732) can cause the redirect variant to be disproportionately larger than the others, bloating the type if the common case is not a redirect.

I'm not sure if this is considered an issue but thought it was worth mentioning. On current master (8cae077) the following code prints 384 for me (on Linux):

```rust
    println!("{}", std::mem::size_of::<Redirect>() );
```

**Comment by mattfbacon** [comment]
I wonder if it would be sufficient to Box the Redirect.

**Comment by SergioBenitez** [comment]
With bf2bd0e9ede12dc227326d069cd84fc98dddf2e4, you can now do:

```rust
#[derive(Responder)]
enum Content {
    Redirect(Box<Redirect>),
    Text(String),
}
```
