### ISSUE TITLE
enhancement: allow route decorator to declare multiple http verbs at once

### ISSUE THREAD

**Issue by SergioBenitez** [SergioBenitez/Rocket#2]
IE, allow the following (in the extreme case):

```
#[route(PUT, POST, DELETE, GET, path = "...")]
```

**Comment by SergioBenitez** [comment]
I'd like some feedback from others to determine if this feature is indeed worthwhile. I haven't had a need for it, and it seems to only conflate code and ideas. But if someone has a good use-case, I'm all ears.

**Comment by SergioBenitez** [comment]
Pushing this to a decision by 0.4.

**Comment by kylone** [comment]
I haven't had much use for this default behavior in Asp.Net MVC. I typically want it to be obvious where a request will be routed. I feel that Get/Post on the same handler function is more hassle than it's worth.

**Comment by mehcode** [comment]
Routing both GET and POST to the same handler is very useful in a traditional web app that has a postback form.

An example in Flask (Python):

```python
@app.route('/submit', methods=('GET', 'POST'))
def submit():
    form = MyForm()
    if form.validate_on_submit():
        return redirect('/success')
    return render_template('submit.html', form=form)
```

**Comment by lawliet89** [comment]
My use case, at the moment, is trying to implement CORS (before middleware) support. I would like to have `Options` and `Get` (for example) to be handled by the same function so that I can handle the pre-flight and the actual requests without repeating some code.

**Comment by kylone** [comment]
Those sound like valid use cases. Is there anyone that thinks this is a bad idea?

**Comment by echochamber** [comment]
It sounds like valid use cases. I agree it can be used to conflate ideas and easily abused. I think best some sort best practices or warning in the docs would helpful at addressing that, at least partially (since the most likely candidates to abuse the feature are newer users, the people who likely to be reading the docs).

**Comment by SergioBenitez** [comment]
Pushing into the future.

**Comment by SergioBenitez** [comment]
Closing this as it seems unnecessary. Will revisit if requests call for it.
