### ISSUE TITLE
Encrypt and sign session cookies

### ISSUE THREAD

**Issue by SergioBenitez** [SergioBenitez/Rocket#20]

**Comment by flosse** [comment]
I really hope https://github.com/hyperium/hyper/pull/975 will be merged soon :)

**Comment by mgattozzi** [comment]
Should be noted it might not be based off the response from the maintainer here:
https://github.com/hyperium/hyper/issues/985

Seems like it'll remove openssl-sys so as to not cause conflicts/not be breaking change.

**Comment by SergioBenitez** [comment]
https://github.com/alexcrichton/cookie-rs/pull/68 will make this possible.

**Comment by SergioBenitez** [comment]
Unfortunately this must be pushed to 0.3.

**Comment by flosse** [comment]
> Seems like it'll remove openssl-sys so as to not cause conflicts/not be breaking change.

It's done in [v0.10.0](https://github.com/hyperium/hyper/releases/tag/v0.10.0) :)

**Comment by SergioBenitez** [comment]
I've submitted a PR (https://github.com/alexcrichton/cookie-rs/pull/76) to make this possible. After the PR is in, session support in Rocket should be straightforward.

**Comment by majkcramer** [comment]
> After the PR is in, session support in Rocket should be straightforward.
PR is in.

**Comment by SergioBenitez** [comment]
Sessions landed in master ~18 days ago in https://github.com/SergioBenitez/Rocket/commit/16cb7297abeef3af03666247e2fbbf6d9aae683e. Aside from the [session example](https://github.com/SergioBenitez/Rocket/tree/master/examples/session), however, sessions are undocumented. This is because the API is likely to change before support lands in `0.3`. I'm hoping for a more robust, future-proof solution. That route, however, requires a few more general features to implement.

**Comment by pointlessone** [comment]
Session can not be restored after process restart. It appears, some key gets changed on every run and it prevents session from properly decrypting cookies.

I'm not sure if this is a bug or me using it wrong. Also if it needs its own issue here.

**Comment by SergioBenitez** [comment]
@pointlessone You need to set the `secret_key` config parameter. Otherwise, Rocket will generate a secret key for you.
