### ISSUE TITLE
The optional parameters in query string are not parsed as expected

### ISSUE THREAD

**Issue by yuqiang-yuan** [SergioBenitez/Rocket#2007]
**Description**

I'm a newbee to Rust and Rocket and I just started my toy project with Rust and Rocket. First of all thank Rocket project!

I have an optional query form with 3 fields at most and I'd like to parse the form from the query string. But I found route works correctly and query form is parsed only when the field `s` appears in the query string.

Here is the form:

```rust
#[derive(Debug, Serialize, Deserialize, Clone, FromForm)]
pub struct SimpleQueryForm {
    #[field(name = "s", default = None)]
    pub s: Option<String>,

    #[field(name = "page", default = 1u32)]
    pub page: u32,

    #[field(name = "itemsPerPage", default = DEFAULT_PAGE_SIZE)]
    pub items_per_page: u32,
}
```

Here is the route:

```rust
#[get("/users?<form..>")]
pub async fn query(state: &State<AppState>, form: SimpleQueryForm, _op: UserVo) -> Json<PagedQueryResult<UserVo>> {
    log::debug!("form = {:?}", form);
    // database query goes here
}
```
I found the urls with `s` in it can be parsed correctly, for example:

`/users?s=&page=2`
`/users?s=1&page=2&itemsPerPage=10`

If the parameter `s` was missing, for example: `/users?page=1&itemsPerPage=10`, I got 404 response.
I wanna if the fields' data type is number causes this issue or something else I did not do it right?

**Expected Behavior**

The request can be routed to my code and the query form could be generated from the query string even some fields are missing.

**Environment:**

 - OS Distribution and Kernel: Ubuntu 20.04.3
 - Rocket Version: 0.5.0-rc.1
 - rustup: 1.24.3
 - rustc: 1.57.0

**Comment by kolbma** [comment]
I think there is missing something serde related to handle missing fields like its default.  
With json-parsing you would have the same problem.  
But can't remember right now exactly what to do to get this to work.

**Comment by the10thWiz** [comment]
Based on my quick testing, the issue is `#[field(default = None)]`. If you remove it, serde correctly detects that the Option type is indeed optional, and uses None if the value isn't present.

**Comment by yuqiang-yuan** [comment]
> Based on my quick testing, the issue is `#[field(default = None)]`. If you remove it, serde correctly detects that the Option type is indeed optional, and uses None if the value isn't present.
> 
> This is probably either an issue in Serde or Rocket, since it should work reguardless, but this is the work around for now. In general, I would recommend only using `#[field(...)]` if you have to (i.e. it deviates from the defaults), since the defaults tend to be pretty good.

@the10thWiz Thanks, I'll try the work around

**Comment by yuqiang-yuan** [comment]
> Does this happen on master as well? Does this happen without deriving anything, i.e, if you do:
> 
> ```rust
> #[get("/?<q..>")]
> fn f(q: Option<usize>) { .. }
> ```

@SergioBenitez I'll try it and to see if this happens

**Comment by SergioBenitez** [comment]
@yuqiang-yuan Any update for us?

**Comment by yuqiang-yuan** [comment]
@SergioBenitez Sorry for late response. I've tried @the10thWiz work around, just remove the `#[field(default = None)]` from the field `s` and the send the request without parameter `s` in the query string, it works. I think this is the right way to handle requests which have optional parameters. 

Thanks a lot

**Comment by SergioBenitez** [comment]
> @SergioBenitez Sorry for late response. I've tried @the10thWiz work around, just remove the `#[field(default = None)]` from the field `s` and the send the request without parameter `s` in the query string, it works. I think this is the right way to handle requests which have optional parameters. 
> 
> 
> 
> Thanks a lot

The issue is that using that attribute should effectively be a no-op as `None` is already the default. I'll take a close look at this later today.

**Comment by SergioBenitez** [comment]
Okay, this is actually working exactly as expected. From [the `FromForm` docs](https://api.rocket.rs/v0.5-rc/rocket/derive.FromForm.html):

> If expr is not literally None, the parameter sets the default value of the field to be expr.into(). If expr is None, the parameter unsets the default value of the field, if any. The expression is only evaluated if the attributed field is missing in the incoming form.
