### ISSUE TITLE
Problem get Collision error with similar routes

### ISSUE THREAD

**Issue by oren0e** [SergioBenitez/Rocket#2012]
Does rocket don't know how to deal with these?
```rust
#[get("/known_issues?<issue_name>")]
pub fn func1(...) {...}

#[get("/known_issues?<test_id>")]
pub fn func2(...) {...}
```
The first will call `api/known_issues?issue_name=<SOMETHING>`
and the second will call `api/known_issues?test_id=<SOMETHING ELSE>`

why am I getting a collision with these?

**Comment by tobymurray** [comment]
My understanding is that Rocket doesn't implicitly know what to do with this. The docs cover some of it here: https://rocket.rs/v0.5-rc/guide/requests/#requests as well as a workaround. As suggested when it fails to compile, you can give them different rankings:

```
Error: Rocket failed to launch due to the following route collisions:
   >> (func1) GET /known_issues?<issue_name> [2] collides with (func2) GET /known_issues?<test_id> [2]
   >> Note: Route collisions can usually be resolved by ranking routes.
```
E.g. something like this should start up
```
#[get("/known_issues?<issue_name>", rank = 2)]
pub fn func1(...) {...}

#[get("/known_issues?<test_id>", rank = 3)]
pub fn func2(...) {...}
```

**Comment by oren0e** [comment]
Thanks, yeah that's what I ended up doing.
