### ISSUE TITLE
FromForm #[field(skip)] attribute

### ISSUE THREAD

**Issue by timando** [SergioBenitez/Rocket#2029]
**Existing Functionality**

Rocket lets me have a struct with readonly fields if I'm using JSON (serde `skip_deserializing`), but not if I'm using forms.

**Suggested Changes**

Add a `#[field(skip)]` attribute to the `FromForm` derive macro.

**Alternatives Considered**

Including it in the struct and just ignoring it: Doesn't work if the readonly field is a `chrono` type (e.g. creation date)

**Additional Context**

`serde` supports `#[skip_deserializing]`

**Comment by SergioBenitez** [comment]
> Including it in the struct and just ignoring it: Doesn't work if the readonly field is a `chrono` type (e.g. creation date)

This _does_ work, but you need a default value, which you can set using `#[form(default = ...)]`.
