### ISSUE TITLE
Make HTTP/2 optional

### ISSUE THREAD

**Issue by andreymal** [SergioBenitez/Rocket#2030]
HTTP/2 support is actually useless in some real-world cases, primarily when a web application is behind a proxy server like nginx (which uses HTTP/1.0 for proxying). Moreover, `h2` is one of the biggest crates in the resulting hello-world binary (~220-240 KiB according to "cargo bloat --release"). I would be happy if I could significantly reduce the size of the binary by disabling the feature that I never plan to use.

If I understand the code correctly, Rocket doesn't use `h2` directly but just has few configuration lines ([1](https://github.com/SergioBenitez/Rocket/blob/7ffe3a73601aabdfe3190a809e660538acd5bdce/core/lib/src/server.rs#L462), [2](https://github.com/SergioBenitez/Rocket/blob/7ffe3a73601aabdfe3190a809e660538acd5bdce/core/http/src/tls/listener.rs#L73)), so I hope it's easy to implement.

See also related PR in warp: https://github.com/seanmonstar/warp/pull/836

UPD: also, axum has http2 feature disabed by default https://github.com/tokio-rs/axum/blob/axum-v0.4.3/axum/Cargo.toml#L16

**Comment by SergioBenitez** [comment]
Would be happy to make `http2` a feature-flag (enabled by default).
