### ISSUE TITLE
Missing clear documentation for 0.5 

### ISSUE THREAD

**Issue by VentGrey** [SergioBenitez/Rocket#2038]
**Existing Functionality**

The current v0.5-rc1 works great. Compared to other frameworks rocket is way easier to learn & understand. However some functionalities on the 0.5 version of the crate are not documented enough or don't provide a concise direction on how to start using them. I asked for this question on a [discussion](https://github.com/SergioBenitez/Rocket/discussions/2026)  first but It seems that the `Serialize` and `Deserialize` macros are not the only ones suffering from this. For example if you compile rocket with the `uuid` feature, if you add `use rocket::serde::uuid::Uuid;` you'll get a :

```rust
error[E0432]: unresolved import `rocket::serde::uuid`
 --> src/main.rs:9:20
  |
9 | use rocket::serde::uuid::Uuid;
  |                    ^^^^ could not find `uuid` in `serde`
```

error message. Even if you don't have another `UUID` crate installed. This makes things difficult to work with and only encourages people to install outside crates for things that come bundled with rocket but are not explained on how to use them properly as the docs example blocks only have a ` use rocket::serde::uuid::Uuid;
` without any special attribute above or below. 

**Suggested Changes**

Explain which attributes are needed or a small FAQ for users who need to use the integrated rocket features, this could help extend the userbase as some new users might need directions on how to use this crate properly without having to import the same crates that rocket provides (like serde and serde_json). 

**Alternatives Considered**

Searching in obscure sources or "The code is the documentation" I guess :thinking: 

**Additional Context**

The same serde crate comes with [good examples](https://docs.rs/serde_with/1.11.0/serde_with/guide/index.html) on how to overcome some problems. A sensible solution or snippet I can propose for rocket would be like this:

:warning:  this example is a modification of [this page](https://api.rocket.rs/master/rocket/serde/trait.Serialize.html) as this is how I solved my problem in the GitHub discussion I mentioned earlier

```rust
    ///  --- Trimmed docstring ---

pub trait Serialize {
    /// Serialize this value into the given Serde serializer.
    ///
    /// See the [Implementing `Serialize`] section of the manual for more
    /// information about how to implement this method.
    /// 
    ///  **Note**:  Due to Rust's orphan rule, you are required to specify
    ///  from which external crate serde is being used. You can achieve this
    ///  using the following attribute:
    /// 
    /// #[serde(crate = "rocket::serde")]
    /// 
    /// You can find more information [here](https://serde.rs/remote-derive.html)
    /// ```edition2018
    /// use serde::ser::{Serialize, SerializeStruct, Serializer};
    ///
    ///
    /// struct Person {
    ///     name: String,
    ///     age: u8,
    ///     phones: Vec<String>,
    /// }
    ///
    /// // This is what #[derive(Serialize)] would generate.
    /// impl Serialize for Person {
    ///     fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    ///     where
    ///         S: Serializer,
    ///     {
    ///         let mut s = serializer.serialize_struct("Person", 3)?;
    ///         s.serialize_field("name", &self.name)?;
    ///         s.serialize_field("age", &self.age)?;
    ///         s.serialize_field("phones", &self.phones)?;
    ///         s.end()
    ///     }
    /// }
    /// ```
    ///
    /// [Implementing `Serialize`]: https://serde.rs/impl-serialize.html
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer;
}
```

**Comment by SergioBenitez** [comment]
> For example if you compile rocket with the `uuid` feature, if you add `use rocket::serde::uuid::Uuid;` you'll get a :
> 
> ```rust
> error[E0432]: unresolved import `rocket::serde::uuid`
>  --> src/main.rs:9:20
>   |
> 9 | use rocket::serde::uuid::Uuid;
>   |                    ^^^^ could not find `uuid` in `serde`
> ```

This doesn't sound right. If you enable the `uuid` feature, then `uuid` _is_ in `rocket::serde`.

The rest of the issue is valid critique.

**Comment by VentGrey** [comment]
I placed that example because it's an issue I faced 😅 maybe I was just invoking the crate in the wrong way (?)
