### ISSUE TITLE
Wrong documention of Lenient

### ISSUE THREAD

**Issue by elbaro** [SergioBenitez/Rocket#2039]
https://docs.rs/rocket/0.5.0-rc.1/rocket/form/struct.Lenient.html
https://github.com/SergioBenitez/Rocket/blob/master/core/lib/src/form/lenient.rs

> Unlike using Form directly, this type uses a lenient parsing strategy: forms that contains a superset of the expected fields (i.e, extra fields) will fail to parse and defaults will not be use for missing fields.

The description of `Lenient` is identical to `Strict`.

**Comment by IniterWorker** [comment]
Related #1965
