### ISSUE TITLE
Broken website link 

### ISSUE THREAD

**Issue by veritem** [SergioBenitez/Rocket#2047]
I was browsing rocket's docs but this link is broken https://rocket.rs/v0.5-rc/guide/within-guards#within-guards

**Comment by IniterWorker** [comment]
Hi @veritem

Could you share more detail about the location of this link (button, link, page, ...)?

Thank you,

B. r

**Comment by veritem** [comment]
I just searched `guard` and the first link came broken
![image](https://user-images.githubusercontent.com/53856673/147957173-7cc0c0ae-30e3-4696-bbc1-9b1683b3c446.png)

**Comment by IniterWorker** [comment]
Related to : #1737

**Comment by SergioBenitez** [comment]
This is fixed in master. Try https://rocket.rs/master/guide.
