### ISSUE TITLE
HSTS Preload Mising includeSubdomains

### ISSUE THREAD

**Issue by Soham3-1415** [SergioBenitez/Rocket#2049]
**Description**

According to the HSTS Preload requirements at https://hstspreload.org/:
> The includeSubDomains directive must be specified.

and in order to maintain a domain on the preload list:
> You must make sure your site continues to satisfy the submission requirements at all times.

The `rocket::shield::Hsts` has a `Preload` variant that is supposed to add an HSTS header with the preload directive. However, this variant does not have the `includeSubdomains` directive. This contradicts the requirements specified for the preload list.

As an additional note, the `max-age` directive must be at least `31536000` seconds, and there is no mechanism to enforce or warn the user about this. However, I do not consider this particular behavior to be a bug as it is still possible for the header to be used correctly.

**To Reproduce**
Cargo.toml:
```toml
[package]
name = "oops"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.1"
time = "0.2"
```

main.rs:
```rust
#[macro_use]
extern crate rocket;

use rocket::shield::{Shield, Hsts};

#[launch]
fn oops() -> _ {
  rocket::build().attach(Shield::new().enable(Hsts::Preload(time::Duration::new(63072000, 0))))
}
```

Steps:
1. Run with: `cargo run`
2. Run `curl -I localhost:8000`

Response:
```
HTTP/1.1 404 Not Found
content-type: text/html; charset=utf-8
server: Rocket
strict-transport-security: max-age=63072000; preload
content-length: 383
date: Wed, 05 Jan 2022 22:54:59 GMT
```
Notice that strict-transport-security has the `preload` directive but is missing the `includeSubdomains` directive.
(date is subject to change and is not relevant)

**Expected Behavior**
The strict-transport-security header ought to display as (source: https://hstspreload.org/):
```
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
```
(header capitalization is irrelevant)

**Environment:**

 - OS Distribution and Kernel: core-11.1.0ubuntu3-noarch:security-11.1.0ubuntu3-noarch
 - Rocket Version: 0.5.0-rc.1

**Additional Context**
The issue seems to be at line `320` in `/core/lib/src/shield/policy.rs`:
```rust
Hsts::Preload(age) => format!("max-age={}; preload", age.whole_seconds()),
```

**Comment by somehowchris** [comment]
Ok fair point, Sergio the maintainer of the project is off due to personal matters, just trying to add some points for discussions.

* the `includeSubDomains` directive and the `hstspreload list` are related though not the same, the preload list isn’t an official spec but used by basically all browsers
* running that on a subdomain will only give you the opportunity to have hsts enabled on further subdomains (`my-page.example.com` => `*.my-page.example.com`)
* serving this directive on a subdomain will be excluded for the `preload list` as it would need to be served at the hosts domain
* I don’t see a direct disadvantage to have it but would love to see a flag, in some cases http traffic is still needed on subdomains, would default to true with an optional Boolean to set it to false. Basically an `opt-out`
* __Please add it to the documentation__

**Comment by Soham3-1415** [comment]
Yeah, because the HSTS preload list is not an official spec, it is tricky to definitively say what is "correct". However, I am not aware of any other preload list that relies on the preload directive. I think the best solution depends on what the intent of this option is. I think clarifying the documentation to address this is necessary.

What follows is based on the assumption that this option is intended to conform to the requirements of the preload list at https://hstspreload.org:

> serving this directive on a subdomain will be excluded for the preload list as it would need to be served at the hosts domain

Yes, I think the preload list directive is only useful if you are serving the header at the hosts domain, but it was not entirely clear to me what this means. I am unsure if, for example, one can add `example.co.uk` to the preload list.

> running that on a subdomain will only give you the opportunity to have hsts enabled on further subdomains (my-page.example.com => *.my-page.example.com)

You cannot get onto the preload list without the `includeSubDomains` directive, so even though it is a separate directive, it is a prerequisite to use `preload` effectively. Thus, it is not possible to have HSTS disabled on subdomains and also be on the preload list. These are conflicting intentions.

> I don’t see a direct disadvantage to have it but would love to see a flag, in some cases http traffic is still needed on subdomains, would default to true with an optional Boolean to set it to false. Basically an opt-out

As the preload list exists now and has for some time, `includeSubDomains` is a requirement, and while I agree that a flag would certainly add configurability, I think it is only useful in the case that the preload list requirements change or if another preload list with different requirements is desired. Whether this is worth doing or not is certainly debatable.

I think right now, the current expectation is for compatibility with the Chromium preload list form, and as such, the current header is a bug. Maybe adding a flag would be better as an additional feature?

**Comment by somehowchris** [comment]
* Host domain means `example.com`. If you are serving this on `api.example.com` it will not be added to the hstspreload-list.
* `includeSubDomains` is deffinitly not a requirement as companies like WhatsApp or Ticktock still have apis over casual http (these are some public examples but I am certain there are a lot more)
* Including this by default with no option to overwrite it will shatter some business setups. Yes the preload list is only for public websites but again, it isn't an official spec but `includeSubDomains` is. Adding this directive would crush setups on internal networks for servers on internal subdomains which servers do not use tls

**Comment by Soham3-1415** [comment]
I am not disputing that `includeSubdomains` is not always desirable. I 100% agree with you there. I am simply quoting the requirements on the HSTS preload list submission form.

> The includeSubDomains directive must be specified.

The host domain is the only one that needs that preload directive if you want to enable preload. If you enable preload, that HSTS header must also have the `includeSubDomains` directive. `whatsapp.com` is on the preload list. `whatsapp.com` also has `includeSubDomains`. `tiktok.com` does not have HSTS and is not on the preload list.
![poc1](https://user-images.githubusercontent.com/17441466/148468137-68437f00-2932-424b-885e-b01ca0add467.png)
![poc2](https://user-images.githubusercontent.com/17441466/148468143-00806f44-56c5-4f08-ad56-22bbb38af9d6.png)

**Comment by somehowchris** [comment]
Weird, just listened to some tech talk from some engineers at whatsapp and ticktok but anyway. That's just an example not the point.

Still, if you could update your PR with the docs needed and the optional overwrite would be awsome.

And in the end, the word of @SergioBenitez counts

**Comment by Soham3-1415** [comment]
If I changed `Hsts::Preload(Duration)` to `Hsts::Preload(Duration, bool)`, that's a breaking change. Do we want it to be a breaking change? To avoid breaking the API, I think another variant could be added. Is there a better way to do this?

**Comment by somehowchris** [comment]
I may have a bit of a different opinion on that. Rust is type heavy, we have cargo for versioning and rustc will tell you whats wrong. As long as the stuff is clearly documented and semantic it shouldn't be that much of a braking change. 

Yes it will break compilation due to rusts heavy type checking but it doesn't brake functionality

**Comment by Soham3-1415** [comment]
I've updated the PR with documentation changes and an added flag.
