### ISSUE TITLE
mTLS release

### ISSUE THREAD

**Issue by digitwolf** [SergioBenitez/Rocket#2054]
I would like to use the mTLS feature, but it's not released yet.
When are you planning to publish this to crates.io?

**Comment by somehowchris** [comment]
The maintainer of this project, Sergio, is currently off due to personal reasons, so no plans until now

**Comment by digitwolf** [comment]
Does anyone else have permissions to release? This is kinda a big bummer. Would be sad if the project died because the creator no longer has time to maintain it.

**Comment by somehowchris** [comment]
No. But we are discussing to manage a fork

**Comment by somehowchris** [comment]
You cam still use it by pointing the cargo dep to the master branch

**Comment by digitwolf** [comment]
I actually can't. My build system prohibits that. So I gonna have to post a copy of rocket crate

**Comment by kolbma** [comment]
https://github.com/rocket-org/Rocket/issues/4

**Comment by SergioBenitez** [comment]
This will be in `rc2` and `0.5.0`.

**Comment by digitwolf** [comment]
This is awsome! Thank you!
