### ISSUE TITLE
How to set multiple cookies?

### ISSUE THREAD

**Issue by flosse** [SergioBenitez/Rocket#206]
How can I set multiple cookies in one response?
I tried two things:

1. Use one `&Cookies` argument:

```rust
#[post("/accounts/login", format="application/json", data = "<data>")]
fn login(db: State<ConnectionPool>,
         data: JSON<FirstLogin>,
         cookies: &Cookies)
         -> result::Result<(), Failure> {
    match login_user(&mut *db.get().unwrap(), data) {
        Ok(key) => {
            cookies.add(Cookie::build(COOKIE_USER_KEY, data.name.clone())
                .path("/")
                .finish());
            cookies.add(Cookie::build(COOKIE_API_KEY.to_string(), key)
                .path("/")
                .finish());
            Ok(())
        }
        Err(err) => {
            match err {
                Error::InvalidCredentials => Err(Failure(Status::Unauthorized)),
                _ => Err(Failure(Status::InternalServerError)),
            }
        }
    }
}
```

2. Use two `&Cookies` arguments:

```rust
#[post("/accounts/login", format="application/json", data = "<data>")]
fn login(db: State<ConnectionPool>,
         data: JSON<FirstLogin>,
         u_cookies: &Cookies,
         k_cookies: &Cookies)
         -> result::Result<(), Failure> {
    match login_user(&mut *db.get().unwrap(), data) {
        Ok(key) => {
            u_cookies.add(Cookie::build(COOKIE_USER_KEY, data.name.clone())
                .path("/")
                .finish());
            k_cookies.add(Cookie::build(COOKIE_API_KEY.to_string(), key)
                .path("/")
                .finish());
            Ok(())
        }
        Err(err) => {
            match err {
                Error::InvalidCredentials => Err(Failure(Status::Unauthorized)),
                _ => Err(Failure(Status::InternalServerError)),
            }
        }
    }
}
```

It doesn't matter the response only contains one `Set-Cookie` header :(

**Comment by SergioBenitez** [comment]
Just confirmed that this is a bug. Investigating the issue now.

**Comment by flosse** [comment]
> Investigating the issue now.

Thank you!

**Comment by SergioBenitez** [comment]
The issue stems from Hyper in what appears to be a present limitation. In particular, I assumed that calling [set_raw](https://hyper.rs/hyper/v0.10.0/hyper/header/struct.Headers.html#method.set_raw) using the same header name would set multiple versions of the header, but this appears to be incorrect. As a result, only one `Set-Header` header gets sent to the client. It does not appear that there is any way to set multiple headers of the same name in Hyper at the moment.

I've pinged @seanmonstar to try to resolve this.

**Comment by ineedhelppls1** [comment]
so how do i add multiple cookies to a jar? i'm trying to add two named "_ga" and nothing works

**Comment by jebrosen** [comment]
> i'm trying to add two named "_ga"

That is not possible, due to HTTP itself - cookie names must be unique, unless they have a different domain+path from each other.
