### ISSUE TITLE
Allowing custom body for error statuses for responders.

### ISSUE THREAD

**Issue by eltiare** [SergioBenitez/Rocket#2061]
**Current behaviorr**

Currently if you return an `Ok` response from a responder with an error code, a catcher always catches it and overwrites the body. With the following response being returned from a responder I do not get the body I had written to the response but instead the catcher response. 

```
Ok(Response::build()
      .header(ContentType::JSON)
      .status(Status::UnprocessableEntity)
      .sized_body(body.len(), Cursor::new(body))
      .finalize())
```

**Why this is an issue**

When designing REST services it is often prudent to use status codes with information. In this case, I wish to pass back which fields failed validation. I cannot do this and set an HTTP error code.

**Suggested Changes**

If a responder returns an `Ok` response, do not invoke a catcher.

**Comment by somehowchris** [comment]
You could use the type `(Status, Json<MyCustomErrorStruct>)` as an error type of a `Result`

**Comment by eltiare** [comment]
This is the result type: 

```
pub type Result<'r> = std::result::Result<Response<'r>, crate::http::Status>;
```

It does not accept a tuple, it only accepts a `Status`.

**Comment by somehowchris** [comment]
You mean like [that](https://github.com/somehowchris/rocket-tracing-fairing-example/blob/main/src/main.rs#L121) shouldn't work?

**Comment by eltiare** [comment]
I'm talking about responders: https://rocket.rs/v0.5-rc/guide/responses/#responder

**Comment by somehowchris** [comment]
Ok, your example isn‘t mentioned until [`Implementations`](https://rocket.rs/v0.5-rc/guide/responses/#strings) and what I provided you was an implementation of [wrapping](https://rocket.rs/v0.5-rc/guide/responses/#wrapping). May I ask for a concrete example? Couldn't reproduce yet

**Comment by eltiare** [comment]
Return an instance of `ResponderExample` from handler function:

```
pub struct ResponderExample;

impl<'r, 'o: 'r> Responder<'r, 'o> for ResponderExample {
    fn respond_to(self, _req: &'r Request<'_>) -> rocket::response::Result<'o> {
        let body = "It worked!";
        Ok(Response::build()
            .status(Status::UnprocessableEntity)
            .sized_body(body.len(), Cursor::new(body))
            .finalize())
    }
}
```

**Comment by somehowchris** [comment]
Well your example just works like intended.

```rust
// main.rs
#[macro_use]
extern crate rocket;

use std::io::Cursor;
use rocket::Response;
use rocket::Request;
use rocket::response::Responder;
use rocket::http::Status;

pub struct ResponderExample;

impl<'r, 'o: 'r> Responder<'r, 'o> for ResponderExample {
    fn respond_to(self, _req: &'r Request<'_>) -> rocket::response::Result<'o> {
        let body = "It worked!";
        Ok(Response::build()
            .status(Status::UnprocessableEntity)
            .sized_body(body.len(), Cursor::new(body))
            .finalize())
    }
}

#[get("/")]
fn test() -> ResponderExample {
    ResponderExample{}
}

#[launch]
fn rocket() -> _ {
    rocket::build().mount("/", routes![test])
}
```

Òutputs:
```sh
curl -v http://0.0.0.0:8000/
*   Trying 0.0.0.0:8000...
* TCP_NODELAY set
* Connected to 0.0.0.0 (127.0.0.1) port 8000 (#0)
> GET / HTTP/1.1
> Host: 0.0.0.0:8000
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 422 Unprocessable Entity
< server: Rocket
< x-frame-options: SAMEORIGIN
< x-content-type-options: nosniff
< permissions-policy: interest-cohort=()
< content-length: 10
< date: Mon, 10 Jan 2022 10:33:34 GMT
< 
* Connection #0 to host 0.0.0.0 left intact
It worked!
```

**Comment by eltiare** [comment]
Is this on the latest or on rc-1? I'm getting back the default catcher response on rc-1. I was running into all sorts of weird issues when I tried the git repo, so I wasn't able to test there.

**Comment by somehowchris** [comment]
Yes https://github.com/somehowchris/rocket-tracing-fairing-example/blob/main/Cargo.toml#L9

**Comment by eltiare** [comment]
I apologize, I made a rookie mistake and wasn't watching the logs. The 422 error was due to the dataguard failing and not my response.
