### ISSUE TITLE
Cookie usage interferes with FlashMessage

### ISSUE THREAD

**Issue by philwhineray** [SergioBenitez/Rocket#207]
Hit a problem that using cookie code in a route prevents the `_flash` cookie being set in the response.

Update to the `todo` demo shows the problem - the `mykey` cookie is set but the `_flash` one is not with the result that no message is shown in that case.

[cookies-patch.txt](https://github.com/SergioBenitez/Rocket/files/794417/cookies-patch.txt)

**Comment by SergioBenitez** [comment]
This is likely a duplicate of #206.

**Comment by SergioBenitez** [comment]
I've pushed a fix for #206 in master. Can you try using master and confirm that this is a duplicate?

**Comment by philwhineray** [comment]
Confirmed, thanks!
