### ISSUE TITLE
sync_db_pools' re-export of Diesel does not export macros

### ISSUE THREAD

**Issue by OJFord** [SergioBenitez/Rocket#2083]
**Existing Functionality**

```rs
use rocket_sync_db_pools::diesel
```

Does not re-export macros.

**Suggested Changes**

```rs
#[macro_use]
pub extern crate diesel
```

behind feature flag.

**Alternatives Considered**

Currently downstream can (and must) have `diesel` as a direct dependency as well, in order to be able to import macros. This works, but isn't ideal not least because of needing to keep versions in sync.

**Additional Context**

**Comment by SergioBenitez** [comment]
I don't think is actually possible. That it, it simply doesn't work as expected in Rust; macros are a weird 1.5 class citizen in Rust when it comes to namespacing and path modularity.

If there is some way to make this work perfectly, I'm all in for a PR with the implementation and a reworked `diesel` example in `examples` that makes use of this.

**Comment by OJFord** [comment]
I believe it is, but I might be missing something:
https://github.com/rust-lang/rust/issues/17103
https://stackoverflow.com/questions/50037091/how-to-use-macros-from-re-exported-crates

I might get around to having a fiddle with it & potential PR.
