### ISSUE TITLE
License of site/

### ISSUE THREAD

**Issue by ajorg-aws** [SergioBenitez/Rocket#2089]
The file `site/LICENSE` gets caught in our filters, raising the software as requiring further review. The license is totally fine for what it applies to (the website) but I wondered if it would make sense to put the site, if you're using GitHub pages, on a [`gh-pages` branch](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#:~:text=The%20default%20publishing%20source%20for%20project%20sites%20is%20the%20root%20of%20the%20gh%2Dpages%20branch.) instead so that the site content doesn't get included and doesn't get caught in license filters like ours.

No problem if that's a bad suggestion, I just wondered if it might be desirable. If it's not, we're happy to deal with the filter issues on our end.

**Comment by SergioBenitez** [comment]
I don't like abusing git branches in this manner, but I generally agree that it would be nice to separate the two logically distinct projects. There are downsides, however, primarily that we'd need to replicate testing tooling and figure how to keep the two repositories in-sync.

For now, I think it's best to keep things as they are. If there's something simple we can do to aid your tooling, however, I'm happy to oblige.
