### ISSUE TITLE
Default address to 0.0.0.0 in release mode 

### ISSUE THREAD

**Issue by veritem** [SergioBenitez/Rocket#2091]
**Existing Functionality**

Currently, the rocket doesn't make 0.0.0.0 the default address for build 

**Suggested Changes**

I can't count how many hours I've wasted deploying the rocket app in production but the API can't be reached because rocket doesn't default to the `0.0.0.0` address. If this is added it would save the time of so many people.

**Comment by jkbbwr** [comment]
Strongly disagree with this, services should deploy safe by default. 
If you forget configuration, that is on you.

**Comment by SergioBenitez** [comment]
We specifically decided against this to avoid confusion: there's one address to remember.
