### ISSUE TITLE
[suggestion] Handler trait

### ISSUE THREAD

**Issue by petar-dambovaliev** [SergioBenitez/Rocket#2092]
There doesn't seem to be a handler trait that clearly establishes an interface between the application and the user handler functions.
At our company, we created a `tracing_rocket` crate which allows for open telemetry spans (by implementing additional features in the macros) from the code calling the user defined handler.
We use that, instead of the rocket macros that generate handlers.

When you combine that (not having a contract) with the fact that part of the application routing is happening inside the generated handler (forwarding), it leaves a lot of room for our crate breaking on a "non breaking change" in rocket.

**Comment by SergioBenitez** [comment]
There are in fact _two_ `Handler` traits:

 * https://api.rocket.rs/master/rocket/route/trait.Handler.html
 * https://api.rocket.rs/master/rocket/catcher/trait.Handler.html

But I think solving #21 (via #1410) might actually be what you'd want.
