### ISSUE TITLE
context! macro is private

### ISSUE THREAD

**Issue by jakob-lilliemarck** [SergioBenitez/Rocket#2093]
I can't use the `context!` macro as described here:
[https://api.rocket.rs/master/rocket_dyn_templates/struct.Template.html](https://api.rocket.rs/master/rocket_dyn_templates/struct.Template.html)

Seems identical to closed (but not resolvled?) issue:
[https://github.com/SergioBenitez/Rocket/issues/1771](https://github.com/SergioBenitez/Rocket/issues/1771)

relevant parts of cargo.toml
```
[dependencies]
rocket = "0.5.0-rc.1"

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.1"
features = ["handlebars", "tera"]
```
The `rocket_dyn_templates = 0.1.0-rc.1` is specified to depend on `rocket = 0.5.0-rc.1` as per the info at crates.io:

https://crates.io/crates/rocket_dyn_templates/0.1.0-rc.1/dependencies

In main.rs I do:
```
#[get("/")]
fn index() -> Template {
    Template::render("index", context! { test: "test" })
}
```

I get:
```
error: cannot find macro 'context' in this scope
  --> src/main.rs:27:31
   |
27 |     Template::render("index", context! { test: "test" })
```

I believe this to be identical to the documentation :/ what am I missing?

Attempting `use rocket_dyn_templates::{context}` yields `module 'context' is private`

I'm using Manjaro:
`Linux version 5.10.93-1-MANJARO (builduser@fv-az82-887) (gcc (GCC) 11.1.0, GNU ld (GNU Binutils) 2.36.1) #1 SMP PREEMPT Thu Jan 20 09:46:07 UTC 2022
`

**Comment by jose-juarez-renteria** [comment]
I am getting the same error with the context! macro

**Comment by blackghost1987** [comment]
It's a bug in the documentation. The code has been changed, the macro became private, but the documentation is not updated. The crate maintainer is away for personal reasons, so we have no way of fixing this currently.

The workaround is really easy though, you can simply define a serializable struct and use that for the context, that's what the macro would do anyway.

**Comment by jose-juarez-renteria** [comment]
Exactly, that is what I had to do at the end to workaround it. This is a link to another thread indicating to copy/paste the macro into your code https://github.com/SergioBenitez/Rocket/discussions/2001#discussioncomment-2028553

**Comment by jakob-lilliemarck** [comment]
Ah, thank you! Ill look into it!

**Comment by SergioBenitez** [comment]
> It's a bug in the documentation. The code has been changed, the macro became private, but the documentation is not updated. The crate maintainer is away for personal reasons, so we have no way of fixing this currently.
> 
> 
> 
> The workaround is really easy though, you can simply define a serializable struct and use that for the context, that's what the macro would do anyway.

It's the other way around, actually: the macro is new and no release currently has it, but you're looking at documentation for unreleased versions.
