### ISSUE TITLE
Disable default responder implementations 

### ISSUE THREAD

**Issue by cameron1024** [SergioBenitez/Rocket#2098]
**Is your feature request motivated by a concrete problem? Please describe.**

I want to be able to "turn off" all of the implementations of `Responder` that are provided by Rocket

I would like to be able to fully restrict the types that can be returned from *any* endpoint in my entire application. In particular, I have the following types:

```rust
// marker trait for "things that are allowed to be returned by request handlers"
trait ValidResponse: serde::Serialize {}

// approx. 1-to-1 mapping between endpoints and response types
impl ValidResponse for LoginResponse {}
impl ValidResponse for LogoutResponse {}
// many more, generated by a macro

// there are more variants than listed here, just for example
enum ApiResponse<T: ValidRepsonse> {
  Ok(T),
  Err {
    status: Status,
    data: ErrorResponse  // structured data, written to the response body as json
  },
}

impl<T: ValidResponse> Responder for ApiResponse<T> {
  // this implementation is fairly complex, involved in auditing, alerting, logging, etc
}
```

However, developers (especially those not familiar with Rust/Rocket) can still just return a plain string from a request handler, since the only requirement is that they return an `impl Responder`.

I'd like to be able to force "all responses go through this particular implementation" at compile time

**Why this feature can't or shouldn't live outside of Rocket**

The orphan rule prevents a crate outside Rocket defining impls for Rocket traits for built-in types. Even without that, it would still be a huge breaking change and very un-ergonomic to require existing users to add a new `rocket_responder_impls` crate to their list of dependencies

**Ideal Solution**

A feature flag (maybe called `responder_impls`) that is enabled by default, that provides all the default implementations for `Responder` 

**Alternatives Considered**

Currently I just use a combination of comments and all-caps warnings in the readme to warn devs not to return a type other than `ApiResponse` from a request handler.

Of course, code review mostly works, but I feel the benefits of using the type system instead of relying on code review are well understood by the Rust community 😜 

**Additional Context**

I don't know of any other systems that do what I'm suggesting, but perhaps Rocket can be the first :). I'm really enjoying the "make the compiler enforce your invariants", and would like to extend that. This feature allows me to add "all errors are serialized in the same format, and interact with the correct logging/alerting infrastructure" to the list of things the compiler keeps track of for me.

If this sounds like something that's valuable to people, I'd be happy to open a PR for it

Really enjoying the framework, keep up the good work!

**Comment by SergioBenitez** [comment]
I can't imagine Rocket ever supporting this directly. You _could_ maintain an internal patch that makes the right changes to Rocket's codegen to enforce this, of course,.

But here's another idea: abuse sentinels (with the help of specialization...somehow) in the following way:
  * Implement a _passing_ `Sentinel` for `ApiResponse<T>` for all `T`.
  * Implement a _failing_ `Sentinel` for everything else.

I _think_ specialization on nightly will allow you to do this.
