### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by codesculpture** [SergioBenitez/Rocket#2099]
Actually Im new To rust and im a nodejs dev but i need to learn about rust through Backend Server..
So i chose rocket.. I tried to  do it via the documentation..
so i created new rust project via cargo CLI..
And added rocket dependency `rocket = "0.5.0-rc.1"` as mentioned [https://rocket.rs/v0.5-rc/guide/getting-started/#installing-rust](url) 

and started `cargo run`  and everything started to  compile few mins and suddenly my antivirus said virus blocked and says its been blocked and soon as this happens my antivirus gave big warning to restart so i dint understand.. what is this.. because my antivirus genuine(McAfee) and its not just fake screaming... and pls anyone explain me wht is this

**Comment by somehowchris** [comment]
May you please elaborate on what your anti virus said? I guess you are on windows if you use McAfee....? What did it say? What code did you write? Do you have a repository to link to? Are u using wsl, cmd or powershell?

**Comment by codesculpture** [comment]
Hi yeah i am using windows and i saw my antivirus said we found a virus and we blocked it.. yeah it is what it do usually when virus executed..  Then i wiped the directory immediately cause i dont want to affect my pc and mcafee told it is a sever levle of virus but sorry i dint have any log so i cant explain it.. and i just copied the code from the getting started page the code is `#[macro_use] extern crate rocket;

#[get("/")]
fn index() -> &'static str {
    "Hello, world!"
}

#[launch]
fn rocket() -> _ {
    rocket::build().mount("/", routes![index])
}`

and yeah it is it.. and as it said to start server run `cargo run `and thats what i do..

ok this is the answer from me..

Now im gonna say from my thoughts (like how it happend or what it is),
As i said im a NodeJS dev, so we use `npm`
for packages to use in our  app....

so  like that here rust i think cargo is doing that thing(i mean not exactly but likely) so after i run cargo run maybe some suspicious packages may be downloaded?? and it executed? or it came via rocket packages? these are what i thought... And finally im not sure above thoughts because im very new to Rust...
And im explored this issue someonelse is already had... But i dint saw it happened to someother before..
So i dont know why it happens and how it happens.. very confused

**Comment by blackghost1987** [comment]
You should copy the exact message from your antivirus here, or post a screenshot. An important detail is what process raised the warning? Is it cargo itself, some compile tooling, or is it your application? Also what directory has it wiped?
You should first try to only call `cargo build`, and see if it raises a warning. If not, try to start the "exe" from the target directory manually, because `cargo run` simply calls `cargo build` then starts the built executable. If it only happens on starting the exe, then the "virus" is actually your own application, which is unlikely to have anything malicious in it if it's really just a hello-world app.
Maybe McAffee is just too sensitive, and it thinks ANY application that tries to start a server is probably malicious.

**Comment by codesculpture** [comment]
Yeah, First of all it dint wiped any directory, i wiped the project directory when i see its say virus.. Sorry for that.. May be i typed wrong... and it happended when compiling rocket-*(something i forget it) And next yeah maybe mcafee is too sensitive... And im using softwares all are genuine (rustcompiler,vscode,)...
And yeah i think mcafee is problem.. But here my one question Just i wanna say is no one faced this problem before.... Because yeah as u  said mcafee is prob but im asking why mcafee is blocking this.. and i think this is not the right place to ask this question for that... So im closing this... and still i dont know why it is blocking rust binaries maybe im overthinking of it.. And Thank You Both For Replying
