### ISSUE TITLE
Implement `std::ops::Try` for `rocket::request::Outcome`

### ISSUE THREAD

**Issue by Aurora2500** [SergioBenitez/Rocket#2102]
**Is your feature request motivated by a concrete problem? Please describe.**

I sometimes create request guards that act as sort of "smart wrappers" around request guards.
Like a `User` request guard that depends on a `SessionID` request guard.

Implementing a Request guard consists of implementing a function that returns `rocket::request::Outcome`, and calling
another guard can be done trough `rocket::request::Request::guard`, which also returns an `Outcome`, thus if `Try` were
implemented, one could simply use the `?` syntax to retrieve the value from the `Outcome`.

**Why this feature can't or shouldn't live outside of Rocket**

You can only implement a trait for a type if either the trait or the type are defined in the crate.
`std::ops::Try` is defined in the standard library, and `rocket::request::Outcome` is defined inside the rocket.rs library.
Thus this implementation could only be written inside the Rocket library. 

**Ideal Solution**

The solution would be to just implement `std::ops::Try` for `rocket::request::Outcome`, along with any documentation
and tests needed to make sure it works properly.

**Alternatives Considered**

There isn't much of an alternative other than using match blocks that return early, but this produces unnecesarily verbose code
for the same functionality.

**Comment by Aurora2500** [comment]
Looking trough the versions, it seems it is already implemented for version 0.4 but not for version 0.5, is there any reason for this?

**Comment by Punie** [comment]
@Aurora2500 I believe this feature was removed in version 5 because rocket made the move to be able to compile in stable rust and `std::ops::Try` is still an unstable nightly-only API.

However, the [`try_outcome`](https://api.rocket.rs/v0.5-rc/rocket/outcome/macro.try_outcome.html) has been added to fill that functionality and is indeed nicer to use than raw match blocks.

Hope this helps :)
