### ISSUE TITLE
Not found a link from the Guide search page.

### ISSUE THREAD

**Issue by inkusu** [SergioBenitez/Rocket#2119]
**Description**

I move from the top page of the site to the Guide page.
I searched "model" in the search box.
When I select a search result, the link is broken.

![Mar-09-2022 16-27-37](https://user-images.githubusercontent.com/1542500/157394744-388329da-edcc-475a-a974-fff650c2f65e.gif)

**Environment:**

 - docs version v0.5-rc
 - Chrome

**Comment by SergioBenitez** [comment]
Neat GIF! This is already fixed in master, however. Try https://rocket.rs/master/guide.
