### ISSUE TITLE
Query string not percent-decoded?

### ISSUE THREAD

**Issue by messense** [SergioBenitez/Rocket#212]
Rocket version: 0.2.1

Sample code:

```rust
#[derive(FromForm, Debug)]
struct Edge<'r> {
     from: &'r str,
     to: &'r str,
}

#[get("/edge?<edge>")]
fn has_edge(edge: Edge) -> JSON<Value> {
  println!("{:?}", edge);
}
```

Fire a request using HTTPie:

```bash
http http://localhost:8000/edge\?from\=北京\&to\=上海
```

Output:

```
GET /edge?from=%E5%8C%97%E4%BA%AC&to=%E4%B8%8A%E6%B5%B7:
    => Matched: GET /edge?<edge>
Edge { from: "%E5%8C%97%E4%BA%AC", to: "%E4%B8%8A%E6%B5%B7" }
```

**Comment by messense** [comment]
Oh, just found that it's already reported in #43 and has an open PR #211

**Comment by SergioBenitez** [comment]
To be clear, you should use `String` to get a decoded value.

**Comment by messense** [comment]
I think this should be documented.

**Comment by messense** [comment]
@SergioBenitez I mean in here: https://rocket.rs/guide/requests/#query-strings

And the [query string example](https://github.com/SergioBenitez/Rocket/blob/v0.2.1/examples/query_params/src/main.rs) uses `&str`, kind of misleading for newbies like me.
