### ISSUE TITLE
Broken docs for `rocket_db_pools`

### ISSUE THREAD

**Issue by jmaargh** [SergioBenitez/Rocket#2120]
**Description**

The docs for the `rocket_db_pools` crate 404s

**To Reproduce**

Click the link "[crate docs](https://api.rocket.rs/v0.5-rc/rocket_db_pools)" from the [crate REAME](https://github.com/SergioBenitez/Rocket/blob/v0.5-rc/contrib/db_pools/README.md)

**Environment:**

 - Web browser

**Comment by SergioBenitez** [comment]
The README is for master for which the docs exist.

**Comment by jmaargh** [comment]
That may be the case, but even on [master README](https://github.com/SergioBenitez/Rocket/blob/master/contrib/db_pools/README.md) the link is broken, pointing at the a `v0.5-rc` URL. This was the only place I could find docs for this crate (not on docs.rs or lib.rs) and the one link I found is broken.
