### ISSUE TITLE
Diesel SQLite database backend does not handle SQLITE_BUSY status, causing database locked errors.

### ISSUE THREAD

**Issue by christian-oudard** [SergioBenitez/Rocket#2130]
**Description**

When multiple requests are using the same SQLite database, they error out with the message `DatabaseError(__Unknown, "database is locked")`. This only happens when there is a transaction going, and the same table is being updated by multiple requests.

**To Reproduce**

Here is a pretty minimal example of the problem:
https://github.com/christian-oudard/rust_tutorial/tree/0edcd03dd5b92926790d93be57bf996c4a339627/rocket_tutorial

**Expected Behavior**

The `busy_timeout` setting of SQLite should be respected here, and make the threads block until the database is available.

**Environment:**

 - OS Distribution and Kernel: Ubuntu 21.10
 - Rocket Version: 0.4.10

**Additional Context**

This seems to be a Diesel or R2D2 problem, but the usage pattern is a very common one among web apps. Using write-ahead-logging and setting the busy timeout don't work.

**Comment by SergioBenitez** [comment]
Please use 0.5.0-rc to see if the problem still exists. If it does, this is likely a configuration issue with SQLite directly. If you enable debug logging, we should be able to see where the error is coming from.

**Comment by christian-oudard** [comment]
The problem still happens on 0.5.0-rc.1, and debug logging does not appear to show much.
https://github.com/christian-oudard/rust_tutorial/tree/03ca5d1186cfcf3115a5cca9cb49ad78b5de48e6/rocket_tutorial

**Comment by christian-oudard** [comment]
Doing some more research inside Diesel, it is never actually handling SQLITE_BUSY. Rusqlite does implement handling of SQLITE_BUSY. I think the only solution here is to switch to Rusqlite as a backend instead.

**Comment by christian-oudard** [comment]
I've done some more work on this, and it's not really a bug. I would say it is a confusing pitfall of the way that Diesel, Rocket, and SQLite interact around transactions and database file locking.

SQLite tends to lock the database in ways that are unavoidable when many threads are attempting to begin transactions and write to the same table. The only solution I was able to find was to implement a retry loop with exponential backoff.

Should we add something like this to the Diesel or Rocket libraries? This should probably become a feature request to find a convenient way to solve these locking problems without weeks of investigation by new developers.

https://github.com/christian-oudard/sqlite-locking

Here's an example of the retry-able transaction. Thoughts? Feedback?

```
const BASE_DELAY_MS: u32 = 10;
const NUM_RETRIES:u32 = 5;

pub fn transaction<T, E, F>(conn: &PooledConnection<ConnectionManager<SqliteConnection>>, f: F) -> Result<T, E>
where
    F: Clone + FnOnce() -> Result<T, E>,
    E: From<Error>,
{
    for i in 0..NUM_RETRIES {
        let r = conn.immediate_transaction::<T, E, F>(f.clone());
        if r.is_ok() || i == (NUM_RETRIES - 1) {
            return r;
        }
        sleep(Duration::from_millis((BASE_DELAY_MS * 2_u32.pow(i)) as u64));
    };
    panic!("Should never reach this point."); 
}
```

**Comment by SergioBenitez** [comment]
> Should we add something like this to the Diesel or Rocket libraries? This should probably become a feature request to find a convenient way to solve these locking problems without weeks of investigation by new developers.

I'd be in favor of incorporating such a solution into `db_pools`. Please submit a PR!

Since this issue isn't something to "fix" in Rocket, I'm closing this out. But I'd love to make it easier to avoid this pitfall.
