### ISSUE TITLE
Any plans to support Swagger?

### ISSUE THREAD

**Issue by pwrdwnsys** [SergioBenitez/Rocket#214]
Having implemented a small API service in Rocket, it would be very nice to have templating support via Swagger for a larger implementation. Thanks!

**Comment by mehcode** [comment]
I think this makes the most sense in its own crate that would support many frameworks, including Rocket. 

There is a very basic implementation of swagger in [rustless](https://github.com/rustless/rustless/blob/master/src/batteries/swagger.rs). I would think that an interested party's first step would be generalizing that into its own `swagger` crate and have it work with both rustless and Rocket.

**Comment by SergioBenitez** [comment]
While I don't think swagger is something that Rocket should support internally, I _do_ think Rocket should expose all of the information necessary to implement swagger support externally. To that end, if someone wants to implement swagger support for Rocket, I'm happy to work with them to ensure that Rocket exposes all of the necessary information.

For these reasons, I'm closing this issue. Looking forward to working with anyone who wants to implement this!
