### ISSUE TITLE
Add must_use for Rocket<Build> and Rocket<Ignite>

### ISSUE THREAD

**Issue by Alvenix** [SergioBenitez/Rocket#2146]
I think adding must_use may help beginners who are just starting in Rust. For example here is a simplified code for a mistake which I saw:

```
#[launch]
fn rocket() -> _ {
   // Assume specific configuration is here
   let figment = Figment::from(rocket::Config::default());

   rocket::custom(figment);

   // Why is my configuration not working?
   rocket::build()
}

```

However, due to Rocket<T> being a generic type this may not be possible?

**Comment by SergioBenitez** [comment]
I like it. Done!
