### ISSUE TITLE
EventStream has incorrect event name

### ISSUE THREAD

**Issue by grasserik2** [SergioBenitez/Rocket#2152]
**Description**

Sometimes the event name is "message" instead of the given name.
![wrongEventName](https://user-images.githubusercontent.com/104515061/165555265-640529f0-7394-49e0-ba67-3c6807451496.png)

**To Reproduce**

[example.zip](https://github.com/SergioBenitez/Rocket/files/8573373/example.zip)

**Expected Behavior**

The event should have the correct name ("progress" in the example).

**Environment:**

 - OS Distribution and Kernel: Ubuntu 21.10
 - Rocket Version: "0.5.0-rc.1"

**Additional Context**

It seems that the occurrences align with the heartbeat (30s, 60s, 90s).

**Comment by SergioBenitez** [comment]
Confirmed. Working on a fix.
