### ISSUE TITLE
fairings: add support for after_response

### ISSUE THREAD

**Issue by toxeus** [SergioBenitez/Rocket#2161]
**Is your feature request motivated by a concrete problem? Please describe.**

Yes, I need to trigger a new state in a state machine but only if I can be sure that the client has received the response.

**Why this feature can't or shouldn't live outside of Rocket**

To my knowledge there is no workaround outside of Rocket.

**Ideal Solution**

The ideal solution is to add another fairing `after_response` that fires after the response has been sent successfully.

**Alternatives Considered**

I read the rocket docs. There seems to be no alternative.

**Comment by SergioBenitez** [comment]
Can you comment on what your use-case, specifically and in detail, would be? One workaround you can consider is implementing `Drop` on a custom Responder.

**Comment by the10thWiz** [comment]
> I need to trigger a new state in a state machine but only if I can be sure that the client has received the response.

The thing is, there is very little that can be done to actually guarantee that the client actually received the response. In many cases, it may simply be better to advance the state machine regardless of whether the client actually gets a response. Ideally, you probably want the client to be able to retry without penalty, i.e. if you think it worked, but the client thinks it failed, the client can retry, and guarantee that the server-side action happened exactly once. This concept is referred to as idempotence, and is arguably a much better solution to your issue.

Sergio's solution to use a drop implementation would work (although I think it may still run even if the response failed). It's kind of a hacky solution, but Rocket itself can't really provide much better.

**Comment by SergioBenitez** [comment]
> The thing is, there is very little that can be done to actually guarantee that the client actually received the response. In many cases, it may simply be better to advance the state machine regardless of whether the client actually gets a response.

Another approach, assuming you control the client, is to have the client trigger a new request informing you that they've received and processed some previous response. Assuming proper tracking, likely with some cookies, you can thus guarantee that you're only updating state when the client has received and acted on a response. (You can't, however, guarantee that the client _will_ send that message, only that _if_ they send that message, they got the previous response.)

**Comment by toxeus** [comment]
Thanks for all the input!

> Can you comment on what your use-case, specifically and in detail, would be? 

Sure, I'm trying to find a balance between avoiding details that just add noise to the limitation discussed here but still illustrating the use-case sufficiently.

Imagine a machine to machine HTTPS based protocol where A does a request to B. Once B has successfully responded to A it would like to inform an internal micro-service C about which request has been responded successfully to and to which machine.

> One workaround you can consider is implementing Drop on a custom Responder.

That's indeed a viable workaround. But since it involves another network interaction with service C it feels like it's too big of a "side-effect" for Drop.

> The thing is, there is very little that can be done to actually guarantee that the client actually received the response.

Agreed. Success on the TCP level doesn't mean the client could parse the response correctly, etc. But I mostly care that "from my perspective" everything was successful and want to let the micro-service C know that.

> Another approach, assuming you control the client, is to have the client trigger a new request informing you that they've received and processed some previous response.

Unfortunately, the protocol is considered stable and I cannot change it. But that would definitely be the most robust solution.

**Comment by SergioBenitez** [comment]
> That's indeed a viable workaround. But since it involves another network interaction with service C it feels like it's too big of a "side-effect" for Drop.
> 
> >

You don't need to perform the network request on `Drop`. Instead, you can keep a queue of "post-response" work to be performed around, with a task listening on the queue, and send a message on the queue on `Drop`. Something like:

```rust
#[derive(Clone)]
struct DropQueue(UnboundedSender<Msg>);

struct MyResponse {
    drop_queue: DropQueue,
}

impl Drop for MyResponse {
    fn drop(&mut self) {
        self.drop_queue.0.send(Msg { .. });
    }
}

pub fn main() {
    let (tx, rx) = tokio::sync::mpsc::unbounded_channel();

    task::spawn(async move {
        while let Some(msg) = rx.recv().await {
            // do something since response was dropped
        }
    });

    rocket.manage(DropQueue(tx))
}
```

Unlike a `after_response` hook, which can't give you information about your concrete response value, this does.

You can even generalize to use the same set-up for any kind of responder:

```rust
#[derive(Responder)]
struct DropNotice<R>(R, DropQueue);

impl<R> Drop for DropNotice<R> {
    fn drop(&mut self) {
        self.1.0.send(Msg { .. });
    }
}
```

**Comment by SergioBenitez** [comment]
I think given the concerns in https://github.com/SergioBenitez/Rocket/issues/2161#issuecomment-1120575251 coupled with the solutions in https://github.com/SergioBenitez/Rocket/issues/2161#issuecomment-1132213139 and https://github.com/SergioBenitez/Rocket/issues/2161#issuecomment-1122049702 are sufficient reasons to not implement this in Rocket.
