### ISSUE TITLE
Unused Rocket<Ignite> in main

### ISSUE THREAD

**Issue by mladedav** [SergioBenitez/Rocket#2168]
**Existing Functionality**

This is just a minor cosmetic issue that came up after migrating to 0.5-rc2.

The rc-2 release added two things:
- `launch` now returns an instance of `Rocket<Ignite>`
- `Rocket<T>` must be used.

Previously I have used a simple main like this:
```
#[rocket::main]
async fn main() -> Result<(), rocket::Error> {
    my_build().await?.launch().await?
}
```
With the two changes I have to do this now.
```
#[rocket::main]
async fn main() -> Result<(), rocket::Error> {
    _ = my_build().await?.launch().await?;
    Ok(())
}
```
I have found in the section of `general improvements` that this is by design, can I ask why? I feel like both of these can serve a purpose (although I personally don't see it right now) but they feel a bit clunky when put together.

**Suggested Changes**

I don't know if it is possible to have `#[must_use]` only for some of the generic Rockets. If we could have `Rocket<Recovered>` which would not have to be used I think that would be great.

Otherwise, I would propose to not make the rocket recoverable and keep the original API, but I expect there to be a use case I am not considering. I am happy to close this if both the changes serve a purpose.

Maybe adding a `scrape` function (or whatever happens to old rockets after deorbiting) to more clearly get rid of the instance would also be fine (but arguably we can alredy assign it to `_` or drop it or do anything else with it).

**Alternatives Considered**

Using the snippet as shown above.

Using `#[rocket::launch]`

**Comment by SergioBenitez** [comment]
You don't need to do either of those, however. The following is the preferred approach:

```rust
#[rocket::launch]
async fn rocket() -> _ {
    my_build().await?
}
```

**Comment by SergioBenitez** [comment]
> I don't know if it is possible to have `#[must_use]` only for some of the generic Rockets. If we could have `Rocket<Recovered>` which would not have to be used I think that would be great.

I don't believe this is possible, but generally all `Rocket`s must be used in some way. What would be ideal is if it could mark the `launch()` function as one such use.

> Otherwise, I would propose to not make the rocket recoverable and keep the original API, but I expect there to be a use case I am not considering. I am happy to close this if both the changes serve a purpose.

This was a very explicit design choice: we want to allow inspecting the `Rocket` instance after shutdown.



> With the two changes I have to do this now.
> 
> ```
> #[rocket::main]
> async fn main() -> Result<(), rocket::Error> {
>     _ = my_build().await?.launch().await?;
>     Ok(())
> }
> ```

Another alternative is:

```rust
#[rocket::main]
async fn main() -> Result<(), rocket::Error> {
    my_build().await?.launch().await.map(|_| ())
}
```

**Comment by SergioBenitez** [comment]
Closing due to the above.

**Comment by Stargateur** [comment]
> What is it specifically that you're finding confusing?

That rustc tell me I must use a rocket already launched ^^, I was like "wait did rc2 make the behavior of my code change ?" So I searched on the doc what I was supposed to do with the Rocket<Ignite>.

But I didn't find much and look for issue and find this one.

I decide to follow your use-case:

> This was a very explicit design choice: we want to allow inspecting the Rocket instance after shutdown.

```rust
let mission_success = rocket::build().launch().await.context(Rocket)?;

debug!("{mission_success:?}");
```

Not bad actually, more logging.

**Comment by SergioBenitez** [comment]
> Using this on methods that return a `Rocket<Build>` seems like a more precise way to go, actually! Wonderful suggestion.

This change has landed in https://github.com/SergioBenitez/Rocket/commit/26b58846a7890268808a4513cff2770873874f43.
