### ISSUE TITLE
Docs contain huge Rocket logo

### ISSUE THREAD

**Issue by ondrowan** [SergioBenitez/Rocket#2169]
**Description**

There's a huge Rocket logo floating above the content at https://api.rocket.rs/v0.5-rc/rocket/

<img width="886" alt="image" src="https://user-images.githubusercontent.com/423776/167573974-8463f27a-f655-4fcd-afd6-3f05cf3d787a.png">

**Environment:**

Firefox 100, MacOS

**Comment by SergioBenitez** [comment]
That's pretty funny! Unfortunately it's just a side effect of the browser's cache getting in the way and `rustdoc` not properly busting caches. Try a few reloads. Worst cache, open up the dev tools and check the "Disable Cache" button in the "Network" panel and reload. That should get you fresh assets.
