### ISSUE TITLE
Options::Index doesn't seem to work on 0.5.0-rc.1

### ISSUE THREAD

**Issue by gquintard** [SergioBenitez/Rocket#2171]
**Description**

If I understand the [documentation](https://api.rocket.rs/v0.5-rc/rocket/fs/struct.FileServer.html#impl) correctly, hitting a `FileServer` with a directory should return an `index.html`, but I get a 404 instead.

**To Reproduce**

`main.rs`:

``` rust
#[macro_use] 
extern crate rocket;
use rocket::fs::FileServer;                                                                                                                                                                    
              
#[launch]
fn rocket() -> _ {                                               
    rocket::build().mount("/public", FileServer::from("/tmp"))
}
```

`Cargo.toml`:

``` toml
[package]
name = "foo"         
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
```

Trying to query `localhost:8000/public/` gives a 404
```
$ http localhost:8000/public/
HTTP/1.1 404 Not Found
content-length: 383
content-type: text/html; charset=utf-8
date: Tue, 10 May 2022 16:51:45 GMT
permissions-policy: interest-cohort=()
server: Rocket
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>404 Not Found</title>
</head>
<body align="center">
    <div role="main" align="center">
        <h1>404: Not Found</h1>
        <p>The requested resource could not be found.</p>
        <hr />
    </div>
    <div role="contentinfo" align="center">
        <small>Rocket</small>
    </div>
</body>
</html>
```

and the logs show the `FileServer` forwarded the request:

```
🚀 Rocket has launched from http://127.0.0.1:8000
GET /public/:
   >> Matched: (FileServer: /tmp/) GET /public/<path..> [10]
   >> Response was `None`.
   >> Outcome: Forward
   >> No matching routes for GET /public/.
   >> No 404 catcher registered. Using Rocket default.
   >> Response succeeded.
```

**Expected Behavior**

I expected a 200 with a list of the files in `/tmp`.

**Environment:**

 - OS Distribution and Kernel: `ubuntu focal`
 - Rocket Version: `0.5.0-rc.1`

**Comment by SergioBenitez** [comment]
> I expected a 200 with a list of the files in /tmp.

Why did you expect this? This is not what the docs say. They say:

> Respond to requests for a directory with the index.html file in that directory, if it exists.

When enabled, FileServer will respond to requests for a directory /foo or /foo/ with the file at ${root}/foo/index.html if it exists. When disabled, requests to directories will always forward.

**Comment by gquintard** [comment]
Ah shoot, i definitely missed the "if it exists" bit, my bad. Is there a way for `rocket` to generate that file on the fly?

**Comment by SergioBenitez** [comment]
> Ah shoot, i definitely missed the "if it exists" bit, my bad. Is there a way for `rocket` to generate that file on the fly?

No, and generating a file would be a bit odd. However, a feature in which the handler generates a file list and returns some kind of content, perhaps HTML, with said  list if there's no index file would be a nice option for `FileServer`.
