### ISSUE TITLE
400 error catchers always receive a dummy response

### ISSUE THREAD

**Issue by SergioBenitez** [SergioBenitez/Rocket#2173]
From https://github.com/SergioBenitez/Rocket/issues/2129:

> When the request is malformed, Rocket doesn't have a valid request to pass in to the [400] error handler. Thus, there's no way for the error handler to check the Accept header and thus no way for it to determine that it should be sending JSON. This has been a wart in the error handling infrastructure for some time, and it's not clear to me what should be done, exactly. I believe this is the first issue that's been identified as a result of this wart, however, but I'll prioritize finding a solution, at least in theory.

**Comment by the10thWiz** [comment]
I've implemented a solution for this, by creating a fairing that sets the `Accept` header if it was not already set. My implementation is in #2180, let me know what you think.

**Comment by SergioBenitez** [comment]
Resolved in 5cb70ec58ca9c38f7b54d6a7a2e84b3a674e76ba.
