### ISSUE TITLE
Outdated examples

### ISSUE THREAD

**Issue by daweth** [SergioBenitez/Rocket#2178]
**Description**

Many of the examples are now outdated in the docs. 

for example: https://api.rocket.rs/v0.4/rocket/request/trait.FromRequest.html
this code does not work anymore.

**To Reproduce**

build a simple api key auth using the link above

**Environment:**

macOS 12.3.1
rocket 0.5.0-rc.1

**Comment by SergioBenitez** [comment]
You're reading the docs for 0.4, which are not the docs for 0.5. All the links from the site go to the right place, as does just going to "api.rocket.rs" directly, so we don't lead you there. Was it Google?

**Comment by daweth** [comment]
Yes, google led me there. @SergioBenitez
