### ISSUE TITLE
support $NO_COLOR environment variable

### ISSUE THREAD

**Issue by danielyrovas** [SergioBenitez/Rocket#2185]
**Existing Functionality**
Rocket already supports picking up the $ROCKET_CLI_COLORS environment variable.

**Suggested Changes**

[no-color.org](http://no-color.org/) suggests using the $NO_COLOR environment variable for CLI aplications, Rocket could pick it up similarly to $ROCKET_CLI_COLORS

**Comment by edgarogh** [comment]
I just made a basic implementation here:

https://github.com/edgarogh/Rocket/commit/5b5526a8c216fb19bdb76091739d4e1331eefe53

Let's maybe wait for some kind of approval before I open a PR.

**Comment by Mike-Neto** [comment]
I believe rocket relies on https://github.com/SergioBenitez/yansi to output colors, maybe adding support to the crate itself would be more apropriate.

**Comment by danielyrovas** [comment]
good idea
