### ISSUE TITLE
request with query string not match route with dynamic segments

### ISSUE THREAD

**Issue by jarod** [SergioBenitez/Rocket#219]
take the code from https://rocket.rs/guide/requests/#dynamic-segments
```
#[get("/<file..>")]
fn files(file: PathBuf) -> Option<NamedFile> {
    NamedFile::open(Path::new("static/").join(file)).ok()
}
```

`GET http://localhost:8000/file.html?version=1`  won't match

**Comment by impowski** [comment]
In your route you have a file, but you don't have any `version` argument.

**Comment by mehcode** [comment]
That's the issue. 

Though it's a duplicate of https://github.com/SergioBenitez/Rocket/issues/15

**Comment by SergioBenitez** [comment]
@jarod Dynamic segments only match against path segments, but you're passing in a query parameter. You need to match against the query parameter as well. You probably want something like this:

```rust
#[derive(FromForm)]
struct Version {
    version: usize
}

#[get("/<file..>?<version>")]
fn files(file: PathBuf, version: Version) -> Option<NamedFile> {
    println!("Version: {}", version.version);
    NamedFile::open(Path::new("static/").join(file)).ok()
}
```

@mehcode I don't think this is related to #15.

**Comment by mehcode** [comment]
@SergioBenitez Does this work (don't have a minute to check right now)?

```rust
#[get("/<file..>?<query>")]
fn files(file: PathBuf, query: HashMap<String, String>) -> Option<NamedFile> {
    println!("Version: {}", query.get("version"));
    NamedFile::open(Path::new("static/").join(file)).ok()
}
```

**Comment by SergioBenitez** [comment]
@mehcode No. `FromForm` is not implemented for `HashMap`. I'm unlikely to accept a request to implement it for `HashMap`.

**Comment by mehcode** [comment]
I can see a lot of use for a `rocket_contrib::Query` type that allows for a dynamic query string and easy value deserialization.

**Comment by SergioBenitez** [comment]
@mehcode If you'd like to make such a request, please open another issue.

**Comment by jarod** [comment]
maybe the proposal from @mehcode is what I need. I just want to ignore the query string ,which may contain unknown parameter.

**Comment by SergioBenitez** [comment]
If you just want to ignore it, you can easily implement `FromForm` for some `Ignored` struct:

```rust
struct Ignored;

impl<'f> FromForm<'f> for Ignored {
    type Error = ();

    fn from_form_items(form_items: &mut FormItems<'f>) -> Result<Self, Self::Error> {
        Ok(Ignored)
    }
}
```

Using it is as simple as:

```rust
#[get("/<file..>?<_anything>")]
fn files(file: PathBuf, _anything: Ignored) -> Option<NamedFile> {
    NamedFile::open(Path::new("static/").join(file)).ok()
}
```

Looks like this will result in a `non_snake_case` warning, but should work otherwise.

**Comment by jarod** [comment]
@SergioBenitez Yeah, it works. Thank you.
