### ISSUE TITLE
Add support for deadpool-diesel to rocket_db_pools

### ISSUE THREAD

**Issue by AndrolGenhald** [SergioBenitez/Rocket#2190]
I would like to move to the async rocket_db_pools crate instead of using rocket_sync_db_pools, but I'm using diesel. Deadpool [supports diesel](https://docs.rs/deadpool-diesel/latest/deadpool_diesel/), but rocket_db_pools currently only allows using deadpool with postgres and redis. It would be great if support could be added for diesel, probably with features `deadpool_diesel_sqlite`, `deadpool_diesel_postgres`, and `deadpool_diesel_mysql`.

**Comment by SergioBenitez** [comment]
There is no benefit to using `deadpool-diesel` over `rocket_sync_db_pools`. See https://github.com/bikeshedder/deadpool/issues/112. What benefit do you perceive?

**Comment by SergioBenitez** [comment]
> Now that deadpool can wrap r2d2, is the eventual goal to deprecate rocket_sync_db_pools and only use the ["cleaner, leaner, easier to maintain"](https://github.com/SergioBenitez/Rocket/commit/5b1a04deabc75981fde566c4381b4cba0d3b7cc8) rocket_db_pools, or will rocket_sync_db_pools be sticking around for a while yet?

No, I don't think we'll deprecate `rocket_sync_db_pools` any time soon. I code-reviewed the implementation in `deadpool` and found it to contain several issues (many now resolved, to be fair), and so I am not as confident that it is as correct as `rocket_sync_db_pools`.

> The main reason though was that I want to access the connection pool outside of rocket for some background processing, and I saw that #1187 was fixed for rocket_db_pools but #1884 is still open for rocket_sync_db_pools, so for now I have to create a separate pool to use.

That's fair. Let's resolve #1884 then and close this one out.
