### ISSUE TITLE
JSON is not idiomatic

### ISSUE THREAD

**Issue by steveklabnik** [SergioBenitez/Rocket#22]
This is your project, so feel free to close.

According to [RFC 430](https://github.com/rust-lang/rfcs/blob/master/text/0430-finalizing-naming-conventions.md#fine-points), it should be `Json`, not `JSON`.

🚀

**Comment by SkylerLipthay** [comment]
Same goes for `APIKey` -> `ApiKey` (non-breaking, because it's just documentation-level).

**Comment by SergioBenitez** [comment]
Indeed, this is by design. There are several other names that don't conform, but I prefer to keep upper-case names for acronyms. If enough people disagree, happy to change it.

**Comment by LLBlumire** [comment]
I'll chime in and say Rocket should conform to what of the rust style guide is defined. So, `Json` and `ApiKey`. This is more intuitive for library users as it's what people are (or should be) used to for rust. 

Same goes for code layout, a cargo fmt goes a long way towards readability (except when it doesn't and screw up royally)

**Comment by ereichert** [comment]
I prefer upper-case names but understand why it would bother someone wanting to contribute.

**Comment by ghazkarim** [comment]
I agree with LLBlumire. Stick to the Rust guidelines for the sake of consistency in the Rust ecosystem.

**Comment by mgattozzi** [comment]
Especially since this is just such a slick framework. It really had potential and I think if people want to use it then making it more idiomatic will be beneficial

**Comment by kerberosmansour** [comment]
@SergioBenitez bravo and building this framework in rust, and looking forward to getting Rocket on to  Rust asynchronous I/O libraries once they stabilize.

**Comment by reillysiemens** [comment]
I second @kerberosmansour's kudos and @LLBlumire's recommendation. Consistency goes a long way (especially for new folks).

**Comment by cbruun** [comment]
Quite a few people have expressed support for following the RFC guideline. Is more feedback needed?

**Comment by impowski** [comment]
I agree, `Json` and `ApiKey`.

**Comment by tshepang** [comment]
It will be more hard to change the names as more people use the project. I imagine there are more pressing things, but this doesn't seem like something that'll take much effort.

**Comment by SergioBenitez** [comment]
Okay, let's do this! 🚀 

Slating for 0.4. In all likelihood, we'll make this happen by 0.3.

**Comment by drusellers** [comment]
whoot

**Comment by ZelphirKaltstahl** [comment]
I never understood why anyone would want to lower case an abbreviation or acronym. Makes no sense to me and I always keep them upper case. Well, I am late to the party anyway : )

**Comment by tshepang** [comment]
@ZelphirKaltstahl my reasons, other than following idiom:
- looks better
- more pleasant to type

**Comment by inta** [comment]
@ZelphirKaltstahl it is easier to recognize word boundaries. If you end with something like JSONAPIKey that is definitely harder to read than JsonApiKey.

**Comment by ZelphirKaltstahl** [comment]
@inta Hmm, that's actually the first valid point I see for this. I am not sure this overrules the "correct" spelling of abbreviations or acronyms, but it is a valid point. Now I at least know one good reason why someone would do that.

Looking better? Meh that's subjective.
Pleasant to type? I am already pressing the shift key for the first character, so it does not really matter.

**Comment by steveklabnik** [comment]
It's also easier to convert simply between the two styles this way; that is, you can easily convert

    JsonApi => json_api

but this means

    JSONAPI => j_s_o_n_a_p_i

and

    JSONEncoder => j_s_o_n_encoder

We don't use reflection a ton in Rust, but this is why Ruby uses this scheme.

**Comment by inta** [comment]
@ZelphirKaltstahl camel case is not about correct spelling at all, you start every word with a capital letter, even those you would usually write all lowercase.

@steveklabnik I have not thought about conversion, that's really the best reason for me.

**Comment by JeremySorensen** [comment]
This was the Rust version of a flame war. That's why this community is so great!
@SergioBenitez Thanks for taking the feedback so graciously. Rocket is in good hands.

**Comment by SergioBenitez** [comment]
This is shipping in 0.3!
