### ISSUE TITLE
Suggestion: replace "session_key" with "secret_key"

### ISSUE THREAD

**Issue by bluetech** [SergioBenitez/Rocket#220]
Rocket includes a `session_key` configuration, which contains some random key that is used specifically for `Session`. And I saw a recent commit 16cb7297abeef which mentions a breaking change to this setting.

Over time, I expect Rocket will require a secret key for many other things besides just sessions. For example, Django has a single [`SECRET_KEY` setting](https://docs.djangoproject.com/en/1.10/ref/settings/#std:setting-SECRET_KEY), which is used for various purposes, here is a list: http://stackoverflow.com/a/15383766

My suggestion is that for future-proofing, Rocket use a single `secret_key` config and derive all other keys from just this one config. A user should generate this key once for each deployment and that's it.

**Comment by SergioBenitez** [comment]
Sure.
