### ISSUE TITLE
Switch default port to something that is not officially blocked by other apps/services

### ISSUE THREAD

**Issue by KillerCodeMonkey** [SergioBenitez/Rocket#2201]
**Existing Functionality**

Default port is 8000

**Suggested Changes**

Maybe 1122 :D

**Alternatives Considered**

Switch it to something that is not officially blocked on some/many devices.

**Additional Context**

On many intel machines the port is blocked by "iRDMI (Intel Remote [Desktop Management Interface](https://de.wikipedia.org/wiki/Desktop_Management_Interface))"

Use something that is not officially blocked: https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers | https://de.wikipedia.org/wiki/Liste_der_standardisierten_Ports
Sadly the lists are different in different languages :(.

But i can confirm on some customers corsair intel machines port 8000 is blocked per default by iRMDI.

Thanks for your effort and the wonderful project :)

**Comment by SergioBenitez** [comment]
I appreciate the concern raised here, but I feel that any such "solution" will be subject to the same problems. That is, if we switch the default port to `X`, what's to stop someone else from using `X` as "their" port?

Rocket makes it quite easy to change the port it's listening on via `ROCKET_PORT` or the `port` configuration parameter. I think that's about the best we can do. Not to mention that the last time we changed a default port, we broke lots of applications and external configuration that depended on that port - it's a hard change to make visible. For all of these reasons, I'm declining this request.

**Comment by KillerCodeMonkey** [comment]
Thats okay :). But it might be a little bit of a bad first impression when a windows user with intel cpu wants to checkout the wonderful rocket project and wants to start a minimal example and it is not working.

Maybe there could be something in dev mode like "vite" does: It checks if the port is already used and is increasing the port. And this could be just done 3 times and then it fails.

I do not have a real problem with changing the default port. I build a tauri app and you can change the port on the fly inside of the app, but would be some nice addition just to start developing with rocket when you newbie :).

Anyway: Thanks for the fast response.
