### ISSUE TITLE
Cookies are not removed when response is a redirect

### ISSUE THREAD

**Issue by mawis** [SergioBenitez/Rocket#2204]
**Description**

I tried to create a HTTP resource, the removes a session cookie and redirects the user to a login page. I noticed, that the session cookie was not removed. Then I searched for something similar in the [cookies example of Rocket](https://github.com/SergioBenitez/Rocket/tree/v0.5-rc/examples/cookies) and found the function `logout(jar: &CookieJar<'_>)` in `examples/cookies/src/session.rs`.

When I get the code correctly, a POST request to `http://localhost:8000/session/logout` should remove the `user_id` cookie and redirect the caller to `/session/login`. It seems to me, that this is also not working in the example.

**To Reproduce**

- execute `cargo run` in the `examples/cookies` folder
- execute `curl -X POST -v http://localhost:8000/session/logout` in a different terminal window

**Expected Behavior**

I would expect a `set-cookie` header in the response, that deletes the private `user_id` cookie. Instead only the `_flash` cookie is set in the response:

```
$ curl -X POST -v http://localhost:8000/session/logout   
* Uses proxy env variable no_proxy == '127.0.0.1,::1,localhost,fritz.box,192.168.178.21'
*   Trying 127.0.0.1:8000...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST /session/logout HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 303 See Other
< location: /session/login
< set-cookie: _flash=7%3AsuccessSuccessfully%20logged%20out.; SameSite=Strict; Path=/; Max-Age=300
< server: Rocket
< x-frame-options: SAMEORIGIN
< permissions-policy: interest-cohort=()
< x-content-type-options: nosniff
< content-length: 0
< date: Wed, 25 May 2022 07:35:46 GMT
< 
* Connection #0 to host localhost left intact
```

**Environment:**

 - OS Distribution and Kernel: NixOS 21.11, Linux 5.10.109
 - Rocket Version: branch v0.5-rc from repository (commit 6778089c129ee15dfd524413f067c9c572226159)

**Comment by SergioBenitez** [comment]
If there's no cookie to begin with, there's no cookie to remove. The request being sent by curl doesn't include the cookie, so there's nothing to remove. In other words, there's nothing to log out. Try the example in web browser and confirm it works. Also see the unit tests in the example which check this behavior.

**Comment by mawis** [comment]
I wasn't aware the the removal is only sent when the cookie has been present at the first place. I now found this also documented on `https://docs.rs/cookie/0.16.0/cookie/struct.CookieJar.html#deltas`.

Problem in my original case was that my cookie was scoped to a path and I tried to remove it without specifying the same path again.

Thanks for clarifying. I can confirm now, that there was no bug in Rocket.

**Comment by SergioBenitez** [comment]
> I wasn't aware the the removal is only sent when the cookie has been present at the first place. I now found this also documented on https://docs.rs/cookie/0.16.0/cookie/struct.CookieJar.html#deltas.

Note that this is an HTTP thing, not a peculiarity of Rocket or `cookie`. HTTP is stateless. Thus a client needs to send all cookies all the time. If the client doesn't send a cookie, then that implies the client doesn't have the cookie (or it's lying in which case this is all irrelevant), thus there's no cookie to delete.
