### ISSUE TITLE
Provide a means for detecting whether a template path exists.

### ISSUE THREAD

**Issue by naturalethic** [SergioBenitez/Rocket#2214]
**Existing Functionality**

I can set up a custom responder to handle both static files and templates from a dynamic path.  The purpose being to be able to serve static files from `/`, and if missing, look for a template.  If the template is missing, I get a status 500 result, with no way to determine if that result is due to a missing template.  In that case I'd like to return a 404 instead of a 500.  I'd still like to see the 500 if it was any other error.

**Suggested Changes**

Rocket could provide a means to help detect if a template file is missing.  Possibilities:

1. Have templates return a 404 if the template file is missing.
2. Have templates annotate the returned error somehow so this result is known.
3. Provide public access to ContextManager, so that my Responder can ask the template context if a template exists.

**Alternatives Considered**

Currently the only way to deal with this I have found is to manually search the templates directory to determine the templates existence.  If the templates are compiled in on release, I'll have to also cache this information in the build.

**Comment by SergioBenitez** [comment]
I believe this is [`Metadata`](https://api.rocket.rs/v0.5-rc/rocket_dyn_templates/struct.Metadata.html#usage).

**Comment by naturalethic** [comment]
Yep!  Thanks.
