### ISSUE TITLE
Macro Import not working - Tera Templates

### ISSUE THREAD

**Issue by StefanZimmermann98** [SergioBenitez/Rocket#2215]
Failed to parse "DIRECTORY/templates/index.html.tera"
   >>  --> 3:1
  |
3 | {% import "navbar" as navbar %}␊
  | ^---
  |
  = unexpected tag; expected end of input or some content
   >> Template initialization failed. Aborting launch.
Error: Rocket failed to launch due to failing fairings:
   >> Templating
thread 'main' panicked at 'aborting due to fairing failure(s)', USER/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.5.0-rc.2/src/error.rs:229:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**To Reproduce**

{% import "navbar" as navbar %}
{{ navbar::navbar_begin(fullname=fullname, jwt=jwt) }}

**Expected Behavior**

Macro ist imported and ready for usage

**Environment:**

 - OS Distribution and Kernel: Ubuntu 22.04
 - Rocket Version: 0.5.0-rc.2

**Comment by SergioBenitez** [comment]
According to the error there's a syntax issue with your template. What do the first two lines look like? What's the whole template?

**Comment by SergioBenitez** [comment]
Closing since this is unlikely to be an issue related to Rocket.
