### ISSUE TITLE
Set `address` to `0.0.0.0` for release builds by default

### ISSUE THREAD

**Issue by seeplusplus** [SergioBenitez/Rocket#2222]
**Existing Functionality**

Setting this as the default just kind of "makes sense." It solves a frequent issue I face (and maybe others as well), which is that the default `127.0.0.1` binding for release means that containers can't reach Rocket apps, unless the address is explicitly set (which I often forget or don't think about). This is total personal preference and I'd like to hear if there's a reason *not* to do this. I speculate that more often than not developers would want release builds to bind to all ports, but I could be wrong about this.

I'm open to taking this on and opening a PR, but wanted to open an issue to see if this would be a welcome change first.

**Suggested Changes**

Change the default address binding for release configs to `0.0.0.0`.

**Comment by kotx** [comment]
Might also want to listen on `[::]` for IPv6?

**Comment by SergioBenitez** [comment]
This is #2091. We long ago decided that the address/port would remain the same between profiles, though I can't find the issue/PR/commit that made this change. The main arguments being 1) this is safer, so you don't accidentally expose your application to the world, 2) cargo run --release will always run without `sudo` by default (some distros/settings block binding to `0.0.0.0`), and 3) many proxies run on `0.0.0.0`, with Rocket running as an application server, so the conflict is avoided with configuration.

I think we'll stick to that decision for now.
