### ISSUE TITLE
Guide contains nonexistent links

### ISSUE THREAD

**Issue by Glitchy-Tozier** [SergioBenitez/Rocket#2223]
**Description**

When searching for keywords in the Guide on rocket.rs, the results sometimes contain links that return a `404`-error.

**To Reproduce**

1. Go here: https://rocket.rs/v0.5-rc/guide/
2. Use search-bar to search for "redirect"
3. Click on the second link ("More Typed URIs")
4. `404`

**Expected Behavior**

No `404`, only links that exist should show up in search.

**Environment:**

Linux, Firefox

**Additional Context**

![image](https://user-images.githubusercontent.com/59611881/172311519-12e6008a-ec21-4433-bc3b-fca5f9d8a3fd.png)
---
![image](https://user-images.githubusercontent.com/59611881/172311601-482a73dd-ca04-4990-89e4-07c5c908e269.png)
---

**Comment by SergioBenitez** [comment]
Not sure why https://github.com/SergioBenitez/Rocket/commit/dfea521eb67723b777713fc9c1994ff31dc79c4b didn't autoclose this, but this is resolved!
