### ISSUE TITLE
Async Behavior Not Working

### ISSUE THREAD

**Issue by skandabhairava** [SergioBenitez/Rocket#2228]
**Description**

Rocket is termed as an async web framework. 0.5.x is supposed to completely make everything asnyc on the back. Although many examples do tell how to run an async server, when I await a specific call in a route, it blocks the whole thread on which the server is running on.

**To Reproduce**

main.rs
```rs
#[macro_use] extern crate rocket;
use chrono::Local;
use tokio::time::sleep;
use core::time::Duration;

#[get("/")]
async fn hello() -> String {
    let time_1 = Local::now(); 
    sleep(Duration::from_secs(5)).await;
    let time_2 = Local::now();
    format!("Hallo! \n{}\n\n{}", time_1, time_2)
}

#[launch]
async fn rocket() -> _ {
    rocket::build().mount("/", routes![hello])
}

// OR this launch as well, both dont work

/* #[launch]
fn rocket() -> _ {
    rocket::build().mount("/", routes![hello])
} */
````

Open up 2 webbrowsers/tabs, and make a request to localhost:8000/ , at around the same time

**Result**

![image](https://user-images.githubusercontent.com/58636952/173197932-e07439e4-9dd5-4b1c-9820-704c0d0f22d0.png)
Page1

![image](https://user-images.githubusercontent.com/58636952/173197935-d75c2245-1900-401c-bbe4-98ef86104578.png)
Page2

As you can see here, the first page loads at ~9sec, and the 2nd page starts loading ~9sec, even if u sent the request to the server around the same time!

**Expected Behavior**

When I send 2 requests from 2 clients at the same time, the server should serve the output to both of those clients at around the same time (in this program, the server should serve both the clients around 5secs after both of those sends a request)

**Environment:**

 - OS Distribution and Kernel: x86_64-pc-windows-msvc
 - Rocket Version: 0.5.0-rc.2

**Additional Context**

N/A

**Comment by SergioBenitez** [comment]
This is your browser serializing requests. Try using a command line client, or two different browsers instead of two tabs in one.
