### ISSUE TITLE
Print timestamps in the default logger `RocketLogger`

### ISSUE THREAD

**Issue by fuyufjh** [SergioBenitez/Rocket#2229]
**Is your feature request motivated by a concrete problem? Please describe.**

Timestamps are very helpful when locating a bug in logs. For a typical scenario, suppose that another service reports an error when calling an API from this Rocket server, as the developer, I would first search for the logs around the timestamp when the error happened.

Most logging frameworks usually print a timestamp before the specific log info. Could Rocket also support this simple feature?

**Why this feature can't or shouldn't live outside of Rocket**

In Rocket, logging is done by [`RocketLogger`](https://github.com/SergioBenitez/Rocket/blob/2fc4b156ebcc3e7220159dd638286e8d890cccba/core/lib/src/log.rs#L64) which is hard to extend. 

**Ideal Solution**

Add an option to enable/disable printing timestamps in `RocketLogger`. e.g.

```
2022-06-12T04:37:28Z GET /api/user:
2022-06-12T04:37:28Z    >> Matched: (user) GET /api/user
2022-06-12T04:37:28Z    >> Outcome: Success
2022-06-12T04:37:28Z    >> Response succeeded.
```

**Alternatives Considered**

It's possible to use an external logger instead of `RocketLogger`, but in this way the formatting in 
`RocketLogger` also gets lost.

<img width="740" alt="image" src="https://user-images.githubusercontent.com/10192522/173217490-b9fbe34d-05bb-45ed-af0c-04af35b66b7f.png">

**Additional Context**

N/A

**Comment by fuyufjh** [comment]
@SergioBenitez How do you think? If you think it's acceptable, I would be happy to accomplish that. 😄

**Comment by SergioBenitez** [comment]
I totally see the value in this, but I don't think we should work on `RocketLogger` or any `log` based logging, nor extend it with specific features. Instead, I think we should migrate to `tracing`, which would make it easier for anyone to extend logging. This is #21. Closing in favor of that.
