### ISSUE TITLE
A list of headers is represented as a single comma separated value

### ISSUE THREAD

**Issue by scottschroeder** [SergioBenitez/Rocket#223]
### Description of Issue
I would expect that when multiple headers are passed in with the same key, the values are interpreted as a list.

So for a query like:
``` bash
curl -H "friend: adam" -H "friend: bob" localhost:8000
```
I would expect a list with two entries
``` bash
{"friends": ["adam", "bob"]}
```
But instead, I get a list with one entry, separated by a `, `
``` bash
{"friends": ["adam, bob"]}
```

This can get even worse if our original header has a `, ` inside one of the values
``` bash
curl -H "friend: adam" -H "friend: bob, carol" localhost:8000
{"friends": ["adam, bob, carol"]}
```

This is on the latest version of Rocket, both v0.2.2 and master branch as of this writing.

### Root Cause

When Rocket grabs the headers from Hyper, we use the `value_string()`
```
for hyp in h_headers.iter() {
    let header = Header::new(hyp.name().to_string(), hyp.value_string());
    request.add_header(header);
}
```
See [request/request.rs](https://github.com/SergioBenitez/Rocket/blob/16cb7297abeef3af03666247e2fbbf6d9aae683e/lib/src/request/request.rs#L481-L485) for exact listing.

According to the [Hyper Documentation](https://hyper.rs/hyper/v0.10.5/hyper/header/struct.HeaderView.html#method.value_string): 
> `fn value_string(&self) -> String`
> Get just the header value as a String.
> This will join multiple values of this header with a `,`.
> Warning: This may not be the format that should be used to send a Request or Response.

It seems like this is the incorrect interface to use for grabbing header values from Hyper.

**Comment by SergioBenitez** [comment]
Fixed in https://github.com/SergioBenitez/Rocket/commit/47fe659ebe64e4079105798aa8850dc952c1bdd9.
