### ISSUE TITLE
Hyper/Rocket URI validity discord: 

### ISSUE THREAD

**Issue by FoxLisk** [SergioBenitez/Rocket#2234]
**Description**

Found this in my log file:

```
 Warning: Hyper/Rocket URI validity discord: "/${(%23a=@org.apache.commons.io.IOUtils@toString(@java.lang.Runtime@getRuntime().exec(\"whoami\").getInputStream(),\"utf-8\")).(@com.opensymphony.webwork.ServletActionContext@getResponse().setHeader(\"X-Response\",%23a))}/"^ 
[1;49;39m>> [0m  [33mPlease report this warning to Rocket's GitHub issue tracker. 
```

and
```
Hyper/Rocket URI validity discord: "/.\\\\./.\\\\./.\\\\./.\\\\./.\\\\./.\\\\./windows/win.ini"
```

**To Reproduce**

I don't know, make a request that looks like that?

**Expected Behavior**

The log file literally asked me to file this bug

**Environment:**

 - OS Distribution and Kernel: 
CentOS Linux release 8.5.2111

 - Rocket Version: "0.5.0-rc.2"

**Comment by nox** [comment]
For webcompat, Hyper allows `{}` in paths, and also `"` since https://github.com/seanmonstar/httparse/pull/89

**Comment by SergioBenitez** [comment]
It would be nice to be able to configure Rocket to accept technically invalid URIs. There are such few cases, however, that it may not be worthwhile. Still, thank you for reporting this. At least we have one more data point.
