### ISSUE TITLE
Support sqlx v0.6 in "rocket_db_pools"

### ISSUE THREAD

**Issue by yzernik** [SergioBenitez/Rocket#2249]
**Existing Functionality**

`rocket_db_pools` works with sqlx version 0.5. There is a new version of `sqlx`, [v0.6.0](https://github.com/launchbadge/sqlx/releases/tag/v0.6.0). `rocket_db_pools` does not work with the new version of `sqlx`.

**Suggested Changes**

Update `rocket_db_pools` and the example `database` app to use sqlx v0.6.

**Alternatives Considered**

**Additional Context**

v0.6 of `sqlx` has some important bug fixes, so it would be nice to be able to use it.

**Comment by yzernik** [comment]
I just noticed that there is an open PR for this: https://github.com/SergioBenitez/Rocket/pull/2242

**Comment by Coca162** [comment]
When will a new crate for `rocket_db_pools` be published so this can be used?
