### ISSUE TITLE
There seems to be a mismatch in rocket_db_pools for Redis

### ISSUE THREAD

**Issue by patchthecode** [SergioBenitez/Rocket#2255]
The [website](https://api.rocket.rs/v0.5-rc/rocket_db_pools/#quickstart) has 4 steps in the quick start guide, but it is done for SQL. My requirement was REDIS, so i modified everything for REDIS. All works, and the datbase _does_ connect. But the problem is step `#4` which says

```Use [Connection<Type>](https://api.rocket.rs/v0.5-rc/rocket_db_pools/struct.Connection.html) as a request guard to retrieve an active database connection, which dereferences to the native type in the [Connection deref](https://api.rocket.rs/v0.5-rc/rocket_db_pools/#supported-drivers) column.

use rocket_db_pools::Connection;
use rocket_db_pools::sqlx::Row;

#[get("/<id>")]
async fn read(mut db: Connection<Logs>, id: i64) -> Option<Log> {
    sqlx::query("SELECT content FROM logs WHERE id = ?").bind(id)
        .fetch_one(&mut *db).await
        .and_then(|r| Ok(Log(r.try_get(0)?)))
        .ok()
}
```

When converted to my REDIS requirement it looks like the following ->

```rs
pub use rocket_db_pools::deadpool_redis;
pub use rocket_db_pools::Database;

#[derive(Deserialize)]
#[derive(Debug)]
pub struct AddPostRequest {
    #[serde(rename = "postId")] post_id: String,
    #[serde(rename = "hashTags")] hashes: Vec<String>,
    data: HashMap<String, String>,
    r#type: String
} 

#[post("/post", data="<add_post_request>")]
pub async fn route(mut db: Connection<RedisCache>, add_post_request: Json<AddPostRequest>) {
    /* BUG HERE --->>*/  redis::cmd("ZINCRBY").arg(&modifiedHashes).query_async(&mut db).await;  
}
```

BUG/Mismatch: That REDIS command will not work because `&mut db` _requires_ that `db` conforms to `ConnectionLike`
Error Message:
```
the trait bound `rocket_db_pools::Connection<RedisCache>: rocket_db_pools::deadpool_redis::redis::aio::ConnectionLike` is not satisfied
the trait `rocket_db_pools::deadpool_redis::redis::aio::ConnectionLike` is not implemented for `rocket_db_pools::Connection<RedisCache>`
```

it looks like `use rocket_db_pools::Connection` does not conform to `ConnectionLike`.
Oddly enough, [deadPools's implementation of connection](https://github.com/bikeshedder/deadpool/blob/deadpool-redis-v0.9/redis/src/lib.rs#L192) _does_ implement it, but I am unable to use that connection because it doesnt allow for a generic database type.

Can you guide in how I can send a redis command using the connection pools?

**Comment by patchthecode** [comment]
omg...
😓

**Comment by cmac4603** [comment]
This solved everything for me, you're not alone 😆
