### ISSUE TITLE
Question: Can I bundle everything(html,js) in one executable file with rocket?

### ISSUE THREAD

**Issue by adals** [SergioBenitez/Rocket#227]
hello

i want to run server as executable file at client machine with included everything(js,html,others)

can i do it with rocket?

thanks

**Comment by felipesere** [comment]
I'd also be interested in embedding those files to get the simplest possible deplorable unit.

**Comment by felipesere** [comment]
This https://github.com/pyros2097/rust-embed/blob/master/README.md might already be solving what you need.

**Comment by adwhit** [comment]
You might like to look as [include_str!](https://doc.rust-lang.org/std/macro.include_str.html)

**Comment by adals** [comment]
thanks i will try it

**Comment by adals** [comment]
i have done but i have small problem when used like this
#[get("/")]
fn index() ->  String
i got text string 
and when i used 
#[get("/")]
fn index() ->  Template
it must be file outside and i dont want that 

so how to make it html not string output
thanks

**Comment by SergioBenitez** [comment]
@adals You'll need to set the Content-Type of the item manually, since Rocket doesn't know the filename. You can use the types in the [content](https://api.rocket.rs/rocket/response/content/index.html) module to do so.

**Comment by adals** [comment]
how can use it with this function which does function return String? template?
#[get("/")]
fn index() -> String

**Comment by SergioBenitez** [comment]
@adals You need to _not_ return `String`. It would look like this:

```rust
use rocket::response::content;

#[get("/")
fn index() -> content::HTML<String> {
    content::HTML(your_string)
}
```

**Comment by adals** [comment]
thanks it works
