### ISSUE TITLE
Responder does not use Future, contrary to the documentation

### ISSUE THREAD

**Issue by emembrives** [SergioBenitez/Rocket#2286]
**Description**

In [`core/lib/src/response/responder.rs`, line 109](https://github.com/SergioBenitez/Rocket/blob/f64029f079882c1fe8e47d65d4a57ec260729bea/core/lib/src/response/responder.rs#L109), it is written that 
```
/// A `Responder` returns a `Future` whose output type is a `Result<Response,
/// Status>`.
```
which would be a very useful feature.

However, the code of the `Responder` trait is not async nor uses a Future, contrary to what the documentation says:
```
    fn respond_to(self, request: &'r Request<'_>) -> response::Result<'o>;
```

It would be great to have this feature available.

**Comment by edgarogh** [comment]
From my understanding, the doc comment is wrong, responders aren't meant to be async. It's the `Handler`'s job to do any async calculation prior to returning the `Responder`. In can't think of a situation where `respond_to` being sync would make anything harder. However, you could still [respond with (async) streams](https://docs.rs/rocket/0.5.0-rc.2/rocket/response/stream/index.html) depending on what you're trying to do exactly. This can be seen as an "async response" in a way...
