### ISSUE TITLE
Allow overriding/provide default `Content-Type` for `MultipartParser`

### ISSUE THREAD

**Issue by BlackDex** [SergioBenitez/Rocket#2299]
**Is your feature request motivated by a concrete problem? Please describe.**
Yes:
The Bitwarden clients are able to upload files/attachments to the server.
With Vaultwarden we use the `FromForm` derive and `TempFile` to receive these files.
However, it looks like some Bitwarden clients do not send a `Content-Type` header within the multipart boundary (The mobile clients).
This triggers Rocket to indicate it as a `value` and thus converts it to a string, while the data is actually binary.
As indicated here: https://github.com/SergioBenitez/Rocket/blob/f64029f079882c1fe8e47d65d4a57ec260729bea/core/lib/src/form/parser.rs#L163-L166

<br>

**A clear and concise description of what the problem is.**

I want to override or set a default `Content-Type` for the received Multipart data instead of Rocket deciding it's either `data` or `value`.

If i want to somehow override this my self, i would need to try and impl `FromData` my self, and then also parse the multipart data my self with multer-rs, feed that to TempFile somehow and try to return the same response as a `FromForm` would do to at least try to keep everything safe and similar.

<br>

**Why this feature can't or shouldn't live outside of Rocket**

Trying to receive and parse the multipart data outside of Rocket isn't what the `FromData` Guard is designed for i think.
Especially when Rocket has a lot of nice checks and steps built-in which handles TempFiles, checks the maximum sizes set for `files` and `form-data` which then have to be done again.

<br>

**Ideal Solution**

The ideal solution would be having something to be able to tell `Form` to always use `Data::from` for a `TempFile`.
Maybe something like this?
```rust
#[derive(FromForm)]
struct UploadData<'f> {
    key: Option<String>,
    data: FormData<TempFile<'f>>,
}
```

<br>

**Alternatives Considered**

I have considered to try and use `impl<'r> FromData<'r> for UploadData<'r> {`, but while trying to implement that, i noticed i needed to copy a lot of code from Rockets library, and reinvent everything, just to bypass a check which forces the data to be converted to a string.
This felt a bit counterproductive.

**Comment by BlackDex** [comment]
This isn't needed anymore. At least not for our use case.
The client didn't sent the correct headers, which caused issues. This has been fixed now. Not sure if other clients could still have issues when they do not send the correct content-type though.

**Comment by xvolks** [comment]
Hello, I have a use case that produce similar problem. This sample python code will fail if `will_work` is false.
Here I can change the client, but it's not always the case.
In python, it seems the default to omit the `Content-Type`.

```python
                start = time.time_ns()
                if will_work:
                    files = [('file', (image.name, open(image, 'rb'), 'image/jpeg'))]
                else:
                    files = [('file', (image.name, open(image, 'rb')))]
                stem = image.stem
                values = {'uuid': f'{stem}', 'find_rotation': '90'}
                print(f"Reading {stem}")
                ret = self.session.post(f"{self._base_url}/hocr", files=files, data=values)
                end = time.time_ns()
```

Is there a workaround on the server side (for now I get 422 or an empty image, in all my tests).
Thanks for any help.
