### ISSUE TITLE
There is no link to this repository on rocket.rs

### ISSUE THREAD

**Issue by klingtnet** [SergioBenitez/Rocket#23]
As the title says, please add a link to this repository to [rocket.rs](https://rocket.rs).

**Comment by ereichert** [comment]
@klingtnet It's the contribute link in the upper right-hand corner.

**Comment by klingtnet** [comment]
Oh sorry, I missed that. Nonetheless, it seems that I'm [not the only one missing that link](https://twitter.com/klingtnet/status/812341134206832640).

**Comment by SergioBenitez** [comment]
Multiple folks seem to have missed it, so I'll find a way to make it more prominent.

**Comment by SShrike** [comment]
Maybe a GitHub ribbon as well?

This would like quite nice I think: https://github.com/tholman/github-corners.

**Comment by theduke** [comment]
Just rename "Contribute" to "Code" would be my suggestion.

**Comment by SergioBenitez** [comment]
Alrighty! The site's been updated for 0.2! It now includes the GitHub corner suggested by @SShrike as well as a link rename to "Code" as suggested by @theduke. Closing this issue as a result. :)

Thanks all!

**Comment by theduke** [comment]
Cheers, and keep up the good work.
