### ISSUE TITLE
Question: get State in FromRequest

### ISSUE THREAD

**Issue by Rukenshia** [SergioBenitez/Rocket#230]
Rocket version: `0.2.2`

I have a managed `SessionManager`(which is connected to Redis) and basically want to do what the `session` example is doing. But for that, I need the `SessionManager` in my FromRequest implementation.

I've tried looking into the documentation but couldn't find anything useful (I might just be blind, though). Is there any way of retrieving a managed State in `FromRequest`? Otherwise I'll have to do this in all of my routes I guess.

I really like Rocket so far, keep up the awesome work!

**Comment by SergioBenitez** [comment]
This is answered in the guide in the [Retrieve State subsection of the State section](https://rocket.rs/guide/state/#retrieving-state).

**Comment by Rukenshia** [comment]
Seems like I actually was blind. Thanks!
