### ISSUE TITLE
OutputCaching

### ISSUE THREAD

**Issue by bigpilot** [SergioBenitez/Rocket#2305]
The thing I'm missing is an OutputCache like with ASP.NET. 

Ideally, you don't want to generate a new page but to fetch it from the cache. This would have an **enormous** impact on performance.

**Comment by SergioBenitez** [comment]
This seems like something that can be implemented entirely outside of Rocket. I'm going to assume that's the case and close this issue out. If it's not, please feel free to comment and we'll revisit.
