### ISSUE TITLE
Namespace #[error] behind #[rocket(error)]

### ISSUE THREAD

**Issue by mehcode** [SergioBenitez/Rocket#231]
Both `log` and `slog` use `error!` for error logging. This conflicts with `#[error]` as both attribute macros and functional macros share the same scope.

I propose that we make it policy to namespace attribute macros outside of the [standard HTTP methods](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods) and `route`.

```rust
#[rocket(error(404))]
fn not_found(req: &Request) -> String { }
```

**Comment by SergioBenitez** [comment]
Macro namespace conflicts will be resolved with macros 2.0, part of #19. As a result, namespacing macros in this way will be unnecessary. Furthermore, the aesthetics of what you've proposed are subpar. For these reasons, I am declining this request and closing the issue.

That being said, I _have_ considered renaming `error` to `catcher` or `catch` to better declare its intention. This would inadvertently solve the problem.

**Comment by mehcode** [comment]
@SergioBenitez I agree with switching to using `#[catch]`. Rust is adding `catch` as a contextual keyword so it seems to be the de-facto word for this kind of thing.

I was under the impression that macros (both attribute and functional) would move to using normal `use` instead of "magic" scope. This is still a conflict (though not as serious) as I'd imagine you'd start having `use rocket::prelude::*` recommended same as slog would recommend `use slog::prelude::*`.

**Comment by SergioBenitez** [comment]
See https://github.com/nrc/rfcs/blob/macro-naming/text/0000-macro-naming.md for the details.

**Comment by Nemikolh** [comment]
Hi, is there a workaround or a way to declare an error handler outside of using the `error` macro?
