### ISSUE TITLE
Client routing 

### ISSUE THREAD

**Issue by Ludea** [SergioBenitez/Rocket#2313]
**Description**
I use reactjs as frontend.
I would like to use react router dom v6 as router. 
Rocket serves only html file (like https://github.com/SergioBenitez/Rocket/blob/master/examples/static-files/src/main.rs). 
I create routes with react router. I try to reach some routes, but there are unreachable. 
The only route available is `/`

**To Reproduce**
clone https://github.com/Ludea/lucle
```
cd web
yarn 
yarn build
cd .. 
cargo run
```
All routes are listed into routes.tsx

**Expected Behavior**
All routes available, handle by react 

**Environment:**

 - OS Distribution and Kernel: Ubuntu 20.04
 - Rocket Version: 0.5-rc

**Additional Context**

**Comment by robertwayne** [comment]
You need your catch-all route to explicitly respond with your `index.html`, which is where your client-side routing will take over. From briefly looking at your code, you aren't actually matching against that - just your static folder.

You can [see an example of how I do it here](https://github.com/robertwayne/template-rocket-svelte-spa/blob/main/server/src/main.rs). It uses Svelte, but I presume React has a similar overall structure.

**Comment by Ludea** [comment]
With your example, works as expected, thanks a lot
