### ISSUE TITLE
option to add second Logger (as example sentry-log) to RocketLogger

### ISSUE THREAD

**Issue by LuckyTurtleDev** [SergioBenitez/Rocket#2324]
**Is your feature request motivated by a concrete problem?**

I would like to use [sentry-log](https://github.com/getsentry/sentry-rust/tree/master/sentry-log) to send errors from the log crate to [sentry](https://github.com/getsentry/sentry), without losing the RocketLog to stdout.

**Why this feature can't or shouldn't live outside of Rocket**

It is not possible to access the [RocketLogger](https://github.com/SergioBenitez/Rocket/blob/7bbe0457a5ecc9d4b3ca0a2bc6120ffbe1e7febd/core/lib/src/log.rs#L64)  outside from Rocket.

**Ideal Solution**

Adding an option to add a generic to with does implanted [log::Log](https://docs.rs/log/latest/log/trait.Log.html) as second logger. The RocketLogger can simple pass log events to this generic. This would also allow to use other loggers as sentry.

**Alternatives Considered**

Disabling the RocketLogger and use an alternative logger for logging to stdout.
(But I like the RocketLogger and would like to keep using it)

**Additional Context**

I would like to implanted this, if this feature is wanted.

**Comment by edgarogh** [comment]
See #2323

**Comment by SergioBenitez** [comment]
We just need to completely rework logging. Fixing #21 would finally enable this. Closing in favor of that issue, keeping this in mind.
