### ISSUE TITLE
`rocket_db_pools` : Upgrade `sqlx` to `0.6`

### ISSUE THREAD

**Issue by griffi-gh** [SergioBenitez/Rocket#2335]
**Existing Functionality**

`sqlx` 0.5 is a bit outdated and 0.6 added some useful features, for example `#[sqlx(flatten)]`

**Suggested Changes**

 Upgrade `sqlx` in `rocket_db_pools` to `0.6`

**Alternatives Considered**

\-

**Additional Context**

\-

**Comment by edgarogh** [comment]
Duplicate of #2249 (& PR #2242)
