### ISSUE TITLE
RUSTSEC-2020-0016 net2 is oudated; transitive dep of notify<-mio<-rocket_dyn_templates

### ISSUE THREAD

**Issue by jblachly** [SergioBenitez/Rocket#2337]
See #1440 

Existing objections in that thread have been addressed (namely, notify 5.0.0 was released as stable 11 days ago, and has been updated to use mio > 0.6, thus net2 is no longer a transitive dependency)

https://crates.io/crates/notify/5.0.0/dependencies
https://crates.io/crates/mio/0.8.4/dependencies

**SUGGESTED FIX**
Update rocket_dyn_templates to use a notify version in the 5.0 series.

**Comment by SergioBenitez** [comment]
We should absolutely do this! Happy to accept a PR updating `notify`.
