### ISSUE TITLE
dynamic query paramaters with ? delimiter

### ISSUE THREAD

**Issue by endermaz41** [SergioBenitez/Rocket#2338]
I've tried everything but nothing is catching If I try to use a url with a  `?`

If someone can provide a small  working example. that would be great.
I tried catching the 404, but still nothing matches

Here is my stackover [question](https://stackoverflow.com/questions/73684459/matching-a-route-with-a-dynamic-query-parameter-using-rocket-rs?noredirect=1#comment130118431_73684459)

**Comment by SergioBenitez** [comment]
The code in your StackOverflow question _looks_ right, but it doesn't include a main function, so I don't know if you're actually `.await`ing the future that includes the server. Here's a complete example:

```rust
#[macro_use] extern crate rocket;

#[get("/transactions?<id>")]
fn transactions(id: &str) {
    dbg!(id);
}

#[launch]
fn rocket() -> _ {
    rocket::build().mount("/", routes![transactions])
}
```

There are more examples here:
  * https://rocket.rs/v0.5-rc/guide/requests/#query-strings
  * https://github.com/SergioBenitez/Rocket/tree/master/examples/hello
  * https://github.com/SergioBenitez/Rocket/tree/master/examples/

**Comment by SergioBenitez** [comment]
I'm closing this out as the issue template wasn't followed. Nothing is reproducible, and the given example works.

**Comment by endermaz41** [comment]
@SergioBenitez  Ty, I just the code.
And  ran Hello, I entered "http://127.0.0.1:8000/?lang=ру" into terminal
And still get `zsh: no matches found: http://127.0.0.1:8000/?lang=ру`

**Comment by endermaz41** [comment]
same error

**Comment by SergioBenitez** [comment]
Just put some quotes around the URL. This is just your shell and isn't getting to Rocket.

**Comment by endermaz41** [comment]
OMG thank you Sir...Ah ok that error message makes more sense now
