### ISSUE TITLE
Trying to use state for an endpoint in another file

### ISSUE THREAD

**Issue by realTristan** [SergioBenitez/Rocket#2349]
![image](https://user-images.githubusercontent.com/75189508/192149951-5d202eb2-b6a3-451f-af18-896ffc1815a3.png)

as you can see in the screenshot above is says I need to use .manage() but in my code I already have.

my code:
```
// Launch Endpoints
#[launch]
async fn rocket() -> _ {
    // Establish a new database
    let db: Database = Database::init().await;
    // Insert a test user for debugging purposes
    let _ = db.insert_test_user().await;

    // Build the API Endpoints
    rocket::build()
        .manage(db)
        .mount("/user/update", routes![users_endpoint::update_user_data])
        .mount("/user/get", routes![users_endpoint::get_user_data])
}
```

**Comment by edgarogh** [comment]
Are you sure you're using the exact same `Database` type in both files? You can print `TypeId::of::<Database>()` in both files and check if they match, just to be sure.

If you could provide the entire code, or at least a minimal, reproducible example, it would be easier to help (and could even make you find the error).

**Comment by SergioBenitez** [comment]
Looks like this was likely a bug in @realTristan's code which was caught by Rocket.
