### ISSUE TITLE
[Minor] `clippy::let_unit_value` warning on function name with Rocket

### ISSUE THREAD

**Issue by ClementNerma** [SergioBenitez/Rocket#2350]
**Description**

As an image is worth a thousand words:

![image](https://user-images.githubusercontent.com/9782521/192237513-18f0cb4c-b473-43bd-86d7-21d63e29b867.png)

**To Reproduce**

```rust
#[rocket::get("/exit")]
pub fn exit() {
    std::process::exit(0)
}
```

**Expected Behavior**

The lint warning should not appear.

**Environment:**

Using Rocket `0.5.0-rc.2`

**Comment by the10thWiz** [comment]
Avoiding Clippy warnings on generated code is considered best effort. Feel free to find and fix the issue (even just inserting an allow in the generated code).

**Comment by ClementNerma** [comment]
Absolutely, which I why I added `[Minor]` on the title issue :)
I'll try to check where does that come from when I some time.

**Comment by olback** [comment]
Another warning introduced in the latest release:

```rs
#[derive(FromForm)]
struct A {
    a: String
}
```
![image](https://user-images.githubusercontent.com/8039145/192552404-a7197412-f0db-4c9f-a7e1-09098213af8a.png)

**Comment by SergioBenitez** [comment]
Please feel free to submit a PR that modifies the generated code to avoid the lint! As we don't consider this an issue with Rocket itself, I'm closing this out, but we'd gladly accept a PR to resolve this!
