### ISSUE TITLE
Inconsistent behaviour of status::NotFound

### ISSUE THREAD

**Issue by constantingoeldel** [SergioBenitez/Rocket#2351]
**Existing Functionality**

The implementation of `Responder` for various status codes seems inconsistent: While most (`BadRequest`, `Unauthorized`, `Forbidden` and `Conflict`) are defined as `Status<R>(pub **Option<R>**)`, the 404 status `NotFound` is a `Status<R>(pub **R**)`

https://api.rocket.rs/v0.5-rc/rocket/response/status/index.html

**Suggested Changes**

Should use unified interface (Or is there a reason for the difference?)

I'd also be happy to write a PR which implements the missing status codes, if wanted :)

**Comment by the10thWiz** [comment]
This needs to be explored further. There some status codes (such at `NoContent`) for which there is a clear reason why they contain what the do. However, your point about `NotFound` is likely valid. The http spec says that servers 'SHOULD' provide a body to all 4XX status codes, but it's not required. Rocket seems to require a body for 404, but none of the others.

I think it would be desirable to adjust all 4XX response structs to be the same, but I'm not sure whether we should standardize on Option. Requiring the insertion of `Some()` doesn't increase readability, and could break existing code (although 0.5 is in beta, so this is less of an issue). Standardizing on just wrapping a raw Responder could be ideal, although it technically takes away the ability to send a 4XX without a body using these structs. This could be solved in one of two ways: First, implement Responder for `Option`, which responds with no content when None, second, implement responder for `()`, or finally, `NotFound` (and friends) could take `<O: Into<R>, R: Responder>` as type parameters. I the best option might be to remove the `R: Responder` bound on the status structs, but only apply it to the `Responder` impl. This should allow `NotFound<()>` to also implement Responder, even if `()` doesn't implement Responder.

**Comment by the10thWiz** [comment]
After some careful consideration, I believe the best option is to standardize on `Status<R>(pub R)`. From a design point of view, I think it's best for the type signature to indicate what the return type is, and avoid implicitly marking the body as optional. I believe it's possible (if not trivial) to create an empty body if desired, but with this change, it would need to be marked by the return type.

@SergioBenitez can confirm whether this is the correct choice, and a PR would be quite welcome.
