### ISSUE TITLE
Clippy warning `then_some` in `FromForm`

### ISSUE THREAD

**Issue by ralpha** [SergioBenitez/Rocket#2364]
**Description**

Clippy warning on generated code from `#[derive(FromForm)]`.

Example warning:
```
warning: unnecessary closure used with `bool::then`
  --> examples/custom_schema/src/message.rs:17:17
   |
17 |     message_id: u64,
   |                 ^^^ help: use `then_some(..)` instead: `then_some(message_id)`
   |
   = note: `#[warn(clippy::unnecessary_lazy_evaluations)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_lazy_evaluations
```

**To Reproduce**

Create a structure like this:
```rust
#[derive(Serialize, Deserialize, FromForm)]
struct Post {
    post_id: u64,
    title: String,
    summary: Option<String>,
}
```
Full example here: https://github.com/GREsau/okapi/blob/master/examples/json-web-api/src/main.rs#L75

**Expected Behavior**

I do not expect this (or any) Clippy warning from generated code.
Ether solve the issue or add an ignore flag. `#[allow(clippy::unnecessary_lazy_evaluations)]`

**Environment:**

 - OS Distribution and Kernel: Linux (but should be the same anywhere)
 - Rocket Version: 0.5.0-rc.2

**Additional Context**

Issue is minor and can be solved on the users end. But this would involve adding this for every user. So better solve it at the source.

**Comment by robertwayne** [comment]
There was a relevant PR: #2309 

That said, this got addressed upstream recently [here](https://github.com/rust-lang/rust-clippy/pull/9486), which is available on nightly.

**Comment by SergioBenitez** [comment]
Indeed, fixed in rc.3 as well. Thanks!
