### ISSUE TITLE
Implement `serde::Serialize` for `rocket::http::Status``

### ISSUE THREAD

**Issue by Scripter17** [SergioBenitez/Rocket#2366]
**Is your feature request motivated by a concrete problem? Please describe.**

My website has an API that, for the sake of making it easier for users to parse, returns the HTTP status in the response JSON (as well as the response code). I'd like the enum variants to have a `code: rocket::http::Status` in them, but that conflicts with `#[derive(Serialize)]`

**Why this feature can't or shouldn't live outside of Rocket**

As far as I'm aware, it's impossible for me to do this outside of modifying rocket's source code on my machine.

The only alternative is to, well

```Rust
use serde::ser::{Serialize, SerializeStruct, Serializer};
use rocket::http::Status;

enum ApiResult {
    Error{code: Status},
    // ...
}

impl Serialize for ApiResult {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error> where S: Serializer, {
        match *self {
            ApiResult::Error{ref code, ..} => {
                let mut state = serializer.serialize_struct("Error", 1)?;
                state.serialize_field("code", &code.code)?;
                state.end()
            },
            // ...
        }
    }
}
```

Which is just not practical to scale up, especially given how small of a feature it is

**Ideal Solution**

Ideally `rocket::http::Status` would be serialized as a `u16`. So `enum ApiResult{Error: {code: Status}}` would look like `{"code": 404}` to the client

**Alternatives Considered**

There's a chance that someone else would want `Status::NotFound` to serialize to `{"code": 404, "reason": "Not Found"}`, but I think a `404` is more than enough here

**Comment by the10thWiz** [comment]
This can be done, at least to a limited extent, from outside Rocket. See https://serde.rs/remote-derive.html for documentation on how this can be done in general.

This method also allows customizing what exactly Serde outputs, e.g. if someone wants to include the reason, they can.

**Comment by Scripter17** [comment]
This simplifies things greatly. Thank you so much

I still think it should be implemented in rocket itself but this is a perfectly fine workaround
