### ISSUE TITLE
Dapr Intergration

### ISSUE THREAD

**Issue by kochia3** [SergioBenitez/Rocket#2371]
**Is your feature request motivated by a concrete problem? Please describe.**

I would like to see Dapr integration with Rocket.rs, similar to what FastAPI have:
https://docs.dapr.io/developing-applications/sdks/python/python-sdk-extensions/python-fastapi/

There is Rust SDK wip:
https://github.com/dapr/rust-sdk

**Why this feature can't or shouldn't live outside of Rocket**

If it's possible to be used without integration, maybe mentioning it in wiki and providing example would help.

**Comment by SergioBenitez** [comment]
I'm not opposed to this in the slightest, but we'd need to show that this can't live outside of Rocket's core, or that doing so comes at too high a usability cost. I'd encourage the community to explore external implementations of such support.
