### ISSUE TITLE
Incorrect file size in multipart form file upload

### ISSUE THREAD

**Issue by hellomotor** [SergioBenitez/Rocket#2377]
**Description**

Rocket seems not handle multipart form file correctly, 

**To Reproduce**
         
      main.rs 
                
                 #[macro_use] extern crate rocket;
                use rocket::serde::json::Json;
                use rocket::fs::TempFile;
                use serde::{Serialize, Deserialize};
                use rocket::http::ContentType;
                use rocket::form::Form;
                
                #[derive(FromForm)]
                struct FileUpload<'f> {
                    name: String,
                    file: TempFile<'f>
                }
                
                #[derive(Serialize, Deserialize, Debug)]
                struct Response {
                    name: String,
                    fsize: u64
                }
                
                #[get("/")]
                fn index() -> &'static str {
                    "hello, world"
                }
                
                #[post("/upload", format = "multipart/form-data", data = "<form>")]
                async fn upload(cont_type: &ContentType, form: Form<FileUpload<'_>>) -> Json<Response> {
                    println!("Content-Type: {:?}", cont_type);
                    println!("file: {:?} size: {:?}", form.name, form.file.len());
                    let resp = Response {
                        name: form.name.clone(),
                        fsize: form.file.len()
                    };
                    Json(resp)
                }
                
                #[launch]
                fn launch() -> _ {
                    rocket::build().mount("/", routes![index, upload])
                }

    post_file.py

        import requests
        import os
        
        upload_file = '###/path/to/upload/file###'
        
        files = { 'file': open(upload_file, 'rb'), 'name': os.path.basename(upload_file) }
        r = requests.post('http://127.0.0.1:8000/upload', files=files)
        
        print("reported size: {}".format(r.json()['fsize']))
        print("stat size: {}".format(os.path.getsize(upload_file)))
        assert r.json()['fsize'] == os.path.getsize(upload_file), 'different file size'

**Expected Behavior**

**Environment:**

 - OS Distribution and Kernel: macOS 12.5.1
 - Rocket Version: 0.5.0-rc.2

**Additional Context**

  I found that using curl post file works fine, but python requests post does not work, the difference I observed is that the boundary used in content-type is different, curl uses a boundary that starts with `--------------`, while requests uses alpha and numbers

**Comment by SergioBenitez** [comment]
I just tried your code and I cannot replicate. Perhaps fixes to `multer` resolved this? Or perhaps your `curl` invocation was missing something? Can you see if this problem still occurs?

Here's what I ran:

```
❯ wc -c foo.txt
      14 foo.txt

> curl -v -F name='foo.txt' -F file=@foo.txt http://localhost:8000/upload
{"name":"foo.txt","fsize":14}

> python3 req.py
reported size: 14
stat size: 14
```

I don't believe there's an issue here, so I'm closing this out, but I'm happy to be correct and take a second look.
