### ISSUE TITLE
Route argument with twitter API convention

### ISSUE THREAD

**Issue by sweihub** [SergioBenitez/Rocket#2380]
Hi Rocket

Thanks for the awsome contribution, can we add feature to support the twitter like API convention? The argument in the route path with a leading colon, it's simple and REST way. (Java/JavaScript ...)

```
DELETE /2/users/:id/likes/:tweet_id
GET /2/tweets/:id/liking_users
GET /2/users/:id/liked_tweets
POST /2/users/:id/likes
```

Note:
We can support both the `<argument>` and `:argument` way for compatibility.

**Comment by SergioBenitez** [comment]
The challenge with `:foo` is that it prohibits naming parameters within a segment, for instance, something like: `foo<bar>baz` would not be possible (`foo:barbaz` == `foo<barbaz>` != `foo<bar>baz`). While Rocket doesn't support this today, I do hope it supports it in the future, and so we cannot use `:foo`. `{foo}` doesn't suffer from this, and would be fine, and I'd be open to an implementation that considers _all_ cases. A grep for `<` and `const`s mapped to `<` or `>` would be needed. There are lots of particularities to getting this right.

Closing this issue as it proposes `:foo` which I am not in favor of for the reasons above.
