### ISSUE TITLE
Support multiple content types in requests

### ISSUE THREAD

**Issue by ghost** [SergioBenitez/Rocket#2381]
I'm building an API to a spec that mandates you support two different content types but returning the same response format. They're both JSON, but one has an extension to it, e.g.:

```
Accept: application/json
Accept: application/json+custom
```

**Why this feature can't or shouldn't live outside of Rocket**

I'm not an expert on Rocket's architecture, but I would assume routing is intrinsic to Rocket and probably not extensible in the manner needed to implement this externally.

**Ideal Solution**

It would be nice if we could declare multiple values for format that are valid for the route, to avoid having to declare multiple routes that implement the same behavior. This would mean less need to duplicate logic / split logic out into other functions to minimize duplication in this scenario.

Ideally this would take the form of something as simple as:

```rust
#[rocket::get("/my/route", format = vec!["application/json", "application/json+custom"])]
```

**Additional Context**

The specific situation I'm in is properly conforming to the ActivityPub spec, as quoted:

> The HTTP GET method may be dereferenced against an object's id property to retrieve the activity. Servers MAY use HTTP content negotiation as defined in [[RFC7231](https://www.w3.org/TR/activitypub/#bib-RFC7231)] to select the type of data to return in response to a request, but MUST present the ActivityStreams object representation in response to application/ld+json; profile="https://www.w3.org/ns/activitystreams", and SHOULD also present the ActivityStreams representation in response to application/activity+json as well. The client MUST specify an Accept header with the application/ld+json; profile="https://www.w3.org/ns/activitystreams" media type in order to retrieve the activity.

**Comment by the10thWiz** [comment]
In this case, I think the format parameter is not the correct way to handle this. Rather, I would suggest not specifying a format in the route attribute, but rather creating a custom route guard that checks the Accept & Content-Type headers. This also allows much more advanced logic.
