### ISSUE TITLE
Remove sqlx features due to a bug in rustls/webpki failing to resolve IP addresses 

### ISSUE THREAD

**Issue by aadityadhruv** [SergioBenitez/Rocket#2391]
**Description**

 Currently `sqlx` in `db_pools` uses `runtime-tokio-rustls` as its feature. This has a [bug](https://github.com/launchbadge/sqlx/issues/1095) which results in a `InvalidDNSNameError` for raw IP addresses as a part of the url. This is being [fixed](https://github.com/rustls/webpki/pull/5), however, it would be nice to let the user choose their TLS back-end. 

**To Reproduce**

Setting the database url to a raw IP address as follows: 
```
mysql://foo:bar@<IP>:3306/baz
```

**Expected Behavior**

The IP shouldn't need any DNS resolution. 

**Environment:**

 - OS Distribution and Kernel: [Fedora 36, Kernel 6.0.5]
 - Rocket Version: [0.5.0-rc.2]

**Additional Context**

A simple fix is to remove the feature from sqlx, and let the user choose the backend.

**Comment by aadityadhruv** [comment]
Here is a simple fix to resolve this issue https://github.com/SergioBenitez/Rocket/pull/2392

**Comment by tn-dev-fl** [comment]
i got this error **error occurred while attempting to establish a TLS connection: InvalidDNSNameError .** it worked fine on my main machine . i tried to remove the features sqlx runtime i get another error 
compile_error!( "one of the features ['runtime-actix-native-tls', 'runtime-async-std-native-tls', \
      'runtime-tokio-native-tls', 'runtime-actix-rustls', 'runtime-async-std-rustls', \
      'runtime-tokio-rustls'] must be enabled"
 );
   ^

**Comment by aadityadhruv** [comment]
You need to specify a runtime, you can use the `tokio-native-tls` one since `rustls` cannot resolve direct IP addresses yet.

**Comment by SergioBenitez** [comment]
I'm considering this an upstream isusue: https://github.com/SergioBenitez/Rocket/pull/2392#issuecomment-1487728679.

**Comment by aadityadhruv** [comment]
Yeah, I read that comment, I think that may be a suitable idea.

**Comment by SergioBenitez** [comment]
Looks like the new rustls release fixes this! Shall we update dependencies and see if that's so?

**Comment by SergioBenitez** [comment]
I updated rustls in Rocket in fbb0ace52981fde8825cad08ec42710c4e61c216. I also sent a PR to sqlx to update rustls there as well (https://github.com/launchbadge/sqlx/pull/2440). Since there's no issue on Rocket's end, and everything we could do from our side is now complete, I'm closing this out.

**Comment by aadityadhruv** [comment]
That's great! So once sqlx updates rustls on their end, everything should be good to go right?

**Comment by SergioBenitez** [comment]
Yup! It should just work if you `cargo update`, even without a new Rocket release.
