### ISSUE TITLE
Async story?

### ISSUE THREAD

**Issue by ereichert** [SergioBenitez/Rocket#24]
First, this looks extremely promising at first glance. The top level DSL looks fantastic. Nice job.

Second, do you have plans for an async version?

Just saw you used Hyper. That may answer the question.

**Comment by SergioBenitez** [comment]
Thank you!

Certainly. I discuss this in the README:

> ### Future Improvements
> 
> Rocket is currently built on a synchronous HTTP backend. Once the Rust
> asynchronous I/O libraries have stabilized, a migration to a new, more
> performant HTTP backend is planned. We expect performance to improve
> significantly at that time. The [Stabilize HTTP Library](https://github.com/SergioBenitez/Rocket/issues/17) issue tracks the progress
> on this front.

Definitely want to switch over to async as soon as the ecosystem matures.

**Comment by ereichert** [comment]
Ah. Hadn't got to the README yet. Went straight to the code. Gotta eat my dinner before desert next time. :)
