### ISSUE TITLE
Default permissions-policy header includes 'removed' feature, causes warnings

### ISSUE THREAD

**Issue by randomouscrap98** [SergioBenitez/Rocket#2410]
**Description**

Adding `interest-cohort=()` to the `permissions-policy` header produces a warning on each page load. This is unfortunately the default `Shield`/`Permission` setup when launching Rocket, and I haven't found a good way to get around this, other than attaching `Shield::new()` and manually setting up the OTHER default security headers. 

Google seems to have stopped their FLoC thing; here are a couple links mentioning the same article that Google is "going in a new direction": 
https://stackoverflow.com/a/70915754/1066474
https://www.drupal.org/project/drupal/issues/3284706
(The linked google blogpost, which of course doesn't directly mention that they're killing this trial): https://blog.google/products/chrome/get-know-new-topics-api-privacy-sandbox/

**To Reproduce**

- Create a basic default rocket project from 0.5.0-rc.2 with a whatever index page, launch. 
- Visit the page in a chromium-based browser, open dev log
- See: 
![image](https://user-images.githubusercontent.com/13357277/204376929-512ecb60-c398-4dce-8043-d0dda94cda38.png)

**Expected Behavior**

I would hope that the defaults for rocket wouldn't cause warnings due to 'deprecated' features (I know it's hard because Google and other web companies change their mind every couple months). I do appreciate that you're trying to protect the users.

**Environment:**

 - OS Distribution and Kernel: any
 - Rocket Version: 0.5.0-rc.2

**Comment by SergioBenitez** [comment]
While the "interest cohort" feature is gone, a new topic API with similar interests has been proposed, and this header [disables that as well](https://github.com/patcg-individual-drafts/topics). From the draft spec:

> A site can forbid topic calculation on a page via the following permission policy header:
>
>Permissions-Policy: browsing-topics=()
>Note: The old Permissions-Policy: interest-cohort=() from FLoC will also forbid topic calculation.

As far as I know, this is the only header that protects against the older API and the newer API. If you really don't want the header, it's also fairly straightforward to remove:

```rust
rocket::build()
    .mount("/", ....)
    .attach(Shield::default().disable::<Permission>())
```
