### ISSUE TITLE
Add LruCache or Hasmap State Example

### ISSUE THREAD

**Issue by elibroftw** [SergioBenitez/Rocket#2418]
**Existing Functionality**

A clear and concise description of existing functionality and why it is insufficient. Examples:

I frequently want to do acccess an LRU Cache (underelying hashmap) accross routes, but Rocket makes it hard. 
It would be nice if there were examples of complicated states that involve mutex or arc since tokio isn't even a dependency.

**Suggested Changes**

add an example where a route modifies a cache or a state. In my case, multiple routes should be able to access and modify this cache and the cache should be mutable from a non route function too.

**Alternatives Considered**

Using Vlang or C++ lithium for future development.

**Additional Context**

I'm porting https://github.com/elibroftw/website/blob/master/blueprints/tauri_releases/__init__.py to rocket.rs

**Comment by SergioBenitez** [comment]
Have you seen the [examples](https://github.com/SergioBenitez/Rocket/blob/master/examples/README.md) directory? In particular, the state example shows how to leverage Rocket's state management facilities to do things like what you'd like.

**Comment by elibroftw** [comment]
I did take a look but it isn't a global cache with ttl. I ended up figuring it out though since I did something similar in March.

There should be an arc mutex example. It may seem pretty simple in hindsight bur for people who don't use arc a lot it's a whole new ball game.

**Comment by SergioBenitez** [comment]
I agree that this can be tricky, but unfortunately it's trickiness that's independent of Rocket. We can definitely steer folks in the right direction, as I think we do with the `state` example, however. Nevertheless, I'm closing out this issue as you've found a solution.
