### ISSUE TITLE
async FromParam

### ISSUE THREAD

**Issue by M1ngXU** [SergioBenitez/Rocket#2420]
**Existing Functionality**

A clear and concise description of existing functionality and why it is insufficient. Examples:

I need to check weather "something" exists (path segment), so i wanted to use guards. but to check weather it exists, i have to ask a db which is async, but `from_param` is sync (is `tokio::task::block_on` a good alternative?)

**Suggested Changes**

Make FromParam async.

**Alternatives Considered**

- FromParamAsync, though I am not sure how to integrate this into the current macros.
- Make sure that a "long-running" from_param doesn't hang the whole server (didn't test if it's already the case)

**Comment by the10thWiz** [comment]
I don't think this is going to happen, for a few reasons. First, `FromParam` is intended to parse a segment, not check whether a database entry, or anything else exists. This narrow interpretation means that checking arbitrary preconditions (such as the existence of a database entry) should be deferred to the actual route body.

To provide an easier API, your type that implements `FromParam` could provide an async method to complete verification of the parameter.

**Comment by M1ngXU** [comment]
Ok thanks
