### ISSUE TITLE
Misleading error using TLS: 'aborting due to socket bind error'

### ISSUE THREAD

**Issue by hut8** [SergioBenitez/Rocket#2423]
**Description**

First, thanks for making such a great framework 👍🏻 I'm really liking it but ran into a hiccup 😄 

I'm trying to deploy a Rocket application via systemd. I used capabilities (i.e., `AmbientCapabilities` in my service file) to ensure that I could bind to privileged ports. I spent a few frustrating hours, trying to figure out why this wasn't working, after I got this:

```
Dec 12 18:27:50 localhost strace[1074055]: thread 'main' panicked at 'aborting due to socket bind error', /home/liam/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.5.0-rc.2/src/error.rs:200:17
Dec 12 18:27:50 localhost strace[1074055]: stack backtrace:
Dec 12 18:27:50 localhost strace[1074055]:    0: rust_begin_unwind
Dec 12 18:27:50 localhost strace[1074055]:              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
Dec 12 18:27:50 localhost strace[1074055]:    1: core::panicking::panic_fmt
Dec 12 18:27:50 localhost strace[1074055]:              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
Dec 12 18:27:50 localhost strace[1074055]:    2: <rocket::error::Error as core::ops::drop::Drop>::drop
Dec 12 18:27:50 localhost strace[1074055]:    3: server::main::{{closure}}
Dec 12 18:27:50 localhost strace[1074055]:    4: tokio::park::thread::CachedParkThread::block_on
Dec 12 18:27:50 localhost strace[1074055]:    5: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
Dec 12 18:27:50 localhost strace[1074055]:    6: tokio::runtime::Runtime::block_on
Dec 12 18:27:50 localhost strace[1074055]:    7: server::main
```

So it sounds like there's a problem with binding to a port (`socket bind error`). As you can see above, I was actually running this through `strace` to debug it, and noticed that nowhere in the strace logs does a `bind` call occur. I'm using environment variables to configure this app in production rather than `rocket.toml` (ideally I'd like to have everything in one binary, including the assets). Here's my config:

```
ROCKET_TLS={certs="/path/to/cert.com.crt",key="/path/to/key.com.key"}
ROCKET_ADDRESS=0.0.0.0
ROCKET_PORT=443
ROCKET_LOG_LEVEL="debug"                                                                                                                                                                  7 ROCKET_CLI_COLORS="false"
```

Digging into the strace logs, I looked wat what was happening right before the crash:

```
1074055 getcwd("/", 512)                = 2
1074055 openat(AT_FDCWD, "/path/to/cert.com.crt", O_RDONLY|O_CLOEXEC) = 10
1074055 openat(AT_FDCWD, "/path/to/key.com.key", O_RDONLY|O_CLOEXEC) = 11
1074055 read(10, "-----BEGIN CERTIFICATE-----\nMIIE"..., 8192) = 5333
1074055 read(10, "", 8192)              = 0
1074055 read(11, "-----BEGIN EC PRIVATE KEY-----\nM"..., 8192) = 227
1074055 close(10)                       = 0
1074055 close(11)                       = 0
1074055 munmap(0x7ff734e00000, 5044484796) = 0
1074055 munmap(0x7ff861a00000, 575087848) = 0
1074055 write(2, "thread '", 8)         = 8
1074055 write(2, "main", 4)             = 4
1074055 write(2, "' panicked at '", 15) = 15
1074055 write(2, "aborting due to socket bind erro"..., 33) = 33
1074055 write(2, "', ", 3)              = 3
1074055 write(2, "/home/liam/.cargo/registry/src/g"..., 89) = 89
1074055 write(2, ":", 1)                = 1
1074055 write(2, "200", 3)              = 3
1074055 write(2, ":", 1)                = 1
1074055 write(2, "17", 2)               = 2
1074055 write(2, "\n", 1)               = 1
1074055 getcwd("/", 512)                = 2
1074055 write(2, "stack backtrace:\n", 17) = 17
```

This is what really tripped me up -- there's no `bind` syscall anywhere! But I noticed that the panic trace is written immediately after some SSL stuff, so I commented out the `ROCKET_TLS` config line in my environment file, and then it works.

**To Reproduce**

This asks for the code, so here it is: https://github.com/hut8/wikipedia-speedrun/tree/617b68a26b3689ef3eefee23ef6122801c909cfe

The `rocket` server is in `/server` and the systemd service is in `wikipedia-speedrun.service`, although the environment file is really what matters. A .env containing the above config should work. The critical line to trigger the bug is:

```
ROCKET_TLS={certs="/path/to/certs.com.crt",key="/path/to/key.com.key"}
```

With that line, I get the error message. Without it, it will successfully bind to port 443 (although obviously it will be listening without TLS; but it can serve plaintext HTTP fine).

**Expected Behavior**

If something about the TLS config is causing a problem, the error message (`socket bind error`) should not suggest that there's a problem with binding.

**Environment:**

 - OS Distribution and Kernel: [e.g. Arch Linux 4.16.13, macOS 11.2.1]

```
Arch Linux
6.0.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 15 Oct 2022 14:00:49 +0000 x86_64 GNU/Linux
```

 - Rocket Version: [e.g. 0.4.12, master@abf996b]

```
[[package]]
name = "rocket"
version = "0.5.0-rc.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "98ead083fce4a405feb349cf09abdf64471c6077f14e0ce59364aa90d4b99317"
```

**Additional Context**

Judging by strace, it looks like it can read the cert and key files fine; I'm not yet sure what the problem is with them, but I'll update the issue when I find out.

**Comment by hut8** [comment]
Ah, so I had configured my own logging via `stderrlog` which silenced this error:

```
Dec 12 19:10:58 localhost strace[1078632]: Error: Rocket failed to bind network socket to given address/port.
Dec 12 19:10:58 localhost strace[1078632]:    >> bad TLS private key: invalid key header; supported formats are: RSA, PKCS8
```

When removing the logging config, that makes it much simpler to debug 😄 Still, I think the panic message should reference the certificate rather than the binding, if possible.

**Comment by SergioBenitez** [comment]
The problem is that the error occurs during binding, so it's not an incorrect message. But as you've noticed, it's possible to hide the error details which elucidate the true problem. I see this is a logging issue, so I'm punting to #21. Thank you for the issue!
