### ISSUE TITLE
"Rocket configuration extraction from provider failed." | "Rocket configuration extraction from provider failed."

### ISSUE THREAD

**Issue by 2-3-5-41** [SergioBenitez/Rocket#2437]
**Description**

While trying to create a prototype rest api with diesel and postgresql, I've ran into this error when trying to use the `ROCKET_DATABASES` one-liner variable:

```
Error: Rocket configuration extraction from provider failed.
   >> invalid type: string "{gaslight={url=\"postgres://introvert:5RFcGn5i45RPjSg7p7TgU56zneWiH69u@localhost/gaslight\"}}", expected a map for key `ROCKET_DATABASES` at line 2 column 18
   >> in Rocket.toml TOML file
```

If I try to use the other variation of this `databases` variable, or if I use the one-liner in a normal `.env` file:

```
Error: database config error for pool named `gaslight`
   >> missing field `url`
Error: Rocket failed to launch due to failing fairings:
   >> 'gaslight' Database Pool
```

**To Reproduce**

Here is the github repo; [gaslight](https://github.com/1SMOL/gaslight).

**Environment:**

 - OS Distribution and Kernel: Arch Linux 6.0.12-arch1-1
 - Rocket Version: 0.5.0-rc.2
 - Rocket Sync DB Pools Version: 0.1.0-rc.2

**Additional context**

I'm currently trying to learn how work with rust based apis using rocket, and I'm switching between documentation and an [example by TmLev](https://github.com/TmLev/crud-rest-api-rust-rocket-diesel-postgres). And don't worry, the posgres user creds are not used on any live services.

**Comment by SergioBenitez** [comment]
> While trying to create a prototype rest api with diesel and postgresql, I've ran into this error when trying to use the `ROCKET_DATABASES` one-liner variable:
> 
> ```
> Error: Rocket configuration extraction from provider failed.
>    >> invalid type: string "{gaslight={url=\"postgres://introvert:5RFcGn5i45RPjSg7p7TgU56zneWiH69u@localhost/gaslight\"}}", expected a map for key `ROCKET_DATABASES` at line 2 column 18
>    >> in Rocket.toml TOML file
> ```

This isn't semantically meaningful TOML syntax but instead Figment's environment-variable syntax, and thus isn't parsed how you expect it. Here's the equivalent TOML:
 
```toml
[global.databases.gaslight]
url = "postgres://introvert:5RFcGn5i45RPjSg7p7TgU56zneWiH69u@localhost/gaslight"
```

I recommend reading at least the first part of the docs at https://rocket.rs/v0.5-rc/guide/state/#databases and/or https://api.rocket.rs/v0.5-rc/rocket_db_pools/index.html.
