### ISSUE TITLE
Big JSON data handling bug

### ISSUE THREAD

**Issue by L117** [SergioBenitez/Rocket#244]
## Bug Report

I'm on latest version of Rocket (0.2.3).

When trying to handle POST request with really big JSON data (More than 2Mb, base64-encoded images), it fails with following terminal output: 
```
POST /api/upload_image application/json:
    => Matched: POST /api/upload_image application/json
    => Warning: Data left unread. Force closing network stream.
    => Error: Couldn't parse JSON body: Syntax(EOFWhileParsingString, 1, 1048576)
    => Outcome: Failure
    => Warning: Responding with 400 Bad Request catcher.
    => Error: Failed to write response: Error { repr: Os { code: 32, message: "Broken pipe" } }.
```

I'm able to reproduce it with following `main.rs`:
```
#![feature(plugin)]
#![plugin(rocket_codegen)]

extern crate rocket;
extern crate serde_json;
#[macro_use] 
extern crate rocket_contrib;
#[macro_use]
extern crate serde_derive;

use rocket_contrib::{ JSON, Value };

#[derive(Serialize, Deserialize)]
struct ImageUploadRequest {
   data: String
}

#[post("/api/upload_image", format = "application/json", data = "<message>")]
fn upload_image(message: JSON<ImageUploadRequest>) -> JSON<Value> {
    JSON(json!({ "data" : message.data }))    
}

fn main() {
    rocket::ignite().mount("/", routes![upload_image]).launch();
}
```
And the following `curl` invocation:
```
echo "{\"data\":\"`cat someimage.jpg | base64 | tr -d '\n'`\"}" | curl -H "Content-Type: application/json" -X POST -d @- http://localhost:8000/api/upload_image
```

**Comment by SergioBenitez** [comment]
This isn't a bug, and so I've marked it as "invalid". Instead, it's an explicit restriction of the JSON type: the size limit of a JSON encoded body is set to 1MB. This is to prevent DOS attacks with extremely long JSON messages.

Ideally, this size limit would be configurable. Further, when the limit is reached, it would be nice if a more favorable error message was emitted. If you'd like to request these features, please open a separate issue.

**Comment by L117** [comment]
@SergioBenitez Actually this JSON issue originates from inability to find a way to receive POST request with both data and arguments (e.g. username(arg), usersecret(arg) and file(data)). Should I open another Issue for this?

**Comment by SergioBenitez** [comment]
No, you can certainly do that with Rocket. It would look something like this:

```rust
#[post("/<username>/<secret>", data = "<file>")]
fn your_route(username: String, secret: Secret, file: Data) -> io::Result<T> {
    file.read_to_file("some_path")?;
    ...
}
```

If you need help accomplishing something that feels like it should be possible, make sure you ask on IRC/Matrix. It almost certainly is.

**Comment by L117** [comment]
In this case args become part of path, right?

**Comment by SergioBenitez** [comment]
I'm not sure what you mean. I assumed that by arguments, you meant path parameters, but perhaps you meant something else. Nonetheless, wherever your arguments are coming from, you can get _them_ _and_ the data. If you need extra help, hop on Matrix/IRC.
