### ISSUE TITLE
No way to stop EventStream

### ISSUE THREAD

**Issue by justindthomas** [SergioBenitez/Rocket#2455]
It looks like the suggested code for `EventStream` involves a loop that will never break - even after client disconnect. If I close my browser after initiating an `EventStream` from Rocket, that stream just keeps going on the server. I can't find a way to have it automatically stop the loop, or some mechanism to check the status of the connection from within the loop to stop it there.

What is the recommended way to do this? Surely, just looping forever for every request can't be the expected outcome. Here's a snippet of what I have going on. `EventsChannel` is a Fairing that I wrote to maintain `crossbeam` channels to handle event distribution.

```rs
#[get("/events")]
async fn stream(mut shutdown: Shutdown, mut events: EventChannels) -> EventStream![] {
    EventStream! {
        let rx = events.subscribe("stream".to_string());
        let mut interval = time::interval(Duration::from_secs(1));

        let mut i = 1;

        loop {
            debug!("looping");
            select! {
                _ = interval.tick() => {
                    if let Ok(message) = rx.try_recv() {
                        i += 1;
                        yield Event::data(message).event("message").id(i.to_string());
                    }
                },
                _ = &mut shutdown => {
                    yield Event::data("goodbye").event("message");
                    break;
                }
            };
        }
    }
}
```

I tried eliminating the loop, but that seems to terminate the connection (my browser constantly reestablishes, but again, I can't believe that would be the expected outcome here). Especially since I can't move that `subscribe` outside of the `EventStream!` macro - the macro seems to demand to be at the top of the function.

I'm sure I'm missing something obvious. Please point me in the right direction if so.

*UPDATE*

I added another counter and an explicit `break` to force a regular connection reset (since the browser does it automatically).

```rs
if k >= 300 {
    //debug!("breaking loop to force reconnection");
    break;
} else {
    k += 1;
}
```

I'm hoping there's something better, though.

**Comment by Nukesor** [comment]
@justindthomas 

The way we're currently handling this scenario is as follows:

```rs
    let event_stream = EventStream! {
        loop {
            let message = match receiver.recv().await {
                Err(RecvError::Closed) | Ok(SseMessage {
                    message_type: SseMessageType::Shutdown,
                    ..
                })=> {
                    break;
                },
                Err(RecvError::Lagged(_)) => continue,
                Ok(message) => message,
            };

            yield Event::json(&message);
        }
    };
```

This breaks the loop as soon as the connection is closed.

**Comment by justindthomas** [comment]
Thank you for the notes, @Nukesor! But isn't that checking for a disconnection with the source of the messages rather than the destination? I don't know what `receiver` is in that block, but I assume that's an analog to my crossbeam channel.

What I'm most concerned about is the browser on the other end of the `EventStream`. I haven't found a way to detect when that disappears (i.e., either the window is closed or whatever else might cause the HTTP connection to be interrupted).

**Comment by SergioBenitez** [comment]
The intention is for the stream to be automatically interrupted when the client disconnects, and in my testing, this is exactly what happens. For example, if I have the following (taken from the `responders` example):

```rust
#[get("/stream/hi/<n>")]
fn one_hi_per_ms(mut shutdown: Shutdown, n: u8) -> TextStream![&'static str] {
    TextStream! {
        let mut interval = time::interval(Duration::from_millis(n.into()));
        loop {
            select! {
                _ = interval.tick() => {
                    println!("sending hi...");
                    yield "hi"
                }
                _ = &mut shutdown => {
                    yield "goodbye";
                    break;
                }
            };
        }
    }
}
```

I see the following log output when I connect and then disconnect after a short period of time:

```
GET /stream/hi/250:
   >> Matched: (one_hi_per_ms) GET /stream/hi/<n>
   >> Outcome: Success
sending hi...
sending hi...
sending hi...
sending hi...
sending hi...
sending hi...
sending hi...
sending hi...
sending hi...
   >> Remote left: channel closed.
```

There is no log output after this, indicating that the stream has closed. We can go a step further and ensure that the entire stream has dropped by using a drop guard:

```rust
struct DropGuard;

impl Drop for DropGuard {
    fn drop(&mut self) {
        eprintln!("-- DROPPED --");
    }
}

#[get("/stream/hi/<n>")]
fn one_hi_per_ms(mut shutdown: Shutdown, n: u8) -> TextStream![&'static str] {
    TextStream! {
        let _drop_guard = DropGuard;
        let mut interval = time::interval(Duration::from_millis(n.into()));
        loop {
            select! {
                _ = interval.tick() => {
                    println!("sending hi...");
                    yield "hi"
                }
                _ = &mut shutdown => {
                    yield "goodbye";
                    break;
                }
            };
        }
    }
}
```

The log shows that this indeed does happen:

```
GET /stream/hi/250:
   >> Matched: (one_hi_per_ms) GET /stream/hi/<n>
   >> Outcome: Success
sending hi...
sending hi...
sending hi...
sending hi...
sending hi...
sending hi...
sending hi...
-- DROPPED --
   >> Remote left: channel closed.
```

Are you sure the client is actually disconnecting? Browsers love to keep connections open.

**Comment by justindthomas** [comment]
Interesting. Okay, I'll dig on this a bit more. It looked to me like once the `loop` entered, it never exited. But maybe I misinterpreted. I'll integrate the `DropGuard` and observe things for a while.

**Comment by justindthomas** [comment]
Could this be an `EventStream` versus `TextStream` thing? Even with my code as adjusted below, I never see that `drop` called - even after I've completely closed the client browser. The server continues to trigger that "SENDING MESSAGE TO" log message long after the browser is gone.

```rs
struct DropGuard {
    events: EventChannels,
    uuid: String,
}

type DropType = (EventChannels, String);
impl From<DropType> for DropGuard {
    fn from((events, uuid): DropType) -> Self {
        DropGuard { events, uuid }
    }
}

impl Drop for DropGuard {
    fn drop(&mut self) {
        log::debug!("REMOVING EVENT LISTENER {}", self.uuid.clone());
        self.events.remove(self.uuid.clone());
    }
}

#[get("/api/user/<username>/events")]
async fn stream(
    mut shutdown: Shutdown,
    mut events: EventChannels,
    username: String,
) -> EventStream![] {
    EventStream! {
        let (uuid, rx) = events.subscribe(username);
        let _drop_guard = DropGuard::from((events.clone(), uuid.clone()));
        let mut i = 1;

        #[derive(Serialize)]
        struct StreamConnect {
            uuid: String
        }

        let message = serde_json::to_string(&StreamConnect { uuid: uuid.clone() }).unwrap();

        yield Event::data(message).event("message").id(i.to_string());
        i += 1;

        let mut interval = time::interval(Duration::from_secs(1));

        loop {
            select! {
                _ = interval.tick() => {
                    if let Ok(message) = rx.try_recv() {
                        log::debug!("SENDING MESSAGE TO {uuid}");
                        i += 1;
                        yield Event::data(message).event("message").id(i.to_string());
                    }
                },
                _ = &mut shutdown => {
                    log::debug!("SHUTDOWN {uuid}");
                    yield Event::data("goodbye").event("message");
                    break;
                }
            };
        }
    }
}
```

The code is obviously more complex than the example because I'm ingesting events from the `crossbeam` channels. I'm also authorizing the stream on initiation as an out-of-band message.

**Comment by SergioBenitez** [comment]
> Could this be an EventStream versus TextStream thing? Even with my code as adjusted below, I never see that drop called - even after I've completely closed the client browser. The server continues to trigger that "SENDING MESSAGE TO" log message long after the browser is gone.

I haven't had a chance to take a close look at your repository, but I wanted to jump on this piece and note that the browser might still be keeping the connection open if any of its processes are running. For example, closing a tab doesn't mean the connections initiated for that tab close. To make sure the problem you're seeing isn't due to the client remaining connected, I would advise using something like `curl` or `netcat`, which absolutely close the connection when they exit. I used (a version of) the latter in my tests above. Beyond that, ensure you're using rc3, though I don't recall any related issues.

I'll take a closer look at your repository later this weekend.

**Comment by justindthomas** [comment]
Thanks. I did verify that all Firefox processes were killed off, but the server continues to loop. I'll look in to recreating from the CLI as well (have to remove the authentication since that's a complex interaction between a wasm module and cryptographic signatures).

**Comment by justindthomas** [comment]
Okay, a little progress here. I simplified the endpoint and tried access from the browser with the same results. I then tried using `curl` and saw what you expect (the loop is interrupted when the connection is terminated).

I then tried a direct connection to the application server from the browser instead of the connection through my TLS proxy. Then I closed the browser and made sure all processes were killed. That worked!

So, it seems that the proxy (Apache in this case) is holding the connection open somehow. I'll explore that and close this for now. Thank you for your insight!

**Comment by justindthomas** [comment]
Could also be Vite. Because I'm seeing this on my `dev` server where Vite is facing the Apache reverse proxy and is in turn relaying connections to Rocket (to avoid CORS issues). On my `prod` instance, I'm using `nginx` instead of Vite, so that may show different behavior. I'll keep experimenting and note what I ultimately find here for posterity.

**Comment by justindthomas** [comment]
It's definitely Vite. I don't see the problem behavior when I use my production Apache -> nginx -> Rocket infrastructure. The connections eventually clear as expected (although it doesn't happen as instantly as when testing curl -> Rocket directly).

I've experimented with the "timeout", "proxyTimeout" and various other `http-proxy` settings exposed by Vite, but nothing seems to affect it. I guess it's just something to live with for now. Stopping and starting the dev server clears the connections at Rocket.

**Comment by balping** [comment]
I face the same issue, yet I don't use Vite or any proxy.

**Comment by the10thWiz** [comment]
> I face the same issue, yet I don't use Vite or any proxy.

Do you have reproduction steps?

**Comment by balping** [comment]
I've created a minimal reproducible example that you can access in this zip file: [stream_example.zip](https://github.com/user-attachments/files/16416403/stream_example.zip)

For readability, here are code snippets as well:

```rust
#[get("/stream")]
async fn stream(mut end: Shutdown) -> EventStream![]  {
   let mut interval = time::interval(time::Duration::from_secs(2));
   let mut i = 0;
   EventStream! {
        loop {
            select! {
                _ = interval.tick() => {
                    i += 1;
                    println!("tick {}", i);
                    yield Event::data(format!("tick{} ", i));
                },
                _ = &mut end => {
                    println!("closing stream");
                    break;
                },
            };
        }
    }
}
```


```javascript
const evtSource = new EventSource("/stream");

evtSource.addEventListener("message", function (e) {
    console.log(e.data);
});

evtSource.addEventListener("error", function (e) {
    console.warn(e);
});

evtSource.addEventListener("open", (e) => {
    console.log("The connection has been established.");
});

document.getElementById("close").addEventListener("click", function(){
    evtSource.close();
});
```

Steps:

1. `cargo run`
2. Open http://127.0.0.1:8000/ in Firefox (version 128)
3. Open the developer console and check the messages
4. After some time click on "Close stream" in the browser

Browser output:

```
The connection has been established.
tick1
tick2
tick3
tick4
```

Rust std output:

```
tick 1
tick 2
tick 3
tick 4
tick 5
   >> Remote left: channel closed.
```

Note that there's an extra tick in rust, also "closing stream" is never printed, contrary to my expectation.

**Comment by balping** [comment]
@justindthomas @SergioBenitez Could you please reopen this issue? I think it's still an unresolved bug.

**Comment by the10thWiz** [comment]
If you have specific code you want to run when the client disconnects, you are best off creating an object, and implementing Drop on it, since Rocket drops the EventStream after the client disconnects.

**Comment by balping** [comment]
Ah thank you for the clarification, I was confused about shutdown.


I've checked in wireshark, the browser sends a `FIN-ACK` packet when calling `evtSource.close()` to which the server replies with  `FIN-ACK`. So at least at low level, it should be possible to detect when the client gracefully disconnects.


![wsh](https://github.com/user-attachments/assets/15a0bf11-4ed6-4547-b5e8-49eefbe4defc)
