### ISSUE TITLE
Server Sent Events cause unclean shutdown

### ISSUE THREAD

**Issue by levkk** [SergioBenitez/Rocket#2463]
**Description**

Using SSE (Server Sent Events) causes Rocket to have an unclean shutdown and panic:

```
2023-02-09T19:31:48Z WARN  rocket::server] Server failed to shutdown cooperatively.
[...]
thread 'main' panicked at 'failed to shut down Rocket: Shutdown(Orbiting { router: Router { routes: 
[...]
```

**To Reproduce**

Create a route with `EventStream!`, something like this:

```rust
EventStream! {
   loop {
      tokio::time::sleep(tokio::time::Duration::from_millis(1000).await;
      yield Event::data("hey");
   }
}
```

Connect to it from a browser using:

```javascript
let sse = EventSource('/route/to/sse');
```

Keep the browser open and issue a `SIGINT` to the Rocket process (Ctrl-C). Shutdown will wait for all HTTP requests to finish, but since SSE is streaming, it will not terminate. Eventually Rocket will panic and crash.

**Expected Behavior**

Terminate the SSE connection and exist cleanly.

**Environment:**

 - OS Distribution and Kernel: Ubuntu 22.04
 - Rocket Version: 0.5.0-rc2

**Additional Context**

It doesn't cause a big problem but if you're also using error reporting like Sentry, it causes noise in the monitoring and also delays shutdowns during deploys of new app versions.

Looks like it's related to #2455 .

**Comment by justindthomas** [comment]
Have you tried using `shutdown` to break out of the loop? #2455 shows that:

```rs
_ = &mut shutdown => {
    yield Event::data("goodbye").event("message");
    break;
}
```

**Comment by levkk** [comment]
That was it! Thank you!
