### ISSUE TITLE
Can't set max_age on cookies because time is not re-exported

### ISSUE THREAD

**Issue by jblachly** [SergioBenitez/Rocket#2465]
**Description**

`CookieBuilder::max_age` takes `time::Duration`. 

The `cookie-rs` library (https://github.com/SergioBenitez/cookie-rs) which is used internally by Rocket does re-export `time` (so would be fine if were to use cookie library directly), but Rocket only imports a few items like Cookie, CookieJar, and does not re-export `cookie`

The workaround is to include precisely the version of time used by the cookies-rs crate in your Cargo.toml at the top level, which is problematic if you were otherwise using time crate, and in particular a newer version.

**To Reproduce**

See:

https://github.com/SergioBenitez/Rocket/blob/master/core/lib/src/cookies.rs

**Expected Behavior**

I would expect that `time` is re-exported so that I don't have a version conflict , and can use the re-exported version with `max_age`

**Environment:**

 - Rocket 0.5.0-rc.1

**Comment by SergioBenitez** [comment]
`time` is now re-exported in rc.3. Thanks!
