### ISSUE TITLE
Support TLS 2

### ISSUE THREAD

**Issue by bradlysnyder2021** [SergioBenitez/Rocket#2470]
The Rocket framework TLS module should be updated to support TLS 2.0 because it provides stronger security than previous versions of TLS, such as TLS 1.2. TLS 2.0 has improved key exchange algorithms and stronger cryptographic primitives, making it more resistant to attacks such as eavesdropping, man-in-the-middle attacks, and decryption of encrypted data. Additionally, many modern web browsers and operating systems are dropping support for TLS 1.2, making it important for web applications to support the latest version of TLS to ensure compatibility with these platforms. Updating the Rocket framework TLS module to support TLS 2.0 would provide a more secure and future-proof solution for developers and their users.

**Comment by rtldg** [comment]
chatgpt

**Comment by SergioBenitez** [comment]
😅
