### ISSUE TITLE
Use `text/javascript` for `.mjs`

### ISSUE THREAD

**Issue by 42triangles** [SergioBenitez/Rocket#2479]
**Existing Functionality**

Currently Rocket appears to not support mapping `.mjs` files to the `text/javascript` mime type.

This has caused issues with a recent sveltekit update that switched to `.mjs` files for the static adapter, which have been served using [`rocket::fs::FileServer`](https://api.rocket.rs/v0.5-rc/rocket/fs/struct.FileServer.html) which doesn't appear to contain any possible way of extending known mime types, resulting in the mime type to not be set & as such a broken site.

**Suggested Changes**

Include `"mjs" => JavaScript,` in [`known_extensions!`](https://github.com/SergioBenitez/Rocket/blob/master/core/http/src/header/known_media_types.rs#L58) presumably

**Alternatives Considered**

Adding functionality to `rocket::fs::FileServer` (and `rocket::fs::NamedFile`) to add extra mimetypes, or alternatively users could just copy the code for those two types & add the mimetype manually themselves.

**Comment by glanderson42** [comment]
Hi @42triangles 
I'm started working on this, could you provide me some example code for testing?
