### ISSUE TITLE
[Windows 10] build is broken since v0.2.0

### ISSUE THREAD

**Issue by JoeyAcc** [SergioBenitez/Rocket#248]
Hello, and thanks for opening a new issue about Rocket!

Before opening your issue, we ask that you search through existing issues and
pull requests to see if your bug report, concern, request, or comment has
already been addressed. Ensure to search through both open and closed issues and
pull requests. If this is a question, feature request, or general comment,
please ensure that you have read the relevant sections of the documentation
before posting your issue. Finally, consider asking questions on IRC or Matrix
before opening an issue.

If you feel confident that your issue is unique, please include the following
information, selecting the category that best describes your issue:

## Bug Reports

Bug reports _must_ include:

  1. The version of Rocket you're using. Ensure it's the latest, if possible. `The bug is present in Rocket v0.2.0 and up. Haven't tried 0.1.x.`

  2. A brief description of the bug that includes:
    * The nature of the bug:  `Compiler error`
    * When the bug occurs: `When trying to compile my Rocket-based project.`

    * What you expected vs. what actually happened: `Expected successful compile, got a compile error.`

  3. How you discovered the bug. Short test cases are especially useful. `Trying to compile a project based on Rocket on windows 10.`

  4. Ideas, if any, about what Rocket is doing incorrectly: `A source error, since I get a compile error. Specifically, rocket_codegen fails to compile.`

Below is the error log:

````
joey@DESKTOP-P4V3PIP MINGW64 ~/WebstormProjects/sbr-validate-ws (master)
$ cargo update && cargo build
    Updating git repository `https://github.acc.nl/AcceptDevelopmentBV/sbr-xquery-interpreter-api`
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.acc.nl/AcceptDevelopmentBV/sbr-xquery-parser-api`
   Compiling rocket_codegen v0.2.0
error[E0432]: unresolved import `syntax::codemap::spanned`
  --> C:\Users\Joey\.cargo\registry\src\github.com-1ecc6299db9ec823\rocket_codegen-0.2.0\src\utils\mod.rs:20:23
   |
20 | use syntax::codemap::{spanned, Span, Spanned, DUMMY_SP};
   |                       ^^^^^^^ no `spanned` in `codemap`. Did you mean to use `Spanned`?

error: no field `value` on type `&syntax::ast::Attribute`
   --> C:\Users\Joey\.cargo\registry\src\github.com-1ecc6299db9ec823\rocket_codegen-0.2.0\src\lints\mod.rs:234:30
    |
234 |                 true => attr.value.meta_item_list().and_then(|list| list[0].name())
    |                              ^^^^^

error[E0023]: this pattern has 1 field, but the corresponding tuple variant has 2 fields
   --> C:\Users\Joey\.cargo\registry\src\github.com-1ecc6299db9ec823\rocket_codegen-0.2.0\src\lints\utils.rs:163:57
    |
163 |                 | Def::Local(id) | Def::Upvar(id, ..) | Def::Macro(id) => Some(id),
    |                                                         ^^^^^^^^^^^^^^ expected 2 fields, found 1

error: aborting due to 2 previous errors

error: Could not compile `rocket_codegen`.

To learn more, run the command again with --verbose.

````

Feel free to comment at will. We simply ask that your comments are well
constructed and actionable. Consider whether IRC or Matrix would be a better
venue for discussion.

**Comment by SergioBenitez** [comment]
The build isn't broken. We make sure no release ever includes a broken build!

You're using an incompatible version of `rustc` with Rocket. As mentioned in the [getting started guide](https://rocket.rs/guide/getting-started/#nightly-version), you need the latest version of `rustc` and `rocket`. Please use the latest nightly, currently `rustc 1.18.0-nightly (91ae22a01 2017-04-05)`, and the latest `rocket`, currently `0.2.4`.

**Comment by SergioBenitez** [comment]
Closing this issue out. If the above doesn't fix things for you, I'm happy to reopen.

**Comment by JoeyAcc** [comment]
This bug is not invalid. I just tried recompiling with the nightly compiler from yesterday:
````
$ rustc -V
rustc 1.18.0-nightly (ad36c2f55 2017-04-09)
````

I still get the same error when the compiler tries to compile `rocket_codegen`.

**Comment by SergioBenitez** [comment]
Are you using the latest version of `rocket` and `rocket_codegen`?

**Comment by JoeyAcc** [comment]
Thanks for the quick reply.

I just had a look in the Cargo.toml in my project. Turns out the dependencies were set using `rocket_codegen = "0.2.0"` rather than `rocket_codegen = "0.2"`. Not sure how that ended up in there, but that made the difference as Cargo interprets the former as an exact match apparently.

So when all's said and done Rocket works as advertised :)
