### ISSUE TITLE
release profile on build fails to produce a functioning binary

### ISSUE THREAD

**Issue by JurrianFahner** [SergioBenitez/Rocket#2490]
**Description**

When I run `cargo build` and run the binary, everything works as expected.

However if I run `cargo build --release` the artifact seems to hang and fails to startup the rocket server. 

**To Reproduce**

How to reproduce the bug. A fully working code example (`main.rs` + `Cargo.toml`) is preferred.

```rust
#[macro_use] extern crate rocket;

#[get("/")]
fn index() -> &'static str {
    "Hello, world!"
}

#[launch]
fn rocket() -> _ {
    rocket::build().mount("/", routes![index])
}
```

```toml
[package]
name = "hello-world-rocket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.2"
```

```bash
# first run the build
cargo build --release

# run the binary
./target/release/hello-world-rocket
```

**Expected Behavior**

We need to see something like the following:
```
🔧 Configured for debug.
   >> address: 127.0.0.1
   >> port: 8000
   >> workers: 12
   >> ident: Rocket
   >> limits: bytes = 8KiB, data-form = 2MiB, file = 1MiB, form = 32KiB, json = 1MiB, msgpack = 1MiB, string = 8KiB
   >> temp dir: /tmp
   >> http/2: true
   >> keep-alive: 5s
   >> tls: disabled
   >> shutdown: ctrlc = true, force = true, signals = [SIGTERM], grace = 2s, mercy = 3s
   >> log level: normal
   >> cli colors: true
📬 Routes:
   >> (index) GET /
📡 Fairings:
   >> Shield (liftoff, response, singleton)
🛡️  Shield:
   >> X-Frame-Options: SAMEORIGIN
   >> Permissions-Policy: interest-cohort=()
   >> X-Content-Type-Options: nosniff
🚀 Rocket has launched from http://127.0.0.1:8000
```

**Environment:**

 - OS Distribution: Ubuntu 20.04.5
 - Kernel: 5.15.90.1-microsoft-standard-WSL2
 - WSL version: 1.1.3.0
 - Rocket Version: 0.5.0-rc.2

**Work around**

By adding the following snippet to the `Cargo.toml`, the build succeeds:

```toml
[profile.release]
debug-assertions = true
```

The default value for release profile should be false, for the debug profile it should be set to true. 
See also [cargo book](https://doc.rust-lang.org/cargo/reference/profiles.html).

**Comment by robertwayne** [comment]
Are you sure your binary was non-functioning? Did you test the server responded?

By default, Rocket will only log critical messages in release mode. You can set `log_level="normal"` in the `Rocket.toml` file to change this behavior to what you are expecting.

**Comment by JurrianFahner** [comment]
@robertwayne Thanks for your answer. I thought that I had tested it, but maybe on a wrong port (in hindsight).

You are right that I could have read it in the manual. 

Issue is hereby resolved.
