### ISSUE TITLE
Cannot build due to error in devise_codegen-0.3.1

### ISSUE THREAD

**Issue by fadmaro-code** [SergioBenitez/Rocket#2491]
**Description**

Trying to build the example from getting started page but it failed with the following error.

```
error[E0282]: type annotations needed for `(&devise_core::syn::Ident, U)`
  -->~/.cargo/registry/src/github.com-1ecc6299db9ec823/devise_codegen-0.3.1/src/lib.rs:56:25
   |
56 |                     let (ident, span) = (f.ident.as_ref().unwrap(), f.span().into());
   |                         ^^^^^^^^^^^^^
   |
help: consider giving this pattern a type, where the placeholders `_` are specified
   |
56 |                     let (ident, span): (&devise_core::syn::Ident, U) = (f.ident.as_ref().unwrap(), f.span().into());
   |                                      +++++++++++++++++++++++++++++++

For more information about this error, try `rustc --explain E0282`.
error: could not compile `devise_codegen` due to previous error
warning: build failed, waiting for other jobs to finish...

```

**To Reproduce**

1. Create a new project with `cargo new hello-rocket`
2. Add `rocket = "0.5.0-rc.2"` as dependency in Cargo.toml
3. Execute `cargo build`

**Expected Behavior**

Should have build.

**Environment:**

 - Archlinux 6.2.5-arch1-1
 - Rocket Version: 0.5.0-rc.2
 - Cargo: cargo 1.68.0 (115f34552 2023-02-26)

**Additional Context**

Also tried to run hell-rocket example in Ubuntu 18.04.6 LTS but got the same result.

**Comment by longkezhe** [comment]
Specify  proc-macro2 version on Cargo.toml.

[dependencies]
proc-macro2 = "<= 1.0.51"

**Comment by ykwd** [comment]
We have encountered the same problem. It seems like this issue is caused by an upgrade of proc-macro2 from 1.0.51 to 1.0.52. And proc-macro2 is used in  devise_codegen.
So a quick fix is to add the following line to the cargo.toml of your project:
proc-macro2 = "= 1.0.51"
This sets the version of proc-macro2 to be exactly 1.0.51

**Comment by ykwd** [comment]
> I find it funny how this is the second time while toying around with a new project that a dependency has broken only hours before I wanted to use it (the other one being diesel/quote). Does this happen often?

When using xxx = "0.1.12", the string "0.1.12" is a version requirement. Although it looks like a specific version of the time crate, it actually specifies a range of versions and allows [SemVer](https://semver.org/) compatible updates. (https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html)

To avoid such issues, perhaps one's project and the project's dependencies shall all use xxx = "= 0.1.12" to fixate the version number, which is very difficult as how the project's dependencies import their dependencies is out of one's control.

**Comment by fadmaro-code** [comment]
Thank you longkezhe and ykwd, that worked.
