### ISSUE TITLE
Documentation Incorrect

### ISSUE THREAD

**Issue by patientplatypus6** [SergioBenitez/Rocket#2492]
On this page https://api.rocket.rs/v0.5-rc/rocket/response/stream/struct.EventStream.html

```
use rocket::response::stream::{Event, EventStream};;
use rocket::tokio::time::{self, Duration};

#[get("/events")]
fn stream() -> EventStream![] {
    EventStream! {
        let mut interval = time::interval(Duration::from_secs(1));
        loop {
            yield Event::data("ping");
            interval.tick().await;
        }
    }
}
```

Doesn't work. (Returns no result)

```
use rocket::response::stream::{Event, EventStream};
use rocket::tokio::time::Duration;

#[get("/events")]
fn events() -> EventStream![] {
    EventStream! {
        for i in 0..3 {
            yield Event::data(format!("{}", i)).id("cat").event("bar");
            yield Event::comment("silly boy");
        }
    }
}
```

Does, but it returns the entire response all at once.

```
    EventStream! {
        let mut interval = time::interval(Duration::from_secs(1));
        for i in 0..20 {
            yield Event::data(format!("{}", i)).id("cat").event("bar");
            interval.tick().await;
        }
    }
```

This does not work at all. (Empty response).

The issue may be with my axios call on the frontend

```
    const response = await axios({
      method: 'get',
      url: 'http://127.0.0.1:8000/streamrss',
      responseType: 'stream'
    })
    .then(response => {
      const stream = response;
      console.log("value of stream: ", stream);
      // process the stream data
    })
    .catch(error => {
      // handle the error
    });
```

Please ensure that your documentation is correct so that your users can use your framework.

**Comment by robertwayne** [comment]
I can't tell you what the issue is with your axios setup _(never used it)_, but it definitely works with standard JS APIs.

```js
  const source = new EventSource(URL_HERE)
  source.addEventListener("message", (event) => {
      console.log(event)
  })
```

```
message { target: EventSource, isTrusted: true, data: "ping", origin: "http://127.0.0.1:3000/", lastEventId: "", ports: Restricted, srcElement: EventSource, currentTarget: EventSource, eventPhase: 2, bubbles: false, … }
```

(Though I do notice a typo in the first example with an extra colon, making it impossible to compile!)

**Comment by patientplatypus6** [comment]
Yes, I fixed that. It still doesn't work. I'm using svelte on the front end. Here is the code. 

```
<style>
</style>
<script>
  import "../main.css"
  import axios from 'axios';
  import Linkbar from '../../components/linkbar.svelte';
  import { onMount } from 'svelte';

  let api_data = [];

  onMount(async () => {
    // const response = await axios({
    //   method: 'get',
    //   url: 'http://127.0.0.1:8000/streamrss',
    //   responseType: 'stream'
    // })
    // .then(response => {
    //   const stream = response;
    //   console.log("value of stream: ", stream);
    //   // process the stream data
    // })
    // .catch(error => {
    //   // handle the error
    // });

    const source = new EventSource(`http://127.0.0.1:8000/streamrss`)
    source.addEventListener("data", (event) => {
        console.log(event)
    })

    // const stream = response.data;

    // stream.on('data', data => {
    //     console.log('inside on stream')
    //     console.log(data);
    // });

    // stream.on('end', () => {
    //     console.log("stream done");
    // });
  })
</script>

<Linkbar/>
<div>
  RSS goes here
</div>
```

```
#[get("/")]
fn streamrss() -> EventStream![] {
    EventStream! {
        let mut interval = time::interval(Duration::from_secs(1));
        loop {
            yield Event::data("ping");
            interval.tick().await;
        }
    }
}
```

```
GET /streamrss text/event-stream:
   >> Matched: (streamrss) GET /streamrss/
inside streamrss
   >> Outcome: Success
   >> Response succeeded.
   >> Response succeeded.
```

And the error in the terminal for the front-end - 

`The connection to http://127.0.0.1:8000/streamrss was interrupted while the page was loading. [+page.svelte:26:16](http://localhost:5173/src/routes/rss/+page.svelte)`

Perhaps this doesn't work on onload? As far as the Axios library is concerned, it doesn't look like it works because it's designed to accept the entire response at once. I understand that this isn't technically part of the Rocket.rs ecosystem, but can you take a look at this and tell me how it's supposed to be implemented on a WillMount-esque method - I presume this would also be a problem in React.

**Comment by patientplatypus6** [comment]
That's on loading the page in the browser window - if I navigate to the page there is no error, but the page doesn't show any data either. I've used "message" and "data" in the listener method. Neither displays anything. Can you post your code so I can verify that it works on my computer?

**Comment by patientplatypus6** [comment]
<img width="1274" alt="Screenshot 2023-03-15 at 3 43 22 PM" src="https://user-images.githubusercontent.com/60800027/225459776-0f3ac465-adea-4779-99d7-b8d85b7797da.png">

Screenshot

**Comment by patientplatypus6** [comment]
<img width="1255" alt="Screenshot 2023-03-15 at 3 44 02 PM" src="https://user-images.githubusercontent.com/60800027/225459877-91363560-b3e8-4b8c-a969-eef5a6aa06c5.png">

**Comment by patientplatypus6** [comment]
<img width="1501" alt="Screenshot 2023-03-15 at 3 45 05 PM" src="https://user-images.githubusercontent.com/60800027/225460064-e3e7d93e-9548-4201-801f-041c9792c9df.png">

**Comment by robertwayne** [comment]
I think this is a Firefox specific issue, see here: https://bugzilla.mozilla.org/show_bug.cgi?id=833462

There is no error on Chrome, but I do see it on my FF Developer Edition as well. I was unable to make it work with just doing cleanup in an `onDestroy(() => source.close())` in Svelte.

The bug report includes this code, which does solve it:

```svelte
<script lang="ts">
    import { onMount } from "svelte"

    onMount(async () => {
        const source = new EventSource("http://127.0.0.1:3000/events")

        source.addEventListener("message", (event) => {
            console.log(event)
        })

        window.addEventListener("beforeunload", () => {
            source.close()
        })
    })
</script>

<div class="flex flex-col items-center" />
```

**Comment by patientplatypus6** [comment]
That's not in the documentation from what I see. 

<img width="1507" alt="Screenshot 2023-03-15 at 3 57 54 PM" src="https://user-images.githubusercontent.com/60800027/225461714-f7e61cca-e94b-4889-ae09-998d1bffff51.png">

<img width="1505" alt="Screenshot 2023-03-15 at 3 57 44 PM" src="https://user-images.githubusercontent.com/60800027/225461728-afb7b8d7-84e3-45ba-a1b3-3e6407765541.png">

<img width="1506" alt="Screenshot 2023-03-15 at 3 57 22 PM" src="https://user-images.githubusercontent.com/60800027/225461747-104205ea-1fec-4241-918f-4887798dc21c.png">

And closing the source on the event listener didn't change anything on my frontend. It doesn't make any sense to me why it would - closing the source on the window object would just close an open source, it should still display the message. 

I've tested this on chrome - it doesn't work. 

<img width="1512" alt="Screenshot 2023-03-15 at 4 00 22 PM" src="https://user-images.githubusercontent.com/60800027/225462108-f032f759-ddaf-4361-9285-3ed714f8aea2.png">

Can you provide a screenshot? I'm having a hard time believing in your sincerity.

**Comment by patientplatypus6** [comment]
I've added a stackoverflow link: https://stackoverflow.com/questions/75750777/cant-return-data-from-a-rust-rocket-stream-to-frontend

**Comment by robertwayne** [comment]
![Screenshot_2023-03-15_19-03-17](https://user-images.githubusercontent.com/13954303/225462376-fb0f118e-e3c9-4d7a-bcdc-06cb2cbb7c84.png)

I pushed an example branch with my code: https://github.com/robertwayne/template-rocket-svelte-spa/tree/sse-test

**Comment by patientplatypus6** [comment]
Now it works. I have no idea what was going on. I'm so used to hot reloading that it may have been a problem with me reloading the server. I'll have to look into a hot reloading module for rocket. Thanks for taking a look for me - this may be of help to other people.

**Comment by robertwayne** [comment]
Well, nothing stands out immediately as being an issue. Is Rocket receiving a GET request for the endpoint at all in your logs?

Can you use `curl` to make a request to your SSE endpoint?

**Comment by patientplatypus6** [comment]
Yes, the curl works and then it works and now both examples work. I don't know for certain, but I would hazard a guess that the reason that this was failing intermittently was because I was force shutting down the server and the SIGINT wasn't being properly terminated. Maybe. Thanks!

**Comment by SergioBenitez** [comment]
Looks like this was resolved. Happy to see it!
