### ISSUE TITLE
Outbound HTTPS request

### ISSUE THREAD

**Issue by rohitjoshi** [SergioBenitez/Rocket#250]
Hello,
  One of the requirements we have is to validate an OAuth token against the OAuth server via HTTPS call.  How do I invoke outbound https request?

Thanks,

**Comment by kybishop** [comment]
You'll need to use a crate that impliments http requests; outbound requests are out of the scope of rocket. [Reqwest](https://github.com/seanmonstar/reqwest) is great for this.

**Comment by SergioBenitez** [comment]
At this time, Rocket only provides an HTTP and not a client. As mentioned by @kybishop, you can use other libraries, such as [reqwest](https://github.com/seanmonstar/reqwest), to accomplish this.

**Comment by alper** [comment]
I can't figure out the signature, Rocket does not seem to like this: `fn gmap() -> Result<String, reqwest::Error> {`

**Comment by somehowchris** [comment]
If you implement the type `Responder` for each of the types it’s going to work

**Comment by alper** [comment]
This is what the documentation says:

> If the error type E does not implement Responder, then the error is simply logged to the console, using its Debug implementation, and a 500 error is returned to the client.

I can't really square that with having to implement Responder for this.

**Comment by blackghost1987** [comment]
I'm not really sure why we have this conversation going in two places at once, but I'm copying the result of my investigation here from https://github.com/SergioBenitez/Rocket/discussions/2068
```
In Rocket v0.5, `Result<T, E>` implements `Responder` only if `E` implements `Responder`.
For the previous behavior, use `Result<T, Debug<E>>` where `Debug` is `rocket::response::Debug`."
```
I think this issue should not be continued further, this problem is mostly unrelated to the original issue, which should have been a discussion anyway.
