### ISSUE TITLE
Regress always logged final launch message introduced in rc3

### ISSUE THREAD

**Issue by Directory** [SergioBenitez/Rocket#2507]
In the 0.5 rc3 change log
> Final launch messages are now always logged, irrespective of profile.

Why? Who asked for this? What reasoning is there behind always having stdout noise that I did not explicitly opt in? The reason I run `LogLevel::Critical` in my config is because rocket is not the main program being executed in my rust project, it's conditionally executed and I do not want its stdout interfering with my other logging (getting in the way looking ugly).

Also the implementation isn't even correct. I have the address set to `0.0.0.0` which causes the printed out log to say `Rocket has launched from http://0.0.0.0:8000` which isn't even a valid endpoint to connect to from localhost. And even then presenting this http link assumes there's even an endpoint mounted on the root `/` which in my case there isn't. 

Point is this printed out message is pointless, and I would prefer setting `LogLevel::Critical` actually log critical info only and not a glorified watermark.

**Comment by SergioBenitez** [comment]
The problem with not emitting anything at all is that folks think the server is stuck/broken/doing nothing, or don't know what their server is bound to. Here are some issues illustrating this:

  * https://github.com/SergioBenitez/Rocket/issues/1469
  * https://github.com/SergioBenitez/Rocket/issues/1478
  * https://github.com/SergioBenitez/Rocket/issues/2174
  * https://github.com/SergioBenitez/Rocket/issues/1457
  * https://github.com/SergioBenitez/Rocket/issues/1811

> Also the implementation isn't even correct. I have the address set to `0.0.0.0` which causes the printed out log to say `Rocket has launched from http://0.0.0.0:8000` which isn't even a valid endpoint to connect to from localhost. 

We ask the network interface to give us the final address and port that it bound to, and we print that. `0.0.0.0` _is_ a valid address.

> And even then presenting this http link assumes there's even an endpoint mounted on the root `/` which in my case there isn't.

I don't think so. We're just saying there's a server running there, which there is. If you make an HTTP request to that URL, the server responds. Maybe it's a 404, maybe it's a customized 404, but it still responds.

> Point is this printed out message is pointless, and I would prefer setting `LogLevel::Critical` actually log critical info only and not a glorified watermark.

I think avoiding all of the issues above is worthwhile. You might be completely aware of what your server is bound to, and that it's running, but clearly other folks would have benefitted from the log message. If you _really_ want to filter out the log message, install a [custom logger[(https://docs.rs/log/latest/log/#implementing-a-logger) and filter out `rocket::launch` messages. This should ideally be easier and more obvious once we finally land #21.
