### ISSUE TITLE
master fails with `undefined symbol: GFp_RAND_bytes` on NixOS

### ISSUE THREAD

**Issue by flosse** [SergioBenitez/Rocket#251]
Tested with
    - rustc:
        - `1.18.0-nightly (91ae22a01 2017-04-05)`
        - `1.18.0-nightly (2564711e8 2017-04-04)`
    - rocket 982997db
    - cargo `0.19.0-nightly (4e95c6b41 2017-03-23)`

The `main.rs` looks like this:
```rust
#![feature(plugin,custom_derive)]                                                                                                                                      
#![plugin(rocket_codegen)]
#![allow(unmanaged_state)]

extern crate rocket;
extern crate rocket_contrib;

fn main() {
    println!("Hello, world!");
}
```
Running `cargo build` tells me this:

```
...
error: /home/mk/dev/rocket-nightly-bug/target/debug/deps/librocket_codegen-cd9174ccf3d9f83e.so: undefined symbol: GFp_RAND_bytes
 --> src/main.rs:2:11
  |
2 | #![plugin(rocket_codegen)]
  |           ^^^^^^^^^^^^^^

error: Could not compile `rocket-nightly-bug`.
```
This seems to be related to `ring`:
https://github.com/briansmith/ring/blob/e9cd812d10f241c115575e5b7b2cb3e20bbec0a6/src/rand.rs#L263

`ring` itself is used by `cookie` but downgrading `cookie` to `v0.7.2` doesn't help  :(

**Comment by flosse** [comment]
>Which OS?

```
uname -a
Linux lenovo-t440s 4.9.17 #1-NixOS SMP Wed Mar 22 11:44:07 UTC 2017 x86_64 GNU/Linux
```

> Can you try creating a new project and depending only on Ring to see if this is indeed an issue with Ring?

compiling `ring v0.7.3` works :-\

**Comment by flosse** [comment]
even cookies can be compiled with ring
```toml
[dependencies]
cookie = { version = "*", features=["secure", "percent-encode"] }
```

**Comment by SergioBenitez** [comment]
I can't replicate on any of three machines and two different operating systems. Maybe there's something nondeterministic in `ring`'s build; that symbol comes from C code. I believe `ring` has had changes to its build system recently. Can you say one way or another, @briansmith?

Can you try `cargo clean` and `cargo build` in the original project and see if that fixes things?

**Comment by flosse** [comment]
> Can you try `cargo clean` and `cargo build` in the original project and see if that fixes things?

No, it's still there :(
So it seems to be something NixOS specific :-\
Anyway, thanks for trying to reproduce the bug!

**Comment by flosse** [comment]
There seems be a difference between the released crate and the git crate.
If I declare `rocket = "0.2.4"` within `Cargo.toml` it works fine
but if I use `rocket = { git = "..." }` it fails.
Using `ring = { git = "..." }` or `cookie = { git = "..." }` in a project  is working as well as the crate.io versions.

**Comment by SergioBenitez** [comment]
There are _many_ differences between the two versions. The `master` branch is the development branch. It is in no way meant to be stable.

**Comment by flosse** [comment]
I see.... I'm just confused because the commit message `New version: 0.2.4.` in f57d984e2e544dfd2cae6b662f4c9ad87f277ea2 is quite different from the tag `0.2.4` 355da8a1ba7ffbd4b6f3edfc384282e51980d9f1 right?

**Comment by flosse** [comment]
I still don't understand it :(
This works:
```
git clone https://github.com/SergioBenitez/Rocket/
cd Rocket/
git checkout 982997d
cd lib/
cargo build
cd ..
cd codegen/
cargo build
...
```
But linking the same commit (982997d) as dependency in a project doesn't work :(

**Comment by SergioBenitez** [comment]
Indeed. Commits are cherry-picked from `master` into a stable branch for every release after the stable version has branched off. After this point, when master says `New version: 0.2.4.`, it doesn't mean that this is the point in history where the version was cut from, it's just the change that introduced the version number into the codebase.

Can you hop on IRC so we can try to debug this? I've spin up a NixOS VM and am compiling Rocket now.

**Comment by SergioBenitez** [comment]
Okay, after some debugging, it's become fairly clear that issue is almost certainly with `rustc` on NixOS. This is based on the following facts:

  * The problem appears to only present itself on NixOS.
  * `rocket` and `rocket_codegen` compile properly on NixOS.
  * A crate that depends on `rocket` compiles properly on NixOS.
  * A crate that depends on `rocket` and `rocket_codegen` compiles properly on NixOS _if `#[plugin(rocket_codegen)]` is not used in the crate.

I'll be opening an issue on the `rustc` issue tracker to discuss this with Rust developers further.

**Comment by flosse** [comment]
Thanks a lot!

**Comment by briansmith** [comment]
See https://github.com/briansmith/ring/commit/d51e389673277acd6733de0b136d33e79967e4f9. If the problem was the declared-but-undefined-and-unused function, it will be fixed in *ring* 0.7.4.

**Comment by SergioBenitez** [comment]
@briansmith I think that commit will fix this issue, however I believe there's still an underlying issue with `rustc` here. I describe it further in https://github.com/rust-lang/rust/issues/41128.

**Comment by flosse** [comment]
yes, ring `0.7.4` works for me :)

**Comment by SergioBenitez** [comment]
Since we can avoid the problem by using `ring 0.7.4`, I've updated `cookie` (https://github.com/alexcrichton/cookie-rs/commit/cc071a0682316d058c0b277ba68fe8539c63e717) and `rocket` (https://github.com/SergioBenitez/Rocket/commit/a2a0aab541d2b64716381cf55c19bd302cf73b6e) approapriateiy. Since the `rustc` issue no longer affects Rocket, I'm closing this out.
