### ISSUE TITLE
Reconsider URI normalization

### ISSUE THREAD

**Issue by SergioBenitez** [SergioBenitez/Rocket#2512]
At present, Rocket considers the following URLs equivalent and will often normalize to the first variant:

1. `https://rocket.rs/foo`
2. `https://rocket.rs/foo/`
3. `https://rocket.rs/foo/?`

RFC#3986 [6.2.2](https://www.rfc-editor.org/rfc/rfc3986#section-6.2.2) describes the types of normalization that should result in equivalent URIs. Comparing the guidelines in the RFC with the examples above, we conclude that while Rocket is not violating the RFC, it also isn't following the RFC's advice. In particular, the RFC states:

> In general, a URI that uses the generic syntax for authority with an empty path should be normalized to a path of "/".

~~This means that the first variant (`https://rocket.rs/foo`) should be normalized to the second (`https://rocket.rs/foo/`) whereas Rocket actually performs the inverse.~~ correction: This isn't stated by the RFC, but the RFC does mention that `/foo` and `/foo/` _may_ be equivalent, not _should_, so performing the normalization in the inverse isn't necessarily correct. The RFC further states:

> For example, the URI "http://example.com/?" cannot be assumed to be equivalent to any of the examples above.

Given that the examples the RFC refers to include `http://example.com`, we can conclude that Rocket is also not following this guideline: it normalizes the third variant (`https://rocket.rs/foo/?`) above to the first (`https://rocket.rs/foo`).

This is problematic, not only because we're not following the guidelines in the RFC, but also because other servers may not be either. This means that even though considering `https://rocket.rs/foo/` and `https://rocket.rs/foo` equivalent is  strictly correct as far as the RFC goes, other servers may disagree. And since the `uri!()` macro performs normalization automatically, this can result in a frustrating case where a user can't comfortably use the `uri!()` macro to construct the needed URI to an external resource.

My recommendation is that Rocket continue to perform normalization, but limited to mutations that are extremely unlikely to cause issues in the wild. In particular, Rocket should only remove empty segments in the _middle_ of a component and apply _no further normalization_. Here are examples of applying this rule:

These remain unchanged after normalization, unlike before:

* `https://rocket.rs/foo`
* `https://rocket.rs/foo/`
* `https://rocket.rs/foo/?`
* `/a/b/`
* `/?&foo&` -> `/?&foo&`
* `/?foo&` -> `/?foo&`

These are still normalized, but more conservatively:

* `https://rocket.rs/foo//?` -> `https://rocket.rs/foo/?`
* `https://rocket.rs/.././foo//?` -> `https://rocket.rs/foo/?`
* `https://rocket.rs/.././foo/../?` -> `https://rocket.rs/?`
* `https://rocket.rs/.././foo/../../?` -> `https://rocket.rs/?`
* `/a/ab//c//d/` -> `/a/ab/c/d/`
* `/?a&&b` -> `/?a&b`
* `/?a&&b&` -> `/?a&b`
* `/?&` -> `/?&`

Some URIs normalize just like before:

* `//` -> `/`
* `///` -> `/`
* `/a/ab//c//d` -> `/a/ab/c/d`
* `/a/ab//c//d?foo` -> `/a/ab/c/d?foo`

<sup>According to [whatwg on form-urlencoded](https://url.spec.whatwg.org/#application/x-www-form-urlencoded), we can be significantly more aggressive with normalizing query strings, if desired.</sup>

We should explore making this change sooner than later.

**Comment by fenhl** [comment]
> > In general, a URI that uses the generic syntax for authority with an empty path should be normalized to a path of "/".
> 
> This means that the first variant (`https://rocket.rs/foo`) should be normalized to the second (`https://rocket.rs/foo/`) whereas Rocket actually performs the inverse.

This is not what that means. “Path” here means the entire path, not an individual segment. In your examples, the paths are `/foo` and `/foo/`, neither of which are empty. I haven't read the entire RFC but at a glance it doesn't seem to prescribe a normalization between `/foo` and `/foo/` or even treating them as equivalent (though [section 6.2.4](https://www.rfc-editor.org/rfc/rfc3986#section-6.2.4) notes that redirecting from one to the other may cause clients to treat them as equivalent in the future). So not normalizing here is not only something that appears in the wild but also compliant, and one more reason to make this change. (Though it may be confusing for users, but that's not our problem if I understand correctly that this issue is only about external URIs and not about Rocket's router.)

**Comment by SergioBenitez** [comment]
> This is not what that means. “Path” here means the entire path, not an individual segment.

You're absolutely right. I've amended the issue text to recognize this.

> So not normalizing here is not only something that appears in the wild but also compliant, and one more reason to make this change.

Agreed! See https://github.com/SergioBenitez/Rocket/tree/new-uri-normalization where I've implemented this.
