### ISSUE TITLE
Make `FormFrom` a separate crate.

### ISSUE THREAD

**Issue by Tomperez98** [SergioBenitez/Rocket#2516]
**Existing Functionality**

Currently, the trait `FromForm` is part of the API framework. But the data validation functionality comes really handy for other types of applications such as (CLI) applications.

**Suggested Changes**

Move the `FromForm` trait a a separate crate so the logic can be used for different types of applications, other than APIs.

This would be similar to the core functionality `Pydantic` provides. `Pydantic + FastAPI` is a great combination, but the validation logic `Pydantic` provides can be used even if `FastAPI` is not installed

**Comment by SergioBenitez** [comment]
The `FromForm` trait is very specific to Rocket. The validation parts are somewhat specific to Rocket but could be extracted out. I think that would be great, but doing so isn't really within the scope of the Rocket project itself, so I'm closing this issue. Feel free (of course!) to take any of the code and transform it into an external crate!
