### ISSUE TITLE
dockerized app just outputs Hello, world! and exits.

### ISSUE THREAD

**Issue by alekspickle** [SergioBenitez/Rocket#2518]
### Discussed in https://github.com/SergioBenitez/Rocket/discussions/2517

<div type='discussions-op-text'>

<sup>Originally posted by **alekspickle** April 11, 2023</sup>
I have a more or less [simple template](https://github.com/alekspickle/rocket-template) and simple `cargo run` works like a charm but when I build docker image and try to run it I get:

```
docker build -t rocket-template:local .
docker run --rm -it -p 8000:8000 --hostname test-rocket --name test-rocket rocket-template:local
Hello, world!

```
I am so confused.
I have a multistage dockerfile to leverage build time and debian slim image so that the resulting image would be as small as possible.

I read all relatable issues and discussions I could find. I don't get where the hell this hello world could be, it is definitely not in my project.
AFAIK the common issues are Rocket.toml and some proxies, but in my case I want at least run the simple server in docker locally for start, and I most certainly do COPY it to the last stage image.

Any ideas?</div>

**Comment by SergioBenitez** [comment]
Let's keep this in the discussion.
