### ISSUE TITLE
#[get("/")] - needles_pass_by_value - lint

### ISSUE THREAD

**Issue by drusellers** [SergioBenitez/Rocket#252]
Using Rocket `0.2.4`
Clippy `0.0.122`

```
rustc 1.18.0-nightly (666e7148d 2017-04-08)
cargo 0.19.0-nightly (472917504 2017-04-01)
```

```
warning: this argument is passed by value, but not consumed in the function body
   --> src/features/accounts/users.rs:233:5
    |
233 |     #[get("/")]
    |     ^^^^^^^^^^^
    |
    = note: #[warn(needless_pass_by_value)] on by default
help: consider taking a reference instead
    |     &#[get("/")]
    = help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#needless_pass_by_value
```

I'm not exactly sure if I should add the `&` to my attribute? Or is this a _thing_ that Rocket wants to fix. I'm mounting my routes using the vector patterns described here: https://github.com/SergioBenitez/Rocket/issues/174

**Comment by SergioBenitez** [comment]
Clippy is giving a bogus help message: `&#[get("/")]` is not valid syntax. :D 

Clippy is referring to code generated by the attribute which may either be code that you wrote or code that Rocket generates. What is the signature of your handler? The lint fires when you ask for something by value (`T`) but only ever use `&T` in the function.

**Comment by drusellers** [comment]
```
    #[get("/<handle>")]
    fn single_handle(handle: String) -> Result<Option<JSON<Plan>>, ()> {
        let env = AppEnv::new();
        let repo = Plans::new(&env);


        match repo.find(&handle) {
            Ok(Some(item)) => Ok(Some(JSON(item))),
            Ok(None) => Ok(None),
            Err(_) => Err(()),
        }
    }
```

That's pretty much what is going on. Can I do `&str` with Rocket? I didn't even think about that.

**Comment by drusellers** [comment]
```
    /// Basic HTTP Route to confirm host is working
    #[get("/")]
    fn handle(env: State<AppEnv>) -> Result<JSON<Vec<RoutingData>>, ()> {
        let routes = routing::list(&env);

        Result::Ok(JSON(routes))
    }
```

also gets

```

warning: this argument is passed by value, but not consumed in the function body
   --> src/features/routing/mod.rs:152:20
    |
152 |     fn handle(env: State<AppEnv>) -> Result<JSON<Vec<RoutingData>>, ()> {
    |                    ^^^^^^^^^^^^^
    |
    = note: #[warn(needless_pass_by_value)] on by default
help: consider taking a reference instead
    |     fn handle(env: &State<AppEnv>) -> Result<JSON<Vec<RoutingData>>, ()> {
    = help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#needless_pass_by_value
```

**Comment by SergioBenitez** [comment]
I think this is a poor lint from Clippy, and I would simply disable it. There are valid reasons to take a something by value even if you're only accessing it by reference in the method. Also, it happens that something "looks" like a value but is really a wrapper around a reference, which Clippy will be unaware of.

There's nothing Rocket is doing wrong or could do better here. I think this is an unhelpful lint from Clippy, and I would disable it without hesitation.

**Comment by drusellers** [comment]
Noted! :) Thanks for taking a look.


`#[allow(needless_pass_by_value)]`
