### ISSUE TITLE
Dynamic Parameters inconsistent with doc

### ISSUE THREAD

**Issue by ZiJiaW** [SergioBenitez/Rocket#2527]
**Description**

In the official doc, for `GET` method with query params, it gives something like this:

<img width="756" alt="image" src="https://user-images.githubusercontent.com/31954700/233243708-ec358e42-9383-439f-9f74-14be2ce74bc5.png">

```
#[get("/xx/?<name>")]
fn hello(name: &str, color: Vec<Color>, person: Person<'_>, other: Option<usize>) {
    .....
}
```
But in my practice, this gives an error, shows `error: route URIs cannot contain empty segments`

I replace it with `#[get("/xx?<name> ")]`, and it's ok now.

So it turns out that the last slash must be removed, which is inconsistent with the doc.

This is confusing, is this a BUG?

**Environment:**
In ubuntu 20.04, with rocket version 0.5.0 rc.3

**Comment by ZiJiaW** [comment]
OK, turns out that depends: `#[get("/?<name>")]` is right, `#[get("?<name>")]` is wrong, `#[get("/xx/?<name>")]` is wrong, `#[get("/xx?<name>")]` is right

**Comment by SergioBenitez** [comment]
This isn't a bug, but it can be confusing. These rules were changed recently on master, which would allow the route you indicate. See #2512.
