### ISSUE TITLE
Unable to specify multiple routes at root path

### ISSUE THREAD

**Issue by seenickcode** [SergioBenitez/Rocket#2531]
**Description**

Hi there. I'm a newcomer to Rocket and am having a hard time setting up a few routes at root, after reading this documentation: [mounting](https://rocket.rs/v0.5-rc/guide/overview/#mounting).

I'd like to be able to set up the following routes, yet the documentation does not seem to clearly state (at least to me) how to do this.

```
/
/foo
```

**To Reproduce**

```
#[macro_use] extern crate rocket;

#[get("/")]
fn index() -> &'static str {
    "Hello, world!"
}

#[get("/foo")]
fn foo() -> &'static str {
    "foo"
}

#[launch]
fn rocket() -> _ {
    rocket::build()
        .mount("/", routes![index])
        .mount("/foo", routes![foo])
}
```

**Expected Behavior**

The following routes get mounted:

```
/
/foo
```

**Observed Behavior**

The following routes are mounted instead:

```
/
/foo/foo
```

**Environment:**

 - macOS 13.3.1
 - Rocket Version: 0.5.1-rc3

**Additional Context**

The docs on [mounting](https://rocket.rs/v0.5-rc/guide/overview/#mounting) do not quite cover this use case (from what I can tell). What if I wanted to simple set up a number of routes like this? 

Thank you.

**Comment by SergioBenitez** [comment]
It's the second list item in that section:

> The mount method takes as input:
> 1. A base path to namespace a list of routes under, here, /hello.
> 2. A list of routes via the routes! macro: here, routes![world], with multiple routes: routes![a, b, c].

So you'd want: `.mount("/", routes![index, foo])`.

**Comment by seenickcode** [comment]
Hi @SergioBenitez, thank you for your quick reply.

`.mount("/", routes![index, foo])` yields routes:

```
📬 Routes:
   >> (index) GET /
   >> (foo) GET /foo/foo
```

Which is not what I wanted in my Expected Behavior.

Updated code per your suggestion:
```
#[macro_use] extern crate rocket;

#[get("/")]
fn index() -> &'static str {
    "Hello, world!"
}

#[get("/foo")]
fn foo() -> &'static str {
    "foo"
}

#[launch]
fn rocket() -> _ {
    rocket::build()
        .mount("/", routes![index, foo])
}
```

**Comment by SergioBenitez** [comment]
If it does, than that's a rather extreme bug. Are you sure you recompiled and ran the updated code?

**Comment by seenickcode** [comment]
Fixed. I had renamed my project directory but not my package name and my IDE run configuration didn't seem to account for that. Thanks again for your help.
