### ISSUE TITLE
Support mutual authentication over TLS

### ISSUE THREAD

**Issue by SergioBenitez** [SergioBenitez/Rocket#254]
Rocket will support client authentication over TLS. This is a tracking issue.

**Comment by Kmoneal** [comment]
I am looking at implementing MTLS for a project that uses Rocket and wanted to know if I could be pointed in the right direction to start making these modification.

**Comment by SergioBenitez** [comment]
Looks like this will make it in for 0.4, thanks to @Kmoneal and @akuanti. Track progress in https://github.com/SergioBenitez/Rocket/pull/657.

**Comment by SergioBenitez** [comment]
Ah, unfortunately spoke to soon. Pushing to `0.5`, though this could also be in a `0.4` point release.

**Comment by SergioBenitez** [comment]
This is held up in the PR queue. Removing it as a milestone until further progress.

**Comment by faulesocke** [comment]
Can I somehow help with implementing this?

**Comment by SergioBenitez** [comment]
@faulesocke The latest effort is at https://github.com/SergioBenitez/Rocket/pull/1419. Feel free to ping the author and/or takeover.

Note that whatever implementation we go with, it must have the property that MTLS can be enabled and disabled per-route, via a request guard, as well as optionally for the entire application, likely via a fairing.
