### ISSUE TITLE
Cargo warns about future incompatibility with ubyte v0.10.

### ISSUE THREAD

**Issue by andreasklostermaier** [SergioBenitez/Rocket#2540]
"cargo build" on rocket v0.5.0-rc.2 warns about a future incompatability of ubyte v.0.10.1:

```
warning: the following packages contain code that will be rejected by a future version of Rust: ubyte v0.10.1
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`

```

I suggest to update the ubyte dependency to a newer version in the next rocket release.

**Comment by SergioBenitez** [comment]
The latest version of Rocket and `ubyte` are `0.5.0-rc.3` and `0.10.3`, respectively. Running `cargo update` gets you these version, which don't result in the warning you're seeing. There's nothing to do on our end.
