### ISSUE TITLE
Include a FromForm example within the examples/forms.rs

### ISSUE THREAD

**Issue by WarrenN1** [SergioBenitez/Rocket#2561]
An example for how to make a custom FromForm for a custom DataType would be a good idea. The current example only covers using the derives as well as validation methods.
This would be particularly useful for people building ORMs with custom data types or who are trying to enable form handling of custom data types from other libraries (for example parsing the field as a string first and then converting it to the appropriate data type).

**Comment by SergioBenitez** [comment]
Have you seen the [API docs for forms](https://api.rocket.rs/v0.5-rc/rocket/form/trait.FromForm.html) and [form values](https://api.rocket.rs/v0.5-rc/rocket/form/trait.FromFormField.html)? They should collectively cover just about everything there is to know about forms, with plenty of examples.

**Comment by SergioBenitez** [comment]
I'm assuming the API docs answer this question, given the lack of response.
