### ISSUE TITLE
Changing the default launch message

### ISSUE THREAD

**Issue by Stefanuk12** [SergioBenitez/Rocket#2569]
# The problem

You cannot change the launch message *easily* as it's hardcoded as seen [here](https://github.com/SergioBenitez/Rocket/blob/master/core/lib/src/rocket.rs#L695C21-L695C24). You currently have to disable all logging in order to achieve this, but you might want to keep the rest of the logging, and only change the launch message.

# A possible solution

An optional parameter could be passed within the `launch` function which is passed to the logging macro instead of the hardcoded default. An example usage could be like this: 
```rust
rocket.launch("Server started")
```

This may break existing codebases so to minimise this, a function called `launch_with_message` could be used instead.

**Comment by SergioBenitez** [comment]
I don't think we need any explicit APIs to support this. When we get to #21, we should make sure that removing this message is pretty trivial, however. Adding your own message is already trivial via a launch fairing.
