### ISSUE TITLE
Allow directly returning a `Response` from a route

### ISSUE THREAD

**Issue by hwittenborn** [SergioBenitez/Rocket#2570]
**Is your feature request motivated by a concrete problem? Please describe.**

I have an application that functions as a reverse proxy. Likewise, I need it to pass headers from the webserver it ends up calling back to the client, but I haven't been able to find any clean way to do it.

I really like the flexibility that working with a `Response` directly can give - I've managed to do some (but not everything) of what I need to do by wrapping types, but being able to work with a `Response` would be better for me.

**Why this feature can't or shouldn't live outside of Rocket**

I could make a wrapper around `Response` to work with it inside of my route, but then the only thing inside of the struct is the `Reponse`, and I have to manually implement `Responder`, both of which aren't ideal.

There isn't really more than one way to do this either, it's just a matter of adding the `impl Responder` stuff for `Response`.

**Ideal Solution**

See above.

**Alternatives Considered**

I know Rocket's philosophy is to validate as much data as possible (which modifying a `Response` directly doesn't necessarily lend itself to), but being able to have this flexibility when I need it would be preferred, if not required.

**Comment by hwittenborn** [comment]
Now that I think about this, I'm starting to realize I need the same behavior for getting a `Request` directly into a route, as I need to get all the passed headers to pass into the proxied website.

Again, I know Rocket's logic is to validate as much as possible, but I really would like the flexibility I'm wanting when I need it.

I'd even be fine if both of these features were behind a feature flag that was disabled by default, I'd really just like the flexibility to have what I'm needed when I need it.

**Comment by SergioBenitez** [comment]
Have you looked into manual routing? That lets you both get the request and return a response, directly. See the manual routing example.

**Comment by hwittenborn** [comment]
I don't know how I overlooked that, that looks exactly like what I need. Thanks for the quick response, appreciate it a ton!
