### ISSUE TITLE
failed to run custom build command for `pear_codegen v0.1.5` when run the rocket demo example

### ISSUE THREAD

**Issue by happybeta** [SergioBenitez/Rocket#2582]
**Description**

cargo run the demo. 
error: failed to run custom build command for `pear_codegen v0.1.5`

Caused by:
  process didn't exit successfully: `D:\code\rustdemo\rocketdemo\target\debug\build\pear_codegen-90826289a346c49b\build-script-build` (exit code: 101)
  --- stderr
  Error: Pear requires a 'dev' or 'nightly' version of rustc.
  Installed version: 1.71.0 (2023-07-12)
  Minimum required:  1.31.0-nightly (2018-10-05)
  thread 'main' panicked at 'Aborting compilation due to incompatible compiler.', C:\Users\zhangzhile\.cargo\registry\src\index.crates.io-6f17d22bba15001f\pear_codegen-0.1.5\build.rs:24:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `rocket_codegen v0.4.11`

**To Reproduce**

main.rs
```
#[macro_use] extern crate rocket;

#[get("/<name>/<age>")]
fn hello(name: &str, age: u8) -> String {
    format!("Hello, {} year old named {}!", age, name)
}

#[launch]
fn rocket() -> _ {
    rocket::build().mount("/hello", routes![hello])
}
```
cargo.toml
```
[package]
name = "rocketdemo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "=0.4.11"
```

**Expected Behavior**

work fine

**Environment:**

 - Windows 10
 - Rust 1.71.0 (installed by rustup windows)
 - Rocket Version: rocket "0.4.11"

**Additional Context**

## full log
```
error: failed to run custom build command for `pear_codegen v0.1.5`

Caused by:
  process didn't exit successfully: `D:\code\rustdemo\rocketdemo\target\debug\build\pear_codegen-90826289a346c49b\build-script-build` (exit code: 101)
  --- stderr
  Error: Pear requires a 'dev' or 'nightly' version of rustc.
  Installed version: 1.71.0 (2023-07-12)
  Minimum required:  1.31.0-nightly (2018-10-05)
  thread 'main' panicked at 'Aborting compilation due to incompatible compiler.', C:\Users\zhangzhile\.cargo\registry\src\index.crates.io-6f17d22bba15001f\pear_codegen-0.1.5\build.rs:24:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `rocket_codegen v0.4.11`

Caused by:
  process didn't exit successfully: `D:\code\rustdemo\rocketdemo\target\debug\build\rocket_codegen-075ae5fecb37225a\build-script-build` (exit code: 101)
  --- stderr
  Error: Rocket (codegen) requires a 'dev' or 'nightly' version of rustc.
  Installed version: 1.71.0 (2023-07-12)
  Minimum required:  1.33.0-nightly (2019-01-13)
  See the getting started guide (https://rocket.rs/v0.5/guide/getting-started/) for more information.
  thread 'main' panicked at 'Aborting compilation due to incompatible compiler.', C:\Users\zhangzhile\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rocket_codegen-0.4.11\build.rs:29:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to run custom build command for `rocket v0.4.11`

Caused by:
  process didn't exit successfully: `D:\code\rustdemo\rocketdemo\target\debug\build\rocket-ffbde9ecbdad3df0\build-script-build` (exit code: 101)
  --- stderr
  Error: Rocket (core) requires a 'dev' or 'nightly' version of rustc.
  Installed version: 1.71.0 (2023-07-12)
  Minimum required:  1.54.0-nightly (2021-05-18)
  See the getting started guide (https://rocket.rs/v0.5/guide/getting-started/) for more information.
  thread 'main' panicked at 'Aborting compilation due to incompatible compiler.', C:\Users\z\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rocket-0.4.11\build.rs:29:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


```

**Comment by SergioBenitez** [comment]
You should use Rocket 0.5-rc with rust stable or use nightly when using 0.4. This information is all over the docs, and there are several issues in this repository noting this as well. The error message also indicates this.

**Comment by yusangeng** [comment]
Same error. I'm using rocket v0.5.1.

![image](https://github.com/user-attachments/assets/5e3a4eca-fc37-411c-af6b-f1c98479fe93)

**Comment by the10thWiz** [comment]
You should check what toolchain version you're using (`rustc --version`). You should also try `cargo update`, since the pear_codegen version you have appears to be out of date.

**Comment by markg85** [comment]
> You should also try cargo update, since the pear_codegen version you have appears to be out of date.

No kidding...
That is the whole problem why people hit this issue!

Like i am right now too.
The problem is not in the toolchain. It's in `rocket-contrib`
```plain
├── rocket_contrib v0.4.11
│   ├── log v0.4.26
│   ├── notify v4.0.18
│   │   ├── bitflags v1.3.2
│   │   ├── filetime v0.2.25
│   │   │   ├── cfg-if v1.0.0
│   │   │   └── libc v0.2.170
│   │   ├── inotify v0.7.1
│   │   │   ├── bitflags v1.3.2
│   │   │   ├── inotify-sys v0.1.5
│   │   │   │   └── libc v0.2.170
│   │   │   └── libc v0.2.170
│   │   ├── libc v0.2.170
│   │   ├── mio v0.6.23
│   │   │   ├── cfg-if v0.1.10
│   │   │   ├── iovec v0.1.4
│   │   │   │   └── libc v0.2.170
│   │   │   ├── libc v0.2.170
│   │   │   ├── log v0.4.26
│   │   │   ├── net2 v0.2.39
│   │   │   │   ├── cfg-if v0.1.10
│   │   │   │   └── libc v0.2.170
│   │   │   └── slab v0.4.9 (*)
│   │   ├── mio-extras v2.0.6
│   │   │   ├── lazycell v1.3.0
│   │   │   ├── log v0.4.26
│   │   │   ├── mio v0.6.23 (*)
│   │   │   └── slab v0.4.9 (*)
│   │   └── walkdir v2.5.0
│   │       └── same-file v1.0.6
│   ├── rocket v0.4.11
│   │   ├── atty v0.2.14
│   │   │   └── libc v0.2.170
│   │   ├── base64 v0.13.1
│   │   ├── log v0.4.26
│   │   ├── memchr v2.7.4
│   │   ├── num_cpus v1.16.0 (*)
│   │   ├── pear v0.1.5
│   │   │   └── pear_codegen v0.1.5 (proc-macro)
```

As you can see, rocket_contrib (0.4.11) requires rocket (0.4.11) which requires pear (0.1.5) which requires pear_codegen (0.1.5). And there you have the problem.

@SergioBenitez Could you perhaps reopen this issue?
It would be super if you could have a look at that contrib package. I frankly don't quite know how this all works in rust, kinda new to it.

**Comment by the10thWiz** [comment]
`rocket_contrib` has been deprecated, and is not supported for `rocket` 0.5. As listed in the migration guide, `rocket_contrib` has been split into several crates, including `rocket_db_pools` and `rocket_dyn_templates`.
