### ISSUE TITLE
When selecting custom profile, other config aren't updated

### ISSUE THREAD

**Issue by EliseChouleur** [SergioBenitez/Rocket#2584]
**Description**

In the Rocket.toml I've added a custom profile which specifies a custom address and a custom port. But when selecting the profile thanks to ROCKET_PROFILE, it doesn't load the address and port configuration.

**To Reproduce**

Rocket.toml:
```
[default]
address = "127.0.0.1"
port = 8081

[custom]
address = "0.0.0.0"
port = 8082
```

**Current Behavior**
```
Configured for custom.
   >> address: 127.0.0.1
   >> port: 8081
```
**Expected Behavior**

ROCKET_PROFILE=custom cargo run
```
Configured for custom.
   >> address: 0.0.0.0
   >> port: 8082
```

**Environment:**

 - Rocket Version: [0.5.0-rc3

**Comment by notjek1** [comment]
i can't reproduce the issue
[screenshot](https://imgur.com/a/5N65Vqo)

**Comment by EliseChouleur** [comment]
Actually, what's happening is when I put the built executable on another machine, then it's not working.
In the log I see that the `custom` profile has been selected but the address and port are wrong.

**Comment by robertwayne** [comment]
The `Rocket.toml` file is not compiled into the binary. Are you copying that over alongside the binary as well?
