### ISSUE TITLE
Wrong dependency code at documentation

### ISSUE THREAD

**Issue by solaris5000** [SergioBenitez/Rocket#2587]
**Description**

[dependencies]
rocket = "=0.5.0-rc.3"

there are equality symbol in the quotes

https://api.rocket.rs/v0.5-rc/rocket/

**Comment by robertwayne** [comment]
[This is valid syntax](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html). It specifies a dependency on a _specific_ version. Excluding the "=" actually specifies a *range* for any SemVer compatible versions.
