### ISSUE TITLE
`CookieJar::get_pending` returns both pending and non-pending cookies

### ISSUE THREAD

**Issue by quentinmit** [SergioBenitez/Rocket#2591]
**Description**

The docs for `CookieJar::get_pending` say:

> This _does not_ return cookies sent by the client in a request. To
> retrieve such cookies, using [`CookieJar::get()`] or
> [`CookieJar::get_private()`].

but in fact, the last line of the implementation of `get_pending` is

```rust
self.get(name).cloned()
```

which means that it *does* in fact return the cookie sent by the client, if there wasn't a pending operation that replaced the cookie.

This means that it cannot be safely used to retrieve a pending private cookie, because it will fall back to returning an unencrypted cookie with the same name.

**To Reproduce**

Here's an example program that demonstrates the bug, and demonstrates the security implications re: private cookies:

```rust
use rocket::*;
use rocket::local::blocking::Client;
use rocket::http::{Cookie, CookieJar};

#[get("/?<set>")]
fn hello(jar: &CookieJar<'_>, set: bool) -> String {
    if set {
        jar.add_private(Cookie::new("private_cookie", "encrypted value"));
    }
    let cookie = jar.get_pending("private_cookie");
    format!("cookie = {:?}", cookie.map(|c| c.value().to_string()))
}

#[launch]
fn rocket() -> _ {
    rocket::build().mount("/", routes![hello])
}

#[test]
fn test_ignores_encrypted() {
    let client = Client::tracked(rocket()).expect("valid rocket");

    assert_eq!(
        client.get("/")
            .dispatch().into_string(),
        Some("cookie = None".to_owned()),
    );

    assert_eq!(
        client.get("/?set")
            .dispatch().into_string(),
        Some(r#"cookie = Some("encrypted value")"#.to_owned()),
    );

    // Fails here, returning the raw encrypted value of the cookie.
    assert_eq!(
        client.get("/")
            .dispatch().into_string(),
        Some("cookie = None".to_owned()),
    );
}

#[test]
fn test_ignores_unencrypted() {
    let client = Client::tracked(rocket()).expect("valid rocket");

    // Fails here, returning the string "unencrypted value".
    assert_eq!(
        client.get("/")
            .cookie(Cookie::new("private_cookie", "unencrypted value"))
            .dispatch().into_string(),
        Some("cookie = None".to_owned()),
    );
}
```

**Expected Behavior**

Either `get_pending()` should not call `get()`, or a second `get_pending_private()` should be introduced that calls `get_private()` instead of `get()` (and probably also makes sure that the pending cookie is private before returning it).

**Environment:**

 - Rocket Version: 0.5.0-rc3

**Comment by SergioBenitez** [comment]
> which means that it _does_ in fact return the cookie sent by the client, if there wasn't a pending operation that replaced the cookie.

That's true. The documentation is wrong. Look like this was erroneously added in 1ba41b3990c8202ba50de60ff0e7157a9ee2887a.

> Either `get_pending()` should not call `get()`, or a second `get_pending_private()` should be introduced that calls `get_private()` instead of `get()` (and probably also makes sure that the pending cookie is private before returning it).

`get_pending()` also returns any added private cookies, but it currently does not return a _original_ private cookie. Or rather it does, but it doesn't decrypt it. Let's fix that.
