### ISSUE TITLE
Unable to derive `UriDisplayPath` for enum.

### ISSUE THREAD

**Issue by lindhe** [SergioBenitez/Rocket#2595]
I'm probably missing something here, but I can't get `UriDisplay` to work for enums. I'm just getting an error saying "enums are not supported", but I thought that the documentation indicates that enum is supported.

https://github.com/SergioBenitez/Rocket/blob/c2936fcb1e4f8f4907889b54a9e4e741a565a7d7/core/http/src/uri/fmt/uri_display.rs#L201

> (or enum)

![Screenshot from 2023-08-11 16-38-54](https://github.com/SergioBenitez/Rocket/assets/7773090/ed6d2e46-8fe5-4774-af80-d4106daae197)

Might be a bug, might be a documentation issue, but it's very likely me just not understanding the details of how to use Rocket.

**Comment by lindhe** [comment]
What I'm trying to do is to make the `family` parameter [here](https://github.com/lindhe/webicons/blob/a35eab512cb3c44fd428dd2f8e7175bd076e6d33/src/main.rs#L21) type safe by making it be of type [`WebiconFamily`](https://github.com/lindhe/webicons/blob/a35eab512cb3c44fd428dd2f8e7175bd076e6d33/src/lib.rs#L35-L40).

The [lindhe/webicons](https://github.com/lindhe/webicons/) project is 90% just a way for me to learn Rust and try to write according to the best practice, so if it seems like I'm approaching things the wrong way I'm more than happy to hear what to do instead. :)

What I originally had in mind was to make something similar to a [union](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#union-types) of [literal types](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#literal-types) in Typescript, but it seems like that's not really possible in Rust. That's why I went with C-style enums with traits to make it convert to/from strings instead.

**Comment by SergioBenitez** [comment]
> What I'm trying to do is to make the `family` parameter [here](https://github.com/lindhe/webicons/blob/a35eab512cb3c44fd428dd2f8e7175bd076e6d33/src/main.rs#L21) type safe by making it be of type [`WebiconFamily`](https://github.com/lindhe/webicons/blob/a35eab512cb3c44fd428dd2f8e7175bd076e6d33/src/lib.rs#L35-L40).

That's a good goal. The way to do this is to implement [`FromParam`](https://api.rocket.rs/v0.5-rc/rocket/request/trait.FromParam.html) for the type. We could make the derive implement the `UriDisplay` trait in the way you want, but doing so would require significant work to account for similar use-cases. Instead, it's rather simple to implement `UriDisplay` here as well.

The [example](https://api.rocket.rs/v0.5-rc/rocket/http/uri/fmt/trait.UriDisplay.html#example) shows how to do both. In your case, I would recommend doing something like this, part of which you already have:

```rust
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum WebiconFamily {
    Emojis,
    Icons,
}

pub struct ParseWebiconFamilyError;

impl WebiconFamily {
    pub const fn as_str(&self) -> &'static str {
        match self {
            WebiconFamily::Emojis => "emojis",
            WebiconFamily::Icons => "icons"
        }
    }
}

impl fmt::Display for WebiconFamily {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.as_str().fmt(f)
    }
}

impl FromStr for WebiconFamily {
    type Err = ParseWebiconFamilyError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if s == WebiconFamily::Emojis.as_str() {
            Ok(Self::Emojis)
        } else if s == WebiconFamily::Icons.as_str() {
            Ok(Self::Icons)
        } else {
            Err(ParseWebiconFamilyError)
        }
    }
}

impl<'r> FromParam<'r> for WebiconFamily {
    type Error = ParseWebiconFamilyError;

    #[inline]
    fn from_param(param: &'r str) -> Result<Self, Self::Error> {
        param.parse()
    }
}

impl UriDisplay<Path> for WebiconFamily {
    fn fmt(&self, f: &mut Formatter<Path>) -> fmt::Result {
        UriDisplay::fmt(&self.as_str(), f)
    }
}

impl_from_uri_param_identity!([Path] WebiconFamily);
```

**Comment by lindhe** [comment]
Thanks a bunch!

And what about the C-style enum? Do you think it makes sense in context, or would something else be more idiomatic?
