### ISSUE TITLE
rocket_db_pools doesn't have the feature diesel_postgres or diesel_mysql

### ISSUE THREAD

**Issue by buranovite** [SergioBenitez/Rocket#2596]
**Description**

When including `"diesel_postgres"` or `"diesel_mysql"` cargo build fails with this message:

```
    Updating crates.io index
error: failed to select a version for `rocket_db_pools`.
    ... required by package `rocket_db_pools_diesel_test v0.1.0 (/home/pavel/devel/rust/rocket_db_pools_diesel_test)`
versions that meet the requirements `=0.1.0-rc.3` are: 0.1.0-rc.3

the package `rocket_db_pools_diesel_test` depends on `rocket_db_pools`, with features: `diesel_postgres` but `rocket_db_pools` does not have these features.


failed to select a version for `rocket_db_pools` which could resolve this conflict
```

Despite enabling the exact feature that the [documentation](https://api.rocket.rs/master/rocket_db_pools/index.html#diesel-v2) tells me to enable, cargo can't find it.

**To Reproduce**

1. `cargo new rocket_db_pools_diesel_test --bin`
2. `cd rocket_db_pools_diesel_test`
3. Put this into `Cargo.toml`:
```
[package]
name = "rocket_db_pools_diesel_test"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = "2"
diesel_migrations = "2"

[dependencies.rocket]
version = "=0.5.0-rc.3"

[dependencies.rocket_db_pools]
version = "=0.1.0-rc.3"
default-features = false
features = [ "diesel_postgres" ]
```
4. No need to change main.rs
5. `cargo build`

**Expected Behavior**

Cargo build to succeed.

**Environment:**

 - OS Distribution and Kernel: [Arch Linux 6.4.9-arch1-1]
 - Rocket Version: [`=0.5.0-rc.3`]

**Additional Context**

I initially added this feature alongside `deadpool_postgres` in an existing project. Then I tried putting it as a dependency into a clear, newly-created project and it didn't work there.

The databases example works, but only with paths. If I replace the path to `rocket_db_pools` with the version from the documentation, it gives the same error.

**Comment by SergioBenitez** [comment]
A version of the crate with these features hasn't been released yet. You'll be able to use them once it's released, or prior if you depend on the crate via git/GitHub.
