### ISSUE TITLE
FromForm derive macro uses removed private_in_public lint

### ISSUE THREAD

**Issue by ItsDrike** [SergioBenitez/Rocket#2608]
**Description**

Using the `FromForm` derive macro causes a warning for `renamed_and_removed_lints`, explaining that the `private_in_public` lint is no longer available to appear on newer rust versions.

**To Reproduce**

Create a structure that derives `FromForm`, and compile with rust version of 1.72 (not sure exactly in which version this lint got removed, so some older versions might also produce the warning)

**Expected Behavior**

The `#[allow(private_in_public)]` should be removed, or replaced by the new lints. I'm not sure exactly what this lint is for, and what was should it be replaced with (if anything), but it would be nice to be able to avoid this warning on every struct that derives `FromForm`.

This wouldn't be as big of an issue if people could do `#[allow(renamed_and_removed_lints)]`. But putting this before the derive macro doesn't actually cause the lint to be allowed, probably since the derive macro actually puts the line with that allow elsewhere. This makes it very annoying to use `FromForm` as the warning is unavoidable.

**Environment:**

 - OS Distribution and Kernel: Arch Linux (6.4.12-arch1-1)
 - Rocket Version: 0.5.0-rc.3

**Comment by SergioBenitez** [comment]
Very annoying indeed. Pushing a fix soon.

**Comment by CSharperMantle** [comment]
[Rust 1.74.0](https://github.com/rust-lang/rust/releases/tag/1.74.0) has stably deprecated `private_in_public` lint with a group of two rust-lang/rfcs#2145 compatible new lints: `private_interfaces` and `private_bounds`; see rust-lang/rust#113126 for details. Thus I think it is safe for us to move to these new lints when we are compiling on `rustc > 1.74.0`.

A PR is underway.
