### ISSUE TITLE
Bugs in negated `in` expressions

### ISSUE THREAD

**Issue by gorosgobe** [SergioBenitez/Rocket#2617]
**Description**

`in` and `instanceof` expressions in JS
```js
a in obj;
a instanceof C;
```
can be negated by grouping them and applying the `!` operator, i.e.

```js
!(a in obj);
!(a instanceof C);
```

Applying the `!` operator incorrectly (on the LHS operand) leads to bugs:
```js
!a in obj; // will evaluate to false, unless obj has a "true" or "false" key
!a instanceof C; // will evaluate to false, unless C overrides instanceof with a @@hasInstance method
```
For more information, please see these [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#not_an_instanceof) and [the no-unsafe-negation recommended Eslint rule](https://eslint.org/docs/latest/rules/no-unsafe-negation).

I have found several potentially problematic instances of the above bugs in your codebase:
https://github.com/SergioBenitez/Rocket/blob/26a3f00f82b6ddec2bbdb3ecb0c29d6ff0da7472/examples/chat/static/script.js#L97

**Comment by SergioBenitez** [comment]
This is an example, which we don't hold to the same standard as the rest of the codebase. No harm is making it better, of course!
