### ISSUE TITLE
TempFile should be able to be read like a Stream

### ISSUE THREAD

**Issue by ethereumdegen** [SergioBenitez/Rocket#2619]
TempFile should be able to be read like a Stream

A clear and concise description of what the problem is. Examples:

-  I want to take a temp file and immediately read it as data to send it to an S3 bucket instead of saving it locally at all.  
 

**Ideal Solution**
 add a method to TempFile that allows it to be read as a bytes stream .   Without necessarily saving it to disk first.

**Comment by SergioBenitez** [comment]
There's already `TempFile::open()`.

**Comment by SergioBenitez** [comment]
See [`TempFile::open()`](https://api.rocket.rs/master/rocket/fs/enum.TempFile.html#method.open) (on master).
