### ISSUE TITLE
Code for benchmark from README

### ISSUE THREAD

**Issue by Eilie** [SergioBenitez/Rocket#262]
Hello,

@SergioBenitez  Could you please provide the code you've benchmarked to compare Rocket with Iron?

https://github.com/SergioBenitez/Rocket/tree/master/examples/hello_world

with `./hello_world > /dev/null` gives me 29k req/s, while Iron gives ~70k. I understand that raw Iron doesn't even have logging, but I'm just curious.

**Comment by Eilie** [comment]
Ah, I've launched hello_world example with `log = "critical"` and Rocket score ~70k as well at my machine.

**Comment by SergioBenitez** [comment]
@Eilie Everything you might to accurately replicate the benchmarks can be found in https://github.com/SergioBenitez/Rocket/issues/140#issuecomment-273396582.
