### ISSUE TITLE
Don't 404 on invalid input

### ISSUE THREAD

**Issue by dev-ardi** [SergioBenitez/Rocket#2626]
**Is your feature request motivated by a concrete problem? Please describe.**
```rs
#[get("/echo?<num>")]
fn echo(num: u64) -> Result<String, BadRequest<String>> {
    Ok(num.to_string())
}
```
works for `/echo?num=1` but 404s for `/echo?num=-1`.

This is very bad for public APIs

**Why this feature can't or shouldn't live outside of Rocket**

This should be in the core of the router.

**Ideal Solution**

The error should be returned to the caller in a 400.

**Alternatives Considered**

Right now you'd have to match inside of the function, have number be an  `Option<String>` and do all of the validation manually.

**Comment by SergioBenitez** [comment]
> **Is your feature request motivated by a concrete problem? Please describe.**
> 
> ```rs
> 
> #[get("/echo?<num>")]
> 
> fn echo(num: u64) -> Result<String, BadRequest<String>> {
> 
>     Ok(num.to_string())
> 
> }
> 
> ```
> 
> works for `/echo?num=1` but 404s for `/echo?num=-1`.
> 
> 
> 
> This is very bad for public APIs

Why?

> 
> 
> 
> **Why this feature can't or shouldn't live outside of Rocket**
> 
> 
> 
> This should be in the core of the router.
> 
> 
> 
> **Ideal Solution**
> 
> 
> 
> The error should be returned to the caller in a 400.

400 would is likely incorrect - such an error code should only be used when a request is syntactically incorrect. 422 might be a better fit. 

> 
> 
> 
> **Alternatives Considered**
> 
> 
> 
> Right now you'd have to match inside of the function, have number be an  `Option<String>` and do all of the validation manually.

You can also create a fairing that check for 404s, check if any request matches, and emit whatever error you want at that point.

**Comment by dev-ardi** [comment]
>> This is very bad for public APIs

> Why?

When someone is using your API you want them to know exactly why it failed and what they did wrong:

1. Is there a route called "echo" and they used POST? -> `405: "there exists GET /echo`
2. Correct method but wrong names? eg `/echo?banana=1` -> `400: "Expected msg: u64"`
3. Serde error? eg `/echo?msg=-1` or `/echo?msg=foo` -> `422: the serde error`

> You can also create a fairing that check for 404s, check if any request matches, and emit whatever error you want at that point.

It would be nice if the routed did that for us. Is there a reason why you wouldn't want the error messages to be more explicit?

**Comment by SergioBenitez** [comment]
> >> This is very bad for public APIs
> 
> 
> 
> > Why?
> 
> 
> 
> When someone is using your API you want them to know exactly why it failed and what they did wrong:
> 
> 
> 
> 1. Is there a route called "echo" and they used POST? -> `405: "there exists GET /echo`
> 
> 2. Correct method but wrong names? eg `/echo?banana=1` -> `400: "Expected msg: u64"`
> 
> 3. Serde error? eg `/echo?msg=-1` or `/echo?msg=foo` -> `422: the serde error`
> 
> 
> 
> > You can also create a fairing that check for 404s, check if any request matches, and emit whatever error you want at that point.
> 
> It would be nice if the routed did that for us. Is there a reason why you wouldn't want the error messages to be more explicit?

One might argue that a generic error is better for security reasons. IE, perhaps you don't want to leak a route's existence. By returning 404 irrespective of whether a route exists or not, you avoid this.

That being said, my intent is for routing to be completely customizable, and I would advocate for making it simply to change the default "route not found" status code in such a case. 

Until then, I would advocate for the custom fairing route. The implementation is very straightforward and clean.

**Comment by dev-ardi** [comment]
> One might argue that a generic error is better for security reasons. IE, perhaps you don't want to leak a route's existence. By returning 404 irrespective of whether a route exists or not, you avoid this.

If your security is relying on attackers not knowing of the endpoint that's bad security, but that's just my opinion.

I think axum does what I suggested, maybe take the code from there?

**Comment by SergioBenitez** [comment]
> > One might argue that a generic error is better for security reasons. IE, perhaps you don't want to leak a route's existence. By returning 404 irrespective of whether a route exists or not, you avoid this.
> 
> 
> 
> If your security is relying on attackers not knowing of the endpoint that's bad security, but that's just my opinion.

It's not about securing the endpoint or the application, it's about disclosing the endpoint. The endpoint itself needs to be secure irrespectively, but this is orthogonal to whether it's disclosed by default.

> I think axum does what I suggested, maybe take the code from there?

Axum and Rocket work dramatically different in the relevant respects. There's no code to just _take_, and nothing particularly helpful in that regard. We could trivially modify Rocket to emit a different error code based on how routing evolved - the question is whether we should without also providing the ability to _not_.

**Comment by Directory** [comment]
I also quite dislike this behavior. I have an application with hundreds of endpoints and don't want them all to default to forwarding just because query params where invalid. All i want is for invalid params to hit the 422 or 400 catcher is that is correct. not 404. and even in the 404 catcher there's no way to check how many times the Request object forwarded to override the response as a 400 and not a 404

can provide an example of how to make such a fairing do this?

**Comment by SergioBenitez** [comment]
> can provide an example of how to make such a fairing do this?

```rust
#[launch]
fn rocket() -> _ {
    rocket::build()
        .attach(AdHoc::on_response("404 -> 422", |req, res| Box::pin(async move {
            if req.route().is_some() && res.status() == Status::NotFound {
                let catcher = Catcher::default();
                if let Ok(r) = catcher.handler.handle(Status::UnprocessableEntity, req).await {
                    *res = r;
                }
            }
        })))
}
```

Note that this will also change 404s that the application explicitly or implicitly emitted from a matched route, for instance, via an `Option::None`, which might be what you want, or might not.

**Comment by SergioBenitez** [comment]
> That's not up to me to decide but if that's the decision then I'll just not use Rocket (at least for projects with more than one person), which is a shame.

The issue remains open because no particular decision has been made. In fact, I've alluded to making a decision in the direction that is in favor of your request:

> That being said, my intent is for routing to be completely customizable, and I would advocate for making it simply to change the default "route not found" status code in such a case.

**Comment by dev-ardi** [comment]
> The issue remains open because no particular decision has been made

I've reworded my comment so that there's no confusion. What I meant is that in the case that the decision will be taken I won't be able to use it because of my requirements.

**Comment by Directory** [comment]
> Note that this will also change 404s that the application explicitly or implicitly emitted

yea thats not desirable. I was under the impression the "very straightforward and clean" way was only for the forwarding scenario that's being discussed here. is this just impossible to do in rocket?
