### ISSUE TITLE
Type-Safe URI Generation

### ISSUE THREAD

**Issue by habnabit** [SergioBenitez/Rocket#263]
Currently, given this code:

```rust
#[get("/documents/<id>")]
fn get_document(id: usize) ...
```

The `get_document` route can be matched against for incoming requests to e.g. the URI `/documents/0`, but there's no way to, given the `get_document` route and `id: usize = 0`, get back a string or URI which would match the route when requested. This is present in many other web frameworks, sometimes called `url_for`. The general utility is that you have a single source of truth for routing, instead of one source of truth for matching routes and separate ad-hoc URI generation, which isn't guaranteed to line up or stay synchronized. Adding this to rocket means that the URI generation can be generated as part of `rocket_codegen` and type-safe on inputs.

This could be exposed as something like `url_for!(get_document, id = 0)`, though routes can be mounted at places other than `/` on the `Rocket`.

**Comment by Kerollmops** [comment]
I think this feature can be useful for the [`Created`](https://api.rocket.rs/rocket/response/status/struct.Created.html) type that need a route as a `String`.
Your function (macro*) can be used to check **at compile time** the validity of the route and not point anywhere (**404**).

**Comment by Qqwy** [comment]
This could indeed provide compile-time checks similar to how Yesod does this! :-)

**Comment by SergioBenitez** [comment]
This is now implemented in master! The best documentation on how this works can be found in:

  * [`uri!`](https://github.com/SergioBenitez/Rocket/blob/33e972615160b2ac0bba2a93ada38c72b6399ba3/codegen/src/lib.rs#L129)
  * [`UriDisplay`](https://github.com/SergioBenitez/Rocket/blob/master/lib/src/http/uri/uri_display.rs#L18)
  * [`FromUriParam`](https://github.com/SergioBenitez/Rocket/blob/master/lib/src/http/uri/from_uri_param.rs#L6)

A lot of effort has gone into making `uri!` as intuitive and useable as possible. Nonetheless, I would appreciate any testing and feedback. If you're able, you can use type-safe URI generation now by depending on Rocket straight from GitHub:

```toml
[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket" }
```

Note that master contains breaking changes. In particular, `URI` is now `Uri`, and the `decl_macro` feature is required. Please take it for a spin if you can! Any feedback is greatly appreciated.

**Comment by lfairy** [comment]
That's really cool! I like how it's just a thin wrapper around `format!`.

Would it be possible for it to return a [`std::fmt::Arguments`](https://doc.rust-lang.org/std/fmt/struct.Arguments.html) instead of a `String`? Maud is moving toward zero allocations (lfairy/maud#90) so it would be cool to support that.

**Comment by SergioBenitez** [comment]
@lfairy It actually returns a `Uri`, but it does allocate once to hold the internal `String`. A value of `Arguments` doesn't contain the necessary information to reconstruct the URI, but we can imagine an analogous type that does. I'm not sure the potentially usability implications are worth the hassle, however.

On a related note, a nice optimization would be to format, at compile time, invocations with only laterals, saving an allocation in that case.

**Comment by sedrik** [comment]
What would happen if I have a single handler mounted at two different points? Like if I want to provide a complete second version of an api but re-use the old handlers (say that only one changed). Sorry but I did not try this from master but mounting handlers on several mount-points works great in the latest release.

Would uri! handle this case?
