### ISSUE TITLE
`uri!` macro does not accept routes defined as constants

### ISSUE THREAD

**Issue by Luni-4** [SergioBenitez/Rocket#2638]
**Is your feature request motivated by a concrete problem? Please describe.**

Until now, it is not possible to write something like this:

```rust
const ROUTE: &str = "/route";
rocket::uri!(ROUTE, index);
```

This approach is really helpful when you have to write routes written in a non-English language. Using constants to define routes lead to not change your routes everywhere in the code, but only the constant values.

**Ideal Solution**

Accepting `&'static str` as input route for `uri!` macro

**Comment by SergioBenitez** [comment]
You can do almost exactly that! See https://api.rocket.rs/v0.5-rc/rocket/macro.uri.html#prefixes-and-suffixes. 

Unless Rust exposed some mechanism for procedural macros that allows evaluating constants, what you're suggesting wouldn't possible. We need to ensure we're generating valid URIs, and to do so we need to know the actual string contents.

**Comment by Luni-4** [comment]
> Unless Rust exposed some mechanism for procedural macros that allows evaluating constants, what you're suggesting wouldn't possible.

Thanks a lot for your reply! 

My issue was maninly based on simplicity.

If I can write

```rust
rocket::uri!("/route", index) 
```

I *should* also be able to write

```rust
const ROUTE: &str = "/route";
rocket::uri!(ROUTE, index);
```

but since `Rust` does not support this kind of mechanism for procedural macros right now, I'm going to use your approach. Thanks a lot for your reply and help!

**Comment by Luni-4** [comment]
@SergioBenitez 

> ```rust
> const/static HOST: Absolute<'static> = uri!("http://bob.me");
> 
> let bob = uri!(host, person("Bob", Some(28)));
> assert_eq!(bob.to_string(), "http://bob.me/person/Bob?age=28");
> ```

I had used your snippet of code with `const` and I got the following `clippy` warning:

``` rust
warning: a `const` item should never be interior mutable
  --> src/main.rs:41:1
   |
41 | const ROUTE: Origin<'static> = uri!("/route");
   | -----^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   | |
   | make this a static item (maybe with lazy_static)
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#declare_interior_mutable_const
```

Therefore I had replaced `const` with `static` and I got the following error 

``` rust
error[E0507]: cannot move out of static item `ROUTE`
  --> src/route.rs:43:34
   |
43 |     ($($t:tt)*) => (rocket::uri!(ROUTE, $($t)*))
   |                                  ^^^^^^^^^^^^^^^^^^^^ move occurs because `ROUTE` has type `rocket::http::uri::Origin<'_>`, which does not implement the `Copy` trait
...
94 |     Ok(Redirect::to(uri!(route)))
   |                     ---------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `uri` (in Nightly builds, run with -Z macro-backtrace for more info)
```

To solve this problem, I had to clone the iterm: `ROUTE.clone()`. The same happened in `mount(ROUTE, routes![index])`, while for the `context!` macro I was able to use `&ROUTE`.

So my question is: can we pass an `Origin<'static>` as a reference inside `uri!` and `mount`, such as for the `context` macro, without having to clone anything?

Thanks for your reply!

**Comment by SergioBenitez** [comment]
Use `const`. This is probably a clippy bug. https://github.com/rust-lang/rust-clippy/issues/9224

**Comment by Luni-4** [comment]
Thanks a lot!
