### ISSUE TITLE
Impl<T> From<T> for Stream<T> where T: Read

### ISSUE THREAD

**Issue by dgriffen** [SergioBenitez/Rocket#267]
# Feature Request

`Stream` currently has a method called from that takes a `Read` object and returns a Stream. It would be nice if `Stream` implemented `From` so that we could call `.into()` on our `Read` types.

This would be useful in reducing the amount of code written for returning a `Stream` object. Currently in order to return a `Stream` one must type `Stream::from(reader)`, if this impl was added you could simply write `reader.into()`.

This feature needs to exist in Rocket since the Stream type is defined there and impls of traits for types must be done in the same crate.

**Comment by SergioBenitez** [comment]
I'd happily accept a PR for this!
