### ISSUE TITLE
Getting the remote IP in a handler

### ISSUE THREAD

**Issue by nabeelomer** [SergioBenitez/Rocket#279]
If I have an handler:
```rust
#[get("/")]
fn indexhandler() -> Result<Redirect, String>{
    Ok(Redirect::to("/a"))
}
```
How do I get the remote IP?
`Rocket v0.2.6`
`rustc 1.18.0-nightly (94e884b63 2017-04-27)`

**Comment by SirDoctors** [comment]
Specifics would help, what ip are you looking for? The clients? The Servers? Please feel free to include more details, will make it much easier to help you.

**Comment by nabeelomer** [comment]
I need the client's IP.

**Comment by bytebuddha** [comment]
You Have to tell rocket to pass your handler the raw request, then you can access the remote socket address, like this.
`
#[get("/")]
fn index(req: Request) -> String {
    let remote_socket_addr = req.remote().unwrap();
    format!("Ip: {:?}",remote_socket_addr)
}
`

**Comment by SergioBenitez** [comment]
@bytebuddha's answer is close, but you should never, _ever_ be unwrapping request related content in a handler. This is one of the core strength's of Rocket: all request data should be validated _before_ a handler is called.

The correct thing to do is use to use the `SocketAddr` request guard, as documented in the [FromRequest](https://api.rocket.rs/rocket/request/trait.FromRequest.html#provided-implementations) page, as follows:

```rust

#[get("/")]
fn index(remote_addr: SocketAddr) -> String {
    format!("Remote Address: {:?}", remote_addr)
}
```

**Comment by nabeelomer** [comment]
@SergioBenitez And how would I do this if I have a handler that accepts data?

**Comment by nabeelomer** [comment]
Never mind, I was able to do it. Thank you so much @SergioBenitez, @bytebuddha, and @SirDoctors.

**Comment by ycd** [comment]
Possible necrobumpers, use this: 

```rust
use rocket::{
    request::{FromRequest, Outcome},
    Request,
};
use std::{convert::Infallible};


#[derive(Debug)]
pub struct RequestSocketAddr {
    pub socket_addr: String,
}

impl<'a, 'r> FromRequest<'a, 'r> for RequestSocketAddr {
    type Error = Infallible;

    fn from_request(request: &'a Request<'r>) -> Outcome<Self, Self::Error> {
        let socket_addr: String = request.remote().unwrap().to_string();

        rocket::Outcome::Success(Self {
            socket_addr: socket_addr,
        })
    }
}
```

**Comment by SergioBenitez** [comment]
> Possible necrobumpers, use this: 
> 
> 
> 
> ```rust
> 
> use rocket::{
> 
>     request::{FromRequest, Outcome},
> 
>     Request,
> 
> };
> 
> use std::{convert::Infallible};
> 
> 
> 
> 
> 
> #[derive(Debug)]
> 
> pub struct RequestSocketAddr {
> 
>     pub socket_addr: String,
> 
> }
> 
> 
> 
> impl<'a, 'r> FromRequest<'a, 'r> for RequestSocketAddr {
> 
>     type Error = Infallible;
> 
> 
> 
>     fn from_request(request: &'a Request<'r>) -> Outcome<Self, Self::Error> {
> 
>         let socket_addr: String = request.remote().unwrap().to_string();
> 
> 
> 
>         rocket::Outcome::Success(Self {
> 
>             socket_addr: socket_addr,
> 
>         })
> 
>     }
> 
> }
> 
> ``` 

This is unnecessary and incorrect as the unwrap could fail. `SocketAddr` is already a request guard. Use it directly.

**Comment by ycd** [comment]
@SergioBenitez tthanks! looks like i became the necrombumper :laughing:
