### ISSUE TITLE
Support SSL

### ISSUE THREAD

**Issue by sfackler** [SergioBenitez/Rocket#28]
The most straightforward way would probably be to add a `lanuch_ssl` method to Rocket that takes a `T: hyper::net::SslServer`.

**Comment by SergioBenitez** [comment]
This is blocked by https://github.com/hyperium/hyper/pull/975. That being said, Rocket tries very hard not expose Hyper types directly, and I don't particularly like the idea of having two `launch` methods. I imagine the best avenue for this would be via some [configuration parameters](https://api.rocket.rs/rocket/config/index.html).

**Comment by sfackler** [comment]
You can disable Hyper's ssl feature and use https://crates.io/crates/hyper-openssl to get an `SslSever` implementation that uses a modern version of rust-openssl.

There's a fairly large set of things you'd need to be able to configure to do TLS setup programmatically but it should be doable.

**Comment by ghazkarim** [comment]
I'm not sure what exactly the plan for Rocket's HTTP backend is but I support this feature request. I like Rocket a lot but without TLS I can't really use it in a serious project. HTTP2 and HTTP2 Server Push support are also things I'd like to see in a release.

**Comment by SergioBenitez** [comment]
@ghazkarim You can place Rocket behind a reverse proxy, like NGINX, to get SSL support. This is what [paste.rs][https://paste.rs] does, for example.

**Comment by ghazkarim** [comment]
@SergioBenitez didn't know that. Thank you!

**Comment by SergioBenitez** [comment]
Is there a case where putting Rocket behind a reverse proxy like NGINX or HAProxy to get SSL support doesn't suffice? I'd like to hear about them, if so.

**Comment by jxn** [comment]
@SergioBenitez I'm not sure if this is enough to justify the extra work, but native support certainly has benefits.  HTTPS is increasingly a requirement even in development, for features like Service Worker.

Nginx and HA proxy are great for complicated use cases, but for simple apps, they introduce complexity and friction to building and set up for both development and production.  Proxy servers require more set up (especially cross-platform like Windows), can't be version managed in Cargo.toml dependencies, and could add unnecessary bloat.  They also add more non-Rust code to the app.  By now we've already drank the Rust-safety Kool-aid, so we don't want that.

My use-case is that I've been playing around with rust a little bit, and I've been asked to give a short workshop intro, but it requires HTTPS-only web features.  I'd love to be able to use Rocket, and have `rustup` installation and `cargo run` the only required steps to get people started, but adding in nginx greatly complicates the start of a project.  I know native HTTPS support in rocket wouldn't arrive in time for this workshop, but it's one example!

**Comment by mgattozzi** [comment]
Maybe not everyone wants to use NGINX or HAProxy and having native inbuilt support would be nice. Maybe behind a feature flag like `native-ssl` so that those who want it can use it and those who don't can use something else. Flexibility and covering more use cases will benefit everyone, at the cost of maintainability.

**Comment by mehcode** [comment]
> I don't particularly like the idea of having two launch methods. I imagine the best avenue for this would be via some configuration parameters.

:+1: I shouldn't have to change code to change the protocol binding of the app. 

---

On that note.. I'm not really in favor of this in a general case. Outside of **development** or **demoing** there is no use-case I can think for the app using SSL itself.

I would be in favor of actually automatically listening on both HTTP _and_ HTTPS via an automatically generated self-signed certificate. This behavior could be expanded to allow configuration to run HTTPS with a real certificate. 

---

More on use cases.. I can't see any point of listening on SSL in production. 

I can try and envision a use case:

You are trying to be as cheap as possible. You have a single server running your application and would want this so you don't have to configure nginx on the same server and deal with port binding.

 - First off.. even if you are being cheap.. please get 2 servers and use a basic load balancer for an app that is in production which in that case the SSL gateway is at the load balancer and the individual app servers are behind a firewall. But perhaps this is just a throw-away site that it doesn't really matter if it goes down. 

 - Using some reverse proxy like nginx can give you **zero-downtime upgrades** for free. Without this your site will go offline for a brief moment when you push the new version.

Any _production_ reason I can think of just goes to the site being throw-away which is contradictory to wanting SSL in the first place.

Now, please don't take any of this as criticizing you or your processes if any of this is what you do. But you must realize that it's not considered the *correct* method in respect to industry best practices and tools shouldn't cater to that.

**Comment by fabricedesre** [comment]
> Now, please don't take any of this as criticizing you or your processes if any of this is what you do. But you must realize that it's not considered the correct method in respect to industry best practices and tools shouldn't cater to that.

That's because you focus on one use case: running in a "big server" setup. If I want to expose an IoT device as a https endpoint, I certainly don't want to put anything in front of the https server itself.

Different use cases have different constraints, so one size does not fit all. By offering an optional, feature gated support, Rocket could cater to all.

**Comment by mehcode** [comment]
> That's because you focus on one use case: running in a "big server" setup. If I want to expose an IoT device as a https endpoint, I certainly don't want to put anything in front of the https server itself.

I stand corrected. I've never done anything with IoT but now that I consider that, it makes a lot of sense. I still think easily running HTTPS with a generated self-signed cert would be neat for demoing in cases where your demo must be in SSL.

**Comment by mmstick** [comment]
I'd like SSL support too because it seems that SSL support is a requirement for enabling Brotli compression of web content. I've improved my page caching technique in Rocket to also support Brotli, but no web browser supports `("Content-Encoding", "br")` without HTTPS.

**Comment by Roba1993** [comment]
I would like to use rocket, but without SSL support it's not possible. I have two use-cases:
1. Provide a Home Control website to turn lights on/off etc.
2. Communicate to the IoT devices over a secured connection

I really hope, SSL support is coming soon....

**Comment by rohitjoshi** [comment]
:+1 Hopefully Mutual SSL will be supported as well.

**Comment by SergioBenitez** [comment]
I'm convinced.

Rocket will support TLS, including client-to-server authentication. Support will be provided via [rustls](https://github.com/ctz/rustls). This will ship as part of the next major release, `0.3`, and will land in master soon.

**Comment by SergioBenitez** [comment]
TLS support has landed in 1516ca4! If you're on master and would like to use it immediately, please see the [hello_tls](https://github.com/SergioBenitez/Rocket/tree/master/examples/hello_tls) example. Client authentication via TLS is not yet supported. Its progress will be tracked in #254.

**Comment by mmstick** [comment]
@SergioBenitez I've a question. I'm trying to use keys I got from Let's Encrypt, and I've added the following into my Rocket.toml file:

```
[global.tls]
certs = "/etc/letsencrypt/live/mmstick.tk/fullchain.pem"
key = "/etc/letsencrypt/live/mmstick.tk/privkey.pem"
```

But I seem to be getting this error:

```
Error: 'development.tls' key could not be parsed
    => in "/mnt/archive/Sources/personal-website/Rocket.toml"
    => expected value to be a readable certificates file, but found nonexistent or invalid file
```

**Comment by SergioBenitez** [comment]
@mmstick I just tried with a Let's Encrypt chain and private key, and everything worked as expected. I would check the permissions on the files and ensure that the Rocket process can read them. I'm pushing an update now that will clarify error messages. It's currently not clear if there's an I/O issue with reading the files or if the files failed to parse.

**Comment by mmstick** [comment]
@SergioBenitez Seems to report it as a malformed PEM file. Now I'm wondering why Let's Encrypt would create a malformed file.

**Comment by SergioBenitez** [comment]
@mmstick It's possible that `rustls` is expecting one format when Let's Encrypt is giving you another. If you hop on `#rocket`, I'd love to help you debug this!

**Comment by GildedHonour** [comment]
If I'm using nginx as a proxy between a rust rocket application and internet, will I need to setup anything in my application to support tls? Or will I have to do that in nginx config file?

**Comment by SergioBenitez** [comment]
@GildedHonour You'd use NGINX for TLS in that case. See [their documentation](http://nginx.org/en/docs/http/configuring_https_servers.html) for more information.
