### ISSUE TITLE
Can't request static file twice

### ISSUE THREAD

**Issue by Roba1993** [SergioBenitez/Rocket#280]
Hi,

I've created the following two static file functions: 
```rust
#[get("/")]
fn index() -> io::Result<NamedFile> {
    NamedFile::open("../ui/web/index.html")
}

#[get("/<file>")]
fn files(file: String) -> Option<NamedFile> {
    NamedFile::open(Path::new("../ui/web/").join(file)).ok()
}
```

The first request is working, like expected. The second request (from chrome browser) didn't sent a response for 20-30 seconds.
I run this under mac os x and with `cargo run`

Is it a bug, or did I make a failure?

Thanks,
Robert

**Comment by SergioBenitez** [comment]
Please see #191, #239, #243.
