### ISSUE TITLE
Request Guard to validate request body with signature in HTTP header?

### ISSUE THREAD

**Issue by aergonaut** [SergioBenitez/Rocket#284]
**Rocket version:** 0.2.6

I am writing a GitHub webhook service and I want to add message validation according to [GitHub's documentation](https://developer.github.com/webhooks/securing/). The docs say to validate the contents of the `X-Hub-Signature` header against the HMAC digest of the request body.

I've read the documentation about creating [Request Guards](https://rocket.rs/guide/requests/#request-guards) with [FromRequest](https://api.rocket.rs/rocket/request/trait.FromRequest.html), and that struck me as a good way to handle it. The code I wanted was something like this:

```rust
pub fn webhook(signature: VerifiedSignature) -> Result<()> {
    // ...
}

struct VerifiedSignature;

impl<'r, 'a> FromRequest<'r, 'a> for VerifiedSignature {
    fn from_request(request: &'a Request<'r>) -> request::Outcome<VerifiedSignature, ()> {
        // return Failure if the signature doesn't match
    }
}
```

The [documentation for Request](https://api.rocket.rs/rocket/struct.Request.html) says that the Request struct doesn't have access to the request body. But in this case to compute the expected signature I need access to the request body as well.

My next thought for this was to make the `VerifiedSignature` just extract the signature from the `X-Hub-Signature` if it's present and validate the signature in the handler itself. In that case, though, I'm not sure how to access the request body to compute the expected signature.

What would be the best approach in this case?

**Comment by SergioBenitez** [comment]
It sounds like you want a [data guard](https://api.rocket.rs/rocket/data/trait.FromData.html). Data guards are derived from both a request and the body data.

**Comment by aergonaut** [comment]
Ah, thanks! That's what I wanted!
