### ISSUE TITLE
Documentation for deploying on Linux server

### ISSUE THREAD

**Issue by freinn** [SergioBenitez/Rocket#288]
Hi!

I'm not in a good health state now, but tried to deploy a working rocket app (localhost) into a Linode VPS. I couldn't.

For that, I ask for a guide to deploy in digital ocean, linode, or any VPS. Maybe is just an issue with the port 80.

Thanks in advance.

**Comment by Eijebong** [comment]
Here is my setup for my website. Not sure if it's relevant for your use case (I don't know if you have shell access, nginx configuration access...) but it might help you
## bananium.rs.service
```
[Unit]                                             
Description=Bananium.rs
After=redis.service postgresql.service

[Service]
User=bananium
WorkingDirectory=/srv/http/bananium.rs
ExecStart=/srv/http/bananium.rs/target/release/web

[Install]
WantedBy=multi-user.target
```

## Rocket.toml (I should use the production environment but I'm way to lazy to change that :D)
```
[development]        
address = "localhost"
port = 8069
workers = 8
log = "normal"
```

## Relevant nginx configuration
```
server {                                                                                
    listen 443 ssl ;
    server_name bananium.fr;

    location /static {
        root /srv/http/bananium.rs;
        expires 1d;
    }

    location / {
        proxy_pass http://127.0.0.1:8069;
    }
}
```

**Comment by SergioBenitez** [comment]
What issue did you have, exactly? Are you deploying Rocket behind a reverse proxy, like NGINX?

**Comment by freinn** [comment]
@SergioBenitez no, I'm deploying just with Rocket, that's what I want. I'm using ubuntu 16.04.2 LTS on my server. Trying to launch in production mode as root, on port 80 or 443 (rocket 3.0)

**Comment by SergioBenitez** [comment]
@freinn But what issue are you having? `sudo ROCKET_ENV=prod cargo run --release` should suffice.

By the way, it's highly recommended to run Rocket behind a reverse proxy like NGINX. This is because NGINX is async, so you'll get around many of the synchronous limitations of Rocket, and NGINX support HTTP2 as well as TLS >= 1.0.

**Comment by freinn** [comment]
```
Error: Failed to start server.
thread 'main' panicked at 'Address already in use (os error 98)', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.2.6/src/rocket.rs:555
note: Run with `RUST_BACKTRACE=1` for a backtrace.

```

**Comment by freinn** [comment]
I'm trying to understand nginx so I can use it with Rocket

**Comment by freinn** [comment]
Now I have no errors and the message is:

```
Finished release [optimized] target(s) in 0.2 secs
Running `target/release/web`
```

**Comment by SergioBenitez** [comment]
The error you've posted contains all of the information: "Address already in use (os error 98)". Some other process on your VM is running on port 80. Use `netstat` or `lsof` to determine what it is, then kill it. Rocket should then launch successfully.

**Comment by freinn** [comment]
I've read [this article](https://medium.com/@rap2h/a-rust-powered-public-website-in-5-minutes-b682d8527b6b) but it's impossible to get it running. In production, I can't even know in which port its executing.

**Comment by belst** [comment]
I created a small guide to deploy rocket behind nginx with letsencrypt:

https://gist.github.com/belst/ff36c5f3883f7bf9b06c379d0a7bed9e

**Comment by freinn** [comment]
@belst Many thanks, with that guide and a friend help I have my website online. Some iptables fails because I have ufw installed but was almost perfect.

**Comment by SergioBenitez** [comment]
Awesome, glad to hear this has been resolved, @freinn. @belst Thank you for the guide! I'm hoping to have a deploying section in the guide for the next release, and I'll incorporate some of what you wrote there. :) Let's track a deploying guide in the existing docs issue, #171.
