### ISSUE TITLE
Custom traits is deprecated

### ISSUE THREAD

**Issue by adelarsq** [SergioBenitez/Rocket#29]
Running the [forms example](https://github.com/SergioBenitez/Rocket/tree/master/examples/forms) shows the following warning:
```
warning: `#[derive]` for custom traits is deprecated and will be removed in v1.15. Prefer using procedural macro custom derive
  --> src\main.rs:12:10
   |
12 | #[derive(FromForm)]
   |          ^^^^^^^^
```

**Comment by SergioBenitez** [comment]
The warning will go away as soon as Rust releases a new nightly. Waiting for https://github.com/rust-lang/rust/pull/38533.

**Comment by ishitatsuyuki** [comment]
There's always a reason to warn you. Have you considered to step a bit back from relying on plugin, and use the stabilized macros?

**Comment by SergioBenitez** [comment]
@ishitatsuyuki Of course! Please see https://github.com/SergioBenitez/Rocket/issues/50 and the linked comment for my thoughts.

**Comment by SergioBenitez** [comment]
Fixed in https://github.com/SergioBenitez/Rocket/commit/337173eaf417d54187a0ca8b24b475e8a3fe8aad.

**Comment by zoumi** [comment]
I got this warn.
My rust version:

Default host: x86_64-pc-windows-gnu

nightly-i686-pc-windows-gnu (default)
rustc 1.21.0-nightly (f774bced5 2017-08-12)

**Comment by madeindjs** [comment]
Same problem on 

- nightly-x86_64-unknown-linux-gnu
- rustc 1.23.0-nightly
