### ISSUE TITLE
Argument passed by value but not consumed with clippy lints

### ISSUE THREAD

**Issue by Razican** [SergioBenitez/Rocket#294]
I'm getting this clippy warning:
```text
warning: this argument is passed by value, but not consumed in the function body
  --> src/lib.rs:84:1
   |
84 | #[get("/favicon.ico")]
   | ^^^^^^^^^^^^^^^^^^^^^^ help: consider taking a reference instead `&#[get("/favicon.ico")]`
   |
   = note: #[warn(needless_pass_by_value)] on by default
   = help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#needless_pass_by_value
```

for this code:

```rust
/// Main favicon.
#[get("/favicon.ico")]
pub fn favicon() -> Option<NamedFile> {
    NamedFile::open("static/favicon.ico").ok()
}
```

It's a really minor issue: seems that the `"/favicon.ico"` is being owned by the generated function, but never consumed, and clippy suggests using a reference. Not sure what code is being generated though.

I'm also getting some warnings if I activate the `use_debug` lint.

**Comment by SergioBenitez** [comment]
My guess is that the lint is referring to the `Data` argument of the code generated function. If someone wants to confirm, that'd be fantastic! The thing to do is to view the code generation source ([see codegen debug in the guide](https://rocket.rs/guide/testing/#codegen-debug)], replicate it in the source code, and run clippy on the generate code directly. Then, the warning should point to actual culprit.

**Comment by Eijebong** [comment]
You're right

```
warning: this argument is passed by value, but not consumed in the function body
  --> src/main.rs:10:40
   |
10 |                                 _data: ::rocket::Data)
   |                                        ^^^^^^^^^^^^^^ help: consider taking a reference instead `&::rocket::Data`
   |
   = note: #[warn(needless_pass_by_value)] on by default
   = help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#needless_pass_by_value
```

**Comment by SergioBenitez** [comment]
I don't think there's anything we can do here, unfortunately, besides adding an `#[allow(needless_pass_by_value)]` to generated functions. However, that itself may cause a warning when not using clippy. If it doesn't, however, that'd be the way to go.

**Comment by Razican** [comment]
That second warning can be avoided by using `#[allow(unknown_lints, needless_pass_by_value)]`, I think.

**Comment by Mcat12** [comment]
Even better is: `#[cfg_attr(feature = "cargo-clippy", allow(needless_pass_by_value))]`

**Comment by SergioBenitez** [comment]
Closing this out as Clippy should be ignoring ignored arguments, especially code-generated ones.
