### ISSUE TITLE
Request: Add Rocket to TechEmpower web framework benchmarks

### ISSUE THREAD

**Issue by dessalines** [SergioBenitez/Rocket#296]
It would be great to see how Rocket compares against other web frameworks in speed. So far, `Iron` is the only one on there. 

Someone with some experience should work on adding it to the [TechEmpower Benchmarks](
https://www.techempower.com/benchmarks/).

https://github.com/TechEmpower/FrameworkBenchmarks

**Comment by mfirry** [comment]
> So far, Iron is the only one on there.

Not entirely true. [Check out here](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Rust), you can see they've got now `hyper`, `nickel` and a few others.

I've been helping with the Scala ones a little. 
I'm giving `Rocket` a try. 

Will keep you guys posted here.

**Comment by SergioBenitez** [comment]
I'm going to close this as it's not something we'll be doing ourselves. See my commentary in https://github.com/SergioBenitez/Rocket/issues/710#issuecomment-405721936 for more.
