### ISSUE TITLE
Allow multiple query string matchers, or custom query string matchers

### ISSUE THREAD

**Issue by rbalicki2** [SergioBenitez/Rocket#298]
I'd like for rocket to be able to match multiple objects to a query string. Namely, I would like to have a generic `LimitOffsetParam` that matches on `limit` and `offset`, and a separate parameter that is specific to whatever the particular route is doing. For example:

`#[get("/users?<LimitOffsetParam, UserSpecificQueryParam>")`

I think this implies that we would ignore unused query params, per #247 

Otherwise, I would be very happy to have a `LimitOffsetParam` that implements `FromRequest` and figures out the appropriate parameters from the query string. However, this causes the rocket to not match the route, so that is (currently) a no-go.

I think the third option is to have up with a macro that allows for structs to inherit each others' properties. Then, I could do something like

```
inherits!(LimitOffsetParam, struct MyOtherQueryParams {
...
})
```

If that's the best option, I could explore that.

This relates to #261 and #247

**Comment by SergioBenitez** [comment]
If I'm not mistaken, you can already do exactly what you want. The trait you need to implement is `FromForm`, not `FromRequest`, as [described in the guide](https ://rocket.rs/guide/requests/#query-strings).

**Comment by rbalicki2** [comment]
Hm. So, the way I see it is as follows:

* Using standard rocket, I can't declare multiple parameters that are populated from query strings. I'm limited to one, e.g. `/users?<param_1>`.
* So, instead I can have `param_1` implement `FromForm` and `param_2` implement `FromRequest`. That would work. But then, if I decide to remove `param_1`, I have to remember to put `param_2` in the angle brackets in the route declaration, which isn't ideal, either.
* I can't have both of them implement `FromRequest`, or the route will not match if I have any query params.
* I could also implement an `Any` type that allows for all query strings, and have both `param_1` and `param_2` implement `FromRequest`, which works but is also not ideal.

All of these seem like hacks :)

Perhaps there is a way to implement `FromForm` for a type that is generic across other types, e.g. a `all_my_query_params: Combo<LimitOffsetParams, MyUserParams>`

**Comment by SergioBenitez** [comment]
I believe @rbalicki2 and I handled this out of band, so I'm closing this out.

**Comment by SergioBenitez** [comment]
For posterity, here is the code for a `Both<A, B>` type that only validates a form if both `A` and `B` parse from the form:

```rust
use rocket::request::{FromForm, FormItems};

/// This trait is used to get the names of the fields of the structures.
pub trait NamedFields {
    const FIELDS: &'static [&'static str];
}

pub struct Both<A, B>(A, B);

impl<'f, A, B> FromForm<'f> for Both<A, B>
    where A: for<'x> FromForm<'x> + NamedFields,
          B: for<'x> FromForm<'x> + NamedFields,
{
    type Error = ();

    fn from_form_items(form_items: &mut FormItems<'f>) -> Result<Both<A, B>, ()> {
        let first_query_items: Vec<_> = form_items
            .filter(|&(ref k, _)| A::FIELDS.contains(k))
            .map(|(k, v)| format!("{}={}", k, v))
            .collect();

        let second_query_items: Vec<_> = form_items
            .filter(|&(ref k, _)| B::FIELDS.contains(k))
            .map(|(k, v)| format!("{}={}", k, v))
            .collect();

        let first_query_string = first_query_items.join("&");
        let second_query_string = second_query_items.join("&");
        let mut first_items = FormItems::from(first_query_string.as_str());
        let mut second_items = FormItems::from(second_query_string.as_str());

        let a = A::from_form_items(&mut first_items).map_err(|_| ())?;
        let b = B::from_form_items(&mut second_items).map_err(|_| ())?;
        Ok(Both(a, b))
    }
}
```

**Comment by rbalicki2** [comment]
Minor update: it should be `pub struct Both<A, B>(pub A, pub B)` in order to make the fields accessible elsewhere. Also, `FormItems` is already consumed the second time we iterate through it, so the line should be:

```
    let second_query_items: Vec<_> = FormItems::from(form_items.inner_str())
```

**Comment by rbalicki2** [comment]
I ended up turning this into a macro (for grouping arbitrary amounts of query params), and publishing it as a crate
https://crates.io/crates/query_param_group
