### ISSUE TITLE
Website - Guide typo (Responder)

### ISSUE THREAD

**Issue by kriskova** [SergioBenitez/Rocket#30]
There is a typo in the guide's Responses section. There is 'Reponder' instead of 'Responder' both in the side menu and the section title.

**Comment by SergioBenitez** [comment]
Good catch! Not sure how that got through.

I've pushed a fixed. Should be live withing ~15m. WIl close once it is.

**Comment by kriskova** [comment]
It's ok now 👍

**Comment by SergioBenitez** [comment]
Perfect! Thanks for the report!
