### ISSUE TITLE
rocket_contrib show old dependencies on crates.io

### ISSUE THREAD

**Issue by mp4096** [SergioBenitez/Rocket#300]
Hi! 

[`rocket_contrib`'s crates.io page for 0.2.7](https://crates.io/crates/rocket_contrib/0.2.7) lists obsolete dependencies, notably `^0.9` for `serde` and `^0.25` for `handlebars`. The same old versions show up in my `Cargo.lock` file.

The 0.2.7 release was 2 days ago, so I decided to create an issue. Maybe one needs to be more patient for the changes to be propagated? Feel free to close it anyway. Thanks!

**Comment by SergioBenitez** [comment]
Updating dependencies is a breaking change. The next breaking release, `0.3`, will include an update of all dependencies. Until `0.3` is released, dependencies won't be updated.

**Comment by mp4096** [comment]
Oh, I see, didn't know about this behaviour. Thanks for the quick response!
