### ISSUE TITLE
Compiler error: cannot find macro `routes!` in this scope

### ISSUE THREAD

**Issue by dmitryvm** [SergioBenitez/Rocket#303]
Compiler version: rustc 1.19.0-nightly

Cannot compile hello_world example because of this error

**Comment by SergioBenitez** [comment]
All examples are continuously checked (compiled, run, and tested) on the latest nightly release. Barring strange platform and environment dependent issues, it is not possible for an example _not_ to function if it is in this repository. 

Have you read the [getting started guide](https://rocket.rs/guide/getting-started/)?

Your issue doesn't adhere to the guidelines provided in the issue template. Unless you read through the issue template and provide all of the requested information, I won't be able to help you.

**Comment by dmitryvm** [comment]
I'm terribly sorry. I guess that was the "cargo update" command I didn't run. Thanks
