### ISSUE TITLE
Rocket-contrib 0.2.7 and serde 0.9 / 1.0

### ISSUE THREAD

**Issue by krampenschiesser** [SergioBenitez/Rocket#305]
I use rocket 0.2.7 with rocket_contrib.
Rocket contrib references serde 0.9 and rocket itself  serde 1.0.
This causes some trouble with 2 different serde versions in cargo.lock :(

I am using nightly on msvc

**Comment by SergioBenitez** [comment]
All 0.2 releases of `rocket` and `rocket_contrib` use serde 0.9.
