### ISSUE TITLE
Flexible logging system

### ISSUE THREAD

**Issue by divoxx** [SergioBenitez/Rocket#31]
First of all, I wanna say good job. This project looks very promising.

One thing that is bugging me is how logging is set up. The way it remaps the levels from the standard debug/info/warn/error/critical to debug/normal/critical is not very intuitive and doesn't seem to be easy or allow plugging your own logger.

I think making logger pluggable and moving the current implementation to contrib would be really good. Is that something that makes sense to implement? I might give it a shot.

**Comment by divoxx** [comment]
One more thing: changing the log system in a way that allows/support structured logging would be great too. Most large applications use structured logging nowadays, and having a log subsystem that supports it right at the core would be great. For example, https://github.com/slog-rs/slog

**Comment by SergioBenitez** [comment]
Thanks for the issue! Yes, logging needs a better story. There's an issue tracking this already, however: https://github.com/SergioBenitez/Rocket/issues/21. I'll close this in favor of the existing one, but feel free to chime in there, too.
