### ISSUE TITLE
Link to website from repository

### ISSUE THREAD

**Issue by cbrewster** [SergioBenitez/Rocket#32]
There does not seem to be a link anywhere on the REPO to https://rocket.rs or you could just add it to the REPO description.

**Comment by SergioBenitez** [comment]
How about a badge?

[![Rocket Homepage](https://img.shields.io/badge/web-rocket.rs-red.svg?style=flat&label=web&colorB=d33847)](https://rocket.rs)

**Comment by cbrewster** [comment]
@SergioBenitez a badge would work! also github lets you add a website to the repo when you edit the repo description. I think having both would be good though

**Comment by SergioBenitez** [comment]
Ah, of course. Just added that.

**Comment by SergioBenitez** [comment]
Fixed in https://github.com/SergioBenitez/Rocket/commit/1e2237d7263c0cad28384e40c25c414cacbf4e13.
