### ISSUE TITLE
Where to import State from for managed state?

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [SergioBenitez/Rocket#320]
This is a question.

Currently I am following the Rocket guide and arrived at the section about managed state (https://rocket.rs/guide/state/). As I am very new to Rust in general, I don't know where to import `State` from. Searching for such a general term had no results with any code example where anyone was importing it. Unfortunately in the guide there is also no example with the according `use` line for `State`. (I think there should at least be one example where `State` is imported.)
So Rustc now complains about it not being in the scope, but I also cannot find how to import it.

Where do I import `State` from? (And how can I find such information in the future?)

# Info

* Cargo version: `cargo 0.20.0-nightly (0d0f3baad 2017-06-13)`
* Rust version: `rustc 1.19.0-nightly (78d8416ca 2017-06-17)`
* Rocket version: `rocket v0.2.8` (I am not sure about this, since `cargo install --list` prints nothing for me and I got this info from running `cargo install --all-features`)

**Comment by SergioBenitez** [comment]
`State` is a top-level type. You can import it as follows:

```rust
use rocket::State;
```

The guide links to the `State` API documentation. Every page for a type in the API documentation shows the path to the type. If you were you click on the docs for `State`, for instance, you'd see the path `rocket::State`. The examples in the API docs also show how to import it.

**Comment by ZelphirKaltstahl** [comment]
@SergioBenitez Thanks! I did overlook that link in the text. Good to have it there. I still think it might help to put it in one example though.
Is it a common policy to have it only on the API docs pages?

**Comment by SergioBenitez** [comment]
Well, the approach I take in the guides is to link to API docs for detailed usage information and use the guide to provide an overview, intuition, and basic usage. We don't want to duplicate information, but we also don't want to see things only once in case something is missed. It's a hard balance.

**Comment by ZelphirKaltstahl** [comment]
@SergioBenitez So far the documentation on the Rocket page has been good and working and I got the managed state working now.

**Comment by SergioBenitez** [comment]
Awesome, glad to hear it @ZelphirKaltstahl!
