### ISSUE TITLE
Compilation fails for rocket-codegen on commit 539a7fc55b4d865a4aeb40f16d0852d8f5f113f1

### ISSUE THREAD

**Issue by kitsuneninetails** [SergioBenitez/Rocket#322]
Rocket version: github on commit: 539a7fc55b4d865a4aeb40f16d0852d8f5f113f1
OS: Ubuntu 16.04
Problem:
Compilation failure: 
Using the tip of rocket master via a git dependency:

  rocket = {git="https://github.com/SergioBenitez/Rocket"}
  rocket_codegen = {git="https://github.com/SergioBenitez/Rocket"}
  rocket_contrib = {git="https://github.com/SergioBenitez/Rocket"}

results in this error:

```
   Compiling rocket_contrib v0.3.0-dev (https://github.com/SergioBenitez/Rocket#ce363810) error: use of 
unstable library feature 'unicode': mainly needed for compiler internals (see issue #0)
   --> /~~~/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/ce36381/codegen/src/utils/mod.rs:116:22
    |
116 |     (c > '\x7f' && c.is_xid_start())
    |                      ^^^^^^^^^^^^
    |
    = help: add #![feature(unicode)] to the crate attributes to enable
```

Adding that feature flag to my root crate does not help.

However, adding the parent's commit number to the Cargo.toml DOES solve the problem (i.e. using a previous commit):

  rocket = {git="https://github.com/SergioBenitez/Rocket", rev="6a7fde6d"}
  rocket_codegen = {git="https://github.com/SergioBenitez/Rocket", rev="6a7fde6d"}
  rocket_contrib = {git="https://github.com/SergioBenitez/Rocket", rev="6a7fde6d"}

This is probably due to the changes in that commit (which I noticed removed the "unicode" import among some other related changes).

**Comment by Eijebong** [comment]
I think you need to update your nightly

**Comment by SergioBenitez** [comment]
You simply need to update your `rustc`, as @Eijebong states. Note that all commits are tested by two CIs, so you can look at the build status to inquire if there is, in fact, an issue with the build.

In any case, I've ensured that Rocket emits a nice error message when the installed version of `rustc` is old in 3f87b16d759e91386371ef0eb61df9a372ea8fec.

**Comment by kitsuneninetails** [comment]
Thank you.  It would have taken me many hours (or longer) to come to the conclusion that that particular esoteric error was due to the rustc being a couple days too old (I had last updated rustc a day before the required update).  The added error helps a great deal.
