### ISSUE TITLE
Latency question

### ISSUE THREAD

**Issue by egilburg** [SergioBenitez/Rocket#327]
@mrLSD Hi, followup to https://github.com/SergioBenitez/Rocket/issues/315, making new question since that issue is closed:

I'm trying out Rocket. I'm running the hello_world example with `ROCKET_PORT=8000 ROCKET_ENV=prod cargo run --release` options, and although I haven't tried concurrent throughput, I did observe comparative high latency for a single request:

```
$ time for i in {1..1000}; do    curl localhost:8000; done

Hello, world!Hello, world <snip 1000 times> Hello, world!Hello, world

real	0m14.202s
user	0m3.851s
sys	0m4.792s
```

This corresponds to about 14ms per request, much higher than described 150 microsecond on the readme.

P.S. `ROCKET_LOG=normal` or `ROCKET_LOG=critical` doesn't change those numbers for me. That being said, for actual production environments logging is usually necessary for security and monitoring reasons (in addition to debugging things that slipped past QA), so it'd be more realistic to include benchmarks with logging.

**Comment by AtomicBit** [comment]
``` bash
$ time for i in {1..1000}; do curl -s localhost:8000; done
real    0m9.112s
user    0m2.576s
sys     0m1.748s

$ time for i in {1..1000}; do wget -q localhost:8000; done
real    0m2.539s
user    0m0.124s
sys     0m0.336s
```
If I wrote some rust test to benchmark it I will get even better numbers I guess.

**Comment by SergioBenitez** [comment]
You're measuring something very different than what the `README` measures. Your small snippets measures the round-trip cost to:
  
  1. Fork a `curl` process.
  2. Have `curl` parse its parameters.
  3. Set-up a TCP connection to `localhost:8000`.
  4. Sent the HTTP request and have Rocket process it.
  5. Have `curl` process the response.
  6. Print the response to the screen.

Rocket is only involved in 1/6 of the above bullet points, which is what the `README` measures. In other words, most of what you're measuring isn't Rocket at all.

> That being said, for actual production environments logging is usually necessary for security and monitoring reasons (in addition to debugging things that slipped past QA), so it'd be more realistic to include benchmarks with logging.

Logging to the console is prohibitively expensive, and you don't want to be logging to the console in production. You also don't want to be logging _everything_. Instead, you likely want to log key pieces of information to a thread-local, in-memory buffer that is periodically coalesced and written out to disk by a logging thread. When done right, this approach should have negligible impact on Rocket's performance. Rocket doesn't offer something like this out of the box, at least not yet (see #21), so it wouldn't make sense to enable logging to benchmark Rocket.
