### ISSUE TITLE
How to upload image to the server?

### ISSUE THREAD

**Issue by Fuckoffee** [SergioBenitez/Rocket#328]

**Comment by cafeclimber** [comment]
[The raw_upload example gives a decent introduction to doing this.](https://github.com/SergioBenitez/Rocket/tree/v0.2.8/examples/raw_upload)

Additionally, there is [this](https://rocket.rs/guide/requests/#streaming) section in the guide.

**Comment by SergioBenitez** [comment]
This is either handled by the links @cafeclimber has posted, or required multipart support multipart forms support (#106). This also doesn't conform to the [issue requirements for questions](https://github.com/SergioBenitez/Rocket/blob/master/.github/ISSUE_TEMPLATE.md#questions).
