### ISSUE TITLE
Accept-encoding: gzip

### ISSUE THREAD

**Issue by tafia** [SergioBenitez/Rocket#329]
It would be very nice if rocket could have a `JSON` like `GZIP` wrapper.
I am not sure it is relevant but hyper seems to have an `Encoding::Gzip` header.

**Comment by selaux** [comment]
Hi, I'm currenlty writing something similar for the iron web framework: https://github.com/selaux/iron-pack. From what I understand this could be an optional request fairing, correct?

**Comment by SergioBenitez** [comment]
@tafia Do you mean that Rocket should automatically decompress GZIP-encoded HTTP streams? If so, while this would be nice, I know of no Rust library that can do this quickly enough to make sense. Also, this is something like should likely be handled upstream from Rocket, with the option for Rocket to enable/disable such functionality.

There was previous discussion on this on #195. In short, until Rust gains a mature, speedy implementation of gzip, we won't be able to do this.

@selaux You wouldn't (and really shouldn't) be able to do this using a fairing. You can't rewrite body data using a fairing.

**Comment by tafia** [comment]
Thanks for pointing me toward #195. I believe I will implement my own responder!
