### ISSUE TITLE
Could not find `local` in `rocket`

### ISSUE THREAD

**Issue by mrLSD** [SergioBenitez/Rocket#331]
Rocket version: `latest`
Rust: `rustc 1.20.0-nightly (f590a44ce 2017-06-27)`
OS: `Ubuntu 16.04`

I clone github `rocket` repo.
`cd rocket/examples/redirect`

Change Cargo.toml:
```
[dependencies]
rocket = "*"
rocket_codegen = "*"
```

Run `cargo test`

And I have got error:
```
error[E0432]: unresolved import `rocket::local::Client`
 --> src/tests.rs:2:5
  |
2 | use rocket::local::Client;
  |     ^^^^^^^^^^^^^^^^^^^^^ Could not find `local` in `rocket`

error: aborting due to previous error(s)
```

How to fix it?

**Comment by SergioBenitez** [comment]
`local` is only in `0.3`, but the latest release is `0.2`.
