### ISSUE TITLE
Problem building Rocket example handlebars_templates

### ISSUE THREAD

**Issue by rajeev** [SergioBenitez/Rocket#332]
I get the following error when building the example. What am I doing wrong?

Rajeevs:handlebars_templates kane$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/SergioBenitez/hyper-rustls`
error: no matching package named `rocket` found (required by `cookies`)
location searched: file:///Users/kane/venvs/sfmobile/rusttest/rocket/lib
version required: = 0.2.4

 I searched the issue tracker for similar issues faced by others, but could not find anything.

I tried deleting my ~/.cargo/ directory and started from scratch. Also pulled the latest from github:

Updating ef4c2fd..1f367af

**Also when building from my own sample project (main.rs copied from handlebars example):**

Compiling webtest v0.1.0 (file:///Users/kane/venvs/sfmobile/rusttest/webtest)
error[E0277]: the trait bound `TemplateContext: serde::ser::Serialize` is not satisfied
  --> src/main.rs:33:5
   |
33 |     Template::render("index", &context)
   |     ^^^^^^^^^^^^^^^^ the trait `serde::ser::Serialize` is not implemented for `TemplateContext`
   |
   = note: required by `rocket_contrib::Template::render`

error[E0599]: no method named `attach` found for type `rocket::Rocket` in the current scope
  --> src/main.rs:46:10
   |
46 |         .attach(Template::fairing())
   |          ^^^^^^

error[E0599]: no function or associated item named `fairing` found for type `rocket_contrib::Template` in the current scope
  --> src/main.rs:46:17
   |
46 |         .attach(Template::fairing())
   |                 ^^^^^^^^^^^^^^^^^

error: aborting due to previous error(s)

error: Could not compile `webtest`.

To learn more, run the command again with --verbose.

**Comment by SergioBenitez** [comment]
You cannot simply copy the code from an example in the repository to a different directory and run it; the code in the repository directly references itself. You also can't use the example code from the `master` branch of the repository directly; the version in `master` isn't published anywhere.

You should switch to the `v0.2.8` tag (`git checkout v0.2.8`) to see the example compatible with the latest released version of Rocket. You can then copy those examples elsewhere and run them.

**Comment by SergioBenitez** [comment]
Hopefully this is answered. Please feel free to continue commenting if not.

**Comment by rajeev** [comment]
Hi Sergio,

In the first build log, I am building directly within rocket (within the rocket/examples/handlebars_templates/ directory.

On the copied (webtest) project:
Of course, only the main.rs is copied. The Cargo.toml was adapted. This was the Cargo.toml at the time of the build[1]. Note: I was attempting to use tera in my custom project and so I removed handlebars from the deps.

I will try checkout 0.2.8 and see how that works.

[1] Cargo.toml in custom project
[package]
name = "webtest"
version = "0.1.0"
authors = ["Rajeev J Sebastian <rajeev@alokin.in>"]

[dependencies]
rocket = "0.2.8"
rocket_codegen = "0.2.8"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["tera_templates", "json"]

**Comment by rajeev** [comment]
Thanks Sergio. Both the handlebars_templates and my custom copy worked.

For reference, this is the Cargo.toml I used:

[package]
name = "webtest"
version = "0.1.0"
authors = ["Rajeev J Sebastian <rajeev@alokin.in>"]

[dependencies]
rocket = "0.2.8"
rocket_codegen = "0.2.8"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"

[dependencies.rocket_contrib]
version = "0.2.8"
default-features = false
features = ["tera_templates", "json"]
