### ISSUE TITLE
Could not compile 'state'

### ISSUE THREAD

**Issue by aramun** [SergioBenitez/Rocket#333]
I can't build, here the stack trace:

   Compiling term-painter v0.2.3
   Compiling rocket_codegen v0.2.8
   Compiling rocket v0.2.8
   Compiling state v0.2.2
   Compiling idna v0.1.2
   Compiling unicase v1.4.2
error[E0554]: #[feature] may not be used on the stable release channel
 --> /Users/byte01/.cargo/registry/src/github.com-1ecc6299db9ec823/state-0.2.2/src/lib.rs:1:1
  |
1 | #![feature(const_fn)]
  | ^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `state`.
Build failed, waiting for other jobs to finish...
error: build failed

**Comment by Eijebong** [comment]
Rocket only works with rust nightly.

**Comment by SergioBenitez** [comment]
As explained in the guide and documentation, Rocket only compiles on Rust nightly. Please use `rustup default nightly` to set nightly as your default tool chain.
