### ISSUE TITLE
weird issue with or_forward() with the session example

### ISSUE THREAD

**Issue by bbigras** [SergioBenitez/Rocket#334]
from master
- rocket 0.3.0-dev
- rocket_codegen 0.3.0-dev
- rocket_contrib 0.3.0-dev

Arch Linux

When I run the example in `examples/session` I can log in but if I refresh I'm not logged anymore.

I changed `from_request` to:
```rust
fn from_request(request: &'a Request<'r>) -> request::Outcome<User, ()> {
    let u = request.cookies()
        .get_private("user_id")
        .and_then(|cookie| cookie.value().parse().ok())
        .map(|id| User(id));

    println!("u: {:?}", u);
    
    let result = u.or_forward(());

    println!("result: {:?}", result);

    result
}
```

and I see:
```
u: Some(User(1))
result: Outcome::Forward
```

I think the result shouldn't be forward.

**Comment by SergioBenitez** [comment]
Huh. Looks like the methods had a stub implementation instead of the real one.

Fix is incoming. Thanks so much for reporting this, especially for doing a bit of debugging!
