### ISSUE TITLE
max(number_of_cpus, 2) cannot be parsed in Rocket.toml

### ISSUE THREAD

**Issue by denysvitali** [SergioBenitez/Rocket#336]
Version of Rocket: `0.2.8`
Version of Rust: `rustc 1.20.0-nightly (2fbba5bdb 2017-07-04)`
Version of Cargo: `cargo 0.21.0-nightly (eb6cf012a 2017-07-02)`

I've noticed in [the docs](https://api.rocket.rs/rocket/config/) and [the guide](https://rocket.rs/guide/overview/#namespacing) that it is possible to specify a number of workers. Specifically I was interested in the `workers = max(number_of_cpus, 2)` config entry.

Unfortunately it seems that `max(number_of_cpus, 2)` isn't a valid value even though it is documented in both the docs and the guide. Apparently `workers` only accepts integers.

Is the `max(number_of_cpus, 2)` pseudocode or it is a valid statement and the error is not intended?

Minimal reproducible `Rocket.toml`

```
[global]
workers = max(number_of_cpus, 2)
```

Result:
```
dvitali@denvit-ws1:prj/be ‹master*›$ cargo run                                                                                                                                                  -1-
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/be`
Error: config file could not be parsed as TOML
    => at "/home/dvitali/rust/prj/be/Rocket.toml":2:11
    => 'm' - expected a value

```

**Comment by mehcode** [comment]
I guess that is a bit confusing. What the guide means is that the _expression_ `max(number_of_cpus, 2)` is the default setting for workers. 

You couldn't set that yourself from the toml file as a toml file is just a static configuration file.

**Comment by denysvitali** [comment]
Oh, I see. This makes a lot more sense

**Comment by SergioBenitez** [comment]
The documentation states:

> The workers parameter is computed by Rocket automatically; the value above is not valid TOML syntax. When manually specifying the number of workers, the value should be an integer: `workers = 10`.

The guide also states:

> The workers parameter is computed by Rocket automatically; the value above is not valid TOML syntax.

The latter statement has been expanded in the unreleased version of the guide. The documentation also presently (in the unreleased version) shows the number as:

```rust
workers = [number_of_cpus * 2]
```

to try to illuminate the fact that it is not valid syntax.

Do you think this is sufficient, or is there something we can do better to highlight this?

**Comment by denysvitali** [comment]
Well, I think I haven't read the invalid TOML syntax part before trying it on my own. I think it is just me, and I definitively should learn to read everything before testing things 😄 

Maybe putting the text before the TOML example would better highlight that the thing the user is going to read isn't indeed a valid syntax, but that `workers` value is what internally Rocket defaults to.

![screenshot from 2017-07-05 23-20-29](https://user-images.githubusercontent.com/4939519/27885514-8fdbd618-61d8-11e7-8805-dfaed64e809d.png)

My bad, sorry about this issue

**Comment by SergioBenitez** [comment]
Ah, alright. I'm closing this for now. If we find that this is an issue for others, we'll see what we can do. Thanks for reporting this!

**Comment by shalugin** [comment]
I've made the same mistake :)

**Comment by messense** [comment]
I've made the same mistake the first time I try Rocket.
