### ISSUE TITLE
Implement Rocket::launch that returns Result

### ISSUE THREAD

**Issue by fireantik** [SergioBenitez/Rocket#34]
It should be possible for application to handle errors. For example when binding to already used port, application could decide to bind to an alternative port.

Same applies for Rocket::ignite or any other function that can panic but does not have Result alternative.

**Comment by fireantik** [comment]
Yes, `launch` should block. It is consistent with how other web servers work (iron, nickel) and besides, how would we make it not block? Make Rocket run `launch` in a thread? That seems like it would create its own set of issues.

I like the idea of separating bind and run loop, if it would be possible to bind to multiple ports and addresses (possibly with different http/s combinations) and then handle connections from all with a single run loop, that would be amazing. However, I am not sure if it is even possible. AFAIK iron cannot do that, not sure if hyper can.

**Comment by anderejd** [comment]
A callback on success would allow further actions, like launching an embedded browser to connect to the resulting listening port (if a port was picked by the system instead the Config).

**Comment by anderejd** [comment]
> I ask because, if so, I'd suggest for a slightly lower-level interface to be exposed as well. That'd allow framework users to start tasks after successful binds, for instance.

This case is solved by https://github.com/SergioBenitez/Rocket/pull/210

**Comment by SergioBenitez** [comment]
I think we can be a tad-bit more clever here, but I agree. Let's get this in for 0.3.

**Comment by mehcode** [comment]
An interesting hack would be to make `::launch()` use a new thread to start the server and then `.join()` it in the Drop (which I think is default for rust's threads).

Your normal examples would all work the same but something like this would also work:

```rust
fn main() {
  // ignore the obvious port conflict here
  let _ = rocket::ignite().launch();
  let _ = rocket::ignite().launch();
}
```

**Comment by SergioBenitez** [comment]
Someone (maybe you?) proposed this, but it just feels like too much magic. I had in mind something much simpler: return a `Result<(), RocketError>` where `RocketError` implements drop and simply prints the error out the console. This exactly emulated the behavior we have right now, and the behavior most will want, while still letting someone catch it.

**Comment by mehcode** [comment]
I can't imagine myself ever wanting multiple rocket servers running from the same main so don't want it that much. It's super easy to have N binaries in the same cargo project anyway.

I'm fine with the simpler option.
