### ISSUE TITLE
[Feature request] Type safe template support

### ISSUE THREAD

**Issue by Dandandan** [SergioBenitez/Rocket#340]
Rocket tries to be type-safe. From the home page https://rocket.rs: "From request to response Rocket ensures that your types mean something." Currently, the template systems included (handlebars, tera) are not type safe and can result in run time errors. An example of type safe template system is: https://github.com/djc/askama 
Rocket has already supports two non type safe template systems in contrib, a type safe version would be more in the spirit of Rocket.

**Comment by jaroslaw-weber** [comment]
I love rust safety, but I think it is not necessary in templates. It may add some unnecessary complexity.
The main problem is that the askama crate is not stable. There will be some maintenance work added when upgrading a version.

> Because Askama will generate Rust code from your template files, the crate will need to be recompiled when your templates change. 
there is a refresh option although it may be difficult to make it play nice with rocket

Although it would be nice to have optional type-safe templates, I think there are more urgent issues.

**Comment by Korvox** [comment]
Tera had a discussion about making the templates type safe here: https://github.com/Keats/tera/issues/24

**Comment by Dandandan** [comment]
There is also maud https://github.com/lfairy/maud/blob/master/README.md

**Comment by Korvox** [comment]
The main problem with compile time templates in regards to Rocket is that Rocket's Template API uses Serde to pass template arguments in to the respective rendering engines, which... isn't a generic templating api anymore.

The better idea would probably to produce wrappers of these compiled template libraries as farings, and the libraries would just export a Responder to return from routes that supports the Templating system.

The best option, IMO, would be for anyone interested to just make rocket-askama and/or rocket-maud crates that provide a fairing and responder the way the contrib Template api does, but they would have to be library specific. That way you preserve the typing, which is the whole point of these template libraries.

**Comment by Dandandan** [comment]
I moved to Maud now, seems almost what I want :)

**Comment by SergioBenitez** [comment]
I'd be really excited to see a full-featured, easy to integrate, compile-time checked, and general purpose templating library for Rust that is subsequently integrated into Rocket. Unfortunately none appear to exist at the moment. All of the available options, with the exception of Maud which isn't general purpose, appear to be rather nascent. Until such an option exists, it's difficult to contemplate what such an integration might look like.

That being said, I think something will eventually exist, and I agree that Rocket should support it as a first-class citizen. The approach to incorporating support for a compile-time templating engine will likely differ substantially from what Rocket does now. Whatever form it takes, it should be as easy and usable as what we have now. If anyone wants to experiment, I'd be more than happy to review and advise on potential integration strategies!

**Comment by djc** [comment]
@SergioBenitez since yesterday, [Askama](https://github.com/djc/askama) master includes optional support for Rocket, by implementing `Responder` for any struct that derives `Template`.

Test case (which also serves as a good example) here:

https://github.com/djc/askama/blob/master/testing/tests/rocket.rs

Code generation happens here:

https://github.com/djc/askama/blob/master/askama_derive/src/generator.rs#L652

I'd be happy to have you review this integration for potential improvements (the two `unwrap()` calls in the generated code are obvious candidates); I'm also curious, specifically for Askama's case, what about it makes you consider it "nascent".

**Comment by Korvox** [comment]
@djc I'm confused what kind of integration Rocket could even do with Askama. You build them before the main project - you don't have any inits, so you don't need a fairing or other wrapper init structure in main like the dynamic templates. Rocket itself isn't overriding the build process so it can't automagically inject the Askama template build stage to my knowledge. The types constructed are already Responders, so you can just return them. There is no boilerplate already, so what would Rocket integration look like?

I'd definitely see and support adding a subsection under the Handlebars / Tera template description in the contrib docs saying Askama and Maud are typesafe template systems that support Rocket. Should at least tell users these options exist if they want them.

**Comment by djc** [comment]
@Korvox I'm not saying Rocket needs to write any code for Askama integration, I'm merely asking if Sergio (and others) have feedback on the Rocket integration I built into Askama.

**Comment by flavius** [comment]
Why is maud not mentioned in the docs?

**Comment by mgattozzi** [comment]
@flavius because those are not in `rocket_contrib` right now. Terra/Handlebars is the only one supported right now.

**Comment by djc** [comment]
FYI, I released a new version of Askama that includes the Rocket integration (but without the `unwrap()`s); for more, see the [changelog](https://github.com/djc/askama/releases/tag/0.4.0).

**Comment by SergioBenitez** [comment]
Askama and other upstream libraries are good choices! We'll leave it up to the broader ecosystem to fill in the gap here.
