### ISSUE TITLE
Why is not there a `Responder` implementation for a bool?

### ISSUE THREAD

**Issue by vityafx** [SergioBenitez/Rocket#341]
As I see in the [docs](https://api.rocket.rs/rocket/response/trait.Responder.html) there is no `Responder` trait implementation provided for the `bool` type by the library. Why is it so? I would like to have a simple `API` server which on some methods returns 200 OK and some other error status (404, for example). This can easily be done by using `bool` type as same as we have `Option<T>` in the docs.

**Comment by SergioBenitez** [comment]
It's not clear what the semantics of returning a `bool` would be. Why is a `false` a **404**? Why is the body empty? What would `true` imply?

The short answer: a `bool` doesn't convey enough information to allow a default implementation for it. The behavior you're looking for could be easily implemented via a custom enum with two nullary variants along with a `Responder` implementation for that enum.

**Comment by vityafx** [comment]
How does a `Option<T>` gives enough information then?

- Option<T>

    If the Option is Some, the wrapped responder is used to respond to the client. Otherwise, an Err with status 404 Not Found is returned and a warning is printed to the console.

**Comment by SergioBenitez** [comment]
`None` implies that there's nothing there when there could be. Unlike `false`, `None` is not a value, it's the absence of a value.

**Comment by vityafx** [comment]
Okay. Thanks for the response.
