### ISSUE TITLE
Testing feature has disappeared?

### ISSUE THREAD

**Issue by vityafx** [SergioBenitez/Rocket#344]
This is a question:
1. Rocket 0.3.0 (git, master branch)
2. Tried to find in the docs, in the rocket code itself, on the rocket.rs.
3. The answer should include all the needed information about writing the tests.

I don't see any `testing` feature in the `rocket 0.3.0`. I also can't find any `MockRequest` structs in the docs, and the [`examples/testing`](https://github.com/SergioBenitez/Rocket/blob/master/examples/testing/src/main.rs) does not have it. How to unit-test my rocket code?

There is another question, about using the unit-testing of the rocket: I have 2 submodules of my crate, which provide different routes. Is it possible to include the tests into each submodule's local `test` submodule? As from what I see in the `examples/` directory there is no way to organize the code like this, because rocket must be launcher from somewhere..

**Comment by SergioBenitez** [comment]
See the Rocket 0.3 [CHANGELOG](https://github.com/SergioBenitez/Rocket/blob/v0.3.0/CHANGELOG.md).
