### ISSUE TITLE
Nix-expression for nix-build for Rocket

### ISSUE THREAD

**Issue by greglearns** [SergioBenitez/Rocket#346]
Rocket 0.2.9 can be compiled using Nix and the Rust nightly overlay if one uses `nix-shell` or `nix-env`: 
https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.md#using-the-rust-nightlies-overlay

However, in order to use `nix-build` (so that one can deploy using `nixops`, for example), it's not so clear how to proceed. This is the closest I got to making it work:
https://gist.github.com/greglearns/192a4cc31aef8acdf3190fefa4f124ee

But, it produces an error.

Has anyone had success producing a Nix-expression for Rocket.rs?

cc @flosse

**Comment by SergioBenitez** [comment]
@flosse I recall that you were using Rocket with Nix. Would you be able to field this questions?

**Comment by flosse** [comment]
Yes, I'm running NixOS on my systems :)
Unfortunately I cannot show you a way how to create a proper Nix-expression for Rocket :(
I tried it once but it was quite time consuming so I stopped packaging it.
My current workaround is to compile my application with `musl` (https://github.com/solson/rust-nightly-nix#compile-with-musl) and then I just copy the binary to the target. I know that this is totally against the idea of Nix but after all it works ;-)

Maybe @qknight can help us!?

**Comment by qknight** [comment]
@flosse no, never used before.

**Comment by greglearns** [comment]
@flosse can you share your configuration? It sounds like an effective solution.

**Comment by uniphil** [comment]
I use nixos with [the nixpkgs-mozilla overlay](https://github.com/mozilla/nixpkgs-mozilla), which has all the latest rust releases including nightlies. Maybe this information will help someone:

- [Rust install steps](https://github.com/mozilla/nixpkgs-mozilla#rust-overlay)

I use nix-shell for rust projects. My basic `shell.nix` for a rocket project looks like this:

```nix
with import <nixpkgs> {};

stdenv.mkDerivation {
    name = "rust";
    buildInputs = [
        rustChannels.nightly.cargo
        rustChannels.nightly.rust
    ];
}
```

Here are [some more nix+rust examples](https://github.com/uniphil/nix-for-devs#rust) (no promise of quality beyond "worked for me" there though).

**Comment by SergioBenitez** [comment]
Was this resolved, @greglearns? Can we close out this issue?

**Comment by greglearns** [comment]
So, my understanding is that Nix removed (or will remove) Rust Nightly (which didn't work with Rocket anyway), and instead will rely on the Mozilla Overlay (which it seems that no one has ever made work with `nix-build`). So, it seems like the only way to make Rocket work with nix-build is to build Rocket apps yourself using `nix-shell` on your box or in a Docker container (optionally, you can use MUSL), and then add the compiled output. i.e. you can't do a one-step nix-build and then deploy, you have to do a two-step (build locally, usually using nix-shell, and then deploy the output of that build). Not really fun.

As a (sad) result, I had to stop using Rocket ;-( and instead build directly on futures and async Hyper.

I think that you can close this topic for now.

**Comment by SergioBenitez** [comment]
That's a bummer. Hopefully things will improve on Nix soon. Thanks for the update, @greglearns.
