### ISSUE TITLE
Autoconfiguration of TLS certificates using let's encrypt

### ISSUE THREAD

**Issue by est31** [SergioBenitez/Rocket#349]
It would be cool if Rocket could automatically configure TLS certificates like [caddy](https://caddyserver.com/docs/automatic-https) does. Then the server owner doesn't have to do recurrent manual work any more to keep TLS working. As library, one could use https://github.com/onur/letsencrypt-rs .

**Comment by alex** [comment]
I have an implementation of this for rustls here: https://github.com/alex/ct-tools/blob/master/src/letsencrypt.rs

Example of configuring it here: https://github.com/alex/ct-tools/blob/master/src/main.rs#L229-L242

I'd be delighted if someone were to take that code and turn it into a real library, rather than "just enough to work for my use case" :-)

**Comment by SergioBenitez** [comment]
It should be possible, and indeed fairly simple if using a DNS challenge, to implement an attach fairing that automatically configures TLS with Let's Encrypt, entirely outside of Rocket. I don't see something like this being part of Rocket core or contrib, but I think it would be a great contribution to the Rocket ecosystem!

**Comment by SergioBenitez** [comment]
For the reasons outlined above, I'm closing this issue out. I'd love to see an implementation of this, however!

**Comment by uwearzt** [comment]
I would love to have that inside rocket (with the HTTP validation), because on some hosted websites it is not easily possible to fullfill the DNS challenge automatically. 

May be a plugin for rocket?

**Comment by ctsrc** [comment]
For anyone coming across this via Google, here is a permanent link to the code referenced by @alex above: https://github.com/alex/ct-tools/blob/ee77adac1a56ccd0f358238bfeedb2edb3cc1309/src/main.rs#L229-L242

And here it is in the most recent version of that file as of this writing: https://github.com/alex/ct-tools/blob/947880714460d980fc9a82f5defb917a8bbcdc03/src/main.rs#L308-L323

**Comment by alex** [comment]
Please note that my code uses the TLS-SNI-01 challenge, which is now disabled due to a security issue that was discovered. (I eventually plan to port it over to the http challenge, but E_NOT_ENOUGH_HOURS_IN_A_DAY)

**Comment by jrmiller82** [comment]
New user testing out Rocket; why is this not a planned feature inside Rocket (which is an HTTP server?!?)? Other libraries you literally tick a boolean a la `USE_LETS_ENCRYPT = True` and supply the email you want to use with Let's Encrypt. It's 2019. This deserves reconsideration.

**Comment by SergioBenitez** [comment]
@jrmiller82 It's entirely possible to implement this outside of Rocket. I'd gladly accept an implementation into `rocket_contrib`!

**Comment by jrmiller82** [comment]
@SergioBenitez What is the reason for this not being part of the main Rocket crate? 

> It should be possible, and indeed fairly simple if using a DNS challenge, to implement an attach fairing that automatically configures TLS with Let's Encrypt, entirely outside of Rocket. I don't see something like this being part of Rocket core or contrib, but I think it would be a great contribution to the Rocket ecosystem!

Sure, that may have made sense in 2017. It's no longer 2017 and many web browsers are moving to where they won't even view unencrypted content. LetsEncrypt is a wonderful free solution to this. Why should this not be part of core?

**Comment by SergioBenitez** [comment]
@jrmiller82 My stance two years ago was that this would make sense entirely out of Rocket. My stance now is that I'd love to have an implementation inside of Rocket's `contrib` library.

In general, whatever _can_ be outside of core _should_. This is so to 1) reduce code in `core` for compile time and maintenance reasons, 2) ensure that Rocket's core APIs allow for easy extension through dog-fooding, and 3) create a logical separation between what is only possible in `core` and what can be done by any external party. Another rule of thumb is to ask: is it likely that the _vast majority_ of Rocket applications will make use of this? If the answer is no, I believe we should err on the side of placing a feature in `contrib`.
