### ISSUE TITLE
Form Validations surplus code

### ISSUE THREAD

**Issue by mrLSD** [SergioBenitez/Rocket#351]
I have usual form validation cicle:
- fetch form fields:
for example:
struct UserLoginForm {
    username: String, // 'UserLogin[username]' required 
    password: String, // 'UserLogin[password]'  required
    age: uint8, // 'UserLogin[age]' should be > 18
}
- I should always return validation results (exist fields in the form or not)
- I should validate with useful validators. For example: required, min, max, and many-many other
- I should generate error depend of current supported error messages.
- I should send all errors message and error fields
- It should have reusable, fast writing, compact code.

Let's look to example:
https://github.com/SergioBenitez/Rocket/tree/v0.3.0/examples/form_validation

I see incredible boilerplate code. What if I have 100 form? I need for validation field create new type, implement `from_form_value`, and it's not pre existed validators.

It is very uncomfortable.

I looking for: 
`fn login<'a>(user_form: Form<'a, UserLogin<'a>>)`

and I see part of validation in the handler. Is's very bad practice.

I don't have out of the box useful validations, error message + fields gathering, error message configuration for multi lang.

It's not usable for real world applications. It's difficult to support that code.

It's possible creating form validation rules by code generation, for type checking, validation by useful validations, error message for fields generator. And without boilerplate code.

Do you have any plans for that?

**Comment by Korvox** [comment]
Keats has useful struct validation I've been using in my Rocket projects found [here](https://github.com/Keats/validator).

It isn't just the prebaked valdiators, its done the boilerplate to add validators by just supplying function definitions. 

I believe he meant to rewrite the error handling to be better but has not gotten around to it yet. I don't find much lacking personally.

Note that you will have to call validate on your form after getting it if you use Validator, though. So you get() from the form and then validate()? on the struct.

**Comment by mrLSD** [comment]
HI, @Korvox,
thank you for response. It's really interesting decision. But error messages handling look like pretty bad.
And my basic issue that complex and useful form validation not included to Rocket.

**Comment by tomhoule** [comment]
Just as a small side-note, validator 0.6.0 is out and it looks like it contains the redesign @Korvox mentioned: https://github.com/Keats/validator#060-20170912

**Comment by SergioBenitez** [comment]
I don't think we'll do much besides what Rocket has now, which is pluggable and allows you to overlay something like https://github.com/Keats/validator ergonomically. In particular, you can define some wrapping type, say, `Validated`, that will automatically validate using the `validator` crate. Such an implementation is below:

```rust
use rocket::request::{FromForm, FormItems, FormParseError};
use validator::{Validate, ValidationError, ValidationErrors};

struct Validated<T>(T);

impl<T> Deref for Validated<T> {
    type Target = T;

    fn deref(&self) -> &T {
        &self.0
    }
}

impl<'f, T> FromForm<'f> for Validated<T>
    where T: Validate + FromForm<'f, Error = FormParseError<'f>>
{
    // In practice, we'd use a more descriptive error type.
    type Error = ValidationErrors;

    fn from_form(items: &mut FormItems<'f>, strict: bool) -> Result<Self, Self::Error> {
        let value = T::from_form(items, strict).map_err(|error| {
            let mut validation_errors = ValidationErrors::new();
            match error {
                FormParseError::BadValue(name, value) => {
                    let mut v_error = ValidationError::new("bad_value");
                    v_error.add_param("name".into(), &name.as_str());
                    v_error.add_param("value".into(), &value.as_str());
                    validation_errors.add("rocket-form-field", v_error);
                },
                FormParseError::Unknown(name, value) => {
                    let mut v_error = ValidationError::new("unknown_value");
                    v_error.add_param("name".into(), &name.as_str());
                    v_error.add_param("value".into(), &value.as_str());
                    validation_errors.add("rocket-form-field", v_error);
                },
                FormParseError::Missing(name) => {
                    let mut v_error = ValidationError::new("missing_value");
                    v_error.add_param("name".into(), &name.as_str());
                    validation_errors.add("rocket-form-field", v_error);
                }
            }

            validation_errors
        })?;

        value.validate()?;
        Ok(Validated(value))
    }
}
```

With this type, you can use the `validator` create transparently:

```rust
#[derive(Debug, FromForm, Validate)]
struct UserLogin {
    #[validate(length(min = 1))]
    username: String,
    #[validate(length(min = 6))]
    password: String,
    #[validate(range(min = 18, max = 120))]
    age: u8,
}

#[post("/login", data = "<user>")]
fn login(user: Form<Result<Validated<UserLogin>, ValidationErrors>>) -> Result<Redirect, String> {
    if let Err(errors) = &*user {
        return Err(errors.to_string());
    }

    let user = user.as_ref().unwrap();
    if user.username == "Sergio" && user.password == "password" {
        Ok(Redirect::to("/user/Sergio"))
    } else {
        Err("Unknown user or password.".to_string())
    }
}
```

You can, of course, simplify the type of `user` by implementing other versions of `Validated` in combination with traits like [`FromDataSimple`](https://api.rocket.rs/v0.4/rocket/data/trait.FromDataSimple.html). For instance, an implementation of `FromDataSimple for Validated<T, Error = ValidationErrors>` would allow you to omit the `Form` part of the signature.

With this, I'm closing out the issue. Rocket is intended to be pluggable to allow any library to add Rocket's feature in what feels first class. I hope the example I've provided attests to the ability to do so today.
