### ISSUE TITLE
How to get a client socket from rocket?

### ISSUE THREAD

**Issue by vityafx** [SergioBenitez/Rocket#353]
I need to get a client socket from rocket's handler and to work with it later. Is this possible to do?
Or, I may handle connections with another thread and to pass client's socket requests to the rocket instance.

To clarify my intentions, this is what I need:

0. 2 kind of clients: X and Y.
1. X-Client connects to the rocket (server) and performs REST-api requests.
2. Rocket responses to the requests of X-client but does not close the socket, just leaves it live it's own life.
3. I remember this X-client socket from the message handler in some `hashmap`.
4. Y-client calls another REST-api calls (I have 2 rocket mounts, one for X and one for Y clients).
5. The message handler sends some data to X-client socket and answers Y-client "the query has been sent successfully, 200".
6. The X-Client sends the answer on the Y-client's request back to the rocket by calling X-client's rest-api methods.

X -> Rocket <- Y

As from what I think this can be done in 2 different ways:
1. I handle the X-client connections by myself and then forward them to the rocket somehow.
2. I leave this to `rocket` itself and get sockets from there.

**Comment by SergioBenitez** [comment]
There's no support for either of these in Rocket. I'm not sure how they would work, actually; Rocket (Hyper, really) needs to handle the client socket directly to properly implement HTTP.

This is a pretty odd thing to want to do. From the sound of it, you'd be better off having the client connect to two different servers. Can you perhaps explain what you're actually trying to do?

**Comment by vityafx** [comment]
I need to provide a custom logic for sockets but they must also work as simple http client. So, I want to have a persistent connection between a client and the server. This how it should work:

1. Client connect to http server, says "hello" via http rest api.
2. Server answers "ok", but does not close the connection.
3. Another client calls another resp-api endpoind of my rocket server and the the rocket server sends http request to the client which connected at 1. stage.

**Comment by SergioBenitez** [comment]
This is definitely outside the scope of Rocket, at least for the time being. Something like WebSockets is likely more amenable to solving your problem. You're essentially trying to implement a publish/subscribe and broadcasting mechanism, something that web sockets is perfect for.

Rocket will eventually have support for web sockets out of the box (#90). Until then, you can use one of the available Rust web socket libraries. I've included information about how to use them alongside Rocket in https://github.com/SergioBenitez/Rocket/issues/90#issuecomment-304725055.

**Comment by vityafx** [comment]
@SergioBenitez thanks for the answer! Close the issue if you think it is needed to be closed.

**Comment by vityafx** [comment]
Hello again! Has anything been changed since our last discussion? I see there is a `rocket::Request::remote()` method which returns the `SocketAddr`:

> Returns the address of the remote connection that initiated this request if the address is known. If the address is not known, None is returned.

So if this is a socket, I think it would be not very difficult to add a `socket_handle()` method for it. It will be helpful also for custom implementations of `Connection: keep-alive` so that, for example, I could implement my own responder which took `&Request` as function argument and I could take a socket handle from it and then do something with it.

If you still think that it is very bad to do this in **rocket** itself, could you give me any hint how I could use **rocket** and get a socket handle, just any method please, because the framework is very simple to use and useful and I don't want to waste my time on rewriting my server in other frameworks or even from scratch using linux's headers.
