### ISSUE TITLE
generated param `match`es contain unignored unreachable patterns

### ISSUE THREAD

**Issue by durka** [SergioBenitez/Rocket#356]
The provided implementation of `FromParam` for `Option<T>` sets the error type to `!`. Therefore, the `Err` arm in the generated `match` is unreachable (see [example](https://gist.github.com/durka/c4a7adb095ac76209c6e7385bfd9e3ee#file-expanded-rs-L196)). When `#![feature(never_type)]` is enabled, the `unreachable_patterns` lint can detect this (see also https://github.com/rust-lang/rust/issues/39858). Therefore, the generated code needs to disable the warning or omit the `Err` arm.

Meta:
Rocket 0.3.0
Debian Sid
rustc 1.20.0-nightly (8f1339af2 2017-07-16)

**Comment by SergioBenitez** [comment]
We should definitely emit an `#[allow(unreachable_patterns)]` attribute for matches emitted by Rocket. This is a simple improvement, and I'd be happy to review an implementation!

**Comment by durka** [comment]
Working on it.

**Comment by SergioBenitez** [comment]
Closed via #362 and 02794db2cd6646d21cd834e99c3e86e2a600ddb2.

**Comment by rdrpenguin04** [comment]
It seems like this may have gotten unfixed recently? Minimum reproducer:

```rs
#[get("/<_x>")]
pub fn get_x(_x: &str) {}
```

**Comment by durka** [comment]
Guess I should've included that test 🙃

**Comment by kallebysantos** [comment]
I've the same warning in some request handlers, while upgrading `meteoritus` from  `rocket v0.5.0-rc.2` to `rocket v0.5.1`:
```rust
#[head("/<id>")]
pub fn file_info_handler(
    id: &str, // unreachable pattern this pattern matches no values because `Infallible` is uninhabited `#[warn(unreachable_patterns)]` on by default [unreachable_patterns]
    vault: &State<Arc<dyn Vault>>,
) -> FileInfoResponder {
    match vault.get_file(id) {
        Ok(file) => FileInfoResponder::Success(file),
        Err(_) => FileInfoResponder::Failure(Status::NotFound),
    }
}

```
