### ISSUE TITLE
Mutable reference to State<T>

### ISSUE THREAD

**Issue by Eilie** [SergioBenitez/Rocket#359]
Hello,

Is it possible to have mutable reference to `State<T>`?
E.g., I have following request handler:
```
#[get("/")]
fn index(x: State<X>)
```

And inside that handler I'd like to pass `x` to another function as `&mut x` is it possible?
If not then what should I do in this situation? Is there a workaround?

**Comment by belst** [comment]
You need to use inner mutability via a [Mutex](https://doc.rust-lang.org/std/sync/struct.Mutex.html) or [RwLock](https://doc.rust-lang.org/std/sync/struct.RwLock.html)

**Comment by SergioBenitez** [comment]
To expand on @belst's response: you cannot obtain an `&mut T` reference from a `State<T>` as doing so would be racy. This is because requests are handled concurrently, so allowing this would allow two `&mut T` references to the same `T` to be active concurrently.

To get access to a mutable `T`, you need to use some form of internal mutability. Among others, these include the types in [`sync`](https://doc.rust-lang.org/std/sync/index.html).

**Comment by dofork** [comment]
Could anyone show some code for the question?

**Comment by jebrosen** [comment]
@dofork You can manage and use a Mutex with something like this:

```rust
use std::sync::Mutex;

struct SharedData { numbers: Mutex<Vec<i32>> };

#[get("/<number>")]
fn add_number(number: i32, shared: State<SharedData>) -> String {
    let lock = shared.lock().expect("lock shared data");
    lock.numbers.push(number);
    format!("There are now {} numbers", lock.numbers.len())
}

fn main() {
    rocket::ignite()
        //...
        .manage(SharedData { numbers: Mutex::new(vec![5]) })
        .launch();
}
```

Using an `RwLock` would work in a similar way. `RwLock` and `Mutex` might be too slow if you will have a lot of concurrent operations on the same shared data, however.

**Comment by emryx26** [comment]
> @dofork You can manage and use a Mutex with something like this:
> 
> ```rust
> use std::sync::Mutex;
> 
> struct SharedData { numbers: Mutex<Vec<i32>> };
> 
> #[get("/<number>")]
> fn add_number(number: i32, shared: State<SharedData>) -> String {
>     let lock = shared.lock().expect("lock shared data");
>     lock.numbers.push(number);
>     format!("There are now {} numbers", lock.numbers.len())
> }
> 
> fn main() {
>     rocket::ignite()
>         //...
>         .manage(SharedData { numbers: Mutex::new(vec![5]) })
>         .launch();
> }
> ```
> 
> Using an `RwLock` would work in a similar way. `RwLock` and `Mutex` might be too slow if you will have a lot of concurrent operations on the same shared data, however.

It seems that when you push a number into lock.numbers.push(number), it have to be mutable, but rocket doesn't allow that. Am I missing something here?

**Comment by jebrosen** [comment]
> Am I missing something here?

Probably a `mut` between `let` and `lock`: `let mut lock = shared.lock().expect("lock shared data");`

If that works, I will go back and edit that example.

**Comment by olback** [comment]
@emryx26
Mutex and RwLock locks acquired by their respective lock methods have to be mutable if you want to push an item.

**Comment by emryx26** [comment]
> 
> 
> @emryx26
> Mutex and RwLock locks acquired by their respective lock methods have to be mutable if you want to push an item.

Rocket will freeze when you create a mutable in routes, right?

**Comment by emryx26** [comment]
this is my working examples: 

```rust
// src/cache.rs

use std::collections::HashMap;
use std::sync::{RwLock, RwLockReadGuard};
use std::sync::atomic::{AtomicI32, AtomicU32};
use std::sync::atomic::Ordering::Relaxed as ordering;
use super::models::Hook;

#[derive(Hash, Eq, PartialEq, Debug)]
pub struct LogPage {
    dt: u32,
    sid: i32,
    pn: i32,
}

impl LogPage {
    pub fn new(d: &u32, s: &i32, p: &i32) -> LogPage {
        LogPage { dt: *d, sid: *s, pn: *p }
    }
}

#[derive(Serialize)]
pub struct Context {
    items: Vec<Hook>,
    page: i32,
    total_page: i32
}

impl Context {
    pub fn new(v: &Vec<Hook>,  p: &i32, tp: &i32 ) -> Context {
        let vec = v.to_vec();
        Context{ items: vec, page: *p, total_page: *tp }
    }
}

pub struct Cache {
    date: AtomicU32,
    counter: AtomicI32,
    map: RwLock<HashMap< LogPage, Context >>
}

impl Cache {
    // init
    pub fn new() -> Cache {
        Cache {
            date: AtomicU32::new(0),
            counter: AtomicI32::new(0),
            map: RwLock::new(HashMap::new())
        }
    }

    // getter
    pub fn date(&self) -> u32 {
        self.date.load(ordering)
    } 

    pub fn counter(&self) -> i32 {
        self.counter.load(ordering)
    } 

    pub fn map(&self) -> RwLockReadGuard<HashMap< LogPage, Context >> {
        self.map.read().unwrap()
    }

    // set values
    pub fn set_date(&self, v: &u32) {
        self.date.store(*v, ordering);
    }

    pub fn set_counter(&self, v: &i32) {
        self.counter.store(*v, ordering);
    }

    pub fn fetch_inc_counter(&self) -> i32 {
        self.counter.fetch_add(1, ordering)
    }

    pub fn map_mut(&self, k: LogPage, v: Context) {
        let mut lock = self.map.write()
            .expect("locking cache to write");
        lock.insert(k, v);
    }
}
```

**Comment by benmarten** [comment]
> @dofork You can manage and use a Mutex with something like this:
> 
> ```rust
> use std::sync::Mutex;
> 
> struct SharedData { numbers: Mutex<Vec<i32>> };
> 
> #[get("/<number>")]
> fn add_number(number: i32, shared: State<SharedData>) -> String {
>     let mut lock = shared.lock().expect("lock shared data");
>     lock.numbers.push(number);
>     format!("There are now {} numbers", lock.numbers.len())
> }
> 
> fn main() {
>     rocket::ignite()
>         //...
>         .manage(SharedData { numbers: Mutex::new(vec![5]) })
>         .launch();
> }
> ```
> 
> Using an `RwLock` would work in a similar way. `RwLock` and `Mutex` might be too slow if you will have a lot of concurrent operations on the same shared data, however.

Modified to compiling+working:

```
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use]
extern crate rocket;

use rocket::State;
use std::sync::Mutex;

struct SharedData {
    numbers: Mutex<Vec<i32>>,
}

#[get("/<number>")]
fn add_number(number: i32, shared: State<SharedData>) -> String {
    let shared_data: &SharedData = shared.inner();
    shared_data.numbers.lock().unwrap().push(number);
    format!(
        "There are now {} numbers",
        shared_data.numbers.lock().unwrap().len()
    )
}

fn main() {
    rocket::ignite()
        .mount("/", routes![add_number])
        .manage(SharedData {
            numbers: Mutex::new(vec![5]),
        })
        .launch();
}
```

**Comment by ycd** [comment]
You are awesome @benmarten, thank you!
