### ISSUE TITLE
Console coloring is not working in Windows

### ISSUE THREAD

**Issue by blackghost1987** [SergioBenitez/Rocket#363]
1. Rocket version: 0.3.0
  2. OS: Windows 10 x64
  3. Description:
Console coloring of the log is messed up, coloring characters are showing up, see the attached screenshot. This is a regression from 0.2.9, where this was working fine. The console definitely supports coloring, as it can be seen from the cargo output.

  4. Reproduction:
Simply start a minimal Rocket example from command line with "cargo run"

  5. Ideas:
The 0.3.0 Changelog contains: "yansi is now used for all terminal coloring.", which could be a reason. Should I create an issue in the Yansi repository as well? Or is this an error on Rockets side?

![rocket_coloring_bug](https://user-images.githubusercontent.com/2356991/28621392-0ae72fa4-7211-11e7-8b2c-3ed8c132916d.png)

![rocket_coloring_working_in_0 2 9](https://user-images.githubusercontent.com/2356991/28621952-f1fc1f52-7212-11e7-8d70-69bfe4969b47.png)

**Comment by lnicola** [comment]
Can you try the `windows-colors` branch?

**Comment by blackghost1987** [comment]
Wow thanks for the quick response. I had to play around with the dependencies a bit, but I managed to change to the branch, and it works like a charm. Thanks a lot!

**Comment by SergioBenitez** [comment]
The Windows console doesn't support ASCII sequences unless support is explicitly enabled. This feature is only available on modern versions of Windows 10. I originally implemented support for this feature in the `windows-colors` branch but have now upstreamed it to [`yansi`](https://crates.io/crates/yansi). I've pushed this change to the `master` branch. As a result, colors should now work on consoles in Windows 10 on `master`.

**Comment by ronnyek** [comment]
Should this problem be resolved? I'm attempting to run this fairly recent example from github (https://github.com/KodrAus/rust-web-app/tree/main/src) , and on windows I get the same output as OP (ansi/ascii color codes etc)

**Comment by blackghost1987** [comment]
The fix is not released yet, so if you are using 0.5.0-rc.1 from Crates.io then it won't work. If you use the latest master from GitHub, then it should work. Hopefully there will be an rc.2 release soon, which includes this.
