### ISSUE TITLE
rocket_codegen lints fail to handle unresolved HIR paths leading to failed compilation

### ISSUE THREAD

**Issue by Lapz** [SergioBenitez/Rocket#367]
## Bug Report
  1. Rocket v 0.3.0, Rust: 1.21.0-nightly (aac223f4f 2017-07-30)

  2. macOS Sierra v 10.12.6

  3.  Rocket codegen enters unreachable code that crashes the compiler

  4. I've an example in this [repo](git@github.com:Lapz/rocket_compile_error.git)

  5.  Rocket codegen enters unreachable code. It seems to be that there is a case that is reached that is covered by the unreachable! macro in the [rocket_codegen lint](https://github.com/SergioBenitez/Rocket/blob/master/codegen/src/lints/mod.rs#L156l) and this causes the compiler to crash.

**Comment by SergioBenitez** [comment]
What code is being compiled?

**Comment by Lapz** [comment]
This is the code thats being compiled
```rust 

use rocket::config::{Config, Environment};


#[get("/hello")]
fn hello() -> &'static str {
    "Hello, world!"
}


fn main() {


    let config = Config::build(Environment::Staging)
                .address("localhost")
                .port(3000)
                .finalize()
                .unwrap();
    

    // rocket::custom(config, false).mount("/", routes![hello]); // This compiles properly 

    rocket::Rocket::custom(config,false).mount("/", routes![hello]); // This causes an error and does not compile due to the unreachable! in the lint
}
```

**Comment by SergioBenitez** [comment]
Ah, I see. Change `rocket::Rocket::custom` to `rocket::custom`. Does the error go away?

**Comment by Lapz** [comment]
Yep the error goes away

**Comment by SergioBenitez** [comment]
Confirmed. Fix is incoming.
