### ISSUE TITLE
How to add a private cookie to a LocalRequest?

### ISSUE THREAD

**Issue by golddranks** [SergioBenitez/Rocket#368]
Using Rocket 0.3.

I tried to look for a way to add private cookie to a LocalRequest for testing, but it seems that the only way to get private cookies for tests is to generate them first on the server (simulate a session-initiating request). It would be helpful if adding private cookies would be directly available for testing.

I think it would be sufficient to be documented in the API docs, maybe as a method `cookie_private` on `LocalRequest`.

**Comment by SergioBenitez** [comment]
This should definitely be possible and shouldn't be difficult to implement. If anyone wants to tackle this, I'd be more than happy to review.
