### ISSUE TITLE
Catch-it-all routes that ignore the parameters?

### ISSUE THREAD

**Issue by golddranks** [SergioBenitez/Rocket#372]
Using Rocket 0.3

I'm using a route like `#[get("/prefix/<path..>", rank = 2)]` to have a catch-it-all route. I'm actually ignoring the path, since I'm just sending the same index.html for every query to power a single-page app that parses the URL path client-side.

I'd like to ignore the `path` but Rocket doesn't allow using identifiers starting with "_". Is using `#[allow(unused_variables)]` the preferred way to achieve this or is there a better way?

I don't want to use a general error catcher because if I understand it right, it would be global, and seems like a wrong tool for the job.

**Comment by SergioBenitez** [comment]
Using `#[allow(unused_variables)]` works. You can also do something like: `let _ = path;` in the body. A step beyond that, you can create a tiny macro that does that. Something like:

```rust
macro ignore($($v:ident),+) {
    $(let _ = $v;)+
}
```

You can then do something like:

```rust
ignore!(a, b, c);
```

**Comment by golddranks** [comment]
Okay, thanks for answering!
