### ISSUE TITLE
invalid form field identifier

### ISSUE THREAD

**Issue by kardeiz** [SergioBenitez/Rocket#375]
I have a form that looks like:

```rust
#[derive(FromForm)]
struct SignupForm {
    email: String,
    password: String,
    #[form(field = "password-confirmation")]
    password_confirmation: String
}
```

which fails to compile with:

```
error: invalid form field identifier
    // ...
    |         #[form(field = "password-confirmation")]
```

It seems like this should compile (indeed it seems like the primary use case for this attribute would be to handle form input names that aren't valid Rust identifiers).

I'm on Rocket 0.3.0.

**Comment by SergioBenitez** [comment]
This has already been addressed in 952c98fc047ec6020a25752636652afb81a0fd2c and will ship in 0.3.1.
