### ISSUE TITLE
 #[feature] may not be used on the stable release channel

### ISSUE THREAD

**Issue by ceyhunkerti** [SergioBenitez/Rocket#377]
`cargo run`
gives the above error.

quick search: `rustup override set nightly`

**Comment by nihiluis** [comment]
I think you must be on nightly.

`Rocket requires a nightly version of Rust as it makes heavy use of syntax extensions. This means that the first two unwieldly lines in the introductory example above are required.`

**Comment by ceyhunkerti** [comment]
thanks i have just found that
