### ISSUE TITLE
Use error from FromData Outcome::Failure return in a catcher

### ISSUE THREAD

**Issue by geauxvirtual** [SergioBenitez/Rocket#380]
Version: 0.3.0

When implementing FromData, Outcome::Failure is a valid return type that takes a status and an error. Looking through the code, it appears any error returned with Outcome::Failure from a FromData implementation is discarded with the status being used to match a catcher. It would be useful to be able to pass errors out of FromData to be returned to the user through a catcher for that status code.

**Comment by SergioBenitez** [comment]
This would be handled by #749. As such, closing this out to track there.
