### ISSUE TITLE
`FromSegments` should be implemented for string

### ISSUE THREAD

**Issue by rbalicki2** [SergioBenitez/Rocket#390]
I want to have an options route that handles any route, because I'm (at the moment) too lazy to do CORS the right way. I would assume that I would implement that with something like

```
    #[options("/<any..>")]
    pub fn options_handler(
      any: String, // an ignored parameter
    // ...
```

Unfortunately, that gives me:

```
    the trait `rocket::request::FromSegments<'_>` is not implemented for `std::string::String`
```

I'm sure there are other, more legitimate needs for other people to have String implement fromSegments (or perhaps `Vec<String>`). Happy to make a PR if you think so as well.

Edit: I realize this works with PathBuf. Correct me if I'm wrong, but are there strings which cannot be converted to path bufs but which could be valid routes for rocket? If not, then this would be unnecessary

**Comment by SergioBenitez** [comment]
> Edit: I realize this works with PathBuf. Correct me if I'm wrong, but are there strings which cannot be converted to path bufs but which could be valid routes for rocket? If not, then this would be unnecessary

If something is a valid `String`, it's a valid `PathBuf`. However, if something is a `PathBuf`, it may or may not be a valid `String`.

**Comment by SergioBenitez** [comment]
An implementation of `FromSegments` for `String` would not preserve the path components in any meaningful way. Because of this, I don't believe such a conversion should exist. Instead, use `PathBuf` or a manual implementation.
