### ISSUE TITLE
Route case sensitivity

### ISSUE THREAD

**Issue by snarf95** [SergioBenitez/Rocket#392]
1. The version of Rocket you're using. Ensure it's the latest, if possible.
-- Rocket 0.3.2

  2. The operating system (distribution and version) where the issue occurs.
-- Irrelevant

  3. A brief description of the bug that includes:
-- When I navigate to a router with all-lowercase using an ALL-CAPITALS URL I get a 404-exception.
-- I expect route handling to not take case sensitivity into consideration.

  4. How you uncovered the bug. Short, reproducible tests are especially useful.
-- See above

  5. Ideas, if any, about what Rocket is doing incorrectly.
-- Make route comparison case-insensitive.

**Comment by belst** [comment]
In my opinion this is expected behaviour. At least when running on a unix like system.

`foo/Bar` is a different path than `foo/bar`

**Comment by snarf95** [comment]
Both makes sense depending on context. if you're mapping a static file directory then it makes sense for it to be case sensitive.. Maybe make it an option.

**Comment by SergioBenitez** [comment]
The target of a request is not defined to be case sensitive or insensitive by any standard. As such, it is up to the server to make this decision. The only valid default for Rocket is case-sensitivity as case-_insensitivity_ is a subset of this. In other words, you can implement case-insensitivity on-top of case sensitivity, but not the other way around.

Case in point, it is trivial to create a fairing that rewrites every request to lower-case, achieving case insensitivity:

```rust
#[get("/hello")]
fn index() -> &'static str {
    "Hello, world!"
}

fn main() {
    rocket::ignite()
        .attach(AdHoc::on_request(|req, _| {
            let new_uri = req.uri().as_str().to_lowercase();
            req.set_uri(new_uri);
        }))
        .mount("/", routes![index]).launch();
}
```

With the code above, `/hello`, `/HELLO`, `/heLLo`, and so on all match `index`.

For these reasons, I'm closing out this issue.
