### ISSUE TITLE
env_logger::init() deadlocks Rocket

### ISSUE THREAD

**Issue by golddranks** [SergioBenitez/Rocket#398]
1. Using Rocket 0.3.2.

  2. Using macOS 10.12.6

  3. A deadlock happens when attempting to `.launch()` the Rocket, when `env_logger::init()` has been called earlier in the code. The launch messages are not written to log, expect for the mount message.  I'd expect it not to deadlock. 

  4. A reproducible test is here: https://github.com/golddranks/rocket_deadlock_demo

  5. Maybe Rocket is locking the stderr just for itself? I haven't consulted the source code.

**Comment by SergioBenitez** [comment]
Your example code works perfectly for me. There's nothing in Rocket's code that could somehow cause a deadlock. If there _is_ an issue, it's with `log` or `env_logger`.

Are you sure that things aren't actually working? Have you tried visiting `http://localhost:8000` to see if Rocket is in fact serving requests? You've overwritten Rocket's logger, so you won't see Rocket's log messages unless you set up the correct environment flags. Perhaps you're mistaking lack of logging for a deadlock?

**Comment by golddranks** [comment]
Ah, that is indeed the case – it doesn't deadlock, it just skips the messages. I thought that it freezed for an entirely different reason (the browser tried to connect to https instead of http).

So the actual problem is that some of the log messages go missing. Here's the supposed output:

```
1
🔧  Configured for development.
    => address: 0.0.0.0
    => port: 3000
    => log: normal
    => workers: 8
    => secret key: generated
    => limits: forms = 32KiB
    => tls: disabled
2
🛰  Mounting '/':
    => GET /
3
🚀  Rocket has launched from http://0.0.0.0:3000
GET / text/html:
    => Matched: GET /
    => Outcome: Success
    => Response succeeded.
GET / text/html:
    => Matched: GET /
    => Outcome: Success
    => Response succeeded.
```

Here's what I get instead:
```
1
INFO:rocket::rocket: 🔧  Configured for development.
2
INFO:rocket::rocket: 🛰  Mounting '/':
3
INFO:rocket::rocket: GET / text/html:
INFO:rocket::rocket: GET / text/html:
```

Btw. I just noticed that I had set rocket=trace in my `RUST_LOG`. Setting it to warn or higher doesn't show anything.

So it seems from the symptoms that Rocket uses the `log` facade to log, and `env_logger` takes over, deciding what to show?

**Comment by SergioBenitez** [comment]
> So it seems from the symptoms that Rocket uses the `log` facade to log, and `env_logger` takes over, deciding what to show?

That's right.

There are efforts to improve Rocket's logging facilities, which are being discussed in #21. Feel free to chime in there stating what you're trying to accomplish. Ideally we can create logging infrastructure that is flexible enough to meet everyone's requirements.
