### ISSUE TITLE
Add "Projects using Rocket" to Readme

### ISSUE THREAD

**Issue by jaroslaw-weber** [SergioBenitez/Rocket#401]
It would be nice to have few links to repos/projects which use Rocket. I think adding them to the bottom of Readme would be a nice addition to examples.

**Comment by madeindjs** [comment]
I begin to build a simple REST application with [Disell.rs](http://diesel.rs/) and just one model. I want to know if I can link it on Readme or if I should add it in example folders? What do you think?

**Comment by phayes** [comment]
I'm not sure if you'd like to highlight closed-source projects, but if you do, feel free to highlight our project that uses Rocket:

https://neurovisualtrainer.com/

Feel free to use our logo etc.

**Comment by Weasy666** [comment]
I would even suggest a dedicated `Used by` section on [Rocket.rs](https://rocket.rs), in which projects that use rocket are listed/linked.

I think, that it could be really helpful for others to see some **real world**™ projects to get a feeling for rocket and to maybe get some inspiration for how to use it.

Projects that come to my mind are:
- [Conduit.rs](https://conduit.rs) @timokoesters
- [Plume](https://joinplu.me/) @igalic

**Comment by flosse** [comment]
The backend of https://kartevonmorgen.org/ is also powered by rocket: https://github.com/kartevonmorgen/openfairdb :)

**Comment by igalic** [comment]
i'd feel more comfortable adding Plume once we've migrated to rocket 0.5

**Comment by azzamsa** [comment]
- https://github.com/revoltchat/delta/
