### ISSUE TITLE
rocket_plugin spans do not report that they are part of an expansion

### ISSUE THREAD

**Issue by oli-obk** [SergioBenitez/Rocket#407]
Running `clippy` on a project using `rocket_plugin` will report lints on every `#[get()]` invocation (and probably others. These look like

```
warning: this argument is passed by value, but not consumed in the function body
  --> src/api/fractal.rs:13:1
   |
13 | #[get("/fractal")]
   | ^^^^^^^^^^^^^^^^^^ help: consider taking a reference instead: `&#[get("/fractal")]`
   |
   = note: #[warn(needless_pass_by_value)] on by default
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/0.0.155/index.html#needless_pass_by_value
```

There is no way we can fix this in clippy, because the spans given to your expanded code does not contain expansion info. Taking any span from meta items or even the span given to plugin functions without marking it as an expansion is considered a [bug in rustc](https://github.com/rust-lang/rust/issues/43268#issuecomment-320764532).

**Comment by SergioBenitez** [comment]
After a brief chat with @oli-obk, we're investigating whether the culprit is rustc's `quote!` macro.

**Comment by SergioBenitez** [comment]
This should be fixed with the new `Span` stuff in newer nightlies.
