### ISSUE TITLE
Is there any way to request guard without explicit handler parameter?

### ISSUE THREAD

**Issue by pocket7878** [SergioBenitez/Rocket#409]
## Questions

I want to validate client mobile application's minimum supported version before processing 
request.

My client app sends app semantic version to server with custom Header field. (e.g `X-App-Version`)
And I want to check if semantic version of it satisfies minimum supported version.
And If validation failed I want to stop processing handler and returns specific-responds.

I think it can be achieved by adding explicit `FromRequest` parameter into every handler.
But it might be annoying to add parameter to all handlers.
Is there any good way to achieve this?

**Comment by belst** [comment]
If you need it for every request you can use a [Fairing](https://rocket.rs/guide/fairings/)

**Comment by pocket7878** [comment]
@belst 
I think Fairing can not be used to return response directly.
So should I use Fairing to modify request's uri into some fallback uri to handle app version validation error?

**Comment by SergioBenitez** [comment]
@pocket7878 Yes, that would be the way to go about it currently. This may change in future versions of Rocket, however.

**Comment by pocket7878** [comment]
@SergioBenitez 
Thank you for your answer! I'll try it!
