### ISSUE TITLE
Conflict with Kubernetes DNS 

### ISSUE THREAD

**Issue by jbowen93** [SergioBenitez/Rocket#411]
Filing this under a general comment since while it causes breakage it's not incorrect behavior on either project.

The issue is as follows:
If you attempt to run a rocket application on a kubernetes cluster and there happens to be an existing service named `rocket` on the cluster then the new pod with the rocket application will go into an `ERROR` state immediately. 

This is because when the new Pod is created it gathers DNS entries based on the existing state of the cluster and places the information into environment variables. One of the environment variables created has the following naming convention:
`<Service name>_<PORT>=tcp://<ip-adress>:<port>`

 If there is a service named `rocket` on the cluster there will be an env var:
`ROCKET_PORT=tcp://<ip-adress>:<port>`

This results in the rocket application returning this error:
```
Error: environment variable 'port=tcp://10.0.0.143:3000' could not be parsed
    => expected a 16-bit unsigned integer, but found string
```

The current "fix" for this is to just not have a service named `rocket` on your kubernetes cluster. 

Might be worthwhile adding a line to mention this if/when a deployment section of docs gets made.

**Comment by SergioBenitez** [comment]
Thanks for reporting this! Let's keep this in mind when resolving #171. I'll close this in favor of keeping track there.
