### ISSUE TITLE
FromForm shoud url decode the param

### ISSUE THREAD

**Issue by Matrix-Zhang** [SergioBenitez/Rocket#422]
when the url query string is chinese, the route param &str is the form url encoded string, i must decode myself

**Comment by SergioBenitez** [comment]
There are no Rocket traits implemented for `&str` in 0.3. Use `&RawStr` with the provided methods for URL decoding, or `String` which automatically performs URL decoding.

**Comment by Matrix-Zhang** [comment]
I have used RawStr, but it not implements the FormRequest trait?so compiled failed

**Comment by SergioBenitez** [comment]
Please read through the [guide](https://rocket.rs/guide/). You probably want to use `String`.

**Comment by Matrix-Zhang** [comment]
#[post("/<account_id>/cancel?<reason>")]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `rocket::request::FromForm<'_>` is not implemented for `std::string::String`

also compile failed

**Comment by SergioBenitez** [comment]
@Matrix-Zhang Please read the guide. Specifically, the section on query strings.
