### ISSUE TITLE
Favicons

### ISSUE THREAD

**Issue by TheUberCatman** [SergioBenitez/Rocket#423]
Hi, I am currently using version 0.3.2 and I was wondering how I could setup a favicon for my webapplication, I currently am trying it with the example for static files but my browser doesn't recognize it. Maybe because the content-type is not right?

**Comment by mgattozzi** [comment]
I have this working on my site. If you look [here](https://github.com/mgattozzi/mgattozzi/blob/master/templates/base.tera#L9) I've defined a base template used everywhere that sets all the favicons depending on your screen size. The code to serve the static files is [here](https://github.com/mgattozzi/mgattozzi/blob/master/src/bin/main.rs#L81-L84) and below it is how the templates are served up. My guess is you just need to set up the route properly and have the page with the html link it right.

**Comment by jaroslaw-weber** [comment]
hey, favicons are not so difficult to implement, check my project: 
https://github.com/jaroslaw-weber/learn-korean-tools/blob/master/src/webapi.rs

**Comment by TheUberCatman** [comment]
This issue can be closed because when i pulled my project on my other computer, the browser started to retrieve the favicon while i didn't change any code. It might be a cache thing after all.
