### ISSUE TITLE
Question about rendering template

### ISSUE THREAD

**Issue by samrayleung** [SergioBenitez/Rocket#435]
I have occured a question, Say, I have a `base.html.tera` file, and other tera files (eg, `index.html.tera` and `profile.html.tera`)are extended from `base.html.tera`. Some code  in `base.html.tera` as below:
```html
                <div class="media-body">
                    <h5 class="media-heading">User:</h5>
                    <ul class="list-unstyled user-info">
                        <li> <a href="">{{username}}</a> </li>
                        <li>Last Access :
                            <br>
                            <small>
                  <i class="fa fa-calendar"></i>&nbsp;{{access_time}}</small>
                        </li>
                    </ul>
                </div>
```
and controller code:
```rust
#[get("/admin/index")]
pub fn index(user: User, db: DB) -> Template {
    let visitor_logs = VisitorLog::query_login_user(db.conn(), user.0);
    let users = user::User::query_by_id(db.conn(), user.0);
    let mut context = HashMap::new();
    if let Some(user) = users.first() {
        context.insert("username", UserInfo::Username(user.username.to_string()));
    }
    if let Some(log) = visitor_logs.first() {
        context.insert("access_time", UserInfo::AccessTime(log.access_time));
    }
    Template::render("admin/index", &context)
}
```
 When I render `index.html.tera`, I insert `username` and `access_time` into `context`, when I render `profile.html.tera`, could I stop inserting `username` and `access_time` again, could I insert a `value` into the parent tera file once, and could render its childern tera file with  `value` many times? Before I open this issue, I have opened an [issue](https://github.com/Keats/tera/issues/216) in Tera project, but it seems get nothing. Could you help me ?

**Comment by SergioBenitez** [comment]
I'm not sure I understand what you'd like. The `username` and `access_time` values change every time a corresponding child template is rendered, but it sounds like you want to cache these values somehow. Do I understand correctly that you want to render `base` once and use the pre-rendered parent template when rendering several of its child templates?

This _can_ be made to work, but I can't see how it would have any benefit. You'd need to render the base template at least one for a given handler for its data to be valid which means you can simply render the base template along with the child template and get the same performance. The only benefit would be when rendering multiple child template in one handler which shouldn't happen.

Can you perhaps share some fictional example code that shows what you'd like to do and what the perceived benefit would be?

**Comment by samrayleung** [comment]
![admin](https://user-images.githubusercontent.com/14180681/30838948-370fd8ea-a2a1-11e7-8210-02ca6443a922.png)
This is the admin page of My Blog, and I will try to explain my thought. As you could see, the `side menu` and the `header` part will not change no matter which page it is , so I put them into a `Base` template. What will change is the content(eg,something in the red rectangle), so I create a `Base` template which has all same side menu and header, and all `children` template just need to extend `Base` template.

Base template
```html
<body>
    <div id="wrap">
        <div id="left">
            <div class="media user-media">
                <a class="user-link" href="/admin/profile">
          <img class="media-object img-thumbnail user-img" alt="User Picture" src="assets/img/rust_logo.png">
          <!-- <span class="label label-danger user-label">16</span> -->
        </a>
                <div class="media-body">
                    <h5 class="media-heading">User:</h5>
                    <ul class="list-unstyled user-info">
                        <li> {{username}} </li>
                        <li>Last Access :
                            <br>
                            <small>
                  <i class="fa fa-calendar"></i>&nbsp; {{access_time}} ;</small>
                        </li>
                    </ul>
                </div>
            </div>

            <!-- #menu -->
            <ul id="menu" class="collapse">
                <li class="nav-header">Menu</li>
                <li class="nav-divider"></li>

                <li>
                    <a href="/admin/index">
            <i class="fa fa-dashboard"></i>&nbsp;Dashboard</a>
                </li>
                <li>
                    <a href="/admin/post_list">
            <i class="fa fa-credit-card"></i>&nbsp;Post Management</a>
                </li>
                <li>
                    <a href="/admin/user">
            <i class="fa fa-user-circle"></i>&nbsp;User Management</a>
                </li>
                <li>
                    <a href="/admin/profile">
            <i class="fa fa-id-card"></i>&nbsp;Profile</a>
                </li>
                <li class="nav-divider"></li>
            </ul>
            <!-- /#menu -->
        </div>
        <!-- /#left -->
        {% block content %} {% endblock content %}
        <!-- end #content -->
    </div>
    <!-- /#wrap -->
    <div id="footer">
        <p>Copyright &copy; Samray Leung 2017-</p>
    </div>

</body>

```
Post Management page:
```html
{% extends "base" %}
{% block content %}
post list ......
{% endblock content %}
```
User Management page:
```html
{% extends "base" %}
{% block content %}
user list ......
{% endblock content %}
```
The value I set into `Base` Template is the value will not change in each `child` template, such as `side menu`, such as `username`, and `access_time`, so I want to set it into `base` once, and use it many times in `child` template. Is it clear?, could you understand what I want ?

**Comment by SergioBenitez** [comment]
What I'm not following is what you mean by "setting it once". If the values are dynamic, then you need to set them each time the template is rendered. If the values are not dynamic, then you can just replace the template variables by the actual values.

If you're concerned about writing the following over and over:

```rust
    let mut context = HashMap::new();
    if let Some(user) = users.first() {
        context.insert("username", UserInfo::Username(user.username.to_string()));
    }
    if let Some(log) = visitor_logs.first() {
        context.insert("access_time", UserInfo::AccessTime(log.access_time));
    }
```

Then I'd simply create a function that returns a pre-populated `HashMap`:

```rust
fn template_context(user: Option<&User>, log: Option<&Log>) -> HashMap<&'static str, UserInfo> {
    let mut context = HashMap::new();
    if let Some(user) = user {
        context.insert("username", UserInfo::Username(user.username.to_string()));
    }
    if let Some(log) = visitor_logs.first() {
        context.insert("access_time", UserInfo::AccessTime(log.access_time));
    }

    context
}
```

Then use it as:

```rust
let context = template_context(users.first().as_ref(), visitor_logs.first().as_ref());
```

Depending on the granularity you need, you could even go further and abstract the whole thing away:

```rust
fn template_context(conn: DbConn, user: User) -> HashMap<&'static str, UserInfo> {
    let visitor_logs = VisitorLog::query_login_user(conn, user.0);
    let users = user::User::query_by_id(conn, user.0);
    let mut context = HashMap::new();
    if let Some(user) = users.first() {
        context.insert("username", UserInfo::Username(user.username.to_string()));
    }
    if let Some(log) = visitor_logs.first() {
        context.insert("access_time", UserInfo::AccessTime(log.access_time));
    }

  context
}

**Comment by samrayleung** [comment]
Thanks for your suggestion
