### ISSUE TITLE
Handling Range header

### ISSUE THREAD

**Issue by belst** [SergioBenitez/Rocket#439]
Since almost every fully featured http server handles the `Range` header by default, I think Rocket should too.

Rocket should add the header `Accept-Ranges: bytes` to every response by default. Maybe have this as a config option? If disabled send `Accept-Ranges: none` and disable `Range` handling.

If a `Range` header is present, Rocket should automatically slice the body to the required range and set the status to `206 Partial Content` or fail with `416 Range Not Satisfiable`.

If additionally an `If-Range` header is present, a validity test of the partial range is needed. Otherwise send the whole file.

For `Range` requests with multiple ranges the `Content-Type` should also be set to `multipart/byteranges`. This requires additional handling of boundaries and part specific headers. (This is also needed to handle `multipart/form-data` requests).

One implementation option would be directly into Rocket itself, without any user facing api (other than perhaps a config option).

Another approach would be to provide a fairing in rocket-contrib. (users would need to opt-in manually)

Hyper does provide a type for the `If-Range` and the `Content-Range` header, not for the `Range` header itself though.

Relevant RFC: https://tools.ietf.org/html/rfc7233

**Comment by SergioBenitez** [comment]
> Since almost every fully featured http server handles the Range header by default, I think Rocket should too.

Can you provide some examples of this?

**Comment by belst** [comment]
I know that apache, nginx and lighttpd handle Range requests without any further configuration.

**Comment by max-frai** [comment]
It's needed, for example, for streaming data and seeking (mp3).
As I know, nginx could do this with binary files automatically. I'm not sure some frameworks has this by default for everything. 
So if you have your own streaming logic you can do it in response handler and parse headers manually. In case when you need this for binary files you could use nginx as backend.

**Comment by belst** [comment]
If you use nginx as a reverse proxy anyway, you can always serve static files directly via nginx.
If you need some way to control access you can use the `x-accel` module for nginx (https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/).

Having range requests in rocket directly would enable applications to not require a reverse proxy.

**Comment by SergioBenitez** [comment]
I don't think Rocket should handle range requests transparently, by default, for everything. As far as I know, no web frameworks or servers do this for every incoming request/response _except_ when handling static files. Indeed, I _do_ thing Rocket should handle range requests by default when serving static files. For this reason, I'm going to decline this particular request but note that we should implement automatic range request/response handling in a supplied static file handling library. Let's track that in #239.

**Comment by 0xcaff** [comment]
The go standard library has a function to handle responding to range requests. https://godoc.org/net/http#ServeContent

**Comment by metasyn** [comment]
For anyone reading this issue years later, I found this relevant add-on package that facilitated the usage of range headers https://github.com/rydz/rocket_seek_stream
