### ISSUE TITLE
Feature request: Enhance the `map!` macro to allow multiple types

### ISSUE THREAD

**Issue by sgrif** [SergioBenitez/Rocket#44]
Variables passed to templates often have multiple types. Creating a one-off struct for this is certainly possible, but since ultimately the `map!` macro is just "a hash map where the keys are strings and the values are something that can be serialized", that macro might be much more useful if the result was always `HashMap<&str, json::Value>`, and the macro performed the serialization eagerly.

**Comment by SergioBenitez** [comment]
Implemented in 27396821ab44df66bc8311e65f30185171719cb0.
