### ISSUE TITLE
Setting it up on c9.io

### ISSUE THREAD

**Issue by dud3** [SergioBenitez/Rocket#445]
c9.io is a really cool and helpful web based IDE that provides you a personal instance, which makes trying out new stuff really easy, not trying to advertise them, but it saves me tons of time.

I took some notes while installing Rocket:
```
# Install rust
https://doc.rust-lang.org/1.0.0/book/installing-rust.html

# Install cargo
http://doc.crates.io/

# Rocket

    # Install
    cd lib && cargo build
    cd codegen && cargo build
    cd contrib && cargo build --all-features
    
    # Run
    cd examples/hello_world
    cargo run
    
    # Compilation error
    https://github.com/SergioBenitez/Rocket/issues/433
```

everything compiled without a problem.

Unless it doesn't run the examples, I get the following:

```
warning: unused manifest key: development
   Compiling hello_person v0.0.0 (file:///home/ubuntu/workspace/Rocket/examples/hello_person)
    Finished dev [unoptimized + debuginfo] target(s) in 3.67 secs
     Running `/home/ubuntu/workspace/Rocket/target/debug/hello_person`
🔧  Configured for development.
    => address: localhost
    => port: 8000
    => log: normal
    => workers: 16
    => secret key: generated
    => limits: forms = 32KiB
    => tls: disabled
🛰  Mounting '/':
    => GET /hello/<name>/<age> (hello)
    => GET /hello/<name> (hi)
🚀  Rocket has launched from http://localhost:8000
```
which I guess is fine, but the webserver won't response.

Can someone try to install it on c9.io and let me know if it worked for them?

**Comment by iDeBugger** [comment]
Hi!

You should use port 8080, 8081 or 8082 in c9.io

You can [read c9 documentation](https://docs.c9.io/docs/run-an-application) for more information :)

**Comment by dud3** [comment]
Yes.

How do I change the Rocket's port?

I tried changing it on `examples/config`, but no luck. ;(

**Comment by dud3** [comment]
cc @iDeBugger

**Comment by iDeBugger** [comment]
To change port in Rocket app you can use environment variable ROCKET_PORT or file Rocket.toml (more info about both cases avaliable [here](https://rocket.rs/guide/configuration/#rockettoml))

**Comment by dud3** [comment]
@iDeBugger I see.

I've managed to change it:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `/home/ubuntu/workspace/Rocket/target/debug/hello_person`
🔧  Configured for development.
    => address: localhost
    => port: 8080
    => log: normal
    => workers: 1
    => secret key: provided
    => limits: forms = 32KiB
    => tls: disabled
🛰  Mounting '/':
    => GET /hello/<name>/<age> (hello)
    => GET /hello/<name> (hi)
🚀  Rocket has launched from http://localhost:8080
```

but the server doesn't respond to to 8080/81/82.

**Comment by dud3** [comment]
@iDeBugger Never mind, just managed to make it work. =)

Thanks.

**Comment by dud3** [comment]
Here's the link: http://rust-playground-textbox-test.c9users.io:8080/hello/else

**Comment by dud3** [comment]
It'll die in few mins.

**Comment by iDeBugger** [comment]
Problem is solved anyway. Don't forget to close the ticket :)

**Comment by SergioBenitez** [comment]
Looks like this was resolved! Closing this out.
