### ISSUE TITLE
Websockets on Rocket?

### ISSUE THREAD

**Issue by catroot** [SergioBenitez/Rocket#448]
Hello!
Is there possible to upgrade http connection with Rocket to handle websockets?
Similar to routings like
#[get("/")]
but with
#[ws("/")]

This will be very handy

**Comment by belst** [comment]
see #33

**Comment by catroot** [comment]
Thanks for pointing me. Polling and LongPolling is another feature.
My vote is for WS support out of the box.

**Comment by SergioBenitez** [comment]
Duplicate of #90.
