### ISSUE TITLE
my rocket code with dart Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by adals** [SergioBenitez/Rocket#451]
hello i have function in rocket
#[get("/get_next", format = "application/json")]
fn get_next() -> Json<Value> {
......

when i called with dart http get request it gave me this answer:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8000/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

how to solve it please

**Comment by Boscop** [comment]
https://github.com/lawliet89/rocket_cors

**Comment by SergioBenitez** [comment]
As @Boscop alludes to, you're running into a CORS issue. The `rocket_cors` crate provides one way to handle this.
