### ISSUE TITLE
ring fails to build on Windows Home 10 64bit

### ISSUE THREAD

**Issue by sasmaster** [SergioBenitez/Rocket#457]
Rocket version :latest
Windows 10 Home,64bit ,
Rust nightly : -  1.22.0-nightly (dcbbfb6e8 2017-10-12)
   
Following this tutorial:

https://rocket.rs/guide/getting-started/

Calling Cargo build fails with several errors related to The Ring-0.11.0 lib. Some files are not found.

For example:

>   The system cannot find the file specified. (os error 2)', C:\Users\ccc\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.11.0\build.rs:655:8

**Comment by SergioBenitez** [comment]
The "getting started" code certainly builds. It's tested once a day. Now it's certainly possible that it doesn't build _for you_ or on a particular setup. Ensure that you're using a support Windows target for `ring`. In particular, its page says:

> On Windows, ring supports the x86_64-pc-windows-msvc and i686-pc-windows-msvc targets best. These targets require the “Visual C++ Build Tools 2015” package or Visual Studio 2015 Update 3 or later to be installed. Patches to get it working on other variants, including in particular Visual Studio 2017, Windows ARM platforms, Windows Universal Platform, Windows XP (the v140_xp toolchain), and the -gnu targets are welcome.

**Comment by sasmaster** [comment]
That's exactly the toolchain I have. But I see in the Cargo build log that the plugin is expecting GCC compiler to be available.Is that something that rust libs require in general? I mean,some of those use GCC even on Windows targets?

**Comment by SergioBenitez** [comment]
`ring` should be using `msvc` to compile its C code; at least, that's what it's build script seems to be doing. Rust projects don't typically make use of C code, no, but `ring` does.

**Comment by sasmaster** [comment]
> TARGET = Some("x86_64-pc-windows-gnu")
> **running "gcc.exe**" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-I" "include" "-std=c1x" "-Wbad-function-cast" "-Wmissing-prototypes" "-Wnested-externs" "-Wstrict-prototypes" "-fdata-sections" "-ffunction-sections" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-declarations" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-Wno-cast-align" "-g3" "-D_XOPEN_SOURCE=700" "-Wall" "-Wextra" "-c" "-oD:\\visualstudioprojects\\Pathfinder_rust\\rust_application1\\target\\debug\\build\\ring-b860532254589dd5\\out\\ecp_nistz256.o" "crypto/ec/ecp_nistz256.c"

It looks like it tried to invoke GCC

**Comment by sasmaster** [comment]
I will ask the dude who wrote the lib.

**Comment by SergioBenitez** [comment]
Your target is `-gnu`. Use a `msvc` target.

**Comment by sasmaster** [comment]
How? Your tutorial says nothing about it.

**Comment by sasmaster** [comment]
Now I see it.I installed GNU version of Rust. :/  What a noob I am. Thanks for the pointer.

**Comment by sasmaster** [comment]
You can close it. I reinstalled Rust with MSVC toolchain and now it builds ok. Thanks.
