### ISSUE TITLE
Question about timing and fairings

### ISSUE THREAD

**Issue by sindreij** [SergioBenitez/Rocket#461]
Apologies if this has been addressed, but I could not find anything while searching. I want to be able to do timing of requests in my rocket application for logging and metrics. I could not find any information on best practises for doing that. I know that the fairing documentation says that it should be possible.

To do timing, I need to, as far as I know, be able to save a request start time in `on_request`, and then fetch that and calculate the ellapsed time in `on_response`. The only way I have found to do that, is by saving the start time to a header. And serializing a SystemTime as a string feels wrong.

Another concern is that on_response happens when the router has finished the response, but it has not been sent to the user yet. I would like to also time how long it takes to stream the response to the user.

Rocket version: 0.3.2

**Comment by SergioBenitez** [comment]
This is now more easily possible with request-local state (https://github.com/SergioBenitez/Rocket/issues/654), implemented in 97c6b3ace8.
