### ISSUE TITLE
Nesting FromRequest

### ISSUE THREAD

**Issue by hgrecco** [SergioBenitez/Rocket#463]
Is there a way to use the result of a `FromRequest` in another `FromRequest` implementation? For example, using a DB connection as shown in this [example](https://github.com/SergioBenitez/Rocket/blob/master/examples/todo/src/db.rs) to implement a DB backed version of `is_valid` shown in this [example](https://api.rocket.rs/rocket/request/trait.FromRequest.html#example-1) 

(I know is possible to do it directly in the route handler but it would not be as nice)

**Comment by SergioBenitez** [comment]
Of course! You can either directly call the `from_request` method of the type or use the [`req.guard()`](https://api.rocket.rs/rocket/struct.Request.html#method.guard) method.

**Comment by hgrecco** [comment]
thanks!
