### ISSUE TITLE
Warn on launch if {unused managed state} or {attempted use of unmanaged state}

### ISSUE THREAD

**Issue by lucasem** [SergioBenitez/Rocket#464]
Right now, rocket compiles and runs this:

```rust
#![feature(plugin)]
#![plugin(rocket_codegen)]

extern crate rocket;
use std::sync::atomic::{Ordering, AtomicUsize};

struct Counter {
    c: AtomicUsize,
}
impl Counter {
    fn new() -> Result<Self, ()> {
        Ok(Counter { c: AtomicUsize::new(0) })
    }
    fn update(&self) {
        self.c.fetch_add(1, Ordering::SeqCst);
        println!("count: {}", self.c.load(Ordering::SeqCst))
    }
}

#[get("/")]
fn hello(c: rocket::State<Counter>) -> String {
    c.update();
    "hello".to_string()
}

fn main() {
    rocket::ignite()
        .mount("/", routes![hello])
        .manage(Counter::new()) // whoops, should've unwrapped!
        .launch();
}
```

There are two problems here:
- The managed state `Result<Counter, ()>` is unused, there should be a warning about that.
- Use of unmanaged state `Counter` is attempted, there should be a warning about that.*

*500 is returned from a request to `/` because of unmanaged state. But one wouldn't know the state is unmanaged unless the particular route is being tested (other requests like `/foo` function as expected).

I'm not sure we could easily get this to warn/error during compilation, but we certainly should be able to print a warning _upon launch_ for both of these cases. This would improve usability and reduce bug potential.

**Comment by SergioBenitez** [comment]
Rocket actually _did_ issue a warning at compile-time about unmanaged state in `0.2` and earlier versions of `0.3`. This was accomplished using lints, another kind of syntax extension. Unfortunately, the lint API is incredibly unstable, and lots of nightly-related breakage ensued as a result.

The idea was to bring back these lints in due time. In fact, the [guide](https://rocket.rs/guide/state/#unmanaged-state) still alludes to the lints for just this reason. Unfortunately, it seems unlikely given that the lint API will, with high probability, never stabilize. But one possibility is to introduce a new crate `rocket_lints`, that includes this very unstable code. See #389 for that idea.

I'd be interested in how we can do this dynamically at launch time. While Rocket knows all of the managed state and mounted routes, it doesn't currently know about all of the request guards that could execute. One possibility is to generate some code for each route that informs Rocket about all of the request guards in some way. Then we can call this piece of code for each route at initialization, learn about all of the managed state types, and compare them against the set of types registered as managed states, and finally emit a warning.

I would be open to mentoring an implementation of this!

**Comment by Kacppian** [comment]
I would want to implement this. Is this still open?
