### ISSUE TITLE
`Flash` consumed prematurely

### ISSUE THREAD

**Issue by dpc** [SergioBenitez/Rocket#466]
###  1. The version of Rocket you're using. Ensure it's the latest, if possible.

0.3.3

###  2. The operating system (distribution and version) where the issue occurs.

Linux

###  3. A brief description of the bug that includes

`Flash` can get consumed during unsuccessful request match if it's not the last argument.

###  4. How you uncovered the bug. Short, reproducible tests are especially useful.

My code looked like that:

```
#[get("/", rank = 0)]
fn root_user(flash: Option<FlashMessage>, session: Session) -> Template {
    // ...
}

#[get("/", rank = 1)]
fn root_visitor(flash: Option<FlashMessage>) -> Template {
    // ...
}
```

`Session` represents user being signed-in. So we first match if the user is signed-in, and if not, we display something else for users that are not signed-in yet.

`Flash` messages wouldn't work during "logout" (in `root_visitor`). If I change the order of arguments in in `root_user` to:

```
fn root_user(session: Session, flash: Option<FlashMessage>,) -> Template {
```

everything works OK again.

###  5. Ideas, if any, about what Rocket is doing incorrectly.

When the requests are matched, they are matched in order. First `root_user` is matched, and `FromRequest for FlashMessage` succeeds. The cookie is considered to be delivered and cleared. But then `Session` match fails, and handler falls back to trying `root_visitor`. Unfortunately, the cookie is already erased by then.

**Comment by dpc** [comment]
BTW. It also seems to me, that it's easy to loose `Flash` anyway. Maybe it would be better if it was opaque type, that can get consumed to return it's content and delete itself.

Something like:

```
impl Flash {
   fn consume(self) -> (Type, String) {
     // here it gets deleted from cookies
  }
}
```

**Comment by SergioBenitez** [comment]
I like the proposed solution, but I'm curious about a detail: what should happen to the flash cookie in the `Request` if `Flash` remains un-`consume`d?

**Comment by dpc** [comment]
I guess it should stay in the cookies until something consumes it.

I was also wondering if `Flash` cookie should be really a list (capped at something reasonable). I haven't reached that point already, but it seems to me that two or three "notifications" should not be uncommon in certain scenarios.

**Comment by SergioBenitez** [comment]
Perhaps we can issue a warning on `Drop` if it wasn't consumed using the same mechanism that `LaunchError` uses. I'd be open to accepting an implementation of what we've discussed.

On enabling lists: what does Rails do here, for example? We could serialize/deserialize arbitrary objects, which is what I believe Rails does, but that seems incredibly cumbersome and slow.
