### ISSUE TITLE
Documentation still say to use #[error()] on error catchers

### ISSUE THREAD

**Issue by kitsuneninetails** [SergioBenitez/Rocket#467]
The rocket docs (Rocket Guide web page) say to use ```#[error(code)] ``` to set up a catcher, but this has apparently been changed to ```#[catch(code)]```.  I was also apparently looking at old examples (master looks to have been updated) which were linked from the site (they should really just link to `master` to prevent confusion like this), which meant the only way I found out about the change was parsing the codegen library code itself.  If the docs were updated, or at least point to current examples, a lot of time could be saved by users trying to correctly write an error catcher.

**Comment by SergioBenitez** [comment]
The rendered guide is for the latest release, not the master branch. In general, you should not be using the master branch for any development.
