### ISSUE TITLE
can't response content-type

### ISSUE THREAD

**Issue by uncode** [SergioBenitez/Rocket#469]
```rust
#[get("/algorithm/order-list2")]
fn list2(db: DbConn) -> QueryResult<Json<Vec<Algorithm>>> {
    load!(game);
    game.load::<Algorithm>(&*db).map(|x| Json(x))
}

```
In header only hava  `Content-Type:application/json`

![image](https://user-images.githubusercontent.com/13595898/31988102-93442d34-b933-11e7-9bf0-20a21e325f9d.png)

where set `content-type:utf-8`?

**Comment by shalugin** [comment]
@uncode See https://github.com/SergioBenitez/Rocket/issues/304
