### ISSUE TITLE
Output logs are garbled when sending concurrent requests

### ISSUE THREAD

**Issue by sgrif** [SergioBenitez/Rocket#47]
## Steps to reproduce:

- Submit multiple concurrent requests to an application which is serving some content at `/`.

## Expected behavior:

- Log output is grouped per-request, or at least uses line-buffering and includes sufficient information per-line to link that line to the relevant request.

## Actual behavior:

- Logs are mixed in an unreadable fashion, such as:

```
GET /:
    => Matched: GET /
GET /:
    => Matched: GET /
    =>     => Outcome: Succcess
Outcome: Succcess
    => Response succeeded.
    => Response succeeded.
```

In particular, the `=>     => Outcome: Succcess` line seems especially undesirable.

**Comment by SergioBenitez** [comment]
Yes, this is indeed an issue that I'm aware of. I don't have a good solution yet, but I'll merge this in with the existing logging issue #21.
