### ISSUE TITLE
Better way to the query string parameters inside a FromRequest

### ISSUE THREAD

**Issue by leocavalcante** [SergioBenitez/Rocket#476]
Simple case: using a custom Guard for Auth middlewaring based on a `access_key` param on the URL.
Did this solution was the best approach? How to improve this code?

https://github.com/leocavalcante/rusty-rocket/blob/master/src/main.rs#L25

**Comment by tcmal** [comment]
Personally I think the `Authorization` header for APIs & a session variable/private cookie would be the best way to handle this. If you're dead set on this however, I don't see where you're defining `access_token` as a query parameter.

**Comment by SergioBenitez** [comment]
This will be handled as part of #518.
