### ISSUE TITLE
Rocket places too much faith in X-Real-IP header

### ISSUE THREAD

**Issue by henrikno** [SergioBenitez/Rocket#479]
Hi,

Rocket is trusting whatever is in the `X-Real-IP` header blindly:
https://github.com/SergioBenitez/Rocket/blob/d136332e917f82f2ea3b8f8c7165d21c6a5c5c57/lib/src/rocket.rs#L183-L193

A client can spoof this by settings this header. If you're behind a trusted proxy that overrides this header you're fine, but if you're exposing this directly or through a proxy that forwards this then you should not trust this header.

The solution is to make it configurable whether to trust this header or not. If you're behind a proxy that sets it, enable it, if not disable.

Rocket 0.3.3
OS: Ubuntu 16.04

Example:
```
#![feature(plugin)]
#![plugin(rocket_codegen)]

extern crate rocket;

use std::net::SocketAddr;

#[get("/")]
fn index(addr: SocketAddr) -> String {
    return format!("{}", addr.ip());
}

fn main() {
    rocket::ignite().mount("/", routes![index]).launch();
}
```

```
curl http://localhost:8000/ -H 'X-Real-IP: 8.8.8.8'
8.8.8.8
```

**Comment by SergioBenitez** [comment]
But that's sort-of the point of the header. It's not "trusting" the header, it's simply passing the information along. If someone is altering the request before it gets to you, this header is the least of your worries.

That being said, it seems valuable to also expose the original IP address and not call this IP address `remote()`. Perhaps we can add another method to `Request` where the `X-Real-IP` logic is moved to. This gives users a choice at the expense of having to make one.

**Comment by henrikno** [comment]
Yes, the issue is that it overwrites the actual remote socket address, so the application doesn't know which one is the "real" one. If they're separate the application can decide (and it usually knows whether it's behind a proxy or not). Also, if it's overwritten you can't know which proxy IP the request came from, which is sometimes nice to know for logging.

**Comment by SergioBenitez** [comment]
Agreed. Happy to mentor an implementation of something similar to what I've proposed.

**Comment by almielczarek** [comment]
I would like to take a shot at this.

**Comment by SergioBenitez** [comment]
@almielczarek Excellent! It's all yours. Feel free to drop by #rocket on IRC if you need any help/advice!
