### ISSUE TITLE
`Content-Type` inconsistent between `String` and `&str`

### ISSUE THREAD

**Issue by sgrif** [SergioBenitez/Rocket#49]
The `Content-Type` for `String` is `text/html`, but it is `text/plain` for `&str`. This seems like an unintuitive behavior, one would expect them to behave the same. Is there a reason for this?

**Comment by reillysiemens** [comment]
I would definitely expect both of those to map to `text/plain` by default.

**Comment by SergioBenitez** [comment]
After some thought, I've come to agree. Slating for 0.2.
