### ISSUE TITLE
302 with Location from Guard

### ISSUE THREAD

**Issue by Peternator7** [SergioBenitez/Rocket#490]
Hi Rocket Team,

I'm using version 0.3.3.

I'm experimenting with OpenId Connect and Rocket. Ideally I would to put the authentication in the method parameters as a guard, but I want to be able to automatically call a 302 redirect to the authority, and it doesn't appear guards can set response headers. Is that true?

Right now my best idea for a workaround is to have the authenticator return a custom error code > 1000, and then have a catcher that for that code that returns a new response with 302 and the `location` header, but that feels a bit icky.

Is there a better way of doing that?

Thanks!
Peter

**Comment by SergioBenitez** [comment]
There is no better way to do that. That is, in fact, the suggested approach: custom status codes. The reason for that is that the user can decide to catch the error and handle it differently.

You should use a status code between 400 and 599, however. Everything outside that range is either invalid or a success/informational code.
