### ISSUE TITLE
Cannot use Tera's template inheritance

### ISSUE THREAD

**Issue by paulvt** [SergioBenitez/Rocket#495]
If one is using Tera templates and there is any template that extends another, Rocket's launch fails throwing the following launch error:

 ```
Error: Failed to initialize Tera templating.
    => Template 'index' is inheriting from 'base.tera', which doesn't exist or isn't loaded.
Error: Rocket failed to launch due to a failing fairing.
thread 'main' panicked at 'launch fairing failure', 
```

This error is thrown regardless of whether I am using any of the templates, so it probably has to do with the way the fairing is loading them?

Template inheritance is very useful for having several layouts/blocks and extended them to create page templates. See also: https://tera.netlify.com/docs/templates/#inheritance.

I am using Rocket (codege/contrib) 0.3.3 on Debian GNU/Linux testing.

**Comment by SergioBenitez** [comment]
It looks like you're asking for a template named "base.tera"; this would mean that you have a file named something like "base.tera.tera", which seems unlikely. You'll likely be able to resolve this by simply changing "base.tera" to "base".

**Comment by paulvt** [comment]
That results in:

```
    => Template 'index' is inheriting from 'base', which doesn't exist or isn't loaded.
```

So, unfortunately, doesn't help. I was a bit confused by Tera just using `index.html` but Rocket (logically) insisting on the .tera extension because it needs to know what to do.

**Comment by SergioBenitez** [comment]
Without seeing your file system layout, I don't know what things should be called. Please see the [tera templates examples](https://github.com/SergioBenitez/Rocket/tree/master/examples/tera_templates) for a concrete implementation.

**Comment by paulvt** [comment]
When using `.html.tera` as extension as opposed to just `.tera`, everything works fine! Thanks!

I followed [the guide](https://rocket.rs/guide/responses/#templates) on templating here, so it was not clear to me that a render of `index` means `index.html.tera` should exist. Maybe a note could be added or the explanation on extensions could be tweaked? (I overlooked the tera template example, sorry).
