### ISSUE TITLE
Could not understand the form validation example

### ISSUE THREAD

**Issue by hasanOryx** [SergioBenitez/Rocket#498]
I'm very new to `RUST`, tried to test the form validation example and have 2 questions:

1. What is the required password to be enytere with user name `Sergio` I tried many times different passwords more than 8 characters but keep getting `wrong password`

2 I could not understand the too `'a`s in this code block

```
#[post("/login", data = "<user_form>")]
fn login<'a>
    (user_form: 
        Form<
            'a,
             UserLogin<'a>
            >
    ) 
    -> Result<Redirect, String> { }
```

**Comment by BartWillems** [comment]
1.  The password is "password".
2. [Those are lifetime parameters](https://doc.rust-lang.org/book/second-edition/ch10-03-lifetime-syntax.html#lifetime-annotation-syntax)

**Comment by hasanOryx** [comment]
Thanks @BartWillem, apparently I did not understand the meaning if:

'let Ok(StrongPassword("password"))'
