### ISSUE TITLE
Support template streaming

### ISSUE THREAD

**Issue by seanlinsley** [SergioBenitez/Rocket#499]
Rocket already supports [file streaming](https://rocket.rs/guide/responses/#streaming), but template streaming would also be a valuable tool for application developers.

Template streaming allows the server to stream HTML as it's generated, so that the browser is able to parse & render it earlier than it otherwise would.

The most likely slowdown for page rendering is expensive / poorly optimized database queries. This allows the browser to eagerly load assets and render page navigation elements while the server is finishing up the actual content of the page. This optimization is especially important for mobile users, because network latency can easily add 5 seconds to page render time (especially if the page requires JS).

Template streaming is supported by [Rails](http://api.rubyonrails.org/classes/ActionController/Streaming.html), and [Django](https://www.mysociety.org/2015/06/01/django-streaminghttpresponse-json-html) users have found hacky solutions to get similar behavior.

It seems that there are two possible implementations:

- update the template rendering libraries to return an iterator
  - @Riamse has a working prototype for Tera: https://github.com/Keats/tera/issues/211
- have the application developer wrap certain parts of the HTML in a closure, communicating that the server can now pause to send all previous HTML to the browser
  - this is what Rails does, with closures passed to `provide`

**Comment by SergioBenitez** [comment]
I think this would be great! Thanks for brining it to the forefront; I'll keep this in mind.

**Comment by sunng87** [comment]
Template streaming sounds like an interesting idea. I will do some experiment on handlebars-rust too.

**Comment by SergioBenitez** [comment]
Moving to `async` (see #17) should be make this easy to implement, assuming support from templating engines. Because #17 covers the former, and because generally Rocket does not itself provide a templating engine, I'm closing this out.
