### ISSUE TITLE
Would a PR to use Macros 1.1 be welcome

### ISSUE THREAD

**Issue by sgrif** [SergioBenitez/Rocket#50]
While most of your codegen won't be satisfied by Macros 1.1, your custom derives will be. Using libsyntax for custom derive is currently deprecated (and sounds like it's slated for removal in 1.15). Would you be open to a PR to pull the custom derives out into a separate crate which uses macros 1.1?

**Comment by sgrif** [comment]
Also sorry for randomly dropping a bunch of issues on you on Christmas.

**Comment by SergioBenitez** [comment]
No worries on the issues! I appreciate your diligence. :)

I've given some thought to this, and at present, I'd rather keep derives as they are. My main argument against moving to macros 1.1 is that it adds another crate, and thus another line to `src/main.rs`. I expanded on this in the following comment: https://github.com/rust-lang/rust/pull/37128#issuecomment-266266617.

That being said, it _may_ be possible to reexport the derives from the core `rocket` crate, and so you'd only need to add `#[macro_use]` to `extern crate rocket`. If the derive code for macros 1.1 is significantly cleaner, for whatever reason, and this reexport can indeed be done, then I might be convinced. Still, I worry that this avenue might be confusing to users. Why should they import a plugin via `#[plugin(...)]` _and_ do a `#[macro_use]`? Codegen can be a confusing subject, and I'd like to avoid all means to further confusion.

**Comment by sgrif** [comment]
It would need to be a separate crate as it's a separate compilation mode.

**Comment by SergioBenitez** [comment]
I'm okay with having another crate as long as users don't need to explicitly import it. What I was referring to was that it might be possible to, in the `rocket` crate, add something like:

```rust
#[macro_reexport] extern crate rocket_derive;
```

And then users would write:

```rust
#[macro_use] extern crate rocket;
```

Is this what you're referring to when you say it won't work? I haven't explored this myself.
