### ISSUE TITLE
Comparison with others performance

### ISSUE THREAD

**Issue by hasanOryx** [SergioBenitez/Rocket#502]
Is there any performance comparison with others frameworks, like [Total / Node](https://www.totaljs.com/) , [Ktor / Kotlin](http://ktor.io/), [.Net Core](https://www.microsoft.com/net/learn/get-started/windows), [Dart](https://www.dartlang.org/) or others,

**Comment by SergioBenitez** [comment]
I have some (very simple) benchmarks that I ran against a few well-known frameworks at the end of [this slide deck](https://sergio.bz/docs/rocket-china-meetup-slides.pdf). In general, Rocket's performance is better, usually by a wide margin, than other high-level web frameworks, and is usually competitive or more performant than lower-level web frameworks.

Making Rocket's performance even better will be a strong focus of future releases. Expect Rocket to get faster and faster!

**Comment by hasanOryx** [comment]
Great, thanks for the presentation and wish you all the best.
