### ISSUE TITLE
Expose internal template system for improved usability

### ISSUE THREAD

**Issue by marcusball** [SergioBenitez/Rocket#51]
I think it would be useful if the internal template system—Handlebars or Tera—was exposed somewhere, so that it would be possible to make more template-specific modifications. 

For some context, I'm using Handlebars, and I want to output a string containing HTML, however, [Handlebars escapes strings by default](http://sunng87.github.io/handlebars-rust/handlebars/index.html#escaping). Hopefully this isn't a case of [the XY problem](http://mywiki.wooledge.org/XyProblem), but I figure the best way I could solve this issue would be to acquire a reference to the static `HANDLEBARS` object, so that I could mess with the `escape_fn` settings or add a custom Helper.

**Comment by SergioBenitez** [comment]
With handlebars, you can use three curly braces instead of two to render the raw HTML:

```
{{{ my_html }}}
```

Does that get you what you're looking for?

**Comment by marcusball** [comment]
Oh, yes! That does work.

Huh, now that you point that out, I see it's documented on the handlebarsjs site, but not the handlebars-rust docs, so that's how I missed it. 

Thank you! Rocket is looking really awesome, great work!

**Comment by SergioBenitez** [comment]
Awesome! And thanks for the kind words. :)
