### ISSUE TITLE
Documentation how to get URI from request handler?

### ISSUE THREAD

**Issue by stockholmux** [SergioBenitez/Rocket#510]
Apologies if this is a total newb question. I can't seem to find the answer in documentation. I'm trying to do something (seemingly) simple, so I'm sure I'm just missing something.

I have a route attribute and a request handler, and I want to respond back with the URI of the request:
```
#[get("/hello/<name>")]
fn hello(mut cookies: Cookies, name : String) -> String {
   ...
}
fn main() {
    rocket::ignite().mount("/", routes![hello]).launch();
}
```
I'd just like to get the URI in `hello.` I've seen examples for a 404 handler that has the URI:
```
#[catch(404)]
fn not_found(req: &rocket::Request) -> content::Html<String> {
    content::Html(format!("<p>Sorry, but '{}' is not a valid path!</p>
            <p>Try visiting /hello/&lt;name&gt;/&lt;age&gt; instead.</p>",
            req.uri()))
}
```
But I can't seem to get the `req` argument when using route attribute / request handler pattern, trying something like:
```
fn hello(req: &rocket::Request, mut cookies: Cookies, name : String) -> String {
   ...
}
```
yields an error like:
```
the trait bound `&rocket::Request<'_>: rocket::request::FromRequest<'_, '_>` is not satisfied
```

There seems to be basically documentation on how to use `&rocket::Request` _or_ route attribute / request handler pattern not really together. I assume they can be used together but I can't, for the life of me, find a useful example.

**Comment by SergioBenitez** [comment]
Please see the guide section on [request guards](https://rocket.rs/guide/requests/#request-guards) and note that [`&URI`](https://api.rocket.rs/rocket/http/uri/struct.URI.html) implements [`FromRequest`](https://api.rocket.rs/rocket/request/trait.FromRequest.html#provided-implementations).

**Comment by stockholmux** [comment]
OK. So I was able to get the data, but I feel like I'm doing it wrong or this is not very direct. There must be a better way, right?

```
struct ThisUri(String);

impl<'a, 'r> FromRequest<'a, 'r> for ThisUri {
    type Error = ();

    fn from_request(request: &'a Request<'r>) -> request::Outcome<ThisUri, ()> {
        return Outcome::Success(ThisUri(  request.uri().to_string() ));
        ....
    }
}

fn hello(uri: ThisUri, mut cookies: Cookies, name : String) -> String {
   println!("thisuri {}",uri.0);
}
```

**Comment by stockholmux** [comment]
@SergioBenitez This yields
```
error[E0432]: unresolved import `rocket::http::URI`
  --> src/main.rs:10:5
   |
10 | use rocket::http::URI;
   |     ^^^^^^^^^^^^^^^^^ no `URI` in `http`
```

**Comment by SergioBenitez** [comment]
Looks like you missed my edit. It's `use rocket::http::uri::URI;`

**Comment by stockholmux** [comment]
Awesome. Thank you!

**Comment by cazgp** [comment]
For anyone coming to this now, `FromRequest` is no longer implemented on `Uri` (changed from `URI`), but `Origin` works just fine.

**Comment by dmulder** [comment]
> For anyone coming to this now, `FromRequest` is no longer implemented on `Uri` (changed from `URI`), but `Origin` works just fine.

Would you mind explaining what you mean here? I'm just starting out with Rocket, and your clarification isn't specific enough.

**Comment by SergioBenitez** [comment]
@dmulder You can do this:

```rust
#[get("/")]
fn f(uri: &Origin<'_>) { }
```
