### ISSUE TITLE
Allow for setting a custom Content-Length

### ISSUE THREAD

**Issue by hamhut1066** [SergioBenitez/Rocket#514]
Feature requests _must_ include:

This is a follow on from a PR (https://github.com/SergioBenitez/Rocket/pull/482) I made against this repository last month. It was not discussed, and the use-case may be a little unclear. I am creating an issue as I think this should be considered in the Rocket codebase as it is not possible to implement around it.

  1. Why you believe this feature is necessary.

There are several specs that require setting a custom _Content-Length_, especially in the case of a HEAD request. 

  2. A convincing use-case for this feature.
The current behaviour does not comply with the HTTP Spec.

Excerpt from the spec (highlighting mine):

> The Content-Length entity-header field indicates the size of the entity-body, in decimal number of OCTETs, sent to the recipient or, __in the case of the HEAD method, the size of the entity-body that would have been sent had the request been a GET__.
https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

  3. Why this feature can't or shouldn't exist outside of Rocket.

 The following function [write_response](https://github.com/hamhut1066/Rocket/blob/dfc3ddebf162c36342aca1604f2b17997ecdb343/lib/src/rocket.rs#L135) overwrites the _Content-Length_ regardless of input, so any library/application that utilises rocket must have their Content-Length forcibly changed.

# General Comments

I welcome a discussion on this, (perhaps on reasons why this may _not_ be a good idea). I am relying on this behaviour, so hope we can work out how to implement it.

Thanks!

**Comment by SergioBenitez** [comment]
Thanks for opening up this issue!

Can you tell me more about why you need this? You say:

> 2. A convincing use-case for this feature.
The current behaviour does not comply with the HTTP Spec.

What are you referring to? Rocket automatically handles `HEAD` requests by calling the appropriate `GET` handler and stripping the response's body. As a result, it handles `HEAD` requests properly. In particular, it emits the correct `Content-Length` header without a body.

It's true that it's not currently possible to properly handle a `HEAD` request manually. Is this what you're trying to do? And if so, can you explain why?

**Comment by hamhut1066** [comment]
Hi, yes I'm trying to handle a HEAD request manually in compliance with the following Spec

https://docs.docker.com/registry/spec/api/#pushing-an-image

I could possibly have the response be handled automatically, but I may want to run custom code on the HEAD request.

Thanks Sergio.

**Comment by amouat** [comment]
Sergio, thanks for the reply.

Unfortunately, this functionality is essential for our project. Without it, we have to either maintain our own fork of Rocket or move to a different framework. I can fully understand if you don't want to support this as it is a somewhat low-level feature, and perhaps we would be better off with a different framework.

If you could let us know your thoughts, it would help us to decide whether to fork the project until the PR is merged or to move to a different framework now.

**Comment by SergioBenitez** [comment]
@amouat I think you should certainly be able to craft correct responses to `HEAD` requests with Rocket. I don't believe that @hamhut1066's PR is the correct approach, however: having a manually set header completely change the semantics of sending a response is error prone. It doesn't, for instance, prevent a user from sending a body-less but sized response to non-HEAD requests.

There are a few approaches I can see us taking here:
  1. Strip bodies from `HEAD` responses regardless of whether they were handled automatically.
    
     This would let you return any `Responder` type from a `HEAD` request handler and have Rocket automatically strip the body. The downside, of course, is that you still need to supply a body that actually has the correct size. We should do this in any case, nonetheless, to ensure that `HEAD` responses don't contain a body.

     You can accomplish the same by exposing the `strip_body` method of `Response`, but again, this opens up the possibility of malformed responses in the face of non-`HEAD` requests.

  2. Add a `Body::None(usize)` variant.

     On `HEAD` requests, Rocket will use the `usize` as the `Content-Length` header. On non-`HEAD` requests, Rocket will send a body of `Content-Length: 0`.

I like approach 1 as it's the most direct, least error-prone approach. Will that change suffice for your needs @hamhut1066, @amouat? Or, does necessitating a real body/response have performance implications in your use-cases?

**Comment by amouat** [comment]
Yes, I think that would work. Just to clarify, in our case we would have a NamedFile for the body.

It may have some performance implications, but I don't think they are important.

Would you like us to come up with a new PR? Or would you rather work on this yourself?

**Comment by SergioBenitez** [comment]
While the specific functionality requested in this issue wasn't implemented, I did implement option 1 in https://github.com/SergioBenitez/Rocket/issues/514#issuecomment-358284445 which allows for the same end-result while being less error-prone.

**Comment by arturmazurek** [comment]
I was hoping to use Rocket to send files through multipart requests.
The files are 10GB+ in size. Does the implemented option 1 mean that I have to actually supply Rocket with e.g. a dummy 10GB buffer which later on will be stripped?

**Comment by SergioBenitez** [comment]
This is a three year old issue! No, of course it doesn't mean that. The response holds a stream. The stream is dropped. No reading happens.

Please don't bump old issues with questions; discussions is a better place.
