### ISSUE TITLE
Add the right version of nightly to the documentation

### ISSUE THREAD

**Issue by calhilcaw** [SergioBenitez/Rocket#519]
Since the latest versions of nightly are breaking rocket due to the ring library drama, I was wondering if we could add: `~/.cargo/bin/rustup override set nightly-2017-12-18` for people who are new to rust? (2017-12-18 is the minimum requirement for pear-codegen and therefore rocket-codegen)

**Comment by calhilcaw** [comment]
This is in response to #513

**Comment by SergioBenitez** [comment]
Given the uncertainty brought on by #513, it seems prudent to specify which version of nightly to use in the documentation. This is something I was _really_ hoping to avoid during Rocket's life as a nightly library by always building on the latest nightly. It's a real shame that an unrelated library's unwillingness to do what's best for the community has temporarily grounded Rocket.

My thoughts are that we should indicate the proper nightly version in the [getting started guide](https://rocket.rs/guide/getting-started/) as well as the `README`, perhaps in the "building" section. Are there additional places we should record this?

**Comment by calhilcaw** [comment]
I had a brief look over your PR's for the ring library, I don't understand the unwillingness to cooperate on ring's behalf, especially in this case as you have already gone to the trouble fixing ring 0.11 for the latest nightly build.

Yes I think this is a good idea. I think definitely in the 'Getting Started' guide as rustup can be a bit of a pain for even intermediate rust users. The 'Getting Started' and the `README` seem to be the only places I can think of. I think listing the minimum requirement of nightly as well as the latest currently supported version of nightly for rocket (which I believe is `nightly-2017-12-21`) would be good too.

**Comment by SergioBenitez** [comment]
Changes made and deployed!

**Comment by hasanOryx** [comment]
I'd like to suggest looking into the option of building Rocket without dependencies, aware this may need more effort, but believe will help not sticking in such situation again, Total.js framework is doing like this.

**Comment by calhilcaw** [comment]
It looks good to me! Hopefully when Rocket is ready for 0.4 we'll be able to support the newest nightlies again!
