### ISSUE TITLE
Change how query parameters are parsed.

### ISSUE THREAD

**Issue by Aaronepower** [SergioBenitez/Rocket#524]
## Summary

Currently query parameters are required to appear in the route to be matched and call that function. This is unintuitive compared to other popular web frameworks like Flask. Take the following as an simple example where this behaviour is desired.

```rust
// Works: /hello?person=john
// Doesn't work: /hello
#[get("/hello?<person>")]
fn route(person: Option<&str>) -> String {
    format!("Hello {}", person.as_ref().unwrap_or("world"))
}
```

In order to have working version of this functionality additional boilerplate is required. This then adds to technical debt of the route, as can be seen below the two functions need to contain the same arguments minus the optional query parameters. This is especially cumbersome as `route2` provides no new information about the route that isn't already known in `route`.

```rust
#[get("/hello")]
fn route2() -> String {
    route(None)
}

#[get("/hello?<person>")]
fn route(person: Option<&str>) -> String {
    format!("Hello {}", person.as_ref().unwrap_or("world"))
}
```

## Proposed Solution
I propose that whether or not query parameters are optional should be done on the type level rather than in the route syntax. This removes the boilerplate while providing an easy way to express intent in how the route should match.

## Edge cases
There are some edge cases as to what to regarding to behaviour to a non-present or a invalid value.

#### Invalid values
Invalid values should never be accepted and should be allowed as an empty string.
```rust
// Works: /hello?foo=8
// Works: /hello
// Doesn't work: /hello?foo=world
// Doesn't work: /hello?foo=
#[get("/hello?<foo>")]
fn route(foo: Option<u8>) {}

// Works: /hello?foo=8
// Doesn't Work: /hello
// Doesn't work: /hello?foo=world
// Doesn't work: /hello?foo=
#[get("/hello?<foo>")]
fn route(foo: u8) {}
```

#### Not present/Empty values
Empty values should be allowed for a `String/&str` and for `()` where empty is defined as the key being present and the value being empty eg. `/hello?foo=` query parameters that are not present.
```rust
// Works: /hello?foo=
// Works: /hello?foo=world
// Doesn't work: /hello
#[get("/hello?<foo>")]
fn route(foo: &str) {}

// Works: /hello?foo=
// Doesn't work: /hello?foo=world
// Doesn't work: /hello
#[get("/hello?<foo>")]
fn route(foo: ()) {}
```

**Comment by chillcaw** [comment]
I like the idea of accepting `/resource` routes under `/resource?<param>`, but only if you don't have a `/resource` route defined. I personally like to separate the two routes completely and use different logic for both, I'm sure I'm not alone. In one of my applications my `/resource` returns a collection resource, and my `/resource?<param>` returns a paginated resource.

**Comment by paulvt** [comment]
There are examples where the params are used to modify the collections where this could be useful.
```
/collection
/collection?attr=specific_value
/collection?sort=desc
/collection?attrs=id,name
```
IMO in this case it makes sense to have just a single handler for the collection, and optional parameters performing there filter, sort and serialize manipulations on the collection before using it.

**Comment by SergioBenitez** [comment]
Accepted for 0.4. Tracked in #608 as part of the new query-string handling.
