### ISSUE TITLE
Model attributes and generic query parameters together

### ISSUE THREAD

**Issue by chillcaw** [SergioBenitez/Rocket#529]
I've been playing with rocket for some time now, but there is one thing that I can't quite nail and that's to do with query parameters.

I've been wanting to use generic query parameters such as `filter`, `page`, `offset`, `sortBy`, etc a long side attribute query params such as `id`, `name`, `user_id`, etc.

So far I've set up generic queries like so:
```rust
#[derive(FromForm)]
pub struct Query {
    pub filter: Option<&'static str>,
    pub orderBy: Option<&'static str>,
    pub sortBy: Option<&'static str>,
    pub searchJoin: Option<&'static str>,
    pub page: Option<i32>,
    pub offset: Option<i32>
}

impl Query {
    pub fn filter(&self) -> Vec<&'static str> {
        match self.filter {
            Some(filter_string) => filter_string.split(";").collect(),
            None => vec!["*"];
        }

    }

    pub fn order_by(&self) -> &'static str {
        self.orderBy.unwrap_or("id")
    }

    pub fn sort_by(&self) -> &'static str {
        self.sortBy.unwrap_or("asc")
    }

    pub fn search_join(&self) -> &'static str {
        search_join = self.sortJoin.unwrap_or("and");
        if search_join != "and" || search_join != "or" {
            search_join = "and";
        }

        search_join
    }

    pub fn page(&self) -> &'static str {
        self.page.unwrap_or(1)
    }

    pub fn offset(&self) -> &'static str {
        self.offset.unwrap_or(50)
    }
}

#[get("/users?<page_query>")]
fn page(conn: DbConn, page_query: Query) -> Response<'static> {
    let page = page_query.page();
    let offset = page_query.offset();

    let data = PageView::new(conn, page, offset).page();

    response::Build::new(data, 200)
}
```

I was just wondering what the best way forward for adding model attribute query parameters to this existing logic? If I could get all query parameter as a string, that could be sufficient too.

**Comment by SergioBenitez** [comment]
The best approach is to create a new type, say `Both`, that implements `FromForm` and lets you combine two `FromForm` type into one. You can then use this `Both` type as the target of a handler. Something like:

```rust
#[get("/users?<page_query>")]
fn page(conn: DbConn, page_query: Both<Query, Page>) -> T { ... }
```

A similar question has been asked before in #298. For inspiration on how to implement `Both`, see #298. Your implementation may vary. In particular, with the introduction of lenient parsing in 0.3, the implementation of `FromForm` for `Both` reduces to just a few lines and no longer requires any memory allocation. I'll leave the implementation as a challenge!

**Comment by chillcaw** [comment]
Ah this is awesome, thanks a lot. I will play around with this tonight! I will need to read up on lenient parsing, and look at the API docs, but I should be fine from here, thanks again. :)
