### ISSUE TITLE
Outdated info and example in the guide

### ISSUE THREAD

**Issue by janekp** [SergioBenitez/Rocket#538]
https://rocket.rs/guide/requests/#error-catchers

errors! -> catchers!, error! -> catch!

**Comment by SergioBenitez** [comment]
The guide is for the latest stable release, v0.3, where that information is correct. As such, I'm closing this issue.

This has changed in master, as you've noted, but the guide has been updated on the master branch to reflect this as well. In general, however, the master branch guide isn't guaranteed to be up to date given the fast and changing pace of development.
