### ISSUE TITLE
JsonValue not found on Root for Rocket_Contrib

### ISSUE THREAD

**Issue by tensor-programming** [SergioBenitez/Rocket#539]
Got a fairly basic API example that uses Rocket_contrib to serve some JSON.  I based it off of the JSON example that you have.  I am building an app for a tutorial and I wanted to see what kinds of stuff I could potentially do before actually building the real project but when I try to build this app I get an error `no `JsonValue` in the root`.  I also get an error where it isn't finding the `catchers! macro` either.

If I try to change the JsonValue to just Value, then I get a bunch of errors about it not implementing the `rocket::response::Responder<'_>` trait.   There is a basic error swapping `catchers!` to `errors!` as well involved.  I have the `default-features = "false"` and the `features = ["json"]` parts added for the rocket_contrib dependency but that doesn't seem to fix anything.  

I am running on Windows MSVC with the latest nightly build and I am using Rocket 0.3.6 for rocket, rocket_codegen and rocket_contrib in case that matters.

Edit: I tried copying and pasting your JSON example and I got the same errors even after a `cargo clean && cargo build`

Any ideas?

**Comment by SergioBenitez** [comment]
You're looking at examples from the master branch while using a stable release. Switch to the v0.3 branch to see examples compatible with v0.3.

**Comment by tensor-programming** [comment]
Alright, Ill give it a shot.

**Comment by tensor-programming** [comment]
It worked but I had to take and copy the v0.3 version of the example as well.  From what I could see in the diff between the master and the v0.3 contrib, the JsonValue type just doesn't exist in the v0.3 branch.  Does that mean that you are removing that type in the next stable release or is it the other way around?  

Sorry for all of the questions, I just want to get this straight.  

Also, according to what I was reading in the actual source of the contrib on master, I was seeing the stuff that I was using, is 0.3.6 not the master branch?

**Comment by SergioBenitez** [comment]
Master is always the latest development branch. v0.3 is a maintenance branch as it is the current stable release. `JsonValue` is a type that was added in master and not present in v0.3.

Note that master itself is unstable - depending on it is a bad idea for this reason. Commits to master may contain breaking changes. In contrast, all v0.3 releases are backwards compatible with all other v0.3 releases.
