### ISSUE TITLE
pastebin example route not mounted

### ISSUE THREAD

**Issue by Toadsworth** [SergioBenitez/Rocket#54]
I noticed that the retrieve route is never mounted in the documentation. Everywhere is shown that you shouldn't forget to mount the new route you just made, but I missed this one. (it's not very hard to figure out by yourself but since all the others are shown I thought this one might as well be added)

Maybe it would be an idea to add it add the end of the tutorial just above the conlusion.
`
fn main() {
    rocket::ignite().mount("/", routes![index, upload, retrieve]).launch()
}
`

I'm reffering to the pastebin example at: https://rocket.rs/guide/pastebin/

**Comment by SergioBenitez** [comment]
The second sentence of the conclusion, right after the discussion of the `retrieve` route, says:

> Ensure that all of your routes are mounted and test your application.

Did you read this, and if so, did you feel that it wasn't enough?

**Comment by cldershem** [comment]
I tend to be someone that tries to figure it out on my own before I look at the answer, so it didn't bother me that it wasn't explicit. However, I did think I might have missed something when there wasn't an example.

Rust in general is focused on beginner friendliness, web is one of the first things beginners try to do, and there is a very good chance Rocket becomes the beginner web framework of choice....so it might be a good idea to include it (plus, it's one of those things people will keep reporting on your issue tracker).

I'd submit a PR, but I'm can't seem to find the source for the website.

**Comment by ghazkarim** [comment]
I'm a beginner but I don't think that this is really necessary. Rocket has good documentation and when I walk through its beautiful website, which is the first thing I did, it's obvious to me that every new route has to be mounted separately. It's like writing a function and expecting it to do it's thing without actually calling it. But that's just me.

**Comment by Toadsworth** [comment]
In hindsight I think a change in the documentation is not really needed. I fixed my problem really quickly and think other people will have the same thing.
