### ISSUE TITLE
How to merge to handler with same request guard and handler's body?

### ISSUE THREAD

**Issue by sackery** [SergioBenitez/Rocket#540]
Question: There are two handler `loginned` and `register_1` with `AuthorizedUser` request guard, if this guard is successfully passed then prove that the user is logged in and return a jsonapi to respond, so the body of these two handler is the same, how to just use one handler?

**Comment by SergioBenitez** [comment]
Did you get an answer to your question?

**Comment by sackery** [comment]
...just hard coding.
