### ISSUE TITLE
.htaccess equivalent 

### ISSUE THREAD

**Issue by hasanOryx** [SergioBenitez/Rocket#543]
To allow video to be played in element from my website, but not allowing it through direct link, I created .htaccess in a sub-directory with the source videos, and nothing else. with the below code:

    RewriteEngine On
    RewriteCond %{REQUEST_URI} \.(mp4|mp3|avi)$ [NC]
    RewriteCond %{HTTP_REFERER} !^http://sample.com/.*$ [NC]
    RewriteRule ^.* - [F,L]

I need to do the same with `rocket` server, but do not know how?

**Comment by BartWillems** [comment]
I think you could do something like this:
https://github.com/SergioBenitez/Rocket/tree/master/examples/optional_redirect

**Comment by SergioBenitez** [comment]
There is no `.htaccess` equivalent. You can, of course, implement the functionality yourself. But you're likely better off either putting Rocket being NGINX/Apache to get these simple things for free or writing customized logic on top of something like the [`static_files`](https://github.com/SergioBenitez/Rocket/tree/v0.3/examples/static_files) example.

**Comment by SergioBenitez** [comment]
Looks like this has been answered.
