### ISSUE TITLE
Cannot change the listen url

### ISSUE THREAD

**Issue by PieerotGG** [SergioBenitez/Rocket#548]
Hello,

I have a really strange issue, the listen url is localhost but i can't request the rocket server with 127.0.01

So i've created my Rocket.toml file and i've puted that inside:

```toml
[global]
adress = "127.0.0.1"
port = 8000
log = "normal"
```

And the start log are:

```
🔧  Configured for development.
    => address: localhost
    => port: 8000
    => log: normal
    => workers: 16
    => secret key: generated
    => limits: forms = 32KiB
    => tls: disabled
    => [extra] adress: "127.0.0.1"
🛰  Mounting '/':
    => GET /graphql?<request>
    => POST /graphql
    => OPTIONS /graphql
    => GET /graphiql
🚀  Rocket has launched from http://localhost:8000
```

And even with this I can't request the server with 127.0.0.1 or any other adress.

Using the last version of Rocket.

Thank you !

**Comment by messense** [comment]
It's `address` not `adress`.

**Comment by PieerotGG** [comment]
Fuck me

**Comment by PieerotGG** [comment]
But same error I can't access it from 127.0.0.1

**Comment by messense** [comment]
Try:

```toml
[development]
address = "127.0.0.1"
port = 8000
```

**Comment by PieerotGG** [comment]
Okay it worked after I cargo install --force thank you !
