### ISSUE TITLE
TLS files must exist in all environments for rocket to load

### ISSUE THREAD

**Issue by DeonPoncini** [SergioBenitez/Rocket#551]
I have a website in Rocket (using v0.3.6, latest at writing). I am developing on my laptop (Mac OS X 10.12.6 (the development environment) and releasing on Amazon Linux 2017.12. The bug happens in both places

That is, in my Rocket.rs, I have defined TLS to key/cert for my development environment to /etc/ssl/<files>, whereas on Amazon Linux I am using letsencrypt, so the keys are in /etc/letsencrypt/...

If I set one global.tls and set the keys in the same location in both, there is no issue. However, I would like the keys in different locations for different environments. When I do this, I get the following error launching:

Error: I/O error while setting tls.certs:
    => No such file or directory (os error 2)

This happens with both
ROCKET_ENV=dev <exe> 
and
ROCKET_ENV=prod <exe>

On their respective machines. I believe the bug exists because:

https://github.com/SergioBenitez/Rocket/blob/master/lib/src/config/builder.rs#L307 
Calls set_tls which inside
https://github.com/SergioBenitez/Rocket/blob/master/lib/src/config/config.rs#L505
Returns the error here because the TLS file is not found

However, it should only do this on the environment that is actually executing

Please let me know if I am missing something here

**Comment by SergioBenitez** [comment]
Let's fix this in #852.

**Comment by NathanielAJohnson** [comment]
I am having the same issue and I disagree with the deficiency tag.  This is a bug.

**Comment by SergioBenitez** [comment]
@NathanielAJohnson This was the intended behavior: we want to check all configuration, but it has a drawback (this). So, it's not a bug since it's working as expected, but we've realized it's maybe not the way things _should_ work. Hence, a deficiency (of the current design).

**Comment by rethab** [comment]
Came across this as well. My workaround is to setup TLS using environment variables locally instead of the config:
```bash
export ROCKET_TLS="{certs = \"etc/cert.pem\" key = \"etc/key.pem\"}"
cargo run
```
