### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by hoobean1996** [SergioBenitez/Rocket#555]
## Questions
I am using Rocket 0.3.6,In my project,
I want organize my files like this:
----pro
 - Cargo.toml
 - Cargo.lock
 -src
├── lib.rs            //here contains : pub mod model, pub mod route
├── main.rs
├── model
│   └── mod.rs
└── route
    └── mod.rs

I want to  organize all routes in a mod, but when I finished it in route/mod.rs,

#![feature(plugin)]
#![plugin(rocket_codegen)]
extern crate rocket;
extern crate rocket_codegen;
#[get("/world")]
fn world() -> &'static str {
    "Hello,World"
}
something wrong!

![image](https://user-images.githubusercontent.com/35843204/35686892-5c746d6e-07a8-11e8-965e-60c0eb4b9e4e.png)

does the route have to place in src/main.rs?
how to solve this?
thanks.

**Comment by SergioBenitez** [comment]
You need to place

```rust
#![feature(plugin)]
#![plugin(rocket_codegen)]
```

at the crate root. This is usually src/main.rs. Note that this is true for Rust in general: crate attributes need to be at the crate root.

**Comment by hoobean1996** [comment]
Thanks.
problem has been solved

**Comment by spacekookie** [comment]
@SergioBenitez I'd actually be curious what your opinions are of more rigidly enforcing a project structure (like Django or ember.js)
