### ISSUE TITLE
Use actix-web as http server backend.

### ISSUE THREAD

**Issue by fangyuanziti** [SergioBenitez/Rocket#559]
Do you have experience with [`actix-web`](https://github.com/actix/actix-web). It seems that it support HTTP, HTTP2, async concurrency and websocket which are needed to implement a morden web server.
Currently the `Rocket` use hyper as then web backend which limits  HTTP2 and websocekt features. Shall we use `actix-web` to replace `hyper` to get all those features?
If we decide not to change our backend, shall we split our rocket sugar syntax code into a separate project, so that we can reuse it's code to add the nice syntax for other web framework?

**Comment by SergioBenitez** [comment]
Let's track this in #17.

**Comment by fangyuanziti** [comment]
Should I repost those questions in #17 ?

**Comment by kjeremy** [comment]
@fangyuanziti I think so.
