### ISSUE TITLE
Overly strict FromSegments implementation for PathBuf

### ISSUE THREAD

**Issue by Noughmad** [SergioBenitez/Rocket#560]
In the interest of safety, the implementation of `FromSegments` for `PathBuf` ([code](
https://github.com/SergioBenitez/Rocket/blob/8b1aaed0cecb0a26dde8f1aa4ce89a2a4003f957/lib/src/request/param.rs#L339)) rejects all segments that start with a dot (`.`). I believe this is overly strict, since

1. The dot-dot case (a filename of exactly `..`) is already handled.
2. A single dot segment (exactly `.`) could also be valid, and just skipped.
3. Lots of hidden files start with `.`, such as `.gitignore` and other config files.

In my use case I only require the third case, as I am trying to create a file browser, where the path is specified as `<path..>` and `path: PathBuf`. However, such a route cannot browse a file with a name starting with a dot, and I get a `Failed to parse 'path': BadStart('.')` error message. 

I can reproduce this behavior on version `0.3.6` on ArchLinux, but looking at the code I can see it is present in `master` as well.

**Comment by zxvfxwing** [comment]
Hi,

I have also encountered this behavior when I wanted to accept dotfiles (as you say) in my routes.
@SergioBenitez answered me on matrix channel / IRC bridge after exposing my problem.
You can read the entire conversation [here](https://riot.im/app/#/room/!NkeCEOxYAAanlPMmEf:matrix.org/$15106551905wxJcZ:spokonline.net).

So I made a [workaround](https://github.com/zxvfxwing/fancyndex/blob/v1.0/src/filesystem/unsafepath.rs) (used in [one of my personal](https://github.com/zxvfxwing/fancyndex/blob/96e4cae57dbedc732a3064ede1b880cf1f8fbf0f/src/api/home.rs#L53) project) which is certainly not perfect but works.

Use case:

```rust
#[get("/<unsafe_p..>")]
pub fn dotfiles(unsafe_p: UnsafePBuf) -> ... {
    let dotpath = unsafe_p.path();
    /* Do wathever you want with your path */
}
```
Hopefully, my answer met your expectations.

**Comment by SergioBenitez** [comment]
The danger is that users will unknowingly leak hidden files if this change is made. I'd like to keep the safe-by-default behavior while also allowing users to disable this on a per-case basis.

In https://github.com/SergioBenitez/Rocket/issues/239#issuecomment-288869202 I sketch out an API for mounting a "StaticFiles" handler. To resolve this issue, that handler could accept options on creation to allow this behavior:

```rust
rocket::ignite()
    .mount("/path_to_serve_on", StaticFiles::from("/path_to_serve_from").allow_hidden());
```

I've already laid out all of the ground work to enable the implementation of something like `StaticFiles`, and I've implemented a very basic version of `StaticFiles`. Once my team frees up a bit, I'll polish the implementation and merge it in.

If this sounds like a good plan moving forward @Noughmad, let's close this and track progress in #239.

**Comment by Noughmad** [comment]
Serving static files is not good for me, as I want to show other things in addition to the file content. 

However, as I said I the workaround meantioned above works for me, and is not overly complicated. So unless you wish to change the current implementation, feel free to close the issue.

**Comment by SergioBenitez** [comment]
@Noughmad The plan in my previous comment covers your use-case as well by relaxing the constraints on PathBuf. I'll close this out and track in #239.

**Comment by Scripter17** [comment]
> P.S: Complementary to this, we could have the `StaticFiles` handler deny hidden files by default but have `PathBuf` allow them. We'd then advocate for only using `StaticFiles` to serve static files with the safe-by-default behavior. `PathBuf` would be relegated to special cases, protecting against path traversal attacks but nothing else.

Has any progress been made on this in the last 2 and a half years? For reasons that aren't relevant using `FileServer` simply will not work for me.

I would quite like to be able to decide myself whether or not I want to handle a provided path. Yeah security by default is nice but I'd like the option to turn it off.

Also, @zxvfxwing, your workaround seems to not work in rocket 0.5.0-rc

**Comment by SergioBenitez** [comment]
> > P.S: Complementary to this, we could have the `StaticFiles` handler deny hidden files by default but have `PathBuf` allow them. We'd then advocate for only using `StaticFiles` to serve static files with the safe-by-default behavior. `PathBuf` would be relegated to special cases, protecting against path traversal attacks but nothing else.
> 
> 
> 
> Has any progress been made on this in the last 2 and a half years? For reasons that aren't relevant using `FileServer` simply will not work for me.
> 
> 
> 
> I would quite like to be able to decide myself whether or not I want to handle a provided path. Yeah security by default is nice but I'd like the option to turn it off.
> 
> 
> 
> Also, @zxvfxwing, your workaround seems to not work in rocket 0.5.0-rc

Yes. Rocket doesn't prohibit you from doing anything in this space, and never did. You can take a raw [`Segments`](https://api.rocket.rs/v0.5-rc/rocket/http/uri/struct.Segments.html#) and convert it to a path yourself.

**Comment by Scripter17** [comment]
I probably should've clarified my issue is that routes refuse to accept any path with a segment starting in `.`

As far as I can tell doing this

```Rust
#[macro_use] extern crate rocket;
use std::path::PathBuf;

#[get("/<path..>")]
fn route(path: PathBuf) -> _ {
    //
}

#[launch]
fn rocket() -> _ {
    rocket::build()
        .mount("/route", routes![route])
}
```

will never let you access `/route/.fileINeedToAccess`, at least in 0.5.0-rc.2. And yes. I need to handle directories too. I know what I need and this is it. Alternative design suggestions will be both ignored and not appreciated as they are irrelevant to the problem at hand

If there's a way to use raw `Segments`s as you said then I'll do it but as far as I'm concerned I shouldn't have to

**Comment by SergioBenitez** [comment]
> I probably should've clarified my issue is that routes refuse to accept any path with a segment starting in `.`
> 
> 
> 
> As far as I can tell doing this
> 
> 
> 
> ```Rust
> 
> #[macro_use] extern crate rocket;
> 
> use std::path::PathBuf;
> 
> 
> 
> #[get("/<path..>")]
> 
> fn route(path: PathBuf) -> _ {
> 
>     //
> 
> }
> 
> 
> 
> #[launch]
> 
> fn rocket() -> _ {
> 
>     rocket::build()
> 
>         .mount("/route", routes![route])
> 
> }
> 
> ```
> 
> 
> 
> will never let you access `/route/.fileINeedToAccess`, at least in 0.5.0-rc.2. And yes. I need to handle directories too. I know what I need and this is it. Alternative design suggestions will be both ignored and not appreciated as they are irrelevant to the problem at hand
> 
> 
> 
> If there's a way to use raw `Segments`s as you said then I'll do it but as far as I'm concerned I shouldn't have to

As I said in my response, you simply need take a `Segments` and convert it to a path yourself. Here's the code allowing dotfiles, in case the docs are out of reach:

> #[get("/<path..>")]
> 
> fn route(path: Segments<'_, Path>) -> _ {
> 
>     let path = path.to_path_buf(true)?;
> 
> }

**Comment by Scripter17** [comment]
Oh I didn't realize that was even possible

Sorry 'bout that
