### ISSUE TITLE
Empty response when JSON fails to deserialize

### ISSUE THREAD

**Issue by idubrov** [SergioBenitez/Rocket#562]
1. The version of Rocket you're using. Ensure it's the latest, if possible.

0.3.6

2. The operating system (distribution and version) where the issue occurs.

Mac OS X Sierra 10.12.6 (16G1212)

3. A brief description of the bug that includes:

 * The nature of the bug.

Connection is immediately closed if JSON being deserialized returns an error. The following log messages I think explain it well:

```
 WARN  rocket::data::data_stream > Data left unread. Force closing network stream.
 ERROR rocket_contrib::json      > Couldn't parse JSON body: ErrorImpl { code: Message("missing field `url`"), line: 1, column: 3244 }
 INFO  rocket::rocket            > Outcome: Failure
 WARN  rocket::rocket            > Responding with 400 Bad Request catcher.
 ERROR rocket::rocket            > Failed to write response: Error { repr: Os { code: 32, message: "Broken pipe" } }.
 INFO  hyper::server             > set_read_timeout keep_alive Error { repr: Os { code: 22, message: "Invalid argument" } }
```

 * When the bug occurs.

Client submits JSON request which fails to deserialize in `rocket_contrib-0.3.6/src/json.rs:101`

 * What you expected vs. what actually happened.

I expected 400 error to be returned. What I get is client receiving no response (connection is closed).

4. How you uncovered the bug. Short, reproducible tests are especially useful.

Accidentally. Don't have test case at the moment.

5. Ideas, if any, about what Rocket is doing incorrectly.

I think, Rocket should skip the remaining data when deserialization fails.

**Comment by SergioBenitez** [comment]
I agree Rocket can be doing better here. There's no harm in doing what it's doing, however.

This will be solved once https://github.com/SergioBenitez/Rocket/pull/547 is merged.
