### ISSUE TITLE
Travis: build not accessible

### ISSUE THREAD

**Issue by ishitatsuyuki** [SergioBenitez/Rocket#57]
It seems that you're using a private Travis subscription(travis-ci.**com**), while the repository itself is open source and public.

Travis is inaccessible from public users, since you are using a (possibly paid) private subscription. Please migrate to travis-ci.org.

**Comment by SergioBenitez** [comment]
Yeah, this is unfortunate. The repository was initially private, so I (necessarily) used a private Travis CI thing. I'd like to migrate it over to a public one, but I'm not sure how to do that without losing the build history. I sent an email to the Travis folks some days ago, but they're away for Holidays. This will be resolved as soon as I hear back.

**Comment by SergioBenitez** [comment]
It looks like it's not possible to migrate the build history. 😞 

From Travis support:
> ...it is not possible to transfer the build history when open sourcing your application. Because the public and private builds are really two separate systems at the moment, it is not possible to transfer builds from one to the other.

I've switched the badge to the public version in https://github.com/SergioBenitez/Rocket/commit/e9ad5b5c02c80d273aff22c4684e48446f34df2f.
