### ISSUE TITLE
Rocket matches routes with single character

### ISSUE THREAD

**Issue by lschuermann** [SergioBenitez/Rocket#574]
When using the following minimal rocket application, I just stumbled upon the `/test`-route not only being accessible at `/test` but also at `/t`. Is this intended behavior? It does not work with `/te`, `/tes`, etc.

```
#![feature(plugin)]
#![plugin(rocket_codegen)]
extern crate rocket;

#[get("/test")]
fn test() -> &'static str {
    "Hi!"
}

fn main() {
    rocket::ignite()
        .mount("/", routes![test])
        .launch();
}
```

My `Cargo.toml` dependencies:
```
[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rocket_contrib = { version = "*", default-features = false, features = ["json"] }
```

I'm using `rustc` version `rustc 1.25.0-nightly (3ec5a99aa 2018-02-14)`.

Thanks!

**Comment by lschuermann** [comment]
In case this bug can be reproduced by other people, I'm willing to look into fixing this. Because I'm still pretty new to Rust and especially Rocket, could you give me a few pointers on where to start?

**Comment by SergioBenitez** [comment]
I've confirmed this.

Strangely, if you change `/test` to `/hello` in the `test()` route, `/h` won't be routed to `/hello`. If you change it to `/true`, `/t` doesn't route to `/true` either. Changing it to `/te` or `/tes` also doesn't exhibit the incorrect behavior; only `/test`.

Excited to find out what tom-foolery has led to this.

**Comment by lschuermann** [comment]
Oh, that's some weird stuff. Try with `/students`, it shows the same behavior.
I only tried `/test` and `/students`, I would've never guessed that it could work correctly with `/hello` then!

**Comment by SergioBenitez** [comment]
The bug is in the collider implementation for strings. This bug will occur when the request URI is both a suffix and a prefix of route's URI. For instance, a request for `/t` will route to `/test`, `/tt`, or `/thit`. Similarly, `/hi`, will route to `/hihi` and `/hitherehi`.

The is caused by a failure to check for early termination of a string match.

I am working on a fix now.

**Comment by lschuermann** [comment]
Thanks! Then I apparently had some pretty bad examples! :)

**Comment by SergioBenitez** [comment]
Thank you so much for finding and reporting this, @lschuermann! I really appreciate it.
