### ISSUE TITLE
Get a config option from Rocket.toml

### ISSUE THREAD

**Issue by olegantonyan** [SergioBenitez/Rocket#576]
I want to get `assets_dir` from `Rocket.toml`. This issue https://github.com/SergioBenitez/Rocket/issues/173 kind of has answer,  I just don't understand how to use it

Here is my code:
```
#![feature(plugin)]
#![plugin(rocket_codegen)]

extern crate rocket;
extern crate rocket_contrib;

use rocket_contrib::Template;
use rocket::response::NamedFile;
use rocket::config;

use std::collections::HashMap;
use std::path::{Path, PathBuf};

#[get("/")]
pub fn index() -> Template {
    let mut context = HashMap::new();
    context.insert("name", "Rust");
    Template::render("index", &context)
}

#[get("/<asset..>")]
fn assets(asset: PathBuf) -> Option<NamedFile> {
    let assets_dir = config::active().map(|config| {
	    let dir = config.get_str("assets_dir").unwrap();
        config.root().join(dir).to_string_lossy().into_owned()
	}).unwrap();
    println!("{}", assets_dir);

    NamedFile::open(Path::new(assets_dir).join(asset)).ok()
}

fn rocket() -> rocket::Rocket {
    rocket::ignite()
        .mount("/", routes![index, assets])
        .attach(Template::fairing())
}

fn main() {
    rocket().launch();
}
```
And this is a compile error:
```
error[E0425]: cannot find function `active` in module `config`
  --> src/main.rs:25:30
   |
25 |     let assets_dir = config::active().map(|config| {
   |                              ^^^^^^ not found in `config`
```

It's suggested in #173 to do it this way:
```
let rocket = rocket::ignite();

let config = /* your init here */;

rocket.mount(...)
    .manage(config)
    .launch()
```
But is there a concrete example? I don't understand what `/* your init here */` should look like to get the actual config form Rocket.toml.
Maybe this is something obvious everyone understand without documentation. If it is, please, give me an advise what book to read to get this.

rocket 0.3.6
rustc 1.26.0-nightly (322d7f7b9 2018-02-25)
cargo 0.26.0-nightly (1d6dfea44 2018-01-26)

**Comment by SergioBenitez** [comment]
I believe this is directly answered in the rustdocs [here](https://api.rocket.rs/rocket/config/index.html#retrieving-configuration-parameters).

**Comment by olegantonyan** [comment]
Thank you @SergioBenitez 

This works:
```
#![feature(plugin)]
#![plugin(rocket_codegen)]

extern crate rocket;
extern crate rocket_contrib;

use rocket_contrib::Template;
use rocket::response::NamedFile;
use rocket::fairing::AdHoc;
use rocket::State;

use std::collections::HashMap;
use std::path::{Path, PathBuf};

struct AssetsDir(String);

#[get("/")]
pub fn index() -> Template {
    let mut context = HashMap::new();
    context.insert("name", "Rust");
    Template::render("index", &context)
}

#[get("/<asset..>")]
fn assets(asset: PathBuf, assets_dir: State<AssetsDir>) -> Option<NamedFile> {
    NamedFile::open(Path::new(&assets_dir.0).join(asset)).ok()
}

fn rocket() -> rocket::Rocket {
    rocket::ignite()
        .mount("/", routes![index, assets])
        .attach(Template::fairing())
        .attach(AdHoc::on_attach(|rocket| {
            let assets_dir = rocket.config().get_str("assets_dir").unwrap().to_string();
            Ok(rocket.manage(AssetsDir(assets_dir)))
        }))
}

fn main() {
    rocket().launch();
}
```

I've created PR to include this into the guide. I think this is one of those things the majority of people want to do right from the beginning, like `templates_dir`. But `templates_dir` works automagically, and to achieve the same result for assets you have to do this extra work. Or maybe it's better to include this into static_files example rather than configuration guide?

**Comment by JokerQyou** [comment]
Sorry to comment on a closed issue, but it does not work as the doc describes now. The following code follows the exact pattern, but does not compile.

```rust
rocket::ignite()
        .attach(AdHoc::on_launch("Secrets config", |rocket| {
            let bot_token = rocket.config()
                .get_str("telegram_bot_token")
                .unwrap()
                .to_string();
            Ok(rocket.manage(TelegramBotToken(bot_token)))
        }))
        .mount("/", routes![index])
        .launch();
```

```
error[E0308]: mismatched types
   --> src/main.rs:204:13
    |
204 |             Ok(rocket.manage(TelegramBotToken(bot_token)))
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^- help: try adding a semicolon: `;`
    |             |
    |             expected `()`, found enum `std::result::Result`
    |
    = note: expected unit type `()`
                    found enum `std::result::Result<rocket::Rocket, _>`
```

**Comment by nathanielford** [comment]
One thing I'm not clear on here is a best practice around management of the configuration; is it a good idea to create a separate struct for every element in your configuration (that matters) and pass it to `rocket` to manage? On the one hand 'yes' seems like a reasonable answer (it forces the programmer to be explicit about every item in the configuration's usage), but on the other it makes the configuration ingestion feel on the verbose side. Since I'm pretty new to rust and very new to rocket, I figured I'd ask since I wasn't able to find good examples.

The scenario I was trying to wrap my head around was using the `StaticFiles` type from `rocket_contrib`, rather than the above solution. I can attach a fairing to pull the config before I mount it - but my instinct was that having n adhoc fairings attached to rocket in main was not what was intended.

**Comment by jebrosen** [comment]
@nathanielford 

>  I can attach a fairing to pull the config before I mount it - but my instinct was that having n adhoc fairings attached to rocket in main was not what was intended.

That is a fine thing to do, and is even suggested by the documentation: <https://api.rocket.rs/v0.4/rocket/config/index.html#retrieving-configuration-parameters>.

> is it a good idea to create a separate struct for every element in your configuration (that matters) and pass it to `rocket` to manage

This is up to the application - `rocket` does not have any particular preferences here. Sometimes there is an external reason that influences the decision break apart or group together certain configuration - for example, a program that can run as a CLI or as a web server, where some configuration is shared and some is server-specific. There *is* a (small) performance cost paid per-request for each separate piece of configuration accessed through `State`, so from that angle fewer managed pieces of data may be better if they are usually used together in routes.

**Comment by nathanielford** [comment]
Thank you! I did find the AdHoc fairings to get configuration in the documentation (documentation win!), but it's super helpful to understand the boundary of what Rocket is attempting to manage. Knowing it's intending to be agnostic to the application handling configuration gives me a lot of confidence I'm not being bone-headed about it. :)
