### ISSUE TITLE
Rocket realworld demo

### ISSUE THREAD

**Issue by TatriX** [SergioBenitez/Rocket#582]
Hello! I'm working on the ["The mother of all demo apps"](https://github.com/gothinkster/realworld) backend [implementation](https://github.com/TatriX/realworld-rust-rocket) which uses Rocket.

I hope it can be a nice example of how one can use Rocket to make a "real world" app.

As I'm not a pro rust/rocket user I will appreciate any feedback: https://github.com/TatriX/realworld-rust-rocket

Realword issue: https://github.com/gothinkster/realworld/issues/172

**Comment by SergioBenitez** [comment]
This is pretty cool! Well done! Once it's merged, I'll see how I can add a note to the documentation or elsewhere to point users to it.

**Comment by TatriX** [comment]
So it was finally [merged](https://github.com/gothinkster/realworld/pull/318)
I'm also [updating](https://github.com/TatriX/realworld-rust-rocket/pull/7) it to use `0.4`.

Since I wasn't using Rocket actively, because I had to use rust-stable, it will be nice to get some comments on the codebase and how I can improve it.

**Comment by TatriX** [comment]
In case you are curios, I've added Rocket's native database support and wrote tests, again using Rocket's builtins.

I have several questions:
1) What is the most idiomatic way to handle errors in Rocket's world?
2) I'd like to use custom config so I could load database from `.env` file, such that both `diesel_cli` and application itself could reuse it. But it's not entirely clear to me how the custom config works, for instance will it handle dev/release mode the way default config does?

**Comment by jebrosen** [comment]
> 1. What is the most idiomatic way to handle errors in Rockets world?

Rocket itself doesn't have any particular requirements on how errors should be handled -- even `std::error::Error` is used only rarely. I do see a few places especially in database access where you `panic!` or return `None` when you could return a `Result` -- perhaps via your own `Errors` type.

> 2. I'd like to use custom config so I could load database from `.env` file, such that both `diesel_cli` and application itself could reuse it. But it's not entirely clear to me how the custom config works, for instance will it handle dev/release mode the way default config does?

The default behavior for `diesel_cli` is to read the `.env` file and check the `DATABASE_URL` environment variable. Rocket does not read the `.env` file and the environment variable syntax is not a single connection url: `ROCKET_DATABASES='{db={url="url"}}'`.

If you want to be fully compatible with `diesel_cli`, I think the easier choice would be to 1) read the `.env` file using the [dotenv](https://crates.io/crates/dotenv) crate, and then 2) [apply the database configuration manually](https://api.rocket.rs/v0.4/rocket_contrib/databases/index.html#procedurally). Manual configuration this way has a few warts that we plan to address in #852, but you should be able to adapt that code to your needs.

**Comment by SergioBenitez** [comment]
I'm closing this issue out, only because this isn't an issue. I'll be enabling GitHub discussions soon, and I'd love to have a showcase post! When it's there, I encourage you to share your project.
