### ISSUE TITLE
Error catcher with info about error

### ISSUE THREAD

**Issue by sergeysova** [SergioBenitez/Rocket#586]
Rocket v0.3.6
Rust 1.26

How can I handle errors from request guard?

https://rocket.rs/guide/requests/#error-catchers

I want to give info about error https://github.com/sergeysova/instaclone-backend.rs/blob/5ea7fe68aa39d0dd4093b0ed7818a7faa6b65aac/src/auth.rs#L87 like `AuthError::NoUserOsSession`

And JSON parsing/validation errors too

![image](https://user-images.githubusercontent.com/5620073/37489240-0b02ce50-28a8-11e8-9233-d977f1dac4d4.png)

**Comment by SergioBenitez** [comment]
At present, if you want to handle a guard error response value, you need to catch the error in a handler with a `Result`. If the error type implements `Responder`, you can forward it nice an easy as follows:

```rust
fn route(guard: Result<GuardType, AssociatedErrorType>) -> Result<T, AssociatedErrorType> {
    let value = guard?;
    ...
}
```

If it doesn't implement `Responder`, you can still catch it in a `Result`, but you'll need to generate a value that implements `Responder` yourself.

I'm hoping to improve error handling soon. We'll track that in #596. I think this answers the question, so I'm closing the issue out. Feel free to comment if you feel this isn't the case or just want to follow-up.

**Comment by sergeysova** [comment]
@SergioBenitez Need I use route instead of error handler?

**Comment by sergeysova** [comment]
I need to handle `AuthError` in error handlers: https://github.com/sergeysova/instaclone-backend.rs/blob/5ea7fe68aa39d0dd4093b0ed7818a7faa6b65aac/src/routes/mod.rs#L77
