### ISSUE TITLE
build of v0.3.6

### ISSUE THREAD

**Issue by mghz** [SergioBenitez/Rocket#589]
I got latest on the library and did checkout v0.3.6. when I build the project I get this error: 

error: multiple packages link to native library `sqlite3`, but a native library can be linked only once

package `libsqlite3-sys v0.9.1`
    ... which is depended on by `diesel v1.1.1`
    ... which is depended on by `todo v0.0.0 (file:///Users/mghz/wspace/projects/Rocket/examples/todo)`
links to native library `sqlite3`

package `libsqlite3-sys v0.8.1`
    ... which is depended on by `rusqlite v0.12.0`
    ... which is depended on by `raw_sqlite v0.0.0 (file:///Users/mghz/wspace/projects/Rocket/examples/raw_sqlite)`
also links to native library `sqlite3`

**Comment by SergioBenitez** [comment]
What are you trying to do? Development happens on either the master branch or 0.x branch.
