### ISSUE TITLE
Hello World not compiling in v0.3.6

### ISSUE THREAD

**Issue by sverrisson** [SergioBenitez/Rocket#593]
I am new to Rust so I wanted to run the Hello World example here. 

After installing the Rust compiler (v1.24.1) and running the following command, I get the errors listed:
`git clone https://github.com/SergioBenitez/Rocket && cd Rocket && git checkout v0.3.6 && cd examples/hello_world && cargo run`

**Error produced in the console:**
```bash
Cloning into 'Rocket'...
remote: Counting objects: 10676, done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 10676 (delta 2), reused 18 (delta 1), pack-reused 10626
Receiving objects: 100% (10676/10676), 2.12 MiB | 2.41 MiB/s, done.
Resolving deltas: 100% (6458/6458), done.
Note: checking out 'v0.3.6'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 174f85e... New version: 0.3.6.
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading pear_codegen v0.0.12                                               
 Downloading yansi v0.3.4                                                       
 Downloading pear v0.0.12                                                       
 Downloading state v0.3.3                                                       
   Compiling cfg-if v0.1.2                                                      
   Compiling smallvec v0.4.4
   Compiling rayon-core v1.4.0
   Compiling pear v0.0.12
   Compiling percent-encoding v1.0.1
   Compiling untrusted v0.5.1
   Compiling matches v0.1.6
   Compiling serde v1.0.35
   Compiling typeable v0.1.2
   Compiling state v0.3.3
   Compiling language-tags v0.2.2
error[E0554]: #![feature] may not be used on the stable release channel
 --> /Users/Hannes/.cargo/registry/src/github.com-1ecc6299db9ec823/state-0.3.3/src/lib.rs:1:1
  |
1 | #![feature(const_fn)]
  | ^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
 --> /Users/Hannes/.cargo/registry/src/github.com-1ecc6299db9ec823/state-0.3.3/src/lib.rs:2:1
  |
2 | #![feature(const_unsafe_cell_new)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
 --> /Users/Hannes/.cargo/registry/src/github.com-1ecc6299db9ec823/state-0.3.3/src/lib.rs:3:1
  |
3 | #![feature(const_atomic_usize_new)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
 --> /Users/Hannes/.cargo/registry/src/github.com-1ecc6299db9ec823/state-0.3.3/src/lib.rs:4:1
  |
4 | #![feature(const_atomic_bool_new)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 4 previous errors

error: Could not compile `state`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Further details on the iMac (Retina 5K, 27-inch, Late 2014),  macOS 10.13.3 (17D102):
3,5 GHz Intel Core i5
24 GB 1600 MHz DDR3
AMD Radeon R9 M290X 2 GB

Rustc -V:
rustc 1.24.1 (d3ae9a9e0 2018-02-27)

## Bug Reports

Bug reports _must_ include:

  1. The version of Rocket you're using. Ensure it's the latest, if possible. 0.3.6

## Steps Taken to Fix
- Tried running the master branch with no avail.
- Don't want to run a nightly build of the compiler but that may be the next try.

**Comment by jebrosen** [comment]
Rocket currently requires nightly builds of rust, as explained in the [quickstart](https://rocket.rs/guide/quickstart/). Issue #19 has more information regarding the exact unstable features Rocket uses.

**Comment by sverrisson** [comment]
Thanks I see that now - I should delete the issue?

**Comment by DJMcNab** [comment]
> Rocket makes abundant use of Rust's syntax extensions and other advanced, unstable features. Because of this, we'll need to use a nightly version of Rust 

From https://rocket.rs/guide/getting-started/.

However, perhaps it is relevant that there is no note of the nightly requirement in https://rocket.rs/guide/quickstart, where the commands run are from.

Maybe the final command could be changed in order to address this, to:

```
cargo +nightly run
```

**Comment by sverrisson** [comment]
Yes, the following change fixed it. Perhaps the quick start should be updated: 
`git clone https://github.com/SergioBenitez/Rocket && cd Rocket && git checkout v0.3.6 && cd examples/hello_world && cargo +nightly run`

**Comment by jebrosen** [comment]
The first paragraph of the quickstart page does indicate this:
>Before you can start writing a Rocket application, you'll need a **nightly** version of Rust installed. We recommend you use rustup to install or configure such a version.

That said, I see no major downsides to using `cargo +nightly run` there either.
