### ISSUE TITLE
environment variable `DATABASE_URL` not defined

### ISSUE THREAD

**Issue by haruhinoshana** [SergioBenitez/Rocket#599]
hi goodmorning im just a new user of rocket. I do include diesel on my project like on the tutorial 

but always got this error environment variable `DATABASE_URL` not defined

i do setup .env already using echo DATABASE_URL=postgres://username:password@localhost/diesel_demo > .env

**Comment by SergioBenitez** [comment]
If you want to use a `.env` file, you need to use the `dotenv` crate. See the [Diesel getting started guide](http://diesel.rs/guides/getting-started/) for more information.

**Comment by haruhinoshana** [comment]
thankyou sir
