### ISSUE TITLE
"Error: No matching routes for" is duplicated for autohandled HEAD requests.

### ISSUE THREAD

**Issue by jebrosen** [SergioBenitez/Rocket#606]
Rocket version: master
Operating System: Arch Linux
rustc --version: rustc 1.27.0-nightly (ad610bed8 2018-04-11)

Currently, the `Error: no matching routes for ...` message is displayed unconditionally when a route is not found. This results in output like the following:

```
🚀  Rocket has launched from http://localhost:8000
HEAD /:
    => Error: No matching routes for HEAD /.
    => Autohandling HEAD request.
    => Matched: GET / (index)
    => Outcome: Success
    => Response succeeded.
HEAD /does/not/exist:
    => Error: No matching routes for HEAD /does/not/exist.
    => Autohandling HEAD request.
    => Error: No matching routes for GET /does/not/exist.
    => Warning: Responding with 404 Not Found catcher.
    => Response succeeded.

```

Or in production, maybe something like:
```
Rocket has launched from http://127.0.0.1:8000
Error: No matching routes for HEAD /.
Error: No matching routes for HEAD /does/not/exist.
Error: No matching routes for GET /does/not/exist.
Warning: Responding with 404 Not Found catcher.
```

I'm not sure whether it would be better to say there is no matching route for GET or for HEAD in the error case, but I think seeing two for one request is confusing. I don't think the message is at all helpful in the success case because there is already a notification that Autohandling is happening.

**Comment by SergioBenitez** [comment]
I think I like that you get to know that both `HEAD` and `GET` were tried, but perhaps the first `HEAD` should be a warning if it will be autohandled? I think _any other_ functionality would be confusing.

I think, for production logs, you'd want something like:

```
[TIME] HEAD / -> GET / (index) (success: 200)
[TIME] HEAD /does/not/exist (failure: 404)
```

**Comment by jebrosen** [comment]
I think combining it into one line in production would be acceptable -- My main motivation for opening this is the hundreds of lines of "Error: No matching routes for HEAD /" in the production error logs when there was nothing actually wrong.

**Comment by SergioBenitez** [comment]
Ah, yes, that makes sense. Let's keep that in mind for #21. Closing in favor of tracking there.
