### ISSUE TITLE
same route used more than once on different handler functions will result in a runtime crash when mounting

### ISSUE THREAD

**Issue by mitp0sh** [SergioBenitez/Rocket#611]
Hello, 

I'm using the lastest version of rocket in my project and stumbled over a small issue:

I have define a route for a POST like this:

`#[post("/service/xxx/ep-project-blah", format = "application/octet-stream", data = "<data>")]
pub fn service_endpoint_project_open(data: Data) -> Json<Template> {`

Due to an mistake, when implementing something different I just copied the whole function and forgot to change the routing accordingly. Basically I just had two routings pointing to different handler but mapping to the same name.

It compiled just fine, but when starting my application it crashed right away. After I realized that this was most likely the same routing I changed it and the application did not crash anymore.

Of course this was my issue but I would rather expect that rocket will either just bind the first mapping or the last registered. In any case it should not just fade away with a crash imho.

This is not an important issue, but I guess it would make rocket even more awesome as is already is if you could fix it. The operating system I used was Windows 10 - Enterprise, latest patch level.

Thank you very much,
mitp0sh

**Comment by SergioBenitez** [comment]
What does "crash" mean? Rocket is designed to fail fast on misconfiguration like this one, but it should do so with an error message indicating why it's failing. Can you post the logs?

**Comment by mitp0sh** [comment]
I have to admit it didn't screen the strack trace for fast fail initially...my apologies. But apart from that, do you consider it required to bail out like this ?

In my opinion the application shouldn't panic. I would rather prefer to allow the developer to have multiple equal routes but define a rule which of these finally get registered.

But maybe you consider that a bad design.

See a white labelled stack trace here:

> STACK_TEXT:  
0000006f`79dfd4f0 00007ffd`4fea2cdf : 00007ff6`00000003 00007ff6`00000003 00000000`00000006 00000000`00021000 : ucrtbase!abort+0x4e
0000006f`79dfd520 00007ff6`912391b7 : 00000000`00000080 00000000`00024000 00000020`00001000 ffffae8e`01000000 : ucrtbase!terminate+0x1f
0000006f`79dfd550 00007ffd`50906913 : 00007ff6`91239180 0000006f`79dfff00 00000000`00000006 00000000`00000006 : some_exe+0x1e91b7
0000006f`79dfd580 00007ffd`5369da9d : 00000000`00000000 00007ffd`5372ae2c 00000000`00000000 00000000`00000000 : KERNELBASE!UnhandledExceptionFilter+0x153
0000006f`79dfd690 00007ffd`53686466 : 0000006f`79dfe6f0 0000006f`79dfd710 0000006f`79dfe0c0 00007ffd`51262774 : ntdll!RtlUserThreadStart$filt$0+0x38
0000006f`79dfd6c0 00007ffd`5369a07d : 00000000`00000000 0000006f`79dfd860 00000000`00000001 0000006f`79dfd820 : ntdll!_C_specific_handler+0x96
0000006f`79dfd730 00007ffd`53609c58 : 00000000`00000000 00000000`00000001 00000000`00000000 00000000`00000000 : ntdll!RtlpExecuteHandlerForException+0xd
0000006f`79dfd760 00007ffd`53605851 : 00000000`00000000 00000000`00000000 0000006f`79dfdec0 00000000`00000000 : ntdll!RtlDispatchException+0x368
0000006f`79dfde70 00007ffd`50969f68 : 0000006f`79dfe6e8 00007ffd`14d80390 00007ffd`2c998630 0000006f`79dfe840 : ntdll!RtlRaiseException+0x311
0000006f`79dfe6d0 00007ffd`2c987d20 : 0000bf43`cf124359 00000000`00000015 00000000`00000000 00000000`00000001 : KERNELBASE!RaiseException+0x68
0000006f`79dfe7b0 00007ffd`149801fc : 0000006f`79dfe898 00007ffd`14f3bdc4 0000006f`79dfe8e0 0000006f`79dfe960 : VCRUNTIME140D!_CxxThrowException+0x130
0000006f`79dfe860 00007ffd`148b228f : 00000000`00000015 00000000`00000019 000000d0`00000011 0000017b`74b6c050 : ***_integration_x86_64!_rust_start_panic+0x7c
0000006f`79dfe8b0 00007ffd`148b20af : ffffffff`00000000 ffffffff`fffffffd 00000000`00000002 0000017b`74b66f80 : ***_integration_x86_64!rust_panic.llvm.5141089389197493436+0xf
0000006f`79dfe930 00007ffd`14938027 : 0000017b`00000000 00000000`00000010 00007ffd`14d82dcc 00000000`00000000 : ***_integration_x86_64!ZN3std9panicking20rust_panic_with_hook17h2f479d8461252804E+0x26f
0000006f`79dfea00 00007ffd`14961bf2 : 0000017b`738d3400 00000000`00000000 00000000`0000001e 00010000`00000000 : ***_integration_x86_64!ZN3std9panicking11begin_panic17haa5d4a5fd7962dd8E+0x47
0000006f`79dfea40 00007ffd`1489835d : 0000017b`74b65ac8 0000006f`79dfeb40 0000006f`79dff440 00000000`00000000 : ***_integration_x86_64!ZN68_$LT$rocket..error..LaunchError$u20$as$u20$core..ops..drop..Drop$GT$4drop17h400d44b873509061E+0x102
0000006f`79dfeac0 00007ffd`14d5274f : cccccccc`cccccccc cccccccc`cccccccc cccccccc`cccccccc cccccccc`cccccccc : ***_integration_x86_64!***_local_node_start_rocket+0x231d
0000006f`79dffdd0 00007ffd`51262774 : 0000017b`739cdd00 00000000`00000000 00000000`00000000 00000000`00000000 : ***_integration_x86_64!qthread_cb_***_server+0x2f
0000006f`79dffed0 00007ffd`53660d51 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : KERNEL32!BaseThreadInitThunk+0x14
0000006f`79dfff00 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21>

**Comment by SergioBenitez** [comment]
Please look at your console logs. Rocket is not failing, it's returning an error, and you will see messages on your console about why and even how to fix it. No, it is not bad design to detect and inform the user about misconfiguration.
