### ISSUE TITLE
Better error message

### ISSUE THREAD

**Issue by elbaro** [SergioBenitez/Rocket#613]
rocket 0.3.9

```rust
fn new_redis_pool() -> RedisPool {
    let manager = RedisConnectionManager::new("redis://localhost").expect("Redis connection fail");
    r2d2::Pool::builder().build(manager).expect("Redis connection pool build fail")
}

rocket::ignite().mount("/", ...).manage(new_redis_pool()).launch();
```

If a redis-server is not running, you get

```
...
Error: address not available: Cannot assign requested address (os error 99)
Error: address not available: Cannot assign requested address (os error 99)
Error: address not available: Cannot assign requested address (os error 99)
Error: address not available: Cannot assign requested address (os error 99)
Error: address not available: Cannot assign requested address (os error 99)
...
```

The message misleads the user to think that the port is already in use or this is a permission problem.

**Comment by SergioBenitez** [comment]
Where is that error message coming from? I don't think Rocket is producing it, so there's nothing we can do to fix it. That being said, once #167 lands, we will be able to massage error massages however we want for supported databases.

**Comment by elbaro** [comment]
Here is a minimal example: https://gist.github.com/elbaro/f3c4a307a7c4dacedf579be1fb5580cf
Outside docker, I see the error 111 instead.

```
...
Error: connection refused: Connection refused (os error 111)
Error: connection refused: Connection refused (os error 111)
...
```

When RedisPool is used without rocket, it hangs without printing anything.
```rust
fn main() {
    new_redis_pool(); // hangs
}

fn new_redis_pool() -> RedisPool {
    let manager = RedisConnectionManager::new("redis://localhost").expect("Redis connection fail");
    // hangs here. this function doesn't return
    r2d2::Pool::builder() 
        .build(manager)
        .expect("Redis connection pool build fail")
}
```

But when used with rocket, it still hangs and does not return from `new_redis_pool`, but error messages are printed in console.

It seems Rocket prints those errors or changes the verbose level of redis library.

**Comment by SergioBenitez** [comment]
Indeed, that message isn't originating from Rocket. Rocket configures a logger, which all logged messages pass through, so Rocket _does_ style and emit the message, but it didn't create it in the first place. As such, there's nothing we can do to improve it at this point. Let's keep this in mind for #167.
