### ISSUE TITLE
Ring fails to compile on macOS

### ISSUE THREAD

**Issue by unbe4table** [SergioBenitez/Rocket#615]
Rust nightly 1.27 (2018-04-29)
macOS High Sierra 10.13.5 Beta.

Ring library can not compile. I receive 136 "random" errors (Ring 0.11.0)
Earlier versions of Rocket also can not compile because of Ring.
Although Linux version runs with no errors and works fine.

It's definitely a Ring's problem and changing version to 0.12.1 solves the problem.

I would appreciate a change of the Rocket's Ring version to a newer one as it fully solves this issue.

**Comment by SergioBenitez** [comment]
Please post more information:

  * Which version of Rocket?
  * Can you post the complete build logs with errors? (Ideally behind a "details" drop-down)

Rocket v0.3.9 and master compile just fine on macOS 10.11.6 using `rustc 1.27.0-nightly (79252ff4e 2018-04-29)`.

**Comment by SergioBenitez** [comment]
@unbe4table The master version is, unfortunately, not ready for a release. Do you know _why_ master works while v0.3 does not? Is it because of the newer `ring` version?

**Comment by unbe4table** [comment]
>@unbe4table The master version is, unfortunately, not ready for a release. Do you know _why_ master works while v0.3 does not? Is it because of the newer `ring` version?

@SergioBenitez Yeah, every Ring version earlier than 0.12 fails to compile. Rocket 0.3.9 and earlier versions use Ring 0.11 while Master branch uses 0.13 and therefore works as expected.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Speedy37** [comment]
cookie 0.9.1 and 0.9.2 use ring 0.11.0, which does not compile on windows too with latest MSVC 2017 on Win 10 April update.

**Comment by SergioBenitez** [comment]
Okay, so everything is okay on master. This is really unfortunate. ring is causing issues on Windows as well. Alas, there's not much we can do (see #687 and so on). As such, I'm closing this out.
