### ISSUE TITLE
Docs.rs  is not supported

### ISSUE THREAD

**Issue by huangjj27** [SergioBenitez/Rocket#616]
I was searhing the latest version of API Documents on docs.rs, but found out the [breaking build log](https://docs.rs/crate/rocket/0.3.7/builds/94475) as follow:

```
   Compiling pear_codegen v0.0.14
     Running `/home/cratesfyi/cratesfyi/debug/build/pear_codegen-6cad8be9d26c6389/build-script-build`
error: failed to run custom build command for `pear_codegen v0.0.14`
process didn't exit successfully: `/home/cratesfyi/cratesfyi/debug/build/pear_codegen-6cad8be9d26c6389/build-script-build` (exit code: 101)
--- stderr
Error: Pear requires a more recent version of rustc.
Use rustup update or your preferred method to update Rust
Installed version is: 1.26.0-dev (2018-03-16) Minimum required: 1.27.0-nightly (2018-04-03)
thread 'main' panicked at 'Aborting compilation due to incompatible compiler.', .cargo/registry/src/github.com-1ecc6299db9ec823/pear_codegen-0.0.14/build.rs:43:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.

thread 'main' panicked at 'Error(
    CargoError(
        build failed
    ),
    State {
        next_error: None,
        backtrace: None
    }
)', src/bin/cratesfyi.rs:142:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Shall we update the rust version?

**Comment by unbe4table** [comment]
Rocket requires the latest Rust nightly version.

> Installed version is: 1.26.0-dev (2018-03-16) Minimum required: 1.27.0-nightly (2018-04-03)

As the error message says install the 1.27.0-nightly version and you should be good to go.
```
rustup default nightly
rustup override set nightly
rustup update && cargo update
```

**Comment by huangjj27** [comment]
@unbe4table I'm sorry not to make the issue clear. I found the issue on docs.rs, but on my local

**Comment by jebrosen** [comment]
There is https://api.rocket.rs/rocket/ , which is what the rocket crate links to as its docs. I didn't even know rocket was on docs.rs, and if there are compiler incompatibilities like this I wonder if perhaps it shouldn't be there.

**Comment by huangjj27** [comment]
@jebrosen all right, I'll check that documents. Leaving the issue along if the author want to fix it.

**Comment by huangjj27** [comment]
@jebrosen all right, I'll check that documents. Leaving the issue along if the author want to fix it.

**Comment by SergioBenitez** [comment]
There's not much we can do to fix it, unfortunately. I've wanted a way to opt-out of docs.rs for a while, but no such mechanism is currently available. In any case, https://api.rocket.rs is the only supported online documentation for Rocket.

I'll leave this issue open to gather suggestions about how to handle docs.rs.

**Comment by DJMcNab** [comment]
You already use the custom docs.rs metadata in cargo.toml, which enables all features.

Using this, you can put this warning:
```rust
#![cfg_attr(
    feature = "docsrs",
    doc = "\
# ⚠️Rocket does not support docs.rs api documentation⚠️
Use [api.rocket.rs](https://api.rocket.rs/rocket/) instead
See [#616](https://github.com/SergioBenitez/Rocket/issues/616) for why
"
)]
```

just above [the main introduction documentation](https://github.com/SergioBenitez/Rocket/blob/master/lib/src/lib.rs#L14-L15). This main section which seems to build successfully (https://docs.rs/crate/rocket/0.3.10).

This also requires adding `docsrs = []` into the features section of [lib/cargo.toml](https://github.com/SergioBenitez/Rocket/blob/3894e4e9fe526a27492ca62f4a9e4d4aec5667bd/lib/Cargo.toml).

**Comment by huangjj27** [comment]
change the title, and I think the problem is solved
