### ISSUE TITLE
Get request with body

### ISSUE THREAD

**Issue by Johnlon** [SergioBenitez/Rocket#622]
I have a case where we have a get request that takes a complex query argument.
To overcome length restrictions on the query string the long parameter is passed in the request body to the Get request and not as a query string parameter.

For a get request how can I access the payload of the request.

With a Post request I can use ...
#[post("/upload", data = "<data>")]

But 
#[get("/search", data = "<data>")]

Is rejected by the compiler.

How do I access the get request payload?

(Before we we into a discussion about get requests with bodies, this is not prohibited by the specs and some products like elastic use this eg https://www.elastic.co/guide/en/elasticsearch/guide/current/_empty_search.html)

**Comment by maxdeviant** [comment]
Are you actually using Elasticsearch?

From their docs:
> However, because GET with a request body is not universally supported, the search API also accepts POST requests:

This is the first I've heard of GET requests supporting a body, and it sounds very non-standard. Some quick searching [reveals](https://stackoverflow.com/a/983458) that others (including the creator of the REST architecture) feel similarly about this.

Is there any reason you can't change this to be a POST?

**Comment by Johnlon** [comment]
Legacy integration for starters.
We also have layer 4 WAF supporting this feature.
Further reading with reveal that the direction loosens (removes) comments
about get body's.

Get is generally deemed by infra and ACL to be non mutating and a get body
is a long standing way to overcome long Param restrictions.

JVM libs being used do not have this limitation.



On 3 May 2018 5:36 am, "Marshall Bowers" <notifications@github.com> wrote:

Are you actually using Elasticsearch?

From their docs:

However, because GET with a request body is not universally supported, the
search API also accepts POST requests:

This is the first I've heard of GET requests supporting a body, and it
sounds very non-standard. Some quick searching reveals
<https://stackoverflow.com/a/983458> that others (including the creator of
the REST architecture) feel similarly about this.

Is there any reason you can't change this to be a POST?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SergioBenitez/Rocket/issues/622#issuecomment-386189461>,
or mute the thread

**Comment by SergioBenitez** [comment]
This is interesting. While `GET` requests are not identified as payload-bearing requests by the standard, you're right that the standard doesn't directly prohibit payloads in `GET` requests. That being said, they are very unorthodox, and `GET` handlers with payloads are likely to be a mistake rather than intended.

I propose that we change the hard error into a warning. This way, we can still catch mistakes while allowing payload for `GET` requests when absolutely necessary.

**Comment by Johnlon** [comment]
Hi the point I was making is that we use get with payload.
It's not an error but a legitimate pattern but rarely seen.
We have a JSON or XML body describing the complex query.

Similarly a post request might contain query parameters.

Three difference between the two method types is semantic only and not
technical.

My recommendation is to distinguish Get from post only in terms of name.

**Comment by Johnlon** [comment]
Given rocket is a technical framework for web apps a question is whether
you need or want to be opinionated about something that is not restricted
by the spec.

My recommendation is to distinguish Get from post only in terms of name.

:-)

**Comment by Johnlon** [comment]
Hi I don't think this was resolved.
See my recommendation.

john.lonergan@gmail.com

**Comment by Johnlon** [comment]
And yes we do it elastic.

In one case we were going to user your lib as part of a proxy but cannot as
it doesn't support get and post as I described.
I suggest adopting the more liberal approach previously recommended.
What is there to lose?

**Comment by SergioBenitez** [comment]
@Johnlon How was this not resolved? Rocket now allows bodies on `GET` requests.

**Comment by Virtual-felix** [comment]
> I propose that we change the hard error into a warning. This way, we can still catch mistakes while allowing payloads for `GET` requests when absolutely necessary.

Hi, is there a way to silent the warning when we do this on purpose?
`#[rocket::get("/", format = "application/json", data = "<data>")]`
I don't know the warning type to allow it with `#[allow(warning_type)]`

There is a //FIXME comment on the [related warning generation](https://github.com/SergioBenitez/Rocket/blob/56a617262525de758cb47a0d71049db948f24bbd/core/codegen/src/attribute/route.rs#L62), I don't know really know what it means.

**Comment by BenTaylorPublic** [comment]
I'd also like a way to silent this warning.

**Comment by irexiz** [comment]
I'd like if the warning would return a non 0 exit code, 
```bash
warning: `data` used with non-payload-supporting method
   --> src/routes/network/root.rs:174:51
    |
174 | #[get("/instances/<instance_id>/network/routing", data = "<query>")]
    |                                                   ^^^^^^^^^^^^^^^^
    |
note: 'GET' does not typically support payloads
   --> src/routes/network/root.rs:174:3
    |
174 | #[get("/instances/<instance_id>/network/routing", data = "<query>")]
    |   ^^^
    = note: this warning originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

The above warning slips by our `cargo clippy -- -D warnings` pipeline
