### ISSUE TITLE
Matching with optional query args and optional "?"

### ISSUE THREAD

**Issue by Johnlon** [SergioBenitez/Rocket#623]
If I have a query like "/enquiry?foo=123" but the foo param is optional  then how to I implement such that both ...
"/enquiry?foo=123" and 
"/enquiry?" and 
"/enquiry"

all match the handler?

**Comment by maxdeviant** [comment]
This covers the first two cases:

```rust
#[derive(FromForm)]
struct Params {
  foo: Option<u8>
}

#[get("/enquiry?<params>")]
fn enquiry(params: Params) -> String {
    format!("Foo is {:?}!", params.foo)
}
```

I think if you want to handle the case with no `?` you would need to [forward](https://rocket.rs/guide/requests/#forwarding-guards) to another handler.

This appears to be consistent with the [tests](https://github.com/SergioBenitez/Rocket/blob/master/examples/query_params/src/tests.rs#L38-L46) for the `query_params` example:

```rust
#[test]
fn no_params() {
    run_test!("", |response: Response| {
        assert_eq!(response.status(), Status::NotFound);
    });

    run_test!("?", |response: Response| {
        assert_eq!(response.status(), Status::NotFound);
    });
}
```

**Comment by maxdeviant** [comment]
Note, it looks like the optional `?` has already been requested in #376 and a pending implementation in #454.

**Comment by SergioBenitez** [comment]
You cannot do all three, as @maxdeviant alludes to. The query handling reform coming soon will enable this. Let's track that in #608.
