### ISSUE TITLE
Can't use LenientForms as query parameters.

### ISSUE THREAD

**Issue by FuzzyWuzzie** [SergioBenitez/Rocket#628]
Re: Rocket 0.3.9, according to the docs: https://rocket.rs/guide/requests/#lenient-parsing:

> You can use a LenientForm anywhere you'd use a Form

However, trying to replicate the test here: https://github.com/SergioBenitez/Rocket/blob/33e972615160b2ac0bba2a93ada38c72b6399ba3/lib/tests/strict_and_lenient_forms.rs#L19-L22 but for query parameters:

```rust
#[derive(FromForm)]
struct MyForm<'r> {
    field: &'r RawStr,
}

#[get("/lenient?<form>")]
fn lenient<'r>(form: LenientForm<'r, MyForm<'r>>) -> String {
    form.get().field.as_str().into()
}
```

Creates an error:

```
error[E0277]: the trait bound `rocket::request::LenientForm<'_, routes::MyForm<'_>>: rocket::request::FromForm<'_>` is not satisfied
  --> src/routes.rs:72:1
   |
72 | #[get("/lenient?<form>")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `rocket::request::FromForm<'_>` is not implemented for `rocket::request::LenientForm<'_, routes::MyForm<'_>>`
   |
   = note: required by `rocket::request::FromForm::from_form`
```

Unless I'm misunderstanding things, this shouldn't create an error.

**Comment by SergioBenitez** [comment]
This is indeed confusing. For query parameters, you don't use `Form`. Instead, you can use any type that implement `FromForm` ([guide](https://rocket.rs/guide/requests/#query-strings)). This doesn't include `Form` or `LenientForm`, and this is why your example doesn't compile.

There is a query string handling reform coming soon (#608) that makes what you're trying to do possible. Let's track this issue there.

**Comment by FuzzyWuzzie** [comment]
Ok, thanks!
