### ISSUE TITLE
Allow registration of template helpers / filters

### ISSUE THREAD

**Issue by philwhineray** [SergioBenitez/Rocket#63]
Handlebars allows the registration of helpers and Tera the registration of filters, which allow custom functions to be included in templates.

See PR #60 for some initial discussion.

**Comment by SergioBenitez** [comment]
Slating this for 0.4.0 for now. In all likelihood, this will make into 0.3.0.

**Comment by Rukenshia** [comment]
I really hope this will be possible soon. I could really need helpers for my project right now.

**Comment by jaroslaw-weber** [comment]
I was hoping that I would find an example but I found this... I need simple equality check but cannot do it without template helper.

**Comment by SergioBenitez** [comment]
@jaroslaw-weber See #364 for ongoing discussion on how to implement this.

**Comment by SergioBenitez** [comment]
Closing this in favor of #64, which implicitly resolves this.

**Comment by RalfJung** [comment]
> Slating this for 0.4.0 for now. In all likelihood, this will make into 0.3.0.

Seems like it did not make it into 0.3 (from what I can see in the docs). Is there an ETA for 0.4?

**Comment by SergioBenitez** [comment]
There is no ETA for 0.4.
