### ISSUE TITLE
How to set response's headers?

### ISSUE THREAD

**Issue by AurevoirXavier** [SergioBenitez/Rocket#634]
Hi, thanks for writing this awesome framework.

## Questions

The version of Rocket: Latest.

My Rocket application always **lost responding** and I found there're 128 `CLOSE_WAIT`. (After I use nginx to filter the rquests, this problem solved. *5/8/2018 added*)

I check my code and I've no idea what cause this.

Now, I'm trying to add `Connection: close` to response's headers .

**Comment by SergioBenitez** [comment]
Are you on master or 0.3.10? Can you say more about your solution?

**Comment by AurevoirXavier** [comment]
I'm using the `rocket="*"`. Actually I don't have any idea about that question. Maybe some spider or hacker cause that.

So I install nginx.

There're two ways to solve this problem:
1. `return 403` when request `/`.
2.  use a domain and `return 403` when request by ip.

Now, I'm more interesting in how to configure response's header ; )

**Comment by SergioBenitez** [comment]
You can add a header to all responses using a [response fairing](https://rocket.rs/guide/fairings/).
