### ISSUE TITLE
Dangling link to config in rocket_contrib templates docs

### ISSUE THREAD

**Issue by RalfJung** [SergioBenitez/Rocket#637]
The docs at <https://api.rocket.rs/rocket_contrib/struct.Template.html> link to https://rocket.rs/guide/overview/#configuration (Ctrl-F "the configuration chapter"). That anchor no longer exists, I suppose this should point to https://rocket.rs/guide/configuration/?

**Comment by SergioBenitez** [comment]
Absolutely. Pushing a fix now.

**Comment by SergioBenitez** [comment]
Fixed in a040ddd1221b7ba7aaebce0ed2282a24afcc6524. Thanks for the report!
