### ISSUE TITLE
Light gray on white is nigh-unreadable

### ISSUE THREAD

**Issue by BartMassey** [SergioBenitez/Rocket#639]
Thanks much for Rocket, really enjoying it! This is sort of a bug / enhancement request, and doesn't really fit the requested format, so I shoehorned it in as best as I could.

## Bug Reports

  1. The version of Rocket you're using. Ensure it's the latest, if possible.

0.3.10

  2. The operating system (distribution and version) where the issue occurs.

Debian Stretch

  3. A brief description of the bug that includes:
    * The nature of the bug.

When Rocket starts up, it prints colored log text to the console, which is neat. However, part of it is very light gray, which makes it extremely hard to read against a white terminal background.

    * When the bug occurs.

Rocket startup.

    * What you expected vs. what actually happened.

Expect legible text, get hard-to-read text.

  4. How you uncovered the bug. Short, reproducible tests are especially useful.

Started a Rocket server.

  5. Ideas, if any, about what Rocket is doing incorrectly.

It would be great if Rocket would choose a different color for the currently light-gray text. Unfortunately, the other seven colors in the eight-color terminal palette are currently in use, so something may have to double up.

**Comment by SergioBenitez** [comment]
Can you post a screenshot?

**Comment by BartMassey** [comment]
<https://i.imgur.com/XVSGBjU.png>

Upon further inspection, the URL is printed in an even lighter shade of gray, so apparently the 16-color terminal palette is in use. :smile:

**Comment by BartMassey** [comment]
Leaving the double-right-arrows as gray seems fine. Maybe just change the color of the text to magenta or something?

BTW, might as well use ⇒ for the arrows: you're commited to Unicode anyhow. :smile:

**Comment by SergioBenitez** [comment]
Rocket is emitting the ASCII escape code for "white" for these characters. Unfortunately, to my knowledge, there is no way for Rocket to detect the background color of the terminal and choose colors accordingly. Thus, it is up to you (via the color-scheme) and your terminal to configure the color appropriately.

**Comment by BartMassey** [comment]
It turns out that Gnome Terminal, which is what I use, chooses to print bold text in "lighter colors", which is why the bold white text in my screenshot was lighter.

Almost every terminal on the planet is either black-on-white or white-on-black at this point. That makes explicit choice of ANSI black or ANSI white as text color a problem.

I can and now did change my terminal ANSI white to some darkish shade of gray just so that I can see this text. Most users either can't or won't. Why not pick a color everybody with a terminal can read for this text? The colors are just decorative anyhow, as far as I know?

In any case, thanks for looking at the issue.

**Comment by SergioBenitez** [comment]
I was wrong to dismiss this; we shouldn't prefer one terminal color scheme over another, especially when color defaults make Rocket's output unreadable. A fix is incoming.

**Comment by BartMassey** [comment]
Thanks much! I didn't expect you to revisit this after all this time, but I really appreciate it.
