### ISSUE TITLE
Allow access to native template features

### ISSUE THREAD

**Issue by philwhineray** [SergioBenitez/Rocket#64]
At present the Handlebars and Tera template functionality is fully encapsulated.

It is likely that users will choose one based on features unique to that engine. Rocket should be able to expose the appropriate objects to make those features available.

See PR #60 for initial discussion.

**Comment by kardeiz** [comment]
I'm feeling this limitation too.

I think an acceptable resolution would be to just make `rocket_contrib::templates::Context` public. Then users could write their own fairing, which could modify e.g. `Tera` through `context.engines.tera` after calling `Context::initialize`, and then add the `Context` to `Rocket` state.

`Context` doesn't seem to contain any information that *must* be kept private. It's not ideal to make users set the templates directory manually (as in my scenario above), but is not that difficult, and that part of `Template::fairing` could be abstracted out into a `Template::root` function.

**Comment by seanlinsley** [comment]
I've submitted a new PR if anyone wants to try it out: #500.
