### ISSUE TITLE
Bug: Catching internal server error (500)

### ISSUE THREAD

**Issue by olback** [SergioBenitez/Rocket#640]
Rocket version: `0.3.10`  
Rustup: version `1.11.0`  
Cargo version: `1.27.0-nightly (af3f1cd29 2018-05-03)`

OS: Antergos (Arch linux), rolling release.  

I think this is the only relevant code in this issue:
```rust
#[error(404)]
fn not_found(req: &Request) -> Template {
    let context = site::ErrorTemplate {
        code: 404,
        error: "Page not found".to_string(),
        message: format!("The path {} could not be found.", req.uri())
    };

    Template::render("error_hfjhgdhf", &context) // This trows an internal server error, as expected.
    // Template::render("error", &context) // This works. Shows the 404 page as intended.
}

#[error(500)]
fn internal_server_error() -> Template {
    let context = site::ErrorTemplate {
        code: 500,
        error: "Internal server error".to_string(),
        message: "The server encountered an internal error while processing this request.".to_string()
    };

    Template::render("error", &context)
}

// This as shown in an example does not work either. https://api.rocket.rs/rocket/struct.Catcher.html
// #[error(500)]
// fn internal_server_error() -> &'static str {
//     "server error"
// }

fn main() {
    rocket::ignite()
    .mount("/", routes![index, assets, download, mail, success, error, send_mail])
    .attach(Template::fairing())
    .catch(errors![not_found, internal_server_error])
    // .attach(Template::fairing()) // order does not change anything
    .launch();
}
```

The problem is cathing the sevrer error with `#[error(500)]` does not seem to be working. I don't know of any other way to trow an internal server error so I don't know if this issue is specific to this case.
Expected behavior would be to chatch the 500 error thrown from the `not_found` function.

Ideas, if any, about what Rocket is doing incorrectly? No idea.

All the code can be found [here](https://github.com/olback/olback.net/tree/3.0).

**Comment by SergioBenitez** [comment]
It looks like you're trying to catch an error from an error handler, is that right? If so, that doesn't work now and will likely never be allowed. This is because allowing this would enable potentially infinite routing loops, something we'd like to avoid.

**Comment by olback** [comment]
Yes, that is correct. To prevent infinite loops wouldn't it be possible to just return the default 500 page if your custom 500 catcher fails?

If the above mentioned isn't an option would it be possible to check if all the mentioned templates exist at launch? Maybe print a warning message in the console if one or more templates don't exist.

Would it even be worth it to implement a feature like this though?

**Comment by SergioBenitez** [comment]
There are many tricks we can play, but they're all tricks. We don't want to allow a user to forward to 500 different error catchers, for instance.

No, that is not generally possible. We are working on a new feature that will ameliorate the concern entirely, however.
