### ISSUE TITLE
Same function name in different module for routing

### ISSUE THREAD

**Issue by tandrysyawaludin** [SergioBenitez/Rocket#641]
Hi i have this code,
`use one::static_rocket_route_info_for_create;`
`use two::static_rocket_route_info_for_create;`

they are placed in different module but when i used that syntax in main.rs, i got an error message "duplicate". I know i use same-function-name but anyone know how to solve it if i wanna use same same-function-name?

**Comment by DJMcNab** [comment]
Instead of `use`ing both, you should refer to them as `one::static_rocket_route_info_for_create` and `two::static_rocket_route_info_for_create;` in the routes macro.

**Comment by SergioBenitez** [comment]
Exactly as @DJMcNab states. This is also covered [in the guide](https://rocket.rs/guide/overview/#namespacing).
