### ISSUE TITLE
Schema validation

### ISSUE THREAD

**Issue by ChrisBuchholz** [SergioBenitez/Rocket#65]
What would be the preferred way to plug in something like valico to validate JSON body data against a schema before it is serialized into a struct that is returned to its route?

Would it be better to validate the struct after it has been passed to the route by rocket?

**Comment by SergioBenitez** [comment]
This is the sort of thing [FromData](https://api.rocket.rs/rocket/data/trait.FromData.html) was tailor-made for. To integrate valico, I would:

  1. Create a new type. Let's call it ValidJSON<T>.

          struct ValidJSON<T: Deserialize>(T);

  2. Implement `FromData` for `ValidJSON`, likely by calling contrib::JSON::from_data in the implementation, doing the validation, and returning an appropriate `Outcome` depending on the results.

You'd then use the type in a route as follows:

```rust
#[post("/", data = "<val>")]
fn (val: ValidJSON<T>) ...
```

**Comment by ChrisBuchholz** [comment]
Ah, exactly what I was looking for. Thanks!
