### ISSUE TITLE
Can not set log level for Rocket with log4rs

### ISSUE THREAD

**Issue by zoumi** [SergioBenitez/Rocket#651]
Here is the code to test:
https://github.com/zoumi/test_rocket_log4rs

The problem is:
If I set root's log level to "warn" and set rocket::rocket log level to "info", it works as expected.
But, if I set root's log level to "debug" and set rocket::rocket log level to "warn", Rocket's "info" message will
still be printed.

**Comment by zoumi** [comment]
Why this ERROR appears:
[2018-05-30 21:42:37] ERROR [rocket::rocket]-🚀  Rocket has launched from http://0.0.0.0:8000

**Comment by SergioBenitez** [comment]
This is already ameliorated in master in 3a8d0e8a9a156e06b8ce57a3a4fa8a1426eed29d.

**Comment by zoumi** [comment]
@SergioBenitez
But, if I use env_logger and set RUST_LOG=warn, Rocket's "info" message will be filter out.

**Comment by zoumi** [comment]
@SergioBenitez Will this issue be reopened?
