### ISSUE TITLE
Inline HTTP crate docs into core lib

### ISSUE THREAD

**Issue by SergioBenitez** [SergioBenitez/Rocket#656]
Blocked by rust-lang/rust#51252.

**Comment by QuietMisdreavus** [comment]
A PR that fixed that issue was just merged, so the next nightly that comes out should have it.

**Comment by SergioBenitez** [comment]
Excellent! This has indeed been fixed. Thanks, @QuietMisdreavus!

**Comment by SergioBenitez** [comment]
Note that hidden items are currently being reexported in the `http` docs due to https://github.com/rust-lang/rust/issues/53417.
