### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by Tobaloidee** [SergioBenitez/Rocket#658]
Good day Sir @SergioBenitez , I am a graphics designer and I want to contribute to your project by proposing a logo design which I think will make the project more visible and interesting. I will be gladly doing it as a gift for free, I will ask your permission first before i start my design. Thanks and best regards!

- [Tobaloidee](https://github.com/Tobaloidee)

**Comment by SergioBenitez** [comment]
We already have a logo, which I'm rather content with. I think at this time, I'd like to stick with it. But thank you for the offer. Best of luck!

**Comment by Tobaloidee** [comment]
okay Sir..thanks for your feedback..Best regards!
