### ISSUE TITLE
Disable/modify logging per route

### ISSUE THREAD

**Issue by LeoTindall** [SergioBenitez/Rocket#661]
I would greatly appreciate the ability to disable logging for specific routes. I use Rocket to write microservices which expose a `healthz` endpoint for use by Google Cloud Engine's monitoring (and Prometheus). This is fine but logging a `GET /healthz` request every 15 seconds has a tendency to fill our logs pretty quickly.

Currently, I set logging to "critical" and manually log on other routes. It would be better to not have to do this, and instead be able to inform Rocket that a particular route shouldn't normally log when matched.

**Comment by DJMcNab** [comment]
Related to #21.

**Comment by SergioBenitez** [comment]
That's pretty interesting. Let's definitely track this in #21.
