### ISSUE TITLE
Update tera from ^0.10 to ^0.11 in rocket_contrib

### ISSUE THREAD

**Issue by zoumi** [SergioBenitez/Rocket#665]
I found a bug when rendering templates with tera 0.10. And it was fixed in 0.11. 
When will rocket_contrib update this dependence?

**Comment by jebrosen** [comment]
> When will rocket_contrib update this dependence?

For sure by the 0.4 release.

In general, this kind of version bump in a dependency cannot be made in the 0.3 branch because it might break other existing code that uses rocket with tera templates.
