### ISSUE TITLE
Rocket launches with an "ERROR" status code ? 

### ISSUE THREAD

**Issue by AdrianChallinorOsiris** [SergioBenitez/Rocket#667]
I am starting a Rocket webserver on a RUST application. The application uses the following relevant crates:

 ```
   [dependencies]
    chrono = { version = "0.4", features = ["serde"] }
    log = "0.4"
    fern = { version = "0.5", features = ["colored"] }
    rocket = "0.3.13"
    rocket_codegen = "0.3.13"
    rocket_contrib = "0.3.13"
```
In my code, I set the colours of messages using Fern, Chrono and Log crates to create a nice, coloured message log. I then start a standard Rocket server.

```
#![feature(plugin)]
#![plugin(rocket_codegen)]

#[macro_use] extern crate log;
extern crate fern;
extern crate chrono;
extern crate rocket;

use fern::colors::{Color, ColoredLevelConfig};

fn main() {

    let verbosity: u64 = 2;

    let colors = ColoredLevelConfig::new()
        .debug(Color::Magenta)
        .info(Color::Green)
        .trace(Color::BrightBlue);

    let level = match verbosity {
        0 => log::LevelFilter::Warn,
        1 => log::LevelFilter::Info,
        2 => log::LevelFilter::Debug,
        _3_or_more => log::LevelFilter::Trace,
    };

    fern::Dispatch::new()
        .chain(std::io::stdout())
        .level(level)
        .format(move |out, message, record| {
            out.finish(format_args!(
                "{} {}\t [{}] {}",
                chrono::Utc::now().format("%Y-%m-%d %H:%M:%S"),
                colors.color(record.level()),
                record.target(),
                message
            ))
        })
        .apply()
        .unwrap();

    info!("Starting up ");
    debug!("Verbosity level is {}", verbosity);


    // Startup the controller 
    info!("Starting web service controller");
    rocket::ignite()
        .mount("/", routes![index])
        .launch();
}

#[get("/")]
fn index() -> &'static str {
    "Hello, world!"
}
```
When I run this, it reports Rocket has started, but logs it as an Error. Rocket starts correctly and runs just fine.

adrian@bastet:~/Dropbox/rust/rocket$ cargo build
   Compiling rocket v0.1.0 (file:///home/adrian/Dropbox/rust/rocket)
    Finished dev [unoptimized + debuginfo] target(s) in 2.15s
adrian@bastet:~/Dropbox/rust/rocket$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/rocket`
2018-06-19 07:35:31 INFO         [rocket] Starting up
2018-06-19 07:35:31 DEBUG        [rocket] Verbosity level is 2
2018-06-19 07:35:31 INFO         [rocket] Starting web service controller
2018-06-19 07:35:31 INFO         [rocket::rocket] 🔧  Configured for development.
2018-06-19 07:35:31 INFO         [_] address: localhost
2018-06-19 07:35:31 INFO         [_] port: 8000
2018-06-19 07:35:31 INFO         [_] log: normal
2018-06-19 07:35:31 INFO         [_] workers: 16
2018-06-19 07:35:31 INFO         [_] secret key: generated
2018-06-19 07:35:31 INFO         [_] limits: forms = 32KiB
2018-06-19 07:35:31 INFO         [_] tls: disabled
2018-06-19 07:35:31 INFO         [rocket::rocket] 🛰  Mounting '/':
2018-06-19 07:35:31 INFO         [_] GET /
2018-06-19 07:35:31 ERROR        [launch] 🚀  Rocket has launched from http://localhost:8000
2018-06-19 07:35:31 DEBUG        [hyper::server] threads = 16

On my screen, the messages are colour coded.

BUT - Why is the message from Rocket that it has started recorded as an ERROR. It's all successful, so saying it's an error is just wrong!

Note - I have checked the code, and it's clearly saying that the [launch] message is an info status, so I am confused. 

NOTE - Low Priority. It's cosmetic not functional.

**Comment by SergioBenitez** [comment]
This is already resolved in master. See #563.
