### ISSUE TITLE
Add abillity to assign a custom config name

### ISSUE THREAD

**Issue by avrong** [SergioBenitez/Rocket#677]
> **Feature Request:** Add abillity to assign a custom config name at launch.

## Why?
I thinks because there are a lot of people who cares more then 3 config environments, some people can't fit their bunch of configs in 3 use cases provided by default in Rocket. Also, some projects have multiple binaries and all of them used to run only from one config.

## Use
- Use of multiple binaries in one project
- Need to define a lot of configs for different environments

## Implementation
In my mind I have two possible ways to do it.

The **first one** is based on custom section names in `Rocket.toml` config file. It requires to make optional `production`, `staging` and `developement` sections in config and give user abillity to write their optional sections and choose one of their in `rocket::iginite()` (e.g. using `env(name)` function) call or in `ROCKET_ENV` environment variable.
```
[azure]
address = "0.0.0.0"
port = 5000
...

[heroku]
address = "localhost"
port = 8000
...
```

```rust
rocket::ignite().env("heroku")...
```

The **second way** is based on new function `config_from(filename)`  called with `rocket::ignite()` or `rocket::custom`. All the same as now, but with custom config filename.

```rust
rocket::ignite().config_from("ApiConfig.toml")...
```

## Why do not implement it by myself in my project only
Because in Rocket we have nice one module for doing this stuff. I don't want to write my custom method for doing the same with only one change.

*P.S. I'm not so experienced in Rust to really understand which method (maybe yours one) is better. So I leave the discussion and decision of this question to you.*

**Comment by SergioBenitez** [comment]
I'm generally _for_ this change but am not ready to commit to anything just yet. Nevertheless, let's track this and other config changes in #145.
