### ISSUE TITLE
Stop using the `quote_` macros

### ISSUE THREAD

**Issue by SergioBenitez** [SergioBenitez/Rocket#678]
An issue/PR removing the `quote_` macros from `rustc` is underway (https://github.com/rust-lang/rust/pull/51285, https://github.com/rust-lang/rust/issues/46849). Rocket uses quite a few of these macros in a fairly fundamental way, so this is a fairly large breaking change for Rocket. A workaround is needed.

**Comment by eddyb** [comment]
Ideally a full transition to `proc_macro` + `syn` + `quote` should be done, to avoid further trouble when the existing plugin API will be removed.

**Comment by SergioBenitez** [comment]
That's the hope, @eddyb, but it's a serious undertaking that I was hoping to postpone for another month.

**Comment by SergioBenitez** [comment]
Let's track this in #693.
