### ISSUE TITLE
Can we protect routes for API endpoints and do rate limiting in Rocket?

### ISSUE THREAD

**Issue by raintears** [SergioBenitez/Rocket#679]
Hi, I'm using the latest version of Rocket and it's pretty fun to work with. I'm using it to write a restful API service. I followed the guide and added a few routes to test it out just to familiarize myself. I've a few questions because I'm stuck at finding tutorials that walk us through how to protect or secure API endpoints or routes with Rocket.

I'm curious if we can do that in Rocket? Like how do we use a "API key" to authorize a user can access my api routes and how can I implement rate limiting in Rocket?

Last but not least, I was trying to follow the ssl example. I was wondering if it's possible to include the cert and pem in environment variables instead of writing the path in the file itself? will that be safer?

**Comment by mettke** [comment]
You can find information about SSL with environment variables in the official docs. There is no security difference, 'cause there is no real difference between having information stored in a file or stored in the environment. Both require direct access to the server.
https://rocket.rs/guide/configuration/#configuring-tls

About securing your endpoint, well, I won't walk you through that as it would take too much time. There is no as is default implementation but you can create one yourself by using [State](https://rocket.rs/guide/state/) with a Database and a [Guard](https://rocket.rs/guide/requests/#request-guards) for your routes. An incoming request is validated via Guard which does a database request and either lets the request through or not. Rate Limit is pretty much the same, storing information about how many requests were done already.

**Comment by raintears** [comment]
Nice, then I'll try the tls example. About the rate limit, do you mean I can use State like a cache to store the request count? How can I store multiple states for different API key? That's possible?

Do you mean using Guard to query database if the API key is valid?

**Comment by SergioBenitez** [comment]
Looks like we're good here! Note that we've also recently introduced request-local state (#654, #655, #724), which you might find useful when thinking about implementing this kind of functionality.
