### ISSUE TITLE
How to specify host/port dynamically?

### ISSUE THREAD

**Issue by GildedHonour** [SergioBenitez/Rocket#688]
How can I specify port and host without using the standard rocket config file? for instance, I'm using my own config - yaml or json - or I want to specify port/host from a user input.

**Comment by jebrosen** [comment]
The documentation example for [`Rocket::custom`](https://api.rocket.rs/rocket/struct.Rocket.html#method.custom) appears to cover this use case.

**Comment by GildedHonour** [comment]
That's not working:

```

    let port = get_port_from_my_config();
    println!("port: {:?}", port); // port: 4000

    let cfg = rocket::config::Config::build(rocket::config::Environment::Development)
        .address(_local_ip)
        .port(port)
        .unwrap();

    rocket::ignite()
        .mount("/", routes![pages_index])
        .attach(rocket_contrib::Template::fairing())
        .manage(cfg)
        .launch();
```

Ooutput:
```

🔧  Configured for development.
    => address: localhost
    => port: 8000
    => log: normal
    => workers: 8
    => secret key: generated
    => limits: forms = 32KiB
    => tls: disabled
🛰  Mounting '/':
    => GET /


```

**Comment by jebrosen** [comment]
`custom` is used as an alternative to `ignite`, like so:

```rust
    let cfg = ...;

    rocket::custom(cfg, true)
        .mount("/", routes![pages_index])
        .attach(rocket_contrib::Template::fairing())
        .launch();
```

**Comment by GildedHonour** [comment]
thx

**Comment by mikeumus** [comment]
@jebrosen appreciate the great package but your code example needs to be in the docs. 

We only see a config getting declared but no idea where to plug it in. 

Also, please consider turning on 💖GitHub Sponsorship so we can easily give back. Thank you 🙇🏻‍♂️

**Comment by jebrosen** [comment]
> @jebrosen appreciate the great package but your code example needs to be in the docs.
> We only see a config getting declared but no idea where to plug it in.

That example was recently refactored in the `master` branch (although not by me) and it now includes some surrounding context: (<https://api.rocket.rs/master/rocket/struct.Rocket.html#method.custom>)!
 
> Also, please consider turning on :sparkling_heart: GitHub Sponsorship so we can easily give back. Thank you 🙇🏻‍♂️

I don't think I have the personal bandwidth to set that up now, but I will keep it in mind for the future!

**Comment by baijifeilong** [comment]
```rust
#[rocket::main]
#[allow(unused_must_use)]
async fn main() {
    let config = Config {
        address: Ipv4Addr::new(0, 0, 0, 0).into(),
        ..Config::debug_default()
    };
    rocket::custom(&config).mount("/", routes![parse_metaplex]).launch().await;
}
```
