### ISSUE TITLE
Add JS/CSS minification?

### ISSUE THREAD

**Issue by GuillaumeGomez** [SergioBenitez/Rocket#692]
Hi,

I wrote [minifier-rs](https://github.com/guillaumeGomez/minifier-rs), a small crate to minify JS and CSS. It's currently being used in rustdoc and I'd like, if possible, to get more potential failure/issues feedbacks in order to improve it. Would it be possible to add it into your crate behind a feature so I could get some please?

Thanks in advance!

**Comment by SergioBenitez** [comment]
Duplicate of https://github.com/SergioBenitez/Rocket/issues/684.
