### ISSUE TITLE
Having multiple handler for same error?

### ISSUE THREAD

**Issue by raintears** [SergioBenitez/Rocket#694]
I have included api and web app in my rocket project. My api is returning json response for error like 404, 403 etc. But my web app needs to return a 404 static page. Is it possible to have multiple handler for the same error in Rocket?

**Comment by SergioBenitez** [comment]
I'm not sure I follow what you're trying to do. Can you be more specific, perhaps by posting some minimal example code?

**Comment by raintears** [comment]
Yeap, here's what I was trying to do:

```
#[error(404)]
fn api_not_found() -> JSON<String> {
...
}

#[error(404)]
fn page_not_found() -> Template {
...
}
```

**Comment by SergioBenitez** [comment]
No; how would you expect that particular thing to work? Perhaps you're looking for the same thing that was requested in https://github.com/SergioBenitez/Rocket/issues/453?

**Comment by SergioBenitez** [comment]
You can trivially check the path in an error catcher:

```rust
#[error(404)]
fn not_found(request: &Request) -> Result<Json<T>, Template> {
    if request.uri().path().starts_with("/api") {
        Json(...)
    } else {
        Template::render(..)
    }
}
```

As for souping up error catchers, there's work underway. Let's track expanding error catcher matching in #453.

**Comment by raintears** [comment]
woah that's a lovely hack around @SergioBenitez Hope there will be Either so we don't have to treat it as Err.
