### ISSUE TITLE
What's 'a and 'r in impl<'a, 'r> FromRequest<'a, 'r>?

### ISSUE THREAD

**Issue by raintears** [SergioBenitez/Rocket#695]
It's not mention in the guide. I still don't get what does 'a and 'r means and how can i use them?

**Comment by ZephOne** [comment]
These are lifetimes, you should read the part concerning lifetime in [The Rust programming language](https://doc.rust-lang.org/book/second-edition/ch10-03-lifetime-syntax.html)
