### ISSUE TITLE
Unable to write integration tests which rely on database (diesel)

### ISSUE THREAD

**Issue by Aeradriel** [SergioBenitez/Rocket#697]
Hi,

I'm actually building an app with Rocket & Diesel. I faced an issue with concurrency making my DB dependant tests failing. To solve this, I ran my test with a connection in a transaction (see the example below).

```rust
pub fn connection_without_transaction() -> PgConnection {
    dotenv().ok();

    let connection_url = std::env::var("TEST_DATABASE_URL").expect("No database url set");

    PgConnection::establish(&connection_url).unwrap()
}

pub fn connection() -> PgConnection {
    let conn = connection_without_transaction();

    // Transaction will be rollbacked so db is not corrupted for other tests
    conn.begin_test_transaction().unwrap();
    conn
}

#[test]
fn saves_the_record() {
    let conn = connection();
    let mut record = create_record(&conn);
    let new_name = String::from("newname");
    let new_token = String::from("newtoken");

    record.name = new_name.clone();
    record.save(&conn).expect("Could not save record");
    record = Record::find(&record.id, &conn).expect("Could not find record");
    assert_eq!(record.name, new_name);
}
```

The problem when it comes to test rocket endpoints is that even if I can customize the request with the `CustomizeConnection` (see impl. below) trait from r2d2 to start a transaction when the connection is made, it gets rollback before I can make my assertions. Moreover, another problem here is that if I want to create some record, for example, before I request my Rocket endpoint, I cannot do it in a transaction or it won't be accessible from Rocket and I cannot do it without or it will "corrupt" the database for other tests running at the same time.

```rust
struct TestConnectionCustomizer;

impl<C, E> CustomizeConnection<C, E> for TestConnectionCustomizer
where
    C: diesel::connection::Connection,
    E: std::error::Error + Sync + Send,
{
    fn on_acquire(&self, conn: &mut C) -> Result<(), E> {
        match conn.begin_test_transaction() {
            Ok(_) => Ok(()),
            Err(_) => Ok(()), // TODO: Fix this with real error
        }
    }
}

fn init_pool(database_url: &str) -> PgPool {
    let manager = ConnectionManager::<PgConnection>::new(database_url);
    let customizer = TestConnectionCustomizer {};

    Pool::builder()
        .connection_customizer(Box::new(customizer))
        .build(manager)
        .expect("could not initiate db pool")
}
```

I'm not sure if this is actually possible with Rocket or if there is a workaround other than running tests with `RUST_TESTS_THREADS=1`. If there is not, I think that would be a really great addition to Rocket to allow real integration testings for apps relying on a database. Indeed, testing directly endpoint functions (which wear `#[get("/")]`) does not allow to detect unmounted routes or data validation for example.

**Comment by ELD** [comment]
So, if I understand what you're trying to do with your Rocket integration tests, it is:
1. Create a TestConnection wrapper that begins a test transaction on every request
1. Run an integration test using the testing Rocket instance
1. Attempt to assert on the changes made in the Rocket handler for that given test
1. The test fails because the test transaction was already rolled back by the time the request completes.

(I've obviously skipped a few smaller steps, but this seems to be the gist)

If I understand your use-case correctly, the underlying issue is that the connection you're retrieving from the pool is only valid for the life of the request handler which finishes executing as soon as you have a response object you can inspect. Because of this, the reference to the database connection goes out of scope and the destructor cleans up the transaction.

Based on this, I don't believe Rocket currently supports this ergonomically out of the box. However, with the work in #571, we might be able to get to that someday. I do agree that this would be an excellent feature for Rocket to have in the future. I'll ask @SergioBenitez to add the "request" label to this issue so we can continue to track this request.

**Comment by Aeradriel** [comment]
That's definitly what I'm trying to do.

Are you aware of some best practices to test that kind of scenario ?
A temporary "solution" could be to hit the endpoints with the testing Rocket instance to validate any "request-related" data (like not found if body not formatted the proper way & so) and directly call the decorated function for database related tests passing a custom connection.

Good luck for you work on pooling, I hope we can see that on soon !

**Comment by ELD** [comment]
Unfortunately, I'm at a bit of a loss off the top of my head for doing integration tests outside of the way you highlighted. I'd caution against doing that since it's very heavyweight.

I'll keep thinking about it and let you know if I come up with anything else.

**Comment by Aeradriel** [comment]
Finally what I did is run rocket integration tests on a separate database and use a global mutex to make tests run synchronously so there is no conflict. That may not be an optimal solution but still it allows other tests to run correctly and prevent bugs in rocket ones.

```rust
use std::sync::Mutex;
use std::sync::MutexGuard;

lazy_static! {
    static ref G_MUTEX: Mutex<()> = Mutex::new(());
}

pub fn init_rocket() -> (Client, MutexGuard<'static, ()>) {
    // Allows tests to continue if a test panic
    let guard = match G_MUTEX.lock() {
        Ok(guard) => guard,
        Err(poisoned) => poisoned.into_inner(),
    };

    [...]

    let pool = init_pool(&std::env::var("ROCKET_TEST_DATABASE_URL").expect("No database url set"));
    let rocket_instance = rocket::ignite().manage(pool.clone()).mount(
        "/",
        routes![
            [...]
        ],
    );

    (
        Client::new(rocket_instance).expect("valid rocket instance"),
        guard,
    )
}
```

**Comment by SergioBenitez** [comment]
@Aeradriel This is what the [`todo` example](https://github.com/SergioBenitez/Rocket/blob/master/examples/todo/src/tests.rs) does, for instance. It's not optimal, and I'm hoping extensions to #167 will make this trivial. Let's keep tracking that there.
