### ISSUE TITLE
Clippy issues on codegen & FromForm derive

### ISSUE THREAD

**Issue by Aeradriel** [SergioBenitez/Rocket#698]
- Rocket version: 0.3.14
- OS: MacOS 10.13.2

Running `cargo clippy` with `#[derive(FromForm)]` raises following warning: 

> warning: this looks like an `else if` but the `else` is missing====> ] 155/156: jackdaw
>   --> src/models/license.rs:13:10
>    |
> 13 | #[derive(FromForm, Serialize, Deserialize)]
>    |          ^^^^^^^^
>    |
>    = note: #[warn(suspicious_else_formatting)] on by default
>    = note: to remove this lint, add the missing `else` or add a new line before the second `if`
>    = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#suspicious_else_formatting
> 

Running `cargo clippy` with `#[get("/<id>")]` raises following warning: 

> warning: printing a literal with an empty format string
>   --> src/controllers/licenses.rs:15:1
>    |
> 15 | #[get("/<id>")]
>    | ^^^^^^^^^^^^^^^
>    |
>    = note: #[warn(print_literal)] on by default
>    = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#print_literal
> 
> warning: printing a literal with an empty format string
>   |
>   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#print_literal

**Comment by jebrosen** [comment]
Apparently similar lint issues have come and gone a few times (#252, #294).

For now, it's probably easiest to disable these lints. Unfortunately, it will disable the lints in your own code as well:

`#![cfg_attr(feature = "cargo-clippy", allow(needless_pass_by_value, suspicious_else_formatting, print_literal))]`

**Comment by Aeradriel** [comment]
I saw those two. I was hoping this could be fixed, especially the suspicious else formatting that does look like a problem in the code gen (I might be wrong though). I don’t wanna disable all thoses lints or that might end up the same thing as not to use clippy at all.

**Comment by DJMcNab** [comment]
I suspect the first issue is from https://github.com/SergioBenitez/Rocket/blob/master/core/codegen/src/decorators/derive_form.rs#L293-L297. It might be fixed by adding a line at the end of the 
`quote tokens!` macro! I can't check at the moment.

**Comment by SergioBenitez** [comment]
The `FromForm` derive has been completely rewritten. This no longer pops up.
