### ISSUE TITLE
Getting request body in from_request?

### ISSUE THREAD

**Issue by raintears** [SergioBenitez/Rocket#700]
I notice there are two guards: request guard and data guard. Request guard implements ```from_request``` and data guard implements ```from_data```. But is there a way to get the request body in request guard?

I'm trying to do hmac calculation in the guard methods but I can't find a way to get the request body content. I can only get the headers.

This is what I was doing:
```
pub struct Hmac_str(pub String);

impl<'r, 'a> FromRequest<'r, 'a> for Hmac_str {
    type Error = ();

    fn from_request(request: &'r Request<'a>) -> request::Outcome<Hmac_str, ()> {
        ...
        // get headers and body to calculate hmac string
    }
}
```

I was also reading this guide https://api.rocket.rs/rocket/request/trait.FromRequest.html but I find that sending apikey can be prone to man-in-middle attack so was trying out hmac which I need to access the request content.

**Comment by SergioBenitez** [comment]
> But is there a way to get the request body in request guard?

There is not. The only way to retrieve both the request body and request data is via a request fairing.

> sending apikey can be prone to man-in-middle attack

This sounds wrong. What are you referring to? You shouldn't send the key in the clear, of course, just like you shouldn't send passwords in the clear.

> so was trying out hmac

The HMAC of what?

**Comment by raintears** [comment]
How do i use request fairing to get both body and data of request?

I'm trying to ```HMAC ( key, content, timestamp )```

So I need to get the key, which will be in request header. I can get that with ```from_request```. I need the content, which is in ```from_data```. I suppose timestamp will be in headers as well.

This is my handler:
```
#[post("/school", format = "application/json", data = "<school>")]
pub fn new_school() ...
```

My ```from_request```:
```
fn from_request(request: &'r Request<'a>) -> request::Outcome<Key, ()> {
        let keys = request.headers().get(HMAC).collect::<Vec<_>>();
        if keys.len() != 1 {
            return Outcome::Failure((Status::BadRequest, ()));
        }
...
```

**Comment by SergioBenitez** [comment]
> So I need to get the key, which will be in request header.

This is a very bad idea, and no more secure (and likely less secure) than passing an API key.

> I suppose timestamp will be in headers as well.

There is no timestamp associated with requests unless you do something to put one there.

> How do i use request fairing to get both body and data of request?

That's covered in [the guide](https://rocket.rs/guide/fairings/) and [the API docs](https://api.rocket.rs/rocket/fairing/trait.Fairing.html). Note that you can't get the entire request data, only a part of it.

In general, your approach sounds flawed, no more secure, and much more expensive than using something like an API key, OAuth, or similar. I'd suggest that you reconsider your approach.

I believe I've answered all of your Rocket-related questions, so I'm closing out this issue.

**Comment by the10thWiz** [comment]
There are a couple of ways to handle this, in a somewhat better way. You could wrap the body in a struct (e.g., `HashedPayload</* actual payload type */>`), which uses the (sadly, master branch only) transform API (https://api.rocket.rs/master/rocket/data/struct.Data#method.chain_inspect) to compute the hash of the payload, and compare it to any value in either the request (or else where). There is also an API coming in 0.6, which would allow (almost) any guard to reject a request, and send it to an error handler.

**Comment by luckydonald** [comment]
@the10thWiz awesome, in other words, it will be possible once 0.6 lands?
Is there a milestone board or something to see what's planned for 0.6, and/or it's progress?
