### ISSUE TITLE
Command for generating template projects

### ISSUE THREAD

**Issue by Qwertie-** [SergioBenitez/Rocket#701]
I think it would be very useful to have a command that lets you create a new rocket project with configuration files and folder structure premade.

for example something like `rocket new postgres` which would then create a new project with diesel installed and all the configuration for connections and pools set up.

A feature like this would make getting started with rocket much simpler.

**Comment by SergioBenitez** [comment]
I have, in fact, built such a tool. Here is the current interface:

```rust
❯ rocket --help
Rocket CLI 0.1.0
A command line interface for Rocket.

USAGE:
    rocket <SUBCOMMAND>

FLAGS:
    -h, --help
            Prints help information

    -V, --version
            Prints version information


SUBCOMMANDS:
    help
            Prints this message or the help of the given subcommand(s)

    new
            Generate a new Cargo project with Rocket dependencies.

            Without any flags, the generated Cargo project will use the latest version of Rocket's
            libraries as its dependencies. You can use the --git flag to instead use a version from a
            git repository, and --local to instead use a version from a local path.

❯ rocket new --help
rocket-new 0.1.0
Generate a new Cargo project with Rocket dependencies.

Without any flags, the generated Cargo project will use the latest version of Rocket's libraries as
its dependencies. You can use the --git flag to instead use a version from a git repository, and
--local to instead use a version from a local path.

USAGE:
    rocket new [OPTIONS] <name>

FLAGS:
    -h, --help
            Prints help information

    -V, --version
            Prints version information


OPTIONS:
    -l, --local <path>
            Use Rocket dependencies from a local path

    -g, --git <repo>
            Use Rocket dependencies from git [default: https://github.com/SergioBenitez/Rocket]


ARGS:
    <name>
            The name of the new Cargo project
```

It's designed to be extensible via templates pulled in from anywhere. Unfortunately, I don't consider the tool complete enough, nor necessary enough, to release. I do see the potential for such a tool, however.

**Comment by Keats** [comment]
I wrote a tool for that: https://github.com/Keats/kickstart

One of the potential improvements was to make it work as a library (https://github.com/Keats/kickstart/issues/5) so other CLI like `rocket` could use it without having to ask users to install another tool. Would that make sense/be something you're interested in?

**Comment by SergioBenitez** [comment]
I think this is fairly out of scope, at least for now. Perhaps if a `rocket` CLI tool could do more than create a Cargo project its utility would be obvious, but otherwise, I think the steps in the guide are fairly straightforward to follow.
