### ISSUE TITLE
Automatically remove last slash in routes path

### ISSUE THREAD

**Issue by raintears** [SergioBenitez/Rocket#702]
Was trying out the routes and looks like this matches both ```http://localhost/login``` and ```http://localhost/login/``` :
```
#[get("/login")]
pub fn login() -> Template {
...
}
```
I'm implementing this to redirect but was wondering if there's a better approach to this in Rocket?

```
#[get("/login/")]
pub fn loginredirect() -> Redirect {
...
}
```

**Comment by jebrosen** [comment]
Is there any particular reason that `login/` including the trailing slash is bad? There are both technical and cosmetic reasons to use one or the other in certain cases, and I'm curious what yours are.

**Comment by SergioBenitez** [comment]
Closing this out due to inactivity.
