### ISSUE TITLE
Question: How to set raw vector array of certs to TLS config instead of path

### ISSUE THREAD

**Issue by ameykshirsagar** [SergioBenitez/Rocket#704]
Version : 0.3.14
Operating System : Mac
Hi,
I am using this module to build an HTTPS server for a microservice and I want to set certificates and keys using a raw vector array instead of certs path as I require to keep the certificates and keys away from running container. As far as I have gone through the documentation the `set_tls` function takes only paths. So how can I set them using vector array??
Thanks in advance

**Comment by SergioBenitez** [comment]
Are you saying you have the raw bytes for the certificates available? If so, you're right that the current interface doesn't make configuring TLS this way possible. That being said, if you have the raw bytes, you could right them to files temporarily, pass Rocket the paths, and then delete them before the application begins (achievable with an `on_launch` fairing).

I wouldn't be opposed to extending the interface to allow all things that implement `io::Read` to be used to set up TLS.

**Comment by ameykshirsagar** [comment]
I digged in the source and it seems `hyper-sync-rustls` has the interface to set certs by path. I will try to change the interface

**Comment by SergioBenitez** [comment]
Let's fix this in #852.
