### ISSUE TITLE
Feature request: one-line error responses

### ISSUE THREAD

**Issue by kybishop** [SergioBenitez/Rocket#71]
There is a lot of boilerplate when responding with an error.

It would be great if there were a either a generic method for returning error responses, or structs similar to those in `rocket::response::status`.

**Comment by SergioBenitez** [comment]
Can you be more specific about what you're doing currently and what you find cumbersome about it? Also, are you aware of the [Failure](https://api.rocket.rs/rocket/response/struct.Failure.html) type?

**Comment by kybishop** [comment]
Hey Sergio,

I'm currently using the `Failure` type to reference a method I've made for each error, though think things would clean up nicely if one could instead having something like:

```rust
fn hello_world() -> Result<JSON<&'static str, ResponseError> {
    my_method_that_might_throw().map_err(|err| {
        match err {
            MyErrorFoo => ResponseError(422, "some error message")
            MyErrorBar => ResponseError(500, "some other error message")
            MyErrorBaz => ResponseError(422, "another error message")
        }
    })
}
```

As it stands, each response needs its own method. Error responses seem like a common case where we don't need to repeat ourselves.

Adding off the example: I'm not sure how to implement multiple error responses of the same status code but with differing error messages.

**Comment by SergioBenitez** [comment]
I'm having a bit of trouble understanding where you're having a hard time. I believe that when you say:

> I'm currently using the `Failure` type to reference a method I've made for each error...

You're referring to having an error catcher for each error status you want to return. Am I getting that right?

First, you only need to implement an error catcher if you want a custom error message or you want to use nonstandard error statuses. Rocket implements a default error catcher for every standard http error status code.

Second, if you want custom error messages for a variety of failure modes, the best thing to do is to create your own `Responder` type that sets the appropriate status and body. In your example, if you implement `Responder` for the error type of `my_method_that_might_throw`, you could simply add a `?` to the invocation or directly return the return value. You'd place the `match` logic in the `Responder` implementation. This enriches the error type _and_ gives you a zero line (in handlers, that is) solution.

Error catchers are designed to catch errors that slip through or have a common response global to the application. Custom responses should have a custom `Responder`. You might imagine Rocket making returning custom error responses a bit easier via wrappers, similar to those in `status`. I think that would be a good idea and in-line with the existing types. It's something I've thought about implementing but haven't had the need for, personally, as implementing a custom `Responder` is easy and usually results in cleaner, easier to read and write, and more obvious code.

**Comment by kybishop** [comment]
implementing `Responder` for the error type is a great idea! Still new to Rust and learning the common idioms.

Closing this out in favor of your suggestion.

@SergioBenitez Would love to contribute a PR to https://rocket.rs/guide/responses/#errors with a small example to show fellow beginners a practical example of your suggestion. Any chance there is a public repo for the site?

**Comment by SergioBenitez** [comment]
There isn't a public repository yet, but I'll be opening it up in the next day or so.

**Comment by SergioBenitez** [comment]
Oh, not sure why I didn't think about this earlier, but you can do exactly what you wrote using `status::Custom`, actually. The `Responder` solution is still preferred, of course.

**Comment by fluffy-samurai** [comment]
@SergioBenitez Is this still the preferred method for JSON error responses?
