### ISSUE TITLE
Where to publish the static files

### ISSUE THREAD

**Issue by hasanOryx** [SergioBenitez/Rocket#715]
I copied the `static file` example, and it run smoothly with me.
But after running I `cargo build --release` and getting the exucted file, I copied the `static` folder with the executed file, but upon running it, I got `500: Internal Server Error`

```
#![feature(plugin, decl_macro)]
#![plugin(rocket_codegen)]

extern crate rocket;

use std::io;
use std::path::{Path, PathBuf};

use rocket::response::NamedFile;

#[get("/")]
fn index() -> io::Result<NamedFile> {
    NamedFile::open("static/index.html")
}

#[get("/<file..>")]
fn files(file: PathBuf) -> Option<NamedFile> {
    NamedFile::open(Path::new("static/").join(file)).ok()
}

fn rocket() -> rocket::Rocket {
    rocket::ignite().mount("/", routes![index, files])
}

fn main() {
    rocket().launch();
}
```

**Comment by jebrosen** [comment]
Without more details about how you are running the application or the details of the error, my best guess is that the working directory is not correct. The path `"static/"` is relative to the working directory, so the application should be run in whatever location contains the "static" directory, regardless of where the executable is.

**Comment by hasanOryx** [comment]
Here you can see the screens I've, I tried putting the `index.html` in 2 locations:
1/ beside the executable file
2/ in a folder beside the executable file`static/index.html` 

the exact code I used is:

```
extern crate rocket;

use std::io;
use std::path::{Path, PathBuf};

use rocket::response::NamedFile;

#[get("/")]
fn index() -> io::Result<NamedFile> {
    NamedFile::open("static/index.html")
}

#[get("/<file..>")]
fn files(file: PathBuf) -> Option<NamedFile> {
    NamedFile::open(Path::new("static/").join(file)).ok()
}

fn rocket() -> rocket::Rocket {
    rocket::ignite().mount("/", routes![index, files])
}

fn main() {
    rocket().launch();
}
```

![static_error](https://user-images.githubusercontent.com/26045838/42991725-2723e64e-8c0f-11e8-9ba3-f2a441ded6b0.png)

**Comment by mettke** [comment]
@hasanOryx As @jebrosen said, it is not important that the static folder is next to the executable. It is important that you ARE in the folder which contains the static folder. 

Your terminal is currently in your homefolder and thus the program cannot find the static folder. You must `cd` into the `release` folder and run the application

**Comment by hasanOryx** [comment]
@metka I got confused, I need to distribute the way it appears in the screen shot given, do what shall I change in my code to get it done :)

**Comment by mettke** [comment]
@hasanOryx Nothing :D - just use `cd /Users/hasan/Documents/PycharmProjects/hello-rocket/target/release` before executing

**Comment by hasanOryx** [comment]
Thanks @mettke 

Now my code working the opposite way, i.e. work with the exulted file, but not with running `cargo run`

The code `let path = env::current_dir()?;` output is not same every where!!
When I run `cargo run` the path I've is: `/Users/hasan/Documents/PycharmProjects/hello-rocket`, but when I run the executed file, the path I've is: `/Users/hasan` only!!

SO, my code ended as below:

```
use std::env;

fn index() -> io::Result<NamedFile> {
    let path = env::current_dir()?;
    
    // If run using `cargo run` use:
    // let static_files = format!("{}/static/index.html", path.display());
    //   
    // If run from executed file use:
    let static_files = format!("{}/Documents/PycharmProjects/hello-rocket/target/release/static/index.html", path.display());
    println!("The current directory is {} and index file path is: {}",
             path.display(),
             static_files
    );
    
     NamedFile::open(staatic_files) //    // NamedFile::open("static/index.html")
}
```

Any idea how to fix it?

**Comment by mettke** [comment]
@hasanOryx Sry that was the wrong function. You may want to try https://doc.rust-lang.org/std/env/fn.current_exe.html
