### ISSUE TITLE
xss with contrib tera module

### ISSUE THREAD

**Issue by roller** [SergioBenitez/Rocket#73]
It looks like the contrib/tera module (as demonstrated with the todo example) is subject to script injection.  

For example add a Todo with: <script>alert(1); </script>

It appears that tera enables html autoescaping for [.html extension files](https://github.com/Keats/tera/search?utf8=%E2%9C%93&q=autoescape_extensions), but this is subverted by putting the tera template in a .tera file.

**Comment by SergioBenitez** [comment]
Fixed in https://github.com/SergioBenitez/Rocket/commit/8deac6dba939e29ebe680b569b8d7a97f9deb90e.
