### ISSUE TITLE
Returning <Status, Status> for routes

### ISSUE THREAD

**Issue by WillSquire** [SergioBenitez/Rocket#738]
Think this is more of a feature request rather than a bug. Whilst I can give a return type of `Result<Json<Value>, Status>` on routes, I can't seem to do `Result<Status, Status>`. 

The reason this would be handy is because I'd just like to say '200 (OK)' on REST endpoints rather than retransmitting the data received back (as the data isn't altered on the backend). Returning `Option` wouldn't help here because I might want to return `409 (Conflict)` if a resource already exists when doing create.

**Comment by WillSquire** [comment]
Thanks @jebrosen 

You were right about `Status `, it didn't have an effect. I used `Result<NoContent, NotFound<String>>` as you suggested and it worked great. I couldn't find 201 (Created) and 409 (Conflict) for the 'C' in 'CRUD' or 401 (Unauthorized) for failed authentication though? Are only a few implemented currently?

**Comment by jebrosen** [comment]
`Created` exists as well. For other status codes, `rocket::response::status::Custom` should suffice. In the near future, `#[derive(Responder)]` will make this even easier.
