### ISSUE TITLE
How to make a GraphQL api using Rocket?

### ISSUE THREAD

**Issue by jens1o** [SergioBenitez/Rocket#754]
Hi,

I was wondering whether there are some projects to use Rocket as an endpoint for hosting an GraphQL application. I searched for crates and found only this: https://github.com/countcain/graphql-rust - why does nothing.

Perhaps you add this as an feature request. I think it would be possible to implement this using Fairings and FromForm, but I feel like my knowledge is too exhausted to implement this.

I wonder whether you guys can help me?

**Comment by ELD** [comment]
There's another library out there called Juniper for GraphQL: https://github.com/graphql-rust/juniper

It has an example of using it with Rocket. I haven't personally used it, though, so your mileage may vary.

**Comment by SergioBenitez** [comment]
Indeed, I believe the defacto answer is `juniper`.
