### ISSUE TITLE
NamedFile cannot infer Content-Type of favicon.ico

### ISSUE THREAD

**Issue by SuperHacker-liuan** [SergioBenitez/Rocket#766]
# Basic Info

version: 0.3.16

OS: CentOS Linux release 7.5.1804 (Core) 

# Description

When access favicon.ico from browser (UA: Firefox 63.0b2), I cannot see the Content-Type header from response.

The Content-Type of '*.ico' should be image/x-icon.

If lack of Content-Type, Cache Control will be failed on some proxy.

# Use case

http://any.site.have.favicon.and.use.rocket/favicon.ico

And check the response header. Whether there exists `Content-Type: image/x-icon` line.

# Recommendation

Change core/http/src/known_media_types.rs, and add `"ico" => Icon,` to known_extensions & add `Icon (is_icon): "Icon", "image", "x-icon",` to known_media_types.

**Comment by SergioBenitez** [comment]
I'd happily accept a PR adding `.ico` as a known extension.

**Comment by SuperHacker-liuan** [comment]
@ErikPartridge Thanks you. Your PR fixed this issue as I imagine.

**Comment by SergioBenitez** [comment]
The PR has been merged!
