### ISSUE TITLE
"Static Files" example includes apparently insecure PathBuf usage

### ISSUE THREAD

**Issue by cathalgarvey** [SergioBenitez/Rocket#767]
Hi folks, I hope I'm mistaken, but it looks like [this line][suspect] might allow someone to access arbitrary files by including `".."` path components. If so, it shouldn't be used in the example code as it will end up being used by someone in production.

[suspect]: https://github.com/SergioBenitez/Rocket/blob/592316f099bd688811664cdf469f19a87c8be788/examples/static_files/src/main.rs#L21

**Comment by SergioBenitez** [comment]
The code is totally secure, so I _hope_ folks _are_ doing that in production. This is because the `PathBuf` implementation of `FromSegments` does the appropriate [security checks](https://api.rocket.rs/rocket/request/trait.FromSegments.html#provided-implementations).

**Comment by cathalgarvey** [comment]
If I understand correctly, are you saying that paths are already "sanitised" by the time the function body executes? e.g., if I try to enter "foo.bar/static/../../../etc/passwd" as my URL, then the function will receive "/etc/passwd", not "/../../../etc/passwd"?

If so, that's great - I didn't see that mentioned but it's a nice feature to have.

September 6, 2018 9:49 PM, "Sergio Benitez" <notifications@github.com (mailto:notifications@github.com?to=%22Sergio%20Benitez%22%20<notifications@github.com>)> wrote:
	Closed #767 (https://github.com/SergioBenitez/Rocket/issues/767).

**Comment by SergioBenitez** [comment]
That's correct. It's documented in the documentation for `PathBuf` I linked you to.
