### ISSUE TITLE
Dependency on old version of cookie causes build failure

### ISSUE THREAD

**Issue by FireFaced** [SergioBenitez/Rocket#769]
Rocket Version: 0.3.16
OS: Windows 10 Enterprise 1803

Rocket seems to depend on cookie v0.9.2, which depends on ring v0.11.0.
Both of those are old versions, and in rust 1.30.0-nightly fc81e3624 2018-09-07, ring does not compile. This seems to be fixed in the latest version of cookie. I have not looked into any possible API changes, however.

**Comment by jebrosen** [comment]
See https://github.com/SergioBenitez/Rocket/issues/687#issuecomment-402843320. ring *cannot* be bumped to another major version in Rocket's dependency graph until v0.4, but the timeline has definitely slipped on that release.
