### ISSUE TITLE
How to get the request time when the server received the request?

### ISSUE THREAD

**Issue by jens1o** [SergioBenitez/Rocket#777]
I'm using `v0.3.16` and I already asked on IRC: https://mozilla.logbot.info/rocket/20180919#c15338502 but received no response.

It is really important to have the moment the request arrived at the webserver as close as possible, so `SystemTime::now()` in a fairing or something isn't an option.

**Comment by SergioBenitez** [comment]
If your needs are so sensitive that they can't tolerate the ~100 microseconds between Rocket receiving the request and a request fairing being invoked, perhaps you should reconsider using Rocket at all. What are you doing?

**Comment by jens1o** [comment]
Hi,

i want to implement a give-a-way like route. So it is pretty important that who comes first gets their stuff first. Additionally, some checksum is built from the timestamp, and the last character is what you get exactly. I thought like hyper knows about this, so perhaps there is any getter (I didn't found) to get the raw request and then get the timestamp.

**Comment by SergioBenitez** [comment]
What you're trying to implement is impossible to do in a "fair" way. Network latency variance is easily 10s if not 100s of milliseconds, dwarfing the microseconds lost by implementing this as a fairing. You won't gain anything by having any special support for time stamping.
