### ISSUE TITLE
can i use front-end like angular or elm with rocket

### ISSUE THREAD

**Issue by adals** [SergioBenitez/Rocket#78]
hello
can i use front-end like angular or elm with rocket?if yes how?

thanks

**Comment by mgattozzi** [comment]
Yes you can. I got my site working with React and rocket. You just need to have a route to the assets for the site and then the corresponding html files that you might need, where the route corresponds to the either compiled version of Elm or in angular's case all of the controllers and files needed.

**Comment by SergioBenitez** [comment]
Closing this out. Feel free to reopen if you feel this is unanswered.
