### ISSUE TITLE
is it just me, or is the hello_world example broken? error[E0432]: unresolved import `syntax::source_map`

### ISSUE THREAD

**Issue by Osndok** [SergioBenitez/Rocket#782]
Greetings,

New to rust **and** rocket, I was trying to run the instructions found here:
* https://rocket.rs/guide/quickstart/#running-examples

More literally:
```
git clone https://github.com/SergioBenitez/Rocket
cd Rocket
git checkout v0.3.17
cd examples/hello_world
cargo run
```

Using the most recent fedora-28 software:
* rust-1.29.0-1.fc28.x86_64
* cargo-1.29.0-1.fc28.x86_64

However, I run into this (seemingly deep) dependency issue (below) the solution for which escapes me and is surely beyond the scope of a hello-world example:
```
[...SNIP...]
   Compiling log v0.3.9
warning: Rocket was unable to check rustc compatibility.
warning: Build may fail due to incompatible rustc version.
warning: Rocket was unable to check rustc compatibility.
warning: Build may fail due to incompatible rustc version.
   Compiling mime v0.2.6
   Compiling crossbeam-epoch v0.3.1
   Compiling crossbeam-deque v0.2.0
error[E0432]: unresolved import `syntax::source_map`
  --> /home/robert/.cargo/registry/src/github.com-1ecc6299db9ec823/pear_codegen-0.0.20/src/lib.rs:19:13
   |
19 | use syntax::source_map::{Span, DUMMY_SP};
   |             ^^^^^^^^^^ Could not find `source_map` in `syntax`

error[E0554]: #![feature] may not be used on the stable release channel
 --> /home/robert/.cargo/registry/src/github.com-1ecc6299db9ec823/pear_codegen-0.0.20/src/lib.rs:1:1
  |
1 | #![feature(plugin_registrar, rustc_private, quote)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

Some errors occurred: E0432, E0554.
For more information about an error, try `rustc --explain E0432`.
The following warnings were emitted during compilation:

warning: Pear was unable to check rustc compatibility.
warning: Build may fail due to incompatible rustc version.

error: Could not compile `pear_codegen`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by jebrosen** [comment]
From the [Quickstart](https://rocket.rs/guide/quickstart/#quickstart):

> Before you can start writing a Rocket application, you'll need a nightly version of Rust installed.

Fedora's rust and cargo packages are from the stable rust releases, so they cam can't be used for Rocket. #19 tracks Rocket's status with regards to stable rust.

**Comment by thomasnaudin** [comment]
I have the same problem with a nightly installed via rustup.
**pear_codegen** should be updated to 0.20 for Rocket 0.3.x, as 0.19 doesn't compile anymore with nightly.

**Comment by SergioBenitez** [comment]
@thomasnaudin You don't need to remove `Cargo.lock`. `cargo update` updates `Cargo.lock`.
