### ISSUE TITLE
ETA for rocket_contrib::static_file in stable?

### ISSUE THREAD

**Issue by WillemMali** [SergioBenitez/Rocket#788]
Hi, I'd like to know if `rocket_contrib::static_file` is scheduled to be released with the 4.0 release, and what time I could roughly expect the 4.0 release?

I'll see if there's any open issues matching my ability level, if you have an issue for new contributors in mind I'd like to give it a spin. I'm planning on using Rocket for a long-running project so I'd like to get to know it well.

**Comment by SergioBenitez** [comment]
ASAP. All of the code has been written for the 0.4 release. I am currently polishing documentation and the website. As soon as that's done, which shouldn't be too long now (a day, maybe?), I'll push a release candidate.
