### ISSUE TITLE
Configuring template engine in rocket_contrib

### ISSUE THREAD

**Issue by MikailBag** [SergioBenitez/Rocket#793]
Hello,
Is there any way to access template engine (handlebars::Handlebars in my case)?
I'd like to do
```rust
hb.set_strict_mode(true);
```
for example.

**Comment by jebrosen** [comment]
This functionality was added in #521. In Rocket 0.4 (or the master branch), you can do that like so:

```rust
    .attach(Template::custom(|engines| {
        engines.handlebars.set_strict_mode(true);
    }))
```
