### ISSUE TITLE
how to add json into a Response body? 

### ISSUE THREAD

**Issue by johnkarasev** [SergioBenitez/Rocket#796]
How do I put json in a response body?
`

    impl<'r> Responder<'r> for land {
        fn respond_to(self, _: &Request) -> response::Result<'r> {
            Response::build()
                .status(Status::Ok)
                .header(ContentType(<MediaType>::JSON))
                .raw_header("ratelimit-limit", "5000")
                .raw_header("ratelimit-remaining", "4999")
                .raw_header("ratelimit-reset", "1444931833")
                .sized_body(Cursor::new("{\"JSON...\"}"))
                .ok()
        }
    }
`

**Comment by jebrosen** [comment]
The guide has a [section on JSON](https://rocket.rs/guide/responses/#json), which should fit most use cases. The `Json` type in `rocket_contrib` does several of those things for you: it sets the `Content-Type` header, it serializes a struct to JSON via `serde`, and the status will be set to `Status::Ok` by default.

The rate-limiting would still have to be handled separately, however, similarly to how you have already implemented it. `#[derive(Responder)]` is coming in 0.4 and will make it even easier to add extra headers to responses built from your own `struct`s or `enum`s.

**Comment by mvolkmann** [comment]
@jebrosen You said the `Json` type in `rocket_contrib` sets the status to `Status::Ok` by default. Do you know how I can set it to a different status like 201 for CREATED?
