### ISSUE TITLE
I'm getting bad performance

### ISSUE THREAD

**Issue by alexhultman** [SergioBenitez/Rocket#799]
I'm testing Rocket master as of today with rustc 1.31.0 nightly and --release mode. I'm running the hello_world sample and I have a Rocket.toml file with workers set according to what I'm comparing with.

I read through the issue posted by Hyper devs: https://github.com/SergioBenitez/Rocket/issues/140 but as far as I can tell, Rocket performs better than Hyper. Both scale over many CPU cores, so a proper Rocket.toml configuration is essential for comparing purposes.

However, the result I get is really bad. Almost on Node.js levels, below Crystal, below Golang, below all "C servers".

I'm running Linux and I'm collecting IO benchmark results for a graph I'm plotting for demo purposes and wanted a Rust server in the graph.

Is Rocket supposed to be this slow?

**Comment by alexhultman** [comment]
> Rocket is about 36% faster than node.js/express.

Exactly my point, I get similar results. I guess that answers my question...

Thanks for clearing that up.

**Comment by girng** [comment]
> Thanks for clearing that up.

😂😂🤣
