### ISSUE TITLE
warning: hidden lifetime parameters in types are deprecated

### ISSUE THREAD

**Issue by mmrath** [SergioBenitez/Rocket#800]
## Bug Reports

  1. The version of Rocket you're using. Ensure it's the latest, if possible.
latest master as of today.

  2. The operating system (distribution and version) where the issue occurs.
MacOS

  3. A brief description of the bug that includes:
    * The nature of the bug. -> Warning issued by rustc

    * When the bug occurs. -> During compilation 

    * What you expected vs. what actually happened.
No warnings expected

  4. How you uncovered the bug. Short, reproducible tests are especially useful.
```
pub struct NewUser<'a> {
    pub email: &'a str,
}

#[post("/", format = "json", data = "<new_user>")]
fn create(new_user: Json<NewUser<'_>>, context: DB) -> Result<Json<User>, ApiError> {
   ...
}

warning: hidden lifetime parameters in types are deprecated

```

  5. Ideas, if any, about what Rocket is doing incorrectly.

If possible retain the anonymous lifetime

**Comment by jebrosen** [comment]
I'm not able to reproduce the warning with similar code. Can you post the full output of the warning, including which part of the source code line it pointing to? I'd also like to see the declarations of the other types used in that function -- DB, User, and ApiError. Finally, what exact version of `rustc` was this on, as printed by `rustc --version`?

**Comment by SergioBenitez** [comment]
@jebrosen Note that this is almost certainly because the project is being built with the 2018 edition. The issue is with the `strip_lifetimes` method. We should have it transform lifetimes to `'_` instead of removing them completely.

**Comment by jebrosen** [comment]
I did try with and without the 2018 edition and couldn't even get that warning to show, even for code that should have obviously triggered the lint without codegen being involved.
