### ISSUE TITLE
[Request] - Support Range header for streaming media to Safari

### ISSUE THREAD

**Issue by alexbowers** [SergioBenitez/Rocket#806]
1. Why you believe this feature is necessary.

Currently you can use Rocket to serve static assets such as Images, JS files, etc easily and it works, however if you try to serve video media (and potentially audio, haven't tested audio), it will only work in some browsers, because of browser support and leniency on the Range and RangeByte headers being respected and the correct information being returned.

Currently, it seems to send all bytes at the same time, even if the Range requested was only bytes 0-1 (which is the header request made by Safari to determine media type).

If you return all content back on that request, Chrome and other browsers are happy to play that content and ignore the mistake, however Safari refuses to play the content.

  2. A convincing use-case for this feature.

Using Rocket to serve static movie assets as part of your website is not currently possible, it currently requires either third-party (S3) or alternate server software for serving that asset, which isn't desirable if you want to lock the content behind auth walls etc in your application.

  3. Why this feature can't or shouldn't exist outside of Rocket.

It can exist outside of Rocket, however it makes using Rocket as a static server unusable since a common type of asset is not able to be sent to a popular browser (Mobile safari + Desktop).

**Comment by alexbowers** [comment]
Hi @SergioBenitez congrats on the 0.4.0 release.

Can i request that this feature be added as part of the 0.5.0 release?

**Comment by SergioBenitez** [comment]
Closing in favor of https://github.com/SergioBenitez/Rocket/issues/95.

**Comment by eras** [comment]
As I understand it, #95 is a about adding custom HTTP _response_ headers, but this issues is about supporting the `Range` header in the `FileServer` itself: the server needs to be able to seek in the file per the instructions (and then of course have that information available in the response headers, but having them two handled by separate mechanisms sounds a bit painful implementation-wise).

So can this issue be reopened or further clarified how #95 also solves this issue? It seems the problem still persists, e.g. MP4 files that don't have the `moov` box in the front cannot be played in a streaming fashion from a Rocket server, without (re)implementing the `FileServer` component with that feature. Similarly a download of a large file cannot be resumed.
