### ISSUE TITLE
Why FromDataSimple for String only worked in debug?

### ISSUE THREAD

**Issue by Matrix-Zhang** [SergioBenitez/Rocket#807]
as the topic

**Comment by jebrosen** [comment]
This is documented at https://api.rocket.rs/v0.4/rocket/data/trait.FromData.html#provided-implementations:

> WARNING: Do **not** use this implementation for anything *but* debugging. This is because the implementation reads the entire body into memory; since the user controls the size of the body, this is an obvious vector for a denial of service attack.

**Comment by SergioBenitez** [comment]
As a note, we _could_ consider setting a limit for things like `String` and `Vec<u8>`, and then we could expose these implementation safely, even in release builds. I suspect that this will cause more issues that it'll resolve, however.
