### ISSUE TITLE
[Feature] ContentType helpers

### ISSUE THREAD

**Issue by alexbowers** [SergioBenitez/Rocket#819]
## Feature Requests

Currently on ContentType there are several helpers already provided, `is_javascript`, `is_png` etc.

Having an `is_image` and `is_video` would be useful as a way to group together `png, gif,...` etc

https://api.rocket.rs/rocket/http/struct.ContentType.html

**Comment by alexbowers** [comment]
Seems solved by https://github.com/SergioBenitez/Rocket/pull/785

**Comment by alexbowers** [comment]
Yeah thats what im currently doing (`media_type.top`)

**Comment by SergioBenitez** [comment]
I agree with @jebrosen that this is possible today without too much of a difficulty.
