### ISSUE TITLE
Full uri/host/domain information for incoming requests.

### ISSUE THREAD

**Issue by peterreeves** [SergioBenitez/Rocket#823]
Hello!

I'm fairly new to web servers, so I'm not sure if what I'm asking is possible (or a security issue, etc), but it _feels_ like there should be no problem with this.

For my site I'm aiming to have an arbitrary number of subdomains all pointing to a single instance of Rocket, and I'd like to be able to know which subdomain the request came from (Spinning up one instance of Rocket per subdomain is undesirable).

Rocket seems to have some of the necessary parts already present:
https://api.rocket.rs/v0.4/rocket/http/uri/struct.Absolute.html
https://api.rocket.rs/v0.4/rocket/http/hyper/header/struct.Host.html
All that is needed is this information to be included in the incoming request.

At the moment though (as far as I can tell), there is no way to extract this information. The Route struct only contains an origin, not the full uri that I would like:
https://api.rocket.rs/v0.4/rocket/struct.Route.html
I can't see a way to do this with Fairings either.

Even if valid domain information couldn't be guaranteed for whatever reason (e.g. if the user types in the IP address manually rather than visiting the domain name), I believe an Option/Result would still prove useful for my use case. My guess is that Hyper already has this information, but Rocket is stripping it out to present a nicer interface or something?

Again my feeling is that this should be a trivial change, but have I overlooked anything?

**Comment by jebrosen** [comment]
It sounds from your description like you only actually need the `Host` header. A [request guard](https://rocket.rs/guide/requests/#request-guards) can be used to retrieve the header from the request:

```rust
pub struct HostHeader<'a>(pub &'a str);
impl<'a, 'r> FromRequest<'a, 'r> for HostHeader<'a> {
    type Error = ();

    fn from_request(request: &'a Request) -> rocket::request::Outcome<Self, Self::Error> {
        match request.headers().get_one("Host") {
            Some(h) => Outcome::Success(HostHeader(h)),
            None => Outcome::Forward(()),
        }
    }
}
```

And used as follows:
```rust
#[get("/")]
fn index(host: HostHeader) -> String {
    format!("Hello from {}", host.0)
}
```

**Comment by peterreeves** [comment]
Thanks for the quick response, that code does seem to work correctly! Thank you!
For some reason I was under the impression that this information wasn't present in the header.

**Comment by williamdes** [comment]
And the updated version for rocket `0.5.0-rc.2`

```rs
// Source: https://github.com/SergioBenitez/Rocket/issues/823#issuecomment-437646743
use rocket::request::FromRequest;
use rocket::request::Outcome;
use rocket::Request;

pub struct HostHeader<'a>(pub &'a str);

#[rocket::async_trait]
impl<'r> FromRequest<'r> for HostHeader<'r> {
    type Error = ();

    async fn from_request(req: &'r Request<'_>) -> Outcome<Self, Self::Error> {
        match req.headers().get_one("Host") {
            Some(h) => Outcome::Success(HostHeader(h)),
            None => Outcome::Forward(()),
        }
    }
}

```

**Comment by the10thWiz** [comment]
Rocket actually already has this type builtin, at least for 0.5 - https://api.rocket.rs/v0.5-rc/rocket/http/uri/struct.Host.html.
