### ISSUE TITLE
why warp faster than rocket?

### ISSUE THREAD

**Issue by adals** [SergioBenitez/Rocket#834]
hello

i made benchmark on my local machine 

for hello example inside warp folder

$ wrk -t12 -c400 -d30s http://127.0.0.1:3030
Running 30s test @ http://127.0.0.1:3030
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.41ms    3.88ms  39.54ms   68.27%
    Req/Sec     3.74k     1.52k    7.85k    53.50%
  1338948 requests in 30.02s, 113.65MB read
  Socket errors: connect 155, read 80, write 0, timeout 0
Requests/sec:  44598.70
Transfer/sec:      3.79MB

for hello_2018 exmple inside rocket example folder

$ wrk -t12 -c400 -d30s http://localhost:8000
Running 30s test @ http://localhost:8000
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.57ms  598.43us  31.76ms   85.62%
    Req/Sec     1.95k     0.98k    5.18k    42.62%
  175200 requests in 30.10s, 25.06MB read
  Socket errors: connect 157, read 204, write 0, timeout 0
Requests/sec:   5820.16
Transfer/sec:    852.56KB

just wondering 44,000 per second for warp and 5800 for rocket why?
does it improve in the future?

**Comment by SergioBenitez** [comment]
With so little detail, who knows? I'd expect the delta between Rocket and warp to be similar to the delta between Rocket and async. hyper, which is something like 2x or so. 10x is not an expected value.

You're almost certainly benchmarking different things here. I don't think this is the right place to get to the bottom of this, so I'm closing this issue out.
