### ISSUE TITLE
Macro parameterized State types cause arcane scoping errors

### ISSUE THREAD

**Issue by Korvox** [SergioBenitez/Rocket#839]
Happens on 0.4.0-rc.1 and master.

[See this example program.](https://gist.github.com/Korvox/521af158c49f1a14ab83155a5448a554)

Normally you can generate routes in macros just fine, but if you make the type parameter of a state guard a macro parameter compilation fails with really arcane error messages about scoping issues on internal types such as " cannot find `__req` in this scope"  and "cannot find `__data` in this scope "

To reproduce simply define any route in a macro and parameterize the type of a State guard:

```
macro_rules! foo {
    ($type:ty) => {
        #[get("/")]
        fn index(thing: rocket::State<$type>) -> String {
            format!("Thing: {:?}", *thing)
        }
    }
}
```
@jebrosen on IRC has a tentative patch and is way more knowledgeable on the internals of how Rocket expands its spanned quotes that cause this.

**Comment by jebrosen** [comment]
This patch fixes the test case and passes the existing test suite. At least these functions in the same file probably need similar modifications: `data_expr` (`__req`, `__data`), `query_exprs` (`__trail`, `__data`). Additionally, tests like @Korvox's should be added to guarantee that all kinds of guards work from macros in this way. Any other macros such as `#[catch]` should probably be checked, too.

```diff
diff --git a/core/codegen/src/attribute/route.rs b/core/codegen/src/attribute/route.rs
index 73bf86e..74213c7 100644
--- a/core/codegen/src/attribute/route.rs
+++ b/core/codegen/src/attribute/route.rs
@@ -300,12 +300,14 @@ fn query_exprs(route: &Route) -> Option<TokenStream2> {
 }
 
 fn request_guard_expr(ident: &syn::Ident, ty: &syn::Type) -> TokenStream2 {
+    let req = quote! { __req };
+    let data = quote! { __data };
     let span = ident.span().unstable().join(ty.span()).unwrap().into();
     quote_spanned! { span =>
         #[allow(non_snake_case, unreachable_patterns, unreachable_code)]
-        let #ident: #ty = match <#ty as ___r::FromRequest>::from_request(__req) {
+        let #ident: #ty = match <#ty as ___r::FromRequest>::from_request(#req) {
             ___Outcome::Success(__v) => __v,
-            ___Outcome::Forward(_) => return ___Outcome::Forward(__data),
+            ___Outcome::Forward(_) => return ___Outcome::Forward(#data),
             ___Outcome::Failure((__c, _)) => return ___Outcome::Failure(__c),
         };
     }
```

I don't necessarily like the code, but hopefully it illustrates the problem as I understand it: the spans of certain local variables aren't properly matched up once `quote_spanned` gets involved.

I wouldn't be able to work much on this myself for a while, but if anyone else is interested this should help get started.

**Comment by SergioBenitez** [comment]
Fix is incoming.
