### ISSUE TITLE
uri! with all missing optional query params shouldn't append ?

### ISSUE THREAD

**Issue by jkcclemens** [SergioBenitez/Rocket#840]
```rust
#[get("/example?<name>")]
fn example(name: Option<&str>) -> String {
  format!("Hi, {}!", name.unwrap_or("nameless person"));
}

// later
uri!(example: None) // this results in `/example?` instead of `/example`
```

**Comment by SergioBenitez** [comment]
Just a small note: A `?`-less URI would be ideal, but there's nothing incorrect about what Rocket currently does.

**Comment by igalic** [comment]
> there's nothing incorrect about what Rocket currently does.

yesno…
a `?` at the end of a URL can cause intermediate (proxy) caches to not consult their cache, thinking it's dynamic

**Comment by SergioBenitez** [comment]
@igalic We don't do this anymore. This is an old issue.
