### ISSUE TITLE
Route does not match when it should

### ISSUE THREAD

**Issue by KNaudin** [SergioBenitez/Rocket#841]
rocket = "0.4.0-rc.2"
rocket_cors = "0.4.0-rc.1"
on Windows 10 and using Opera

Hello, I am trying to process a POST request using rocket.
I defined a ReceiveNode struct which implements the FromDataSimple trait and created the following function
```
#[post("/addnode", format = "application/json", data = "<node>")]
fn addnode(node: ReceiveNode){
    println!("goodbye");
}
```
Since I try to send the requests from another application running on another port, I also added the CORS as shown in the documentation for rocket_cors:
```
let (allowed_origins, failed_origins) = AllowedOrigins::some(&["http://localhost"]);
assert!(failed_origins.is_empty());

let options = rocket_cors::Cors {
    allowed_origins: allowed_origins,
    allowed_methods: vec![Method::Post, Method::Options, 
    Method::Get].into_iter().map(From::from).collect(),
    allowed_headers: AllowedHeaders::some(&["Authorization", "Accept", "Content-type"]),
    allow_credentials: true,
    ..Default::default()
};
```
Finally, I mount all my routes
```
rocket::ignite().mount("/", routes![index, hello, addnode]).attach(options).launch();
```
When making an XMLHttpRequest to http://localhost:8080/addnode and setting the header to "Content-type: application/json", I get this error:
```
OPTIONS /addnode:
    => Error: No matching routes for OPTIONS /addnode.
    => Warning: Responding with 404 Not Found catcher.
    => CORS Fairing: Turned missing route OPTIONS /addnode into an OPTIONS pre-flight request
    => Response succeeded.
POST /addnode application/json:
    => Matched: POST /addnode application/json (addnode)
    => Outcome: Forward
    => Error: No matching routes for POST /addnode application/json.
    => Warning: Responding with 404 Not Found catcher.
    => Response succeeded.
```
I have no idea why it doesn't find the route or if I did something terribly wrong, could you help me please?

Here's what the request looks like coming from my browser.
![opera_console](https://user-images.githubusercontent.com/17451603/49334992-19437500-f5e4-11e8-8497-e7faea93211b.PNG)

**Comment by jebrosen** [comment]
What are the definitions for `ReceiveNode` and `FromDataSimple for ReceiveNode`? The log output suggests that your own code (the `FromDataSimple` implementation) returned `Forward`, so the `addnode` route is skipped.

**Comment by KNaudin** [comment]
Thank you for your answer. I went back to that part of the code and I realised that I mistyped the ContentType in my from_data function. It works now.
