### ISSUE TITLE
Rocket's `Uri` does not allow anchors to be used (`#`)

### ISSUE THREAD

**Issue by idubrov** [SergioBenitez/Rocket#842]
1. 0.4.0-rc.2
2. Mac OS X
3. The following code fails with an error:

```rust
#[test]
fn parse() {
  rocket::http::uri::Uri::parse("http://example.com/#hello").unwrap();
}
```
4. Was debugging test breaks due to Rocket upgrade.
5. I think, fragment in redirect URL should be allowed (see https://tools.ietf.org/html/rfc7231#section-7.1.2 for an example). Also, this feature is used in OAuth 2.0 protocol (https://tools.ietf.org/html/rfc6749#section-4.2.2).

**Comment by jebrosen** [comment]
For the case of `Redirect`, it is possible to set the `Location` header plus an appropriate status code manually. This is much easier now that we have `#[derive(Responder)]`:

(disclaimer: completely untested)
```rust
#[derive(Responder)]
#[response(status=303)]
struct RawRedirect((), Location);

fn get_redirected() -> RawRedirect {
    RawRedirect((), Location(format!("{}#{}", uri!(destination_route: params...), "fragment/data")))
}
```

This approach is not without its downsides, and it would definitely be more ergonomic for users if Rocket had first-class support for this.

**Comment by SergioBenitez** [comment]
@rien That's identical to `otherlocation`, expect that `otherlocation` is a valid URI.

**Comment by rien** [comment]
@SergioBenitez a `Location` header is allowed to be relative according to https://tools.ietf.org/html/rfc7231#section-7.1.2 .
I have tried using relative URL's without `./` in front of it, but they are also marked as invalid.

**Comment by SergioBenitez** [comment]
Let's work on this in #998.
