### ISSUE TITLE
StaticFiles serving

### ISSUE THREAD

**Issue by suhaschitade** [SergioBenitez/Rocket#844]
Hi,

I am following static files serving example, however compiler is complaining about below issue

error[E0432]: unresolved import `rocket_contrib::serve`
  --> src/main.rs:12:21
   |
12 | use rocket_contrib::serve::StaticFiles;
   |                     ^^^^^ could not find `serve` in `rocket_contrib`

Not sure if examples needs to be updated

Regards,
Suhas

**Comment by SergioBenitez** [comment]
You need to enable the `serve` feature. This is [in the docs](https://api.rocket.rs/v0.4/rocket_contrib/serve/index.html).

**Comment by SergioBenitez** [comment]
Those don't look like Rocket's log messages.

**Comment by suhaschitade** [comment]
Here are few logs from rocket

GET /static/vendor/bootstrap/css/bootstrap.min.css text/css:
    => Matched: GET /<path..> [10]
    => Warning: Response was `None`.
    => Outcome: Failure
    => Warning: Responding with 404 Not Found catcher.
    => Response succeeded.
GET /static/vendor/fontawesome-free/css/all.min.css text/css:
    => Matched: GET /<path..> [10]
    => Warning: Response was `None`.
    => Outcome: Failure
    => Warning: Responding with 404 Not Found catcher.
GET /static/css/clean-blog.min.css text/css:
    => Matched: GET /<path..> [10]
    => Warning: Response was `None`.
    => Outcome: Failure
    => Warning: Responding with 404 Not Found catcher.
    => Response succeeded.
GET /static/vendor/jquery/jquery.min.js:
    => Matched: GET /<path..> [10]
    => Warning: Response was `None`.
    => Outcome: Failure
    => Warning: Responding with 404 Not Found catcher.
    => Response succeeded.
GET /static/vendor/bootstrap/js/bootstrap.bundle.min.js:
GET /static/js/clean-blog.min.js:
    => Matched: GET /<path..> [10]
    =>     => Warning: Response was `None`.
    => Outcome: Failure
    => Warning: Responding with 404 Not Found catcher.
    => Matched: GET /<path..> [10]
    => Warning: Response was `None`.
    => Outcome: Failure
    => Warning: Responding with 404 Not Found catcher.

Below is the code 
    .mount("/", StaticFiles::from("static/"))

**Comment by SergioBenitez** [comment]
Are you starting your application in a directory that contains the `static/` directory? [The docs](https://api.rocket.rs/v0.4/rocket_contrib/serve/struct.StaticFiles.html#example) mention this.

**Comment by suhaschitade** [comment]
No, I was using handlebar templates example which has templates directory, inside template I have created static directory and placed JS and CSS over there.

**Comment by SergioBenitez** [comment]
@suhaschitade Sorry, I don't know how to help you. The unit tests and my local testing confirms that everything works as expected. Please read the documentation closely.

**Comment by suhaschitade** [comment]
thanks for your help. I followed todo example and created static directory and place all html css js there it seems to be working now. Although I would really want to keep HTML separate from css, js it seems its not possible at the moment.
Regards,

**Comment by SergioBenitez** [comment]
@suhaschitade There is no such restriction. You can place files wherever you like.
