### ISSUE TITLE
Display of a uri::Origin does not have "=" in query values escaped

### ISSUE THREAD

**Issue by RalfJung** [SergioBenitez/Rocket#849]
I am using something like the following code to compute URIs in my application:
```rust
let page = uri!(run_action: signed_action = &signed_action);
let absolute_uri = format!("{}{}", config.root_uri, page);

// Further down
#[get("/run_action?<signed_action>")]
fn run_action(
    signed_action: String,
    db: DbConn,
    renderer: Renderer,
    config: State<Config>
) -> Result<Template, Error>
```
In this case, `signed_action` is a string ending in `=` (it is base64 encoded).  `=` needs to be escaped in queries, but it is not: The result of `absolute_uri` above is
```
http://localhost:8000/run_action?signed_action=kpOsMzBiNWMyNmU5ZDZika1wb3N0QHJhbGZqLmRlAdwAIErMq8zjSDJ0KGB3zNFYzIbM9xPMrczaAVBHzINeaRs0Sn3Mw8zZzJzM+syDzOU=
```
Notice the unescaped `=` at the end.  Clicking that link ends up not working, rocket says `Missing required query parameter 'signed_action'.`.

I am using Rocket 0.4.0 on Debian testing.

**Comment by RalfJung** [comment]
Are there any plans for a patch release containing this fix?

**Comment by SergioBenitez** [comment]
@RalfJung Yes. Today.
