### ISSUE TITLE
Support for absolute URIs in uri! macro

### ISSUE THREAD

**Issue by RalfJung** [SergioBenitez/Rocket#853]
I am a big fan of the new `uri!` macro.  Typed URI handling is something I've been hoping for for a while. :)

However, the macro could be even better if the mount point (in `uri!(mount, route: params)`) could be an arbitrary `uri::Uri` (at run-time).  In my application, I am sending out emails that contain links back to the application; clearly, an `uri::Origin` does not work here: I need an `uri::Absolute`.  Currently, I use string concatenation for this purpose, but something more typed seems way more in-line with Rocket's general philosophy.

**Comment by jebrosen** [comment]
Implementation note: `uri!` would have to change to take (for example) `Into<Uri>`. Currently it only supports string literals. It would be nice (but more complicated) to keep supporting string literals that can be verified to be valid `Uri`s at compile time.

**Comment by SergioBenitez** [comment]
Let's work on this in #998.

**Comment by SergioBenitez** [comment]
@RalfJung I apologize for revisiting this nearly two years later, but I'm wondering: were was the absolutely URI statically known? That is, would it suffice for your use-case for Rocket to accept any valid URI _string literal_ in what is now the `mount` part of the URI?

**Comment by RalfJung** [comment]
I think that would not suffice -- the point is to generate an absolute URL to the currently running instance of the application, and I have a configuration option for the user to set the base of that URL (i.e., `https://mgmt.saar.freifunk.net/node-monitor/`). Configuration is obviously only known at runtime.

**Comment by SergioBenitez** [comment]
Finally, this is possible! See [the new `uri!` docs](https://api.rocket.rs/master/rocket/macro.uri.html#prefixes-and-suffixes).
