### ISSUE TITLE
Bring api.rocket.rs docs up to date with the latest release (0.4.0)

### ISSUE THREAD

**Issue by brokenthorn** [SergioBenitez/Rocket#868]
Documentation at api.rocket.rs is not up to date.
For example https://api.rocket.rs/rocket/struct.Rocket.html#method.catch does not exist in rocket 0.4.0, method.register seems to have replaced it (https://api.rocket.rs/rocket/struct.Rocket.html#method.register is a broken link at the moment).

**Comment by jebrosen** [comment]
With the v0.4 release two sets of documentation were added: https://api.rocket.rs/v0.3/rocket/ and https://api.rocket.rs/v0.4/rocket/. The latter includes the method you are looking for (https://api.rocket.rs/v0.4/rocket/struct.Rocket.html#method.register).

https://api.rocket.rs goes to v0.4 and links on https://rocket.rs go to the currently selected version at the top of the page, but the pages haven't changed. I guess those could be redirects or disambiguation pages, but I'm not really sure if @SergioBenitez has a plan for those.

**Comment by brokenthorn** [comment]
I could have sworn that I selected 0.4 while browsing api... I think I even checked before posting this, because I knew about it before... seems to be OK now, as you've said. I guess I should apologize. Sorry if I was mistaken. I'll do another check tomorrow when I'm less tired too.

**Comment by brokenthorn** [comment]
Oops, forgot to close. Closing now.
