### ISSUE TITLE
Form data guards don't fall through

### ISSUE THREAD

**Issue by cazgp** [SergioBenitez/Rocket#877]
I'm not sure if this is a bug or a feature, but it appears that data guards don't behave in the same way as request guards.

1. Rocket version: 0.4
2. OS: Ubuntu 18.10
3. Some code:

```
#[derive(Debug, FromForm)]
pub struct ActivityTypeEditNoSchedule {
    pub name: String,
    pub description: String,
    pub schedule_type: Option<schedules::Schedule>,
}

#[derive(Debug, FromForm)]
pub struct ActivityTypeEditSchedule {
    pub name: String,
    pub description: String,
    pub schedule_type: Option<schedules::Schedule>,
    pub schedule_start_time: String,
    pub schedule_end_time: String,
}

#[post("/activities/types/<id>/edit", data = "<data>", rank = 1)]
pub fn post_schedule(
    id: i32,
    data: Form<ActivityTypeEditSchedule>
) -> Result<Redirect, Markup> {
...
}

#[post("/activities/types/<id>/edit", data = "<data>", rank = 2)]
pub fn post_no_schedule(
    id: i32,
    data: Form<ActivityTypeEditNoSchedule>
) -> Result<Redirect, Markup> {
...
}
```

So, the first route is expecting the data to be of type `ActivityTypeEditSchedule` and the second route is expecting the type to be `ActivityTypeEditNoSchedule`.

On the client side, if schedule_type is None, then schedule_start_time and schedule_end_time are disabled, which means that those fields are not sent in the submit. I would expect the second route to be called in this case.

However, the first route is called, that fails to parse the form, and we get a 422. Rocket doesn't attempt to try the next route. Having data type guards like this would be really useful because then you could be really specific about the form entities that are expected, and which fields are expected to go with which.

Is this a bug or a feature?

PS thanks for the awesome framework -- it's so much fun to work with!

**Comment by jebrosen** [comment]
> I'm not sure if this is a bug or a feature, but it appears that data guards don't behave in the same way as request guards.

On paper they behave the same way: any data guard can return either a `Failure` or a `Forward`, just like request guards. In practice, however, data guards can only return `Forward` if they only peek at `Data`. `Form` can't always tell whether the data will be valid or not by peeking -- in this case, `Form` could only `Forward` if the submitted form is shorter than `Data`'s peek limit. That might be reasonable for some applications, but in your case it would break as soon as someone put a long enough `description` in.

Assuming nothing changes in Rocket, I think your best bet for now is to use `Option` for both `schedule_start_time` and `schedule_end_time` and validate them in the route if `schedule_type` is specified.

> Is this a bug or a feature?

I'm going to say it's a possible "enhancement". I think `Form` *could* `Forward` in some cases, but it would be limited to small forms and adds complexity to the implementation.

**Comment by cazgp** [comment]
Thanks for the response! That's exactly the way I ended up implementing it upon discovering the limitation. It would be great to have this in core, but using options is fine for now. It's a bit of an overhead, but it's not the end of the world.

**Comment by jebrosen** [comment]
Given the downsides, I don't think this is worth pursuing right now. If anyone thinks of a nicer solution we can re-open.
