### ISSUE TITLE
Route attributes cause an error with Atom's linter-rust

### ISSUE THREAD

**Issue by rebo** [SergioBenitez/Rocket#88]
Not sure where the error is, but I am getting this error when saving in Atom using the standard linter:

    stdin:6:7: 6:15 error: expected identifier, found "/world" stdin:6 #[get("/world")] ^~~~ stdin:6:7: 6:15 error: expected one of ) or ], found "/world" stdin:6 #[get("/world")] ^~~~

I'm sure it's not rocket.rs's fault but with Atom being so widespread it would be good to fix this.

**Comment by SergioBenitez** [comment]
This is definitely an issue on Atom's/Rust's side. 

Is your Atom editor using a nightly version of Rust? It's complaining about syntax that is only valid on nightly, so that could be triggering it.

**Comment by rebo** [comment]
Hi thanks for the quick response.  I completely wiped my Atom's install and all associated rust packages, I then re-installed and it is all working fine now.

It must be that my older version of Atom was referencing a non nightly rust install.

Thanks again and happy new year.
