### ISSUE TITLE
Allow auto mount unmounted routers to namespace '/'

### ISSUE THREAD

**Issue by liigo** [SergioBenitez/Rocket#89]

**Comment by SergioBenitez** [comment]
Do you mean to say that if you have some route that's not mounted, it should automatically be mounted by Rocket on `launch()`? If so, it was a very conscious design decision to disallow this. The reasons are 1) it's not possible to do this correctly given Rust's lack of guarantees at code generation time, 2) it is a security concern, and 3) it's _way_ too much magic. I won't discuss 1), but I'll touch a bit further on the other two.

Mounting in Rocket is designed to make it easy to take some external library and mount a bunch of routes under some namespace. If we were to allow what you're suggesting, then an external library can hijack routes from underneath us without our consent. For example, if you have a route at `/login`, the attacker can create an identical route at `/login` with a lower rank. If the route is automounted, that library can intercept all of your traffic unknowingly (minus logging/timing effects). 

But even if you trust the library, it's still _really_ odd that, without your consent, requests can be going elsewhere. In fact, by simply adding a dependency, you can change routing decisions! You now have _no_ local guarantees about which routes will match a given request. This makes reasoning about your program more difficult, something Rocket actively tries to prevent.

For these reasons, I'm highly in disfavor of this approach.

**Comment by liigo** [comment]
Thank you for detail explanation! And sorry, I didn't think too much.
