### ISSUE TITLE
Applying  binary operation `+` to type `rocket::response::content::Html<&str>`

### ISSUE THREAD

**Issue by hajsf** [SergioBenitez/Rocket#891]
How can I return a calculated number or string in the rust code with the `content::Html` below simple example about the required:
```
let average_salary = total_salaryies / number_of_emplyees;
let as_span = content::Html((r#"
<span>"+format!("{}", average_salary)+"</span>
"#);
let y = content::Html(r#"
<p> The average salary is: " + as_span + "</p>
"#);
```

so that I return single statment as respond.

**Comment by jebrosen** [comment]
This is close to what you're trying to achieve, and should compile or be very near to compiling:

```rust
let average_salary = total_salaryies / number_of_emplyees;
let as_span = format!("<span>{}</span>", average_salary);
let y = format!("<p>The average salary is: {}</p>", as_span);
// at the end of the handler: content::Html(y)
```

`Html` is a `Responder` wrapper that sets the response `Content-Type`; as such it should usually be used only at the end after the response is prepared. It's not obvious what `Add`ing responders together should do.

More importantly, this job is more suited to a template engine which will do all the correct things with HTML escaping and allows cleaner separation between the appearance and the implementation of the application.

**Comment by hajsf** [comment]
Thanks @jebrosen  but `format!()` returns `String`, what `content::Html()` required  `&str`
And if I tried converting `y` into `&str` using `format!().as_str()` then I'm getting the below error while trying to return `content::Html(y)`:

> returns a value referencing data owned by the current function

**Comment by jebrosen** [comment]
> And if I tried converting `y` into `&str` using `format!().as_str()` then I'm getting the below error
> > returns a value referencing data owned by the current function

That error is expected in that scenario -- you can't return an `&str` borrowed from a local `String`.

> `format!()` returns `String`, what `content::Html()` required `&str`

`content::Html` can wrap any `Responder`, including `String`. Why isn't `Html<String>` working for your case? If you can provide it, more code including the route declaration would help explain what's happening.

**Comment by hajsf** [comment]
@jebrosen Below the full code:
```rust
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use] extern crate rocket;
use rocket::response::content;

#[get("/")]
fn index() -> content::Html<&'static str> {
    let h1 = r#"
        <h1>Hi there h1</h1><br>
    "#;
    let h5 = r#"
        <h5>Hi there h5</h5><br>
    "#;
    let mix = format!("{0}{1}",h1,h5);
    content::Html(&mix)
}

fn main() {
    rocket::ignite().mount("/", routes![index]).launch();
}
```
The error i got is:
```
error[E0515]: cannot return value referencing local variable `mix`
  --> src/main.rs:16:5
   |
16 |     content::Html(&mix)
   |     ^^^^^^^^^^^^^^----^
   |     |             |
   |     |             `mix` is borrowed here
   |     returns a value referencing data owned by the current function

error: aborting due to previous error
```

If I wrote `content::Html(mix)` without the `&`, I get the below error:
```
error[E0308]: mismatched types
  --> src/main.rs:16:19
   |
16 |     content::Html(mix)
   |                   ^^^
   |                   |
   |                   expected &str, found struct `std::string::String`
   |                   help: consider borrowing here: `&mix`
   |
   = note: expected type `&str`
              found type `std::string::String`
```

**Comment by hajsf** [comment]
I was able to solve it by changing the function signature from:
```rust
#[get("/")]
fn index() -> content::Html<&'static str> {}
```

To
```rust
#[get("/")]
fn index() -> content::Html<String> {}
```

I understood that: 

> Concatenating two strings together create a new buffer. That buffer has to be owned on the stack somewhere. If it can’t just pass ownership up to its caller, then it will have to put the buffer somewhere else or get it from somewhere (like a parameter, though this function doesn’t accept any, or a global or thread-local storage).
> Remembering the ownership rules:
> 
> - Each value in Rust has a variable that’s called its owner.
> - There can only be one owner at a time.
> - When the owner goes out of scope, the value will be dropped.
