### ISSUE TITLE
Returning an Arc as a Responder?

### ISSUE THREAD

**Issue by lukaslueg** [SergioBenitez/Rocket#893]
The question is wether it's possible to return an `Arc` as a `response::Responder` in `rocket 0.4` (hint: no, it's not implemented) or how to solve the following MVE of returning shared state from a handler function.

I have a route that has some shared state behind an `RwLock`. One can basically think of it as a cache. The request comes in, a read-lock it taken, the value is looked up in a HashMap, if its already there it's returned immediately. Otherwise it get's computed, the write-lock is taken, the value inserted and returned.

The question now is how to return the value from the shared cache: Obviously we can't return a reference to the value itself as a Response, as that reference points to a value behind an `RwLock`, which gets unlocked when the handler returns. I could either `clone()` the value in order to return an owned copy (which I'd like to avoid) or use the already existing `Arc`. As far as I can see `response::Responder` is not implemented for `Arc`, though.

Am I solving the wrong problem here? Basically I'd like for this to work:

```rust
use std::sync::{Arc, RwLock};
use std::collections::HashMap;

#[get("/foobar/<r>")]
fn foo<'a>(m: rocket::State<'a, RwLock<HashMap<u32, Arc<String>>>>, r: u32) -> Arc<String> {
    // stripped-down example
    Arc::clone(
        m
        .write()
        .unwrap()
        .entry(r)
        .or_insert_with(|| std::sync::Arc::new(format!("{}", r))))
}
```

**Comment by jebrosen** [comment]
In lieu of a better solution, you should be able to make your own `pub struct ArcStringResponder(Arc<String>)` and `impl Responder` for that, delegating to the `Responder` `impl` for  `&str`. I do suspect that you will end up implementing `Responder` yourself if you do anything other than cloning the `String`, whether it carries an `RwLockReadGuard`, an `Arc`, or something else.

Note: it's not possible to implement `Responder` generically for all `Arc<R>` where `R: Responder` alone. `R` would also need to be required to be clonable or borrowable as some `&T` such that `&T: Responder` to support this usage.

**Comment by lukaslueg** [comment]
Thanks for the quick response. As far as I can see this wouldn't work without a `.clone()` on the string, though: The `&str` derived from `Arc<String>` is bound to the `Arc`, so a `Response::build().sized_body(std::io::Cursor::new(self.0.as_ref()))` references a `&str` which goes out of scope immediately.

**Comment by jebrosen** [comment]
You're right, the `Arc` ends up needing to be owned by the body so my original suggestion won't work. It can be accomplished with the following code if you need it, and probably with similar code for an `RwLockReadGuard`:

```rust
struct ArcResponder<T>(Arc<T>);

impl<T> AsRef<[u8]> for ArcResponder<T> where T: AsRef<[u8]> {
    fn as_ref(&self) -> &[u8] {
        (*self.0).as_ref()
    }
}

impl<'r, T: 'r> Responder<'r> for ArcResponder<T> where T: AsRef<[u8]> {
    fn respond_to(self, request: &Request) -> response::Result<'r> {
        Response::build()
            .sized_body(Cursor::new(self))
            .ok()
    }
}
```

In this code, I've taken advantage of the fact that `Cursor` only needs its inner type to implement `AsRef<[u8]>` to be `Read + Seek`. I feel like this might be too specific a use case to be worth including in Rocket, but a more generic version that worked with pointers other than just `Arc` might be useful.

**Comment by lukaslueg** [comment]
Thanks, I'll close.

The `owning_ref`-crate might help out as a more general solution for `rocket`-supplied implementations:

```rust

use rocket::{request, response};


struct Foo<T> {
    m: owning_ref::OwningRef<T, [u8]>
}

impl<'r, T: 'r> response::Responder<'r> for Foo<T> {
    fn respond_to(self, request: &request::Request) -> response::Result<'r> {
        response::Response::build()
            .sized_body(std::io::Cursor::new(self.m))
            .ok()
    }
}

```

In this example, the type `Foo` is only there because we need a local type.
