### ISSUE TITLE
Serving static files from compressed file

### ISSUE THREAD

**Issue by hajsf** [SergioBenitez/Rocket#895]
In this example:
```rust
use rocket_contrib::serve::StaticFiles;

fn main() {
    rocket::ignite()
        .mount("/public", StaticFiles::from("/static"))
        .launch();
}
```

Is there a way to read and serve the files, if the folder `/static` is a compressed file, as: `/static.zip`

Or is there a way to include the static files within the same binary, so I've all the files in single executable.

**Comment by jebrosen** [comment]
> Is there a way to read and serve the files, if the folder `/static` is a compressed file, as: `/static.zip`

Currently no; and it has some drawbacks like the performance penalty of repeatedly decompressing files.

> Or is there a way to include the static files within the same binary, so I've all the files in single executable.

There are several crates that can automate this, or you could do it manually with [`include_bytes!`](https://doc.rust-lang.org/nightly/std/macro.include_bytes.html)
