### ISSUE TITLE
How to link JS files with the static files

### ISSUE THREAD

**Issue by hajsf** [SergioBenitez/Rocket#897]
I've the below route work perfectly for fetching the file in my `app/static` folder, where the app folder contains both `src` and `static` folders as well as `Cargo.toml` 
```rust
        .mount("/", StaticFiles::from(concat!(env!("CARGO_MANIFEST_DIR"), "/static")))
```

In the static folder I've subfolder containing my `JavaScript` files, the pat of full path of these files is:
`app/static/openui5-runtime-1.61.2/resources/sap-ui-core.js"'`

so, in the `index.html` file, I tried calling this `js` file as:
`src='./openui5-runtime-1.61.2/resources/sap-ui-core.js"'`

But got the below error:

> GET http://localhost:8000/openui5-runtime-1.61.2/resources/sap-ui-core.js%22 net::ERR_ABORTED 404 (Not Found)

Whats the way to link the JS/css files correctly?

Thanks

**Comment by jebrosen** [comment]
> `src='./openui5-runtime-1.61.2/resources/sap-ui-core.js"'`

Does the file name really end with `.js"` with a trailing double quotation mark?

> ```rust
> concat!(env!("CARGO_MANIFEST_DIR"), "/static"))
> ```

Note that this hardcodes the project directory into the final binary and probably isn't what you want to deploy the application. A relative path like "static" will be interpreted relative to the working directory, which last I checked is  still `CARGO_MANIFEST_DIR` for `cargo run`.

**Comment by hajsf** [comment]
> Does the file name really end with `.js"`

I fixed the `"` but still not getting it working, knowing that it works fine once I run [http](https://crates.io/crates/https) from the `static` folder

> Note that this hardcodes the project directory into the final binary and probably isn't what you want to deploy the application

Thanks for the note, I'll consider it at deployment

**Comment by hajsf** [comment]
I think i figured it out, it looks `rocket` doing some kind of matching between the actual file location, and the latest pth defined in the route.
 
Lets's say my file name is `test.js` and it is located in folder `/static/ui`, then the way to define the route of this file in `html` is related to the way the `route` is defined in `Rocket`.

In the rust, the static file will be called as this:

```rust
    let executable = env::current_exe().unwrap();
    let path = match executable.parent() {
        Some(name) => name,
        _ => panic!()
    };
    let index_file = format!("{}\\static\\ui", path.display());
    println!("{}", index_file);
    rocket::ignite()
        .mount(ROUTE, StaticFiles::from(index_file))
```

If ROUTE for example is: `static` then the rust code is:

```rust
        .mount("/static", StaticFiles::from(index_file))
```

And accordingly the `js` file is calledin the `html` file as:

```html5
 <script src="static/......."></script>
...

If ROUTE for example is: `static/ui` then the rust code is:

```rust
        .mount("/static/ui", StaticFiles::from(index_file))
```

And accordingly the `js` file is calledin the `html` file as:

```html5
  <script src="ui/test.js"></script>
```

If ROUTE for example is: `static/ui` then the rust code is:

```rust
        .mount("/", StaticFiles::from(index_file))
```

And accordingly the `js` file is calledin the `html` file as:

```html5
  <script src="/test.js"></script>
```

If ROUTE for example is: `other_than_static` then the `js/css` file can not be called at all.

**Comment by jebrosen** [comment]
I'll stick with this version of the code for my explanation below, which is a bit more specific to your use than the example in the documentation (https://api.rocket.rs/v0.4/rocket_contrib/serve/struct.StaticFiles.html#example)

```rust
    let executable = env::current_exe().unwrap();
    let exe_dir = match executable.parent() {
        Some(parent) => parent,
        _ => panic!()
    };
    let static_path = exe_dir.join("static");
    rocket::ignite()
        .mount("/files", StaticFiles::from(static_path))
        .launch();
```

Two levels of translation happen to go from a requested path to the "real" file path.

For an incoming request for `"/files/ui/test.js"`:

* "/files" matches up with the `mount("/files")` leaving `"/ui/test.js"` for `StaticFiles`.
* `StaticFiles` joins `"/ui/test.js"` to `static_path`, so the on-disk file served is `<exe_dir>\static\ui\test.js`.

The important takeaways here are that `StaticFiles::from` takes the "root path" of the on-disk files to be served, and `mount` specifies where they will be made available. Hopefully this explanation clears things up.

**Comment by hajsf** [comment]
Thanks, to avoid confusion, I prefered to use `http://<server>:<port>/path`, where `path` is the one `mounted` with the route, and prefered to be called `static` or `public` or `www` so the below worked fine with me now:
```html
src="http://localhost:8000/static//openui5-runtime-1.61.2/resources/sap-ui-core.js"
```
With:
```rust
let static_path = exe_dir.join("static");
rocket::ignite().mount("/static", StaticFiles::from(static_path)).launch();
```

**Comment by commandline-be** [comment]
Hi. I arrived here because i failed to have a tera template render a local css located in the /tempaltes/css/ folder. I am deeply stupified by what and how this works.
