### ISSUE TITLE
Resource interpreted as Stylesheet but transferred with MIME type text/html

### ISSUE THREAD

**Issue by hajsf** [SergioBenitez/Rocket#898]
While trying the `tera` template exampple, and trying to call the `style.css` file as:

```html
<link rel="stylesheet" type="text/css" href="style.css">
```

I got the below error:

> Resource interpreted as Stylesheet but transferred with MIME type text/html

Is the server telling the browser that it is an HTML document (Content-Type: text/html) instead of a stylesheet (Content-Type: text/css), how can I fix it?

**Comment by jebrosen** [comment]
It's hard to guess without seeing code. Please include complete descriptions of problems, including any relevant new code or an explanation of what files have been added where.

`NamedFile` (and `StaticFiles`) set the `Content-Type` header based on file extension. If the source is plain data, like a `String` or `[u8]`, the [`Css`](https://api.rocket.rs/v0.4/rocket/response/content/struct.Css.html) responder can be used to set the `Content-Type` manually.

**Comment by hajsf** [comment]
I got the issue while trying to replicate the `tera` template example, just added the `css` file to it.

The app structure is as the attached screenshoot, the `style.css` file is very simple as see as well.

![tera](https://user-images.githubusercontent.com/46838626/51705254-2b61f280-202c-11e9-907c-a88997d349d4.jpg)

The other files are:

1. The `base.html.tera` is:
```html
<!DOCTYPE html>
<html>
  <head>
    <!-- Standard Meta -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <!-- Site Properties -->
    <title>Tera Demo</title>
    <link rel="stylesheet" type="text/css" href="style.css">
  </head>
  <body>
    {% block content %}{% endblock content %}
  </body>
</html>
```

2. The `main.rs` is almost copy/pase of the one in the example, I used it for testing `static files` as well:
```rust
#![feature(proc_macro_hygiene, decl_macro, custom_attribute)]

#[macro_use] extern crate rocket;
extern crate rocket_contrib;
#[macro_use] extern crate serde_derive;

use rocket_contrib::serve::StaticFiles;
use rocket_contrib::templates::Template;

extern crate serde_json;

use std::collections::HashMap;

use rocket::Request;
use rocket::response::Redirect;

use std::env;

#[derive(Serialize)]
struct TemplateContext {
    name: String,
    items: Vec<&'static str>
}

#[get("/")]
fn index() -> Redirect {
    Redirect::to(uri!(get: name = "Unknown"))
}

#[get("/hello/<name>")]
fn get(name: String) -> Template {
    let context = TemplateContext { name, items: vec!["One", "Two", "Three"] };
    Template::render("index", &context)
}

#[catch(404)]
fn not_found(req: &Request) -> Template {
    let mut map = HashMap::new();
    map.insert("path", req.uri().path());
    Template::render("error/404", &map)
}


fn main() {

    let executable = env::current_exe().unwrap();
    let exe_dir = match executable.parent() {
        Some(parent) => parent,
        _ => panic!()
    };
   // let static_path = exe_dir.join("static");
    let cargo_path = 
    rocket::ignite()
     //   .mount("/", StaticFiles::from(static_path))
     //   .mount("/", StaticFiles::from(concat!(env!("CARGO_MANIFEST_DIR"), "/static")))
        .mount("/", routes![index, get])
        .attach(Template::fairing())
        .register(catchers![not_found])
        .launch();
}
```

**Comment by jebrosen** [comment]
Sorry I didn't reply sooner.

The main issue here is that `templates/` is meant for HTML templates, not CSS. It looks like you are now successfully serving the css via `StaticFiles`, so I'll close this issue. Don't hesitate to comment again if you have any more questions about this.
