### ISSUE TITLE
Element.createShadowRoot is deprecated

### ISSUE THREAD

**Issue by hajsf** [SergioBenitez/Rocket#899]
While testing `rocket` with static files, I got the below warning at the chrome developer tool console.

> content.min.js:2 [Deprecation] Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 for more details

**Comment by jebrosen** [comment]
> content.min.js:2

The error is caused by `content.min.js`, whatever that is or comes from. Rocket does not modify or add JavaScript so it is not the source of this problem.
