### ISSUE TITLE
how can I add JS/CSS to Tera Template

### ISSUE THREAD

**Issue by hajsf** [SergioBenitez/Rocket#900]
I tried adding both `js` and `css` to my tera template, the same standard `html` file, but they are unseen.

I even tried the way I found for the static file [here](https://github.com/SergioBenitez/Rocket/issues/897#issuecomment-456943510) but did not work as well!

**Comment by jebrosen** [comment]
Let's keep this discussion thread in #897, which I've just answered with some more explanation.
