### ISSUE TITLE
can not process data in fairing::on_request

### ISSUE THREAD

**Issue by chenqian-dev** [SergioBenitez/Rocket#901]
version is rocket = "0.4"
code like this:

`let fairing = rocket::fairing::AdHoc::on_request("Dummy", |req, data: &Data| {
            let ref mut s = String::new();
            data.open().read_to_string(s);
        });`

and rls tell me 
`[rustc]
cannot move out of borrowed content

cannot move out of borrowed content [E0507]
main.rs(99, 21): cannot move out of borrowed content
&rocket::Data
let fairing = rocket::fairing::AdHoc::on_request("Dummy", |req, data| { ... }
`

**Comment by jebrosen** [comment]
What are you trying to do with the `Data`? Data can only be opened once because it's streamed with no backing buffer, so it can't be opened in `on_request` and still be able to be passed on to a route.

**Comment by chenqian-dev** [comment]
I want to print data before procesing
