### ISSUE TITLE
Consider reexporting derive macros at the same scope at their traits

### ISSUE THREAD

**Issue by dgriffen** [SergioBenitez/Rocket#903]
Currently derive macros are exported only at the crate root. This is not an issue in the 2015 edition since macros are in a global scope accessible by all modules. In the 2018 edition though this can create confusion since both racer and intellij do not provide completion suggestions for importing. It would be useful if derive macros (such as `FromForm`) we exported at the same level as their traits so one could just `use rocket::request::FromForm` and get both the derive macro and trait in scope.

**Comment by jebrosen** [comment]
This seems reasonable and I don't think it has any downsides; if I get time I'll make a PR. It's also worth noting that the edition should not matter for imports: both `macro_use` and `use path::to::macro` can be used in 2015 and 2018 crates.

I believe to support the `macro_use` import style we will need to keep the re-exports at the crate root, even if we also add them at the locations of their corresponding traits.

**Comment by jebrosen** [comment]
This was merged in #912 / 6bf751f.
