### ISSUE TITLE
Using Rocket with a database

### ISSUE THREAD

**Issue by lfairy** [SergioBenitez/Rocket#91]
Reading through the [guide](https://rocket.rs/guide/), I don't see any documentation on using Rocket with database libraries (like Diesel). In particular, it's not clear how to pass the connection object to each request handler. I'd like to see an example of how this could be done.

**Comment by RandomInsano** [comment]
Follow along with us in #53!

I'll likely write a quick example when I get time on Monday and send a merge request in.

**Comment by lfairy** [comment]
Cool, thanks for the pointer! I'll close this issue in favor of that one.

**Comment by netroby** [comment]
Really need example or document connect with database.

**Comment by SergioBenitez** [comment]
@netroby The [todo](https://github.com/SergioBenitez/Rocket/tree/master/examples/todo) and [raw_sqlite](https://github.com/SergioBenitez/Rocket/tree/master/examples/raw_sqlite) examples illustrate to ways to connect to a database.
