### ISSUE TITLE
Can I get template/redirect without changing the URL

### ISSUE THREAD

**Issue by hajsf** [SergioBenitez/Rocket#915]
Let's say I've the below code, from the rocket sample codes:
```rust
#[get("/hello/<name>")]
fn get(name: String) -> Template {
   // let name = String::from("Hasan");
    let context = TemplateContext { name, items: vec!["One", "Two", "Three"] };
    Template::render("mis/hello", &context)
}
```
Then I can redirect to it from other function as:
```rust
Redirect::to(uri!(get: name = "Hasan"));
```
By doing the above, the `url` in the browser is changing to be: `hello/hasan`
Is there a way to do this, for:
```rust
fn index() ->  Redirect { }
// or
fn index() ->  Template { }
```
Without having the URL changed, i.e. as if it is SPA `Single Page App`

**Comment by max-frai** [comment]
I think you are doing it wrong. If you want to have SPA, the data should be queried by ajax, for example. Redirect usage is wrong here.

**Comment by hajsf** [comment]
Thanks @max-frai , I resolved it with below code:

I think I found the answer by using API key guard as [here](https://api.rocket.rs/v0.4/rocket/request/trait.FromRequest.html#example-1) 

```javascript
function reqListener () {
  window.innerHTML = this.responseText;
}

var oReq = new XMLHttpRequest();
oReq.addEventListener("load", reqListener);
oReq.open("GET", "http://localhost:8000/");
oReq.setRequestHeader("x-api-key", "valid_api_key");
oReq.send();
```
With rocket code:
```rust
#[get("/hello/<name>")]
fn get<'r>(_key: ApiKey, name: String) -> Template {
    let context = TemplateContext { name, items: vec!["One", "Two", "Three"] };
    Template::render("hello", &context)
}
```
