### ISSUE TITLE
Redis Database configuration - table named `databases` was not found for this configuration

### ISSUE THREAD

**Issue by dumboluzz** [SergioBenitez/Rocket#918]
I was trying to add a Rocket Managed Redis Connection-Pool, exactly via the documentation and guides but this runtime error keeps coming up when rocket is trying to launch:

```
Error: Database configuration failure: 'kvs'
    => Error: A table named `databases` was not found for this configuration
Error: Rocket failed to launch due to failing fairings:
    => 'kvs' Database Pool
```
My db config looks like this:
```
[global.databases]
kvs = { url = "redis://localhost:6379" }
```
and the poolable:
```
#[database("kvs")]
struct KeyValueStore(redis::Connection);
```

A local redis instance is running on port 6379.

Is the redis config different from the other databases?

**Comment by jebrosen** [comment]
What else is in `Rocket.toml`? That error message should only appear when [global.databases] is missing entirely, so my guess is it's a problem in code or configuration you haven't posted.

**Comment by ELD** [comment]
Additionally, the `Rocket.toml` file should live in the working directory (or a parent of it) that you're running the binary in. So, if you're running `cargo run` from the root of your project directory, your `Rocket.toml` should also live there, too.

**Comment by vladignatyev** [comment]
Strange that it compiles at all, because `KeyValueStore` struct declared as private!

**Comment by dumboluzz** [comment]
> Strange that it compiles at all, because `KeyValueStore` struct declared as private!

It compiles because the whole project ist just one file/module.

**Comment by dumboluzz** [comment]
I resolved the issue thanks to @ELD!
My code editors extension wasn't running the binary with the root directory of the project as the working directory, where my `Rocket.toml`  is.

**Comment by alisianoi** [comment]
Thanks, I missed that the `[global.databases]` should be in `Rocket.toml` and instead put them into `Cargo.toml`. Got the same error as OP during `cargo run`.
