### ISSUE TITLE
How to use databases with Config::build

### ISSUE THREAD

**Issue by sporto** [SergioBenitez/Rocket#922]
Hi 

I would like to use the Rocket 0.4 managed DB using `Config::build`.
I don't understand how to translate the example from `Rocket.toml` to this.

E.g. say in Rocket.toml you would have:

```
[global.databases] 
postgres = { url = "postgresql://user@localhost/db" }
```
How can I configure this using `rocket::custom`? e.g.

```
	let rocket_config = Config::build(Environment::Staging)
		.address("0.0.0.0")
		.port(4010)
		.finalize()
		.expect("Failed to create rocket config");

	rocket::custom(rocket_config)
		...
```

I suppose that I need to use `.extra` for this. Could you give me an example?
Thanks

**Comment by jebrosen** [comment]
I think you will find this documentation for the `rocket_contrib::databases` module helpful: https://api.rocket.rs/v0.4/rocket_contrib/databases/index.html#procedurally

**Comment by sporto** [comment]
Yes, that is clear, thanks
