### ISSUE TITLE
Adding header to Json

### ISSUE THREAD

**Issue by NicholasLYang** [SergioBenitez/Rocket#926]
1. The version of Rocket this question is based on, if any.
0.4.0
  2. What steps you've taken to answer the question yourself.
Looking through documentation, previous questions, etc.
  3. What documentation you believe should include an answer to this question.
https://api.rocket.rs/rocket_contrib/struct.Json.html

I'm trying to understand how I can compose the Json type from `rocket_contrib` with other Responders. Basically, I'm trying to add a header (JWT) to a Json response and struggling with the documentation. Is there a way to do this in the Json type or should I just use a vanilla response?

Thanks for your help,
Nicholas

**Comment by jebrosen** [comment]
> I'm trying to understand how I can compose the Json type from `rocket_contrib` with other Responders.

Many `Responder`s "wrap" other `Responder`s (see https://rocket.rs/guide/responses/#wrapping). For example, the [status code responders](https://api.rocket.rs/v0.4/rocket/response/status/index.html) wrap an `R where R: Responder`. For the specific case of adding a single header, a [custom responder](https://rocket.rs/guide/responses/#custom-responders) sounds appropriate:

```rust
#[derive(Responder)]
struct ThingWithJwtHeader {
    data: Json<ResponseType>,
    header: Header<'static>,
}
```

I've left out a few details, but that should give you an idea of where to go.

> Basically, I'm trying to add a header (JWT) to a Json response

Is the token itself the response, or is it merely accompanying a response? In the first case a header seems unnecessary, and the second case sounds relatively unusual.

**Comment by NicholasLYang** [comment]
@jebrosen thanks for the quick (and really helpful) response! I managed to get the basic code working. To answer your question, I'm returning the token in the header because that's a fairly [standard](https://stackoverflow.com/questions/47709451/pass-jwt-refresh-token-on-header-or-body) place to put it. I'm attempting to create a flow where the client passes the token for every secure request and receives a new token in response. 

A few follow up questions, what do I import to derive Responder? I resorted to using `#[macro_use]`, but I'd prefer to just import the macro. I tried importing `rocket::rocket_codegen::Responder` but it says the crate is private. Also, when I try to make a generic wrapper (I want to wrap a few different responses with this token header), I get an error saying "type generics are not supported". I guess I probably need to implement a generic version by hand then?

Thanks for taking the time,
Nicholas

**Comment by jebrosen** [comment]
> A few follow up questions, what do I import to derive Responder? I resorted to using `#[macro_use]`, but I'd prefer to just import the macro.

The macro import is `rocket::Responder`. If accepted #912 would additionally make it available at `rocket::response::Responder` alongside the trait it derives.

> Also, when I try to make a generic wrapper (I want to wrap a few different responses with this token header), I get an error saying "type generics are not supported". I guess I probably need to implement a generic version by hand then?

Yes; the derive for `Responder` does not currently support type generics, but it might be possible to support that in the future. Currently you will have to implement `Responder` manually.

**Comment by NicholasLYang** [comment]
Great! Thanks again for your help @jebrosen
