### ISSUE TITLE
No direct API to always get a config value as a string

### ISSUE THREAD

**Issue by mhlakhani** [SergioBenitez/Rocket#927]
I was initially going to file this as a bug report but then realized it fits more as a feature request.

This is on `Rocket 0.4.0`, on `Mac OS X 10.13.6 (17G3025)`

I'm trying to write a configuration where a user provides an app ID (which can be alphanumeric). This is used to make external API calls. I have code like this in my app:

```
let _test = rocket.config().get_string("test").expect("Need this to be set!");
```

This works fine if the value of the appropriate environment variable is a string:

```
$ ROCKET_TEST='abc' cargo run
```

But if I pass it in as an integer (albeit within quotes on the shell), this will fail:

```
ROCKET_TEST='123' cargo run
thread 'main' panicked at 'Need this to be set!: BadType("development.test", "a string", "integer", Some("[redacted]/Rocket.toml"))', src/libcore/result.rs:997:5
```

I know that this is documented, but this makes generic development hard. The external API works with both numeric only and alpha IDs (I don't control this). If the value they provide in the config happens to just be numeric, the code will fail.

I believe this is the line of code which forces it to always be parsed as an integer: 

https://github.com/SergioBenitez/Rocket/blob/v0.4/core/lib/src/config/toml_ext.rs#L64

I'm currently using this workaround:

```
let _test = format!("{}", rocket.config().get_extra("test").expect("Need this to be set!"));
```

That works, but it was not obvious at all.

Is it possible to provide an API to get the raw string value, regardless of the type?

**Comment by jebrosen** [comment]
Is `ROCKET_TEST='"123"'` (with double quotes) a usable workaround for you? Anything in double quotes can only be interpreted as a string.

IMO the inconsistency is that any non-number bareword will be parsed as if it was a string, which isn't really toml syntax but is more convenient for specifying certain configuration variables such as `ROCKET_ADDRESS`

**Comment by mhlakhani** [comment]
> Is `ROCKET_TEST='"123"'` (with double quotes) a usable workaround for you? Anything in double quotes can only be interpreted as a string.

That's a great workaround, thank you!

When I was trying earlier I was going with `ROCKET_TEST="'123'"` which didn't work since it was now having `'` characters as part of the string.

I'm fine closing this out now; we might want to document this workaround though.

**Comment by SergioBenitez** [comment]
Let's make a note of this for #852.
