### ISSUE TITLE
WRK output wrong?

### ISSUE THREAD

**Issue by hjanuschka** [SergioBenitez/Rocket#928]
hey 🤚 thx for this greate crate!
i am currently trying to figure out with http framework i should use, rocket seems to be solid.

when doing benchmarks, i have a little problem, `wrk`  always show's all connections as "read" errors.

any idea what that could be?

```
Running 30s test @ http://127.0.0.1:8083
  12 threads and 13 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.34ms    2.82ms  87.67ms   93.04%
    Req/Sec   463.56     97.90     0.99k    66.53%
  166349 requests in 30.07s, 31.41MB read
  Socket errors: connect 0, read 166344, write 0, timeout 0
Requests/sec:   5531.90
Transfer/sec:      1.04MB

```

when doing, the same business logic, with nickel, iron or whatever,i get clean wrk output.
requests seem to work, if i do the test with `ab` results seem to be valid.

**Comment by jebrosen** [comment]
Try disabling keep-alive for the tests (`ROCKET_KEEP_ALIVE=0` in the environment, or `keep_alive = 0` in `Rocket.toml`). This looks similar to #580 and I'm inclined to think it's a bug in `wrk`'s reporting or error handling; `siege` doesn't seem to have similar issues and neither do browsers.

It's also likely specific to hyper 0.10, which Rocket should stop using relatively soon. As such, I don't think we stand to gain much from keeping this issue open.

**Comment by hjanuschka** [comment]
@jebrosen THX! yes the keepalive env fixed it.
