### ISSUE TITLE
Guard to return json instead of html

### ISSUE THREAD

**Issue by kariae** [SergioBenitez/Rocket#929]
I'm trying to create a data guard which returns a JSON response if it fails to parse the received data.

I tried the approach described in #772 but I had the following error

```
the trait `rocket::data::FromData<'_>` is not implemented for `std::result::Result<rocket_contrib::json::Json<std::vec::Vec<Person>>, ServerError>`
```

Knowing that I implemented `Responder` for my custom error struct `ServerError` and the handler looks like this

```rust
#[post("/person", data = "<persons>")]
fn post_persons<'a>(
    persons: Result<Json<Vec<Person>>, ServerError>
) -> Result<JsonValue, ServerError> {}
```

Did I missed something?

Thanks

**Comment by jebrosen** [comment]
`FromData` is implemented for `Result<T, T::Error>`. In this case, `T` is `Json<Vec<Person>>` (and `Person` must implement `Deserialize`) and `T::Error` is `JsonError` -- not `ServerError`. If you implement `From<JsonError> for ServerError` you will be able to use `persons?` to convert the error if it occurs, but that's the closest to an automatic/convenient conversion between the error types I think you'll get.

**Comment by kariae** [comment]
`Person` already implements `Deserialize`, `ServerError` is a custom struct i create to sanitize all the errors returned by the server, digging a little bit in the documentation I've found `ParseError, JsonError`, ... that I can use did the right things for me, for now my code looks something like this, and it returns well a `JSON`

```
#[post("/person", data = "<persons>")]
fn post_persons<'a>(
    persons: Result<Json<Vec<Person>>, JsonError>
) -> Result<JsonValue, ServerError> {}
```

Thanks for the hints I think we can close this :)
