### ISSUE TITLE
Emitted items should be pub only if the request handler is pub.

### ISSUE THREAD

**Issue by SergioBenitez** [SergioBenitez/Rocket#93]

**Comment by SergioBenitez** [comment]
One concern is that this makes testing more difficult as you'll now need to `pub` everything. One solution is to automatically `pub` if the testing feature is enabled. This would result in a seamless testing experience while make the functions public otherwise.

**Comment by SergioBenitez** [comment]
Let's push this to 0.3 as it's not critical.

**Comment by SergioBenitez** [comment]
I struggle to weigh the benefits (private by default) against the cons (usability implications). Any input that might provide justification for or against this change would be beneficial.

**Comment by mehcode** [comment]
I'm neither for or against this change as it doesn't impact me in the slightest. I favor a large (and separate) integration suite so pub/no-pub doesn't really affect my testing.

**Comment by rbalicki2** [comment]
Generally, I see this as a consistency issue: if something is not declared public, it should not secretly become public. Namely, I think you should allow people to export a single function from a file which returns a vector of routes, while keeping those functions private.

As a side note, I feel like this relates to #174, in that it's only an issue if people are breaking things up across multiple files, e.g. in sufficiently large projects.

This seems like an OCD thing, and I don't think it's the end of the world if the functions are re-exported publicly.
