### ISSUE TITLE
the example hello_world error.

### ISSUE THREAD

**Issue by fhbzyc** [SergioBenitez/Rocket#940]
the example hello_world error.

error: failed to run custom build command for `pear_codegen v0.1.2`
process didn't exit successfully: `/Users/xxx/Rocket/target/debug/build/pear_codegen-eda5b1288a24bff5/build-script-build` (exit code: 101)
--- stderr
Error: Pear requires a nightly or dev version of Rust.
Installed version is: 1.32.0 (2019-01-16). Minimum required: 1.31.0-nightly (2018-10-05).

**Comment by jebrosen** [comment]
> Error: Pear requires a nightly or dev version of Rust.

As explained in [the guide](https://rocket.rs/guide/quickstart/) and the [README](https://github.com/SergioBenitez/Rocket/blob/v0.4/README.md#nightly), Rocket can only be built with nightly releases of rust. #19 is the tracking issue for compatibility with stable rust releases.
