### ISSUE TITLE
Rocket spawned in a new thread

### ISSUE THREAD

**Issue by kariae** [SergioBenitez/Rocket#942]
I'm trying to launch Rocket in a spawned thread, but when I run the binary and check the opened ports I can seem to find the port opened by Rocket `1337`, and the loop before print only `1`

```rust
thread::spawn(|| {
        for i in 1..10 {
            println!("hi number {} from the spawned thread!", i);
            thread::sleep(Duration::from_millis(1000));
        }

        rocket::ignite()
            .mount("/", routes![index])
            .register(catchers![not_found])
            .manage(ConfigElements {
                token,
                file,
            })
            .manage(logger)
            .launch();
    });
```

**Comment by jebrosen** [comment]
I copied very similar code into the hello world example and it worked as expected:

```rust
thread::spawn(|| {
        for i in 1..10 {
            println!("hi number {} from the spawned thread!", i);
            thread::sleep(Duration::from_millis(1000));
        }

        rocket::ignite()
            .mount("/", routes![index])
            .register(catchers![not_found])
            .manage(ConfigElements {
                token,
                file,
            })
            .manage(logger)
            .launch();
    });
```

Please include the details requested in the issue template (version of Rocket, operating system, and a short reproducible test) so we can diagnose this more effectively.

**Comment by kariae** [comment]
Sorry, here are the details:
Rocket 0.4.0.
Mac OS X 10.11 / Ubuntu Server 18

**Comment by jebrosen** [comment]
Can you try this code exactly as written?

```rust
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use] extern crate rocket;

#[cfg(test)] mod tests;

#[get("/")]
fn hello() -> &'static str {
    "Hello, world!"
}

fn main() {
    let t = std::thread::spawn(|| {
        for i in 1..=5 {
            println!("hi number {} from the spawned thread!", i);
            std::thread::sleep(std::time::Duration::from_millis(500));
        }

        rocket::ignite().mount("/", routes![hello]).launch();
    });

    t.join().unwrap();
}
```

If that works fine, my guess is it's something to do with the rest of your code which you haven't shared.

**Comment by kariae** [comment]
Your example is working, the missing part in my code was `t.join().unwrap();` which fix my code, but don't do what I was waiting for which is another issue, I'm trying to run Rocket in another process, but this code start Rocket in the same process just with another thread, the idea behind what I want to do is to run a command that launch Rocket and then I can close the connection to the server (having Rocket running in the background), I was thinking about having the command as a systemd service, but this is my last hope, any idea on how to achieve this?

**Comment by jebrosen** [comment]
If the end goal is "run as a service", then you shouldn't need to change any server/application code. A systemd unit like this should be enough to get something running to play with, but needs to be configured for your own deployment needs:

```
[Unit]
Description=web server for www.example.com

[Service]
User=http
ExecStart=/srv/www.example.com/server
WorkingDirectory=/srv/www.example.com
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

As long as `main()` calls `launch()`, this server should run until stopped.

**Comment by kariae** [comment]
Yes, this was the solution I've found past days, but since the server will be distributed to different users, I can't assume they have `systemd` all of them, and I can already see that in Alpine for example they use ` OpenRC` instead

**Comment by jebrosen** [comment]
Rocket doesn't have much or anything in the way of a deployment guide (see #171), where this kind of information would best belong. However, I think Rocket should not know anything about service or process management itself because it's too platform-specific.

I usually learn towards not adding backgrounding support directly into applications for the same reason. You can distribute service files and init scripts yourself for platforms you support, external to the code - if downstream operating systems package your software, they will create or modify such scripts anyway.

If you want the functionality, you could add a "background" command line argument that would re-run the process with the [`Command`](https://doc.rust-lang.org/nightly/std/process/struct.Command.html) API.

**Comment by kariae** [comment]
> You can distribute service files and init scripts yourself for platforms you support, external to the code
Finally I think I'll do it this way, thanks for the detailed help, I think we can close this.

**Comment by jebrosen** [comment]
> thanks for the detailed help

Of course!
