### ISSUE TITLE
Do not abort launch when database is down

### ISSUE THREAD

**Issue by sanisoclem** [SergioBenitez/Rocket#957]
1. Why you believe this feature is necessary.
   
to simulate scenarios where the database is not available. Currently, launch aborts when the `onAttach` fairing from the db fails. I think it should only fail in case of misconfiguration (no amount of retries will change anything) and continue if it is configured but the db cannot be reached (since it could go up). 

  2. A convincing use-case for this feature.
     
    - Scenarios where the database is optional (aggregating from multiple dbs). 
    - Integration testing where you want to simulate no db connection.

  3. Why this feature can't or shouldn't exist outside of Rocket.

     The code that generates the db fairings are in the codegen crate.

I'm not sure how relevant this will be to other people and I'm open to other approaches to my problem.

**Comment by jebrosen** [comment]
> I think it should only fail in case of misconfiguration (no amount of retries will change anything) and continue if it is configured but the db cannot be reached (since it could go up).

I think in most cases these situations are indistinguishable from each other. It might be possible to do it with provider-specific code, though.

> The code that generates the db fairings are in the codegen crate.

It looks like Rocket could allow initial connection failure by using [`build_unchecked`](https://docs.rs/r2d2/0.8.3/r2d2/struct.Builder.html#method.build_unchecked), but my guess is that it wouldn't be desired default behavior. It would still be nice to support this, though.

**Comment by sanisoclem** [comment]
> I think in most cases these situations are indistinguishable from each other. It might be possible to do it with provider-specific code, though.

Oh, I just assumed that it's trivial to check because of the wording [here](https://github.com/SergioBenitez/Rocket/blob/fcd64342fdc9e4d063bfabc5c9f7cc033cde04ac/contrib/codegen/src/database.rs#L100-L112). 

> It looks like Rocket could allow initial connection failure by using [`build_unchecked`](https://docs.rs/r2d2/0.8.3/r2d2/struct.Builder.html#method.build_unchecked), but my guess is that it wouldn't be desired default behavior. It would still be nice to support this, though.

Yes, I'm not too familiar with how it all works but maybe a parameter on `db::fairing()` or an entry in the configuration?

**Comment by jebrosen** [comment]
> Oh, I just assumed that it's trivial to check

I guess it depends on the kind of check you mean. Do you consider a wrong hostname to be misconfiguration, or a host that "might come up"? What about a misspelled database name?

A lot of this is driver-specific, but currently the misconfiguration vs connection distinction is whether the error occurs before trying to connect (usually invalid syntax for that database driver's connection string) or when trying to connect.

**Comment by jebrosen** [comment]
I've taken a quick look at the different types Rocket implements pools for, and summarized the failure conditions as they would be reported by Rocket. I did this by glancing through code and it may have errata.

I defined syntax error as "The URL is wrong in some obvious way or failed to parse". e.g. does not start with `postgres://`, or is missing a database name. This is driver-specific.

Notice that several drivers do not even check the syntax of the connection string until connection time. I didn't try to discern whether or not the implementation of `Poolable` can check. For some drivers, it may not be possible with the public API to check the syntax of a connection string before attempting to connect.

Driver | "Database configuration failure" | "Failed to initialize pool"
--- | --- | ---
diesel | always succeeds | wrong url for backend / syntax error, failure to connect
postgres | syntax error | failure to connect
mysql | always succeeds | syntax error, failure to connect
rusqlite | always succeeds | failure to connect (invalid path, access denied, etc.)
cypher | always succeeds | syntax error, failure to connect
redis | syntax error | failure to connect
mongodb | syntax error | failure to connect
memcache | always succeeds | syntax error, failure to connect

I *think* your original proposal would be best approximated with "fail to launch for Database configuration failure" and "ignore error for Failed to initialize pool". The first case is already done that way, the second could be done with `build_unchecked` which will fail for every guard requested as long as the database can't be connected to.

But, it will only work as desired for postgres, redis, and mongodb. If we switch to `build_unchecked`, even connection string syntax errors won't be caught until individual connections are retrieved, after waiting for (as far as I can tell) 30 seconds per connection.

**Comment by cwhakes** [comment]
I just ran into this issue. Essentially, my Heroku Postgres database ran out of connections, and that took my entire site down, even though the database is essentially non-essential.

Perhaps there could be a way to ignore the failed database connection (even if due to a syntax error), but then whenever we try to use it with `#[database(MyDatabase)]` and it fails, it would redirect the request to some guard that would allow the code to handle/troubleshoot the failed connection.

I have no idea what the performance impact of that would be.

**Comment by jebrosen** [comment]
> I just ran into this issue. Essentially, my Heroku Postgres database ran out of connections, and that took my entire site down, even though the database is essentially non-essential.

Running out of connections shouldn't be taking a server down - the generated request guard does already fail with a `ServiceUnavailable` status until connections are available again. Did something else additionally cause the server to restart while the database was overloaded?

**Comment by cwhakes** [comment]
I deployed a new version of the code which had worked in staging. They were using the same database, because I am still learning the dos and don'ts of this sort of thing. Still, Heroku shuffles dynos all of the time, so a restarting server is pretty normal on the platform.

**Comment by jebrosen** [comment]
Ah, it looks like Heroku's Hobby Tier for postgres has [a limit of 20 connections](https://devcenter.heroku.com/articles/heroku-postgres-plans#hobby-tier). Depending on your exact setup, setting a `pool_size` in `Rocket.toml` to a lower value (the default is 10) is probably a good idea.

**Comment by cwhakes** [comment]
Already done and fixed yesterday, but if something else happens, then it would be nice to have an option to recover gracefully.

(As far as I can tell, the limit is equal to the number of workers, which was 16 in my case.)

**Comment by SergioBenitez** [comment]
I'm in favor of making this an option, disabled by default. Let's track this in #1117, however.
