### ISSUE TITLE
Code example typo in rocket.rs guide

### ISSUE THREAD

**Issue by murtyjones** [SergioBenitez/Rocket#960]
## Link
https://rocket.rs/v0.4/guide/state/
## Screenshot
![image](https://user-images.githubusercontent.com/708562/55297515-bed0ee80-53f4-11e9-9c38-71eb2fc0e867.png)
## Issue
I think line 9 of the code section screencapped above should read:
```
Logs::by_id(&*conn, id)
```
Instead of:
```
Logs::by_id(&conn, id)
```
I'm still learning Rust + Rocket so correct me if I'm wrong. But `&conn` doesn't work for me (using the MongoDB driver), whereas `&*conn` does work.

**Comment by jebrosen** [comment]
There *are* a few fixes in master that haven't made it into 0.4 yet: 1) documentation explaining to use `&*conn`, which as far as I know only mattered for diesel, and 2) implementing `DerefMut`, which I think applied to mongodb but `&*conn` wouldn't work around that.

But if you're using the MongoDB driver and not diesel, then I don't think you have provided the code needed to figure out the issue.

**Comment by murtyjones** [comment]
Yikes! Turns out my IDE (PHPStorm) is returning a false positive for a mismatched type error. `&conn` actually compiles fine, my IDE just thought that it wouldn't. Sorry for the false alarm!
