### ISSUE TITLE
No way to resolve route collisions between multiple bundles of static files

### ISSUE THREAD

**Issue by agersant** [SergioBenitez/Rocket#965]
Rocket Version: 0.4.0
OS: Windows 10
Description of the bug:

When mounting multiple sets of static files, there is no way to resolve route collisions between them. In my case, the route setup looks like:
```
rocket::custom(config)
	.mount("/api", api::get_routes())
	.mount("/swagger", StaticFiles::from("docs/swagger'))
	.mount("/", StaticFiles::from("web"))
```

The output looks like:
```
Rocket failed to launch due to the following routing collisions:
GET /swagger/<path..> [10] collides with GET /<path..> [10]
GET / collides with GET /
Note: Collisions can usually be resolved by ranking routes.
```

The error makes sense, but looking at the documentation, I cannot see a way to specify route ranks when using StaticFiles.

Thank you very much!

**Comment by jebrosen** [comment]
Yeah, unfortunately StaticFiles is hardcoded to a rank of 10. It should be made customizable.

In the meantime, you can still do it [the 0.3 way](https://github.com/SergioBenitez/Rocket/blob/v0.3/examples/static_files/src/main.rs#L20). You'll gain control over the ranking, but lose the automatic serving of "/path/to/index.html" when "/path/to" is requested.

**Comment by agersant** [comment]
Thank you for the quick answer!
This seems like a very reasonable trade-off for my use case.

**Comment by agersant** [comment]
Thanks!
