### ISSUE TITLE
XSS in rocket.rs search 

### ISSUE THREAD

**Issue by raminfp** [SergioBenitez/Rocket#969]
Hi,

## Bug

1 - view-source:https://rocket.rs/v0.4/guide/

2 - ``` <input id="search-input" placeholder="Search guide...">```

3 - 
```javascript
on_search_results("../js/search-index.json", "search-input", function(docs) {
   hitsDiv.innerHTML = "";
   toggleResultsIfNecessary();
   var query = searchBar.value;
    
   if (docs.length == 0) {
   noResults = `<b>We didn't find any results for <em>${query}</em>.</b>`;
   searchStatus.innerHTML = noResults; ## vulnerability code
  return;
   }

```

## Fix

```searchStatus.innerText = noResults;```

**Comment by jebrosen** [comment]
Note that switching to `innerText` isn't a complete fix because of the HTML tags in `noResults`.

Assigning @SergioBenitez because I don't have write access.

**Comment by SergioBenitez** [comment]
This has been fixed!
