### ISSUE TITLE
Submit: Login button not defined in main.rs

### ISSUE THREAD

**Issue by jtbarker** [SergioBenitez/Rocket#971]
The submit: login button is not well documented, I see it in the form html but not in the struct alongside any of the other user inputs, and I don't see anything else in the project labelled as submit or login. Where is this button defined?

**Comment by jebrosen** [comment]
Is this from an example (and which one?), or the guide? I assume you mean one of the examples that contains this code in its `index.html`:

```html
    <input type="submit" value="Login">
```

Since there is no `name` specified, the button's value is not ever sent to the server -- the rust code doesn't even know that the button exists.

**Comment by jtbarker** [comment]
It's from the example form_kitchen_sink. The button works so I assume it is doing something, it's just not defined in the project anywhere.

**Comment by jebrosen** [comment]
The button is "defined" at https://github.com/SergioBenitez/Rocket/blob/master/examples/form_kitchen_sink/static/index.html#L45, but it only serves as the submit button on the client side and doesn't need any server-side handling.
