### ISSUE TITLE
Working with distributed PG database

### ISSUE THREAD

**Issue by hajsf** [SergioBenitez/Rocket#974]
In my app, I'll be having 2 PG databases in 2 different pcs, `pc_ip1` and `pc_ip2`, both databases are identical, and I need each change to be done for both DBs simultaneously.

Is there a way that `create/insert/update/delete` statements can be done to both DBs at once?
Is there a way to do `select` statement with such setup, and get notified if the returned results are not the same?

Can you pls give small example about using PG, and show how the above can be done (if possible)?

**Comment by jebrosen** [comment]
> Is there a way that create/insert/update/delete statements can be done to both DBs at once?

You *could*, but it's often more efficient and easier to deal with from an administrative standpoint to use Postgres replication, rather than doing it in the application.

> Is there a way to do select statement with such setup, and get notified if the returned results are not the same?

If the databases are always the same, when would the results ever not be the same?

---

I don't want to provide misleading information or direct you towards unnecessary work. It would be good to know why you even need two identical databases.

**Comment by hajsf** [comment]
Thanks @jebrosen  appreciate your feedback, I'm thinking to do some application with block-chain concept, that has having distributed ledger/database with multiple nodes to avoid cheating, replication will replicate such changes and hide them, this  is my last question was, understand the question is not really related to rocket, but appreciate to show me how to define multiple databases so I can push/pll data from :)

**Comment by jebrosen** [comment]
With Rocket's [database support](https://rocket.rs/guide/state/#usage), any number of databases can be defined, for example:

```rust
#[macro_use] extern crate rocket;
#[macro_use] extern crate rocket_contrib;

use rocket_contrib::databases::postgres;

#[database("pgdb1")]
struct PgDb2(postgres::Connection);

#[database("pgdb2")]
struct PgDb2(postgres::Connection);

#[get("/")]
fn index(conn1: PgDb1, conn2: PgDb2) {
    // use conn1 and conn2
}

fn main() {
    rocket::ignite()
       .attach(PgDb1::fairing())
       .attach(PgDb2::fairing())
       .launch();
}
```

They can be the same or different databases (e.g. both MySQL and Postgres), and routes can freely use one or the other or both.
