### ISSUE TITLE
Valid ROCKET_DATABASES with multiple values

### ISSUE THREAD

**Issue by murtyjones** [SergioBenitez/Rocket#977]
Hello! is this:
```
ROCKET_DATABASES={my_datastore_1={url="..."}, my_datastore_2={url="..."}}
```
considered valid by Rocket?

I'm attempting to conditionally compile based on whether I'm running running Rocket for local development or local testing, but when I use the format above I get this:

    A table named `databases` was not found for this configuration

So just wondering if `ROCKET_DATABASES` is intended to be used with multiple values

  1. The version of Rocket this question is based on, if any.

0.4.0
  2. What steps you've taken to answer the question yourself.

Searched the documentation site and this repo
  3. What documentation you believe should include an answer to this question.

An example in the docs site would be useful if this is indeed allowed

**Comment by jebrosen** [comment]
#919 added an example of the environment variable for multiple databases, but the docs haven't been re-published yet.

My guess is the problem is with passing the variable from your shell. Since the error is that it's not found, maybe you didn't export the variable? Either of `export ROCKET_DATABASES=...; app` or `ROCKET_DATABASES=... app` should work in `bash`, for example.

Aside from that, you might also have an issue with quoting, as there are ` ` (space) and `{` characters. Removing the space or single quoting the whole value should fix that.

**Comment by murtyjones** [comment]
Yep it looks like the space was the issue in my case. Thanks for the quick response!

**Comment by jebrosen** [comment]
If there was no log message or anything complaining about invalid syntax, maybe we should keep this open as a reminder to fix that.

**Comment by murtyjones** [comment]
It'd be helpful, for sure. The `A table named `databases` was not found for this configuration` error was all I got and that led to more confusion on my part.

**Comment by jebrosen** [comment]
I do get this error when I try to reproduce:

```
$ ROCKET_DATABASES={my_datastore_1={url="..."}, my_datastore_2={url="..."}} cargo run

Error: environment variable ROCKET_DATABASES={my_datastore_1={url=...}, could not be parsed
    => expected any token but none was found (take_some_while)
```

So Rocket does emit an error if a variable has invalid syntax, and I don't think Rocket can do better than that. I'm not sure why you didn't get that error message, though.

**Comment by murtyjones** [comment]
So it looks like environment variables don't get validated in typical Rocket fashion when `dotenv` is used:

**src/main.rs**
```
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use] extern crate rocket;
extern crate dotenv;

use dotenv::dotenv;

#[cfg(test)] mod tests;

#[get("/")]
fn hello() -> &'static str {
    "Hello, world!"
}

fn main() {
    dotenv().ok();
    rocket::ignite().mount("/", routes![hello]).launch();
}
```

**.env**
```
ROCKET_DATABASES={postgres_datastore={url="postgres://postgres:develop@localhost:5432/postgres"}, testing={url="postgres://postgres:develop@db:5432/postgres"}}
```

**expected behavior**
```
Error: environment variable ROCKET_DATABASES={postgres_datastore={url=postgres://postgres:develop@localhost:5432/postgres}, could not be parsed
```

**actual behavior**
```
🚀 Rocket has launched from http://localhost:8000
```

**Comment by jebrosen** [comment]
Aha, you're using dotenv. I suspect `dotenv()` is returning an error, which you immediately ignore with `.ok()`. Either way there's nothing to fix in Rocket after all.

**Comment by murtyjones** [comment]
Got it. Thanks!
