### ISSUE TITLE
[docs] How can I conditionally attach a fairing?

### ISSUE THREAD

**Issue by jhpratt** [SergioBenitez/Rocket#978]
If this functionality has enough demand, this may be feasible for a PR. Until then, this issue will serve as documentation for how to conditional attach a fairing.

---

Include the following boilerplate in your project, which will add the method `attach_if()` to a Rocket instance.

```rust
use rocket::{fairing::Fairing, Rocket};

pub trait ConditionalAttach {
    fn attach_if(self, condition: bool, fairing: impl Fairing) -> Self;
}

impl ConditionalAttach for Rocket {
	#[inline]
    fn attach_if(self, condition: bool, fairing: impl Fairing) -> Self {
        if condition {
            self.attach(fairing)
        } else {
            self
        }
    }
}
```

To use this new method, you'll need to `use` the trait in the file (if you've added the boilerplate in a different file). After that, it's trivial. As an example, here's how you can conditionally attach a telemetry fairing.

```rust
use file_name::ConditionalAttach;

rocket::ignite()
	...
	.attach_if(cfg!(feature = "telemetry"), Telemetry::default())
	...
```

Unlike using an `AdHoc` fairing, which can get quite messy and leaves a trace (as it must be given its own name), this implementation is completely silent if the condition is false and is quite clean.

**Comment by SergioBenitez** [comment]
That's neat! Would certainly be a good feature add if there's demand. Please feel free to comment as such! Closing out to clean up the issue tracker.

**Comment by jhpratt** [comment]
Just for reference for anyone searching for this functionality, I've just published the above code as `rocket_conditional_attach`. Just `cargo add rocket_conditional_attach`, add `use rocket_conditional_attach::prelude::*;`, and you're all set. The code is available in [@jhpratt/rocket_conditional_attach](https://github.com/jhpratt/rocket_conditional_attach).

Hopefully this will serve as a passive way to track actual demand for this feature.
