### ISSUE TITLE
one `IntoOutcome` for `Result` implementation returns a `BadRequest`, the other `InternalServerError`

### ISSUE THREAD

**Issue by rbalicki2** [SergioBenitez/Rocket#98]
`from_data.rs` has `Err(err) => Failure((Status::InternalServerError, err))` and `from_request.rs` has `Err(val) => Failure((Status::BadRequest, val))`.

**Comment by SergioBenitez** [comment]
This is by design, though a rather arbitrary design. `IntoOutcome` is not a particularly great trait. I believe the API should be:

```rust
result.into_outcome(failing_status)
```

This will remove the current arbitrary nature while adding flexibility.

**Comment by SergioBenitez** [comment]
Putting this in the 0.4 bucket for now.
