### ISSUE TITLE
hyper dependency is outdated

### ISSUE THREAD

**Issue by gdesmott** [SergioBenitez/Rocket#984]
Hi there,

Rocket still depends on hyper `0.10.13` which is quite old (Aug 2017). Is there any specific reason for this or would you consider upgrading to newer releases?

Thanks!

**Comment by jebrosen** [comment]
hyper 0.11 (and 0.12) have an entirely different `Future`-based API, which is not something Rocket can use effectively without exposing `Future`s or another async capability itself. I've done some preliminary work on that (see also https://github.com/SergioBenitez/Rocket/issues/17#issuecomment-415609486), and if everything goes well it should be completed during this year.
