### ISSUE TITLE
Using explicit lifetimes in routes

### ISSUE THREAD

**Issue by WillSquire** [SergioBenitez/Rocket#987]
I'm trying to pass a lifetime in a route, but I've got an error and can't find documentation on what lifetimes are used in route macros?

This is the code I'm trying to use:
```rust
#[post("/graphql", data = "<request>")]
pub fn post_graphql_handler<'a>(
  context: Context<'a>,
  request: GraphQLRequest,
  schema: State<Schema<'a>>,
) -> GraphQLResponse {
  request.execute(&schema, &context)
}
```

This is the error:
```
explicit lifetime required in the type of `__req`

lifetime `'_b` required

help: add explicit lifetime `'_b` to the type of `__req`: `&'_b rocket::Request<'_b>`
```

`Context` stores per request data and is created with `FromRequest` to store things such as the user and is combined with references to the global data from `State` to get the hashing functions, etc. The other bits are from the [Juniper GraphQL](https://github.com/graphql-rust/juniper) crate.

**Comment by jebrosen** [comment]
More code would be good here, a full but minimal reproduction if possible -- especially because the definition of `FromRequest` for `Context` might be affecting this. In particular, I've reproduced this error with `impl<'a> FromRequest<'a, 'a> for Type<'a>`.

That aside, you should be able to use `'_` for both lifetimes:
```rust
pub fn post_graphql_handler(
  context: Context<'_>,
  request: GraphQLRequest,
  schema: State<'_, Schema<'_>>,
) -> GraphQLResponse {
```

**Comment by WillSquire** [comment]
Thanks for getting back @jebrosen. Here's the implementation of `FromRequest`:

```rust
pub struct Context {
  pub db: &Db,
  pub hasher: &Hasher,
  pub tokeniser: &Tokeniser,
  pub user: Option<Uuid>,
}

impl<'a, 'r> FromRequest<'a, 'r> for Context<'a> {
  type Error = ();

  fn from_request(request: &'a Request<'r>) -> Outcome<Context<'a>, ()> {
    let db = request.guard::<State<Db>>()?.inner();
    let hasher = request.guard::<State<Hasher>>()?.inner();
    let tokeniser = request.guard::<State<Tokeniser>>()?.inner();
    let mut user = None;

    if let Some(token) = request.headers().get_one("Authorization") {
      match (tokeniser.verify)(token) {
        Ok(claims) => user = Some(claims.user),
        _ => return Outcome::Failure((Status::Unauthorized, ())),
      }
    }

    Outcome::Success(Context {
      db,
      hasher,
      tokeniser,
      user,
    })
  }
}
```

It's open source, so here's the [previous commit](https://github.com/WillSquire/Graphy/blob/fae5a62f7223462f4a8e1429928063ac0ebe16e2/api/src/main.rs) if helpful. The aim was to replace static strings for hashing salt and token secrets from args and this is why `Context` needs lifetimes (non-static).

**Comment by jebrosen** [comment]
Did you ever try

```rust
pub fn post_graphql_handler(
  context: Context<'_>,
  request: GraphQLRequest,
  schema: State<'_, Schema<'_>>,
) -> GraphQLResponse {
```

or maybe

```rust
pub fn post_graphql_handler<'a, 'b>(
  context: Context<'a>,
  request: GraphQLRequest,
  schema: State<Schema<'b>>,
) -> GraphQLResponse {
```

I suspect the error is either caused by or more difficult to figure out because your `Context` and `Schema` parameters contain the same lifetime, which might be an impossibility or breaks inference somehow.

**Comment by WillSquire** [comment]
No neither of these work, just get:
```
lifetime mismatch

...but data from `context` flows into `schema` here
```

Thanks, but I'm probably going to switch over to the warp framework instead, at least for the moment. Debugging macros is something I struggle with, and functional is more my style. Appreciate the help.

**Comment by jebrosen** [comment]
Wow, those lifetime relationships are a lot more complex than I realized. I will need a solid chunk of time to figure out what's going on there.

As far as I can tell, Rocket and the route macro isn't the cause of the issues but is making the error messages more confusing. If you have success with this in warp I'd be curious to see the result. There may be an easier way to do this that I'm not seeing.

**Comment by WillSquire** [comment]
Thanks @jebrosen, I have got it working now using warp and was able to simplify the usage with `Arc`. You can see it here: https://github.com/WillSquire/Graphy/blob/master/api/src/routes/graphql/mod.rs

**Comment by SergioBenitez** [comment]
Looks like we no longer need an answer to this question.
