### ISSUE TITLE
Documentation Bug on `cookies.add_private()`

### ISSUE THREAD

**Issue by jrmiller82** [SergioBenitez/Rocket#992]
The example in the documentation about how to set http-only is bad; the cookie is already setting http only by default. Also, the documentation just shows `cookies.add` instead of `cookies.add_private`, meaning the cookie the user thought was encrypted is not encrypted. 

The docs need to be cleaned up there. 

```rust
    /// Adds `cookie` to the collection. The cookie's value is encrypted with
    /// authenticated encryption assuring confidentiality, integrity, and
    /// authenticity. The cookie can later be retrieved using
    /// [`get_private`](#method.get_private) and removed using
    /// [`remove_private`](#method.remove_private).
    ///
    /// If a path is not set on `cookie`, the `"/"` path will automatically be
    /// set. If a `SameSite` attribute is not set, the attribute will be set to
    /// `Strict`. These defaults ensure maximum usability and security. For
    /// additional security, you may wish to set the `http_only` flag.
    ///
    /// # Example
    ///
    /// ```rust
    /// use rocket::http::{Cookie, Cookies};
    ///
    /// fn handler(mut cookies: Cookies) {
    ///     cookies.add_private(Cookie::new("name", "value"));
    ///
    ///     // Set the `HttpOnly` flag.
    ///     let mut cookie = Cookie::new("name", "value");
    ///     cookie.set_http_only(true);
    ///     cookies.add(cookie);
    /// }
    /// ```
```

**Comment by jebrosen** [comment]
It looks like you are reading the 0.3 docs. The current version (https://api.rocket.rs/v0.4/rocket/http/enum.Cookies.html#method.add_private) is correct as far as I can tell.

If you were reading https://api.rocket.rs/rocket/http/enum.Cookies.html, I would love to know how you got there so we can update that link.

@SergioBenitez can we do something more permanent about the not-version-tagged docs?

**Comment by SergioBenitez** [comment]
@jebrosen What did you have in mind?

**Comment by jebrosen** [comment]
Right now http://api.rocket.rs/rocket (the old link) is at the top of DuckDuckGo and 4th result on Google for "rocket api docs". http://api.rocket.rs/v0.4/rocket is 3rd place and not on page 1, respectively. Any or all of `noindex`, a redirect to https://api.rocket.rs/v0.3/rocket/, or a banner mentioning the docs are old might at least help drive down traffic there.

As it turns out, on 2018-10-26 you did try a redirect to https://api.rocket.rs/v0.3/rocket/, but it did something really weird and broken so it was reverted.

**Comment by SergioBenitez** [comment]
Now redirecting `api.rocket.rs/rocket*` to `api.rocket.rs/v0.4/rocket*`.

**Comment by jrmiller82** [comment]
My apologies all; yes, I was looking at the wrong docs. And yes, that's super confusing that the links went to an old version and not the new. I'll pay more attention to rust doc to make sure I'm reading the correct version.
