### ISSUE TITLE
Request for (or is there already) a way through the API to access managed state or a database connection outside of a Request?

### ISSUE THREAD

**Issue by jrmiller82** [SergioBenitez/Rocket#994]
I'm trying to figure out a way to access managed state / access the database that is managed by Rocket outside of a Request context or a Request Guard. I want this for two purposes: 1) scripting, and 2) I want to call some periodic functions that run regardless of a request.

I can't seem to find a way to get at State<foo> or the Database without it being inside a request. 

Thoughts? Thanks in advance.

**Comment by jebrosen** [comment]
> 1) scripting, and 2) I want to call some periodic functions that run regardless of a request.

What kind of scripting did you have in mind?

In general, Rocket is a request/response driven server. If you do want to execute periodic tasks in the background it may be appropriate to do that with a separate connection pool, or even in a separate process from the server.

Databases set up with `#[database]` are implemented as managed state, but not in a documented/stable way. The only public interfaces to it are the request guard and `ConnectionType::get_one(&rocket)` (see https://api.rocket.rs/v0.4/rocket_contrib/databases/index.html#guard-types). `get_one` is useful in `on_attach` and `on_launch` fairings, but won't help for something external.

**Comment by jrmiller82** [comment]
I understand that Rocket is primarily a request/response driven server. And I saw the Conn::get_one(&rocket) method so I can put some pre-launch scripting into a fairing. 

What I guess I don't understand is that if State<T> has to be Sync and Send, why can't I interact with it from a separate thread that's not in a request guard? Especially if T is wrapped with a RwLock or Mutex?

**Comment by jebrosen** [comment]
> why can't I interact with it from a separate thread that's not in a request guard?

Mainly because there's currently no way to get a reference to a running rocket instance to call `.state()` on it. You could create an `Arc` yourself and `.manage()` it, but it won't be integrated as nicely as the built-in database support.

**Comment by jrmiller82** [comment]
Ahhh, so you're saying get a rocket instance, wrap it in an Arc, and *then* launch the main loop. That should work great; thanks for bringing that up!

**Comment by jebrosen** [comment]
That approach won't work because `.launch()` takes ownership of the rocket instance. I meant something more like this (completely untested) code:

```rust
let shared = Arc::new(shared_thing);
let shared2 = shared.clone();
thread::start(|| {
    // use shared
})
rocket.routes(...).manage(shared2).launch();
```

Routes can access `shared2` via `State<Arc<T>>`, which will be the same instance as `shared`.

**Comment by jrmiller82** [comment]
Thank you!
