### ISSUE TITLE
Accessing a route containing invalid UTF8 is impossible

### ISSUE THREAD

**Issue by TheSilvus** [SergioBenitez/Rocket#995]
Creating a catch-all route and accessing a URL containing invalid UTF-8 (e.g. `/%80%81`) causes the request to fail (404) and an error to be printed in the console.

```
#[get("/<path..>")]
fn get(path: PathBuf) -> &'static str {
    println!("{:?}", path);
    "index"
}
```
```
GET /%80%81 text/html:
    => Matched: GET /<path..> (get)
    => Warning: Failed to parse '__rocket_param_path': Utf8(Utf8Error { valid_up_to: 0, error_len: Some(1) })
    => Outcome: Forward
    => Error: No matching routes for GET /%80%81 text/html.
    => Warning: Responding with 404 Not Found catcher.
    => Response succeeded.
```

I think this cannot be fixed using `PathBuf` as a datastructure. It would probably be better to at least allow passing the route as a `Vec<u8>` (or `&[u8]`) and make the user handle encoding problems like this.

**Comment by jebrosen** [comment]
`RawStr` exists for `FromParam`, but there's currently no equivalent for `FromSegments`. I think Rocket 0.4 even requires URIs to be UTF-8, which is one of a few deficiencies I've noticed people running into. I plan to open a comprehensive issue about this and other issues soon.

**Comment by SergioBenitez** [comment]
Let's work on this in #998.

**Comment by SergioBenitez** [comment]
I'm revisiting URI issues; what is the use-case for allowing percent-encoded characters outside of UTF-8? If raw data is being set in the URI for whatever reason, it can be encoded in a subset of UTF-8, say base64, and then decoded by a parameter or segments guard, obviating the need for percent-decoding at all.

Unfortunately, the relevant RFCs don't offer much guidance here. Other web frameworks have issues with non-ASCII paths, so I wouldn't expect them to react well to non-UTF-8 paths, but any insight here would be appreciated.
