### ISSUE TITLE
The "server" response header gets overwritten by Rocket

### ISSUE THREAD

**Issue by lu4nm3** [SergioBenitez/Rocket#996]
In my application, I make an HTTP request to a 3rd party system and then forward the response to the user. I'm using the `reqwest` library which means that I create a `rocket::response::Response` out of a `reqwest::response::Response`. As part of this conversion process, I take all of the headers from the `reqwest` response and I set them on the `rocket` response. 

The issue I'm facing is with the `server` header. When I manually set it in the Rocket Response, its value seems to get overwritten to "Rocket". For example, right before returning a response from my app, the contents of the header looks something like:
```
content-type: text/plain
accept-ranges: none
last-modified: Thu, 02 May 2019 23:39:54 GMT
content-length: 230
date: Wed, 08 May 2019 21:02:13 GMT
server: MY_VALUE
connection: close
```

However, when I inspect the headers from the client side, I see that the `server` value was overwritten:
```
< HTTP/1.1 200 OK
< content-type: text/plain
< accept-ranges: none
< last-modified: Thu, 02 May 2019 23:39:54 GMT
< Content-Length: 230
< date: Wed, 08 May 2019 21:02:13 GMT
< server: Rocket
< connection: close
```

Is there any way to disable or overcome this behavior?

**Comment by kotx** [comment]
Is it possible to remove the header entirely?
